### ISSUE TITLE
Example device registry overwrites existing config when restarting in openshift

### ISSUE THREAD

**Issue by BobClaerhout** [eclipse/hono#1007]
The init container for openshift of the device registry copies the example configuration to the configuration folder using following command: 
`cp -u /etc/examples/example-credentials.json /var/lib/hono/device-registry/credentials.json && cp -u /etc/examples/example-tenants.json /var/lib/hono/device-registry/tenants.json`.  
However, this command overwrites the existing configuration. I think this is because the configmaps (example-credentials and example-tenants) are reacreated in the pod when it starts.  
This can be solved by replacing the -u flag with the -n flag resulting in following command:
`cp -n /etc/examples/example-credentials.json /var/lib/hono/device-registry/credentials.json && cp -n /etc/examples/example-tenants.json /var/lib/hono/device-registry/tenants.json`.  
From the [cp command page](http://man7.org/linux/man-pages/man1/cp.1.html):  
- -n, --no-clobber
              do not overwrite an existing file (overrides a previous -i
              option)
- -u, --update
              copy only when the SOURCE file is newer than the destination
              file or when the destination file is missing

**Comment by ctron** [comment]
@BobClaerhout Yes, that could indeed be a problem. Would you like to create a PR for this change? If you need any help, I would walk you through the process.

**Comment by BobClaerhout** [comment]
I've created a PR: https://github.com/eclipse/hono/pull/1009

**Comment by ctron** [comment]
:+1: Thanks!

**Comment by sophokles73** [comment]
@ctron if I am not mistaken then this is fixed in 0.9, isn't it?

**Comment by ctron** [comment]
Indeed, closed in 0.9.
