### ISSUE TITLE
Add metric for rejected connections

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#1023]
The connection limit added in #931 allows to reject connection requests that exceed a configured limit. Finding the right value for a specific system will probably require some experimenting and tuning. For this purpose as well as for constant monitoring of a productive Hono installation a metric of rejected connection attempts would be helpful.

**Comment by sophokles73** [comment]
might also be related to #366

**Comment by fkaltner** [comment]
I'd like to work on this. Can you assign this issue to me?
