### ISSUE TITLE
Kubernetes deployment script fails

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#1024]
The deployment to Kubernetes using the deployment script fails with the message `no matches for kind "Route" in version "v1"`: 

```
$ bash kubernetes_deploy.sh 
DEPLOYING ECLIPSE HONO TO KUBERNETES
namespace/hono created

Creating Prometheus operator and instance
subscription.operators.coreos.com/prometheus created
serviceaccount/prometheus created
role.rbac.authorization.k8s.io/prometheus created
rolebinding.rbac.authorization.k8s.io/prometheus created
prometheus.monitoring.coreos.com/prometheus created
servicemonitor.monitoring.coreos.com/hono created
... done

Deploying Grafana ...
configmap/grafana-provisioning-datasources created
configmap/grafana-provisioning-dashboards created
configmap/grafana-dashboard-defs created
deployment.extensions/grafana created
service/grafana created
... done

Deploying Artemis broker ...
secret/hono-artemis-conf created
deployment.apps/hono-artemis created
service/hono-artemis created
... done

Deploying Qpid Dispatch Router ...
secret/hono-dispatch-router-conf created
deployment.apps/hono-dispatch-router created
service/hono-dispatch-router-ext created
service/hono-dispatch-router created
error: unable to recognize "<hono-dir>/deploy/target/deploy/resource-descriptors/dispatch-router/dispatch-router-route.yaml": no matches for kind "Route" in version "v1" 
```

**Environment:** Minikube 0.33.1, Kubernetes 1.13, Docker 18.06

**Comment by sophokles73** [comment]
The `kubectl` tool will simply ignore the failure to create the *Route* resources which are OpenShift specific. However, deployment still succeeds.

**Comment by calohmn** [comment]
> However, deployment still succeeds.

This was only the case up until beginning of January, when invocation of `common.sh` was [added](https://github.com/bsinno/hono/commit/04261a70363327b86299356804dfd5a10b31005d#diff-191110070c09a9307e3a90704a80d2f2R15). In `common.sh` there is `set -e` ("Exit immediately if a command exits with a non-zero status.") and this causes the `kubernetes_deploy.sh` script to stop at the point where a route gets deployed.

Workaround is to remove the `set -e` line in `common.sh`.

**Comment by sophokles73** [comment]
> Workaround is to remove the set -e line in common.sh.

Or remove it altogether ...
