### ISSUE TITLE
Protocol adapters should reject messages when no credit is available

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#104]
Currently, the REST and MQTT adapter both register drain handlers when they do not have enough credit to forward a message from a client. This way, the message gets forwarded as soon as the Hono server provides the adapter with some credit. We had introduced this behavior in order to prevent a somewhat odd behavior when the adapter is started up from scratch and has no link to Hono for sending e.g. telemetry data open yet.
The link creation will be triggered with the first message being uploaded to the adapter from a client. However, at that point the link has no credit yet (because it has been just opened) and so cannot immediately forward the message to the Hono server. The adpter has two options: rejecting the message from the client based on the fact that the adapter currently has no credit or (and this is what we have implemented) register a drain handler which gets notified as soon as credit is available and then sends the message to the server.

While this currently prevents the client from receiving an annoying error message when trying to send its first message, this also has some drawbacks:
1. When another request to upload a message is issued by another client and the adapter has not yet received credit, the second client gets an error (the REST adapter will return a 500 HTTP status code) and thus experiences different behavior than the first one.
2. Once the adapter gets some credit, the registered drain handler will be called back and the original message will be forwarded. However, this message might very well be quite old by the time the credit is received and there may have been multiple requests by the client in the meantime for uploading data which all will have failed. This way, we prioritize an old message over (potentially multiple) newer ones.
3. Clients (message senders) need to be prepared to handle the case where the protocol adapter has no credits (anymore) in any case. In the end, that's the whole purpose of using a protocol like AMQP which supports backpressure being pshed back to the client. Consequently, we should be able to rely on the fact that clients can handle a message being rejected by the adapter.

I therefore think that we should change the default behavior of our protocol adapters so that they *always* reject messages if they do not have credit, regardless of whether this is because the link to Hono has just been established or because the Hono server has *drained* the adapter. This way we get a consistent behavior throughout the system, even if this comes with a little inconvenience in the special case where the adapter has just been started up.

**Comment by ppatierno** [comment]
I agree on that but thinking about the MQTT adapter there is no possibility to "reject" a message considering the specification. While with HTTP it's pretty simple thanks to the request/reply nature of the protocol, we don't have such thing with MQTT. The adapter can just "drop" the message without giving any feedback to the client. For QoS 1 it means no acknowledge is sent to the client and the client could just retry. For QoS 0 the client has no idea if the packet was forwarded or not. Of course it's not a big deal because we are confirming the nature of the QoS so "at least once" delivery in the first case and "at most once" in the second case. There is only the difference with the HTTP REST adapter referring to not give a feedback to the client for a "rejected" (so dropped) message.

**Comment by sophokles73** [comment]
I had the very same thoughts this morning :-)
My original thought was that we could simply close the connection to the client if we do not have credit (telemetry use case, QoS 0). However, when I played with the `mosquitto_pub` tool, I noticed that the client had already closed its connection right after it had sent its message so that we do not get a chance to close the connection anymore. This, however, is mainly due to the nature of the command line tool being used which needs to exit, once it has sent its message anyway. However, while working on the MQTT adapter I thought that it would be very helpful to be able to determine from the server side (MQTT adapter) whether a connection with a client is still open or already closed, i.e. something like `MqttEndpoint.isOpen()` or `MqttEndpoint.isConnected()` so that we do not run into nasty exception when we close the endpoint but it has already been closed by the client. 

This whole problem will probably even exist with *real* clients instead of a command line user:
Given that MQTT has also been designed for constrained device use cases, it might be quite probable that a device wakes up, connects, sends a message, disconnects and goes to sleep again.

The MQTT spec states in section 4.8
> If the Client or Server encounters a Transient Error while processing an inbound Control Packet it MUST close the Network Connection on which it received that Control Packet [MQTT-4.8.0-2].

So, I guess this is what we should do when we experience a lack of credit. However, for this to be implemented nicely we should have a way to determine whether the endpoint is still open or has already been closed by the client.

WDYT?

**Comment by ppatierno** [comment]
I'm good to think about things more in the evening before going to sleep :-)

Before thinking about the other part ... let me just say (if you don't know) that you can use the mosquitto_pub with the -l option on the command line (not using the -m).
In this case, the mosquitto_pub client is always running waiting for message typed in the console to sender (when you press Enter). In this way you have a publisher always connected that doesn't disconnect after sending a message.

**Comment by sophokles73** [comment]
Yes, thanks for the hint regarding `mosquitto_pub`. However, I do think that most clients (constrained devices) will actually follow the *wake up, send, go to sleep* pattern ...

**Comment by sophokles73** [comment]
fixed in  8cf3aac7109c71d688fe0c7e924c5481208dc964
