### ISSUE TITLE
Add Jaeger tracing component in Docker Swarm / Kubernetes deployment

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1055]
In order to have a Hono setup for testing that includes a tracing component, it would be useful to include the [Jaeger All-in-one image](https://www.jaegertracing.io/docs/1.10/getting-started/#all-in-one) in the Docker Swarm and Kubernetes/Openshift deployment scripts.

Usage of the Jaeger component should be made optional there.

**Comment by sophokles73** [comment]
@calohmn can you close this issue?
