### ISSUE TITLE
Device Registry Integration Tests assume non-empty device registry

### ISSUE THREAD

**Issue by jbtrystram** [eclipse/hono#1056]
In the process of creating a device registry based on Infinispan for production use, I wanted to get the Hono integration tests to run against our implementation. 

The integration tests expect the DR to already hold some data, which is given in the `resources` of the test module, in JSON files.
This works well with the file based device registry since it use the same persistence mechanism. However, a third party device registry would reasonably be empty. 

I started to write some code to load the json files, similarly to how it is done in the file based registry. But this creates some code that is dedicated to the integration tests in the device registry, which hurts readability and doesn't really make sense.

Maybe we could rework the tests to have some code that "prepare" the device registry before the integration tests run, the same way it's done with the unit tests. That would reduce code duplication and also help future implementations. The downside I see with this approach is that we would have to send HTTP or AMQP messages to do that, so the preparation steps would already been into the testing territory of some sort.

@ctron take on this is a good idea imo : "maybe we can introduce some kind of "IGNORE_JSON" env-var, which would, when the container is started up, ignore the provided JSON content. so we could have an empty DR for tests, but still have a pre-filled one for demo deployments"

What do you guys think ?

**Comment by sophokles73** [comment]
We certainly started to implement the integration tests with the idea to pre-load the registry with data from files, based on the example data we use in the example deployment. However, in the meantime, and with the advent of the `DeviceRegistryHttpClient` I do not think that we actually need to do that at all. Instead, we could create the fixture (i.e. the necessary data in the registry) as part of the integration tests themselves. We are doing this in many tests already and I do not see why we shouldn't make this the general pattern.

Another question is whether we want the test cases to put the data to the registry entity-by-entity or if we want to support *bulk import* of the fixture based on JSON files. I can imagine the `DeviceRegistryHttpClient` to support both ...

**Comment by sophokles73** [comment]
@jbtrystram what's the status of this? With the recent changes you contributed, can we (i.e. you) close this issue?

**Comment by jbtrystram** [comment]
I suppose we can close it, yes !
