### ISSUE TITLE
Hono client does not call connectionHandler in case of failure

### ISSUE THREAD

**Issue by sysexcontrol** [eclipse/hono#106]
A connectionHandler that is registered with the Hono client is not called in case of a connection failure.

This can be reproduced by configuring an invalid port - the connection refused message is logged, but the handler is never called.

Expected behaviour is that the connectionHandler is called with a failed result.

**Comment by sophokles73** [comment]
Fixed in 32bb0fdf17d18270227e7684ad407b0419dab287
