### ISSUE TITLE
Remove Registration of Device 4711 from Getting Started Guide

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#1064]
The device 4711 is widely used throughout the documentation and comes with a couple of predefined configurations. The only thing that is missing is the registration of the device. This is expected to be done by the user when following the steps in the "Getting started" guide. It feels not consistent that I have to register the device, while I don't have to create credentials for it. This inconsistency makes it harder to understand which configuration steps are necessary before I can send data.
The ugly side effect is that the examples in the "User Guide" implicitly require that one had previously followed the "Getting started" guide and registered the device.

**Proposal**
1. Add the existing file `example-device-identities.json` to the example deployment of the device registry.
1. Either: 
    * Remove the topic "Device Registration" from the "Getting started" guide 
    * **Or:** add a separate section that explains configuration steps like registering a device, creating credentials and maybe even creating a new tenant. Use a new device name for this section.

**Comment by sophokles73** [comment]
We keep the example devices and credentials in the example deployment. However, the Getting Started guide now lets the user create a new tenant, register a device and credentials as part of the guide.

Fixed via b08a16ca9f07dd7a25533064e606af462c74d881
