### ISSUE TITLE
[User Guide] Examples for AMQP are broken

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#1067]
The examples for AMQP in the User Guide are broken. E.g.:

`$ /hono/cli/target$ java -jar hono-cli-0.7-SNAPSHOT-exec.jar --spring.profiles.active=amqp-adapter-cli --message.address=event --payload='{"alarm": 1}'`

Here `--payload` needs to be `--message.payload`. 

And in

`$ /hono/cli/target$ java -jar hono-cli-0.7-SNAPSHOT-exec.jar --spring.profiles.active=amqp-adapter-cli --username="" --password=""` 

the arguments `username` and `password` need to be prefixed with `hono.client.`

Furthermore the application does not start with empty username or password.

**Comment by sophokles73** [comment]
@b-abel thanks for reporting,a re you going to create a PR to fix it?

**Comment by b-abel** [comment]
Sure, I can do this together with #1066. But I won't probably have time for this before end of the week.

**Comment by sophokles73** [comment]
@b-abel no worries, I have already done it ...
