### ISSUE TITLE
Client context entries are pruned from a credential creation request.

### ISSUE THREAD

**Issue by jbtrystram** [eclipse/hono#1070]
When a request to create credentials containing some client context (i.e. additional properties) is forwarded to the device registry, hose extra properties are pruned during the various checks. 
This leads to the device registry receiving the credential creation request without any additional properties.

**Comment by sophokles73** [comment]
The problem seems to be that the `CredentialsObject` to which the payload is mapped as part of processing the request, ignores any such additional properties.
