### ISSUE TITLE
Align main Application class names

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#1074]
The current situtation:

* `org.eclipse.hono.adapter.amqp.Application`
* `org.eclipse.hono.adapter.coap.vertx.Application`
* `org.eclipse.hono.adapter.http.vertx.Application`
* `org.eclipse.hono.adapter.mqtt.impl.Application`

I think we should align this.

**Comment by calohmn** [comment]
Commit where the Http adapter `Application` was moved to the `vertx` package: https://github.com/eclipse/hono/commit/19011f6c5c491fcae4df28f24ac4982d557e4606.
There were Eclipse jar-signer conflicts before.

**Comment by ctron** [comment]
Maybe then align that all to `org.eclipse.hono.adapter.<foo>.impl.Application`?!

**Comment by sophokles73** [comment]
@ctron can we (you) close this?
