### ISSUE TITLE
Remove all remaining references to Hono Messaging

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1079]
The `Hono Messaging` component has been removed in #1004.

However, there are still some references in the codebase where it is mentioned.
These places should be changed accordingly.

**Comment by sophokles73** [comment]
can you give some examples?

**Comment by calohmn** [comment]
E.g. here:

https://github.com/eclipse/hono/blob/04b6eda40ebd963ffa363fd912d7bf730445fbe7/service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java#L178

I would rather use `Messaging Network` here - as this term is also used in the documentation.
