### ISSUE TITLE
Use consistent format for paths in documentation.

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#1083]
Currently there are several file paths in command line promts in the documentation used in in different formats.It would be helpful if this is unified.

Found variants:
* `~/hono$`
* `~hono/deploy$`
* `$ /hono/cli/target$`
* `~/hono/services/device-registry $`
* No file path given, even if the command depends on it

**Comment by b-abel** [comment]
**Proposal**

* Always add path to the command prompt, if the command depends on it.
* Always assume that the project base directory is `~/hono`
* Always use a valid file path (invalid is e.g. `~hono`) and no dollar signs in front of the path in command prompt

**Comment by b-abel** [comment]
> Having the prompt in the start of each line however means that you cannot copy & past multiple lines. 

Absolutely. This annoys me regularly.

> So I would propose to simple ignore the prompt.

One downside with this for me is that the prompt in front of a line is a convention that makes it easy to read the documentation and instantly know the context (it's a shell command, in this directory, with normal user privileges). 

> I like the idea assuming that the base directory is the base directory of the Hono repository. And that we either prefix commands with their relative paths inside the repo, or add the `cd` commands to the description as well.

Relative paths only defer the problem. Every time you copy a command you need to know in which directory it can be executed. In the documentation are ~100 commands that depend on a certain path spread over ~20 files (or HTML pages). Consequently we had to add a `cd` line to every of those snippets, even the one-liners.
Alternatively we could of course make the base directory a convention and skip it for the individual code snippets. But for me this does not fit the way I use this documentation. I do not read the User Guide and especially the Admin Guide completely, but rather to look up specific information. For this it is really helpful to have the full context a hand and do not have to remember conventions or perform additional actions.

**Comment by ctron** [comment]
> For this it is really helpful to have the full context a hand and do not have to remember conventions or perform additional actions.

But having the full path inside the repository would exactly achieve that … for a one-liner you would have the full relative path (e.g. `oc create -f deploy/okd/manifests/latest/`) and for a bigger block, and additional `cd` does hurt too much I think.

I only fear that the documentation will look like this:

~~~
$ git clone https://github.com/operator-framework/operator-lifecycle-manager
$ oc login -u admin
$ oc new-project operator-lifecycle-manager
~/hono/operator-lifecycle-manager/deploy/okd/manifests/latest/ $ oc create -f .
$ oc login -u developer
~~~

**Comment by b-abel** [comment]
Your example is special because the `git clone` creates the context :-)

My example would be:

```bash
~/hono/demo-certs/certs$ mosquitto_pub -p 8883 -t telemetry -m '{"temp": 5}' --cert device-4711-cert.pem --key device-4711-key.pem --cafile trusted-certs.pem
```

Would this become something like that?

```bash
# relative to the base directory of the Hono repository
cd ./demo-certs/certs
mosquitto_pub -p 8883 -t telemetry -m '{"temp": 5}' --cert device-4711-cert.pem --key device-4711-key.pem --cafile trusted-certs.pem
```

**Comment by b-abel** [comment]
I would like to think about this topic with another perspective: What are our goals and how do we prioritize them?

My priorities have the following order:

1. Copy & paste with minimal effort
2. Always know the context
3. Short and easy to understand
4. Consistent notation

With this priority order the solution is probably not to have one schema for every place in the documentation. Instead we could say:

* Code blocks with than one or two lines have no prompt in front, provide their context and contain `cd` commands where necessary (maybe even variables in front when individual configuration is necessary).   
Most important is that the block can be copied at once.
* One line commands can provide the path in the prompt. If I only copy one line, it is no problem to start copying after the prompt
* Walk-through documentation with multiple code blocks do not need to provide the context repeatedly for every block, but focus on easy copy & paste workflow. On the other hand, example commands, e.g. in the Admin Guide, that are used to lookup a command need to provide context at hand.


**WDYT?**

**Comment by ctron** [comment]
I would think more like:

~~~
mosquitto_pub -p 8883 -t telemetry -m '{"temp": 5}' --cert demo-certs/certs/device-4711-cert.pem --key device-4711-key.pem --cafile demo-certs/certs/trusted-certs.pem
~~~

**Comment by ctron** [comment]
Maybe it would be good to pick one section and make an example … for everyone to have a look. Or if we already have that, simple post a link.

**Comment by b-abel** [comment]
> I would think more like:
> 
> ```
> mosquitto_pub -p 8883 -t telemetry -m '{"temp": 5}' --cert demo-certs/certs/device-4711-cert.pem --key device-4711-key.pem --cafile demo-certs/certs/trusted-certs.pem
> ```

Maybe that wasn't a good example either :-) 
But still, the base directory is be completely implicit with this and the reader needs to figure out the context before pasting the command into the shell.
Do you mind adding (initial) path information where necessary in a comment? Like e.g.: 

```sh
# run from: hono/example/
mvn exec:java -Dexec.mainClass=org.eclipse.hono.vertx.example.HonoExampleApplication
```

This is short, doesn't disturb copy & paste and IMHO ticks the "Don't make me think" box.

**Comment by sophokles73** [comment]
@b-abel can we (you) close this?
