### ISSUE TITLE
Clarify use-case of hono-example module

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1084]
The Hono developer guide contains a page about the `hono-example` module:
https://www.eclipse.org/hono/dev-guide/java_client_sender/

The `HonoEventSender` and `HonoTelemetrySender` classes in this module send messages directly to the AMQP Messaging network. In this sense these classes represent potential parts of a custom protocol adapter.

However, the webpage in the documentation doesn't make this clear, IMHO.

Someone (not paying attention to the fact that the page appears in the developer guide) could think this is the way to send messages via AMQP to Hono, ie. as part of a device sending messages to Hono.
But such a case (where communication would have to target the AMQP adapter, not the AMQP Messaging network) is not meant here.

I think the documentation (in the webpage and the maven module) should be improved here in this regard.

**Comment by sophokles73** [comment]
So, which case is/should be targeted? IMHO the page stems from times where we still considered allowing devices to connect to Hono Messaging directly using AMQP. However, as you correctly point out, this is no longer the case but we would rather have devices connect to the AMQP protocol adapter instead. So it would probably make sense to adapt the page to reflect this use case, right?

**Comment by calohmn** [comment]
As for connecting devices to the AMQP protocol adapter, I think the [AMQP Adapter page](https://www.eclipse.org/hono/user-guide/amqp-adapter/) in the user guide should be the place where corresponding examples should be put. The Hono CLI example there (with its `AmqpSend` class) could already serve as a simple Java example. In that sense, adding a further example for a java-based sender with the `hono-example` module there wouldn't offer much added information.

On the other hand, thinking about the developer guide and how to offer help for handling the AMQP communication in a custom protocol adapter, the `hono-example` module wouldn't be of much relevance I think. Of course it shows the basics of using the `HonoClient`, but in practice, one would (and should) use the existing methods of the `AbstractProtocolAdapterBase` class instead.

Therefore, maybe better remove the `java_client_sender` dev-guide page and the sender classes of the `hono-example` module altogether in order to avoid confusion.
We could rename the `hono-example` module to `hono-example-consumer` then and have it only serve a single purpose.

**Comment by sophokles73** [comment]
The sender example might, however, make sense in the context of sending (one-way) commands.

**Comment by calohmn** [comment]
Ok, right. However that is integrated in the `HonoExampleApplicationBase` and already documented in the `Consuming Messages from Java` dev-guide page.
Renaming the `hono-example` module to `hono-example-application` would make more sense then.

The `java_client_sender` dev-guide page and the sender classes of the `hono-example` module I would still consider obsolete.

**Comment by sophokles73** [comment]
I'd rather keep the name of the module since we might want to add other examples to it in the future as well. I have no problem with removing the `java_sender_client* page, though. We will definitely need to revise the page covering the development of a custom protocol adapter.
