### ISSUE TITLE
Update qdrouterd-base image version

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1087]
The *qdrouterd-base* image should be updated to a version that contains fixes for:
- https://issues.apache.org/jira/browse/DISPATCH-1273 
("'to' field not authorized against valid targets for anonymous sender")
- https://issues.apache.org/jira/browse/DISPATCH-1287 (see #1026)

**Comment by sophokles73** [comment]
I have created a CQ for Dispatch Router 1.6.0 which seems to fix both of these issues.
