### ISSUE TITLE
no matches for kind "Route" in version "v1"

### ISSUE THREAD

**Issue by alexju88** [eclipse/hono#1091]
**Hi guys,
We tried to deploy hono in kubernetes with script kubernetes_deploy.sh, but when we try to deploy hono-adapter-kura with command "kubectl create -f $RESOURCES/hono-adapter-kura --namespace $NS", we failed, the error is as below:**

unable to recognize "/opt/hono/install/target/deploy/resource-descriptors/hono-adapter-kura/hono-adapter-kura-route.yaml": no matches for kind "Route" in version "v1"

**And we checked the status of pod, the event is as below:**

Unable to mount volumes for pod "hono-adapter-kura-6c9964f79f-vctd6_hono-test(2b309d2e-494d-11e9-aea4-fa163ec16f5b)": timeout expired waiting for volumes to attach or mount for pod "hono-test"/"hono-adapter-kura-6c9964f79f-vctd6". list of unmounted volumes=[conf]. list of unattached volumes=[conf default-token-dvzdf]

MountVolume.SetUp failed for volume "conf" : secrets "hono-adapter-kura-conf" not found

**I checked this repo's issues , it seems that the "kind: Route" is only special set for OpenShift, for common Kubernetes, How should I changed ? 
And, for the unmounted volume problem, is it caused by above failure?**

Thanks!**

**Comment by calohmn** [comment]
About the `no matches for kind "Route"` error:
workaround for that is to edit `common.sh` (in the same directory as `kubernetes_deploy.sh`) and remove the `set -e` line there (see #1024).

Note that in general the script based deployment is deprecated as of Hono 0.9. Alternative would be to use the Helm based deployment.

As for the `Unable to mount volumes for pod` error: I don't think it's related to the above issue.
In general, I cannot reproduce that error, maybe it's a timing issue.
Did this problem persist? Or did it resolve itself when Kubernetes again tried to start the Pod?

**Comment by alexju88** [comment]
> 
> 
> About the `no matches for kind "Route"` error:
> workaround for that is to edit `common.sh` (in the same directory as `kubernetes_deploy.sh`) and remove the `set -e` line there (see #1024).
> 
> Note that in general the script based deployment is deprecated as of Hono 0.9. Alternative would be to use the Helm based deployment.
> 
> As for the `Unable to mount volumes for pod` error: I don't think it's related to the above issue.
> In general, I cannot reproduce that error, maybe it's a timing issue.
> Did this problem persist? Or did it resolve itself when Kubernetes again tried to start the Pod?

Yes ,  this problem persist. I have deleted old pod and start a new one, but not help.
Still mounting volume problem..

**Comment by calohmn** [comment]
Does the secret `hono-adapter-kura-conf` exist in the namespace you are using?
Did the other protocol adapter pods start up ok?
In general you could try running `kubernetes_undeploy.sh` (or deleting the namespace you were using manually) and then running the deployment again - in order to make sure there are no issues because of leftover artefacts from a previous, incomplete deployment run.
