### ISSUE TITLE
no matches for kind "Prometheus" in version "monitoring.coreos.com/v1"

### ISSUE THREAD

**Issue by gongzhao1** [eclipse/hono#1099]
Hey, We try to use helm to deploy hono on kubernetes cluster, But I got this error as follows.

`[root@test helm]# helm install --dep-up --name eclipse-hono --namespace hono .`

`
Error: validation failed: [unable to recognize "": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"]
`

My kubernetes version is 1.11.3, docker version is 17.06 and hono version is 0.9.
Thanks!

**Comment by sophokles73** [comment]
I have tried to reproduce the issue towards a local minikube running kubernetes 1.11.3. I am not able to deploy using helm but due to another problem:
```
Downloading prometheus-operator from repo https://kubernetes-charts.storage.googleapis.com
Deleting outdated charts
Error: release eclipse-hono failed: Secret in version "v1" cannot be handled as a Secret: v1.Secret.ObjectMeta: v1.ObjectMeta.Labels: ReadString: expects " or n, but found 0, error found in #10 byte of ...|version":0.9},"name"|..., bigger context ...|age":"Tiller","release":"eclipse-hono","version":0.9},"name":"hono-artemis-conf","namespace":"hono"}|...
```
I suspect that a newer version of kubernetes is required for the Prometheus operator to be deployed successfully. In any case, are you able to use a more recent version, e.g. 1.13.x?

**Comment by sophokles73** [comment]
Ok, it seems that we have the same bug in the Helm templates for 0.9 as we did in #491, i.e. the version (0.9) that is used as a label is misinterpreted as a number because it is not put in quotes.

This problem will not occur when running the Helm deployment from master (because the version there is usually something like `0.x-SNAPSHOT` which is interpreted as a string instead of a number).

In order to use the Helm templates that are part of the 0.9 download archive, the following command needs to be run before running `helm install`:
```
~/eclipse-hono-deploy-0.9/deploy$ for NAME in $(find helm/templates -name *.y*ml); do sed -i -E -e 's/^(\s*version\:\s*)(.. \.Chart\.AppVersion ..)/\1"\2"/' $NAME; done
```
this will replace all occurrences of the `0.9` version label with `"0.9"`.

I have then been able to deploy using Helm on a local minikube cluster running kubernetes 1.11.3.

**Comment by gongzhao1** [comment]
Yes, I also found `version: 0.9`  error.
I tried to deploy with helm, but it always reported the error I mentioned above.
I think its my kubernetes cluster(Public cloud) does not have this API, maybe I should create it?
`apiVersion: monitoring.coreos.com/v1`
`kind: ServiceMonitor`

So I execute `helm template --name eclipse-hono --namespace hono --output-dir . target/deploy/helm/`, and trying to deploy manually without prometheus.
I found that pod status are abnormal. just like the picture.
<img width="544" alt="2019-03-20_21h57_01" src="https://user-images.githubusercontent.com/34536820/54689831-2d8f8b80-4b5b-11e9-9668-857a2e191c98.png">
So I comment its yaml file `livenessProbe` and `readnessProbe` then the pod turn into ready.

And I also find that `hono-service-device-registry`  need a PersistentVolume, Otherwise it is always pending status. So I create a PV for it.

About the "How to create prometheus". I would be very grateful if someone can help me.

**Comment by sophokles73** [comment]
Are you sure that your cluster meets all the requirements for the Prometheus Operator as described here: https://github.com/helm/charts/tree/master/stable/prometheus-operator ?

Have you deployed Helm's *Tiller* service to your kubernetes cluster using
```
$ helm init
```
before you tried to install the Hono chart?

**Comment by sophokles73** [comment]
@gongzhao1 any news on this?

**Comment by gongzhao1** [comment]
Hi Hudalla,
Sorry for reply late, I have been try to deploy Hono on my cluster these days.
I also try to use helm deploy hono:0.9 on my minikube. And it running well.
So I guess the public cloud provider's kubernetes cluster is somewhat different from the native one.

And I deploy it manually, But when I uploading Telemetry Data using the HTTP Adapter, I always return  `HTTP/1.1 401 Unauthorized`.
So I checked Http-adapter logs.
`07:24:44.523 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - can't connect to AMQP 1.0 container [amqps://hono-service-device-registry.hono:5671]: connection timed out: hono-service-device-registry.hono.svc.cluster.local/10.247.169.77:5671
07:24:44.523 [vert.x-eventloop-thread-0] DEBUG o.e.hono.client.impl.HonoClientImpl - connection attempt failed
io.netty.channel.ConnectTimeoutException: connection timed out: hono-service-device-registry.hono.svc.cluster.local/10.247.169.77:5671
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

It seems that the adapter can not connect with device registry.
there are my k8s cluster pods and services list
<img width="856" alt="2019-03-22_17h54_15" src="https://user-images.githubusercontent.com/34536820/54815303-9ea28080-4ccc-11e9-8d90-f2322186ad0f.png">

My kubernetes version is 1.11.3, and hono version is 0.9.
And I wondering if it is feasible to migrate the hoto on the minikube to my cluster.

**Comment by sophokles73** [comment]
I am confused now. Are you deploying to a local minikube or to a kubernetes cluster?

**Comment by gongzhao1** [comment]
Sorry, I didn’t describe it clearly.
I need to deploy hono on my public cloud k8s cluster
So I execute `helm template --name eclipse-hono --namespace hono --output-dir . target/deploy/helm/`, and trying to deploy manually without prometheus(using `kubectl create`).
But I have encountered the above error.
Maybe something is wrong with my deploy. I will check my deploy this weekend, After that I will close or update this issue.

**Comment by gongzhao1** [comment]
I have successfully deployed hono on my kubernetes cluster. (The prometheus cluster in my environment caused the prometheus of hono to fail to start, So I deployed hono with a clean cluster. )
And In summary:
Deploy `hono:0.9` on kubernetes by using helm only have one bug #491.

Thanks, Hudalla.
Then I will do some test about hono, If I got any problems, I will report my issue.
