### ISSUE TITLE
AMQP application properties of command response are not accessible with CommandClient

### ISSUE THREAD

**Issue by DanielMaier-BSI** [eclipse/hono#1100]
With #958 device-id and tenant-id was added to command response application properties. However these properties cannot be accessed with `CommandClient` because it returns only the command response payload.

**Comment by sophokles73** [comment]
The application properties can be retrieved using the `BufferResult.getApplicationProperty()` method.

**Comment by DanielMaier-BSI** [comment]
Sorry, I didn't expect this from the class name. I can confirm that it works as expected :).
