### ISSUE TITLE
Create an official HTTP API for the device registry

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#1102]
Currently the Device Registry HTTP API is more an internal hack, than a supported version. We would like to change that and provide a proper HTTP API, which can be used by people to build their solution on top. Ideally it should be close to the existing one, but also consider things like authentication.

**Comment by Alfusainey** [comment]
@ctron did you already started working on this? if not, can i take look?

**Comment by ctron** [comment]
Yes, I started to work a little bit on this. My idea was to take the current API and create a OpenAPI definition of this. However I have nothing to share yet. if you want to look I can try prepare something for you by the end of the day.

**Comment by Alfusainey** [comment]
> if you want to look I can try prepare something for you by the end of the day.

Sure, that would be nice

**Comment by ctron** [comment]
I pushed an initial version: https://github.com/eclipse/hono/pull/1130

**Comment by sophokles73** [comment]
@ctron is this done with the OpenAPI spec included in 1.0-M4? Or does this issue also cover the implementation?

**Comment by ctron** [comment]
I would see the actual implementation as part of this issue as well.
