### ISSUE TITLE
Fix cache handling in RegistrationClientImpl (concerning multiple gateways)

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1103]
Relates to #930, #1093:
In order to support the scenario of a device connecting via different gateways (not at the same time but alternating between gateways), the caching logic concerning `assertRegistration` requests has to be adapted.

Scenario:
- device `dev-A` connects via gateway `gw-1` => no cache hit, assertRegistration is invoked (last-via is updated), new cache entry with key `(assert, dev-A, gw-1)` is created
- device `dev-A` connects via gateway `gw-2` => no cache hit, assertRegistration is invoked (last-via is updated), new cache entry with key `(assert, dev-A, gw-2)` is created
- device `dev-A` again connects via gateway `gw-1` => **cache hit** => assertRegistration is NOT invoked and last-via is NOT updated - that is an error

Possible solution:
When writing the cache entry `(assert, dev-A, gw-2)` above, we have to delete all other cache entries concerning `assert` and `dev-A`.

EDIT: We shouldn't cache `RegistrationResult` objects representing devices with multiple `via` entries at all (see below).

**Comment by calohmn** [comment]
Another possible solution: 
Use only `(assert, $deviceId)` as cache key in `RegistrationClientImpl.assertRegistration`.
When having a cache hit, check the cache value and the `last-via` gateway id in it. If it differs from the gateway id used in the request, retrieve the current registration information from the RegistrationService and update the cache entry.

**Comment by BobClaerhout** [comment]
I'm not familiar with the assertRegistration but if it can be compared with a database table I think I would create a table where the DeviceId would be the primary key of that table. If this assumption is correct, I would rather go for the second solution.
On the other hand: is it really needed to check if the id is the same, can't you  just always update the cache entry or is the update an expensive operation?

**Comment by calohmn** [comment]
Yes, the second solution is probably more straightforward.

> is it really needed to check if the id is the same, can't you just always update the cache entry or is the update an expensive operation?

Updating the cache entry is not enough, we have to do the remote call to the Registration Service and have the `last-via` property be updated in the device registry that way.
In order not to do that unnecessarily, the gateway id is checked. At least that was my initial idea.

But, thinking further about this, for devices with multiple `via` entries, I think we **always** have to do the remote call and update the `last-via` property in the device registry, because there could be multiple protocol adapter instances involved.
An example:
- device `dev-A` connects via gateway `gw-1` to protocol adapter instance `http-1` => no cache hit, assertRegistration is invoked, last-via is set to `gw-1`
- device `dev-A` connects via gateway `gw-2` to _another_ protocol adapter instance `http-2` => no cache hit, assertRegistration is invoked, last-via is set to `gw-2`
- device `dev-A` connects via gateway `gw-1` to protocol adapter instance `http-1` => regardless of cache content, remote call has to be done in order to set last-via to `gw-1`

**Comment by BobClaerhout** [comment]
> An example:
> 
> - device dev-A connects via gateway gw-1 to protocol adapter instance http-1 => no cache hit, assertRegistration is invoked, last-via is set to gw-1
> - device dev-A connects via gateway gw-2 to another protocol adapter instance http-2 => no cache hit, assertRegistration is invoked, last-via is set to gw-2
> - device dev-A connects via gateway gw-1 to protocol adapter instance http-1 => regardless of cache content, remote call has to be done in order to set last-via to gw-1

I think you have to assume that your cache is always out of sync. At the second action, `dev-A` connects via gateway `gw-2` you will have to perform a remote call as well. I think the local cache is a rather dangerous concept in this case. The master of this data should be the device registry (and there will always be just one device registry, if not a syncing mechanism should be added here as well). So I propose to always request the data from the device registry and update the data in the device registry instead of keeping a local cache. This does not have to block the normal flow as it can be updated after the telemetry or event data is sent to the AMQP broker.

**Comment by sophokles73** [comment]
The device registry implementation can control the caching behavior in the adapters by means of the *caching policy* which is included in all responses to *assert Registration*. The registry could, e.g. use the *no cache* policy for devices that are allowed to connect via multiple gateways and use the normal cache policy for devices that are only allowed to connect via a single gateway (or none at all).
