### ISSUE TITLE
New Theme for the Homepage

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#1109]
On the occasion of the release of version 1.0 the homepage could get some love. 
A new theme should provide a search feature and a fresh look and feel.

Related tasks are:
* a new landing page
* restructuring of the menu
* a FAQ (#1035)

**Comment by b-abel** [comment]
The PR #1108 is one idea based on the theme [DocDock](https://themes.gohugo.io/docdock/). I am working on another one with the (quite similar) theme [Learn](https://github.com/matcornic/hugo-theme-learn/).

**Comment by jbtrystram** [comment]
The main feature I miss on the website is an index when navigating the API resources :) Is that difficult to add ? It would be a nice addition !

**Comment by sophokles73** [comment]
+1 for having a search field and a better navigation bar that supports > 2 levels ...

**Comment by kaniyan** [comment]
Also 👍  for the search feature.

**Comment by kaniyan** [comment]
I tried out `bsinno:PR/site_theme_learn` and `bsinno:PR/site_theme_docdock`. Both looks good. I like the theme `learn` more that the `docbook`. 

The icons in learn `looks` cool. In `docbook`, I found that the navigation from one page to another is not smooth as `learn`.
Example:  It takes some seconds for correct rendering of code highlights. Check the below 2 images. 

![image](https://user-images.githubusercontent.com/18659982/55091825-c9684c80-50b1-11e9-91ba-48980b5ed9c3.png)


![image](https://user-images.githubusercontent.com/18659982/55091965-046a8000-50b2-11e9-8385-1cdf3fe78025.png)

**Comment by b-abel** [comment]
## Differences between themes *DocDock* and *Learn*

DocDock is a fork of Learn. And a couple of additions in DocDock went back into Learn. So the differences are in detail (apart from features that we don't use, e.g. you can create revealJS presentations from DocDock). 

DocDock provides "**excerpts**", that is the generated overview page for each content folder. The current Hono homepage uses this. But until now nobody insisted on keeping that and I would prefer to have an `_index.md` in each content folder with an explicit descriptive text.
DocDock provides support for a custom footer, in Learn we need to add that by ourselves.

**Visually**, there are details in the styling of the sidebar and the fonts. 

**Technically**: Learn provides a simple mechanism to customize colors. 

**Common**: Things that are IMO easy to adjust on both themes are colors and icons.

**Community**: Learn seems to be more actively developed.

**Comment by sophokles73** [comment]
@b-abel I think we can consider this fixed and close the issue. All remaining changes are basically improvements of the existing content but are not related to changing the theme, right?

WDYT?

**Comment by b-abel** [comment]
> @b-abel I think we can consider this fixed and close the issue. All remaining changes are basically improvements of the existing content but are not related to changing the theme, right?
> 
> WDYT?

I agree.
