### ISSUE TITLE
Move initialization logic from Application class into hono-server module

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#113]
In order to allow creating own hono springboot applications (with adapted configurations / added components) without duplicated code, the hono Application class should be changed so that (springboot-independent) initialization logic is moved into the hono-server module.

**Comment by calohmn** [comment]
I think the straightforward thing to do would be 
- copying the Application class to hono-server, renaming it to HonoApplication, and removing the main() method and replacing class annotations to just have @Component
- removing all methods/fields from the Application class, keeping only the main() method

**Comment by sophokles73** [comment]
Maybe you can create a PR for it so that we can discuss?

**Comment by calohmn** [comment]
I have created #115 for that.

**Comment by sophokles73** [comment]
resolved in fd55211f926be208400b49dee9bf3bf5c7e6bb53
