### ISSUE TITLE
Adding docker push to maven build

### ISSUE THREAD

**Issue by BobClaerhout** [eclipse/hono#1136]
I'm using my own docker registry where I'm getting my docker containers from. When building the original hono project, I'm pushing the resulting containers to this registry. To automate this, I'm using our gitlab ci to do this. Currently hono is pushed to docker using the docker commands, however it is also possible to do this in the maven build using following build profile:
```
<profile>
      <id>docker-push-image</id>
      <build>
          <plugins>
              <plugin>
                  <groupId>io.fabric8</groupId>
                  <artifactId>docker-maven-plugin</artifactId>
                  <executions>
                      <execution>
                          <id>docker-push-image</id>
                          <phase>install</phase>
                          <goals>
                              <goal>push</goal>
                          </goals>
                      </execution>
                  </executions>
              </plugin>
          </plugins>
      </build>
  </profile>
```
This is just something additional which can be used to create your own automated CI builds.
If you add a proper name:
```xml
<name>
     ${docker.repository}/${project.artifactId}:${project.version}
</name>
```
and the ability to add an extra tag:
```xml
<tags>
     <tag>${docker.image.additional.tag}</tag>
</tags>
```
this is very flexible towards custom builds.

The result is only one command which builds and pushes the images:
`mvn clean install -Ddocker.host=host:2375 -Pbuild-docker-image,metrics-prometheus -Pdocker-push-image -Ddocker.registry=registry.gitlab.com -Ddocker.repository=registry.gitlab.com/aloxy/hono -Ddocker.image.additional.tag=testing -Ddocker.push.username=gitlab-ci-token -Ddocker.push.password=verysecret`

WDYT?

**Comment by sophokles73** [comment]
From the perspective of a user doing a custom build I can see the value. We would need to adapt the image name to also include a registry name, I guess. The repository name can already be set using a Maven property, e.g. in order to use `aloxy` instead of `eclipse`. Why don't you create a PR and we can continue to discuss there ...
