### ISSUE TITLE
Device registry doesn't provide CORS headers

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#1138]
The current HTTP endpoint of the device registry does not provide CORS headers. Which makes it rather difficult to work with under some circumstances.

**Comment by sophokles73** [comment]
In particular, it means that we cannot use the Swagger UI to directly access the Sandbox registry, which would be great.
It would also allow us to get rid of the (ugly) Heroku CORS proxy in the OpenAPI spec file.

**Comment by dejanb** [comment]
Fixed
