### ISSUE TITLE
Concurrency issue while authenticating devices with SHA encoded passwords

### ISSUE THREAD

**Issue by DanielMaier-BSI** [eclipse/hono#1170]
`MessageDigestPasswordEncoder` is not thread-safe as it uses the same `MessageDigest` instance for all `matches()` calls. However since `UsernamePasswordAuthProvider` executes password check within different threads this leads to wrong results and thus to failed device authentications. 

Possible solutions might be
- Use new `MessageDigest` instance for every request
- Use separate `MessageDigest` instance per thread
- Add some locking to `matches()`

If creating of `MessageDigest` is not an expensive operation option 1 should be easy and legit to implement.

WDYT?

**Comment by sophokles73** [comment]
That indeed seems to be a problem. Thanks for reporting :+1: 

Creating a `MessageDigest` instance shouldn't be a problem. The time consuming part is invoking the *digest* operation where the hash is computed.
So, option 1 should be fine FMPOV.

Do you want to create a PR?

**Comment by DanielMaier-BSI** [comment]
As I have a setup to reproduce this and as we agree on option 1 I will provide a PR shortly.
