### ISSUE TITLE
Namespace bug

### ISSUE THREAD

**Issue by alexju88** [eclipse/hono#1176]
If we do not use default namespace "hono", then the scripts (helm + kubernetes) need to be changed to use ENV value, and certificates in "config" folder also need to re-produced again.  So that new certificates can be used for _hostname.Newnamespace_

Would you please tell me how to produce certificates quickly for new namespace and new hostname?

**Comment by sophokles73** [comment]
you should be able to make the necessary adjustments in the `ca_opts` file in the `demo-certs` folder. After you have made the desired changes, run the `create_certs.sh` script in the same folder. This will re-create all keys and certificates in the `demo-certs/certs` folder.

**Comment by sophokles73** [comment]
@alexju88 is this still an issue or can you close it?

**Comment by alexju88** [comment]
> 
> 
> @alexju88 is this still an issue or can you close it?

Sorry, I forgot to reply this issue, it works! thank you very much!
