### ISSUE TITLE
Internal server error when sending malformed authentication header

### ISSUE THREAD

**Issue by mbaeuerle** [eclipse/hono#1183]
When sending a malformed Authentication header like "Authentication: basic test test" Hono responds with a 500 and with an error message "Illegal base64 character 20" which I suppose is from the thrown Exception.

**Examples**
``` sh
curl -X POST \
  http://hono.eclipse.org:8080/event \
  -H 'Authorization: basic test test' \
  -H 'Content-Type: application/json' \
  -H 'cache-control: no-cache' \
  -d '{ "test-data": "3" }'
```
Response:
> Status 500: Last unit does not have enough valid bits

``` sh
curl -X POST \
  http://hono.eclipse.org:8080/event \
  -H 'Authorization: basic testtest1' \
  -H 'Content-Type: application/json' \
  -H 'cache-control: no-cache'
  -d '{ "test-data": "3" }'
```
Response:
> Status 500: Last unit does not have enough valid bits

**Expected behavior**
- Status either 400 or 422
- Meaningful error message like: `Authorization Header malformed`

**Comment by sophokles73** [comment]
FMPOV this should result in a 400 because the request does not fail due to a problem with the data in the body but cannot be processed due a problem in an earlier stage (where the body's content is of no concern yet).

**Comment by kaniyan** [comment]
@sophokles73 IMHO this should be fixed in _vertx_ (`BasicAuthHandlerImpl`). The PR #1194 fixes this issue in _Hono_ by using a `RoutingContextDecorator`.

**Comment by sophokles73** [comment]
fixed in https://github.com/eclipse/hono/commit/5e5735f5b4ff89b5e896298c3d264d9b7f187636
