### ISSUE TITLE
LoRaWAN adapter passes payload encoded base64

### ISSUE THREAD

**Issue by BobClaerhout** [eclipse/hono#1191]
The LoRaWAN adapter encodes all payload. Can someone tell me why this is the case? I would rather have this acting the same way as all adapters and not changing the data at all.

**Comment by sophokles73** [comment]
@DanielMaier-BSI @mbaeuerle any thoughts?

**Comment by DanielMaier-BSI** [comment]
This was done to have the same encoding for all providers, i.e. applications don't have to care which provider sent the data.

**Comment by BobClaerhout** [comment]
Ok, if #1199 is merged we can always get the original payload from the original message.
