### ISSUE TITLE
Using GitBooks to maintain Hono documentation

### ISSUE THREAD

**Issue by hekonsek** [eclipse/hono#12]
Hi,

What do you think about using GitBooks to maintain our documentation? It is based on GitHub markdown, but allows you to align the documentation nicely in a form of a book. For example [1].

What do you think?

[1] https://rhiot.gitbooks.io/rhiotdocumentation/content/gateway/index.html

**Comment by ppatierno** [comment]
+1

**Comment by hekonsek** [comment]
That was fast :P

**Comment by ppatierno** [comment]
I follow your movements mate ! :P

**Comment by sophokles73** [comment]
It certainly looks very appealing and professional :-)
My only concern is whether this ties us in any way to GitHub itself (apart from the markdown flavor used).

**Comment by ppatierno** [comment]
@sophokles73 are we using the official web site for that, right ? can we close this issue ?

**Comment by sophokles73** [comment]
Well, the Eclipse Foundation requires us to host our *primary* project web site on Eclipse infrastructure, i.e. we are not allowed to use GitHub pages for that purpose. But I guess we are allowed to e.g. link to an external resource for certain information. So, given that we will definitely run into the problem of maintaining and publishing multiple versions of documentation (and I have no clue yet how to solve this using our current approach), I guess it would make sense to (again) think about using something like GitBooks for Hono as well. My understanding is that you guys are using it for a number of other projects as well, right?

**Comment by sophokles73** [comment]
We have settled to use Hugo's multi language support for this purpose, i.e. every (supported) version is reflected by a language (using the version name) in the docs.
