### ISSUE TITLE
Device lifecycle tracking and events

### ISSUE THREAD

**Issue by bergie** [eclipse/hono#120]
Currently there is no way to know whether a particular device registered with Hono is alive or dead. It would be useful to add lifecycle events support.

Building blocks:

* Information on how often a particular device (or class of devices) intends to transmit telemetry
* Keeping track of when a device was "last seen"

With these two we can provide lifecycle eventing. If device was last seen a longer time ago than the intended transmission schedule (plus maybe some buffer), it can be considered to be "disconnected". If it transmits again later, it is now "connected".

We're doing something related in [MsgFlo](https://msgflo.org):

* msgflo/msgflo#73: Let discovery message declare heartbeat period
* msgflo/msgflo#30: Participants should send discovery messages periodically

In the context of Hono it probably doesn't make sense to impose an additional heartbeat message. So instead it is better to use actual telemetry sent by device as the heartbeat.

**Comment by bergie** [comment]
This would be super useful for the Hono-MsgFlo connector: https://github.com/msgflo/msgflo-hono

**Comment by sophokles73** [comment]
Hey @bergie,

it was great talking to you last week at BCX2017 :-) Thanks for raising this issue, we had already been thinking about having Hono emit lifecycle events for devices being registered, updated and unregistered.
However, you seem to also strive for support for knowing about the device's current *connectivity* status as well. While it is easy to update a *last seen* timestamp, it is a harder task to actively detect that a device has not *met its schedule*. Would you expect Hono to actively publish a `device inactive` event or would you rather need support for querying the *last seen* timestamp for devices?

**Comment by bergie** [comment]
Either would work, but optimally Hono would keep track of it.

**Comment by sophokles73** [comment]
Support for emitting notifications regarding the device lifecycle has been added to Hono's device registry implementation in #2837. The protocol adapters emit events regarding the connection state of devices, if configured.
