### ISSUE TITLE
Implement credentials caching mechanism in Hono Adapters to speedup credentials lookup

### ISSUE THREAD

**Issue by almheida** [eclipse/hono#1203]
Protocol adaptors use Hono Credentials API to lookup credentials for device authentication, each time the device is connected to the adapter. So far by messaging flow (specifically through HTTP protocol) a lookup operation against the credentials store is to be performed each time the device sends message through the adapter. That might turn to be costly in term of many resulting request timeouts when applying huge messaging load to the adapter. Therefore, implementing lookup caching mechanism for device credentials in the adapter may solve the issue here.

**Comment by sophokles73** [comment]
The reason why the `CredentialsClientFactoryImpl` currently does not cache results is for security reasons. In general, it is considered bad practice to cache credentials. In addition to that, the (Credentials) service implementation uses the *cache-control* application property in its response messages to indicate to the client, if the data in the body is supposed to be cached, and if so, how long.

I can imagine that
1. we add general support for caching response data to the `CredentialsClientFactoryImpl` as we have it in all other client factories.
2. we change the Credentials service base classes to include a *cache-control* property in its responses which allows clients to cache the data. We should not make this the default behavior but allow it to be enabled explicitly by setting a configuration option. We also should allow caching of only those credential types that do not contain plain text credentials (like pre-shared key does).

**Comment by DanielMaier-BSI** [comment]
What came into my mind regarding this topic:

Caching of hashed credentials should not be a security issue, so I am fine with that and I also think we should do this. Especially HTTP based adapters need to execute many authentication requests. 

Caching the credentials locally in the adapters would already improve the situation, however in our deployment setup this comes with some limitations:
- Our deployment on AWS uses ELB which load balances requests to different machines without any stickiness
- Our deployment uses Kubernetes which load balances service requests in a round robin manner between pods

For our deployment it would probably make sense to use some kind of distributed cache like infinispan or redis. The question is now, do you think it would be useful to discuss and implement such distributed caching in open source space or is this to deployment specific and hono should only define the caching API and provide a local caching implementation?

**Comment by sophokles73** [comment]
> For our deployment it would probably make sense to use some kind of distributed cache like infinispan or redis.

Actually, I doubt that this would make much difference, because the expensive operation will not be the retrieval from the DB but the remote invocation of the Credentials service from the protocol adapters. If you replace the local cache in the adapters with a distributed cache, then you will also have remote calls for retrieving the values from another cache node in case of a cache-miss.
I would therefore try to keep it simple by using a local cache only ...

**Comment by DanielMaier-BSI** [comment]
As I understood infinispan caches, there is a replicated mode where each key is cached on each node. But as I am not an infinispan expert and I don't know if this scales for many nodes, I am fine with a simple approach. Perhaps an infinspan expert reads this :).

**Comment by almheida** [comment]
Having the simple implementation for caching is always preferable, nevertheless, that implementation  should consider the fact that the cached credential might be updated "by simple update credential operation in the credential store", which make the copies in replicas not more valid. Implementing that mechanism in the adaptor should consider one of the following:

- by updating the certificate every copy in the different adapter's replicas should be also updated.
- or every copy should be invalidated and the next credential lookup should be through the store again.

in that way, all copies of credentials are remained consistent and potential race conditions will be avoided :)

**Comment by sophokles73** [comment]
Like all other cached objects, the credentials would be evicted from the local caches after the time indicated by the *cache-policy* set on the response messages returned by the Credentials service. The cached credentials will then be valid until evicted from the local cache. This should be sufficient FMPOV.

**Comment by sophokles73** [comment]
@kaniyan are you also going to make the changes to the Credentials service implementation for taking advantage of the caching?

**Comment by kaniyan** [comment]
>     2\. we change the Credentials service base classes to include a _cache-control_ property in its responses which allows clients to cache the data. We should not make this the default behavior but allow it to be enabled explicitly by setting a configuration option. We also should allow caching of only those credential types that do not contain plain text credentials (like pre-shared key does).

@sophokles73 yes, as you suggested above. But I didn't start yet. Currently I am working on #1162.

**Comment by kaniyan** [comment]
@sophokles73 The Credentials service implementation is already equipped with cache directives to take advantage of the caching, if needed. The default behaviour is already set to _no-cache_ in `FileBasedCredentialsService`. FMPOV there is no need to make any changes on that part.

**Comment by sophokles73** [comment]
@kaniyan then we can leave it up to implementers of the Credentials service to decide on the particular cache directive they want to return for which credentials type. Even better :-)

**Comment by sophokles73** [comment]
@almheida FMPOV all necessary changes have been made to support caching of Credentials in the protocol adapters. Can you confirm and close this issue?

**Comment by almheida** [comment]
@sophokles73 Yes, Thank you! everything looks good.
