### ISSUE TITLE
Start Consumer with Enmasse

### ISSUE THREAD

**Issue by alexju88** [eclipse/hono#1209]
Hi guys, 
I have deployed Hono with Enmasse integrated, I have exported enmasse server certificate and ca certificate and import both of them into a truststore, and I run following commands but still has problem:

1.
mvn spring-boot:run -Drun.arguments=--hono.client.host=192.168.0.170,--hono.client.port=30646,--hono.client.username=consumer@HONO,--hono.client.password=verysecret,--hono.client.trustStorePath=/opt/hono/install/new/eclipse-hono-deploy-0.9/deploy/helm-enmasse/hono-demo-certs-jar/trustStore.jks

2.
mvn spring-boot:run -Drun.arguments=--hono.client.host=192.168.0.170,--hono.client.port=30646,--hono.client.username=consumer@HONO,--hono.client.password=verysecret,--hono.client.trustStorePath=/opt/hono/install/new/eclipse-hono-deploy-0.9/deploy/helm-enmasse/hono-demo-certs-jar/trustStore.jks,--hono.messaging.username=hono,--hono.messaging.password=bosch-iot-2019

Error logs:

Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

could you tell us how to configure SSL or authentication and start a consumer with Enmasse connected ?

Thanks!

**Comment by alexju88** [comment]
When I try the 3rd command with server certificate defined as below:
3.
mvn spring-boot:run -Drun.arguments=--hono.client.host=192.168.0.170,--hono.client.port=30646,--hono.client.username=consumer@HONO,--hono.client.password=verysecret,--hono.client.trustStorePath=/opt/hono/install/new/eclipse-hono-deploy-0.9/deploy/helm-enmasse/hono-demo-certs-jar/**enmasse.crt**


Still meet errors:
10:57:55.292 [vert.x-eventloop-thread-0] INFO  o.e.hono.client.impl.HonoClientImpl - stopping connection attempt to server [host: 192.168.0.170, port: 30646] due to terminal error
javax.security.sasl.AuthenticationException: Failed to authenticate


It seems that we still need to find a way to set Enmasse's username and password..

**Comment by alexju88** [comment]
Hi @calohmn， could you tell me how to authenticate a consumer for Enmasse?

**Comment by calohmn** [comment]
@alexju88 It looks like you just need to use the name and password of the user you created in EnMasse (instead of the "consumer@HONO"/"verysecret" credentials):
````
hono.client.username=YourEnMasseUser,--hono.client.password=YourEnMasseUserPW
````

**Comment by alexju88** [comment]
> 
> 
> @alexju88 It looks like you just need to use the name and password of the user you created in EnMasse (instead of the "consumer@HONO"/"verysecret" credentials):
> 
> ```
> hono.client.username=YourEnMasseUser,--hono.client.password=YourEnMasseUserPW
> ```

Hi Carsten, 

I used following command, but still meet same authentication error:

mvn spring-boot:run -Drun.arguments=--hono.client.host=192.168.0.170,--hono.client.port=30646,--hono.client.username=hono,--hono.client.password=bosch-iot-2019,--hono.client.trustStorePath=target/config/hono-demo-certs-jar/enmasse.crt

**Comment by calohmn** [comment]
@alexju88 Make sure that the `hono.client.password` is correct.

In order for the example consumer to work, also make sure that the necessary addresses have been created in EnMasse:
telemetry/DEFAULT_TENANT  -> address of type "anycast"
event/DEFAULT_TENANT  -> address of type "queue"
control/DEFAULT_TENANT  -> address of type "anycast"

**Comment by alexju88** [comment]
> 
> 
> @alexju88 Make sure that the `hono.client.password` value is correct.
> 
> In order for the example consumer to work, also make sure that the necessary addresses have been created in EnMasse:
> telemetry/DEFAULT_TENANT -> address of type "anycast"
> event/DEFAULT_TENANT -> address of type "queue"
> control/DEFAULT_TENANT -> address of type "anycast"


Should the address space, address be named according to Hono's user? like：

Address space: DEFAULTTENANT
Address: event
User: hono

Address space: DEFAULTTENANT
Address: telemetry
User: hono

Address space: DEFAULTTENANT
Address: control
User: hono

**Comment by calohmn** [comment]
@alexju88 The name of the EnMasse address space doesn't matter.
For each Hono tenant (e.g. "MyHonoTenantName"), you have to create 3 corresponding addresses in EnMasse: `telemetry/MyHonoTenantName`, `event/MyHonoTenantName`, `control/MyHonoTenantName`.

Then you would create a user in EnMasse with rights to *receive* messages on the `telemetry/MyHonoTenantName` and `event/MyHonoTenantName` addresses and with *send + receive* rights on `control/MyHonoTenantName/*`. The name of this user doesn't matter (but it would typically be or contain the tenant name) - it's the user that your downstream application has to be configured with to receive Hono messages and send commands.

**Comment by alexju88** [comment]
> 
> 
> @alexju88 The name of the EnMasse address space doesn't matter.
> For each Hono tenant (e.g. "MyHonoTenantName"), you have to create 3 corresponding addresses in EnMasse: `telemetry/MyHonoTenantName`, `event/MyHonoTenantName`, `control/MyHonoTenantName`.
> 
> Then you would create a user in EnMasse with rights to _receive_ messages on the `telemetry/MyHonoTenantName` and `event/MyHonoTenantName` addresses and with _send + receive_ rights on `control/MyHonoTenantName/*`. The name of this user doesn't matter (but it would typically be or contain the tenant name) - it's the user that your downstream application has to be configured with to receive Hono messages and send commands.

Thank you Carsten, I have already create address and users, just like what you said, consumer works.
Very appreciate!
