### ISSUE TITLE
Improve reconnect interval handling

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1210]
The handling of the *reconnect interval* concerning AMQP connections between Hono components should be improved.

Currently, when for example the connection between a protocol adapter and the device registry fails or is closed, the re-connect attempt happens only after 500ms (that is the DEFAULT_RECONNECT_INTERVAL_MILLIS = 500).

I guess this was introduced for the scenario that the device registry is indeed unavailable and for example currently being (re)started, so that an immediately-after re-connect attempt would probably fail.

But, there are other scenarios:
- The device registry could be deployed with multiple instances (Kubernetes pods) and even if one instance is currently not responding, the next connection attempt could reach another, fully available instance.
- The device registry could have actively closed the connection with a "access token expired" response, meaning there is no reason to wait for a re-connect attempt.

IMHO, these two scenarios are quite common, therefore we should introduce a way to handle reconnects where there isn't such a long delay before doing the first retry.

Suggested in the mailinglist discussion on this was to use an increasing timeout, starting with zero, up to a maximum:
````
minDelay: 0
maxDelay: 1000
increment: 100
````
On connect, reset relay to "min". On connection failure increment the delay if it is below "max".

**Comment by calohmn** [comment]
@sophokles73 Concerning the `give Vert.x some time to clean up NetClient` comment below, does that mean there were issues with doing a direct reconnect with no delay here, so that we should use a minimum delay > 0? Would something like 10ms be enough?

https://github.com/eclipse/hono/blob/6a85919d1e1cc9c3f2849c88f5c642ab4778b799/client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java#L495-L502

**Comment by sophokles73** [comment]
@calohmn that's  a good question. I have no clue if this has ever really been a problem. If it was, it might have been related to the very early version of proton we have been using at that time so I guess you will simply need to try ...

**Comment by sophokles73** [comment]
@calohmn IMHO you should also mention this enhancement in the release notes ...

**Comment by calohmn** [comment]
Yes, I've added a note there.

**Comment by sophokles73** [comment]
@calohmn can this be closed?
