### ISSUE TITLE
ExampleReceiver produces warnings after running longer than 60 seconds

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#122]
60s after the ExampleReceiver has been started, there are such warnings in the log:

> 12:32:22.495 [vert.x-eventloop-thread-0] INFO  o.e.hono.example.ExampleReceiver - Receiver created successfully.
> 12:32:22.497 [vert.x-worker-thread-0] INFO  o.e.hono.example.ExampleReceiver - Press enter to stop receiver.
> 12:33:22.787 [vertx-blocked-thread-checker] WARN  i.v.core.impl.BlockedThreadChecker - Thread Thread[vert.x-worker-thread-0,5,org.eclipse.hono.example.Application] has been blocked for 60284 ms, time limit is 60000
> io.vertx.core.VertxException: Thread blocked
> 	at java.io.FileInputStream.readBytes(Native Method) ~[na:1.8.0_112]
> 	at java.io.FileInputStream.read(FileInputStream.java:255) ~[na:1.8.0_112]
> 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_112]
> 	at java.io.BufferedInputStream.read(BufferedInputStream.java:265) ~[na:1.8.0_112]
> 	at org.eclipse.hono.example.ExampleReceiver.waitForInput(ExampleReceiver.java:81) ~[classes/:na]
> 	at org.eclipse.hono.example.ExampleReceiver$$Lambda$64/1416827644.handle(Unknown Source) ~[na:na]
> 	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:263) ~[vertx-core-3.4.0.jar:na]
> 	at io.vertx.core.impl.ContextImpl$$Lambda$66/1180079878.run(Unknown Source) ~[na:na]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_112]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_112]
> 	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_112]
> 12:33:23.783 [vertx-blocked-thread-checker] WARN  i.v.core.impl.BlockedThreadChecker - Thread Thread[vert.x-worker-thread-0,5,org.eclipse.hono.example.Application] has been blocked for 61284 ms, time limit is 60000
> io.vertx.core.VertxException: Thread blocked
> 	at java.io.FileInputStream.readBytes(Native Method) ~[na:1.8.0_112]
> 	at java.io.FileInputStream.read(FileInputStream.java:255) ~[na:1.8.0_112]
> 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_112]
> 	at java.io.BufferedInputStream.read(BufferedInputStream.java:265) ~[na:1.8.0_112]
> 	at org.eclipse.hono.example.ExampleReceiver.waitForInput(ExampleReceiver.java:81) ~[classes/:na]
> 	at org.eclipse.hono.example.ExampleReceiver$$Lambda$64/1416827644.handle(Unknown Source) ~[na:na]
> 	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:263) ~[vertx-core-3.4.0.jar:na]
> 	at io.vertx.core.impl.ContextImpl$$Lambda$66/1180079878.run(Unknown Source) ~[na:na]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_112]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_112]
> 	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_112]

Every second after that, a new warning is printed.

**Comment by calohmn** [comment]
The reason is the `System.in.read()` inside `waitForInput()` which is waiting for ENTER to be pressed.
As this is blocking, it is executed with `vertx.executeBlocking()` (so that is is run in a Vertx worker thread).

But although a Vertx worker thread is supposed to be doing longer-running tasks outside the Vertx event thread, these tasks should not run forever. To promote this, there is `VertxOptions.maxWorkerExecuteTime` (default 60s), causing warnings after this time has elapsed.

A simple solution to this would be removing the `waitForInput` method and letting the application be stopped by pressing CTRL+C ("Press CTRL+C to stop receiver.").
Cleanup work on shutdown can then be done in a @PreDestroy method.

(I would prefer CTRL+C also because it would allow pressing ENTER to add some blank lines in the terminal to better distinguish subsequent log output.)

**Comment by sophokles73** [comment]
I have already implemented this locally. I will push this to master later ...

**Comment by sophokles73** [comment]
fixed in a7ff7eda726e77e87f6b5cf3c5d35fe653ead125
