### ISSUE TITLE
Proposal: Hono Feature List for Landing Page

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#1221]
I am working on a new new landing page for Hono's web site. I would like to add some icons with a bit of text to highlight some of the main features of Hono. The attached screenshot only shows the general idea and is not intended to be used (especially the icons are just random placeholders). 
I think 6 would a good number, more are hard to grasp and a multiple of 3 would be good for the layout. My proposal is take the first 6 of the following list and skip the last one even though it is highlighted on the current start page. 

**What do you think?** Is this a good list? Any suggestions for improvements?

1. **Bazillions of Devices**: Hono is designed for connecting large numbers of IoT devices. Due to it's *reactive* architecture it scales very well.
1. **Uniform API**: Connect a multitude of different devices to your (cloud) back end. Communicate with them via a simple API regardless of the device protocol.
1. **IoT Protocols**: Hono ships with protocol adapters for the common IoT protocols *HTTP*, *MQTT* and *AMQP*.
1. **Messaging Patterns**: Hono provides APIs for important IoT communication patterns: *Telemetry*, *Events* and *Command &amp; Control*.
1. **Secure**: Hono is designed to be secure by default. It supports a bunch of state-of-the-art authentication technologies.
1. **Extensible**: Your device speaks a custom protocol? Hono provides a simple mechanism to add custom protocol adapters.
1. ~~**Integrates with your Systems**: Hono provides APIs for integration with existing device and credentials management systems.~~

![hono_features](https://user-images.githubusercontent.com/7031135/57215821-50341180-6fee-11e9-8faa-06f1bddef543.png)

**Comment by sophokles73** [comment]
@b-abel thanks for putting up this list and creating the proposal. I like the idea a lot and I agree that we should get away with six items.

Here are my two cents:

1. IMHO we should try to keep it real, i.e. instead of inventing the *bazillions*, I'd rather be a little more modest and e.g. start off with
> **Millions of Devices** Hono is designed for connecting large numbers of IoT devices. Its micro service based architecture and use of a reactive programming model allow for scaling out horizontally.
2. I would simply add a single word:
> **Uniform API** Connect a multitude of different types of devices to your (cloud) back end. Communicate with all of them via the same simple API regardless of the device protocol.
3. Again, just a small addition:
> **IoT Protocols** Hono supports devices communicating via common IoT protocols like HTTP, MQTT and AMQP out of the box.
4. Adding some explanatory wording could help:
> **Messaging Patterns** Hono provides APIs for important IoT communication patterns: *Telemetry* and *Event* messages can be used by devices to report sensor readings whereas applications can use *Command & Control* to invoke operations on devices.
5. IMHO we can be a little more specific:
> **Secure** Hono is designed for security by default. It supports common authentication mechanisms like username/password and X.509 client certificates to verify a device's identity and uses transport layer security (TLS) when communicating with devices.
6. IMHO we should replace *speaks* with *uses* ...
> **Extensible** Your device uses a custom protocol? Hono provides a simple mechanism to add custom protocol adapters.

**Comment by kaniyan** [comment]
@b-abel Sounds good.

**Comment by ctron** [comment]
> @b-abel thanks for putting up this list and creating the proposal. I like the idea a lot and I agree that we should get away with six items.
> 
> Here are my two cents:
> 
>     1. IMHO we should try to keep it real, i.e. instead of inventing the _bazillions_, I'd rather be a little more modest and e.g. start off with
> 
> 
> > **Millions of Devices** Hono is designed for connecting large numbers of IoT devices. Its micro service based architecture and use of a reactive programming model allow for scaling out horizontally.

:+1: Millions sounds better IMHO.

> 
>     1. IMHO we should replace _speaks_ with _uses_ ...
> 
> 
> > **Extensible** Your device uses a custom protocol? Hono provides a simple mechanism to add custom protocol adapters.

Maybe: "Your device is built on top a custom protocol? Hono provides a simple mechanism to implement custom protocol adapters."
