### ISSUE TITLE
Implement downlink for LoRaWAN adapter

### ISSUE THREAD

**Issue by BobClaerhout** [eclipse/hono#1226]
Currently the LoRaWAN adapter subscribes to pre-defined tenants. This is incorrect as different devices from the same tenant might connect to different adapters.
A first good step would be to subscribe to commands when a first message from a specific device is received on the LoRaWAN adapter. 
The only downside to this is that a device which has not yet sent any messages to the LoRaWAN adapter (after a restart) will not be able to receive downlink commands. Therefore I propose to keep the current pre-defined tenant list in place. By doing so, we keep the ability to choose while keeping in mind this specific tenant will have malfunctions when connecting through different adapters.

WDYT of this approach?

**Comment by sophokles73** [comment]
> Currently the LoRaWAN adapter subscribes to pre-defined tenants. This is incorrect as different devices from the same tenant might connect to different adapters.

what do you mean exactly with *connect to different adapters*? Do you mean devices of the same tenant, some connecting using MQTT and some using LoRaWAN? Or do you mean devices of the same tenant, all connecting using LoRaWAN but some connecting to LoRaWAN adapter instance 1 whereas others connect to adapter instance 2? Do the devices connect via a single network provider back end or are you talking about devices connecting to (local) gateways which connect to the LoRaWAN adapter instances?

**Comment by sophokles73** [comment]
@BobClaerhout Has this been addressed by your latest contribution(s) or is there more work to be done?

**Comment by BobClaerhout** [comment]
Yes, this has been addressed. I'll create a new issue if required.
