### ISSUE TITLE
Remove metrics for no longer active tenants from Prometheus response

### ISSUE THREAD

**Issue by Christian-Schmid** [eclipse/hono#1227]
Hi,

we've just started to use the new metrics based on Prometheus in Eclipse Hono. Very nice work!
However, one question has come to our attention regarding the amount of responded DataPoints of protocol adapters: 
In the Prometheus response I could observe two groups of data points: 
a) "Static data points" which are always there, e.g. with information of the jvm (for example: ``jvm_buffer_memory_used_bytes``)
b) "Dynamic data points" labeled with a certain ``tenant``. E.g.: ``hono_messages_received_seconds_max{component_name="hono-http",component_type="adapter",host="hono-adapter-http-vertx-7cd64d4867-c8p9s",qos="1",status="forwarded",tenant="acme",type="event",} 0.0``

The amount of returned DataPoints in the b) case grows with the amount of tenants which where at one point interacting with the protocol adapter. 

From the observations I made it looks like when a tenant stops interacting with the protocol adapter its metrics will still be returned in future. This leads to an over time growing amount of returned data points. This is inconvenient as it results in high load on the metric infrastructure and thus to high costs. Some cloud providers charge you based on the amount of points reported per scrape.

It would be nice that metrics for no longer interacting (e.g. by a specified time frame) tenants are removed from the result. 

What are your options? 

Thanks 
Chris

**Comment by ctron** [comment]
I think this goes hand in hand with issue #1188 ... maybe we do need some kind of "tenant closed" event (internally!) on which we can hook in functionality like that.
