### ISSUE TITLE
Documentation about possible deployments

### ISSUE THREAD

**Issue by ppatierno** [eclipse/hono#123]
I'm going to start writing documentation about how you can deploy Hono on OpenShift.
Taking a look to the current web site, I'm for creating a new left side menu item named "Deployments" with two possible sub-items : Docker Swarm and OpenShift.

The Docker Swarm should be something like explained in the Getting Started guide but if needed with more details.
The OpenShift item should open a page with detailed steps for deploying on OpenShift.

@sophokles73 @dejanb @dguggemos What do you think ?

**Comment by sophokles73** [comment]
I agree, we should have more detailed instructions for deploying to Docker in Swarm mode, e.g. to Docker for AWS.

**Comment by ppatierno** [comment]
I have already added "deployment" section in the web site with the OpenShift stuff. We have to wait for this night automatic job to push the updated content online from the repo :-)

**Comment by sophokles73** [comment]
Closing to include in 0.5-M5, remaining work covered by new #139
