### ISSUE TITLE
Error: Deploying Hono on Kubernetes under custom namespace

### ISSUE THREAD

**Issue by amit1306** [eclipse/hono#1235]
It seems the namespaces are stored on server and I am not able to deploy the hono under custom namespace i.e. com.org.abc.

Error: Cannot Create namespace at cluster level.

Note: I cannot have permissions at cluster level so only option is to deploy hono under custom namespace

**Comment by sophokles73** [comment]
I am afraid you will need to be a little more specific. What are you trying to achieve? What exactly are you doing?

**Comment by sophokles73** [comment]
I think I see what you mean. Currently, the Helm based deployment allows to specify the Kubernetes namespace to release into. However, in several places of the resource descriptors and config files, we assume the namespace to be `hono`.
