### ISSUE TITLE
Sandbox is down 

### ISSUE THREAD

**Issue by San13** [eclipse/hono#1236]
Could you please make sandbox up again

**Comment by sophokles73** [comment]
should be up and running again, can you confirm?

**Comment by San13** [comment]
I tried via https://hono.eclipse.org/ this url. This site still can't be reached.

**Comment by sophokles73** [comment]
not sure what you expect to find there. As indicated on the web site:
> The sandbox hosts a Hono instance consisting of the same components as described in the Getting started Guide. All services are exposed via the same ports as used in the guide.

Since Hono itself does not provide a web page, there is nothing to be served on https://hono.eclipse.org.

**Comment by San13** [comment]
My bad. I thought i am gonna see some web page. I tried to register a test device. It works. Thanks
