### ISSUE TITLE
Allow to enable SSL for Health Check Server by configuration

### ISSUE THREAD

**Issue by Christian-Schmid** [eclipse/hono#1238]
Hi, 
we use some additional endpoints in the ``VertxBasedHealthCheckServer`` which we want to secure by means of SSL like the main server. 

Therefore we extended the configuration options of the health check server to allow configuration of such. 

Maybe you are interested in such config option as well, I will create a PR :-)

**Comment by sophokles73** [comment]
Not sure if I understand correctly. What "additional endpoints" are you talking about?

**Comment by Christian-Schmid** [comment]
We want to use the Hono provided Prometheus metrics, they are exposed on that server. 
So far all our internal communication is secured by SSL, so we would like to secure the Prometheus metrics endpoint with SSL as well.

**Comment by sophokles73** [comment]
I see, and yes, we would be very interested in a PR adding that functionality...

**Comment by Christian-Schmid** [comment]
I created https://github.com/eclipse/hono/pull/1239 to show the functionality. If it is ok, i can add some integration tests.

**Comment by sophokles73** [comment]
closed via #1349
