### ISSUE TITLE
Move update of "last_via" property out of "assertRegistration" method

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1245]
The update of the `last_via` property is currently done as part of the `RegistrationService#assertRegistration` method (as defined in the javadoc).

It should be decoupled from that, allowing for more optimized implementations.

**Comment by calohmn** [comment]
Without being tied to `DeviceRegistry#assertRegistration`, the update of the `last_via` property should then only be done when there is a command subscription request being handled.

In that regard, the term `last_via` may not fit very well anymore.

I would rather use `commandGateway` instead. That would mean adding these methods to `RegistrationService`:
````
Future<Void> updateCommandGateway(String tenantId, String deviceId, String gatewayId)
String getCommandGateway(String tenantId, String deviceId);
````

**Comment by calohmn** [comment]
The solution here shall introduce a new `RegistrationService#updateDeviceLastVia` method and corresponding `RegistrationClient` methods, to be invoked by the Protocol adapters after the `assertRegistration` request was successful.

In order to be able to decide, whether the `updateDeviceLastVia` request is actually needed, `assertRegistration` should also return the `via` property of the device registration data.
Added #1248 for that.

**Comment by calohmn** [comment]
The suggested changes for this issue concerning the Device Registration API (AMQP) are:
- New mandatory operation `Update last-used gateway for device` for the AMQP interface. 
In `RegistrationService` this looks like:
`Future<Void> updateLastUsedGateway(String tenantId, String deviceId, String gatewayId, Span span)`
- New mandatory operation `Get last-used gateway for device` for the AMQP interface. 
In `RegistrationService` this looks like:
`Future<JsonObject> getLastUsedGateway(String tenantId, String deviceId, Span span);`
The returned JSON value would contain the gateway device id and the update date.
- With the introduction of the above method, the existing `Get Registration Information` operation of the AMQP interface isn't needed anymore in Hono code, therefore we could mark it as deprecated in M4 and remove it in Hono 1.0 (along with removing all the other non-mandatory operations).

In the `RegistrationClient` interface 2 new corresponding methods get added.
(With the introduction of the Infinispan-based Device Registry we could use an adapted RegistrationClient that communicates via the HotRod protocol with the Infinispan backend for the implementation of these methods.)

@sophokles73, @ctron thoughts on this?

**Comment by sophokles73** [comment]
sounds good to me
