### ISSUE TITLE
Support tenant-scoped CommandClient

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1255]
With the changes for #930, the sender link for sending commands is scoped on the tenant now.

That means there only needs to be one sender link on which all commands for devices of one particular tenant can be sent.

However, the current `CommandClient` and `AsyncCommandClient` instances are geared towards a particular device. The underlying sender link can't be shared for sending commands for different devices.

Therefore we should support a tenant-scoped CommandClient, where the `sendCommand` method gets a device parameter.

**Comment by sophokles73** [comment]
IMHO we should replace the existing methods with methods accepting the device ID, i.e. we should change the clients' underlying sender link to be always scoped to the tenant instead of the device.

**Comment by calohmn** [comment]
@sophokles73 For the `AsyncCommandClient` class this looks like the straightforward solution.

For the `CommandClient` class however, we have to take into account that there is a command response receiver link *scoped on the device* being opened there. This requires some more thought.

**Comment by calohmn** [comment]
With the `CommandClientImpl` being an `AbstractHonoClient` with one `ProtonSender` and one `ProtonReceiver` we would have to override quite some of the base class functionality in order to handle multiple *device-scoped* command response receiver links (not opening and closing them on every `sendCommand`). I would rather keep the `CommandClientImpl` device-scoped, but handle re-use of the tenant-scoped command sender link via the `ApplicationClientFactory` (on which `getOrCreateCommandClient` is to be called).

**Comment by sophokles73** [comment]
isn't the intended behavior of the CommandClient the one that we already have in all the other Device Registry clients i.e. using a single set of sender and receiver links for multiple requests?

**Comment by calohmn** [comment]
Yes, the CommandClient would have a single device-scoped Command receiver link and the tenant-scoped Command sender link, provided by and shared via the  ApplicationClientFactory / CommandClientFactory instance. Both would be used for multiple requests. Or what have you been aiming at?

**Comment by sophokles73** [comment]
Well, I would not call it *scoped to a single device* but rather *scoped to a single UUID* c´generated on instantiation, right?

**Comment by calohmn** [comment]
Right, the command response receiver links are indeed scoped to the `replyId` - which may be an ID shared between commands for *different* devices. 

In that sense the `CommandClient` instance can indeed keep just *one* command response receiver link to handle commands for multiple devices.

So yes, we can add a `deviceId` param to the `CommandClient#sendCommand` methods and refactor the `AbstractRequestResponseClient` base class a bit to support setting a request messages address per request.

**Comment by calohmn** [comment]
Fixed via https://github.com/eclipse/hono/commit/409a8db4fd55edd49f7271bc11f306abee690c34 and https://github.com/eclipse/hono/commit/87fb11b6f837d0d5798aacffe6c2b3c3be03b150.
