### ISSUE TITLE
Add "health" route to the HTTP REST adapter

### ISSUE THREAD

**Issue by ppatierno** [eclipse/hono#126]
In order to use the liveness probe feature in OpenShift, to check if an application inside a pod (and related container) is running, adding a "/health" route to the HTTP REST adapter could be useful. Executing a GET request on that and receiving the OK status means that the service is healthy and running. I think that it could be useful outside of the OpenShift context as well.

**Comment by sysexcontrol** [comment]
IMHO definitely useful - I have seen a /health endpoint in other scenarios a lot as well.

How about any payload in the answer?
Could be ignored, and only the status code being evaluated (ok or nok) - but in case of success, some easy to gather information like Hono version nr. could be useful.
Security must be considered though, not letting information to potential hackers if not desired. Could be configurable.

Best regards,
Karsten

**Comment by ppatierno** [comment]
The OpenShift liveness probe doesn't check any payload, it's based only on receiving an OK as HTTP response status code, so sending a payload doesn't hurt its job but as you said could be useful in other scenarios.

Regarding security, in OpenShift this request is executed internally (inside the cluster) but of course we could even use something SSL/TLS based for external incoming GET requests.

**Comment by calohmn** [comment]
Note that there is already a /status endpoint:
```
{
  "connected" : true,
  "#regClients" : 0,
  "Hono server" : "localhost:5672",
  "name" : "Hono REST Adapter",
  "active profiles" : "dev",
  "senders" : [ ]
}
```
Therefore the /health endpoint could be just about ok or nok.

**Comment by ppatierno** [comment]
Yes I see more information on the /status endpoint that could not be useful just for a liveness check; the /health could have an empty payload.

So thanks @calohmn @sysexcontrol ... I'll go for it ;)

**Comment by sysexcontrol** [comment]
+1 for me.

One last word regarding security:
what I meant is that in penetration tests it is a regular finding if any information endpoints are available that are not secured.
For webservers it is usually demanded e.g. that in any status pages there must not be any hint regarding the particular server that rendered the reponse (like Apache Tomcat/8.3 or anything similar), as long as you are not authenticated.

Thus I thought we should think about making these endpoints only available to authorized users.

This only affects the /status endpoint.
A /health endpoint without payload would be perfectly allowed IMHO.

**Comment by sophokles73** [comment]
Note that the `status` resource just contains some useful status information. The fact that it returns a 200 OK currently does **not** mean that the adapter is working properly. This needs to be determined based on the content of the response body.

**Comment by ppatierno** [comment]
@sophokles73 I understand your point and agree with you but ...

... on the OpenShift side we can't analyze the content of the response. The only usage of liveness probes is for giving to the orchestrator a chance to understand that the application is somehow crashed and doesn't respond so the pod needs to be restarted.

**Comment by sophokles73** [comment]
I was only trying to point out that the `status` resource might not be what you are looking for.

**Comment by ppatierno** [comment]
Sure but I know that even for the /health endpoint if it returns 200 OK it doesn't mean that the adapter is working properly but at least that the adapter isn't crashed and container doesn't need a restart.

**Comment by sophokles73** [comment]
Then `status` might indeed be what you are looking for ;-)

**Comment by ppatierno** [comment]
Yes but with useless data. 
Without thinking about OpenShift, consider for example an embedded device connected to Hono via a GPRS connection (so I pay for the transferred data, without having an ADSL flat). If the device wants just check the healthy of the adapter for sending data, it will receive useless traffic (paying it) if the /status endpoint is used. FMPOV it's better having a very simple endpoint, just OK 200 no payload for something like that. If I want more information I can ask on /status.

**Comment by sophokles73** [comment]
IMHO the example you gave is not very realistic. If the device wants to send data, it will simply send the data. If we are, e.g. talking about an HTTP based adapter, then there will most likely be a load balancer in front of the adapter which knows about the up-and-running instances because of the `status` resource. In there is only a single adapter instance then the device will simply do its request and if it fails, it knows that the adapter is not available.

**Comment by ppatierno** [comment]
In my previous company, for GPRS devices we preferred to send i.e. 540 bytes (500 telemetry + 40 health) but being quite sure that we were paying for good data for a running service and not trying to send just 500 bytes without being sure that the server was up (so paying for nothing).

Btw I can live with the /status endpoint. I'll check if OpenShift is clever enough to just discard the payload :-)

**Comment by ppatierno** [comment]
Finally, I used the "/status" for the checking HTTP REST adapter in the OpenShift deployment. I close this issue of behalf of #128
