### ISSUE TITLE
Failed to create SSL connection 

### ISSUE THREAD

**Issue by alexju88** [eclipse/hono#1275]
Hi Sir,
I'm trying to start a consumer according to link:https://www.eclipse.org/hono/getting-started/#starting-a-consumer, I extracted tls.crt certificate from Enmasse secret "external-certs-messaging" and decode it with base64.
**my command is as below:**
mvn spring-boot:run -Drun.arguments=--hono.client.host=192.168.0.92,--hono.client.port=32219,--hono.client.username=hono,--hono.client.password=hono_iot_2019,--hono.client.trustStorePath=target/config/hono-demo-certs-jar/tls.crt

**But failed as below:**

14:12:31.719 [main] INFO  org.eclipse.hono.cli.Application - running command line client in role(s): receiver,ssl
14:12:32.287 [main] INFO  org.eclipse.hono.cli.Application - Started Application in 1.71 seconds (JVM running for 6.674)
14:12:34.151 [vert.x-eventloop-thread-0] INFO  o.e.hono.client.impl.HonoClientImpl - max number of attempts [3] to re-connect to peer [192.168.0.92:32219] have been made, giving up
14:12:34.153 [vert.x-eventloop-thread-0] INFO  o.e.hono.client.impl.HonoClientImpl - stopping connection attempt to server [host: 192.168.0.92, port: 32219] due to terminal error
javax.net.ssl.SSLHandshakeException: Failed to create SSL connection
	at io.vertx.core.net.impl.ChannelProvider$1.userEventTriggered(ChannelProvider.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
	at io.netty.handler.ssl.SslUtils.handleHandshakeFailure(SslUtils.java:319)
	at io.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1573)
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1045)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.channels.ClosedChannelException: null
	at io.netty.handler.ssl.SslHandler.channelInactive(...)(Unknown Source)
14:12:34.154 [vert.x-eventloop-thread-0] ERROR org.eclipse.hono.cli.Receiver - Error occurred during initialization of receiver: failed to connect

Could you tell me why failed?

**Comment by sophokles73** [comment]
can you post the content of `target/config/hono-demo-certs-jar/tls.crt`

**Comment by alexju88** [comment]
-----BEGIN CERTIFICATE-----
MIIDXDCCAkSgAwIBAgIJAO2iBi+nmRNCMA0GCSqGSIb3DQEBCwUAMEIxCzAJBgNV
BAYTAlhYMRUwEwYDVQQHDAxEZWZhdWx0IENpdHkxHDAaBgNVBAoME0RlZmF1bHQg
Q29tcGFueSBMdGQwHhcNMTkwNTIxMDIyODM3WhcNNDkwNzAyMDIyODM3WjBCMRMw
EQYDVQQKDAppby5lbm1hc3NlMSswKQYDVQQDDCJtZXNzYWdpbmctNjJvYWQ1azAw
ZC5ob25vLXRlc3Quc3ZjMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
z1FhsvxOjK0mtqxXVXTYb7R46xq0n3//2Iob8K8yPha/Z9NwXYCaMZgTr0VzTV6e
NHGkNgnvwJl7FMP1ytlznZQNcelsw0mqPFfvYisZyBPLSiqHwL5K/y/xUMAJQ1Mp
pRJBCVWmKN/w7bT1bQSldwArNvYwg1n4BZMl6EhFaoyzOD799YE/c1d9mtE4nYk2
BzLcDV/KIWpsyOYvrMxv1zX1wZUPoQXVtecsTVVysyBDwCxRE/jRWuzoeFsrS3Of
+TLijdT7nsLbn0AfUZCuXMRmMzD+3BPf06q6jrPMa2K0kspaw/zXOd4WMGYb2jlD
ZxkMoTvmXyWndQqy0h5t9QIDAQABo1UwUzBRBgNVHREESjBIgiJtZXNzYWdpbmct
NjJvYWQ1azAwZC5ob25vLXRlc3Quc3ZjgiJtZXNzYWdpbmctNjJvYWQ1azAwZC5o
b25vLXRlc3Quc3ZjMA0GCSqGSIb3DQEBCwUAA4IBAQCpptPEuvx0aAAC9M1kdq4X
kf33m8GNKo48HMYicIJjUdoCp8y9s44+h4VkPqEBbIKD2cJA+ao0rOE3l8qB/hVb
yaal4I8baaZp2KDFHRYWiTI7dlcH2hb4nWzLVEFNjqDoMHVlU7Dl52gmsFppf8XQ
SM3+lCh4QlMY6d/FVT49G0ZeI7sV7Q21HWxs7NbcplTBEzsaQJySgyKS4BnOVBhp
XABDuHuw/rI2BsBwInAkYdIATcVE56IKiBxwaFgdb+HiXVj0jOP8ESNWuG73L92E
xKg0RTFZVCeyopVf1gSJf9qIDFFPRbo8kjUm6BeSSTxcMEanP7Hr5oKZN3n90Bs4
-----END CERTIFICATE-----

**Comment by alexju88** [comment]
> 
> 
> can you post the content of `target/config/hono-demo-certs-jar/tls.crt`

-----BEGIN CERTIFICATE-----
MIIDXDCCAkSgAwIBAgIJAO2iBi+nmRNCMA0GCSqGSIb3DQEBCwUAMEIxCzAJBgNV
BAYTAlhYMRUwEwYDVQQHDAxEZWZhdWx0IENpdHkxHDAaBgNVBAoME0RlZmF1bHQg
Q29tcGFueSBMdGQwHhcNMTkwNTIxMDIyODM3WhcNNDkwNzAyMDIyODM3WjBCMRMw
EQYDVQQKDAppby5lbm1hc3NlMSswKQYDVQQDDCJtZXNzYWdpbmctNjJvYWQ1azAw
ZC5ob25vLXRlc3Quc3ZjMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
z1FhsvxOjK0mtqxXVXTYb7R46xq0n3//2Iob8K8yPha/Z9NwXYCaMZgTr0VzTV6e
NHGkNgnvwJl7FMP1ytlznZQNcelsw0mqPFfvYisZyBPLSiqHwL5K/y/xUMAJQ1Mp
pRJBCVWmKN/w7bT1bQSldwArNvYwg1n4BZMl6EhFaoyzOD799YE/c1d9mtE4nYk2
BzLcDV/KIWpsyOYvrMxv1zX1wZUPoQXVtecsTVVysyBDwCxRE/jRWuzoeFsrS3Of
+TLijdT7nsLbn0AfUZCuXMRmMzD+3BPf06q6jrPMa2K0kspaw/zXOd4WMGYb2jlD
ZxkMoTvmXyWndQqy0h5t9QIDAQABo1UwUzBRBgNVHREESjBIgiJtZXNzYWdpbmct
NjJvYWQ1azAwZC5ob25vLXRlc3Quc3ZjgiJtZXNzYWdpbmctNjJvYWQ1azAwZC5o
b25vLXRlc3Quc3ZjMA0GCSqGSIb3DQEBCwUAA4IBAQCpptPEuvx0aAAC9M1kdq4X
kf33m8GNKo48HMYicIJjUdoCp8y9s44+h4VkPqEBbIKD2cJA+ao0rOE3l8qB/hVb
yaal4I8baaZp2KDFHRYWiTI7dlcH2hb4nWzLVEFNjqDoMHVlU7Dl52gmsFppf8XQ
SM3+lCh4QlMY6d/FVT49G0ZeI7sV7Q21HWxs7NbcplTBEzsaQJySgyKS4BnOVBhp
XABDuHuw/rI2BsBwInAkYdIATcVE56IKiBxwaFgdb+HiXVj0jOP8ESNWuG73L92E
xKg0RTFZVCeyopVf1gSJf9qIDFFPRbo8kjUm6BeSSTxcMEanP7Hr5oKZN3n90Bs4
-----END CERTIFICATE-----

**Comment by alexju88** [comment]
And I tried to import the ca.crt and tls.crt of Enmasse secret "external-certs-messaging" into java default truststore "/etc/pki/ca-trust/extracted/java/cacerts", and try below command:

mvn spring-boot:run -Drun.arguments=--hono.client.host=192.168.0.92,--hono.client.port=32219,--hono.client.username=hono,--hono.client.password=hono_iot_2019,--hono.client.trustStorePath=/etc/pki/ca-trust/extracted/java/cacerts

This time, error message is different:

WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
14:42:33.989 [main] INFO  org.eclipse.hono.cli.Application - running command line client in role(s): receiver,ssl
14:42:34.531 [main] INFO  org.eclipse.hono.cli.Application - Started Application in 1.591 seconds (JVM running for 6.863)
14:42:40.080 [vert.x-eventloop-thread-0] INFO  o.e.hono.client.impl.HonoClientImpl - stopping connection attempt to server [host: 192.168.0.92, port: 32219] due to terminal error
javax.security.sasl.AuthenticationException: Failed to authenticate
	at io.vertx.proton.impl.ProtonSaslClientAuthenticatorImpl.handleSaslFail(ProtonSaslClientAuthenticatorImpl.java:159)
	at io.vertx.proton.impl.ProtonSaslClientAuthenticatorImpl.process(ProtonSaslClientAuthenticatorImpl.java:98)
	at io.vertx.proton.impl.ProtonTransport.processSaslAuthentication(ProtonTransport.java:211)
	at io.vertx.proton.impl.ProtonTransport.handleSocketBuffer(ProtonTransport.java:194)
	at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:392)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:225)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:123)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:370)
	at io.vertx.core.net.impl.ConnectionBase.handleRead(ConnectionBase.java:397)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:174)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
14:42:40.082 [vert.x-eventloop-thread-0] ERROR org.eclipse.hono.cli.Receiver - Error occurred during initialization of receiver: failed to authenticate with server

**Comment by sophokles73** [comment]
There is no need to import any of the certificates into Java's default trust store. In fact, I strongly discourage you from doing so because this might affect the security of other applications based on Java that you run on your platform.

I think the problem you are running into is the fact that you are specifying the wrong certificate file as the trust store on the command line. The server sends its end certificate during the TLS handshake (the tls.crt) which is signed by the private key belonging to ca.crt. However, since you do not trust ca.crt, the certificate chain cannot be validated.

Can you try to run
```
mvn spring-boot:run -Drun.arguments=--hono.client.host=192.168.0.92,--hono.client.port=32219,--hono.client.username=hono,--hono.client.password=hono_iot_2019,--hono.client.trustStorePath=target/config/hono-demo-certs-jar/ca.crt
```

and post the output if you get an error?

**Comment by alexju88** [comment]
> 
> 
> There is no need to import any of the certificates into Java's default trust store. In fact, I strongly discourage you from doing so because this might affect the security of other applications based on Java that you run on your platform.
> 
> I think the problem you are running into is the fact that you are specifying the wrong certificate file as the trust store on the command line. The server sends its end certificate during the TLS handshake (the tls.crt) which is signed by the private key belonging to ca.crt. However, since you do not trust ca.crt, the certificate chain cannot be validated.
> 
> Can you try to run
> 
> ```
> mvn spring-boot:run -Drun.arguments=--hono.client.host=192.168.0.92,--hono.client.port=32219,--hono.client.username=hono,--hono.client.password=hono_iot_2019,--hono.client.trustStorePath=target/config/hono-demo-certs-jar/ca.crt
> ```
> 
> and post the output if you get an error?

I tried ca.crt but meet same error with tls.crt, if I use cacerts as trustStorePath, the result is "failed to authenticate" and Enmasse application also get similar error log. That means SSL connection has been established, credential has been passed from Consumer to Enmasse. So I guess may be user account "hono" in Enmasse has problem.  Enmasse checked the credential from consumer application and say "No, you are not allowed." ?

**Comment by sophokles73** [comment]
can you try to run
```
mvn spring-boot:run -Drun.arguments=--hono.client.host=192.168.0.92,--hono.client.port=32219,--hono.client.username=hono,--hono.client.password=hono_iot_2019,--hono.client.trustStorePath=target/config/hono-demo-certs-jar/ca.crt,--hono.client.hostnameVerificationRequired=false
```
and post the output?

**Comment by alexju88** [comment]
> 
> 
> can you try to run
> 
> ```
> mvn spring-boot:run -Drun.arguments=--hono.client.host=192.168.0.92,--hono.client.port=32219,--hono.client.username=hono,--hono.client.password=hono_iot_2019,--hono.client.trustStorePath=target/config/hono-demo-certs-jar/ca.crt,--hono.client.hostnameVerificationRequired=false
> ```
> 
> and post the output?

I run it and get same error:

17:10:28.365 [main] INFO  org.eclipse.hono.cli.Application - running command line client in role(s): receiver,ssl
17:10:28.980 [main] INFO  org.eclipse.hono.cli.Application - Started Application in 1.608 seconds (JVM running for 6.205)
17:10:30.816 [vert.x-eventloop-thread-0] INFO  o.e.hono.client.impl.HonoClientImpl - max number of attempts [3] to re-connect to peer [192.168.0.92:32219] have been made, giving up
17:10:30.818 [vert.x-eventloop-thread-0] INFO  o.e.hono.client.impl.HonoClientImpl - stopping connection attempt to server [host: 192.168.0.92, port: 32219] due to terminal error
javax.net.ssl.SSLHandshakeException: Failed to create SSL connection
	at io.vertx.core.net.impl.ChannelProvider$1.userEventTriggered(ChannelProvider.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
	at io.netty.handler.ssl.SslUtils.handleHandshakeFailure(SslUtils.java:319)
	at io.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1573)
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1045)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.channels.ClosedChannelException: null
	at io.netty.handler.ssl.SslHandler.channelInactive(...)(Unknown Source)
17:10:30.819 [vert.x-eventloop-thread-0] ERROR org.eclipse.hono.cli.Receiver - Error occurred during initialization of receiver: failed to connect

**Comment by alexju88** [comment]
Hi,
I think SSL connection has been established and authentication is not a problem now, but we meet a new problem as below:

WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
17:36:25.354 [main] INFO  org.eclipse.hono.cli.Application - running command line client in role(s): receiver,ssl
17:36:25.838 [main] INFO  org.eclipse.hono.cli.Application - Started Application in 1.629 seconds (JVM running for 6.374)
17:36:26.365 [vert.x-eventloop-thread-0] ERROR org.eclipse.hono.cli.Receiver - Error occurred during initialization of receiver: Node not found
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.697 s
[INFO] Finished at: 2019-06-06T17:36:26+08:00
[INFO] ------------------------------------------------------------------------
17:36:26.469 [Thread-4] INFO  o.s.c.a.AnnotationConfigApplicationContext - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@372f90cc: startup date [Thu Jun 06 17:36:24 CST 2019]; root of context hierarchy
17:36:26.476 [Thread-4] INFO  o.e.hono.client.impl.HonoClientImpl - connection to server [192.168.0.92:32220] already closed


Enmasse standard-authservice  has related log about user "hono".

So the question is: what is node ? why node is not found ?

**Comment by sophokles73** [comment]
Ok then let's start debugging the TLS handshake.
It would be easier if you started the consumer using the cli client jar file instead of using the spring-boot Maven plugin.

Please run
```sh
# in folder $HONO/cli
java -jar target/hono-cli-*-exec.jar -Djavax.net.debug=ssl:handshake --hono.client.host=192.168.0.92 --hono.client.port=32219 --hono.client.username=hono --hono.client.password=hono_iot_2019 --hono.client.trustStorePath=target/config/hono-demo-certs-jar/ca.crt --hono.client.hostnameVerificationRequired=false
```

**Comment by alexju88** [comment]
mvn command:

mvn spring-boot:run -Drun.arguments=--hono.client.host=192.168.0.92,--hono.client.port=32220,--hono.client.username=hono,--hono.client.password=hono_iot_2019,--hono.client.trustStorePath=/etc/pki/ca-trust/extracted/java/cacerts

**Comment by alexju88** [comment]
> 
> 
> Ok then let's start debugging the TLS handshake.
> It would be easier if you started the consumer using the cli client jar file instead of using the spring-boot Maven plugin.
> 
> Please run
> 
> ```shell
> # in folder $HONO/cli
> java -jar target/hono-cli-*-exec.jar -Djavax.net.debug=ssl:handshake --hono.client.host=192.168.0.92 --hono.client.port=32219 --hono.client.username=hono --hono.client.password=hono_iot_2019 --hono.client.trustStorePath=target/config/hono-demo-certs-jar/ca.crt --hono.client.hostnameVerificationRequired=false
> ```

Thanks, where can I find hono-cli-*-exec.jar ? I can't find it in target folder ..

**Comment by sophokles73** [comment]
what is the content of the target folder?

**Comment by alexju88** [comment]
> 
> 
> what is the content of the target folder?


target content is as below:

[root@cnhwmn01-test target]# ll
total 28
drwxr-xr-x 3 root root 4096 May 21 15:26 classes
drwxr-xr-x 5 root root 4096 Apr 28 11:05 config
drwxr-xr-x 2 root root 4096 Apr 16 15:30 dependency-maven-plugin-markers
drwxr-xr-x 3 root root 4096 Apr 16 15:30 generated-sources
drwxr-xr-x 3 root root 4096 Apr 16 15:30 generated-test-sources
drwxr-xr-x 3 root root 4096 Apr 16 15:30 maven-status
drwxr-xr-x 3 root root 4096 Apr 16 15:30 test-classes

**Comment by alexju88** [comment]
[root@cnhwmn01-test target]# tree
.
├── classes
│   ├── application.yml
│   ├── banner.txt
│   ├── logback-spring.xml
│   └── org
│       └── eclipse
│           └── hono
│               └── cli
│                   ├── AbstractCliClient.class
│                   ├── AbstractClient.class
│                   ├── AmqpSend$1.class
│                   ├── AmqpSend.class
│                   ├── AppConfiguration.class
│                   ├── Application.class
│                   ├── Commander.class
│                   ├── Commander$Command.class
│                   └── Receiver.class
├── config
│   └── hono-demo-certs-jar
│       ├── amqp-adapter-cert.pem
│       ├── amqp-adapter-key.pem
│       ├── amqpKeyStore.p12
│       ├── artemis-cert.pem
│       ├── artemis-key.pem
│       ├── artemisKeyStore.p12
│       ├── auth-server-cert.pem
│       ├── auth-server-key.pem
│       ├── authServerKeyStore.p12
│       ├── ca-cert.pem
│       ├── ca-cert.srl
│       ├── ca-key.pem
│       ├── coap-adapter-cert.pem
│       ├── coap-adapter-key.pem
│       ├── coapKeyStore.p12
│       ├── default_tenant-cert.pem
│       ├── default_tenant-cert.srl
│       ├── default_tenant-key.pem
│       ├── device-4711-cert.pem
│       ├── device-4711-key.pem
│       ├── device-certs.properties
│       ├── device-registry-cert.pem
│       ├── device-registry-key.pem
│       ├── deviceRegistryKeyStore.p12
│       ├── enmasse2.crt
│       ├── enmasse-62oad5k00d.crt
│       ├── enmasse-ca.crt
│       ├── enmasse.crt
│       ├── enmasse-new.crt
│       ├── enmasse-uat-ca.crt
│       ├── enmasse-uat.crt
│       ├── http-adapter-cert.pem
│       ├── http-adapter-key.pem
│       ├── httpKeyStore.p12
│       ├── kura-adapter-cert.pem
│       ├── kura-adapter-key.pem
│       ├── kuraKeyStore.p12
│       ├── mqtt-adapter-cert.pem
│       ├── mqtt-adapter-key.pem
│       ├── mqttKeyStore.p12
│       ├── qdrouter-cert.pem
│       ├── qdrouter-key.pem
│       ├── root-cert.pem
│       ├── root-cert.srl
│       ├── root-key.pem
│       ├── trust-anchor.properties
│       ├── trusted-certs.pem
│       └── trustStore.jks
├── dependency-maven-plugin-markers
│   └── org.eclipse.hono-hono-demo-certs-jar-0.9.marker
├── generated-sources
│   └── annotations
├── generated-test-sources
│   └── test-annotations
├── maven-status
│   └── maven-compiler-plugin
│       ├── compile
│       │   └── default-compile
│       │       ├── createdFiles.lst
│       │       └── inputFiles.lst
│       └── testCompile
│           └── default-testCompile
│               ├── createdFiles.lst
│               └── inputFiles.lst
└── test-classes
    ├── logback-test.xml
    └── org
        └── eclipse
            └── hono
                └── cli
                    └── ReceiverTest.class

23 directories, 67 files

**Comment by sophokles73** [comment]
Are you following the Getting Started guide to build and deploy Hono or are you deploying pre-built images from Docker Hub?

**Comment by alexju88** [comment]
> 
> 
> Are you following the Getting Started guide to build and deploy Hono or are you deploying pre-built images from Docker Hub?

We  followed the Getting Started guide and use helm+tiller to deploy Hono. 
Tenant,device,credentials functions are all OK, only telemetry data can not been pushed to consumer.
 So how can we get that jar file? could you upload it to Github other repo ?

**Comment by alexju88** [comment]
> 
> 
> > Ok then let's start debugging the TLS handshake.
> > It would be easier if you started the consumer using the cli client jar file instead of using the spring-boot Maven plugin.
> > Please run
> > ```shell
> > # in folder $HONO/cli
> > java -jar target/hono-cli-*-exec.jar -Djavax.net.debug=ssl:handshake --hono.client.host=192.168.0.92 --hono.client.port=32219 --hono.client.username=hono --hono.client.password=hono_iot_2019 --hono.client.trustStorePath=target/config/hono-demo-certs-jar/ca.crt --hono.client.hostnameVerificationRequired=false
> > ```
> 
> Thanks, where can I find hono-cli-*-exec.jar ? I can't find it in target folder ..



> 
> 
> There is no need to import any of the certificates into Java's default trust store. In fact, I strongly discourage you from doing so because this might affect the security of other applications based on Java that you run on your platform.
> 
> I think the problem you are running into is the fact that you are specifying the wrong certificate file as the trust store on the command line. The server sends its end certificate during the TLS handshake (the tls.crt) which is signed by the private key belonging to ca.crt. However, since you do not trust ca.crt, the certificate chain cannot be validated.
> 
> Can you try to run
> 
> ```
> mvn spring-boot:run -Drun.arguments=--hono.client.host=192.168.0.92,--hono.client.port=32219,--hono.client.username=hono,--hono.client.password=hono_iot_2019,--hono.client.trustStorePath=target/config/hono-demo-certs-jar/ca.crt
> ```
> 
> and post the output if you get an error?

Hi Sir, I tried java client and error is same with mvn:"Node not found":


10:09:30.420 [main] INFO  org.eclipse.hono.cli.Application - Starting Application v0.9 on cnhwmn01-test with PID 28155 (/opt/hono/test/jar/hono-cli-0.9-exec.jar started by root in /opt/hono/test/jar)
10:09:30.423 [main] INFO  org.eclipse.hono.cli.Application - The following profiles are active: receiver,ssl
10:09:30.495 [main] INFO  o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@4e91d63f: startup date [Mon Jun 10 10:09:30 CST 2019]; root of context hierarchy
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (jar:file:/opt/hono/test/jar/hono-cli-0.9-exec.jar!/BOOT-INF/lib/spring-core-4.3.22.RELEASE.jar!/) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
10:09:31.128 [main] INFO  org.eclipse.hono.cli.Application - running command line client in role(s): receiver,ssl
10:09:31.702 [main] INFO  org.eclipse.hono.cli.Application - Started Application in 2.149 seconds (JVM running for 2.705)
10:09:32.325 [vert.x-eventloop-thread-0] ERROR org.eclipse.hono.cli.Receiver - Error occurred during initialization of receiver: Node not found
10:09:33.356 [Thread-3] INFO  o.s.c.a.AnnotationConfigApplicationContext - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@4e91d63f: startup date [Mon Jun 10 10:09:30 CST 2019]; root of context hierarchy
10:09:33.360 [Thread-3] INFO  o.e.hono.client.impl.HonoClientImpl - connection to server [192.168.0.92:32220] already closed

**Comment by alexju88** [comment]
Authentication with Enmasse is OK since if I change password to connect it will show authentication error.

**Comment by alexju88** [comment]
Problem solved. Thanks! @sophokles73
