### ISSUE TITLE
503 Service Unavailable when I Publish an Event

### ISSUE THREAD

**Issue by alexju88** [eclipse/hono#1282]
Hi Sir,
I have successfully publish an telemetry to Enmasse and receive it in consumer, but when I try to publish an event, the command will meet 503 service unavailable problem.

**My command:**
curl -i -X POST -u s01@alexju:guess -H 'Content-Type: application/json'  --data-binary '{"alarm": true}' http://192.168.0.92:30080/event/

**My enmasse user** has full access for any address as here : https://github.com/alexju88/hono-enmasse/tree/master/enmasse-resources-create

**My consumer command:**
java -jar hono-cli-0.9-exec.jar --hono.client.host=192.168.0.92 --hono.client.port=32221 -Djavax.net.debug=ssl:handshake --hono.client.username=honotest --hono.client.password=*** --spring.profiles.active=receiver --tenant.id=alexju --hono.client.trustStorePath=/etc/pki/ca-trust/extracted/java/cacerts

Should I change address settings here: https://github.com/alexju88/hono-enmasse/tree/master/enmasse-resources-create or change consumer receiver settings ?
Thanks!

**Comment by ctron** [comment]
I think you are using wrong address names. Instead of just `telemetry` you need to add the tenant e.g.: `telemetry/DEFAULT_TENANT`

**Comment by sophokles73** [comment]
@alexju88 is this still an issue? If not, can you close it?
