### ISSUE TITLE
Extend message limit check to include commands

### ISSUE THREAD

**Issue by kaniyan** [eclipse/hono#1284]
With the implementation of  #929, Hono now supports _message limit checks_ for _telemetry_ and _event_ messages. This needs to be extended to cover the _commands_ being sent from north bound applications. Also the protocol adapters should be enabled to verify the _message limit_ before accepting _commands_ from north bound applications.

**Comment by sophokles73** [comment]
@kaniyan can this be closed?

**Comment by kaniyan** [comment]
yes.

**Comment by kaniyan** [comment]
Fixed via [3e788a4](https://github.com/eclipse/hono/commit/3e788a43d8c0e39ceda2d85859ebc81753ee4565)
