### ISSUE TITLE
flowLatency delays creation of senders unnecessarily long

### ISSUE THREAD

**Issue by DanielMaier-BSI** [eclipse/hono#1288]
Hi,

when someone configures flowLatency in hono client, hono client will delay creation of a sender by flowLatency if no credits are available immediately. Given the following setup:

- flowLatency of 200ms leads to no credit issues in our infrastructure from time to time
- So I thought flowLatency of 1000ms should be really enough even in our setup

We now get "always" credits, however the creation of the sender gets delayed very often by a second. This causes for example that the device needs to wait 1 second for a response to a telemetry message or a command sender for the command response.

Would it be possible from a technical point of view to wait for credits only as long as required (as CreditBasedSender does)? Do you think this would be an improvement for hono client or do you just say "get your infrastructure fixed"? 

Even with this in place we would still have the "issue" that sender links with no corresponding receiver links need to wait the maximum amount of time.

**Comment by sophokles73** [comment]
> Do you think this would be an improvement for hono client or do you just say "get your infrastructure fixed"?

You should always get your infrastructure fixed in any case :-) That said, I think that we could (should) improve the code for establishing a sender link in `HonoConnectionImpl.createSender()` so that it registers a *send queue drain handler* in case no credit is available yet. The timer for the *flow latency* would then only act to limit the time to wait for credit to an upper limit. However, if the drain handler fires first, the timer would be canceled.

Shouldn't be too much of an issue. A PR for this would be very welcome :-)

**Comment by DanielMaier-BSI** [comment]
I will try to provide a PR next week.

One additional question out of curiosity: This solution would work fine for command response clients as they get newly created for every single response. As you mentioned in another issue for telemetry connection in protocol adapters this is not true. If there are multiple messages for the same tenant concurrently all but the first will still get a 503 error. Did you discuss or did you think about in the past to not postpone the creation of the sender but postpone sending of the messages, i.e. introduce a small message buffer only until the first credits were received?

**Comment by sophokles73** [comment]
> If there are multiple messages for the same tenant concurrently all but the first will still get a 503 error. Did you discuss or did you think about in the past to not postpone the creation of the sender but postpone sending of the messages, i.e. introduce a small message buffer only until the first credits were received?

We did not introduce a *message buffer* but a request to create a downstream sender will be retried for several times if a concurrent request is in progress already. This should improve the situation to some extent.

**Comment by sophokles73** [comment]
fixed in https://github.com/eclipse/hono/commit/8f50891a1520bb02cca1aa4bd729ec7193f3351c
