### ISSUE TITLE
Hono AMQP 1.0 port improvement - leverage IANA defaults and offer additional insecure port

### ISSUE THREAD

**Issue by sysexcontrol** [eclipse/hono#129]
As already discussed in the mailing list:

Hono currently uses a TLS secured port which offers AMQP 1.0 communication with the default port 5672.
But this is exactly the behaviour that is defined by IANA for port 5671.

Additionally it is desirable in some environments (e.g. dev-environments) to have a port without TLS encryption as well (additionally or as only port).

Thus the following solution was found during the mailing list discussion and needs to be implemented:

- "hono.server.port" represents the secure port (never opens an insecure port)

- "hono.server.insecurePort" represents the insecure port (as only port or as additional port to the secure one)

Best regards
Karsten (sysexcontrol)

****** Detailed result from mailing list discussion: ******

1) leverage the IANA defaults if "hono.server.port" is not configured :

"hono.server.keyStorePath" found -> 5671, otherwise no secure port is opened.
Used Port is logged explicitly as INFO.

2) let the user explicitly configure the "hono.server.port":

"hono.server.keyStorePath" found? -> open desired port. If port is not the IANA secure port 5671, print a warning about potential misconfiguration.
"hono.server.keyStorePath" not found? -> no secure port is opened, print a warning about potential misconfiguration.
Used Port is logged explicitly as INFO.

3) additional insecure port available if flag "hono.server.allowInsecure = true":

Port can be determined by "hono.server.insecurePort":
-  set? then use it. If configured to IANA secure port 5671, print a warning about potential misconfiguration.
- not set? then use the IANA default 5672

Used Port is logged explicitly as INFO.

4) Exceptions during startup:

- both ports active and configured equally (port == insecurePort)  -> misconfiguration
- Hono would not open any port by configuration (this cannot be desirable).

**Comment by sophokles73** [comment]
You can extend `org.eclipse.hono.config.HonoConfigProperties` with corresponding properties.

Do we want to support separate *bind addresses* for secure and insecure endpoints as well?

**Comment by sysexcontrol** [comment]
Thanks, that's exactly where I started :-)

Haven't thought about the bind address so far, but this makes perfect sense to me - the insecure port configuration possibly should only be reachable in internal networks, that cannot be accessed from outside.
So we will have explicit bind address for the insecure port to not expose this port necessarily to everyone.

**Comment by sophokles73** [comment]
fixed in 59d226eacbd3885a8adc6fe28db9ab851bec7039
