### ISSUE TITLE
Upgrade to Spring Boot 2

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#1297]
Spring Boot 1 will run out of support August 1st 2019 as indicated in [this blog post](https://spring.io/blog/2018/07/30/spring-boot-1-x-eol-aug-1st-2019)

IMHO we should include this upgrade in the 1.0 release already.

This will also entail upgrading to Spring 5 AFAIK

**Comment by kaniyan** [comment]
The latest spring boot GA release is [2.1.5](https://spring.io/projects/spring-boot#learn). Spring Framework 5.1.7.RELEASE or above is [required](https://docs.spring.io/spring-boot/docs/current/reference/html/getting-started-system-requirements.html).

**Comment by sophokles73** [comment]
CQs have been approved.

**Comment by sophokles73** [comment]
fixed via https://github.com/eclipse/hono/pull/1303
