### ISSUE TITLE
Allow max message size to be defined for Hono Messaging & AMQP adapter

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#130]
Currently, we have no way of configuring a maximum payload size for messages being processed by Hono Messaging. This, however is important to make sure that we do not run into memory problems when many messages are in flight.

**Comment by sophokles73** [comment]
@ppatierno 
do you know whether this is possible in vertx-proton?

**Comment by sophokles73** [comment]
This has been added in [vertx-proton 3.4.2](https://github.com/vert-x3/vertx-proton/issues/50)

**Comment by sophokles73** [comment]
there is a corresponding [issue in vertx-proton](https://github.com/vert-x3/vertx-proton/issues/57)

**Comment by ctron** [comment]
@sophokles73 Does it make sense to keep this issues. It looks like this is about Hono Messaging, but we don't really make use of that component anymore.

**Comment by sophokles73** [comment]
@ctron maybe not wrt Hono Messaging but certainly wrt to the AMQP protocol adapter.

**Comment by sophokles73** [comment]
vertx-proton doesn't support enforcement of max message size as of version 3.5.4. The underlying Qpis proton-j library also doesn't support this (yet). It doesn't make sense to implement this at the application level though, because once the application level gets its hands on an incoming message, the memory has already been allocated and used. The only thing to do for the time being is probably opening a corresponding issue for Qpid proton-j ...

**Comment by sophokles73** [comment]
There is not much more than https://github.com/eclipse/hono/commit/aa3ce1586fa59f67156e305565eea94b750be9d5 that we can do about it based on the existing capabilities of proton-j in this regard. 

As noted above, we will not add this functionality to Hono Messaging anymore because it is already deprecated.
