### ISSUE TITLE
Re-add links to stable version in documentation.

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#1302]
Until the 1.0 release there is no version of Hono, that is considered the "stable" version. Therefore all links in the code pointing to version `stable` have been replaced by links to `latest`. This was done by simply replacing each occurrence of the string "/docs/stable" by "/docs/latest".

This needs to be reverted right after the release of version 1.0. 

**Do not replace every occurrence of "/docs/latest"!** 
There are some places where the link to latest is correct. For orientation look at the commit, where the initial replacement has been made: a16b49381b4ef30b5b88efb7569dc4d513ea209a.

**Comment by sophokles73** [comment]
latest milestone is used as *stable* version until 1.0.0 is released.
