### ISSUE TITLE
Base64-encoded password in log

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#133]
In the Hono server logs, there are lines like this:

> 13:03:09.795 [vert.x-eventloop-thread-0] DEBUG o.e.h.a.i.BaseAuthenticationService - received authentication request: {"mechanism":"PLAIN","response":"AHJlc3QtYWRhcHRlcgBzZWNyZXQ="}

The "response" part here is a base64-encoded password. That shouldn't occur in the logs.

**Comment by sophokles73** [comment]
fixed in 981e63406ebba5411a4580b8b8cd4de8de2a0645
