### ISSUE TITLE
Report payload size of messages based on the configured minimum message size in HTTP, MQTT and AMQP Adapters

### ISSUE THREAD

**Issue by kaniyan** [eclipse/hono#1330]
Its also the case that the cloud providers set _minimum size_ for incoming messages. For example, lets say a _minimum message size_ is set to 4 KB. This can have an influence on how the number of messages or data volume are calculated.  A message of size 8KB is considered as two messages and another message with 10 KB is considered as three messages. Alternatively it can have influence on how data volume is calculated: a message of size 1KB is considered as 4KB and another with 10KB is considered as 12KB.

 It would be good that if Hono also has such an option and this can be combined with the _resource limit checks_ to effectively manage the resources. Ideally the _minimum message size_ can be set as part of the _tenant configuration_ so that it gives the flexibility to configure this size for each tenant. The adapters while reporting the metrics to Prometheus can calculate the _payload size_ based on the configured _minimum message size_ per tenant and then report the calculated payload size. This behaviour can be enabled only when _minimum message size_ is configured else not.

**Comment by sophokles73** [comment]
@kaniyan can this be closed?

**Comment by kaniyan** [comment]
> @kaniyan can this be closed?

This can be closed after merging the documentation and device registry updates in PR #1399

**Comment by sophokles73** [comment]
@kaniyan merged

**Comment by kaniyan** [comment]
Closed via PRs #1333 and  #1399
