### ISSUE TITLE
Start using major.minor.micro versions

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#1332]
Currently Hono uses major.minor versions. I would suggest to start using major.minor.micro versions, beginning with the next milestone. But latest with version 1.0.0.

*    It is known as "semver" (https://semver.org/).
*    It is common model that many people (even outside of the Java context) do know and understand.
*    It would allow us to release service releases (after the 1.0 release), which do not change the versioning schema in a service release.

**Comment by sophokles73** [comment]
definitely
FMPOV we will release `1.0.0`, not `1.0`.

**Comment by sophokles73** [comment]
Done with the 1.0.0 release.
