### ISSUE TITLE
Support providing a trace context along with MQTT messages

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1336]
In order to have a complete overview of a telemetry/event message lifecycle in a tracing solution, it would be good to have the message related trace spans created in a protocol adapter be combined with trace spans created in the originating device/gateway. For that, the message reaching the protocol adapter must have trace context information and the protocol adapter must use these.

The HTTP adapter already supports having a OpenTracing span context parameter provided via the HTTP headers of an incoming message.

A corresponding feature should be added to the MQTT adapter, providing support for extracting trace context information from a "property bag" at the end of the MQTT topic name.

(This relates to #267 in that there we also need support for "property bags".)

**Comment by sophokles73** [comment]
If I am not mistaken, this would only work in scenarios where the device/gateway reports its spans to the same tracing system as the Hono components, right? I have a hard time imagining what kind of setup that would be?

**Comment by calohmn** [comment]
Yes, the same tracing system would need to be used (or at least tracing data of such 2 systems would have to be merged at some point).
Addmittedly, this is probably not very realistic for real-world scenarios. But it could be useful for having an integrated test environment (e.g. an overall health check), where the whole message lifecycle from device to northbound application is tested and can then be analyzed in the tracing component.
