### ISSUE TITLE
Support limiting the data volume per tenant for the remaining amount of days of the current calender month

### ISSUE THREAD

**Issue by alinaserg** [eclipse/hono#1337]
With the implementation of #929, Hono supports message limit check of data volume per time period. This time period can be defined e.g. in days.

The logic with limit check must be extended to limit the data volume not only for the time period but also on the calender month base. It means that the data volume is monthly calculated (the customer gets monthly data volume at the beginning of the month and can use it till the end of the calender month). 

The additional functionality is necessary if the customer books the service not on the first day of the calender month but e.g. in the middle of the month, then only the data volume for the remaining days of the current month are available. In this case it will be only the half of the monthly volume.

Ex.: service is booked on the 15. June, data volume for the whole month is 100 MB, till the end of the month is left 15 days, that is why the data limits must be set accordingly to the 50 MB.
With the beginning of the new calender month the data limits must be set to the limits of the whole month, it means the customer gets 100 MB of data volume.

**Comment by sophokles73** [comment]
just to be clear about this: the idea is that the amount of data is always the same for each (calendar) month while the number of days over which the limit is to be imposed varies between months, right?

**Comment by alinaserg** [comment]
The amount of data is always the same for each calender month, but if the service is booked not at the beginning of the calender month, but a few days later the average amount of data per day must be calculated and of course will be differently for different calender months. It means that if the service booked on the 2nd of February and on the 2nd of May the calculated remaining data volume will be a little bit different in these two cases.

**Comment by sophokles73** [comment]
@kaniyan can this be closed?

**Comment by kaniyan** [comment]
@sophokles73  yes.

@alinaserg This has been closed via PRs #1420 and #1491
