### ISSUE TITLE
Adapt Getting Started guide and Device Registy user guide to new HTTP Management API

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#1347]
This needs to be done when we create the 1.0.0 release but not before, because the current documentation is supposed to cover 0.9.

**Comment by sophokles73** [comment]
Hmm, on a second thought, that is probably not true, i.e. we currently only have *development* (i.e. *latest*) documentation that covers the current milestone. Once we have release 1.0.0 we will keep documentation for the *stable* version (1.0.0) and continue to update the *latest* documentation to cover what's going on on master ...

**Comment by sophokles73** [comment]
@ctron @dejanb WDYT? Should we schedule this for the current milestone or for 1.0.0 only?

**Comment by dejanb** [comment]
@sophokles73 I think it'd be good to start "releasing" documentation for the milestone releases as well for now. People are using it and depend on them, so having the docs available would make their lives easier (especially with a big change like this). I think it'd be good to have M5 documentation "tagged" and then we can modify docs for the master.

**Comment by sophokles73** [comment]
@dejanb the scope of this issue actually includes adapting the Registry user guide as well, which is not addressed by #1371 IIRC ...
