### ISSUE TITLE
Error during startup of example Device Registry

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1355]
During startup of the device registry component (with the new API), there is this error in the log file:
````
16:20:04.024 [vert.x-eventloop-thread-0] DEBUG o.e.h.d.FileBasedRegistrationService - loading devices for tenant [DEFAULT_TENANT]
16:20:04.040 [vert.x-eventloop-thread-0] DEBUG o.e.h.d.FileBasedRegistrationService - cannot load device identities from file [/var/lib/hono/device-registry/device-identities.json]: Cannot deserialize instance of `java.util.ArrayList` out of VALUE_STRING token
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.eclipse.hono.service.management.device.Device["via"])
````
This points to the `via` entry in the `device-identities.json` not supporting a string value anymore but requiring an array now.

**Comment by calohmn** [comment]
I think, the fact that a `via` string value is not supported anymore should also be mentioned in the release-notes.

What about date entries like `2017-05-01T14:00:00+01:00` not working anymore - should we consider this a bug? Or just require the UTC format with the new API?

**Comment by calohmn** [comment]
Regarding the date value in the credentials object:
_Previously_, the conversion from `String` to `Instant` was done manually (using `CredentialsObject#getTimestampIfPresentForField`, which uses `DateTimeFormatter.ISO_OFFSET_DATE_TIME`).

_Now_ the conversion is done via the `jsonObject.mapTo(CommonCredential.class)` invocation, which will use the `Json#InstantSerializer` (which uses `DateTimeFormatter.ISO_INSTANT`) to map the `CommonSecret.notBefore` `Instant` field.

**Comment by dejanb** [comment]
@calohmn I think we can support single string converting to array using Jackson settings, so we can maintain backward compatibility in that way. I'll take a look into this.

**Comment by dejanb** [comment]
> I think, the fact that a `via` string value is not supported anymore should also be mentioned in the release-notes.
> 
> What about date entries like `2017-05-01T14:00:00+01:00` not working anymore - should we consider this a bug? Or just require the UTC format with the new API?

Hm, as far as I can see this date format is used in example and test credentials.

https://github.com/eclipse/hono/blob/master/tests/src/test/resources/deviceregistry/credentials.json#L12

 Can you give me the exact value that's causing this problem?

**Comment by calohmn** [comment]
I got the date related error after applying the Helm deployment in minikube and then GETting credentials for a device, so the value must have been this one:
https://github.com/eclipse/hono/blob/master/deploy/src/main/deploy/example-credentials.json#L12

**Comment by dejanb** [comment]
@calohmn there's a pr for "via" issue. I'll take a look at the date format next.

**Comment by calohmn** [comment]
@dejanb One other thing concerning the credentials JSON structure:
I tried to adapt the example in the getting started guide to the new API and created a PUT request with a credentials JSON containing the `pwd-plain` field (as in the current example):
````
  {
    "type": "hashed-password",
    "auth-id": "'$MY_DEVICE'",
    "enabled": true,
    "secrets": [
      {
        "pwd-plain": "'$MY_PWD'"
      }
    ]
  }
````
This was rejected with an exception, however.
 `UnrecognizedPropertyException: Unrecognized field "pwd-plain" (class org.eclipse.hono.service.management.credentials.PasswordSecret), not marked as ignorable (7 known properties: "enabled", "not-after", "salt", "hash-function", "not-before", "pwd-hash", "comment"])` 

But, reading the comments starting from https://github.com/eclipse/hono/pull/1130#issuecomment-479827344, I understood that we still wanted to support the `pwd-plain` field.

**Comment by calohmn** [comment]
Ok, I've created #1377 for that.
To be noted is that `pwd-plain` is already used in PR #1371, updating the "getting started" guide to the new management API:
https://github.com/eclipse/hono/pull/1371/files#diff-2a45b0285f5e18c214c50a4d40f05f03R177

**Comment by dejanb** [comment]
@calohmn thanks!
