### ISSUE TITLE
Improve Device Registry API spec with examples, supported values

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1367]
Looking at the Open API spec for the Device Registry API
https://github.com/eclipse/hono/blob/master/site/documentation/static/api/device-registry-v1.yaml
I think we can improve its usability by adding more information about what kind of values are expected for the various fields.

Example:
For a PUT request on the `/credentials/` resource, the Swagger UI creates such an example value for the request Json:
````
[
  {
    "type": "string",
    "auth-id": "string",
    "enabled": true,
    "ext": {
      "additionalProp1": {}
    },
    "secrets": [
      {
        "enabled": true,
        "not-before": "2019-07-16T10:17:22.500Z",
        "not-after": "2019-07-16T10:17:22.500Z",
        "comment": "string",
        "hash-function": "sha-512",
        "pwd-hash": "string",
        "salt": "string"
      }
    ]
  },
[...]
````
It would be useful here to note that the "type" field in the above Json excerpt must contain `hashed-password` as value and that the `hash-function` field supports the values "sha-256", "sha-512" and "bcrypt".

All in all we could integrate example values and descriptive texts for all fields that require certain values.

This relates to #1324.

**Comment by sophokles73** [comment]
@calohmn can we close this with #2048 ?

**Comment by calohmn** [comment]
@sophokles73 Yes, it looks good now :+1: .
