### ISSUE TITLE
Hono Rest-Adapter and MQTT-Adapter not starting on HEAD branch

### ISSUE THREAD

**Issue by sysexcontrol** [eclipse/hono#137]
Due to explicit initialization of PORT_UNCONFIGURED port, the current strategy to compare with 0 leads to an error. Thus the both adapters are not starting currently.

Fix to compare them with Constants.PORT_UNCONFIGURED solves the problem and will be provided soon.

**Comment by sophokles73** [comment]
fixed in 59d226eacbd3885a8adc6fe28db9ab851bec7039
