### ISSUE TITLE
Health check configuration values are not picked up from environment variables

### ISSUE THREAD

**Issue by jbtrystram** [eclipse/hono#1386]
When providing settings for the health check server through environment variables (i.e. `HONO_HEALTH_CHECK_INSECURE_PORT`) the values are not picked up.

**Comment by sophokles73** [comment]
Can you describe what you are doing and what the expected result is?

**Comment by sophokles73** [comment]
@jbtrystram can we (you) close this?

**Comment by jbtrystram** [comment]
I did not make further testing, i'll close this and will take time to re-test it at some point :)
