### ISSUE TITLE
Metrics data are not being recorded in the Prometheus back-end.

### ISSUE THREAD

**Issue by kaniyan** [eclipse/hono#1388]
Metrics data are not being recorded in the Prometheus back-end. Hono is built from the _master_ branch and deployed using _Helm charts_ in _Kubernetes clusters_ spun by _minikube_ locally.

![image](https://user-images.githubusercontent.com/18659982/61540434-e698a080-aa3d-11e9-9a60-baff96ed7fe1.png)

**Comment by mbaeuerle** [comment]
Oh dear, looks like that's a problem introduced with the secure health check which is used in the deployment by default.

**Comment by sophokles73** [comment]
The Prometheus server will probably need to be configured with the Hono trust store ...
