### ISSUE TITLE
Report payload size of messages based on the configured minimum message size in LoRa Adapter

### ISSUE THREAD

**Issue by kaniyan** [eclipse/hono#1397]
Equip _LoRa_ Adapter, so that the message size is calculated based on the configured minimum message size. And the calculated value is reported to metrics.

Refer issue #1330 for more information.

**Comment by sophokles73** [comment]
@kaniyan Shouldn't this already be the case due to the fact that the LoRa adapter extends the (abstract) HTTP adapter base?

**Comment by kaniyan** [comment]
> @kaniyan Shouldn't this already be the case due to the fact that the LoRa adapter extends the (abstract) HTTP adapter base?

@sophokles73 At that time of creation of this issue, the _LoRa_ adapter still supported _Command & Control_ functionality and hence some changes were required to support the minimum message size concept. There by this issue has been created to track it. In May 2020, the _Command & Control_ functionality from the LoRa adapter has been removed thereby no more changes are required to support this minimum message size feature. Also considering the fact that this adapter also extends the HTTP adapter base, this issue can be closed.

**Comment by kaniyan** [comment]
> > @kaniyan Shouldn't this already be the case due to the fact that the LoRa adapter extends the (abstract) HTTP adapter base?
> 
> @sophokles73 At that time of creation of this issue, the _LoRa_ adapter still supported _Command & Control_ functionality and hence some changes were required to support the minimum message size concept. There by this issue has been created to track it. In May 2020, the _Command & Control_ functionality from the LoRa adapter has been removed thereby no more changes are required to support this minimum message size feature. Also considering the fact that this adapter also extends the HTTP adapter base, this issue can be closed.

Due to the above stated reason, this issue is closed.
