### ISSUE TITLE
Provide dual port (secure as default, insecure as optional) strategy to all protocol adapters (see #129 for Hono server)

### ISSUE THREAD

**Issue by sysexcontrol** [eclipse/hono#140]
In #129 the configuration base for the dual port strategy was created and applied to the Hono server itself (for AMQP 1.0).

The same strategy shall be implemented for the protocol adapters.

**Comment by sysexcontrol** [comment]
To handle the still outstanding appliance of the new "service-base" module to the protocol adapters I reopen this issue (will result in more pull requests).

**Comment by sophokles73** [comment]
fixed in a6016ad95e6c373610c2b1e53c983d63ea17e48f
