### ISSUE TITLE
Emit Connection Events from AMQP adapter

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#1400]
The AMQP adapter should use the Connection Events mechanism in order to indicate to downstream applications that a device has connected/disconnected.

**Comment by Alfusainey** [comment]
@sophokles73 are you working on this issue? if not, can I take a look?

**Comment by sophokles73** [comment]
@Alfusainey no, nobody is currently working on this one. It would be great if you could implement it :+1:
