### ISSUE TITLE
Use OpenTracing in SigFox adapter

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#1402]
Use OpenTracing to trace message handling in the SigFox protocol adapter.

**Comment by ctron** [comment]
Taking a look a at the HTTP protocol adapter for a reference, I am not sure what to add to the Sigfox adapter.

**Comment by calohmn** [comment]
I also think the Tracing feature should already be provided by the HTTP adapter base class used in the SigFox adapter.

**Comment by sophokles73** [comment]
Even better, then I will close this issue ...
