### ISSUE TITLE
Ability to collect and report metrics in Hono server

### ISSUE THREAD

**Issue by pellmann** [eclipse/hono#141]
It should be possible to collect and provide Hono server metrics in an extend-able way. In in initial implementation I would expect one possible way to pull this metrics (e.g. by JMX) and an other to push them (e.g. to Hawkular). It should also be possible to activate/deactivate this reporting mechanisms and to add new ones.

As an initial set I propose number of connections, number of links and number of credits per link - upstream and downstream. Also number of messages and number of discarded message per tenant.

Some metrics from the JVM should be accessible like free mem and uptime.

**Comment by sophokles73** [comment]
fixed in 281127fd83203bc0a78bab5bd86882050f5609d8
