### ISSUE TITLE
MQTT Devices self-register through MQTT adapter

### ISSUE THREAD

**Issue by alexjuchina** [eclipse/hono#1422]
Hi,
We are testing if our MQTT device could self-register through MQTT adapter, could you tell me if it is possible ? Device register through "hono-service-device-registry" with CURL command as document said is OK. But our device does not support http protocol. 
Thanks.

**Comment by juwenfeng1988** [comment]
If it's possible, could you tell me how ? thanks

**Comment by sophokles73** [comment]
Please use stackoverflow for any future questions. We are using GitHub for bugs and contributions only.

That said, no, Hono does not support the automatic registration of devices as of now. I would strongly discourage a design where a device would use the Device Registration and Credentials API directly to register itself. These APIs should not be exposed on the internet but should be accessible from (internal) management systems only. Based on that, I can imagine the protocol adapters performing the device registration on the fly. See #1296

**Comment by alexjuchina** [comment]
> 
> 
> Please use stackoverflow for any future questions. We are using GitHub for bugs and contributions only.
> 
> That said, no, Hono does not support the automatic registration of devices as of now. I would strongly discourage a design where a device would use the Device Registration and Credentials API directly to register itself. These APIs should not be exposed on the internet but should be accessible from (internal) management systems only. Based on that, I can imagine the protocol adapters performing the device registration on the fly. See #1296

Thank you Hudalla, so the device is better be registered internally and manually..without using API to register itself.. understand, for safety reason.
By the way, for the #1296 , do you have any plan to add auto provisioning API function?

**Comment by sophokles73** [comment]
It will come eventually, but personally, I have no concrete plan to implement any time soon.

**Comment by alexjuchina** [comment]
@sophokles73, If our customer indeed want to register their device or gateway into Hono by MQTT adapter automatically, and if we have to do some customization to achieve this, could you give us some suggestions?

**Comment by sophokles73** [comment]
you will need to adapt the MQTT adapter and do the registration when the device opens the connection. I am not sure what kind of suggestions you expect. When the device opens the connection you extract whatever information you need from the request and invoke the API available for registering devices in your device registry implementation. Since there is no *mandatory* API defined for that, the specifics of how to do that depend on your concrete registry's capabilities ...
