### ISSUE TITLE
MQTT client 3.1.3 supported?

### ISSUE THREAD

**Issue by alexjuchina** [eclipse/hono#1423]
Hi,
We have a device which support protocol MQTT 3.1.3,  Hono MQTT adapater is 3.1.1, so theoretically can device communicate with Hono successfully ? For example, register device itself in Hono and send messages to Hono.
Thanks.

**Comment by sophokles73** [comment]
Please use stackoverflow for posting questions using the `eclipse-hono` tag.

I am not aware of an MQTT 3.1.3 version. Can you provide a pointer to its specification? Then I can take a look ...

See #1422 for an answer to your second question.
