### ISSUE TITLE
Hardcoded event bus send timeout in AbstractEndpoint leads to timeouts for long lasting operations

### ISSUE THREAD

**Issue by DanielMaier-BSI** [eclipse/hono#1441]
https://github.com/eclipse/hono/blob/c21831c27fe11b21d8b09f4d39592b5ed2ad4293/service-base/src/main/java/org/eclipse/hono/service/AbstractEndpoint.java#L146-L151 sets send timeout of event bus to 3 seconds. This timeout gets also used by RequestResponseEndpoint. This leads to issues during creation of tenants in our tenant manager implementation as creating tenant in dependent systems, e.g. enmasse, may last longer. Would it make sense from your perspective to make this configurable somehow?

**Comment by sophokles73** [comment]
It does and we would be happy to receive a corresponding PR :-)
