### ISSUE TITLE
does MQTT 3.1.1 can support MQTT3.1 ? 

### ISSUE THREAD

**Issue by CharlieCai3** [eclipse/hono#1443]
Hi Hono, 
we have this issue:  device is with MQTT3.1 while Hono support 3.1.1,  how we can link device to hono with such different MQTT version deference ?   is there any workaround suggest ? Thanks.

**Comment by sophokles73** [comment]
I have to admit that I do not have any experience with MQTT 3.1.0 clients. My understanding from https://github.com/mqtt/mqtt.github.io/wiki/Differences-between-3.1.0-and-3.1.1 is that there seem to be quite some differences which might prevent establishment of a connection. Is that what you are also experiencing?

**Comment by sophokles73** [comment]
@CharlieCai3 any news on this?
