### ISSUE TITLE
Error in Verification instructions for Helm Based Deployment

### ISSUE THREAD

**Issue by 195858** [eclipse/hono#1444]
The instructions here 
https://www.eclipse.org/hono/docs/deployment/helm-based-deployment/ contain an error on the deployment validation step, service name is wrong, should be ``eclipse-hono-service-device-registry-ext ``
replace ...
```
export REGISTRY_IP=$(kubectl get service hono-service-device-registry-ext --output='jsonpath={.status.loadBalancer.ingress[0].ip}' -n hono)```

with 
```
export REGISTRY_IP=$(kubectl get service eclipse-hono-service-device-registry-ext --output='jsonpath={.status.loadBalancer.ingress[0].ip}' -n hono)```
```

**Comment by sophokles73** [comment]
thanks for spotting :+1: 
However, fixing this would be quite burdensome since the 1.0-M6 documentation is generated from the tag in the repository. We would need to create a new tag for the fix. I'll see what we can do about it. For the time being, I will keep this issue open so that users can easily find it ...

**Comment by sophokles73** [comment]
@195858 After having taken a closer look I cannot see any error in the documentation for 1.0-M6. May I ask which version you have tried to deploy? Have you built and deployed from master or have you checked out/downloaded 1.0-M6?

**Comment by sophokles73** [comment]
@195858 any news on this?

**Comment by 195858** [comment]
Hi, I just picked it up from the documentation on the web site while following the installation instructions - https://www.eclipse.org/hono/docs/deployment/helm-based-deployment/

I don't know which version that documentation is generated from.

**Comment by sophokles73** [comment]
https://www.eclipse.org/hono/docs/deployment/helm-based-deployment/ refers to the latest (stable) version, which at the moment is 1.0-M7. So, if you are deploying using the Helm chart from the 1.0-M7 tag, the documentation should be correct. I have just now downloaded the 1.0-M7 release artifact from Hono's Downloads page and was able to follow the exact steps as documented in the Helm deployment guide.
