### ISSUE TITLE
minikube tunnel - Amend minikube setup instructions

### ISSUE THREAD

**Issue by 195858** [eclipse/hono#1445]
on this page - https://www.eclipse.org/hono/docs/deployment/create-kubernetes-cluster/

where it says -
 
After the Minikube VM has started successfully, the ``minikube tunnel `` command should be run ...

amend tunnel command to include the -p flag

After the Minikube VM has started successfully, the ``minikube tunnel -p hono`` command should be run ...

**Comment by calohmn** [comment]
Thanks for reporting this. The extra profile parameter is needed when having started minikube with that parameter as well, as described in the documentation:
`minikube start --cpus 2 --memory 8192 -p hono`.

IMHO, it would be better to omit the parameter in the documentation altogether, to avoid such issues with forgetting the parameter with minikube commands. @sophokles73 WDYT?
