### ISSUE TITLE
Change semantics of default TTL on downstream events

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#1448]
Currently, the protocol adapters set a TTL on downstream events as follows:
1. if message contains a TTL, keep it
2.1. otherwise, if a default TTL is set at the tenant level, use it
2.2. if a default TTL is set at the device level, use it.

In production environments, however, a service provider will probably want to be able to set an upper limit for message TTL in order to ensure reasonable resource utilization.

In such a scenario, the *max TTL* would not be settable by the tenant but by the service provider only and the protocol adapters should ensure that the TTL set on a downstream event does not exceed the max TTL. It seems to make sense to be able to support both, a *default TTL* and a *max TTL* at the tenant level so that downstream events can get a default TTL value but adapters can also use the max TTL as an upper limit if a default TTL is specified at the device level by the device owner.

**Comment by calohmn** [comment]
So that means that if a *max TTL* but *no* *default TTL*  is set on the tenant level and if no default TTL is set for the device in the device registry, then the effective TTL on the downstream event will be the *max TTL*, correct?

In general, we have to take the tenant *max TTL* also into account for the implementation of  #267 and #266, where setting the TTL per event message shall get supported.

**Comment by sophokles73** [comment]
> So that means that if a max TTL but no default TTL is set on the tenant level and if no default TTL is set for the device in the device registry, then the effective TTL on the downstream event will be the max TTL, correct?

FMPOV the downstream message should have no effective TTL at all in this case ...

**Comment by calohmn** [comment]
> FMPOV the downstream message should have no effective TTL at all in this case ...

But no effective TTL means an infinite TTL, which is greater than the max TTL...

**Comment by sophokles73** [comment]
That is true :-) So I guess you're right. In that case the effective TTL should be the max TTL.
