### ISSUE TITLE
Intermittent failures of HonoClientImplTest

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#145]
Sometimes, the HonoClientImplTest fails with this error:

> Running org.eclipse.hono.client.impl.HonoClientImplTest
> 10:08:29.303 [main] DEBUG o.e.hono.client.impl.HonoClientImpl - creating new message sender for telemetry/tenant
> 10:08:29.313 [main] DEBUG o.e.hono.client.impl.HonoClientImpl - already trying to create a message sender for telemetry/tenant
> Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.619 sec <<< FAILURE! - in org.eclipse.hono.client.impl.HonoClientImplTest
> testGetOrCreateTelemetrySenderFailsIfInvokedConcurrently(org.eclipse.hono.client.impl.HonoClientImplTest)  Time elapsed: 0.567 sec  <<< FAILURE!
> org.mockito.exceptions.verification.WantedButNotInvoked: 
> 
> Wanted but not invoked:
> protonConnection.createSender(
>     "telemetry/tenant"
> );
> -> at org.eclipse.hono.client.impl.HonoClientImplTest.testGetOrCreateTelemetrySenderFailsIfInvokedConcurrently(HonoClientImplTest.java:91)
> 
> However, there were other interactions with this mock:
> protonConnection.isDisconnected();
> -> at org.eclipse.hono.client.impl.HonoClientImpl.checkConnection(HonoClientImpl.java:361)
> 
> 
> 	at org.eclipse.hono.client.impl.HonoClientImplTest.testGetOrCreateTelemetrySenderFailsIfInvokedConcurrently(HonoClientImplTest.java:91)

See here for example:
https://travis-ci.org/eclipse/hono/builds/217209692

**Comment by sophokles73** [comment]
Yes, I have seen this on Travis happening from time to time. However, this never happened on our Eclipse HIPP instance nor in any of my local builds (yet). Did this happen to you on your local machine?

I wonder if this is a Travis issue ...

**Comment by calohmn** [comment]
It has happened on our Jenkins and it has happened twice on my local machine.
But I couldn't reproduce it while trying to debug it.

**Comment by sophokles73** [comment]
fixed in cf5efbfd6ff1b14d723e50fcc2294a7ecd1adc83
