### ISSUE TITLE
Upgrade to vertx 3.8.x

### ISSUE THREAD

**Issue by kaniyan** [eclipse/hono#1462]
Upgrade to vertx 3.8.x which already use netty 4.1.39.Final and  proton-j 0.33.2.
For more info refer[ release notes](https://github.com/vert-x3/wiki/wiki/3.8.1-Release-Notes).

**Comment by calohmn** [comment]
See also [3.8.0 Deprecations and breaking changes](https://github.com/vert-x3/wiki/wiki/3.8.0-Deprecations-and-breaking-changes).

**Comment by sophokles73** [comment]
we have (manually) upgraded to Netty 4.1.39.Final already (#1450). I think we should defer this upgrade to post 1.0.0 as it will also require several new CQs ...

**Comment by sophokles73** [comment]
closed via #1634
