### ISSUE TITLE
Additional latency metrics for hono adapters

### ISSUE THREAD

**Issue by Christian-Schmid** [eclipse/hono#1469]
Hi Hono Devs,

this is kind of a feature request:

To get a better understanding of the behavior of Hono adapters during load scenarios it would be helpful to have some metric indicating the duration of requests to the different hono apis involved when processing incoming messages.

Specifically we would be interested in metrics as follows (to give an example):
- ` hono_registration_avg_response_time`: a metric that represent average response time of calling registration api
- `hono_tenant_api_avg_response_time`: a metric that represent average response time of calling tenant api
- `hono_credentials_api_avg_response_time`: a metric that represent average response time of calling device authentication api

Furthermore if there are timeouts occurring this could be helpful too:
- `hono_registration_api_timeouts`: A metric that represent how many timeout errors occurred when invoking the registration api.
- `hono_tenant_api_timeouts`:  A metric that represent how many timeout errors occurred when invoking the tenant api
- `hono_credentials_api_timeouts`:  A metric that represent how many timeout errors occurred when invoking the credentials api

What do you think, would make such metrics sense, or is there maybe already an existing way to collect such information?

Thanks 
Chris

**Comment by sophokles73** [comment]
@Christian-Schmid is this still an issue for you?

**Comment by Christian-Schmid** [comment]
Good question :-)
Honestly I haven't been missing those metrics anymore since raising this issue. 
Back then we were interested in them while analyzing some timing issues in our cluster.
Meanwhile we also used the jaeger tracing information to debug such cases.

Fmpov we can close the issue for now. And if someone is missing them, we can reopen.

**Comment by sophokles73** [comment]
@Christian-Schmid we have added some similar [metrics for sending telemetry and events downstream](https://www.eclipse.org/hono/docs/api/metrics/#protocol-adapter-metrics). Maybe these are of interest to you instead.
