### ISSUE TITLE
Online State race condition for clustered adapter

### ISSUE THREAD

**Issue by avgustinmm** [eclipse/hono#1483]
In https://www.eclipse.org/hono/docs/concepts/connection-events/ and https://www.eclipse.org/hono/docs/api/event/#connection-event Hono defines connect/disconnect events. This could (should be able to) be used for maintaining connection status for devices that connects with protocols supporting long living connections (e.g. MQTT, AMQP, GS Adapter). 

However, generally the adapters are assumed to scale & be fault tolerant- i.e. to run on multiple hosts. Then how a backend app is supposed to maintain online state. Suppose we have the following flow:	
1. device connects to node1 -> send connected event -> backend app make status: online
2. connection drop but node1 doesn't have notification (wait for timeout), or understand after some time), - for instance GS Adapter users http for handing connection.
3. device connects again -> this time to node2 -> send connect event -> backend app make status: online -> no change
4. node1 understands (possibly after a timeout) that connection is dead -> send disconnect event -> backend app make status: offline
5. now device is connected but it's status is offline

How do you solve this issue for standard MQTT/AMQP adapters of that kind?
Wouldn't be better to specify field (along with source) that will hold the node (e.g. node). Then the backend app may keep who notified for last connection and update only if receive disconnect from that node? 
Or you could change source semantic to be not the adapter name but node id or both (e.g. hono-mqtt:node_id)

**Comment by ctron** [comment]
I don't think you can implement an "online state" using the connection events.

You can only use them as an indication that some device connected or disconnected. In the end, one device could (using the same credentials) connect twice.

I think now that we have the device connection service, we might be able to use that as a way of generating a global "online" flag storage.

**Comment by avgustinmm** [comment]
Which devices are supposed to open simultaneous connections? Why shall they do that? 
Even if it is allowed I suppose that the main case will be with single connection at a time. In such cases such approach could help. Also, even in case of multiple concurrent connections from single device having connected/disconnected & node a backend app could do some calculation of online state. 

How could I use device connection service for online state? It only, AFAIU, manage last device's gateways which could not help here. Btw, if multiple connections are allowed then why not device concurrently connecting via multiple gateways? Then does last gateway is really the current?

**Comment by ctron** [comment]
> Which devices are supposed to open simultaneous connections? Why shall they do that?

Because the implementation of the device side is buggy :wink:

> How could I use device connection service for online state? It only, AFAIU, manage last device's gateways which could not help here.

That is why we would need to extend it. In order to support the functionality you ask for. I think it is a reasonable request. And I think we should do it. I simply think that the connection events are not the proper way do it.

**Comment by calohmn** [comment]
The described scenario, where the disconnected event gets sent although it shouldn't be, will be fixed for the MQTT and AMQP adapters via #2244. Infos on how to adapt *custom* protocol adapters will be added here after that's done.

**Comment by calohmn** [comment]
The described scenario has been fixed for the AMQP/MQTT adapter.

In order to fix a *custom* protocol adapter, its dependencies first have to be updated to a Hono version containing that fix (will be in Hono 1.5). The adapter code calling `ProtocolAdapterCommandConsumer#close(SpanContext)` then has to be adapted as shown here:
https://github.com/eclipse/hono/blob/e4e6e2464b51fe6f5c34b6a2db2826600b749ca4/adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java#L829-L841
not sending the disconnectedTtdEvent if the `close()` method future was failed with a `PRECON_FAILED` error.
