### ISSUE TITLE
Hono CLI: TLS connections fail with the AmqpCliClient 

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1484]
When using the Hono CLI client to send messages to the AMQP Protocol adapter (ie. with `--spring.profiles.active=amqp-send`) using username/password, a TLS connection cannot be established.

The adapter log just shows `failed to connect over ssl: javax.net.ssl.SSLException: handshake timed out`.

**Comment by b-abel** [comment]
@calohmn Maybe you'd like to take a look at the PR #1503.
