### ISSUE TITLE
Dropping S2I deployment in favor of IoT packages

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#1485]
I would like to discuss the idea of dropping the OpenShift S2I deployment for Hono. Currently we do have a bunch of deployment options, and I think it makes sense to reduce them a bit.

I also think it would make sense to focus on the [Eclipse IoT Packages](https://projects.eclipse.org/proposals/eclipse-iot-packages) project instead.

So, going forward, my proposal is to drop the OpenShift S2I deployment in favor of the existing Kubernetes Helm charts. We will of course test them, running on OpenShift, and document any OpenShift specific alternatives.

**Comment by sophokles73** [comment]
+1 for removing the S2I deployment
