### ISSUE TITLE
Improve usability of CLI

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#1486]
The CLI sample application is currently heavily based on the use of Spring Boot configuration. This is passed on to the user and is not what I expect from a CLI application. 
To customize the configuration, the user must understand Spring Boot and analyze the existing profiles. We should not expect this from every user. Especially since the use of the CLI is very prominent, because without it you can't even perform the simplest action in the "Getting started" guide (i.e. sending telemetry message).
I suggest to provide a simple command line usage, be it with arguments or interactive.

**Comment by ctron** [comment]
I had the same issue, and created a simple command line tool for that: https://github.com/ctron/hot

I would be happy to contribute that to the Hono project.

**Comment by johnMinelli** [comment]
I'm working on it. I committed the cli structure in my fork.

**Comment by b-abel** [comment]
The CLI currently contains logic for both the northbound applications (in the cloud, connecting against the messaging endpoint) and the (southbound) device side (connection against the AMQP protocol adapter). This dual role makes it confusing to use the CLI. Since both sides are independent of each other and only "by coincidence" use both AMQP. It would probably be better to provide two separate applications instead of starting the same one with two different profiles. 
The device side could build on the `AmqpAdapterClientFactory' from #1765. This is a client for the AMQP adapter (there is no implementation in Hono for this yet), which can be easily used for different use cases.  
The other application could probably be based on `ApplicationClientFactory' in the same way (maybe it could also replace the example application in `example/hono-client-examples/`).

**Comment by johnMinelli** [comment]
Hi, i got a deep sight in your PR code in the meantime to understand what do you mean. Do you suggest me to fork your code and finish the cli with your class or to setup and refine all with the actual AmqpCliClient class and add your factory in a second time when merged with master?

**Comment by b-abel** [comment]
Hi, @johnMinelli! Sorry for the late reply, I've been ill for a while. I was hoping the PR was ready. I'm currently clarifying the status. I'll probably know more tomorrow.

**Comment by johnMinelli** [comment]
'Ill' is a buzzword nowdays ahah. I've done this #1811 and commented some line to insert the factory you have made

**Comment by b-abel** [comment]
@johnMinelli FYI: My PR #1765 has been merged today.

**Comment by sophokles73** [comment]
This has been done with the new Picocli based CLI from #2914
