### ISSUE TITLE
HTTP-Adapter: Enable gateways to receive commands for a specific device

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1506]
The scenario here is about an **authenticated gateway** sending an event with a `hono-ttd` parameter (indicating it wants to receive a command).

Following the documentation (chapter `Publish an Event (authenticated Gateway)`), one might think the URL to use here would be `/event/${tenantId}/${deviceId}` (containing the device id, not the gateway id).

**However, the gateway will receive no command in that case** (provided the command is directed at the new `command` address).

**Background:**
The HTTP protocol adapter will create a mapping using the `device connection` API between the device id given in the URL and the gateway id (provided via the authentication data).
The HTTP protocol adapter will also create a command consumer with the "device id" in its link address.

Upon receiving a command, the GatewayMapper logic inside the protocol adapter will map the device id (given in the command address) to the gateway id. The problem is, that there is no command consumer listening on the gateway address.

**Proposed solution:**
Looking at the MQTT and AMQP adapters, we only support authenticated gateways that subscribe for commands using an address that doesn't contain a specific device id. 
In the MQTT case, the topic `command/+/+/req/#` is to be used, for AMQP it is the `command` link address.

Adopting a corresponding behaviour for the HTTP adapter, it would make sense to only support authenticated gateways sending events with the `hono-ttd` parameter using the `/event` URL (without device id). That would cause the gateway to receive a command for _any_ device connected to the gateway. The documentation should be adapted accordingly in that case then.

The **downside** here is, that the northbound application will receive the notification about the command consumer being ready associated with the _gateway id_ - although involvement of a gateway should probably be kept hidden to the application.
(In the MQTT and AMQP adapter cases, the notification event is also associated with the gateway id - but here the overall scenario could be that applications expect long-running command consumers, not waiting for notifications, not like in the HTTP case.)

**_EDIT_**
Solution shall be disabling the update of the last-known-gateway for the HTTP adapter instead - see below.

**Comment by sophokles73** [comment]
FMPOV the problem here is that the HTTP adapter maps the  device ID to the gateway ID using the Connection Service. However, in this case, no mapping is necessary because the HTTP adapter already creates a (short lived) command consumer scoped to the device ID (not the gateway ID).

**Comment by calohmn** [comment]
@sophokles73 Thinking more about it, I agree, that this is the better solution. 
The use case of the gateway saying "I want just one command for any kind of device that sent messages through me", seems rather unusual.

To implement the solution, we would then disable the update of the "last known gateway" for the HTTP adapter.

**Comment by sophokles73** [comment]
@calohmn I believe that should do the trick, yes.

**Comment by sophokles73** [comment]
@calohmn is this still relevant or is this superseded by #1523 ?

**Comment by sophokles73** [comment]
@calohmn ping

**Comment by calohmn** [comment]
@sophokles73 This is indeed superseded by #1523. Closing it here.
