### ISSUE TITLE
Make "Getting started" guide discoverable from docs

### ISSUE THREAD

**Issue by selobosi** [eclipse/hono#1508]
I was puzzled for a couple of minutes trying to find the "Getting Started Guide" from https://www.eclipse.org/hono/docs/. There are a number of guides on the left ("User Guide", "Admin Guide", "Developer Guide"). I was desperately looking for the "Getting Started" link. Had it been renamed? Been integrated into another part of the docs? Hm, no.

Ok, so currently https://www.eclipse.org/hono/getting-started/ is only reachable from https://www.eclipse.org/hono/.

It would be nice to have at least a link to the Getting Started Guide integrated into https://www.eclipse.org/hono/docs/.

**Comment by sophokles73** [comment]
I guess the reason for not including the Getting Started guide in the documentation is that the docs are specific to the particular Hono version whereas the Getting Started guide is only maintained for the most recent version that we want people to use when getting started with Hono.

@b-abel can we still add a generic link to the documentation page's menu which always points to the Getting Started guide on the home page?

**Comment by b-abel** [comment]
@sophokles73 Sure. I'll provide a PR.

**Comment by sophokles73** [comment]
@selobosi 

can this be closed with the latest changes that @b-abel made?

**Comment by selobosi** [comment]
Thanks for adding those links! I see one possible improvement: What about adding these links at the top, above "Concepts", instead of adding them at the bottom? I'd expect the "Getting Started" Guide to be the initial and brief introduction to a project, having it at the top would reflect a suggested reading order. What do you think?

**Comment by sophokles73** [comment]
We already have it prominently on the project's landing page. In fact, the *Getting Started* link is the first link you find on that page. The Documentation page is not the landing page ...

**Comment by selobosi** [comment]
Ok, cool, then this issue can be closed, I guess.
