### ISSUE TITLE
Command & Control: Give more than one credit for receiving commands for gateways

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1515]
Currently, the AMQP and MQTT adapters will only return _one_ credit on the command consumer link once they have processed a command.

I think this may cause delays when applications are trying to send several commands at once, possibly directed at a gateway that consumes commands for several devices.

**Comment by calohmn** [comment]
We should make the initial credits, sent upon successful command consumer creation in `DeviceSpecificCommandConsumer`, configurable here, ie. introduce a protocol adapter config option for this.

The `preFetchSize` in the `createReceiver` invocation in `DeviceSpecificCommandConsumer` should probably be kept 0 since we don't want automatic credit handling (credits need to be sent manually once the command has been acknowledged by the device, which is potentially done *after* the message handler of the command consumer has finished).

**Comment by calohmn** [comment]
There is already a `initialCredits` configuration property on the `commandConsumerFactory` connection.

For the HTTP adapter (receiving only one command at a time) we have to set the initial credits for the `DestinationCommandConsumer` to **1**. For the `MappingAndDelegatingCommandConsumer` (using the same `commandConsumerFactory` connection), the initial credits should be a higher value, because the incoming command there might be forwarded to another protocol adapter.
Therefore we cannot just force the `initialCredits` in the HTTP adapter `commandConsumerFactory` connection properties to be 1 here. We need instead to provide a `isConsumerForSingleCommand` parameter to `DeviceSpecificCommandConsumer.create`, to set the "1" credit in that case.

**Comment by calohmn** [comment]
Concerning the `isConsumerForSingleCommand` flag (see above command; to be set to `true` for the HTTP adapter):
On second thought, I don't think we need this, just as I don't think we don't need to explicitly only send *1 credit* in the HTTP adapter case on the device specific consumer link.
Provided the new `command` endpoints are used, messages on the *device specific consumer link* are only sent by the protocol adapter itself (DelegatedCommandSenderImpl) and not by the northbound applications. Therefore the *1 credit* doesn't reach the northbound application anyway.

**Comment by sophokles73** [comment]
@calohmn I agree with your arguments. Does this mean that we can close this issue as *won't fix*?

**Comment by calohmn** [comment]
No, we should still apply the `initialCredits` configuration property (set on the `commandConsumerFactory` connection) to the `DeviceSpecificCommandConsumer.create` method. I'll create a PR for that.

**Comment by calohmn** [comment]
The change has been committed. A further note on this:

> The `preFetchSize` in the `createReceiver` invocation in `DeviceSpecificCommandConsumer` should probably be kept 0 since we don't want automatic credit handling (credits need to be sent manually once the command has been acknowledged by the device, which is potentially done *after* the message handler of the command consumer has finished).

`preFetchSize` has been set to the initial credits now (thereby enabling automatic credit handling). The manual credit handling (after waiting for command acknowledgement from the device) is not really needed anymore since there is the tenant-scoped `MappingAndDelegatingCommandConsumer` now in between (also having automatic credit handling) meaning that we can't flow an exact device-specific number of credits to the AMQP messaging network anymore anyway. We rather need to make sure that there is not too few credits being provided.
