### ISSUE TITLE
Small usability enhancement for insecure port configuration

### ISSUE THREAD

**Issue by sysexcontrol** [eclipse/hono#152]
To let Hono listen to an insecure (unencrypted) AMQP port it is currently necessary to set the property "insecurePortEnabled" to true.

This created some confusion when the insecurePort was explicitly set but not enabled.

Thus a small change should be implemented as following:
If the insecure port number "insecurePort" is explicitly set, Hono should also open this port (and not insist on the boolean property).
To open the standard AMQP port for unencrypted connections, it remains sufficient to enable it by setting the above flag to true (and not setting the insecurePort explicitly).

**Comment by sophokles73** [comment]
Sounds reasonable, if you have a PR at hand, we can still get it into 0.5-M5 ....

**Comment by sysexcontrol** [comment]
Will provide it very soon. Just working on the documentation.
