### ISSUE TITLE
Add introductory Concept Page to Documentation

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#1571]
The documentation could benefit from an introductory concept page that gives a brief overview of Hono's idea, core features, and key terms. Ideally, it would specify the order in which the other concept pages should be read.

**Comment by b-abel** [comment]
As far as I remember, @dejanb volunteered to write this.

**Comment by b-abel** [comment]
Includes #1559.

**Comment by b-abel** [comment]
Should IMHO explain the terms "downstream/upstream" and "northbound/southbound".

**Comment by b-abel** [comment]
@dejanb, are you working on this? Otherwise, I volunteer to provide a PR for it.

**Comment by sophokles73** [comment]
closed via #2580
