### ISSUE TITLE
Device management API credential example does not match scheme

### ISSUE THREAD

**Issue by mbaeuerle** [eclipse/hono#1573]
The _Device Management API Spec_ shows the following example request when making a _credentials PUT_: 
![image](https://user-images.githubusercontent.com/1345394/66826379-9f428300-ef4c-11e9-911e-390bd8a39775.png)
https://www.eclipse.org/hono/docs/api/management/#/credentials/setAllCredentials

This does not match the scheme of `CredentialsSet` which defines that instead of a single credential an array of credentials should be given in the body.

In the Hono example device registry the `CredentialsSet` scheme with arrays is also used:
https://www.eclipse.org/hono/docs/user-guide/device-registry/#update-credentials-for-a-device

Which of the ones is the right one? I guess the `CredentialsSet` scheme defines it the correct way, as otherwise it would be not possible to create multiple credentials with different type for one device.

**Comment by dejanb** [comment]
You are right, the example is wrong. I tackled that as a part of #1574. Please note, that this hashed password example is being deprecated (per pr), so using pwd-plain is the preferred way going forward.

**Comment by sophokles73** [comment]
@mbaeuerle can this be closed with the changes @dejanb made?

**Comment by mbaeuerle** [comment]
@sophokles73 yes now it looks consistent!
