### ISSUE TITLE
Document concept behind C&C handling for gateways

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1585]
The concept behind how commands are handled in scenarios involving gateways should be documented. This involves the AMQP message flow as well as the implementation regarding the different command consumer classes.

Related issues: #1523, #930.
To be kept in mind: the concept might change again for Hono 1.1.0 - see #1272.

**Comment by sophokles73** [comment]
@calohmn are you planning to add this to 1.0.0? Or will this be added after the release?

**Comment by calohmn** [comment]
@sophokles73 after the 1.0.0 release.

**Comment by sophokles73** [comment]
@calohmn is this done, i.e. can we close this?

**Comment by calohmn** [comment]
yes, closing it.
