### ISSUE TITLE
No REGISTRY_IP found

### ISSUE THREAD

**Issue by BobOntario** [eclipse/hono#1594]
I deployed hono using minikube /helm to the Linux server through  terminal in Windows Laptop. The deployment is successful.  I executed:

export REGISTRY_IP=$(kubectl get service hono-service-device-registry-ext --output='jsonpath={.status.loadBalancer.ingress[0].ip}' -n hono)

echo $REGISTRY_IP

return nothing

After executed " kubectl tunnel", the output is 

machine: minikube
	pid: 29524
	route: 10.96.0.0/12 -> 192.168.1.36
	minikube: Running
	services: [hono-adapter-amqp-vertx, hono-adapter-http-vertx, hono-adapter-mqtt-vertx, hono-dispatch-router-ext, hono-service-device-registry-ext]

Which IP is for REGISTRY_IP?  do i need assign one of them to REGISTRY_IP?

BTW, when I tried to see dashboard and executed "kubectl port-forward service/hono-grafana 3000 -n hono &" , I got 
Forwarding from 127.0.0.1:3000 -> 3000
Forwarding from [::1]:3000 -> 3000

I can't access to it using "http://localhost:3000" because my hono is deployed in the server.  I checked the services in server:

tcp        0      0 127.0.0.1:3000          0.0.0.0:*               LISTEN      50381/kubectl

How can I know IP for dashboard ?

**Comment by sophokles73** [comment]
> I deployed hono using minikube /helm to the Linux server through terminal in Windows Laptop. 

Not sure what this is supposed to mean. Are you running a LInux VM on your Windows machine?

**Comment by BobOntario** [comment]
No. Linux server is in remote side. Hono is deployed in it. I used Windows based terminal to connected to the server and run all commands.

**Comment by sophokles73** [comment]
So, you have deployed Hono to a minikube instance running on another (Linux) host, right?

**Comment by BobOntario** [comment]
Yes

**Comment by sophokles73** [comment]
Are you trying to access Hono's endpoints from the windows machine or from the Linux machine?

**Comment by BobOntario** [comment]
Should be windows machine. Linux is a server, no browser

**Comment by sophokles73** [comment]
So, you are not ssh'ing into the linux machine to run the curl commands there but you are running curl from our Windows cmd shell, right?

**Comment by BobOntario** [comment]
I used windows based terminal connected to Linux   server. Run curl within this terminal. It is required to login to Linux server first. It should be in LiNux environment.

**Comment by sophokles73** [comment]
Ok, caan you then post the output of `kubectl get service -n hono`?

**Comment by BobOntario** [comment]
Will post it evening.

**Comment by BobOntario** [comment]
root@ecs-f52a-1:~# kubectl get service -n hono
NAME                                      TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                           AGE
hono-adapter-amqp-vertx                   LoadBalancer   10.111.137.11    <pending>     5672:32672/TCP,5671:32671/TCP     21h
hono-adapter-amqp-vertx-headless          ClusterIP      None             <none>        <none>                            21h
hono-adapter-http-vertx                   LoadBalancer   10.105.221.74    <pending>     8080:30080/TCP,8443:30443/TCP     21h
hono-adapter-http-vertx-headless          ClusterIP      None             <none>        <none>                            21h
hono-adapter-mqtt-vertx                   LoadBalancer   10.98.196.138    <pending>     1883:31883/TCP,8883:30883/TCP     21h
hono-adapter-mqtt-vertx-headless          ClusterIP      None             <none>        <none>                            21h
hono-artemis                              ClusterIP      10.106.118.188   <none>        5671/TCP                          21h
hono-dispatch-router                      ClusterIP      10.108.234.77    <none>        5673/TCP                          21h
hono-dispatch-router-ext                  LoadBalancer   10.99.92.220     <pending>     15671:30671/TCP,15672:30672/TCP   21h
hono-grafana                              ClusterIP      10.101.216.24    <none>        3000/TCP                          21h
hono-prometheus-server                    ClusterIP      10.96.152.66     <none>        9090/TCP                          21h
hono-service-auth                         ClusterIP      10.102.212.26    <none>        5671/TCP                          21h
hono-service-auth-headless                ClusterIP      None             <none>        <none>                            21h
hono-service-device-connection-headless   ClusterIP      None             <none>        <none>                            21h
hono-service-device-registry              ClusterIP      10.108.142.177   <none>        5671/TCP                          21h
hono-service-device-registry-ext          LoadBalancer   10.106.42.140    <Pending>     28080:31080/TCP,28443:31443/TCP   21h
hono-service-device-registry-headless     ClusterIP      None             <none>        <none>                            21h

**Comment by sophokles73** [comment]
> how can i make it as the host IP of Linux server?

that would require you to re-configure the networking of the VM that minikube starts under the hood for your kubernetes cluster. THe minikube deployment is intended to be used for local testing, it is not supposed to be used from outside of local host.

I am not sure what you are trying to achieve, but if it is going through the getting started guide, then you should simply run your curl commands on the Linux host that you have set up minikube on. If you want to set up a full fledged kubernetes cluster that is accessible from outside of the local host, you should follow the kubernetes installation guide(s). One good option is to use one of the managed service offerings from the usual cloud providers. Hono's documentation also comes with instructions for [doing this on Azure](https://www.eclipse.org/hono/docs/deployment/create-kubernetes-cluster/#setting-up-an-environment-on-microsoft-azure).

**Comment by BobOntario** [comment]
I want to integrate hono, ditto and vorto together to see how them work. Which way is best?

**Comment by BobOntario** [comment]
If I want to test to see whether my device connected to hono, without external IPbin hono , how my device can connected to hono?

**Comment by BobOntario** [comment]
I can make my intention more direct.  We want to test few devices with hono. If we follow deploy way in the documentation, we can't get external ip, devices can't connected to hono.  how can we do?  do we need go other way to deploy hono?

**Comment by sophokles73** [comment]
@BobOntario I will be in a better position to help you if you tell me what you are actually doing and what results you are experiencing that you did not expect.
First and foremost, which version of Hono have you deployed and what kind of kubernetes cluster have you deployed to. Is that still a minikube running on Linux?

**Comment by BobOntario** [comment]
I am using hono 1.0-M7, which is from eclise-hono-1.0-M7-chart.tar.gz.  yes, still is minimize running on Linux.

**Comment by sophokles73** [comment]
If you are deploying Hono to minikube you usually have minikube running in a VM which is running its own network. You may be able to configure the VM so that the service endpoints exposed by the Hono components are accessible from the network that the host computer (your Linux machine) is running on. However, that may be specific to the virtualization technology you are using. I will not be able to help you with that, sorry. That said, the best option for you to go is probably to deploy Hono to a kubernetes cluster that is attached to a public network, e.g. a hosted kubernetes offering like Azure AKS or AWS EKS. You can then connect your devices via internet. Alternatively, you can also set up a kubernetes cluster on your local network. Please refer to the kubernetes installation instructions for details ...

**Comment by BobOntario** [comment]
You don't recommend minikube?

**Comment by sophokles73** [comment]
> You don't recommend minikube?

Not for production environments. It is supposed to be used for local testing only.
