### ISSUE TITLE
Telemetry API : "At least once" and "At most once" QoS levels

### ISSUE THREAD

**Issue by ppatierno** [eclipse/hono#16]
When the device sends a telemetry message, Hono doesn't reply with any data but it leverages on AMQP delivery state. The delivery state is provided by Hono with the "disposition" message and can be ACCEPTED or REJECTED as described but ...
... it's true if the device sends the messages with "AT LEAST ONCE" QoS level so it means that the message isn't pre-settled on the device but it needs the disposition frame from the receiver (Hono).
This information is used for re-delivery of the message by the device (if Hono doesn't receive it).

In the telemetry scenario where data is sent (sometimes) at high rates and where if we lost a message a new one will come soon, the "AT LEAST ONCE" QoS is useless.
The "AT MOST ONCE" is feasible and it means that the device sends the message in a pre-settled state so ... the receiver (Hono) won't send any disposition message because the sender isn't waiting for that.

Current API describes the "AT LEAST ONCE" scenario speaking about possible delivery states (ACCEPTED and REJECTED) but the "AT MOST ONCE" should be expected as well.

**Comment by sophokles73** [comment]
That's a good point, Paolo :-)

I guess you are proposing to support `AT MOST ONCE` semantics *as well*, i.e. in addition to the already described `AT LEAST ONCE` semantics, right?
In this case we would want to consider the client's preferences as indicated in the link establishment, I guess.

**Comment by grs** [comment]
The desired delivery guarantees can be specified in the attach (snd-settle-mode/rcv-settle-mode), as Kai points out. However it might be worth spelling out the approach for re-attaching (assuming durable subscriptions are expected for at-least-once deliveries) as that is not as clear cut in AMQP as it could be.

**Comment by ppatierno** [comment]
Yes @sophokles73 It could be great to provide both QoS levels

**Comment by sophokles73** [comment]
@grs, do you know whether the `ProtonReceiver.getRemoteQoS()` method is actually based on *snd-settle-mode/rcv-settle-mode* values, i.e. can I use this method in order to determine the client's intended delivery guarantees to be used?

**Comment by ppatierno** [comment]
@sophokles73 yes you can use it, it just reads the remote sender settle mode from the underlying Link implementation of the Qpid Proton library.
Just to add another information, the Vert.x Proton implementation maps the concept of "settlement" to "QoS" but it doesn't handle MIXED (when a sender can mix pre-settle, non settle mode during different transfers on the same link).

**Comment by grs** [comment]
You can also just look at the received message's delivery. If that is settled, no acknowledgement is expected. (The default snd-settle-mode is 'mixed' meaning that the settlement is decided by the sender message-by-message).

**Comment by sophokles73** [comment]
I see. I think it makes more sense to do this at the message level because a Protocol Adapter will  report data on behalf of multiple devices which might report data of arbitrary importance and sampling rate for which different settle modes might be required/feasible.

**Comment by sophokles73** [comment]
I think we have discussed this thoroughly in our face-to-face and have also documented the results in the [Telemetry API](/eclipse/hono/wiki/Telemetry-API).

@ppatierno, if you feel the same way, can you close this issue?

**Comment by ppatierno** [comment]
@sophokles73 absolutely. I'm going to close it.
