### ISSUE TITLE
Deploy Sandbox in local

### ISSUE THREAD

**Issue by BobOntario** [eclipse/hono#1602]
Had some problems to deploy hono in local through minikube as mentioned #1594 and 1527.  I can't expose an IP so that other computer can access it.

So I want to deploy hono into local by following Sandbox deployment script (deploy/src/main/sandbox) - Doscker swarm way, or directly deploy Sandbox in local.  To do this, what I need to change deployment scripts:

sandbox_deploy.sh
create_sandbox_cert_secrets.sh

For example, i need change hono.eclipse.org to my localhost.  Where can i find :
hono.eclipse.org-cert.pem
hono.eclipse.org-key.pem
/etc/letsencrypt/live/hono.eclipse.org/fullchain.pem
/etc/letsencrypt/live/hono.eclipse.org/privkey.pem

**Comment by sophokles73** [comment]
You will need to create your own certificate(s) and adapt the deployment script(s) accordingly.
Please refer to the Docker Swarm and Lets Encrypt documentation for details. The Sandbox deployment is not a supported way of deploying Hono. We use it internally only until the Eclipse IoT Working Group will have its own Kubernetes cluster.
