### ISSUE TITLE
Can we start hono using docker compose ?

### ISSUE THREAD

**Issue by BobOntario** [eclipse/hono#1606]
For test purpose, can I start honor using docker compose ? I checked Ditto that it can be started using docker compose..
Thanks

**Comment by sophokles73** [comment]
You can, of course, create your own Docker Compose file for starting up Hono. However, I am afraid that we won't be able to support you in doing so.

**Comment by BobOntario** [comment]
Understood. Can you give some clues how to create docker compose file for hono?

**Comment by sophokles73** [comment]
You might want to take a look at the [Docker Compose docs](https://docs.docker.com/compose/) and then try to migrate the service definitions from the sandbox shell scripts to your compose file.
Good luck!

**Comment by AntrikshNarang** [comment]
I tried dockerizing a hono app, but it doesn't seem to work, i don't know the problem is with wrangler or something, the port 8787 doesn't work in my localmachine after running the docker container.

Here's the Dockerfile for reference
```dockerfile
FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npx prisma generate

CMD ["npm", "run", "dev"]

EXPOSE 8787
```

**Comment by mahe-gi** [comment]
it wont run because your Dockerfile doesn't have cloudflare worker  runtime  / ur using node:20 image hono is for serverless ! i think so
