### ISSUE TITLE
Misleading customize[*]Config methods in AbstractAdapterConfig

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1607]
The `AbstractAdapterConfig.customizeRegistrationClientFactoryConfig` method javadoc states:
````
* Further customizes the properties provided by the 
* {@link #registrationClientFactoryConfig()} method.
* <p>
* This method does nothing by default. Subclasses 
* may override this method to set additional
* properties programmatically.
```` 
This sounds to me as if the `registrationClientFactoryConfig` bean is created first using the "hono.registration" configuration properties, and *then* the `customizeRegistrationClientFactoryConfig` method is called to work on the loaded properties.
The implementations in the overridden `customizeRegistrationClientFactoryConfig` methods support this assumption (conditionally setting a property there).

**But**, actually, it is the other way round. The bean is initialized with the properties from the `customizeRegistrationClientFactoryConfig` method and then the configuration properties are loaded on top.

The same applies for the other `customize[*]Config` methods.

The documented behaviour makes more sense to me, therefore the implementation should be changed IMHO.

**Comment by sophokles73** [comment]
I agree that the behavior that is documented in the JavaDocs is not consistent with the actual runtime behavior. I also agree that a *post-construction* customization as described in the JavaDocs would be nice. However, we are currently using this mechanism only for setting the AMQP client container name, if I am not mistaken. Implementing the documented behavior would require to impleemnt a Spring `BeanPostProcessor` based on my understanding of how the Spring bean container works. This would a) increase our dependency on Spring once more and b) would require an additional class with ugly if/switch statements on bean name and type.

Instead, I would like to propose to simply change the JavaDocs and method names and keep the current implementation as it actually provides what we want to do. WDYT @calohmn ?

**Comment by calohmn** [comment]
> Implementing the documented behavior would require to impleemnt a Spring BeanPostProcessor based on my understanding of how the Spring bean container works.

I think it could also be done just by defining a 2nd bean with a qualifier like `@Qualifier("registration_original")` and loading the configuration properties in there. That bean could then be injected into the existing bean method where `customizeRegistrationClientFactoryConfig` would get called to adapt the properties.

As that is also not a particularly pretty solution and as there probably isn't much need for such a _post-construction_ customization anyway as it seems, I agree that we could instead just change the javadoc and rename the "customize" methods to "setRegistrationClientFactoryConfigDefaults" and the like. I'll create a PR.
