### ISSUE TITLE
Command message correlation ID not preserved when sending to AMQP device

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1610]
When sending a command message to an AMQP device, the command message correlation ID (set by the northbound application) currently is not (always) preserved, so that the AMQP device might get a different correlation ID.

**Comment by sophokles73** [comment]
Can you be a little more specific and e.g. provide an example for the circumstances under which this happens?

**Comment by calohmn** [comment]
This happens when a command arrives at a protocol adapter instance that the target device isn't connected with. Meaning a scenario where the command is delegated to the appropriate adapter instance by forwarding it on the device-specific command address to the AMQP messaging network.

The issue doesn't occur, when the command arrives at a adapter instance that the target device is connected to. Then the message correlation id is preserved.

**Comment by sophokles73** [comment]
And in the former case, the correlation ID is always lost/dropped/whatever? Or does this happen sporadically only?

**Comment by calohmn** [comment]
In the former case, the correlation ID is always set to the message id of the original command message. It's only a small fix, I will commit it shortly.

**Comment by sophokles73** [comment]
@calohmn I wonder how a device could ever succesfully respond to a command in the former case then. Or is there no test scenario covering this case?

**Comment by calohmn** [comment]
@sophokles73 As far as I see it, in our tests, the correlation id isn't set, so the message id was used anyway.

**Comment by calohmn** [comment]
Fixed with 37a9d35a6dc554853d52f5189d564852d1d911ec and bbd9b68f8bb2bc00aa1d2937a717011cfa01d043. Also adopted in 1.0.x branch.
