### ISSUE TITLE
Use SNI to select server certificates out of set.

### ISSUE THREAD

**Issue by boaks** [eclipse/hono#1617]
For central deployments with multiple applications it may be required, that the same protocol adapter endpoints are reached by different DNS names. For simple server certificate validation that would require either "long list of subject-alternative-names" or a mechanism to select a matching certificate out of a set of certificates by that DNS name. 
Therefore I would like to be able to use [SNI](https://tools.ietf.org/html/rfc6066#section-3) to select a matching certificate out of a set.
To do so, the configuration should be extended to multiple certificates and related private keys.
The configuration should contain the DNS hostnames as provided in the SNI to lookup the specific certificate-private-key pair.

**Comment by sophokles73** [comment]
Sounds reasonable. The vert.x framework used by Hono already supports using SNI by means of putting multiple key/cert pairs into a key store and use that for the server side identity. The only thing currently missing in Hono for this to work is actually enabling SNI in the NetServer.

**Comment by bordeuax** [comment]
Hi @sophokles73 , I want to clarify (and yes of course correct me if i am wrong) that currently Eclipse Hono can be configured with two types of Key/certificate format JKS and PEM . We will have only in case of JKS full SNI enabled endpoints. And the requirements for SNI will be configuration key "sni: true" and JKS format for key/certificate.

**Comment by sophokles73** [comment]
> currently Eclipse Hono can be configured with two types of Key/certificate format JKS and PEM

It's actually three types: JKS, p12 and plain PEM. The former two are key store formats and may contain multiple keys/certs whereas the last one may only contain a single key/cert.

You can use any of the file formats for SNI, though. See [vert.x docs for more info](https://vertx.io/docs/vertx-core/java/#ssl) ...

**Comment by bordeuax** [comment]
Thanks for precising regarding JKS, P12 and PEM formats. My point here is to have full enable SNI endpoints that not depending of the certificate format. From technical point of view we can have multiple PEM files because [PemKeyCertOptions]( https://vertx.io/docs/apidocs/io/vertx/core/net/PemKeyCertOptions.html) support also a list of files.
