### ISSUE TITLE
Demo certs cannot be used for PEM file based TLS configuration

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#162]
The demo keys included in the demo-certs module are ECC based (not RSA) and the corresponding key and certificate PEM files not in PKCS8 format. This prevents them from being used for configuring the Hono server based on the `HONO_SERVER_KEY_PATH` and `HONO_SERVER_CERT_PATH` because vertx only supports RSA keys in PKCS8 PEM files.

It would therefore be better to use RSA based keys and use PEM files based on PKCS8.

**Comment by sophokles73** [comment]
fixed in 333c51b36557f55f6bec0516f5b12c2df2f47341

**Comment by ppatierno** [comment]
I have just updated the Hono server OpenShift deployment as well 1826d6941e8f4202adc399b97fa5accd115a0046
