### ISSUE TITLE
Charts folder missed in Eclipse Hono 1.0.1 Archive 

### ISSUE THREAD

**Issue by BobOntario** [eclipse/hono#1620]
Just tried to download Eclipse Hono 1.0.1 Archive from https://www.eclipse.org/downloads/download.php?file=/hono/eclipse-hono-1.0.1-chart.tar.gz
and found "charts" folder is missed in the package compared to Eclipse Hono 1.0.0 Archive.

Any thoughts?

**Comment by kaniyan** [comment]
@BobClaerhout In case of Hono, the _charts_ folder is generated automatically based on the dependencies declared in the `requirements.yaml`. It was never part of the _Hono Archive_. This is generated when you deploy Hono using  `helm install ...` or to generate explicitly `helm dependency update` can be used.

**Comment by BobOntario** [comment]
Eclipse Hono 1.0.0 Archive from has chart folder :)

**Comment by kaniyan** [comment]
> Eclipse Hono 1.0.0 Archive from has chart folder :)

I just downloaded the _Hono 1.0.0 Archive_  from the official [link](https://www.eclipse.org/downloads/download.php?file=/hono/eclipse-hono-1.0.0-chart.tar.gz&mirror_id=1135) and I didn't find _charts_ folder there :-)
There is a chance that the _charts_ folder might have generated in your local downloaded version, if you have already run `helm install ...` or `helm dependency ...`.

**Comment by BobOntario** [comment]
Can Eclipse Hono 1.0.0 Archive or Eclipse Hono 1.0.1 Archive be deployed in K8s v1.13.0?

**Comment by sophokles73** [comment]
> Can Eclipse Hono 1.0.0 Archive or Eclipse Hono 1.0.1 Archive be deployed in K8s v1.13.0?

This seems to be a new/other question than the one you originally raised. It also seems to be interesting for others to know the answer. May I therefore kindly ask you to post it on stackoverflow instead as pointed out on [our community page](https://www.eclipse.org/hono/community/get-in-touch/)?

Thanks for your understanding.
