### ISSUE TITLE
Only supported SASL mechanisms should be advertised to the client

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1635]
Currently a Hono component including an `AuthenticationService` implementation for handling the SASL exchange (e.g. the `FileBasedAuthenticationService` in the Hono Auth component) always indicates both `PLAIN` and `EXTERNAL` as supported SASL mechanisms to clients.

For `AuthenticationService` implementations that only support one or the other, the advertised mechanisms should be configurable.

**Comment by sophokles73** [comment]
@calohmn are you going to work on this? If so, please assign the issue to yourself and set a target milestone ...

**Comment by calohmn** [comment]
Yes, PR is #1640.
