### ISSUE TITLE
User guide and example code for implementing third party protocol adapter

### ISSUE THREAD

**Issue by mhemmeter** [eclipse/hono#1646]
The concept for a "third party protocol adapter" discussed in #1478 follows the generic pattern of using a gateway to connect devices to Eclipse Hono. 

The main use case discussed in the issue is to connect devices via proprietary protocols. I think it makes sense to provide a user guide explaining the setup in context of this use case as well as example code that shows how to implement a third party protocol adapter.

**Comment by mhemmeter** [comment]
I expect that many people implementing a third party protocol adapter will do so using the technology stack in Hono (Vert.x, Qpid Proton, ...). So I would propose to use exactly that stack in the example code.

**Comment by bs-jokri** [comment]
Hi @mhemmeter for the example code @eriksven and me were discussing using a similar approach as in [1]. So the technology stack you mentioned should be covered.

[1] https://github.com/eclipse/hono/blob/master/cli/src/main/java/org/eclipse/hono/cli/adapter/AmqpCliClient.java

**Comment by mhemmeter** [comment]
Yes, makes totally sense from my point of view. Following the Eclipse Hono has a consistent

**Comment by bs-jokri** [comment]
@eriksven To properly describe the Third Party Adapter feature we also need a proper documentation of the gateway group feature. These are the places in the documentation we need to adjust. If there is anything else, please add:

- https://www.eclipse.org/hono/docs/api/management/#/devices/createDeviceRegistration
- https://www.eclipse.org/hono/docs/api/device-registration/

**Comment by eriksven** [comment]
In light of the work on PR #1683 on gateway groups we decided to to postpone a PR for the user guide described in this issue since the realization of gateway group group is an fundamental aspect for the implementation of third party protocol adapters.

**Comment by sophokles73** [comment]
Closed via #1724
