### ISSUE TITLE
Remove dependency on Google Guava

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#1650]
We originally introduced the dependency on Guava for its Cache implementation. However, that has been moved to the Caffeine library which we are now using.

We currently only use Guava's `ToStringHelper` class in some value objects which doesn't seem to justify keeping the dependency. We therefore should replace the usage of `ToStringHelper` and then remove our dependency on Guava altogether.

**Comment by ctron** [comment]
There are new more locations using Guava. I will try to replace them as well.

**Comment by ctron** [comment]
Ok, we are using Guava for:
* toStringHelper (service-base, device registry)
* Base16 decoding (lorawan, sigfox)
* Reading resources (device registry)

Now we could replace all three features with custom code, but I fail to see the benefit now.

**Comment by sophokles73** [comment]
Ah, I didn't realize that we used the other features as well. I agree, that in this case we probably should keep Guava (for now) ...
