### ISSUE TITLE
TTD header semantics unclear in absence of message creation-time

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#1677]
The Telemetry API defines the TTD header value to be interpreted relative to the message's creation time. However, it neither defines the *creation-time* property to be mandatory nor does it define how the TTD is to be interpreted in the absence of a *creation-time* value.

**Comment by sophokles73** [comment]
IMHO we do not need to make the *creation-time* property mandatory but we should advise protocol adapters to set it. We definitely should document how a downstream application is supposed to determine the absolute point in time when the device will disconnect if the *creation-time* is not set.
My proposal would be to use the time of reception instead in this case.
WDYT @dejanb @calohmn @ctron ?

**Comment by boaks** [comment]
Do you mean, a "creation-time" based on the protocol-adapter receive time?
Or should that be the time, when the device sends the message and must therefore be included in the message?

**Comment by sophokles73** [comment]
@dejanb @calohmn @ctron any opinion?

**Comment by sophokles73** [comment]
> Do you mean, a "creation-time" based on the protocol-adapter receive time?
Or should that be the time, when the device sends the message and must therefore be included in the message?

@boaks If the protocol used by the device allows for it (e.g. AMQP 1.0 messages have a *creation-time* header field) then that value should be used (maybe after a short sanity check, e.g. making sure that the creation time is in the past to make up for erroneous device clocks). Otherwise, the time that the message has been received by the adapter could/should be used.

**Comment by boaks** [comment]
FMPOV, such a ttd is more a heuristic than a precise reliable mechanism.
To include a "creation time" "somewhere" (device or adapter) seems for me to be useful, if it's assumed, that processing a message within the "messaging infrastructure" may take reasonable time in relation to the value of the ttd. My impression is, that this processing time should be negligible. Are there any test-results that points to "not negligible"?

**Comment by sophokles73** [comment]
IMHO we can safely assume that it is negligible. If there is a consumer for the message at all, then the consumer should get the message in a few milliseconds. The TTD, in contrast, is specified in seconds ...

**Comment by sophokles73** [comment]
Actually, the Telemetry API *does* define a message's *creation-time* property to be mandatory, if the message contains a TTD.
