### ISSUE TITLE
Provide implementation for Credentials API

### ISSUE THREAD

**Issue by sysexcontrol** [eclipse/hono#169]
Hono needs an in memory implementation of the Credentials API as defined in the API documentation pages.

With providing this implementation the full API will be available in the code on server and client side.

**Comment by sophokles73** [comment]
@sysexcontrol is this done? Do we have the Credentials endpoint activated in *Device Registry*?

**Comment by sysexcontrol** [comment]
@sophokles73 : No,currently it is in the state of Release 0.5M6, so the credentials endpoint is only started in device registry if the profile "credentials" is activated. This is currently not done in the deplyoyment options we have.
I will do that in a soon coming PR inside this issue, afterwards we can close this one.

**Comment by sysexcontrol** [comment]
@sophokles73 : I am not sure if we should keep the profile "credentials", but since the credentials API may not always be implemented inside the device registry component, it would be a simple way to unconfigure it from device registry.
From M7 on, in our default deployments, we would activate the profile "credentials" (but having a longer SPRING_PROFILES config again then).
WDYT?

**Comment by sophokles73** [comment]
@sysexcontrol can this be closed?

**Comment by sysexcontrol** [comment]
Credentials endpoint enabled by default in M7 now.
Done in 99671e4fe6.
