### ISSUE TITLE
HonoConnection: add timeout for connection check

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1691]
Followup of #1673:

As implemented for #1673, the connection check in the HonoConnectionImpl class (`checkConnected` method) now waits for an ongoing connection attempt to finish.
It is implemented in such a way that this wait period spans across multiple reconnect attempts.

If the configured number of reconnect attempts is not limited (which is the default), there is no timeout mechanism currently in place for the `checkConnected` method.

In practice, this means that in case that all device registry instances become unavailable, the first telemetry/event request will _not_ time out. (Subsequent requests will time out, internally producing an "already trying to create a client for .." error.)

To solve this, I suggest letting `checkConnected` wait at most the configured `connect timeout` period (configured in ClientConfigProperties).
(An alternative would be to let `checkConnected` only wait for _one_ reconnect attempt. But in practise, upon shutting down of one device registry instance, there could be some quickly coming "connection refused" errors for the reconnect attempts before another device registry instance is targeted, therefore doing multiple reconnect attempts would be better.)

**Comment by calohmn** [comment]
> To solve this, I suggest letting `checkConnected` wait at most the configured `connect timeout` period (configured in ClientConfigProperties).

The `connect timeout` is by default 5s and a protocol adapter processing a telemetry/event request from a device while the device registry is down would run into this timeout twice (first for tenant API access, then for device registration/credentials access). 10s is just too much here.
And then there is the Kubernetes readiness/liveness check, each time calling `isConnected` (which then calls `checkConnected`) for _all_ services. This would also take way too much time.

_Therefore_ I think we should revert `checkConnected` to the old behaviour, not waiting for an ongoing connection attempt at all. Instead, a new `isConnected`/ `checkConnected` method with a timeout parameter could be introduced. This method then will wait at most the timeout value for an ongoing connection attempt.

Places to use this new method would be the `[*]ClientFactoryImpl` classes, in the `getOrCreate[*]Client` methods, e.g.:
`RegistrationClientFactoryImpl.getOrCreateRegistrationClient()`.
This would also mean that multiple concurrent `getOrCreateRegistrationClient` requests would wait inside the new `checkConnected` method - instead of only the first request getting there and the others causing a "already trying to create a client" error (with only 3 retries and 20ms waiting time in between).

**Comment by sophokles73** [comment]
@calohmn sounds reasonable to me
