### ISSUE TITLE
hono-service-device-registry-0 pod is Pending

### ISSUE THREAD

**Issue by soheilade** [eclipse/hono#1694]
i used hono helm chart to deploy hono and device registry pod is pending with this message
 `Warning  FailedScheduling  3m16s (x3 over 3m17s)  default-scheduler  error while running "VolumeBinding" filter plugin for pod "hono-service-device-registry-0": pod has unbound immediate PersistentVolumeClaims`

I have a k8s cluster with one master node and i removed the noschedule taint from the master node.
I do not have any persistant vol as 
`kubectl get pv -n hono `
shows 
`No resources found in hono namespace.`

can some body pointout the yaml of the pv? or any pointer is appreciated.

**Comment by sophokles73** [comment]
Your cluster needs to support [Dynamic Volume Provisioning](https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/) in order for the PV being dynamically created for the device registry.

**Comment by soheilade** [comment]
thanks Kai, I used this yaml to depoly dynamic provisioning in azure from [here](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/aks/azure-files-dynamic-pv.md)

`kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
  - cache=none
parameters:
  skuName: Standard_LRS`

but still my pod fails with the same error. any idea?

**Comment by sophokles73** [comment]
Did you specify the `azurefile` storage class to be used by the example device registry when deploying using helm, e.g.
```
helm install --set deviceRegistryExample.storageClass=azurefile ...
```

**Comment by soheilade** [comment]
yes here is my command 
` helm install hono eclipse-hono/ --dependency-update --namespace hono --set deviceRegistryExample.storageClass=azurefile`
i tried to uninstall and reinstall several times but 2 pods keeps failing in the pending state with the same error ` error while running "VolumeBinding" filter plugin for pod "hono-prometheus-server-84c57f68f5-clq5n": pod has unbound immediate PersistentVolumeClaims`

**Comment by sophokles73** [comment]
since you seem to be deploying to azure, have you tried to follow Hono's [Azure deployment guide](https://www.eclipse.org/hono/docs/deployment/helm-based-deployment/#deploying-to-azure-kubernetes-service-aks)?

**Comment by soheilade** [comment]
I actually did not use azure k8s service but I have installed a k8s cluster on a VM myself.

**Comment by sophokles73** [comment]
Well, the guide you where following to create the storage class seems to be based on AKS so I doubt that it will work on your home grown k8s cluster ...
Maybe you should rather follow https://kubernetes.io/docs/concepts/storage/storage-classes/ in order to set up your storage class. Also be sure to follow the docs for your particular version of kubernetes.

**Comment by soheilade** [comment]
Thanks Kai, I created this [issue ](https://github.com/MicrosoftDocs/azure-docs/issues/45796)in microsoft azure and apparently the only way to proceed is to use the AKS, However, I have problem downloading the helm chart into AKS. The problem is that when i run `wget https://www.eclipse.org/downloads/download.php?file=/hono/eclipse-hono-1.0.2-chart.tar.gz`, I cannot download this file. Could you please advise on this?

**Comment by sophokles73** [comment]
You'll need to use
```
wget "https://www.eclipse.org/downloads/download.php?file=/hono/eclipse-hono-1.0.2-chart.tar.gz&r=1" -O eclipse-hono-1.0.2-chart.tar.gz
```
in order to skip mirror selection.

**Comment by sophokles73** [comment]
@soheilade can this be closed?

**Comment by soheilade** [comment]
yes :)
