### ISSUE TITLE
eclipse/hono-service-auth:1.1.0-SNAPSHOT missing on index.docker.io

### ISSUE THREAD

**Issue by boaks** [eclipse/hono#1696]
Using the current commit on master (cde62cebf41f9), I executed 

```
mvn clean install
cd tests
mvn verify -Prun-tests
```

And got this error message:

> Unable to pull 'eclipse/hono-service-auth:1.1.0-SNAPSHOT' from registry 'index.docker.io' : {"message":"manifest for eclipse/hono-service-auth:1.1.0-SNAPSHOT not found: manifest unknown: manifest unknown"} (Not Found: 404) 

The tests "readme" points to a general getting started, but I couldn't find the mentioned "instructions on building the Docker images". maybe they could be found under a different topic.

So:
Is this error caused by a wrong local build process?
Or is there something missing?
Is there a guide, which explains, how to build the docker images?

**Comment by boaks** [comment]
I found the "mvn clean install -Pbuild-docker-image".
As link for "instructions on building the Docker images", [Building from Source](https://www.eclipse.org/hono/docs/dev-guide/building_hono/) maybe a better hint.

**Comment by b-abel** [comment]
You are right, building the images is no longer included in the getting started guide. I opened a PR that fixes this.

**Comment by boaks** [comment]
Thanks!
