### ISSUE TITLE
helm-based-deployment - "unknown flag: --name"

### ISSUE THREAD

**Issue by boaks** [eclipse/hono#1703]
helm v3.0.2

[The following commands generate the resource descriptors](https://www.eclipse.org/hono/docs/deployment/helm-based-deployment/)

```
# in directory: eclipse-hono-$VERSION
mkdir resources
helm dep update eclipse-hono/
helm template --name hono --namespace hono --output-dir resources eclipse-hono/
```

The last line reports:

```
Error: unknown flag: --name
```

Remove "--name hono" would not report that error. 
Is that a typo?

**Comment by sophokles73** [comment]
These are instructions for Helm 2. With Helm 3 there is no Tiller component required to be installed to kubernetes. Thus, the Helm 3 instructions only cover using `helm install` ...

**Comment by boaks** [comment]
OK, thanks!
`helm install` fails for local build "on my machine" :-).

**Comment by sophokles73** [comment]
did you follow the instructions given [here](https://www.eclipse.org/hono/docs/deployment/helm-based-deployment/#deploying-to-minikube)?

**Comment by sophokles73** [comment]
if you are building from master then you should follow the [dev docs](https://www.eclipse.org/hono/docs/dev/deployment/helm-based-deployment/#deploying-to-minikube)

**Comment by boaks** [comment]
That maybe my missing link, I didn't found in 
[building from source](https://www.eclipse.org/hono/docs/dev/dev-guide/building_hono/)
