### ISSUE TITLE
Sending commands to devices via gateway without last known gateway

### ISSUE THREAD

**Issue by alinaserg** [eclipse/hono#1712]
Hono supports communication with devices via multiple gateways. To send in such scenarios commands from northbound application to a device via appropriate gateway, the mapping between device and last known gateway from [device connection](https://www.eclipse.org/hono/docs/api/device-connection/) is used. 
That means that Hono forwards commands always to the gateway to which the device was last time connected.

In some use cases the commands must be sent to a device when the device has never sent any messages to Hono and it is the first interaction between Hono and device.
Right now we don't have solution for such scenario and commands won't be ever sent to a device without previous interaction.

It will be very useful for our customers to have such a feature.

**Comment by sophokles73** [comment]
This problem is also addressed by #1272

**Comment by calohmn** [comment]
With #1272, the logic for choosing to which gateway a command will be sent has been changed.
Taking the [documentation](https://www.eclipse.org/hono/docs/user-guide/mqtt-adapter/#receiving-commands-authenticated-device) of how command are sent to MQTT devices, the logic is as follows:
> If no device-specific command subscription exists for a command target device, but one gateway, that may act on behalf of the device, has subscribed to commands for all its devices, then the command message is sent to that gateway.

> If multiple gateways have initiated such generic subscriptions, the protocol adapter may have to decide to which gateway a particular command message will be sent to. In case the command target device has already sent a telemetry, event or command response message via a gateway and if that gateway has created such a command subscription, that gateway will be chosen. Otherwise one gateway that may act on behalf of the command target device and that has an open subscription will be chosen randomly to receive the command message.

That means the "last known gateway" information is now only used when _multiple_ gateways (configured to be able to act on behalf of the target device) have actually subscribed for commands. And if no "last known gateway" information is set for a particular device, one of these gateways will be chosen at random as the command target. 

So commands will be forwarded to a gateway regardless of whether the device has already connected itself.

@alinaserg Can this issue be closed then?

**Comment by alinaserg** [comment]
@calohmn it means, that with the current implementation there's always a possibility that the command will be sent to the random gateway and a device is connected to the another gateway, so the device won't receive this command and actually it won't even be transparent to the northbound application that the command hasn't reached the device, correct?
To avoid it, the initial communication with event or telemetry is necessary, otherwise we don't provide any guarantees, as it's impossible.

**Comment by calohmn** [comment]
@alinaserg correct

**Comment by alinaserg** [comment]
@calohmn thanks, then let close the issue.
