### ISSUE TITLE
Set TTL for Connection Events

### ISSUE THREAD

**Issue by alinaserg** [eclipse/hono#1714]
There's a specific event message type "Connection events" to inform northbound application about the connection status of the device.

Right now it is not possible to set TTL for such type of events, it actually may cause storage problem, when there's no northbound application to which these connection events must be forwarded or when a northbound application listening only to telemetry messages. In such cases connection events won't be ever delivered to northbound application and won't be automatically deleted.

To prevent such cases TTL for Connection Events may be set and applied.

**Comment by Alfusainey** [comment]
my understanding is that the current default implementation for this event type uses the `downstream message sender` implementation to send such events. this sender timeouts if the peer does not acknowledge receiving the message. does this solve the problem? am trying to understand how i can approach this

**Comment by sophokles73** [comment]
@Alfusainey this is not about about timing out the sending, i.e. timing out while waiting for the broker's disposition frame. This is about how long the broker should keep the message in its queue, i.e. setting the message's *ttl* property accordingly ...
