### ISSUE TITLE
Support limiting the connections based on the device connection time

### ISSUE THREAD

**Issue by kaniyan** [eclipse/hono#1716]
Protocol adapters should support limiting the number of connections based on the total connection time of devices per tenant over a defined time frame. The limit must be configurable at the tenant level. The connection time tracked by the metrics defined in #1287 could be used to implement this.

**Comment by sophokles73** [comment]
@kaniyan looks like we can close this one now, right?

**Comment by kaniyan** [comment]
yes. This has been closed via PRs #1722, #1731 and #1734.
