### ISSUE TITLE
hono rsocket adapter

### ISSUE THREAD

**Issue by soheilade** [eclipse/hono#1717]
Dear All,

I was wondering if there is any interest to implement an adapter for rsocket [1] in hono. 
[1]. https://en.wikipedia.org/wiki/RSocket
best regards
Soheila

**Comment by sophokles73** [comment]
Having taken a look at the wikipedia article, it seems that the protocol is mostly intended for streaming use cases. It seems quite obvious how *request/response* and *fire-and-forget* could be mapped to Hono's message based architecture. For the *streaming* interaction model mentioned in the article, I would need to get a better understanding of the underlying use cases. Do you have such a use case?

**Comment by soheilade** [comment]
Hi Kai, the usecase imo can be an statefull long running streaming application that can switch between various access points. On example is to implement an application on kuksa that can switch between various connections such as an application that constantly sends images captured by kuksa while it is moving and switching between different wifi providers. Does that make sense?

**Comment by sophokles73** [comment]
What size of images are we talking about (bytes)?

**Comment by soheilade** [comment]
is it important?

**Comment by sophokles73** [comment]
Well, Hono is message based and the messages are limited in size in order to make sure that resources are not eaten up by malicious clients. The system is not meant for transporting large binary streams of a few devices but is intended to be used for sending discrete (small) messages from large numbers of devices.

**Comment by soheilade** [comment]
in this case maybe we can just focus on sending data from a sensor on kuksa but via rsocket using these patterns: 
request/stream (finite stream of many)
channel (bi-directional streams)

**Comment by sophokles73** [comment]
Again, Hono is based on discrete messages, i.e. the protocol adapter would need to split up the stream of data received from a device into separate messages. The same is true for the other direction which i Hono is called *Command & Control*. I am not sure, though, what the benefit of doing that would be. Do you have a device that *must* communicate via RSocket? Based on what just layed out, IMHO it would be much simpler for the device to use e.g. AMQP or MQTT in the first place.

**Comment by sophokles73** [comment]
@soheilade any additional thoughts on this one?
