### ISSUE TITLE
coap-adapter doesn't get ready

### ISSUE THREAD

**Issue by boaks** [eclipse/hono#1721]
Using 1.1.0-SNAPSHOT (commit d3e7f875726d7f521633e88352b295646b615aec) I deployed a local-build with the coap-adapter enabled. The other adapters (http, mqtt) seems to be healthy but the coap-adapter fails and enters CrashLoopBackOff.

describes reports:
> Readiness probe failed: Get https://10.1.52.176:8088/readiness: dial tcp 10.1.52.176:8088: connect: connection refused  

and the logs also contains some errors.

[logs.txt](https://github.com/eclipse/hono/files/4109016/logs.txt)

**Comment by sophokles73** [comment]
It seems like the key/cert and port bindings are not set in the adapter's configuration. I'll create a fix ...

**Comment by sophokles73** [comment]
@boaks should be fixed on master

**Comment by sophokles73** [comment]
@boaks can we close this issue?

**Comment by boaks** [comment]
Maybe I doing something wrong, but I get now:

09:42:54.927 [vert.x-eventloop-thread-0] WARN  o.e.h.a.c.impl.VertxBasedCoapAdapter - Secure port number configured, but the certificate setup is not correct. No secure port will be opened - please check your configuration!
09:42:54.927 [vert.x-eventloop-thread-0] ERROR o.e.h.a.c.impl.VertxBasedCoapAdapter - configuration must have at least one of key & certificate or insecure port set to start up
09:42:54.934 [main] ERROR o.e.h.a.c.i.Application$$EnhancerBySpringCGLIB$$4c2cda0b - exception occurred during startup, shutting down ...
java.util.concurrent.ExecutionException: io.vertx.core.impl.NoStackTraceThrowable: no ports configured
	at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
	at org.eclipse.hono.service.AbstractBaseApplication.run(AbstractBaseApplication.java:166)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:772)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:762)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:319)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
	at org.eclipse.hono.adapter.coap.impl.Application.main(Application.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:578)

**Comment by sophokles73** [comment]
Well, what *are* you doing to deploy? Are you using head of master?

**Comment by boaks** [comment]
in pom.xml of deploy I added
    
`<docker.registry>localhost:32000</docker.registry>`

```
mvn clean install -Pbuild-docker-image
./push_hono_images.sh 1.1.0-SNAPSHOT localhost:32000
helm install hono eclipse-hono/ --dependency-update --namespace hono --set adapters.coap.enabled=true
```

**Comment by boaks** [comment]
```
Name:                   hono-adapter-coap-vertx
Namespace:              hono
CreationTimestamp:      Tue, 28 Jan 2020 10:58:20 +0100
Labels:                 app.kubernetes.io/component=adapter-coap-vertx
                        app.kubernetes.io/instance=hono
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=eclipse-hono
                        app.kubernetes.io/version=1.1.0-SNAPSHOT
                        helm.sh/chart=eclipse-hono-1.1.0-SNAPSHOT
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app.kubernetes.io/component=adapter-coap-vertx,app.kubernetes.io/instance=hono,app.kubernetes.io/name=eclipse-hono
Replicas:               1 desired | 1 updated | 1 total | 0 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:  app.kubernetes.io/component=adapter-coap-vertx
           app.kubernetes.io/instance=hono
           app.kubernetes.io/managed-by=Helm
           app.kubernetes.io/name=eclipse-hono
           app.kubernetes.io/version=1.1.0-SNAPSHOT
           helm.sh/chart=eclipse-hono-1.1.0-SNAPSHOT
  Containers:
   eclipse-hono-adapter-coap-vertx:
    Image:       localhost:32000/eclipse/hono-adapter-coap-vertx:1.1.0-SNAPSHOT
    Ports:       8088/TCP, 5683/UDP, 5684/UDP
    Host Ports:  0/TCP, 0/UDP, 0/UDP
    Limits:
      cpu:     1
      memory:  512M
    Requests:
      cpu:      100m
      memory:   256M
    Liveness:   http-get https://:health/liveness delay=180s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get https://:health/readiness delay=10s timeout=1s period=10s #success=1 #failure=3
    Environment:
      SPRING_CONFIG_LOCATION:  file:///etc/hono/
      SPRING_PROFILES_ACTIVE:  dev
      LOGGING_CONFIG:          classpath:logback-spring.xml
      JDK_JAVA_OPTIONS:        -XX:MinRAMPercentage=80 -XX:MaxRAMPercentage=80
      KUBERNETES_NAMESPACE:     (v1:metadata.namespace)
      JAEGER_SERVICE_NAME:     hono-adapter-coap-vertx
    Mounts:
      /etc/hono from adapter-coap-vertx-conf (ro)
  Volumes:
   adapter-coap-vertx-conf:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  hono-adapter-coap-vertx-conf
    Optional:    false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      False   MinimumReplicasUnavailable
  Progressing    True    ReplicaSetUpdated
OldReplicaSets:  <none>
NewReplicaSet:   hono-adapter-coap-vertx-567c686f65 (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  54s   deployment-controller  Scaled up replica set hono-adapter-coap-vertx-567c686f65 to 1

```

**Comment by boaks** [comment]
So, describe seems to contain the proper

`Image:       localhost:32000/eclipse/hono-adapter-coap-vertx:1.1.0-SNAPSHOT`

**Comment by boaks** [comment]
I'm using commit c89080e082e8c3c0c which contains your fix.

**Comment by sophokles73** [comment]
Are you deploying to minikube?

**Comment by boaks** [comment]
No, to microk8s. 

According the log message:

"Secure port number configured, but the certificate setup is not correct. No secure port will be opened - please check your configuration!"

I assume, that the update didn't work successful.
It should be "secure port configured, but no certificate/key is set. Will only enable ciphers that do not require server certificate!" on success. So I need to dig more in ...

**Comment by boaks** [comment]
OK, I found it :-).
The pushed new images must be also pulled from the registry into microk8s containerd :-).

**Comment by sophokles73** [comment]
Maybe you can set the *image pull policy* in microk8s to something like *Always* ...
