### ISSUE TITLE
Admin guide documentation outdated for (at least) HTTP adapter

### ISSUE THREAD

**Issue by Pixcell** [eclipse/hono#1729]
Hi,

While trying to configure your http-adapter as a container running on a device outside of a Kubernetes cluster, I tried to use ENV variables to tell the adapter what host and port it should connect to.

I followed the link: https://www.eclipse.org/hono/docs/admin-guide/http-adapter-config/#amqp-1-0-messaging-network-connection-configuration

But it seems it is missing a section with the `HONO_COMMAND` prefix.

Regards,

**Comment by sophokles73** [comment]
Yes, we seem to have forgotten the configuration instructions for the Command & Control connection that the adapters require,
