### ISSUE TITLE
AMQP Adapter: Use timeout when sending command to device

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1732]
When the AMQP adapter sends a command to a device, the adapter waits for the delivery update sent from the device and then itself sends a delivery update to the northbound application.

There is currently no timeout being used when waiting for the delivery update sent from the device.
This still needs to be implemented.

**Comment by sathishreddynsr** [comment]
can someone help to understand..how can we  integrate AMQP adapters to other gateway servers... i mean these AMQP adapters  are already configured to send get,pull requests.
