### ISSUE TITLE
Align Tenant management API implementation with the spec

### ISSUE THREAD

**Issue by dejanb** [eclipse/hono#1736]
At the moment Tenant management API specification defines that payload (without any mandatory parameters) is required during tenant creation. The implementation at the moment accepts empty body and adds 'enabled' field in that case. Empty body is also used in getting started examples.

We need to align specification with the implementation and examples.

**Comment by sophokles73** [comment]
FMPOV there is no need to supply and data in a request payload if I want to use the defaults. SO I would say that the spec should be *relaxed* accordingly.

**Comment by sophokles73** [comment]
@calohmn @ctron WDYT?

**Comment by calohmn** [comment]
I also think that we can change the spec to make the request body optional.

**Comment by dejanb** [comment]
I agree as well.

One question that I have is that with this change and changes in the #1711, should we bump the spec version?

**Comment by sophokles73** [comment]
> One question that I have is that with this change and changes in the #1711, should we bump the spec version?

I think we should. Remember that this is public API and we need to apply semantic versioning.
The change introduced in #1711 seems to only be concerning the wording being changed from *should not be included* to *must not be included* and the change in this PR also looks backward compatible to me. So I would suggest to bump to `1.0.1`. WDYT? @dejanb @ctron @calohmn

**Comment by sophokles73** [comment]
@dejanb can this be closed?

**Comment by sophokles73** [comment]
@dejanb can this be closed?
