### ISSUE TITLE
deploy coap-adapter in eclipse hono sandbox.

### ISSUE THREAD

**Issue by boaks** [eclipse/hono#1742]
I would appreciate, if the coap-adapter could be deployed in the eclipse hono sandbox.
Is that possible?

**Comment by sophokles73** [comment]
I don't see why it shouldn't apart from memory constraints. I'll check and see what I can do ...

**Comment by sophokles73** [comment]
@boaks I have deployed Hono 1.0.0-M2 including the CoAP adapter to the sandbox. The PSK based cipher suites should work. Can you check?

**Comment by boaks** [comment]
Neither

coaps://hono.eclipseprojects.io:30684/telemetry

nor

coaps://hono.eclipseprojects.io:5684/telemetry

sends back messages. For the californium sandbox I had to order the upd forwarding.

**Comment by sophokles73** [comment]
It should be 5684. But you might be right regarding the opening of the port in the VMs firewall.

**Comment by sophokles73** [comment]
@boaks According to webmasters at Eclipse, 5683/5684 UDP should be open.
Have you created a corresponding device with PSK credentials? Can you tell me the tenant and auth-id so that i can take a look at the logs/registry?

**Comment by boaks** [comment]
Start the [Californium - HonoClient](https://github.com/eclipse/californium/blob/master/demo-apps/cf-extplugtest-client/src/main/java/org/eclipse/californium/extplugtests/HonoClient.java) with these arguments:

-i sensor1@DEFAULT_TENANT  coap-secret coaps://hono.eclipseprojects.io:5684/telemetry

(I assumed them as they are the defaults for local installations.)

Wireshark capture:
[hono-sandbox-dtls.zip](https://github.com/eclipse/hono/files/4166299/hono-sandbox-dtls.zip)

The CLIENT_HELLOS seems not reach their destination.

**Comment by sophokles73** [comment]
@boaks my bad, I erroneously configured the container to expose 5683 and 5684 as tcp ports ...
I can now successfully use your client to publish data. However, you will not be able to use the sensor1 device because it doesn't have a PSK key registered. You can use the following device:

PSK id: bumlux2@acme
key: verysecret

**Comment by sophokles73** [comment]
@boaks don't forget to start a consumer first, otherwise your device won't be able to publish any data ...

**Comment by boaks** [comment]
Cool, I got 5.03 as expected.

> start a consumer first

I can see to start that locally in the first steps. But I miss how to connect to the sandbox. Do you have a link for me?

**Comment by boaks** [comment]
OK,

```
export AMQP_NETWORK_IP=hono.eclipseprojects.io
export MY_TENANT=acme
```

does it.

**Comment by boaks** [comment]
If you plan to setup the sandbox with a fixed demo id and secret, I will add that as default to the hono-client.

**Comment by sophokles73** [comment]
We can definitely do that and e.g. add PSK credentials to the default device as well so that it can be used with CoAP. I'll include this in the 1.1.0 deploy that I am doing tomorrow.

**Comment by boaks** [comment]
Great! The default will be sensor1@DEFAULT_TENANT coap-secret ?

**Comment by sophokles73** [comment]
No, it will be `sensor1@DEFAULT_TENANT` with key `hono-secret`

**Comment by sophokles73** [comment]
@boaks I have deployed Hono 1.1.0 on the Sandbox with the additional PSK secret for sensor1.

**Comment by boaks** [comment]
Using

```
-i sensor1@DEFAULT_TENANT hono-secret coaps://hono.eclipseprojects.io/telemetry
```

I get 

> ==[ CoAP Response ]============================================
> MID    : 39410
> Token  : 3C57178D6E531D15
> Type   : ACK
> Status : 4.04 - NOT_FOUND
> Options: {}
> RTT    : 706 ms
> Payload: 26 Bytes
> ---------------------------------------------------------------
> device unknown or disabled
> ===============================================================
> 

So encryption seems to work, is the device enabled?

**Comment by sophokles73** [comment]
@boaks I forgot to register the sensor1 device ... should work now

**Comment by boaks** [comment]
Yes! Works now!

**Comment by sophokles73** [comment]
@boaks can you close the issue then?

**Comment by boaks** [comment]
I prepared a PR do align the local deployment with the sandbox credentials.
The local deployment still uses coap-secret.

But it seems, that github doesn't like me, since I changed to the two factors ;-(.

**Comment by boaks** [comment]
See PR #1757
