### ISSUE TITLE
easiest way to adapt "maxDevicesPerTenant" for local custom builds and deployments

### ISSUE THREAD

**Issue by boaks** [eclipse/hono#1758]
A few days ago, to change the "maxDevicesPerTenant" required to adapt the 

```
deploy/src/main/deploy/helm/templates/hono-service-device-registry/hono-service-device-registry-secret.yaml
```

Now, with the chart repository, I'm not sure how to achieve that. Is there any docu hint about such adaptions?

**Comment by sophokles73** [comment]
I am not sure if I understand the question. Do you want to do local customizations of the chart before using it to install a release?

**Comment by boaks** [comment]
I want a local custom-build of hono deployment with 2000 devices per tenant.
Before updating to the current master commit (1.2.0-SNAPSHOT) this was possible by modifying the above file, build it with maven, and deploy it with helm.

Now I'm wondering, how this could be achieved.
Maybe you make a proposal what to do now in order to adapt this number?

**Comment by sophokles73** [comment]
You can still make local modifications to the Helm chart. You only need to check it out from the Eclipse IoT Packages project ...

**Comment by sophokles73** [comment]
It would, of course, be best if this and the other properties of the example registry would be made configurable through the chart's properties. Maybe you want to create a PR? :-)

**Comment by boaks** [comment]
In the end, I'm sure I made some mistakes, it reports new errors.
We will see next week, how to sort it out :-).
