### ISSUE TITLE
Client for the AMQP adapter

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#1761]
I think it would be beneficial to provide a ( southbound) client implementation for the AMQP protocol adapter. Similar to the `ApplicationClientFactory` it should provide a lean API that can be easily used by _users_ (in the sense of the User Guide) of Hono without having to bother with types that are mainly useful for internal use of Hono. This client could be used for easy interaction with the AMQP adapter and to implement protocol gateways (#1646).

**Comment by sophokles73** [comment]
sounds like a great idea :+1:

**Comment by b-abel** [comment]
I can provide a PR for this.

**Comment by b-abel** [comment]
I added a PR based on existing code from the `client` module for this. I think it's good to integrate this now to have something usable for the time being.
Perspectively, it would be good to have a simple client interface that does not expose how the AMQP links are used (e.g. by separate clients to be retrieved from the factory, by disclosing the caching of the links and by creating clients per tenant). I would like to provide this later, and this could then replace the solution in this first PR.

**Comment by sophokles73** [comment]
@b-abel what is the status of this PR? Are you going to add docs and tests or is this supposed to be merged as-is?
