### ISSUE TITLE
AMQP/MQTT: Gateways may subscribe for commands to disabled devices

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1764]
Currently, when a gateway subscribes for commands of a specific device, there is no check whether that device is actually enabled.

See this example trace:
![AMQPAdapter_CommandSubscription](https://user-images.githubusercontent.com/891931/74315650-2c211000-4d78-11ea-86c3-abfe37e6bcb0.png)

The command subscription is successful - only sending the notification event fails.

(When a northbound application actually tries to send a command to that device, that request will be rejected however - the device registration data is checked when trying to find the mapped gateway.)

**Comment by sophokles73** [comment]
While I tend to agree that the adapters should reject a subscription request if the device is disabled at the point in time of the subscription request, I wonder how we want to deal with a situation where the device is being disabled *after* the subscription has been created?

**Comment by sophokles73** [comment]
@calohmn any additional thoughts?

**Comment by calohmn** [comment]
> I wonder how we want to deal with a situation where the device is being disabled after the subscription has been created?

If we implement a periodic command subscription renewal, done by the protocol adapters (to prevent stale `commandHandlingAdapterInstance` entries in the Device Connection service - see #1858), we could also check the device registration at these points in time.
When finding out about a disabled device, we could invoke the handler, suggested in #1859, to close the subscription (meaning closing the MQTT connection, for example).
The question is, if closing the subscription and thereby explicitly informing the device that it won't receive commands, is all that important. It's the same question also raised in #1859. I tend to think it's probably not that important.

**Comment by sophokles73** [comment]
@calohmn IMHO the least we should do is perform the check during subscription establishment.

**Comment by calohmn** [comment]
> [...] I wonder how we want to deal with a situation where the device is being disabled *after* the subscription has been created?

This has already been solved by the fix for #293, closing the device connection if the device got disabled.

> IMHO the least we should do is perform the check during subscription establishment.

@sophokles73 yes, that check should be added.

**Comment by calohmn** [comment]
> IMHO the least we should do is perform the check during subscription establishment.

Actually, that check has already been added in #2377.
