### ISSUE TITLE
Revert deprecating hashed passwords

### ISSUE THREAD

**Issue by dejanb** [eclipse/hono#1791]
We identified use cases in which is useful to provide pre-hashed passwords when updating device credentials (e.g. mass import of data, use of weaker hashes to save cluster cpus, ...). The get credentials method still should not provide any details about the secret externally.

In order to support this, we need to:

* revert deprecation in the spec
* provide test cases for all supported use cases
* provide a way to blacklist hash algorithms from being used
* update docs

**Comment by jbtrystram** [comment]
I am working on this, FYI :)
