### ISSUE TITLE
Command And Control API : feedback on received command

### ISSUE THREAD

**Issue by ppatierno** [eclipse/hono#18]
When a service (the sender) sends a command to the device, how does it know that the device received the message (but not executed it yet) ?
Of course, we can rely on AMQP disposition frame (even if it is sent only when the sender doesn't pre-settle the command message) sent by the receiver.
However, not always the receiver of the command is exactly the "final" receiver ... the device.

Using a "store and forward" mechanism with a queue in the middle, the sender knows (thanks to the AMQP disposition frame) that the message was delivered to the queue (i.e. in the broker) but not to the device. In this scenario, could be useful to have a "feedback" channel from which the sender can read ack messages from devices that truly received the commands.
The related address could be something like this : 

control/deviceId/tenantId/feedback

The correlationId property in the AMQP specification can be used to define the relationship between the command (identified by its messageId) and the feedback itself.

**Comment by sophokles73** [comment]
We have discussed this scenario this morning in a call I had with @hekonsek and @dguggemos :-) We should talk about this next week during our face-to-face...

**Comment by pellmann** [comment]
@ppatierno - With the Command and Control in 0.6 we assume a response from the device to acknowledge the execution of the command (or whatever is to acknowledge in the devices context). I think this implements the "feedback", referenced in this issue. Do you agree?

https://www.eclipse.org/hono/concepts/command-and-control/
