### ISSUE TITLE
TLS support and basic HTTP authentication for Prometheus resource limits check

### ISSUE THREAD

**Issue by bordeuax** [eclipse/hono#1821]
By default Prometheus don't support  TLS and HTTP authentication. But, in the majority of production cases or SaaSs, Prometheus is accessible via TLS plus basic authentication.

**Comment by sophokles73** [comment]
Just for my understanding, you need Hono's `PrometheusBasedResourceLimitsCheck` implementation to support using TLS for connecting to Prometheus query API and authenticate to the Prometheus server using HTTP Basic Auth, right?

**Comment by bordeuax** [comment]
Hi @sophokles73 , yes your understanding is right. It's will be nice to have at configuration level `-- hono.resourceLimits.prometheusBased.*`  following options: 
* HTTP plain communication 
* HTTP basic authentication or something more generic to support also token based authentication.  This will be independently if i have HTTP or HTTPS 
* TLS configuration for HTTPS
