### ISSUE TITLE
device 4711 - sensor1@DEFAULT_TENANT disabled on sandbox? 

### ISSUE THREAD

**Issue by boaks** [eclipse/hono#1833]
I tried to test the hono-sandbox with

```
./coap-client -u sensor1@DEFAULT_TENANT -k hono-secret -m POST coaps://hono.eclipseprojects.io/telemetry -e { "test" : "hallo" }
```

and get 

```
4.04 device unknown or disabled
```

@sophokles73 
Could you please check, if the device could be enabled?

**Comment by sophokles73** [comment]
why don't you simply enable it?

**Comment by boaks** [comment]
I would have expected it to be enabled in the deployment.
