### ISSUE TITLE
Getting 'Failed to authenticate' error when Connection Limit exceeded. 

### ISSUE THREAD

**Issue by meshkatul-anwer-bosch** [eclipse/hono#1848]
For a Free-plan tenant, when the number of connected devices is exceeded the limit, further connection attempts were getting rejected with a cause 'Failed to authenticate'. This could be confusing the tenant is using the correct credentials for the device. 

Question is: is it even possible to provide better cause e.g. ' max connections reached'?

**Comment by kaniyan** [comment]
Is it the case for `MQTT` or `AMQP` or both?

**Comment by meshkatul-anwer-bosch** [comment]
This is for AMQP.

**Comment by kaniyan** [comment]
In case of the _AMQP_ adapter, the adapter and tenant level connection limits are being verified inside the `AmqpAdapterSaslAuthenticatorFactory`. The result of the verification is communicated using the `SaslOutcome` and there is no standard error codes that suits our purpose here. Need to check if a wrapper could help. Or simply moving the limit checks out of the `AmqpAdapterSaslAuthenticatorFactory` and performing these checks after authentication should work fine.

**Comment by sophokles73** [comment]
@kaniyan sounds like the right way to go FMPOV.

**Comment by sathishreddynsr** [comment]
can someone help to understand..how can we  integrate AMQP adapters to other gateway servers... i mean these AMQP adapters  are already configured to send get,pull requests.

**Comment by sophokles73** [comment]
closed via #1920
