### ISSUE TITLE
Hono resource limits :  timeout for Prometheus queries  

### ISSUE THREAD

**Issue by bordeuax** [eclipse/hono#1865]
Playing around with _Hono resource limits_ I come to the conclusion that for medium loaded cluster(K8S cluster with Hono deployment) we can have network issue, also if Prometheus is heavy loaded,  PomQL queries can take unpredictable time for execution . Why not to have  _resource limits configuration - > timeout for Prometheus queries_  as a tune mechanism. Also not link this timeout only to _vert.x WebClient timeout_ but also with [Prometheus Instant queries](https://prometheus.io/docs/prometheus/latest/querying/api/#instant-queries)

**Comment by sophokles73** [comment]
Sounds reasonable to have a configurable timeout for the query. Do you want to prepare a PR? Not sure about the Instant Query, though. @kaniyan WDYT?

**Comment by kaniyan** [comment]
> Sounds reasonable to have a configurable timeout for the query. Do you want to prepare a PR? Not sure about the Instant Query, though. @kaniyan WDYT?

It sounds good :+1:.  Optimisations such as this, preventing concurrent query executions to retrieve the resource usage for a tenant and caching optimisations are thought through for the next iteration.

**Comment by bordeuax** [comment]
Is need a PR on this topic or you plan to have a large round of discussion and collect all issues for next iteration ?

**Comment by kaniyan** [comment]
> Is needed a PR on this topic or you plan to have a large round of discussion and collect all issues for next iteration ?

A PR is always welcome. If you are interested, go ahead.

**Comment by sophokles73** [comment]
@bordeuax is #1866 related to your proposal to use an Instant Query for determining the number of currently connected devices?

**Comment by bordeuax** [comment]
@sophokles73, when we executing a PomQL instant query via HTTP API, we have the possibility to specify as URL parameter a timeout, `timeout=<duration>` that will indicate how much time Prometheus should take to execute the query, for more info please see [Instant queries](https://prometheus.io/docs/prometheus/latest/querying/api/#expression-queries). 
I found useful, if we have a timeout on adapter side for PomQL also put this timeout as URL parameter when we executing a query.

**Comment by sophokles73** [comment]
I agree, that makes sense. A PR for adding the (configurable) timeout parameter would be very welcome :-)

**Comment by sophokles73** [comment]
closed via #1882
