### ISSUE TITLE
Exception using device registry REST-API 

### ISSUE THREAD

**Issue by boaks** [eclipse/hono#1868]
I currently see

> 14:01:23.132 [vert.x-eventloop-thread-0] DEBUG o.e.h.s.http.DefaultFailureHandler - handling failed route for request [method: POST, URI: http://10.152.183.245:28080/v1/devices/DEFAULT_TENANT/4811, status: -1] - null
> io.jaegertracing.internal.exceptions.UnsupportedFormatException: Builtin.TEXT_MAP_EXTRACT
> 	at io.jaegertracing.internal.JaegerTracer.extract(JaegerTracer.java:215)
> 	at io.jaegertracing.internal.JaegerTracer.extract(JaegerTracer.java:63)
> 	at org.eclipse.hono.tracing.TracingHelper.extractSpanContext(TracingHelper.java:350)
> 	at org.eclipse.hono.service.http.TracingHandler.handlerNormal(TracingHandler.java:101)
> 	at org.eclipse.hono.service.http.TracingHandler.handle(TracingHandler.java:77)
> 	at org.eclipse.hono.service.http.TracingHandler.handle(TracingHandler.java:42)
> 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
> 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
> 	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:130)
> 	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:54)
> 	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:36)
> 	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:50)
> 	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:32)
> 	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:136)
> 	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
> 	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
> 	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:232)
> 	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)

In the logs, when I try to access my the local device registry via REST.
Deployment is from today's master.

```
curl -s --retry 3 -i -X POST "http://${REGISTRY_IP}:28080/v1/devices/${MY_TENANT}/${GW}" -H 'accept: application/json' -H 'Content-Type: application/json' -d "{\"enabled\":true }"
HTTP/1.1 500 Internal Server Error
content-type: text/plain; charset=utf-8
content-length: 24

Builtin.TEXT_MAP_EXTRACTHTTP/1.1 500 Internal Server Error
content-type: text/plain; charset=utf-8
content-length: 24

Builtin.TEXT_MAP_EXTRACTHTTP/1.1 500 Internal Server Error
content-type: text/plain; charset=utf-8
content-length: 24

Builtin.TEXT_MAP_EXTRACTHTTP/1.1 500 Internal Server Error
content-type: text/plain; charset=utf-8
content-length: 24

Builtin.TEXT_MAP_EXTRACT
```

**Comment by sophokles73** [comment]
Yes, that is already fixed on master. Just rebase ...

**Comment by boaks** [comment]
Thanks!
