### ISSUE TITLE
JaegerTracer.extract: UnsupportedFormatException: Builtin.BINARY_EXTRACT

### ISSUE THREAD

**Issue by boaks** [eclipse/hono#1869]
> 19:32:30.879 [CoapServer(main)#1] DEBUG o.e.h.adapter.coap.VertxCoapResource - running handler for resource [/telemetry] on vert.x context
> 19:32:30.882 [vert.x-eventloop-thread-0] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
> io.jaegertracing.internal.exceptions.UnsupportedFormatException: Builtin.BINARY_EXTRACT
> 	at io.jaegertracing.internal.JaegerTracer.extract(JaegerTracer.java:215)
> 	at io.jaegertracing.internal.JaegerTracer.extract(JaegerTracer.java:63)
> 	at org.eclipse.hono.adapter.coap.TracingSupportingHonoResource.extractSpanContextFromRequest(TracingSupportingHonoResource.java:81)
> 	at org.eclipse.hono.adapter.coap.TracingSupportingHonoResource.newSpan(TracingSupportingHonoResource.java:87)
> 	at org.eclipse.hono.adapter.coap.TracingSupportingHonoResource.handleRequest(TracingSupportingHonoResource.java:101)
> 	at org.eclipse.hono.adapter.coap.VertxCoapResource.lambda$handleRequest$0(VertxCoapResource.java:80)
> 

I tried to test the current coap-adapter with:

```
POST coaps://localhost:30684/telemetry
```

Wireshark show a succesful handshake, but then I get "No response received."
The coap-adapter logs contains the above exception.

**Comment by sophokles73** [comment]
should be fixed on master

**Comment by boaks** [comment]
> [INFO] Tests run: 18, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.157 s - in org.eclipse.hono.adapter.coap.AbstractVertxBasedCoapAdapterTest
> [INFO] 
> [INFO] Results:
> [INFO] 
> [ERROR] Failures: 
> [ERROR]   TracingSupportingHonoResourceTest.testExtractTraceContext:93 
> Argument(s) are different! Wanted:
> spanBuilder.addReference(
>     "child_of",
>     Mock for SpanContext, hashCode: 446763332
> );
> -> at org.eclipse.hono.adapter.coap.TracingSupportingHonoResourceTest.testExtractTraceContext(TracingSupportingHonoResourceTest.java:93)
> Actual invocations have different arguments:
> spanBuilder.addReference(
>     "child_of",
>     null
> );
> -> at org.eclipse.hono.tracing.TracingHelper.buildSpan(TracingHelper.java:500)
> spanBuilder.ignoreActiveSpan(
>     
> );
> -> at org.eclipse.hono.tracing.TracingHelper.buildChildSpan(TracingHelper.java:436)
> spanBuilder.withTag(
>     "component",
>     "adapter"
> );
> -> at org.eclipse.hono.tracing.TracingHelper.buildChildSpan(TracingHelper.java:437)
> spanBuilder.withTag(
>     "span.kind",
>     "server"
> );
> -> at org.eclipse.hono.tracing.TracingHelper.buildServerChildSpan(TracingHelper.java:458)
> spanBuilder.withTag(
>     "coap.type",
>     "CON"
> );
> -> at org.eclipse.hono.adapter.coap.TracingSupportingHonoResource.newSpan(TracingSupportingHonoResource.java:90)
> spanBuilder.withTag(
>     "http.url",
>     "/"
> );
> -> at org.eclipse.hono.adapter.coap.TracingSupportingHonoResource.newSpan(TracingSupportingHonoResource.java:91)
> spanBuilder.start(
>     
> );
> -> at org.eclipse.hono.adapter.coap.TracingSupportingHonoResource.newSpan(TracingSupportingHonoResource.java:92)
> 
> [INFO] 
> [ERROR] Tests run: 20, Failures: 1, Errors: 0, Skipped: 0

**Comment by sophokles73** [comment]
I forgot to update the test case ... just pull and rebase

**Comment by boaks** [comment]
Thanks, works!
