### ISSUE TITLE
Checking Hono build using Docker Community Edition

### ISSUE THREAD

**Issue by ppatierno** [eclipse/hono#187]
From a use case in the Hono dev mailing list, it seems that the Hono build doesn't work using the latest Docker CE instead of older version like Docker 1.13.

**Comment by sophokles73** [comment]
Hmm, I am using 

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:27:42 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:27:42 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
which works without any problems. However, I am not using a VM as the docker host but have a local install.

**Comment by sophokles73** [comment]
@ppatierno, do you think that we do have an issue here?

**Comment by ppatierno** [comment]
@sophokles73 looking into the hono-dev archive, it turned out the the user was using a VM with Lubuntu 16.04. I have never tried this specific Ubuntu version.

**Comment by sophokles73** [comment]
neither have I, but still, I do not think that we have an issue here. So, FMPOV we (you) should close this issue ...
