### ISSUE TITLE
coap-adapter: 2.04 Changed with payload?

### ISSUE THREAD

**Issue by boaks** [eclipse/hono#1870]
What was the reason to adapt the 2.05 CONTENT for responses with payload to a 2.04 CHANGED?

**Comment by sophokles73** [comment]
The definition of these response codes in the CoAP RFC:
https://tools.ietf.org/html/rfc7252#section-5.9.1.4
https://tools.ietf.org/html/rfc7252#section-5.9.1.5

**Comment by boaks** [comment]
OK.
The client sends a POST, and 2.04 with the payload as action result is sent back.
If we send back a 2.01 Created (means command exchange created on the server side) that maybe also within the spec. And it supports the "location" options.
WDYT?

**Comment by sophokles73** [comment]
What's wrong with sending back 2.04?

**Comment by boaks** [comment]
RFC 7252 doesn't mention the "location option" for 2.04.
For 2.01 it does.

**Comment by sophokles73** [comment]
Well, my understanding is that for 2.01 the RFC defines the semantics of the *location* options, if present in the response. However, FMPOV the way we are using the location optoin does not really match the defined semantics.
For the 2.04 response status however, the RFC does not explicitly define the semantics of these options, given that they exist in a response. Does that mean that these options are not allowed to be contained in the response? I do not know for sure but I tend to believe that it doesn't.

Based on that I would rather include options in a response with code 2.04 for which no semantics of these options have been defined than using options in a way that is not the one intended by the RFC in case of 2.01. WDYT?

**Comment by boaks** [comment]
In my experience some parts of RFC 7252 are "well defined", and some are just "best effort" (e.g. "request/response" matching with DTLS). Unfortunately discussions with the core-list takes time and attention, which is both hard to find (I currently spend my free time in try to sort out the java limitations for multicast with the list. I don't want to discus a second topic.)

The location in RFC 7252 itself seems to be mainly used to control a "proxy cache". Other specs, e.g. LwM2M use it for followup requests (registration / update registration).
 
In my opinion, as long as that "cache-control" is not violated, I don't see any issues (unless I will be able to verify that with libcoap and then be wiser .;) ).

That "cache-control" requires a location, if a other resources as provided in the URI has changed and therefore the cache must be cleared.
Though hono mainly uses the POST, which doesn't use/support a "caching", this seems to be just no issue at all. 
If "caching" should be considered, then c&c affects a resource different from the provided URI and so the location may be used to clear the cache. But again, without using GET, that seems to be without effects.

**Comment by boaks** [comment]
[question in the core mailing list](https://mailarchive.ietf.org/arch/msg/core/iCbdG8jdijSRXIuH1EJiIBsxKBQ/)

**Comment by boaks** [comment]
According the answers from the list, using "location" with 2.04 is not forbidden, but the behavior according caching-proxies is unspecified. For the hono use-case a caching-proxy seem to be not relevant. So 2.04 with location is a good choice. At least for the current state of art.
