### ISSUE TITLE
coap-adapter - tracing -NullPointerException

### ISSUE THREAD

**Issue by boaks** [eclipse/hono#1873]
> java.lang.NullPointerException: null
> 	at io.jaegertracing.internal.propagation.BinaryCodec.extract(BinaryCodec.java:179)
> 	at io.jaegertracing.internal.propagation.BinaryCodec.extract(BinaryCodec.java:45)
> 	at io.jaegertracing.internal.PropagationRegistry$ExceptionCatchingExtractorDecorator.extract(PropagationRegistry.java:57)
> 	at io.jaegertracing.internal.JaegerTracer.extract(JaegerTracer.java:217)
> 	at io.jaegertracing.internal.JaegerTracer.extract(JaegerTracer.java:63)
> 	at org.eclipse.hono.adapter.coap.TracingSupportingHonoResource.extractSpanContextFromRequest(TracingSupportingHonoResource.java:82)
> 	at org.eclipse.hono.adapter.coap.TracingSupportingHonoResource.newSpan(TracingSupportingHonoResource.java:88)
> 	at org.eclipse.hono.adapter.coap.TracingSupportingHonoResource.handleRequest(TracingSupportingHonoResource.java:102)
> 	at org.eclipse.hono.adapter.coap.VertxCoapResource.lambda$handleRequest$0(VertxCoapResource.java:80)
>

**Comment by boaks** [comment]
@sophokles73 

When do you access the options of a request?
Also when it is already processed/response sent?

**Comment by boaks** [comment]
[returns the null](https://github.com/eclipse/hono/blob/master/adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CoapOptionInjectExtractAdapter.java#L79)

and

```
 public JaegerSpanContext extract(Binary carrier) {
    Map<String, String> baggage = null;

    ByteBuffer buf = carrier.extractionBuffer();

    // Do not require the carrier implemention to rewind.
    buf.rewind();
```

then throws the NullPointerException.

I'm not sure, if an empty buffer would be the right approach?
`null` seems to fail.

**Comment by boaks** [comment]
OK, a empty buffer results in 

> java.nio.BufferUnderflowException: null
> 	at java.base/java.nio.Buffer.nextGetIndex(Unknown Source)
> 	at java.base/java.nio.HeapByteBuffer.getLong(Unknown Source)
> 	at io.jaegertracing.internal.propagation.BinaryCodec.extract(BinaryCodec.java:187)
> 	at io.jaegertracing.internal.propagation.BinaryCodec.extract(BinaryCodec.java:45)
> 	at io.jaegertracing.internal.PropagationRegistry$ExceptionCatchingExtractorDecorator.extract(PropagationRegistry.java:57)
> 	at io.jaegertracing.internal.JaegerTracer.extract(JaegerTracer.java:217)
> 	at io.jaegertracing.internal.JaegerTracer.extract(JaegerTracer.java:63)
> 	at org.eclipse.hono.adapter.coap.TracingSupportingHonoResource.extractSpanContextFromRequest(TracingSupportingHonoResource.java:82)
> 	at org.eclipse.hono.adapter.coap.TracingSupportingHonoResource.newSpan(TracingSupportingHonoResource.java:88)
> 	at org.eclipse.hono.adapter.coap.TracingSupportingHonoResource.handleRequest(TracingSupportingHonoResource.java:102)
> 	at org.eclipse.hono.adapter.coap.VertxCoapResource.lambda$handleRequest$0(VertxCoapResource.java:80)
> 
>

**Comment by sophokles73** [comment]
Can you please provide a description of what you are doing? It is hard to understand the problem without any context ...

**Comment by boaks** [comment]
That happens, if you send a coap request (without the tracing option).

> at io.jaegertracing.internal.JaegerTracer.extract(JaegerTracer.java:63)
> at org.eclipse.hono.adapter.coap.TracingSupportingHonoResource.extractSpanContextFromRequest(TracingSupportingHonoResource.java:82)
> ...
> at org.eclipse.hono.adapter.coap.TracingSupportingHonoResource.handleRequest(TracingSupportingHonoResource.java:102)

I thought, that that's clear from the stacktrace and from your changes in the tracing.

**Comment by sophokles73** [comment]
ok, now I see. This doesn't seem to prevent the request from being processed, though, right? But it is of course a bug. Let's see what we can do ...

**Comment by boaks** [comment]
Yes, at least some requests get responses ...

**Comment by sophokles73** [comment]
@boaks should be fixed on master

**Comment by boaks** [comment]
Fixed, thanks!
