### ISSUE TITLE
Extend device management API to get all devices under a tenant

### ISSUE THREAD

**Issue by kaniyan** [eclipse/hono#1875]
Often I come across the interest to have a possibility in the device registry to list all  the _devices_ belonging to a _tenant_. Currently it is only possible to retrieve one _device_ using its _identifier_. The proposal here is to extend the _device management_ _API_ to support a _list_ operation that retrieves all the _devices_ belonging to a particular _tenant_. Already there was a [discussion](https://github.com/eclipse/hono/pull/1130#issuecomment-480784010) on this topic in the PR #1130.

**Comment by ctron** [comment]
I think we must be careful here with the definition of "all". I am pretty sure you do not want to get *all* devices from a tenant in a single response.

As we discussed during the F2F meeting in Berlin a few weeks back, we are currently working on a UX design for a web console, which will include searching and listing. For that we will require some kind of a query API, which needs features like filtering and paging as well.

So I would wait for some recommendations/best practices from them, to see what actual requirements we have, and need to implement.

But I would really urge you not to implement a method which simply returns *all* devices.

**Comment by kaniyan** [comment]
@ctron Thanks for the information. I didn't  intend to get _all devices_ in a single response. I should have mentioned that above to be precise and thanks for pointing it out :-). Our hub colleagues have implemented this using pagination and my emphasis is mainly to offer a possibility to retrieve all devices, of course in an optimised way.

I remember that we talked in the F2F meeting about the recommendations from the UX design team. That would be great :+1:. Do you roughly have any idea when we could hear from them? Once the _MongoDB_ based implementation including authentication is over, then we would like to focus on this issue.

**Comment by kaniyan** [comment]
This has been closed as another issue #1958 opened for the same.
