### ISSUE TITLE
Problem with running Hono in my private Kubernetes cluster

### ISSUE THREAD

**Issue by roullli** [eclipse/hono#1887]
I'm trying to run Hono inside my own Kubernetes cluster made up of 2 Raspberry Pis (one as a master, the other one as a worker node). The hono version which I'm trying to install is V 1.0.2.
I ran this " helm install hono eclipse-hono/ --dependency-update --namespace hono " on the master node and it showed me the successful installation prompt.
But when I'm running "kubectl get pods -n hono" to see the running pods, I'm getting this output:
![image](https://user-images.githubusercontent.com/51787620/78774311-2c671180-799d-11ea-8d47-d76e4c5b2038.png)
Also, here is the output for running "kubectl get svc -n hono":
![image](https://user-images.githubusercontent.com/51787620/78774535-78b25180-799d-11ea-8a3f-6a6dbae4d3c8.png)
I'm stuck in this situation for 2 days and I didn't find any solution for that anywhere.
I would thankful if anyone can help me.

**Comment by sophokles73** [comment]
Is there a reason why you want to install Hono 1.0.2 and not the most recent 1.2.1?

**Comment by roullli** [comment]
It is just that is has been mentioned in https://www.eclipse.org/hono/docs/deployment/helm-based-deployment/ I have to run my own private image registry. that's the only reason.

**Comment by sophokles73** [comment]
so your kubernetes cluster cannot pull from the docker registry?

**Comment by roullli** [comment]
Yes, it can. but does this problem has anything to do with the hono version?

**Comment by roullli** [comment]
I guess this problem is related to "hono-service-device-registry-0" pod which is unable to start. I don't know the reason!!?

**Comment by sophokles73** [comment]
> Yes, it can. but does this problem has anything to do with the hono version?

It does in so far as it is unnecessary for you to build the images locally and use the (very old) helm chart from the 1.0.2 code base.
Instead, you should be able to use the [current Hono helm](https://github.com/eclipse/packages/tree/master/charts/hono) chart and follow the instructions for installing it.

**Comment by roullli** [comment]
same problem with version 1.2.0!
![image](https://user-images.githubusercontent.com/51787620/78818018-acf93280-79dc-11ea-976d-a5bbe736f868.png)
![image](https://user-images.githubusercontent.com/51787620/78818076-c26e5c80-79dc-11ea-90c3-cd040e06db12.png)

**Comment by sophokles73** [comment]
Does kubernetes report any reason for the CrashLoopBackOff, i.e. what is the output of `kubectl describe pod`?
Does your kubernetes cluster support load balancers for ingress? If not, i.e. if it only supports NodePort services, then you should turn off using the load balancers during installation.
How much RAM does the worker node have? If you're on a raspberry it is probably not much and thus you might want to deploy the bare minimum only, i.e. start with just a single protocol adapter and leave out the monitoring infrastructure (Prometheus and Grafana).

All this can be done by customizing some configuration properties of the helm chart. Create a yaml file named `custom.yaml`:
```
useLoadBalancer: false
adapters:
  amqp:
    enabled: false
  mqtt:
    enabled: false
grafana:
  enabled: false
prometheus:
  createInstance: false
```
Then install using the `-f` switch:
```bash
helm install -f /path/to/custom.yaml eclipse-hono eclipse-iot/hono
```

**Comment by roullli** [comment]
These are the output for each pod:
eclipse-hono-adapter-amqp-vertx-7cdb58649b-686v2
![image](https://user-images.githubusercontent.com/51787620/78880210-baa2cc80-7a5d-11ea-9d8a-178b2db26880.png)
eclipse-hono-adapter-http-vertx-77b8599c4-25hst
![image](https://user-images.githubusercontent.com/51787620/78880404-0786a300-7a5e-11ea-9621-3463f8fcd419.png)
eclipse-hono-adapter-mqtt-vertx-6f86cb74f5-5d9t2
![image](https://user-images.githubusercontent.com/51787620/78880526-356be780-7a5e-11ea-827f-80ff9d100133.png)
eclipse-hono-artemis-554cb5df84-4jkwp
![image](https://user-images.githubusercontent.com/51787620/78880607-516f8900-7a5e-11ea-8ea9-003a592407cb.png)
eclipse-hono-dispatch-router-5788f959b7-9fvst
![image](https://user-images.githubusercontent.com/51787620/78880670-68ae7680-7a5e-11ea-9637-4c0de506f59e.png)
eclipse-hono-grafana-796449745b-p67wc
![image](https://user-images.githubusercontent.com/51787620/78880744-85e34500-7a5e-11ea-95d8-a617a624c337.png)
eclipse-hono-prometheus-server-776fdcf8cb-hf8hc
![image](https://user-images.githubusercontent.com/51787620/78880814-9d223280-7a5e-11ea-9ace-4beebde9a293.png)
eclipse-hono-service-auth-855bdf9bc9-2ncw8
![image](https://user-images.githubusercontent.com/51787620/78880880-b5924d00-7a5e-11ea-8dce-2949f2b507a5.png)
eclipse-hono-service-device-registry-0
![image](https://user-images.githubusercontent.com/51787620/78880947-cba00d80-7a5e-11ea-9400-7e7cdee81261.png)
I'll try to deploy the customized deployment and update the results.
Thank you @sophokles73

**Comment by roullli** [comment]
@sophokles73 same issue with customized deployment.

**Comment by roullli** [comment]
When I run `kubectl get pvc` and it shows the following output: 

![image](https://user-images.githubusercontent.com/51787620/79065773-83c9f200-7cbb-11ea-88c2-8e5c229ecd77.png)

and it has nothing to show for pv.
I think the problem is that there is a missing Persistance volume. I'm not familiar with volumes. can someone guide me how should I wright a yaml file to fix this issue?
Thanks in advance.

**Comment by sophokles73** [comment]
what is the output of `kubectl get storageclass`?

**Comment by roullli** [comment]
there isn't any storageclass available.
![image](https://user-images.githubusercontent.com/51787620/79230016-a94a2d80-7e6c-11ea-8835-fe389cfac24a.png)

**Comment by sophokles73** [comment]
That seems to be the problem. Please consult the kubernetes documentation for details on how to configure dynamic volume provisioning in your cluster.

**Comment by roullli** [comment]
I have fixed the problem with the PersistentVolume, and it is bounded to the pod. But there is another issue which I'm pretty sure it is related to the Architecture. Because, when I'm trying to run the docker image separately with by this command:
`docker run eclipse/hono-service-device-registry:1.0.0` 
this message prompts:
![image](https://user-images.githubusercontent.com/51787620/79343701-6b660b80-7f37-11ea-9727-697aff79227a.png)
How can I build the image for arm64 ARCH? since the image in docker registry is amd64.

**Comment by sophokles73** [comment]
Good point. I totally forgot about that ...
If you have the whole tool chain on your raspberries, you could build from scratch on your pi and use its local Docker registry to host the images.

**Comment by roullli** [comment]
what do you mean by tool chain? what are these tools? 
can you give me some tips about how can I customize the image for arm64?

**Comment by sophokles73** [comment]
Well, the JDK, maven, docker etc ...
Building Hono is described in the [Building from Source](https://www.eclipse.org/hono/docs/dev-guide/building_hono/) guide.

**Comment by roullli** [comment]
I built the Images. now I can run them inside my cluster successfully.
I hope that this would be my final question (if any other issue doesn't happen)how can I edit the deployment files so that it uses my preferable images instead of the default ones?

**Comment by sophokles73** [comment]
That's great to hear :-) Not sure what you mean with *deployment files*, though. Are you referring to the Helm chart?

**Comment by roullli** [comment]
I mean that, how can I force the Kubernetes to use my local images in order to deploy Hono, instead of the default images from docker repository?

**Comment by sophokles73** [comment]
You can set the names of the container images that are being used for Hono's components as configuration properties when installing the chart using helm. This requires that you tag the images using a value that is specific to the arm64 platform, e.g. something like `1.2.2-arm64` instead of just 1.2.2 for the amd64 platform.
You can do that by means of defining the `docker.image.additional.tag` maven property when building, e.g.

```bash
mvn clean install -Pbuild-docker-image -Ddocker.image.additional.tag=1.2.2-arm64
```

This will add the `1.2.2-arm64` tag to each of the container images being built.

After the build, create a *custom.yaml* file:
```yaml
deviceRegistryExample:
  imageName: eclipse/hono-service-device-registry-file:1.2.2-arm64

authServer:
  imageName: eclipse/hono-service-auth:1.2.2-arm64

adapters:
  amqp:
    imageName: eclipse/hono-adapter-amqp-vertx:1.2.2-arm64
  mqtt:
    imageName: eclipse/hono-adapter-mqtt-vertx:1.2.2-arm64
  http:
    imageName: eclipse/hono-adapter-http-vertx:1.2.2-arm64
```

When installing Hono using the chart:
```bash
helm install -f /path/to/custom.yaml hono eclipse-iot/hono
```

**Comment by roullli** [comment]
Thank you so much. 
The problem with Hono images are fixed and containers are running. but I have the same issue with images from quay.io/repository :
![image](https://user-images.githubusercontent.com/51787620/79541638-d546f800-8092-11ea-8f11-940638a4296b.png)
Any Idea about how can I also build those images locally?

**Comment by sophokles73** [comment]
That's a different story. However, I guess the general approach of building the corresponding images on/for arm64 should work as well. The build process will be a different one, though, because Apache ActiveMQ Artemis and Apache Qpid are separate projects. I think you should be able to find information regarding how to build those on their respective project home pages.

**Comment by roullli** [comment]
Finally, I succeeded in running images locally:
![image](https://user-images.githubusercontent.com/51787620/80199580-2ffbc900-862a-11ea-9b81-0d3c65a69ce3.png)
But, I'm facing a new problem which I think is related to the Artemis instance. here is the output of `kubectl describe pod -hono` for hono registry container:
![image](https://user-images.githubusercontent.com/51787620/80200010-af899800-862a-11ea-8779-102e70076dc5.png)
more info:
I built the docker image for ActiveMQ Artemis from [here](https://github.com/apache/activemq-artemis/tree/master/artemis-docker) I think its because of this that default arguments they used in their Dockerfile mismatches with the Hono's settings

**Comment by roullli** [comment]
How can I force the Kubernetes (when I'm running Hono) to deploy Hono on a specific node in my cluster?

**Comment by sophokles73** [comment]
IMHO the Artemis image that we are using in Hono has been built from https://github.com/EnMasseProject/artemis-docker-base
