### ISSUE TITLE
Command And Control API : command message ID

### ISSUE THREAD

**Issue by ppatierno** [eclipse/hono#19]
In order to define a relation between a command sent to a device and related result from the device itself, it's useful to specify the "message-id" as AMQP property in the command message.
At same time, the response from the device can contain the "correlation-id" (AMQP property) with the value of the message-id received.
It's true both for command execution result and my proposal about feedback from device (see issue #18 )

**Comment by sophokles73** [comment]
Yes, I agree. we also discussed this during our call this morning. It seems that we are all pretty well aligned regarding these things :-) @hekonsek wanted to update the Command & Control API wiki page accordingly ...

**Comment by hekonsek** [comment]
Agreed. I have improved that part of specification already.

Thanks!
