### ISSUE TITLE
Improve LoRa adapter Command & Control handling (for >1 adapter instances)

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1901]
With the changes for #1272, commands targeted at a LoRa device will only be sent via one specific LoRa adapter instance, regardless of how many instances are deployed. The chosen instance is always the last one that has started up.
To better distribute the load among multiple adapter instances, this should be changed.

Background: Normally, protocol adapters only support one command listener per device and then have a fixed association of the device id with the adapter instance that has the command listener for that device. The LoRa adapter is different here:
LoRa adapters register themselves as command listeners with the same fixed pseudo device id ("lora"). This leads to the "lora" device id being associated with the last LoRa adapter instance that has registered itself that way. All commands for the "lora" device (and matching tenant) will be sent to that instance then.

**Comment by sophokles73** [comment]
@calohmn can we close this issue, now that the Lora adapter's C&C functionality has been removed as part of #1976 ?

**Comment by calohmn** [comment]
@sophokles73 yes
