### ISSUE TITLE
Remove defining password secrets with user provided password hash, function and salt

### ISSUE THREAD

**Issue by kaniyan** [eclipse/hono#1929]
The credentials management API states that defining password secrets with user provided password hash, function and salt is already deprecated and to be removed in the next upcoming versions. The _pwd-plain_ property is to be used going forward. This issue is created for the removal of the deprecated provision.

**Comment by dejanb** [comment]
@kaniyan we reverted the decision to deprecate that with #1791. I see now that one note is left, but IMHO we should remove it.

**Comment by jbtrystram** [comment]
Hello,

It was decided to keep the feature but we added a whitelist of authorised hashing algorithm to increase the security on that. 
https://github.com/eclipse/hono/pull/1804

**Comment by kaniyan** [comment]
@dejanb, @jbtrystram Thanks for the info and as you suggested it is good to have that note removed from the API doc.
