### ISSUE TITLE
Combine the device registration and credentials API default implementation in a single file

### ISSUE THREAD

**Issue by sysexcontrol** [eclipse/hono#193]
Although the device registration data and the credentials data always belong to a specific device, they are kept in different files.
This should be changed so only one file keeps all the device relevant data.

At a later point this probably moves to a separate microservice that serves all device relevant registration information, but the two APIs would not be implemented by different microservices - thus the file based separation is not necessary, but rather artificial.

**Comment by sophokles73** [comment]
After having used the demo Device Registry for some time now, there doesn't seem to be a real need for this.
