### ISSUE TITLE
Upgrade to vertx 3.9.x

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1937]
Upgrade to the latest vert.x version.

**Comment by sophokles73** [comment]
@calohmn are you going to perform the upgrade any time soon or are you waiting for something in particular?

**Comment by calohmn** [comment]
@sophokles73 I'm still waiting for most of the CQs here.

**Comment by sophokles73** [comment]
You can already make the change and push to the repo. The only thing we need to make sure is that the CQs are approved before we do the 1.3.0 release.
