### ISSUE TITLE
MQTT protocol adaptor doesn't wait for Hono Server's acknowledgement

### ISSUE THREAD

**Issue by francois-travais** [eclipse/hono#194]
When publishing an event using MQTT and QoS 1, the device receive `PUBACK` message without waiting for Hono server acknowledgement.

This issue has been discussed with @sophokles73 in the [mailing list](http://dev.eclipse.org/mhonarc/lists/hono-dev/msg00357.html).

**Comment by francois-travais** [comment]
I can work on fix but I'll like to make sure that I'm on the right track.
To me it looks like the problem lies in the `VertxBasedMqttProtocolAdapter`:
```
    private void doUploadMessage(final String tenant, final String registrationAssertion, final MqttEndpoint endpoint, final MqttPublishMessage message,
            final MessageSender sender, final Future<Void> uploadHandler) {

        boolean accepted = sender.send(endpoint.clientIdentifier(), message.payload().getBytes(), CONTENT_TYPE_OCTET_STREAM, registrationAssertion);
        if (accepted) {
            if (message.qosLevel() == MqttQoS.AT_LEAST_ONCE && endpoint.isConnected()) {
                endpoint.publishAcknowledge(message.messageId());
                uploadHandler.complete();
            }
        } else {
            uploadHandler.fail("no credit available for sending message");
        }
    }
```
I think that the `sender` should take an handler as parameter to signal when Hono server has acknowledged the message. Which means that I'll have to modify the signature of `MessageSender.send` and implement it correctly in `AbstractSender.send` and `AbstractSender.sendMessage`.  And then reflect changes to `VertxBasedMqttProtocolAdapter` and the HTTP counterpart.

How does that sounds to you?

**Comment by sophokles73** [comment]
That sounds about right :-)
Currently, the `AbstractSender` uses a disposition handler (`AbstractSender.setDispositionHandler`) at the instance level which doesn't seem to make sense to me because disposition handling should be done at the message level. So, I guess you are right in that we should provide variants of the `send` methods allowing to pass in a disposition handler. WDYT?

**Comment by francois-travais** [comment]
How does that look?
```
private void doUploadMessage(final String tenant, final String registrationAssertion, final MqttEndpoint endpoint, final MqttPublishMessage message,
        final MessageSender sender, final Future<Void> uploadHandler) {

    boolean accepted = sender.send(endpoint.clientIdentifier(), message.payload().getBytes(), CONTENT_TYPE_OCTET_STREAM, registrationAssertion, (messageId, delivery) -> {
        LOG.trace("delivery state updated [message ID: {}, new remote state: {}]", messageId, delivery.getRemoteState());
        if (message.qosLevel() == MqttQoS.AT_LEAST_ONCE && endpoint.isConnected() && Accepted.class.isInstance(delivery.getRemoteState())) {
            endpoint.publishAcknowledge(message.messageId());
            uploadHandler.complete();
        }
    });
    if (!accepted) {
        uploadHandler.fail("no credit available for sending message");
    }
}
```
I'm not sure what to do if the `remoteState` is not `Accepted`? And I guess we don't need `MessageSender.send` to be synchronous anymore and give it a more generic `dispositionHandler` that would tell the caller whether or not the queue is full to implement this logic which is currently in `AbstractSender.send`:
```
public final boolean send(final Message rawMessage, final BiConsumer<Object, ProtonDelivery> dispositionHandler) {
    Objects.requireNonNull(rawMessage);
    Objects.requireNonNull(dispositionHandler);
    if (sender.sendQueueFull()) {
        return false;
    } else {
        context.runOnContext(send -> {
            sendMessage(rawMessage, dispositionHandler);
        });
        return true;
    }
}
```

**Comment by dejanb** [comment]
@francois-travais MQTT protocol don't have any mechanism with which we can reject that QoS 1 message, so our options would be to try resend it or disconnect. Other stuff looks good so far. It'd be good to create a PR with, to make it easier to review and collaborate on the solution

**Comment by francois-travais** [comment]
Sorry for the fail PRs, I forgot to sign my commits and sign Eclipse license agreement.

**Comment by sophokles73** [comment]
@francois-travais Hi Francois, does this work now for you? If so, can you please close the issue?

**Comment by sophokles73** [comment]
@francois-travais feel free to re-open if this doesn't work for you.

**Comment by francois-travais** [comment]
Yes sure. It worked for me. But I think another part wasn't working as I expected: if I recall correctly hono server acknowledge the message sent by the adapter before it is received by the southbound application or the broker.
