### ISSUE TITLE
Basic auth with username including `@` fails on some LoraWAN network servers.

### ISSUE THREAD

**Issue by BobClaerhout** [eclipse/hono#1949]
Some network servers(NS) have problems accepanting/sending the current username scheme which is used by Hono. This username contains the `@` symbol which is a special character and which should be encoded somehow.  
Although this is actually an issue of the LoraWAN NS, I think we can try to fix this within hono. Because the end result is that those NS are not able to connect to Hono.

We discussed this on gitter and also on the last community call and there are 2 possibilities to solve this:

- Leave the password empty and base64 encode the `username@tenant:password` in the username. When hono detects the password is empty, it should decodeBase64 the username again and fetch the credentials from that.
- On gitter another suggestion was also given by @ctron : 
![image](https://user-images.githubusercontent.com/3315222/81379781-fe92fb00-9109-11ea-8ec2-cb1d81577ec1.png) However, I'm not in favor of this approach for following reasons:
  - What if a NS also doesn't accept the `%` symbol?
  - What if the configuration API of the NS accepts it but when sending the data it is interpreted as the start of an encoded symbol which is not the case. So when the configuration API is actually the problem and not the service sending the messages.
   - Overall I think this solution might be more error prone and not as solid as the other solution. The oher solution is also very easy to configure (in ths NS) and detect (at Hono side).

**Comment by ctron** [comment]
The Sigfox backend does have the same problem.

I would also be in favor of the base64 encoding proposal, as it would provide a way to work without any special character.

**Comment by sophokles73** [comment]
@BobClaerhout @ctron is this something that we need to address in *all* adapters or is this just an issue of the Lora and SigFox, or more generally, the HTTP based adapters?

**Comment by ctron** [comment]
I would say it is a problem with systems that are used to work with URLs. Because that is where you need to escape this special characters. I guess this makes it a problem of HTTP based adapters (LoRaWAN, Sigfox, HTTP). Because in the context of MQTT and AMQP, you are more used to provide hostname & port, and username & password some kind of additional field, property, …
