### ISSUE TITLE
Document usage of "hono.registration.*" properties in protocol adapters

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#195]
The use of an external device registry can be configured via "hono.registration.*" properties in protocol adapters (see #185).
Information about this needs to be added to the documentation.

**Comment by sophokles73** [comment]
fixed in d2fdf8ace146c86ee5050bd6222bf09fa29b569d

@calohmn can you close this issue once the updated documentation has been published to the project web site (i.e. tomorrow)?
