### ISSUE TITLE
Management API : get all devices for tenant

### ISSUE THREAD

**Issue by jbtrystram** [eclipse/hono#1958]
The management API is missing a method to retrieve a list of all the devices for a given tenant. 
The request requires pagination, filters and sorting.

Here are a few ideas on how the API can look like : 
Operation : GET on /v1/devices/{tenantId}
The best practices suggest to pass the parameters in the URL, here are a few examples : 
Filtering : `/v1/devices/{tenantId}?enabled=true,via=4711`
Paging : `/v1/devices/{tenantId}?limit=30,offset=50`
Sorting : `/v1/devices/{tenantId}?status.created=ascending`

It is also possible to define JSON payload and pass the parameters in it, but it seems to be an uncommon practice: 
```
{
	"filters" : {
	    "enabled" : true,
	    "via" : 4711"
	 },
	"page" : {
	    "Limit" : 30,
	    "Offset" : 50
	},
	"sort": {
	    "status.created"="ascending"
	}
}
```

Screenshot of displaying the result :
https://marvelapp.com/5gbji22/screen/68233009 

Default paging values and limits must be set, to avoid dumping large chunks of the database in a single response.

**Comment by sophokles73** [comment]
closed via #2109

**Comment by bialad** [comment]
I'm running Hono v1.4.0, but get 501 Not Implemented when calling this endpoint with:

`http://{{REGISTRY_IP}}:{{REGISTRY_PORT_HTTP}}/v1/devices/{{TENANT}}?enabled=false`

Am I doing something wrong?

**Comment by bialad** [comment]
I'm running Hono v1.4.0, but get 501 Not Implemented when calling this endpoint with:

`http://{{REGISTRY_IP}}:{{REGISTRY_PORT_HTTP}}/v1/devices/{{TENANT}}?enabled=false`

Am I doing something wrong?

**Comment by sophokles73** [comment]
@bialad can you please post your question on stackoverflow as described in our [community guide](https://www.eclipse.org/hono/community/get-in-touch/)? We can then answer your question in a way that others can also benefit from.
Thanks
