### ISSUE TITLE
telemetry/events from multiple tenants

### ISSUE THREAD

**Issue by zubairhamed** [eclipse/hono#196]
Currently, each client connection can get either telemetry or events for a single tenant.
Is there a way to get telemetry or events from multiple tenants?

**Comment by sophokles73** [comment]
Hmm, I think this depends on the *AMQP 1.0 messaging network* you are using. The default implementation (one instance of Qpid Dispatch Router + one instance of Apache Artemis) might support this by means of configuring the Artemis broker with some routing rules which consolidate all messages sent to queues with addresses matching *telemetry/** into an aggregated queue (e.g. *telemetry-consolidated*. The Dispatch Router would then need to be configured with a corresponding *linkRoute* and access rules for the *aggregated messages* link.

Maybe @ppatierno can comment on this as well?

**Comment by ppatierno** [comment]
Yes what @sophokles73 is saying can be a valid solution. Artemis supports "diverts" for forwarding from an address to another, so in this case all telemetry/* into only one telemetry-consolidated. I have a question : @zubairhamed do you have this need because you are not interested to know the tenant_id or just because you don't want to have a receiver attached to different addresses (one per tenant) but just to one address (but you are still interested in to know the tenant_id). In the latter case, the current message format for Telemetry API doesn't bring the tenant_id inside the message (only in the address) so you will lose this information. 
@sophokles73 could be a use case that would need changing the API adding the tenant_id even in the message ? at least as optional ? wdyt ?

**Comment by sophokles73** [comment]
>  In the latter case, the current message format for Telemetry API doesn't bring the tenant_id inside the message (only in the address) so you will lose this information.

All messages leaving Hono on the northbound interfaces contain the tenant and device IDs in the *message annotations* under keys `device_id` and `tenant_id` respectively.

**Comment by sophokles73** [comment]
@ppatierno is there also another way of achieving this that would not rely on Artemis capabilities but just Dispatch Router?

**Comment by ppatierno** [comment]
@sophokles73 afaik there is no such feature (like a forwarding from an address to another) in the router but I'll verify !

Regarding the Telemetry and Event APIs, yes it could be better to document because I didn't remember the code and didn't find this information in the doc.

**Comment by sophokles73** [comment]
Regarding Dispatch Router only, I meant if there is another way of achieving the same thing, e.g. doing some clever addressing like opening a receiver link on `telemetry/*` or something?

**Comment by ppatierno** [comment]
For broker it seems to be simpler avoiding diverts as well : https://activemq.apache.org/artemis/docs/2.1.0/wildcard-routing.html 

Regarding router there is no feature which supports what you are saying (receiver link on `telemetry/*`). It would be nice but not supported for now at least.

**Comment by zubairhamed** [comment]
Hey both,

i'm definitely interested in getting the tenant id.

My use-case that the consumer is a service component which handles telemetry from multiple tenants and work on them.

Currently, for every single tenant i need to create a new client and create a telemetry consumer and and another client to create an event consumer.
If i had say, 5 tenants to manage, that would be 10 connections. Before long I would imagine I would exhaust the number of connections.

Maybe I'm using the client wrong.

**Comment by sophokles73** [comment]
You should be able to use the same client for creating all those consumers. Simply invoke the `create*` methods multiple times ...

**Comment by zubairhamed** [comment]
ah yes you're right. i was reusing a handler to register subsequent tenants, now it works!

Sorry for much ado about nothing :) 

Please close if there's nothing else

**Comment by sophokles73** [comment]
glad it works out for you :-)

**Comment by zubairhamed** [comment]
On a somewhat related note, when i  create about 12 consumers, it throws an error:
io.vertx.core.impl.NoStackTraceThrowable: Error{condition=amqp:resource-limit-exceeded, description='link disallowed by local policy', info=null}

And If i recall right, creating 12 instances of HonoClient to connect also throws the same error.

What sort of resource is it consuming? socket connections? memory? Is this supposed to be a hard limit? 

I would imagine that services which are managing much more tenants than this would hit some sort of limit?

**Comment by sophokles73** [comment]
Apart from the fact that we should handle this error properly in the client, it looks like it is the Dispatch Router refusing to establish more links. In any case, these limits are configurable in Dispatch Router's config file which is located in `/etc/hono/qdrouter/` in the *dispatch-router* Docker image.

Which version of the image are you using?

**Comment by zubairhamed** [comment]
i'm using 0.5-M6-SNAPSHOT

**Comment by ppatierno** [comment]
it seems that you are exceeding the "maxConnectionsPerHost" which is 10 (in terms of TCP connections).

**Comment by zubairhamed** [comment]
@ppatierno  So each call to create a consumer (e.g createTelemetryConsumer) uses up a TCP connection?

**Comment by sophokles73** [comment]
> it seems that you are exceeding the "maxConnectionsPerHost" which is 10 (in terms of TCP connections).

This should not be the case. The HonoClient should re-use the same connection. A new consumer is just a new link being established over the same connection. However, I do not know what the (default) limit for links in DR is ...

**Comment by ppatierno** [comment]
> creating 12 instances of HonoClient to connect also throws the same error.

Referring to this we are over 10 maxConnectionsPerHost.
In the other case, it's strange because the default value for maxSenders and maxReceivers should be "unlimited" : https://github.com/apache/qpid-dispatch/blob/master/doc/book/policy.adoc

**Comment by zubairhamed** [comment]
@ppatierno yes you're right, it should be 10 not 12 connections made. 2 attempts failed out of 12.

**Comment by sophokles73** [comment]
Maybe a bug?

**Comment by ppatierno** [comment]
What I see here : 

https://github.com/apache/qpid-dispatch/blob/6e09494502b9abd3d56f32a782b28e366de8da03/src/policy.c#L321

is that if you don't specify maxReceivers, its value is 0 and then here ...

https://github.com/apache/qpid-dispatch/blob/6e09494502b9abd3d56f32a782b28e366de8da03/src/policy.c#L635

you should have the attaching link request approved.

**Comment by zubairhamed** [comment]
oh hmm i was connecting to the hono server's 5671 port, not qdrouter. does it make a difference?

**Comment by ppatierno** [comment]
@zubairhamed can you get the log from the dispatch router ? What is showing on the console ?
You should see something like "DENY AMQP Attach receiver for user ..." as INFO log that is enabled by default in the JSON router file we provide.

**Comment by ppatierno** [comment]
@zubairhamed for receiving you are connecting to the hono server ?

**Comment by zubairhamed** [comment]
whoops belay my last message, it is to port 15671, not 5671. Almost midnight here, eyes starting to act funny :-D

@ppatierno i'll check

**Comment by zubairhamed** [comment]
yup i see it.

2017-06-07 12:54:23.127883 +0000 POLICY (info) DENY AMQP Attach receiver link 'telemetry/TENANT8' for user 'user1@HONO', rhost '10.255.0.3', vhost '(null)' based on link source name

**Comment by ppatierno** [comment]
@zubairhamed but to be sure ... you said that you are connecting on the Hono server ... or the router. I'm confused now :-)

**Comment by zubairhamed** [comment]
I'm connecting to the router for sure. Port 15671.

**Comment by sophokles73** [comment]
@zubairhamed Have you adapted the qdrouter-config.json file? I would assume that you have defined more than 10 tenants in there as groups, haven't you?
And you are creating one consumer for each tenant then, right?

**Comment by ppatierno** [comment]
@sophokles73 they are being denied "based on link source name" not for max count as I supposed before. What is the problem with the link name ?

**Comment by sophokles73** [comment]
I guess that is the whole point: @zubairhamed hasn't defined the tenants as groups in the vhost policy but simply tries to open receiver links on non-existing tenants ...

**Comment by ppatierno** [comment]
@sophokles73 right ... it seems there is no groups named "TENANT8" (reading the error)

**Comment by zubairhamed** [comment]
oh crap yeah you're right. i missed out defining groups! Let me try that. Sorry bout that and thanks!

Z

**Comment by sophokles73** [comment]
@zubairhamed, the default Dispatch Router configuration we ship only grants access to the `DEFAULT_TENANT`. In order to use other or additional tenants, the Dispatch Router config file needs to be changed. I have been working on such a configuration that would allow consumers to connect to arbitrary tenants (by means of allowing access to `telemetry/*`). We need such a config for our Eclipse sandbox server anyways so I will probably make this the default config soon ...

**Comment by zubairhamed** [comment]
yes i glossed over that bit. i defined the telemetry/* bit without defining groups.

**Comment by sophokles73** [comment]
You don't need to define groups in that case. If you already defined `sources: telemetry/*` for the `DEFAULT_TENANT` group then you should be fine. I think it would help if you could post your config file here so that we can take a look ...

**Comment by zubairhamed** [comment]
Here you go:
"DEFAULT_TENANT": {
  "users": "user1@HONO",
  "remoteHosts": "*",
  "maxSessions": 500,
  "maxMessageSize": 102400,
  "sources": "telemetry/*, event/*"
}

**Comment by zubairhamed** [comment]
or should i be modifying qdrouterd-with-broker.json instead?

**Comment by sophokles73** [comment]
> or should i be modifying qdrouterd-with-broker.json instead?

yep, that's the one we are using by default (piping events through an Artemis broker).

**Comment by zubairhamed** [comment]
*doh* ok that's that then. Thanks again.

**Comment by sophokles73** [comment]
I guess we should remove the original one, since we now have a working broker ... you are not the first person confused by the the two config files...

**Comment by sophokles73** [comment]
BTW your `sources` definition lacks an asterisk for the telemetry sources, should be:
`"sources": "telemetry/*, event/*"`

**Comment by sophokles73** [comment]
@zubairhamed, did you get it to work? If so, can you close this issue again?

**Comment by zubairhamed** [comment]
@sophokles73 Ah yes i did. It threw another error, but didn't affect the subscription. I'll log the error here later for posterity. 

Thanks!
