### ISSUE TITLE
Hotrod DeviceConnectionClient: UnsupportedOperationException

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1977]
Our `org.eclipse.hono.deviceconnection.infinispan.client.BasicCache` class invokes `org.infinispan.commons.api.AsyncCache#removeAsync(key, value)`. For a `RemoteCache` instance, as used by the Hotrod client, this method throws a `UnsupportedOperationException`.
````
java.lang.UnsupportedOperationException: null
	at org.infinispan.client.hotrod.impl.RemoteCacheSupport.removeAsync(RemoteCacheSupport.java:145)
````
See also https://infinispan.org/docs/dev/titles/hotrod_java/hotrod_java.html#hotrod_unsupported_methods

**Comment by calohmn** [comment]
Instead of using a `remove(key, value)` method in BasicCache, we might revert back to using `getWithVersion(key)` and `removeWithVersion(key, version)` methods - see https://github.com/eclipse/hono/commit/0e622a43550aabb5595724c40d90d8893446b9b8#diff-07bc9bbdbf3e97d0e4e3e52451f16038L186.

**Comment by sophokles73** [comment]
@calohmn based on your comment I assume that this was not an issue in 1.2.x, right?

**Comment by calohmn** [comment]
@sophokles73 correct
