### ISSUE TITLE
When using the /registration find method, only one result is returned

### ISSUE THREAD

**Issue by zubairhamed** [eclipse/hono#198]
When searching for attributes using the registration FIND endpoint, results always returns one device even though the search paramter matches more than 1 device's attributes.

**Comment by sophokles73** [comment]
According to the [Device Registration API spec]() there is no *find* operation. That said, we had an *unoffical* *find* operation implemented in the `InMemoryDeviceRegistrationService` but that is more than deprecated, i.e. we will remove it soon. Please do not use it. The reason for this is simple, we do not want to require implementors of the API to provide a full fledged management API. In fact, for the same reason we just recently made all of the Device Registation API's operations but the `assert` operation *optional* to implement for the very same reason. Note that this doesn't mean that a Device Registration implementation may not provide sophisticated management operations. It's just that this is up to the implementation and not required by Hono.

HTH

**Comment by zubairhamed** [comment]
Ah gotcha. I'll close both issues then.

**Comment by sophokles73** [comment]
Anyway, is there strong demand in your use case for doing such *find* operations? I am just curious to find out whether our take considering this kind of functionality not part of Hono is reasonable or not. In the end we expect people to integrate Hono with their existing device management infrastructure, e.g. by providing a *facade* just implementing the `assert` operation on top of what they already have. We therefore anticipate that such existing infrastructure would already provide query capabilities so we shouldn't re-invent the wheel ... does that make sense?

**Comment by zubairhamed** [comment]
Oh no there isn't a strong use-case really although it would really help a lot. 

Currently we're just adding a simple UI to manage a customer's devices but I wouldn't imagine doing this for every customer, which means its a one-time implementation.
If a FIND operation isn't available, a LIST devices operation would at least be more essential (since filtering can be done locally after LISTing)
