### ISSUE TITLE
monogdb - always downloaded during build?

### ISSUE THREAD

**Issue by boaks** [eclipse/hono#1983]
Building hono using

```
clean install -Pbuild-docker-image,jaeger 
```

Results always in a download of the mongodb
  
```
Download PRODUCTION:Linux:B64 DownloadSize: 71023715
```

Is that intended?

**Comment by kaniyan** [comment]
An Embedded Mongo DB(`de.flapdoodle.embed.mongo`) instance is being used for the tests. This gets downloaded during the build process. The _flapdoodle_ documentation talks about a `static` approach which caches the extracted executables and library files. May be  this could help. But the problem with this approach is, that it doesn't work with _travis_ and the _travis_ build fails. A further investigation could help to resolve this.

**Comment by boaks** [comment]
Is it possible to disable these tests on a local build?

**Comment by kaniyan** [comment]
I remember from reading, some options like -DsomeModule.skip.tests=true. For more information you could also check the _sure-fire_ plugin documentation.

**Comment by calohmn** [comment]
I would appreciate a solution here that on the one hand doesn't involve downloading 70MB and on the other hand doesn't require remembering which tests to ignore each time tests should be run locally.
