### ISSUE TITLE
403 errors - coap - telemetry loadtest

### ISSUE THREAD

**Issue by boaks** [eclipse/hono#1985]
Performing a telemetry loadtest with coap on a local hon deployment using, I get 4.03 errors.

URL:  "coaps://localhost:30684/telemetry" (no hono-ttd parameter).

500 clients, 2 requests per second. 
2 coap-adapter pods

Is there a assumption, how many request per client and seconds should be not exceeded? 

> 08:26:49.206 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.i.AbstractRequestResponseClient - received response [reply-to: device_con/DEFAULT_TENANT/2ba1d561-55b3-48e7-9f20-03c9460381f4, subject: null, correlation ID: devcon-client-c27c2475-0b6a-4440-958b-3bf207b75066, status: 403]
> 08:26:49.206 [vert.x-eventloop-thread-0] WARN  o.e.h.a.c.impl.VertxBasedCoapAdapter - failed to update last gateway [tenantId: DEFAULT_TENANT, deviceId: D580074]
> org.eclipse.hono.client.ClientErrorException: Error Code: 403
> 	at org.eclipse.hono.client.StatusCodeMapper.from(StatusCodeMapper.java:92)
> 	at org.eclipse.hono.client.StatusCodeMapper.from(StatusCodeMapper.java:57)
> 	at org.eclipse.hono.client.impl.DeviceConnectionClientImpl.lambda$setLastKnownGatewayForDevice$2(DeviceConnectionClientImpl.java:199)
> 	at org.eclipse.hono.client.impl.AbstractRequestResponseClient.lambda$mapResultAndFinishSpan$11(AbstractRequestResponseClient.java:1109)
> 	at io.vertx.core.Future.lambda$map$4(Future.java:411)
> 	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:105)
> 	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:150)
> 	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:111)
> 	at io.vertx.core.Future.lambda$recover$6(Future.java:495)
> 	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:105)
> 	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:150)
> 	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:111)
> 	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:176)
> 	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:21)
> 	at org.eclipse.hono.client.impl.AbstractRequestResponseClient.handleResponse(AbstractRequestResponseClient.java:458)
> 	at org.eclipse.hono.client.impl.HonoConnectionImpl.lambda$createReceiver$18(HonoConnectionImpl.java:852)
> 	at io.vertx.proton.impl.ProtonReceiverImpl.onDelivery(ProtonReceiverImpl.java:218)
> 	at io.vertx.proton.impl.ProtonTransport.handleSocketBuffer(ProtonTransport.java:164)
> 	at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:379)
> 	at io.vertx.core.net.impl.NetSocketImpl.lambda$new$2(NetSocketImpl.java:101)
> 	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:237)
> 	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:127)
> 	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:357)
> 	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
> 	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
> 	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
> 	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1518)
> 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1267)
> 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1314)
> 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
> 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.base/java.lang.Thread.run(Unknown Source)
>

**Comment by boaks** [comment]
Using 50 clients, and 1 request every 2s, still reports that errors.

**Comment by sophokles73** [comment]
This is probably due to the maximum number of devices per tenant being exceeded in the Device Connection service. I assume that you are using the MapBasedDeviceConnectionService provided by the example registry, right? By default, it allows for 100 devices per tenant. You should see DEBUG level messages in the log of the registry pod like this:
> cannot set last known gateway for device [{}], tenant [{}]: max number of entries per tenant reached ({})

**Comment by boaks** [comment]
I assume, that this number  is set to 2000. At least I was able to create 1995 new devices and activate them. 

I get this errors also using 50 clients.

Grep to coap-pod log, I don't seen the message you mention, Is that in the log of an other pod?

**Comment by boaks** [comment]
I already set `maxDevicesPerTenant: 2000`in hono-service-device-registry-secret.yaml.

Therefore I was able to create the 1995 devices.

Must I adapt that number also somewhere else?

**Comment by boaks** [comment]
From the "eclipse-hono-service-device-registry":

> 09:02:26.578 [vert.x-eventloop-thread-0] DEBUG o.e.h.d.s.d.MapBasedDeviceConnectionService - cannot set last known gateway for device [D580078], tenant [DEFAULT_TENANT]: max number of entries per tenant reached (100)

That raises the question, how that 100 is defined over the time.
When I was testing with only 50 (short after the 500) I got the same errors.

**Comment by sophokles73** [comment]
Yes, it is supposed to be in the log of the device registry pod.
This limit has nothing to do with the number of devices you register. This limits the number of *last known gateway* entries in the Device Connection service ...
You can configure the value as described in the [Device Registry Admin Guide](https://www.eclipse.org/hono/docs/dev/admin-guide/device-registry-config/)

**Comment by boaks** [comment]
I tired to set this also in `hono-service-device-connection-secret.yaml`

>       deviceConnection:
>         svc:
>           maxDevicesPerTenant: 2010
>         amqp:
>           ...

But I still get the:

> DEBUG o.e.h.d.s.d.MapBasedDeviceConnectionService - cannot set last known gateway for device [D580935], tenant [DEFAULT_TENANT]: max number of entries per tenant reached (100)

is there a example, how to adjust that number to a larger value?

**Comment by sophokles73** [comment]
The MapBasedDeviceConnectionService is provided by the example Device Registry component. Thus, you will need to configure the property in the yaml file for the device registry ...
Are you using Helm to install Hono?

**Comment by boaks** [comment]
Yes, I'm sure to use the "packages" project.

But I'm not sure, what exactly must be configured.

**Comment by boaks** [comment]
Caused by the quay.io outage, I'm not able to test.
I will come back to such tests in about 2 weeks.
FMPOV, I think closing this issue and reopen it again in the case I didn't manage to configure it, will be the best option.
