### ISSUE TITLE
determineAmqpUri : wrong env var test ?

### ISSUE THREAD

**Issue by ppatierno** [eclipse/hono#2]
Hi,

in the EventDispatcherApplication, the following method implementation is a bit strange to me : 

`
private String determineAmqpUri() {
	if (EventDispatcherApplication.ENVIRONMENT.get("RABBITMQ_PORT_5672_TCP") != null) {
		return "amqp://" + System.getenv(DOCKER_RABBITMQ_ADDR) + ":" + System.getenv(DOCKER_RABBITMQ_PORT);
	} else {
		return EventDispatcherApplication.ENVIRONMENT.get("AMQP_URI");
	}
}
`

Of course there are two ways to define the AMQP connection to the RabbitMQ broker. Regarding the first one is seems it's needed to define the env var "RABBITMQ_PORT_5672_TCP" and then the two DOCKER_RABBITMQ_ADDR (defined as "RABBITMQ_PORT_5672_TCP_ADDR") and DOCKER_RABBITMQ_PORT (defined as "RABBITMQ_PORT_5672_TCP_PORT").

Is the testing env var "RABBITMQ_PORT_5672_TCP" a typo ? Should it has the "RABBITMQ_PORT_5672_TCP_PORT" value (so DOCKER_RABBITMQ_PORT) ?
Should the test be on both env vars port and addr ?
Or it is desired behavior and you need to define three different env vars ?

Thanks,
Paolo.

**Comment by dguggemos** [comment]
Hi Paolo,
the first way covers the Docker Compose case i.e. the ``RABBITMQ_PORT_5672_*`` variables are set automatically by Docker for linked containers. They are not meant to be set manually. If you start the service as a plain Java application it is easier to use the ``AMQP_URI`` variable.

**Comment by sophokles73** [comment]
I see your point, @dguggemos, but I also do not like the fact that we are supporting multiple *types" of environment variables for configuring the dispatcher. Can't we settle for one set of variables?

**Comment by ppatierno** [comment]
HI,
the connection URI is always formatted in the same way : 

amqp://<host>:<port>

I think that the only DOCKER_RABBITMQ_ADDR and DOCKER_RABBITMQ_PORT env vars are enough. Of course they must be set both or we have to assume default values if the user forgot one of them. I think that we can reduce to use only the above two vars (we can use them to build the AMQP_URI one). For example, in my Eclipse IDE I didn't use AMQP_URI but set above two variables (of course I had to set the "RABBITMQ_PORT_5672_TCP" too that we should remove IMHO).

Paolo.

**Comment by sophokles73** [comment]
Yes, I think so too. We should also rename `DOCKER_RABBITMQ_ADDR` to just `RABBITMQ_ADDR` and `DOCKER_RABBITMQ_PORT` to `RABBITMQ_PORT` because they do not have anything to do with Docker. As you already pointed out, you can set them on the command line as well, it just happens so that Docker also sets these variables automatically when linking containers ...
@ppatierno, would you like to do us the honor of becoming the first *external* contributor and submit a pull request? :-)

**Comment by ppatierno** [comment]
@dguggemos what do you mean saying "the RABBITMQ_PORT_5672_* variables are set automatically by Docker for linked containers" ? I can't find any information about that.

@sophokles73 I'm very pleased but I need the above answer to understand better the relation with Docker.

**Comment by dguggemos** [comment]
You can find some documentation here: https://docs.docker.com/compose/link-env-deprecated/
But as stated these are deprecated and I suggest not to use it anymore, but rather switch to the new networking functionality provided by Docker (Compose): https://docs.docker.com/engine/userguide/networking/work-with-networks/#linking-containers-in-user-defined-networks.

**Comment by sophokles73** [comment]
I think we should migrate to version 2 compose files as described [here](https://docs.docker.com/compose/compose-file/#upgrading). This way we would also get rid of the (legacy) `RABBITMQ_PORT_5672_*` variables set by Docker and could just use the `AMQP_URI` environment variable (which I would prefer).

**Comment by ppatierno** [comment]
@sophokles73 I think we can close this issue after your changes.
