### ISSUE TITLE
Operations run on HotRod client thread instead of vert.x thread

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2001]
If the HotRod-client based Device Connection API service/client is used, the operations following a Device Connection API request (e.g. `getCommandHandlingAdapterInstances`) are run in the HotRod client thread used for the request and not in the vert.x thread in which the request was originally triggered.

I think this *might* cause problems regarding concurrency and/or the vertx-proton related operations (?).

**Comment by sophokles73** [comment]
@calohmn I do not know if this already causes issues but in any case IMHO it would be better to run the callback on the vert:x event loop instead of the Hotrod Client thread.
