### ISSUE TITLE
Expect device connection cache to be a transactional cache

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2004]
The device connection cache is currently initialized as a non-transactional cache in the HotRod client.

This causes these kinds of warnings in the infinispan server:
````
12634:22:08:17,372 WARN  [org.infinispan.server.hotrod.HotRodHeader] (HotRod-ServerIO-4-1) ISPN006011: Operation 'PUT' forced to return previous value should be used on transactional caches, otherwise data inconsistency issues could arise under failure situations
12635:22:08:22,389 WARN  [org.infinispan.server.hotrod.HotRodHeader] (HotRod-ServerIO-4-1) ISPN006010: Conditional operation 'REMOVE_IF_UNMODIFIED' should be used with transactional caches, otherwise data inconsistency issues could arise under failure situations
12636:22:08:22,390 WARN  [org.infinispan.server.hotrod.HotRodHeader] (HotRod-ServerIO-4-1) ISPN006011: Operation 'REMOVE_IF_UNMODIFIED' forced to return previous value should be used on transactional caches, otherwise data inconsistency issues could arise under failure situations
````

**Comment by sophokles73** [comment]
IMHO it is the other way around. The device connection cache is not defined as a transactional cache on the Infinispan server. Thus, the client should not force return values, which in this case doesn't seem to be necessary anyway.
On the 1.2.x branch this has already been changed in #2061. On master (for 1.3.0) we also no longer enforce return values.
FMPOV this issue can therefore be closed.
@calohmn WDYT?

**Comment by calohmn** [comment]
Yes, the `ISPN006011: Operation 'PUT' forced to return previous value [...]` warning doesn't occur now anymore.

The `ISPN006010: Conditional operation 'REMOVE_IF_UNMODIFIED' should be used [...]` warning will still come. But as I've understood, we don't really need to act on that and make the cache transactional because of that.
And since Infinispan 10.1, the warning will only appear once ([ISPN-10990](https://issues.redhat.com/browse/ISPN-10990)).
