### ISSUE TITLE
Is there be database supported in Hono 1.3.0?

### ISSUE THREAD

**Issue by gongzhao2** [eclipse/hono#2015]
Hi there,
I saw #1679 issue it will implements mongodb database, I'd like to ask when the stable version(1.3.*) will be released?

Many Thanks!

**Comment by sophokles73** [comment]
please refer to the [Hono Road Map](https://projects.eclipse.org/projects/iot.hono/governance) for this kind of information.

**Comment by gongzhao2** [comment]
Thanks.
