### ISSUE TITLE
Intermittent failures of BaseRegistrationServiceTest

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#202]
We have noticed the `BaseRegistrationServiceTest.testAssertDeviceRegistrationReturnsToken` test to sometimes fail with a Timeout exception:

> 09:53:34.766 [main] INFO  o.e.h.s.r.RegistrationAssertionHelperImpl - using shared secret [65 bytes] for signing registration assertions
> 
> java.util.concurrent.TimeoutException
> 	at io.vertx.ext.unit.impl.TestContextImpl$Step.lambda$run$0(TestContextImpl.java:112)
> 	at java.lang.Thread.run(Thread.java:748)

It happened when run by our Jenkins and also on a dev machine.
I guess the 1000ms timeout should be increased.

**Comment by sophokles73** [comment]
addressed in 139ff4d151fd9d33a70295bc0f4246d9aa3ca2ad
increased timeout to 2secs.
@calohmn can you close this issue, if the commit fixes the problem for you?

**Comment by sophokles73** [comment]
@calohmn is this still an issue?

**Comment by calohmn** [comment]
Just ran the test again with the changes and it looks good now.
