### ISSUE TITLE
Device Registry does not handle malformed payload

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#2020]
The device management endpoint of the example registry returns a `500` status code when trying to register a device that contains additional (unknown) properties like
```json
{
  "unexpected": "property"
}
```
However, it should return a `400` (Bad Request) in this case.

The tenant management endpoint of the example registry returns a `201` status code when trying to register a tenant that contains additional (unknown) properties like
```json
{
  "unexpected": "property"
}
```
However, it should return a `400` (Bad Request) in this case.

**Comment by sophokles73** [comment]
@dejanb @ctron @calohmn The Device Registry Management API actually defines Tenant, Device and CommonCredentials to not allow additional properties.
The question is, if we want to be *lenient* when reading requests and simply ignore any additional unexpected properties or if this should result in a 400.
I think that we should be (consistently) lenient and simply ignore them. WDYT?

**Comment by ctron** [comment]
I am against that. We explicitly defined "extension" sections in order to store data we do not care about.

Simply allowing "out of spec" data would invalidate the idea of defining types in the first place. We would end up with fields and expectations over time, that don't align anymore.

So if we need a new field, then we must add it. If we don't care, then it belongs into the "ext" section.

**Comment by sophokles73** [comment]
I am not saying that we should accept and store the unknown properties. I am proposing to simply ignore them. Not sure if you were aware of that. But if you were and you are still in favor of rejecting requests that contain unknown properties with a 400 then that is of course also a valid option.

**Comment by dejanb** [comment]
I also think it should be better to return proper error to the user (400), as accepting and ignoring properties could lead them to the false confidence that the payload format is alright and lead to other issues later on (if they want to use that ignored properties). Fail fast approach is better IMHO.

**Comment by sophokles73** [comment]
@ctron @dejanb That's fine with me as well. Then let's not be lenient and return a 400 in this case. I will prepare a CQ ...
