### ISSUE TITLE
Replace HONO_MQTT_COMMAND_ACK_TIMEOUT

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2026]
As discussed in https://github.com/eclipse/hono/issues/1632#issuecomment-621053539:
The MQTT adapter property marking the timeout used when sending a command to a device (`HONO_MQTT_COMMAND_ACK_TIMEOUT`) should be brought in line with the corresponding property used for the AMQP adapter (`HONO_AMQP_SEND_MESSAGE_TO_DEVICE_TIMEOUT`).

That means marking `HONO_MQTT_COMMAND_ACK_TIMEOUT` as deprecated and introducing `HONO_MQTT_SEND_MESSAGE_TO_DEVICE_TIMEOUT` to replace it in the future.

For the direction "adapter to qpid" we would have the `SEND_MESSAGE_TIMEOUT` property, and for the other side, "adapter to device", we would commonly have `SEND_MESSAGE_TO_DEVICE_TIMEOUT`. And, as this is somewhat implied by the names, I think we should change the default for `SEND_MESSAGE_TO_DEVICE_TIMEOUT` to be the `SEND_MESSAGE_TIMEOUT` property value (or its default, 1s).

**Comment by fkaltner** [comment]
@sophokles73 As discussed I would like to take care of this

**Comment by fkaltner** [comment]
After having done the changes locally and a deeper look into to configuration and code I'm wondering if this is the right way to go:

I am not sure if we should use a common name for a configuration property which represents in fact a configuration for a parameter which has a distinct name in the MQTT and AMQP world: `ACK` and `DISPOSITION`.

In my (still limited) view of Hono, I regard the protocol adapters as different domains. Hence I think that a user familiar with one of those domains will rather search for the domain-specific terms than something we defined as a common abstraction for both terms, ack and disposition.

So, for me, it would make more sense to actually rename this the other way around, i.e. leave the name of the MQTT configuration parameter and rename:
`HONO_AMQP_SEND_MESSAGE_TO_DEVICE_TIMEOUT` -> `HONO_AMQP_COMMAND_DISPOSITION_TIMEOUT`

WDYT?

**Comment by sophokles73** [comment]
We already use a name  that is independent from the underlying technology in the downstream direction where the *SEND_MESSAGE_TIMEOUT* property is used to configure the time to wait for a disposition update from the AMQP Messaging network. So it seems ok to me to use such a corresponding name for the other direction as well. In the end, the protocol adapters are supposed to abstract away the underlying protocol as much as possible. So using a common (abstract) name across multiple adapters seems reasonable to me here.
