### ISSUE TITLE
Introduce AdapterInstancesLivenessService, use for getCmdHandlingAdapterInstances

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2028]
This came out of the discussions for #1858:

In order to detect and remove stale `commandHandlingAdapterInstance` entries (used in the Device Connection service), a service shall get introduced that keeps track of the currently alive protocol adapter instances. In the implementation of the Device Connection API `getCommandHandlingAdapterInstances` method, such a `AdapterInstancesLivenessService` is to be used in order to skip dead protocol adapter instance entries in the result and to also delete such stale entries.

The default implementation of the `AdapterInstancesLivenessService` shall support protocol adapters deployed in the same Kubernetes cluster and shall use the Kubernetes API to query the corresponding Pods/Containers.

**Comment by calohmn** [comment]
Supporting not only protocol adapters in the same Kubernetes cluster but also (custom) protocol adapters outside of it, requires an extra, new API method for these adapters to announce that they are still alive. Instead of integrating this in the Device Connection API, I would rather do this in the new `CommandRouting` API (see #2029). 
Integrating the new `AdapterInstancesLivenessService` into the `CommandRouting` component also seems more straightforward compared to having to integrate the new service also in the protocol adapters (if the `HotrodBasedDeviceConnectionClient` and no separate Device Connection API component is used).
Therefore I would go for Hono 1.4 here.

**Comment by calohmn** [comment]
FMPOV, there are 2 approaches here, the first requiring the adapters to be part of the same K8s cluster, the second not having that requrirement:

## Option 1: Liveness Check Using a Kubernetes API client in the Command Router

The Command Router places a watch on the list of Kubernetes pods so that it keeps a list of currently alive protocol adapter pods.
A given `commandHandlingAdapterInstance` entry is checked against that list to determine whether the instance is alive.
NOTE: The `commandHandlingAdapterInstance` ID is referring to one verticle instance inside the container inside the protocol adapter pod. That means:
- there are usually multiple `commandHandlingAdapterInstance` IDs per pod (corresponding to the number of verticles);
- using a `commandHandlingAdapterInstance` ID naming pattern like `[podName]_[verticleNo]` (e.g. `hono-adapter-amqp-vertx-cbcf8f967-9wfrw_1`) wouldn't unique identify the verticle instance over time, since the container can be restarted inside a given pod. 
In that case stale device-to-commandHandlingAdapterInstance mappings after a container was restarted couldn't be identified as such.

Therefore, the `commandHandlingAdapterInstance` ID naming pattern should rather be `[dockerContainerId]_[verticleNo]`. The `dockerContainerId` prefix can be identified both by the adapter java application (with some effort) and by the Command Router via the Kubernetes API.


### Requirements for the Protocol Adapters

- in the adapter application, the docker container id is identified (parsing `/proc/self/cgroup`) and used in each adapter verticle to set the `commandHandlingAdapterInstance` as `[dockerContainerId]_[verticleNo]`.
- in the K8s deployment spec, a label is added to identify which container is the actual adapter container


### Requirements for the Command Router

- in the AdapterInstancesLivenessService, a Kubernetes Watch is created on the podlist, identifying the adapter containers and there container ids. 
- the check for whether a given `commandHandlingAdapterInstance` ID is valid means going through the list of container ids and checking for a `[dockerContainerId]_\d*` match with the `commandHandlingAdapterInstance` ID
- the Command Router K8s Deployment Template Spec has to use a K8s service account with a binding to a role that enables watching pods in the corresponding namespace.

------------------

## Option 2: Liveness Check using state provided by the adapters, made available via Infinispan cache

An alternative implementation that also works with adapters not being in the same Kubernetes cluster/namespace.

This involves a new Command Router API method:
 - setAdapterInstanceAlive(instanceId, timeout)
   - timeout=0 meaning adapter instance is about to shut down
   - timeout=-1 meaning adapter instance is alive, at least until the AMQP connection over which this request is made is closed
   - timeout=20 meaning adapter instance is marked as alive for the next 20s, a followup request has to be made before that time has elapsed to again mark the instance as alive

With this approach, the `commandHandlingAdapterInstance` ID can by any UUID, just as it is now.


### Requirements for the Protocol Adapters

- upon init or reconnect of the Command Router AMQP connection, invoke `setAdapterInstanceAlive(instanceId, -1)`
- when shutting down, invoke `setAdapterInstanceAlive(instanceId, 0)`


### Requirements for the Command Router

- implement `setAdapterInstanceAlive` method, storing the id (with timeout value as lifespan) in the infinispan cache. As such cache entries are seldom updated but often read, these entries should better be put in a separate cache with Near Caching enabled, so that data is kept local to the client.

**Comment by sophokles73** [comment]
> using a commandHandlingAdapterInstance ID naming pattern like [podName]_[verticleNo] (e.g. hono-adapter-amqp-vertx-cbcf8f967-9wfrw_1) wouldn't uniquely identify the verticle instance over time, since the container can be restarted inside a given pod.

Isn't that an argument for *not* including the container ID in the name and indeed simply use the pod ID and the verticle No (assuming that the pod ID remains stable when only the container in the pod is restarted)?

**Comment by calohmn** [comment]
When only the container in an adapter pod gets restarted, still all adapter instance id mappings related to the previous container are invalid (when stopping the container, all device connections are cut off and associated command subscriptions are then obsolete).

If the adapter instance id only contained the pod ID, meaning the ID remains stable in that scenario, then the obsolete adapter instance id mappings couldn't be identified as such. The command router would still route commands to this adapter even though there is no command consumer in the container now. 
And if the original command subscription was from the device itself and now a gateway is connected to receive commands for the device, that gateway would never get the commands because the obsolete device->adapterInstance mapping is still there.

**Comment by calohmn** [comment]
A scenario where an adapter container gets restarted in the same pod, would be for example when the `livenessProbe` of the container fails. This leads to `kubelet` killing the container and restarting it.

**Comment by calohmn** [comment]
Option 1 - "Liveness Check Using a Kubernetes API client in the Command Router" has been implemented and added via #2822.
