### ISSUE TITLE
Provide Hono's default implementation of device registry and credentials API as a separated microservice

### ISSUE THREAD

**Issue by sysexcontrol** [eclipse/hono#203]
Currently Hono is providing the base classes and interface for the device registry and the credentials API  together with a default (simple file based) implementation hosted in the Hono server.

Since it is conceptually expected that in real world scenarios this will be implemented by projects built upon Hono, even the default implementation should already be provided in an own microservice.

Projects can then reuse this microservice and exchange the implementation (mapping to any kind of persistence service e.g.).

**Comment by sophokles73** [comment]
@sysexcontrol  I think this can be closed now, right?

**Comment by sysexcontrol** [comment]
Yes, all work is done now.
