### ISSUE TITLE
Device registry doesn't set default values in device registration payload

### ISSUE THREAD

**Issue by jbtrystram** [eclipse/hono#2041]
When creating a device without attaching a body, there are no default registration data attached to it : 

Create the device : 
```
curl --insecure -X POST -i -H 'Content-Type: application/json' http://localhost:28080/v1/devices/DEFAULT_TENANT/dev                             httpClient_add_patch 
HTTP/1.1 201 Created
[...]
```

Retrieve it : 
``` 
curl --insecure -X GET -i http://localhost:28080/v1/devices/DEFAULT_TENANT/dev                                                                  httpClient_add_patch 
HTTP/1.1 200 OK
etag: 109e8b4f-da87-4363-bc5b-838713b7a730
content-type: application/json; charset=utf-8
content-length: 2

{}
```

I think the result should contain the minimal registration data structure : 
```
{
  "enabled": true,
  "defaults": {},
  "via": [],
  "viaGroups": [],
  "memberOf": [],
  "ext": {}
}
```

This can be changed by updating the `@JsonInclude` serialisation annotations in `org.eclipse.hono.service.management.device.Device`

Also : this shows that devices that are created this way have a null value for `Enabled`, which is a bug i think.

**Comment by dejanb** [comment]
This sounds reasonable to me.

**Comment by sophokles73** [comment]
The enabled property is defined as optional with an absent property being defined as `true`, isn't it?
The same is true for the other properties (defined as optional), so I do not quite get, why the response should include empty properties. Maybe you can elaborate why you think that this would be preferable, @jbtrystram ?

**Comment by jbtrystram** [comment]
> The enabled property is defined as optional with an absent property being defined as `true`, isn't it?

Yes, that is the specification : but as shown, it doesn't work. I'll open a PR to fix it. 

> The same is true for the other properties (defined as optional), so I do not quite get, why the response should include empty properties.

For those other optional properties, I think it is more user friendly, but I also see the confusion this creates, as `memberOf` and `via` or `viaGroups` cannot be set at the same time. All in all i admit I don't have a strong opinion about it, it simply felt more natural to me so I opened the discussion.

**Comment by sophokles73** [comment]
> Yes, that is the specification : but as shown, it doesn't work. I'll open a PR to fix it.

Why do you say that it doesn't work? The response doesn't contain an enabled property and that is in line with the spec, which says that it is optional. The default value in this case means that an absent property should be handled as if it had the value `true` (which the registry does). Or am I mistaken?

**Comment by jbtrystram** [comment]
If you add `@JsonInclude` on the `enabled` field in _org.eclipse.hono.service.management.device.Device_ : 

```
curl --insecure -X POST -i -H 'Content-Type: application/json' http://localhost:28080/v1/devices/DEFAULT_TENANT/dev

HTTP/1.1 201 Created
etag: 0c804871-90fd-442f-9ff8-08152e6459b2
location: /v1/devices/DEFAULT_TENANT/dev
content-type: application/json; charset=utf-8
content-length: 12

{"id":"dev"}


curl --insecure -X GET -i http://localhost:28080/v1/devices/DEFAULT_TENANT/dev

HTTP/1.1 200 OK
etag: 0c804871-90fd-442f-9ff8-08152e6459b2
content-type: application/json; charset=utf-8
content-length: 16

{"enabled":null}
```

I can confirm that enabled is null in the File based registry, with a breakpoint and some inspection.

**Comment by sophokles73** [comment]
I don't think I get the point here. I thought we were talking about the external behavior of the registry as described by the API. So far I cannot see any erroneous behavior. The fact that the *enabled* property in the *class* has no value, doesn't *per se* constitute a bug FMPOV as long as it doesn't cause the registry to exhibit erroneous behavior, which it doesn't, as far as I can tell so far.
The implementation of the `Device` class contains
```
    public boolean isEnabled() {
        return Optional.ofNullable(enabled).orElse(true);
    }
```
so any other class, that checks if the device is enabled should get the default value (`true`) if the flag is not set explicitly.

**Comment by jbtrystram** [comment]
Except for any system that relies on the serialisation done by the management API. I.e, a UI.. 
As you point out, if the value is null it should be enabled by default. So why not have the serialisation of the object to match this behaviour, so it is consistent ?

**Comment by sophokles73** [comment]
> So why not have the serialisation of the object to match this behaviour, so it is consistent ?

Are you talking about changing the API, i.e. making the enabled property mandatory instead of optional or are you talking about changing the registry implementation to always include it?
In the former case, a client (a UI) could *not* still not rely on the fact that it is included in a response ...

**Comment by jbtrystram** [comment]
Yeah, the client can assume that if the property is not included in the payload, it's true by default. 
I prefer explicit than implicit, but that is just a matter of opinion. 

I'll close this.

**Comment by sophokles73** [comment]
@jbtrystram @dejanb @ctron @calohmn We could still discuss if we want to change the API and define the *enabled* property as mandatory in order to make it more explicit. WDYT?
