### ISSUE TITLE
Renew Sandbox certificates

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#2042]
The Let's Encrypt certificates need to be renewed. They expired on June 18th (at least the one for the AMQP adapter).

**Comment by sophokles73** [comment]
@b-abel thanks for noticing. I'm on it ...

**Comment by sophokles73** [comment]
I have updated the certificates and have also upgraded Hono to the most recent 1.2.3 release.
@b-abel can you confirm?

**Comment by b-abel** [comment]
> @b-abel can you confirm?

It works now :+1:
