### ISSUE TITLE
Update last gateway only at session creation phase for connection oriented protocols  

### ISSUE THREAD

**Issue by bordeuax** [eclipse/hono#2058]
In case of connection oriented protocols like MQTT and AMQP, last gateway is updated every time when we upload a message or command-response. In my understating this is obsolete because mentioned protocols are session oriented and will be sufficiently to do this only when we create the session after authentication process.
Update last gateway at every message from device, make sense only in case of HTTP and all derivatives base on it.

**Comment by calohmn** [comment]
Consider a device with `[Gateway-A, Gateway-B]` defined in its `via` property. The device changes its connection from one of these 2 gateways to the other from time to time.
The last-known-gateway information is currently used in case both `Gateway-A` and `Gateway-B` have subscribed for commands and it therefore has to be decided which of these 2 gateways a command message shall be sent to.

The suggestion of updating the last-known-gateway only on connection-establishment in case of an MQTT/AMQP connection wouldn't work here ([1]). When the gateways connect via MQTT or AMQP, they only use their gateway credentials - there is no information about specific devices at that point. It is only when the gateway sends a telemetry/event message on behalf of an actual device, that there is the needed information to set the last-known-gateway for the specific device.

I think at some point the topic was brought up, that devices behind gateways may send special event messages that notify northbound applications about them being available now.
When we have agreed on such special messages and a marker for such kind of devices sending them, we could make the change to only set the last-known-gateway on arrival of these special messages for marked devices.


---
[1] We could only do a kind of non-standard-scenario optimization here: if a device (with via gateway(s)) connects _directly_ via MQTT/AMQP to a protocol adapter we set the last-known-gateway (to the device itself) and skip doing so for the event/telemetry messages that the device sends over this connection. We could only do this if we add the requirement that a device mustn't be connected to adapter and gateway at the same time - a requirement we don't yet have. I'm not sure we need such a special optimization.

**Comment by bordeuax** [comment]
@calohmn , thanks a lot for your feedback. I totally miss above scenario. My biggest motivation is to find some optimization for this case, because we done some tests with around 1 million of devices and infinispan have received  a big load. if you don't have other ideas, how we can optimize this,  i suggest to close the issue.
