### ISSUE TITLE
Issue with running prometheus

### ISSUE THREAD

**Issue by roullli** [eclipse/hono#2062]
Hi,
I'm running Eclipse Hono locally in my private Kubernetes cluster. I wanted to run command and control via Rover Telemetry UI.
but I have an issue with running prometheus. every time that Kubernetes tries to run the container it crashes. here is the `Kubectl get pods -n hono` output:
![image](https://user-images.githubusercontent.com/51787620/86343936-4776b400-bc62-11ea-90d3-80c5e564313d.png)
and here is output for `kubectl describe pod eclipse-hono-prometheus-server-776fdcf8cb-sqdjs -n hono`:
![image](https://user-images.githubusercontent.com/51787620/86344311-ce2b9100-bc62-11ea-892a-21471e6ba56e.png)
![image](https://user-images.githubusercontent.com/51787620/86344388-e4395180-bc62-11ea-99de-a9099d377143.png)
can someone help me with this issue? 
my own guess is that the configuration of the prometheus server needs to be customized for my platform? but I'm not sure and also I don't know how is it possible to edit the configurations through Hono?!
Thank you in advance

**Comment by sophokles73** [comment]
is there log output from the prometheus pod?

**Comment by roullli** [comment]
how can I find this log information? Do you mean the `kubectl describe` command?

**Comment by sophokles73** [comment]
No, I mean the output from `kubectl logs ...`

**Comment by roullli** [comment]
here is the logs output:
![image](https://user-images.githubusercontent.com/51787620/87018482-fb83bc00-c1d9-11ea-90e5-329644316ab8.png)
I have no idea what is the issue here?!!

**Comment by sophokles73** [comment]
Looks like Prometheus is not able to access the local file system. Are you deploying to minikube? How did you deploy Hono, did you use the Helm chart? If so, which version?

**Comment by roullli** [comment]
I have deployed Hono on my private kubernetes cluster consisting of two laptops (one as master node and another one as worker node which is hosting Hono).
I have used the Helm version 3 and followed the same instructions as the following link : [https://github.com/eclipse/packages/tree/master/charts/hono](url)

**Comment by sophokles73** [comment]
Which version of the chart are you installing? Can you try with the latest version?

Do a `helm repo update` before installing the chart.

**Comment by roullli** [comment]
I did the repo update but still getting the exact same error!

**Comment by sophokles73** [comment]
My understanding is that you are not installing to minikube, are you? If not, can you first confirm that deployment to minikube as described in the deployment guide works for you? I just want to make sure where we need to look for the problem ...

**Comment by roullli** [comment]
No, I'm using my own private physical (not virtual) cluster.
I have just now tested it with minikube and deployed Hono. There was no problem and all the services are running!!

**Comment by sophokles73** [comment]
Then it looks like you have found the problem. It looks like the Prometheus pod is not able to write to the persistent volume mounted at `/data`. You will need to configure your cluster's PersistentVolume provisioner(s) accordingly.

**Comment by roullli** [comment]
> apiVersion: v1 
apiVersion: v1 
kind: PersistentVolume 
metadata: 
       name: my-local-pv2 
spec: 
       capacity: 
            storage: 8Gi 
       accessModes: 
          - ReadWriteOnce 
       persistentVolumeReclaimPolicy: Retain 
       storageClassName: local 
       hostPath: 
           path: /mnt/data/
Here is my persistent volume yaml file!
You mean if I change the access mode to ReadWriteMany this will fix the issue?!

**Comment by sophokles73** [comment]
Sorry, I do not know much about kubernetes' persistent volumes. You might want to refer to the kubernetes documentation for that.

**Comment by roullli** [comment]
the issue is fixed by changing the directory permission this command:
`chown -R 65534:65534 /mnt/`
Now I'm trying to run command and control application for roverapp.
@sophokles73 I know it is not related to this topic. But, do you have any idea what should I use as influxdb url? since I'm running all the instances locally!!
Thank you in advance.

**Comment by sophokles73** [comment]
Hey, that's great :+1: 
Regarding the *roverapp* and influxdb URL, I have no clue what you are talking about. Does this have anything to do with Hono? If so, I would appreciate if you could post a question on stackoverflow which is the preferred channel for asking questions around Hono.
Can we close this issue?

**Comment by roullli** [comment]
OK, thanks for your help.
Yes, sure I'll close it.
