### ISSUE TITLE
Start program directly with IDE

### ISSUE THREAD

**Issue by allenhan** [eclipse/hono#2063]
hi，

After the program is compiled and packaged, run the program directly in IDE and report the following error. This setdeviceconnectionclientfactory failed to inject successfully. Where is the lack of configuration?

java.util.concurrent.ExecutionException: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'vertxBasedMqttProtocolAdapter': Unsatisfied dependency expressed through method 'setDeviceConnectionClientFactory' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.eclipse.hono.client.BasicDeviceConnectionClientFactory' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

 Looking forward to your reply, thank you

**Comment by allenhan** [comment]
![image](https://user-images.githubusercontent.com/5449138/86463605-665b7000-bd60-11ea-9974-5b8da2081a9d.png)

This injected device_con  Where is the set? How can I not find it in the code. HONO's code is very advanced

**Comment by sophokles73** [comment]
What exactly are you referring to by *the program*? What are you trying to run, a protocol adapter, the device registry etc?

**Comment by allenhan** [comment]
Thank you for your reply. MqttAdapter, The branch I run is v1.2.3. 
I have run activemqt locally. I have run the device connection service, but an error has been reported. Then I run the mqttadapter, which also reports an error. I want to run the project locally, and then use the mqtt.fx Connect the tool and test it. My local code can't run now. Can you give me some advice? If the program is running locally, what configuration information should be added or modified.
HONO deploy is required for local operation. I don't understand how HONO deploy works.


========here is device-connection ==============
aused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tokenValidator' defined in class path resource [org/eclipse/hono/service/auth/delegating/DelegatingAuthenticationServiceConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.eclipse.hono.service.auth.AuthTokenHelper]: Factory method 'tokenValidator' threw exception; nested exception is java.lang.IllegalArgumentException: configuration does not specify any key material for validating tokens
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:656)


![image](https://user-images.githubusercontent.com/5449138/86524130-46839380-bea9-11ea-8bad-525d93247063.png)

I didn't find an instance of ”authentication“ in the code.

=============here is mqtt-adapter=============
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'vertxBasedMqttProtocolAdapter': Unsatisfied dependency expressed through method 'setDeviceConnectionClientFactory' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.eclipse.hono.client.BasicDeviceConnectionClientFactory' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

**Comment by sophokles73** [comment]
Is there a particular reason why you do not simply deploy Hono as described in the [Deployment Guide](https://www.eclipse.org/hono/docs/deployment/helm-based-deployment/)?

**Comment by sophokles73** [comment]
@allenhan can we close this issue?
