### ISSUE TITLE
Make HotrodCache connection check less expensive

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2068]
The `HotrodCache` `isConnected` check is rather expensive because it performs a cache PUT operation each time. That check is invoked in the protocol adapter readiness check and is also performed each time an MQTT connection is made to the MQTT adapter.

When there are many MQTT devices trying to connect to the MQTT adapter in parallel or in quick succession, a lot of unnecessary cache traffic is generated.

A possible improvement would be to only perform the actual cache PUT operation as part of the periodic readiness check. Any intermittent `isConnected` invocations could use a cached readiness check result value.

_
Side note: the `AbstractProtocolAdapterBase.isConnected()` check which invokes `HotrodCache.isConnected` is not used when a device opens an AMQP connection to the AMQP adapter.

**Comment by calohmn** [comment]
@ctron Are there potential alternatives to implementing the actual connection check via a cache put operation? Maybe for the HotRod cache implementation using `remoteCache.getRemoteCacheManager().getConnectionCount()`? And/or just using a `cache.containsKey` invocation?

**Comment by sophokles73** [comment]
@calohmn I originally tried to use the *remoteCache.getRemoteCacheManager().getConnectionCount()* method, but at least with the 9.4 client, this didn't work out as expected.

**Comment by sophokles73** [comment]
> A possible improvement would be to only perform the actual cache PUT operation as part of the periodic readiness check. Any intermittent isConnected invocations could use a cached readiness check result value.

Sounds reasonable
