### ISSUE TITLE
Introduce resource limits or metrics on device level to identify malfunctioning devices

### ISSUE THREAD

**Issue by alinaserg** [eclipse/hono#2083]
Currently the resource limits can be defined in Hono only on the tenant level. With the help of such kind of limits we can control that the usage of one tenant keep within limits and don't disturb usage of the service by other tenants. But the control of the service usage by single devices is also important and not available yet.

The reason why it is important to monitor the behaviour of a single device is very simple. Some of the devices can be malfunctioned and can start to send a lot of data causing additional costs or blocking usage of the service. The limits of the tenant may still be not exceeded, but the malfunctioning device can continue to use available resources of the tenant. Only when the resource limits of the tenant are unexpectedly exceeded, the customer can identify that smth. went wrong and start to analyse what was the cause. At such point of time it's too late to start analysis, as the resources are already consumed.

That's why  I think it could be helpful to have a possibility to define some rules or limits on the device level to have a control over service usage by a single device. 
I think to provide a monitoring on the device level is not so feasible, but I think at least definition of some limits on the device levels could help to improve the situation. 

Looking forward to your opinion.

**Comment by sophokles73** [comment]
Can you provide some examples of such rules/limits at the device level?

**Comment by alinaserg** [comment]
For example AWS IoT Core has the following limit: 

"Publish requests per second per connection: AWS IoT Core restricts each client connection to a maximum number of inbound and outbound publish requests per second. Publish requests that exceed that quota are discarded."
I can imagine that such kind of limit could help us. With the statistic how many devices or which devices exceed this limit the customer can identify such devices.

**Comment by sophokles73** [comment]
It should be possible to track/limit the message rate of devices at the protocol adapter instance based on limits defined at the tenant and/or device level. However, I believe it would be very hard to track the data volume per device over an extended period of time.

**Comment by alinaserg** [comment]
Not relevant any more, I close this issue.
