### ISSUE TITLE
Hono Project Folder Structure

### ISSUE THREAD

**Issue by ArashJavan** [eclipse/hono#2087]
Hi, I am pretty new to this project. I already did the "getting started" and also was able to install "hono" and 
send messages from RP3 to Hono. Now I am trying to understand the Code behind all this magic.
First I tries to find API-files (Interfaces), but it seemed that they are not in a shared folder, but are rather spreaded in different folders. Could somebody plz clarify me about the content of different folders and where each API is locarted. That means following folders:

- Adapters: Here are different adapter implementations
- Client: ?
- Core: ?
- Service-base: ?
- Services: 
   . File-based service, and MongoDB Service,
   . What else?

Thanks
Ajava

**Comment by kaniyan** [comment]
@ArashJavan Each module has a `pom.xml`. For brief info about a module you can refer to the `description` section in corresponding`pom.xml`

**Comment by sophokles73** [comment]
@ArashJavan can we close this issue?

**Comment by ArashJavan** [comment]
@sophokles73, yes, thanks!
