### ISSUE TITLE
Command And Control API : command parameters

### ISSUE THREAD

**Issue by ppatierno** [eclipse/hono#21]
The API doesn't provide information about command parameters.

Currently, command is an application property and could be the same for a variable number of parameters for it (a variable number of application properties ?).

Or command and related parameters should be encoded inside the body as Map for the Amqp Value.

(sorry for duplicating this "issue" here other than dev internal list but it's useful to have all issue tracked IMHO)

**Comment by sophokles73** [comment]
My understanding is that the *parameters* to an operation (command) would be found in the body. The *command* property merely indicates the overall intention of the message very similar to what the HTTP verbs are used for.
For example if I want to invoke an operation that is supposed to return a value I would probably set the `command` property to something like `GET` and set the `to` property to the operation name.

**Comment by ppatierno** [comment]
Ok ... it was not so clear in the API draft.
So "command" is something like HTTP "verb" but why using "To" for the operation name.
In most cases an AMQP client attached to an address (in our case the "control/deviceId" address for sending command) specifies it inside the "To" property as well.
It could be better a different completely new application property or changing the meaning to "command" for that and adding "verb" ... but these are details :-) 

Agree to have parameter inside the body.

**Comment by hekonsek** [comment]
Yes, parameters are sent as a part of the body. Feel free to propose rephrased description of the Command&Control API if you find existing text vague.

**Comment by ppatierno** [comment]
Just adding following ...

If a control message requires additional data to be properly executed **(i.e. command parameters, ...)**

**Comment by hekonsek** [comment]
Updated the specification. Thanks!
