### ISSUE TITLE
Creating new certs per script should offer the possibility to NOT recreate the root and intermediate CAs

### ISSUE THREAD

**Issue by sysexcontrol** [eclipse/hono#211]
The comfortable script create_certs.sh easily leads to create new certificates (e.g. to add new microservices to the overall architecture) with the pitfall that the root and intermediate CA certs are  recreated as well.
This leads to certs that are not based on the previously created CAs.

So the certs always need to be substituted as a whole set, there is no real way of "just adding" one to the existing set.

Easy solution:
The script should have the option to leave out the recreation of the root and intermediate CAs and only (re)create the certs for each microservice.

**Comment by sophokles73** [comment]
To be honest, I do not see the problem with what we do so far:
1. run `create_certs.sh`
1. commit changed artifacts

The keys and certificates created are **only** meant to be used for running the examples. Users need to create and configure their own keys/certificates for production anyways, so I really do not see the point in jumping through hoops in order to make it easier for users to do the *wrong* thing ....

**Comment by sysexcontrol** [comment]
I know - the point is it is just very easy to do it wrong here.
If you have a setup (the committed certs in the demo-certs folder, or possibly a test installation somewhere where the certs were installed) and you want to add some certs - e.g. to introduce a new microservice,
then it seems to be logical to only add or install the new certificates - which is WRONG.
Since then you have a mix of different CAs.

You must install ALL files instead - which might not be what you expect (at least not me). Since you only added some certs.

To offer a simple solution to that I created this issue and the implementation that was quite easy to provide (see PR).
WDYT?

**Comment by sophokles73** [comment]
I do not see that there is a problem here. We are not adding new services to Hono every day. When we add a service, we add a line to the `create_certs.sh` script, run it and commit all changed files.
The same holds true for the case when certificates expire: we run the script and commit all changed files.
Couldn't be easier. We always have a consistent set of key and certificates. FMPOV it is actually **much** easier to keep keys and certs consistent this way (re-build all from scratch) than having to keep in mind when I have added which key and or certificate. This provides for a *reproducible* build.

Users who want to run Hono in production are **strongly advised** to **NOT** use the demo certs and thus need to create their own certificates using whatever infrastructure they have for it. We cannot prevent them from using our script but we shouldn't encourage them to do so by adding features for *managing* the keys ...
