### ISSUE TITLE
Clean up class structure of Device Registry

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#2110]
Below is the class structure for the device management part of the file based device registry which relies heavily on inheritance instead of aggregation.

![image](https://user-images.githubusercontent.com/5682135/90145079-ddcce800-dd7f-11ea-889b-5b2b0d10653a.png)

I believe that we have reached a point where we need to first unclutter the base classes before adding more functionality. In particular, I believe that the *FileBasedRegistrationService* implementing both *DeviceRegistrationService* and *DeviceManagementService* at the same time is problematic. The same is true for the *FileBasedCredentialsService* which implements *CredentialsService* and at the same time *CredentialsManagementService*. Analogously this applies to the *FileBasedTenantService*.

I think that we would be better off with a dedicated DAO layer for accessing the data store and then have independent implementation classes for *DeviceRegistrationService* and *DeviceManagementService*. IMHO it would then be possible to always use dedicated instances for the aggregating AMQP and HTTP endpoints, i.e. they would never need to share the same instance of a collaborator. The only synchronization necessary would then be at the DAO level as can be seen in the diagram below which shows how the classes could be re-structured.

![image](https://user-images.githubusercontent.com/5682135/90145490-4320d900-dd80-11ea-87c7-8ec347e22215.png)

Note that we would also no longer need the *DeviceBackend* interface and the corresponding implementation.

**Comment by kaniyan** [comment]
:+1: IMHO its a much needed restructuring activity.  For the same reason, with the device back-end approach,  _MongoDbBasedRegistrationService_ had to extend _AbstractRegistrationService_ and implement _DeviceManagementService_ instead of using _AbstractDeviceManagementService_.

**Comment by sophokles73** [comment]
With the file based registry having been deprecated (#2657) we can restrict this issue to the Mongo DB based registry implementation.
