### ISSUE TITLE
The connection between Hono MQTT adapter and gateway will broke if forward wrong topic

### ISSUE THREAD

**Issue by gongzhao2** [eclipse/hono#2111]
Hi,

Gateway maintain one connection between Hono MQTT adapter and will publish different message to different topic, such as below topic,
•	telemetry/tenant_id/device01
•	telemetry/tenant_id/device02
but the connection will broke if the device is not registered at Hono.

Does this make sense? If the gateway forwards an unregistered device, the connection between the gateway and hono will be disconnected, and then the gateway will try to reconnect. **During this time, the gateway will not be able to send data to Hono.**

**Comment by sophokles73** [comment]
Closing the connection is the only way for a server to explicitly indicate to a client that it was not able to process a message. The alternative would be to silently discard such messages. If the gateway doesn't care about the fact that its messages are being discarded, then this might be the better option. For devices other than gateways it might be more relevant to be able to detect that its messages will never reach a downstream consumer. This has also been discussed in #2064.

**Comment by gongzhao2** [comment]
Thanks, then I think I should close this issue.
It would be an excellent option if we can configure disconnection or discarding messages separately.

**Comment by sophokles73** [comment]
@gongzhao2 you should add your opinion to #2064 in any case ...
