### ISSUE TITLE
Extend MongoDB device registry to support search devices operation

### ISSUE THREAD

**Issue by kaniyan** [eclipse/hono#2112]
With the completion of the issue #1958,  the _Open API_ spec for the _Device Registry Management API_ contains also  specifications for the new _search devices_ operation. Based on this spec, the _search devices_ operation is to be implemented in the _MongoDB based device registry_.

**Comment by sophokles73** [comment]
@kaniyan can this be closed?

**Comment by kaniyan** [comment]
> @kaniyan can this be closed?

yes. This has been closed via #2116, #2122, #2138 and #2150.
