### ISSUE TITLE
Allow to configure usage of piggybacked response for CoAP adapter on the tenant level

### ISSUE THREAD

**Issue by alinaserg** [eclipse/hono#2125]
The CoAP adapter can send response to the device in the piggybacked mode. And currently this parameter is configurable only on the adapter level.

We would like to have a possibility to configure this parameter additionally on the tenant level, being flexible in the usage of such functionality.

**Comment by sophokles73** [comment]
I would propose to define a corresponding property in the *adapters* property of the *Tenant* object in the Registry Management API, e.g.
```json
{
  "adapters": [{
    "type": "coap",
    "enabled": true,
    "ext": {
      "timeoutToAck": 0
    }
  }]
}
```
The CoAP adapter would then use the config value specified at the adapter level by default with the value specified at the tenant level overriding that default value.

@alinaserg @calohmn @boaks WDYT?

**Comment by alinaserg** [comment]
@sophokles73, thanks for the proposal. For me it sounds reasonable to proceed as you described.
