### ISSUE TITLE
Message mapping API does not return a failed future

### ISSUE THREAD

**Issue by Alfusainey** [eclipse/hono#2133]
Maybe I do not understand the mapper endpoint feature added recently, so please bear with me :-) I will close the issue once my doubt is clarified ;-)

According to HttpBasedMessageMapping#mapMessage API docs, the method is supposed to returned
1. a `mapped message` if the device payload can be successfully mapped to a `new payload type` OR
2. a `failed future`, with a ServiceInvocationException, if the message cannot be mapped. This happens when the device registration info contains a mapper in its config but the adapter is not configured with an Endpoint corresponding to the configured mapper for the device/gateway

However, the current default implementation present with Hono does not do that. In the default impl., if a mapper is not configured for a device/gateway, or it is configured but endpoint is either missing or not configured for the adapter, then the original message is mapped `as-is`. No failure is returned. If this is the intended behavior, should the API docs be adapted accordingly?

If you look at where the API is used (i.e the `onPublishedMessage` handler of the MQTT adapter), I can see why the original message is mapped `as-is` instead of returning a failure (makes the caller code easier I think). IMHO, the mapper should not map all incoming MQTT messages: either it successfully maps an incoming message (if it can) or fails. In the case of a failure, the MQTT adapter can proceed to forward the message like before, ignoring the failed attempt to mapped the message.

**Comment by sophokles73** [comment]
@BobClaerhout Hi Bob, would you mind taking a look at this and get in touch with @Alfusainey ?

**Comment by BobClaerhout** [comment]
Thanks for the notification @sophokles73.
Hi @Alfusainey,

The primary goal of adding the mapper is/was making sure that the other processing continued without any problems at all costs. This means that it should not fail in any way when nothing is configured, wrongly configured, ...

If I'm correct, the mapper will return a failure when the actual mapping doesn't work (in the pure sense of the word, this is a failure to me). I think what you are talking about here is more of a semantic discussion on the word "failure". Did the mapping really fail if e.g. the mapping was not configured at all or wrongly configured? If so, we can return a failure as well. If we believe this is not really a failure but wrong configuration and for that reason the mapper is doing just fine, we can just return the original payload as-is.

Personally, I don't really have a preference, I can live with both implementations, it's just a different take on this but the end result is the same. I have one remark though: If the mapper is capable of doing error handling (like catching wrong configuration) and returning the original payload, we do not need to repeat ourselves in all the adapter doing the same error handling. But as I said, either way is good for me.

PS: good to see other users are interested in the mapping feature :) we are using it and it is doing a perfect job!

**Comment by Alfusainey** [comment]
Thanks @BobClaerhout for the clarification! i will add my concerns inline

> If I'm correct, the mapper will return a failure when the actual mapping doesn't work (in the pure sense of the word, this is a failure to me)

ok, can you please point me to the codebase where such a failure is returned? I cannot seem to find it

According to the API contract of the message mapping:
```
 /**
     * ...
     * @return A future indicating the outcome of the operation.
     *         The future will be completed with the mapped message or failed with
     *         a {@link org.eclipse.hono.client.ServiceInvocationException} if the
     *         message could not be mapped.
     * @throws NullPointerException if any of the parameters are {@code null}.
     */
```
So I am only going by what is stated in the API above. If any user of the API reads that, then it is fair to assume that ANY implementation will return a failed future (with a SIE) if the message cannot be mapped. However, the current default implementation (i.e `HttpBasedMessageMapping`) does not return any failure (as far as i can see). Do you see what I mean?

> If we believe this is not really a failure but wrong configuration and for that reason the mapper is doing just fine, we can just return the original payload as-is.

Ok, then IMHO  this is important info that needs to be documented in the API.

> I have one remark though: If the mapper is capable of doing error handling (like catching wrong configuration) and returning the original payload, we do not need to repeat ourselves in all the adapter doing the same error handling

If from a software engineering point of view, it is okay to have the mapping service always succeeds regardless of whether it can handle a given request or not, then i am fine with this.

BTW: i am not using the superb mapping feature. All I am doing is keeping myself up-to-date with a codebase that is constantly evolving with new features/improvements :-)

**Comment by sophokles73** [comment]
FMPOV we need to deal with the following cases:
1. No mapping service is configured for the gateway.
2. Mapping service is configured for the gateway but the configured URL is invalid.
3. Mapping service is configured for the gateway but invocation of the service results in an error status code.

Maybe we can agree on the following error handling:

1. Nothing to be done at all.
2. Should be handled during application startup, if possible. URLs could be checked for valid syntax by the configuration class.
3. The device's data should not be forwarded downstream and the device should be notified about the failure to process the data (if the device's transport protocol supports it). 

WDYT? @BobClaerhout @Alfusainey

**Comment by Alfusainey** [comment]
@sophokles73 

> Maybe we can agree on the following error handling:
1. Nothing to be done at all.

👍 
If its not configured, then mapping is not needed and the forwarding of messages should proceed like before

> 2. Should be handled during application startup, if possible. URLs could be checked for valid syntax by the configuration class.

 👍 

> 3. The device's data should not be forwarded downstream and the device should be notified about the failure to process the data (if the device's transport protocol supports it).

Yes. If a user needs the mapping service and configured it correctly with a valid URL, it sounds reasonable to me to abort forwarding of the message and notify the device (if possible)

**Comment by BobClaerhout** [comment]
I think there is a 4th option as well. Consider following use-case:  
We have a gateway which is sending data for devices. Most of the time, the messages are coming from the devices and thus the payload can be mapped (i.e.: a new deviceId can be found within the message). However, the gateway also sends messages, these messages do not contain any deviceId since this is coming from the gateway itself. In that case, the mapping should be called, but the mapping should have the ability to let the adapter know, no mapping has been done and the adapter can continue using the existing deviceId (=gateway) and payload.

**Comment by sophokles73** [comment]
> n that case, the mapping should be called, but the mapping should have the ability to let the adapter know, no mapping has been done and the adapter can continue using the existing deviceId (=gateway) and payload.

@BobClaerhout how should/could this be accomplished?

**Comment by BobClaerhout** [comment]
In case of the `HttpBasedMessageMapping` this can be done by returning a different HTTP STATUS CODE: I suggest returning a 204 when no mapping has been done compared to a 200 when the mapping has succeeded.  
I don't know how this should work when the mapper is called using another protocol but IMO the mapping shouldn't fail in that case.

**Comment by sophokles73** [comment]
This would require a change of behavior in the protocol adapter for handling this status code, wouldn't it? Couldn't the mapper simply return the message payload and device ID unaltered in its response in this case? IMHO the adapter would then simply forward the message downstream using the gateway's device ID as intended, wouldn't it?

**Comment by BobClaerhout** [comment]
I don't think so, right now, mapping fails:

```
webClient.post(mapperEndpoint.getPort(), mapperEndpoint.getHost(), mapperEndpoint.getUri())
            .putHeaders(headers)
            .ssl(mapperEndpoint.isTlsEnabled())
            .expect(ResponsePredicate.SC_OK)
            .sendBuffer(ctx.message().payload(), httpResponseAsyncResult -> {
                if (httpResponseAsyncResult.succeeded()) {
                    final HttpResponse<Buffer> httpResponse = httpResponseAsyncResult.result();

                    final Map<String, String> additionalProperties = new HashMap<>();
                    httpResponse.headers().forEach(entry -> additionalProperties.put(entry.getKey(), entry.getValue()));

                    final String mappedDeviceId = Optional.ofNullable(additionalProperties.remove(MessageHelper.APP_PROPERTY_DEVICE_ID))
                            .map(id -> {
                                LOG.debug("original {} has been mapped to [device-id: {}]", ctx.authenticatedDevice(), id);
                                return id;
                            })
                            .orElse(targetAddress.getResourceId());

                    result.complete(new MappedMessage(
                            ResourceIdentifier.from(targetAddress.getEndpoint(), targetAddress.getTenantId(), mappedDeviceId),
                            httpResponse.bodyAsBuffer(),
                            additionalProperties));
                } else {
                    LOG.debug("mapping of message published by {} failed", ctx.authenticatedDevice(), httpResponseAsyncResult.cause());
                    result.complete(new MappedMessage(targetAddress, ctx.message().payload()));
                }
                resultHandler.handle(result.future());
            });
```

It currently expects an `SC_OK`. If the mapping fails, the message is returned with the original data. So no change is required,  however, it's not documented that way. We currently have it implemented as described above.

**Comment by sophokles73** [comment]
But didn't we want to reject the data from the device if invocation of the mapper fails (case 3)?

**Comment by BobClaerhout** [comment]
Ah ok, now I see :)  
Yes, if we are implementing that, I believe we should allow all 2xx return codes to result in an upstream message. Of which 204 results in using the gateway id and payload and 200 results in using the new deviceId and payload.

**Comment by sophokles73** [comment]
and then we could as well say that the mapper can only return a 200 code with the mapped payload in the response body. The mapper implementation would then simply include the request body in the response and the device ID from the request header in the response header and the HttpBasedMapper doesn't need to consider 204 explicitly. WDYT?

**Comment by BobClaerhout** [comment]
That's indeed a possibility. I think it's personal preference. To me, it sounds a bit strange that a 2xx code could result in an exceptional flow in the adapter. It's exactly what the http status codes are for IMO. However, if you prefer only accepting 200 codes, I'm fine with it.

**Comment by sophokles73** [comment]
@BobClaerhout I did not want to prescribe any particular implementation. However, IMHO returning 200 in the given case will be easier to implement as there is no additional handling of 204 required ...

**Comment by sophokles73** [comment]
@BobClaerhout any further comments? I guess the code will need to be updated/adapted to what we discussed in any case, right?

**Comment by BobClaerhout** [comment]
@sophokles73  I don't have any more comments on that. The code indeed needs an update for that. We can start by implementing the 200 already and see whether we can add the 204 return code as well later.

**Comment by sophokles73** [comment]
@BobClaerhout are you going to create a PR for this?

**Comment by BobClaerhout** [comment]
TBH I'm a bit busy. I would be happy to create a PR for this but I can't do this right now.

**Comment by sophokles73** [comment]
@BobClaerhout @Alfusainey 
Maybe Alfu wants to jump in?

**Comment by Alfusainey** [comment]
sure, i will take a look :-) when is the next (earliest) release date? i couldn't find it [here](https://projects.eclipse.org/projects/iot.hono)

**Comment by sophokles73** [comment]
@Alfusainey I have added the 1.5.0 release to the project management website.

**Comment by BobClaerhout** [comment]
great! Thanks @Alfusainey!
