### ISSUE TITLE
MongoDB implementation does not support client context matching

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#2134]
The Credentials API's *get* operation provides means to include a *client context* which the service implementation may use to determine matching credentials on record.
The file based registry does support this already. In particular, it will not return the following credentials on record
```json
{
  "auth-id": "4711",
  "type": "hashed-password",
  "secrets": [ ... ],
  "ext": {
    "client-id": "AA"
  }
}
```

for a request with the following search criteria:
```json
{
  "auth-id": "4711",
  "type": "hashed-password",
  "client-id": "BB"
}
```
However, the MongoDB currently does not consider the client context and thus (erroneously) returns the credentials mentioned above.

**Comment by kaniyan** [comment]
This is not yet implemented and a _TODO_ is still open. If it can wait, I can start after finishing the IT tests for search devices operation and implementing tenant existence check while registering devices.
https://github.com/eclipse/hono/blob/e30ba4b192b5be4b34315c1325a2a113092b0322/services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedCredentialsService.java#L415-L422
