### ISSUE TITLE
adapters keeps accepting connection from device (with  X.509 certificate) even when tenant's trusted-ca is deleted.

### ISSUE THREAD

**Issue by meshkatul-anwer-bosch** [eclipse/hono#2137]
If the trusted-ca of a tenant is removed, the expected behavior may be, that all further connection requests with  X.509 certificates ( signed by the removed root-ca) should be denied. However, it looks like adapters ( observed on http-adapter ) keeps accepting new connections. Only after a restart of all the adapter pods ( in our test case http-adapter, could be the same for MQTT-adapters also), the changes are taken into account.

**Comment by calohmn** [comment]
Possibly the tenant object was still cached in the protocol adapter here.
The maximum age of the cache entry is defined by the `max-age` cache directive used in the device registry implementation (for the MongoDB implementation this is configured via the `cacheMaxAge` property with a default of 3 minutes). If the used device registry implementation doesn't set this cache directive, the client (ie. the protocol adapter) uses the value configured in the `responseCacheDefaultTimeout` property, with a default of 10 minutes.
@meshkatul-anwer-bosch Could you check whether this problem still exists after having waited for the corresponding time period?

**Comment by meshkat632** [comment]
During the test, we observed that the cache is getting refreshed after 10 min.  So closing the issue.

**Comment by sophokles73** [comment]
@meshkat632 then please do so (i.e. close this issue) :-)
