### ISSUE TITLE
HTTP adapter: "authenticate device" span has no parent (certificate authentication)

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2144]
For an incoming HTTP request using certificate authentication, the HTTP adapter creates an "authenticate device" span that doesn't have the corresponding "POST" (or "PUT", etc.) span as its parent.
That means the "authenticate device" span is not part of the whole HTTP request trace.

**Comment by sophokles73** [comment]
Are we talking about the span that is used for retrieving the trust anchor? If so, then we cannot help it because at the TLS handshake level, there is no HTTP request yet ...

**Comment by calohmn** [comment]
It's the span created by the `X509AuthProvider` with the span context given by the `X509AuthHandler`. And the latter is set in a route handler that comes after the handler that creates the root span. So the root span to be referenced here is actually already available.

With the fix given in #2146, the trace will look like this:
![Http_cert_auth_trace](https://user-images.githubusercontent.com/891931/91882223-f3e50e80-ec82-11ea-89df-ae8c3c64e66a.png)
Without the fix, that part in the red box is in a separate trace.
