### ISSUE TITLE
Transport protocol agnostic interface for Hono-Client

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#2156]
To use [Kafka for messaging](#8 ), the Hono client must be refactored so that its interface is abstracted from AMQP 1.0 and allows the use of a different protocol.

**Comment by sophokles73** [comment]
@b-abel  now that we have added the new interfaces, can we close this issue?

**Comment by b-abel** [comment]
> @b-abel now that we have added the new interfaces, can we close this issue?

@sophokles73 Yes.

**Comment by sophokles73** [comment]
closed via #2168
