### ISSUE TITLE
Adding credentials gives a bad request error

### ISSUE THREAD

**Issue by roullli** [eclipse/hono#2171]
Hi,

I'm trying to add credentials for the device 4711, but I'm receiving this error:

![image](https://user-images.githubusercontent.com/51787620/92933373-db2ce380-f44e-11ea-8aee-f3fa5b56560a.png)

I also tried this for version 1.3 : 
![image](https://user-images.githubusercontent.com/51787620/92933595-18917100-f44f-11ea-8b0b-ca246c90b079.png)
 but again I get this error: 
![image](https://user-images.githubusercontent.com/51787620/92933728-4bd40000-f44f-11ea-8dd7-ca30b5c35923.png)

I don't what is that I'm doing wrong!!?

**Comment by sophokles73** [comment]
You must not include the *device-id* property in the credentials.

**Comment by roullli** [comment]
I removed the 'device_id' property, but still having the same issue:
![image](https://user-images.githubusercontent.com/51787620/93054747-8073d180-f672-11ea-966f-15b0590e15d0.png)

**Comment by sophokles73** [comment]
Can you please post the output as text so that I can copy it easily to test locally?

**Comment by roullli** [comment]
Sure, Thanks:

`curl -i -X PUT -H 'Content-Type: application/json' --data-binary '{
    "type": "hashed-password",
    "auth-id": "'$AUTH_ID'",
    "secrets": [{
        "hash-function" : "sha-512", "pwd-hash": "'$PWD_HASH'", "not-after": "2020-03-31T00:00:00+01:00"
    }]
}' http://192.168.1.151:28080/v1/credentials/DEFAULT_TENANT/4711`

**Comment by sophokles73** [comment]
Oh and which Hono version are you running and how did you deploy? Are you running on a local minikube cluster?

**Comment by roullli** [comment]
I'm running the last version. 1.3
I have built my own Kubernetes cluster.

**Comment by sophokles73** [comment]
And how did you deploy? Using the helm chart?

**Comment by roullli** [comment]
first one is 4711_auth,
and the second one is a hashed password

yes, I used helm chart. I updated the repo and then deployed hono

**Comment by sophokles73** [comment]
Is the hashed password base64 encoded?

**Comment by roullli** [comment]
yes I used this command: 

`PWD_HASH=$(echo -n $PWD | openssl dgst -binary -sha512 | base64 -w 0)`

**Comment by sophokles73** [comment]
Ok, there are two problems with your payload:
1. The payload must be a JSON Array. Yours is a JSON Object.
2. The *auth-id* property does not comply with the pattern used by the file based registry (`^[a-zA-Z0-9-=.]+$`) which is different from the pattern documented in the Device Registry Management API (`^[a-zA-Z0-9-_=.]+$`).

The second issue obviously is a bug in the file based registry. However, you should be able to fix it simply by replacing the underscore with a dash, i.e. `4711-authid` ...

**Comment by roullli** [comment]
Thanks,
I replaced it with this command:
`curl -X PUT "http://192.168.1.151:28080/v1/credentials/DEFAULT_TENANT/4711" -H "accept: */*" -H "Content-Type: application/json" -d "[{\"auth-id\":\"4711-auth\",\"type\":\"hashed-password\",\"secrets\":[{\"pwd-hash\":\"'$PWD_HASH'\",\"hash-function\":\"sha-512\",\"not-after\":\"2020-03-31T00:00:00+01:00\"}]}]"`
and it didn't prompt me anything. is it fine? or should it prompt a msg back?
![image](https://user-images.githubusercontent.com/51787620/93065562-8a510100-f681-11ea-9e1b-0e68532fb0a9.png)

**Comment by sophokles73** [comment]
No, it should be fine. You can check with
```sh
curl http://192.168.1.151:28080/v1/credentials/DEFAULT_TENANT/4711
```
and check if the device's credentials match your expectation ...

**Comment by roullli** [comment]
![image](https://user-images.githubusercontent.com/51787620/93066405-a30de680-f682-11ea-9153-e35291f88ab7.png)

Yes, correct. Thanks a lot.  I'll close the issue!
