### ISSUE TITLE
Invalidating tenant/device/credentials cache entries in protocol adapters

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2176]
When a device or a tenant is getting disabled in the device registry, it could take up to the configured `cacheMaxAge` period for this change to take effect in the protocol adapters - if the old device/tenant object is cached in the protocol adapter.

In order to reduce this period (without having the performance impact of lowering the `cacheMaxAge` configuration), the relevant cache entries in the protocol adapters would have to be actively invalidated when a device/tenant/credentials entry has been updated/removed.

Are there ways to do that (with reasonable performance/complexity cost) ?

Maybe such invalidation could be tied to a new flag (`invalidateProtocolAdapterCaches`) of the device/tenant/credentials update/delete operations, so that it can be performed only if needed.

**Comment by sophokles73** [comment]
I would rather not abuse the registry's APIs for doing implicit cache synchronization/invalidation. If such invalidation is strictly needed in addition to the standard cache timeout, I would propose to let a caching framework handle this, e.g. use a distributed invalidating cache for this purpose, e.g. https://infinispan.org/docs/stable/titles/configuring/configuring.html#invalidation-configuring

**Comment by calohmn** [comment]
I agree that letting the cache invalidation be handled by a caching framework should generally be preferred.
However, FMPOV, replacing the current caching logic with Infinispan would mean a general architectural change, requiring the protocol adapters to all be part of an Infinispan cluster then. As far as I understood, we have avoided taking that step until now (being too restrictive, adding complexity, etc.), although it was already brought up in the context of the Device Connection service for example. (In fact, all protocol adapters being part of an Infinispan cluster would possibly offer new possibilites concerning the routing of command & control messages.)

In that sense, my idea above was more geared towards working with the existing caching mechanisms. But we could also discuss introducing Infinispan for that. I think in one of our recent discussing concerning the Command Routing component, we tended towards strongly preferring the protocol adapters to be deployed in the same Kubernetes cluster anyway (and opting for outside "protocol translators" to connect to the AMQP adapter).

**Comment by sophokles73** [comment]
@calohmn is there anything to be done here?

**Comment by sophokles73** [comment]
@calohmn IMHO we can close this now that we have the internal notification API?

**Comment by calohmn** [comment]
@sophokles73 Yes, fixed via #2984.
