### ISSUE TITLE
Old version deployment

### ISSUE THREAD

**Issue by roullli** [eclipse/hono#2181]
I'm trying to run an application which was built based on older versions of Hono. There the registration commands were different than the newer versions. for example: 
`curl -X POST -i -H 'Content-Type: application/json' -d '{"device-id": "'$DEVICE_ID'"}' $HONO_DEVICE_REGISTRY_ADDRESS/registration/DEFAULT_TENANT` this is the format for adding a device to Hono.

First, I want no know is this based on version 0.8? if not! which version?
second, I want to know how to deploy older versions of Hono!?
I tried this command but there were some errors in deploying Hono: 
`helm install --dependency-update -n hono --set honoImagesTag=0.8-M2 eclipse-hono eclipse-iot/hono
`

Thanks in advance!

**Comment by sophokles73** [comment]
The command for registering the device that posted is from before we introduced the Device Registry Management API in Hono 1.0.
Sorry, but we do not support pre-1.0.0 versions anymore. You might be able to find some hints in the source code at pre-1.0.0 tags.
There have been so many changes and improvements since then that IMHO it should be much more beneficial for you to adapt the registration command to the Device Registry Management API instead of deploying an old unsupported version of Hono ...

**Comment by roullli** [comment]
I also tried to use version 1.0.0 and I could not succeed. 
the device registry container does not run properly. I used `kubectl describe` command to see what is wrong with it!
this was the output!
![image](https://user-images.githubusercontent.com/51787620/93741438-1a002d80-fbf5-11ea-9045-3e595af8e8fb.png)

> Readiness probe failed: Get "https://10.44.0.10:8088/readiness": dial tcp 10.44.0.10:8088: connect: connection refused

 I don't know what is this referring to!

**Comment by sophokles73** [comment]
Why don't you simply run the latest version?

**Comment by roullli** [comment]
cause I'm forced to run version 1.0.0. we had a project which was based on hono 1.0.0 and changing the version needs lots of effort.

**Comment by sophokles73** [comment]
How so? We give our best to keep the external API of Hono's major versions backwards compatible, i.e. if you have clients interacting with Hono 1.0.0, they should also be able to interact with Hono 1.4.0 ...
Apart from that, have you downloaded the 1.0.4 Helm chart from the [Downloads page](https://www.eclipse.org/hono/downloads/#previous-versions) or are you trying to use the Helm chart published on Eclipse Packages?

**Comment by roullli** [comment]
I tried to run the project with the latest release but the subscription process does not go well. 
I'm trying to run the roverapp project [https://app4mc-rover.github.io/rover-docs/](url).
I used Helm chart on Eclipse Packages. [https://github.com/eclipse/packages/tree/master/charts/hono](url)

**Comment by sophokles73** [comment]
Then please use the chart from the Downloads page. We migrated the Helm chart to the Packages project with Hono 1.1.0. The chart, however, is not guaranteed to succeed in deploying older versions of Hono.

**Comment by roullli** [comment]
Thank you for the information. 
I'll close this issue.
