### ISSUE TITLE
File and Mongo DB based registries return pre-shared key via management API 

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#2184]
The file based and Mongo DB based registries both include PSK credentials' shared *key* property in the response body of the *read credentials* operation. However, the key should not be included, analogously to the hashed password credentials

**Comment by kaniyan** [comment]
@sophokles73 Could you please assign this to me, if none is already working on it.

**Comment by sophokles73** [comment]
I have already fixed this, PR pending ...

**Comment by kaniyan** [comment]
> I have already fixed this, PR pending ...

:+1:
