### ISSUE TITLE
Device Registry Management API declares plaintext pwd as Base64 encoded byte array

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#2193]
The registry management API declares the plaintext password field of the PasswordSecret as type `String` of format `byte` which means that the property value is supposed to be a Base64 encoded byte array (http://spec.openapis.org/oas/v3.0.3#dataTypeFormat).
FMPOV this is wrong and the plaintext password should be a simple String.
WDYT @calohmn @dejanb @ctron @jbtrystram ?

**Comment by dejanb** [comment]
@sophokles73 Yeah, that looks like a bug to me
