### ISSUE TITLE
PasswordSecret's pwd-hash type is not used as declared

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#2194]
The API declares the *pwd-hash* as type *String* of format *byte* which means that the property value is supposed to be a Base64 encoded byte array. However, if the hash-function is `bcrypt` then the hash is a plain String which itself contains the Base64 encoding of the pwd-hash and the salt used to create the hash.

FMPOV we have the follwing options:
1. Keep the property declared as String with format byte. We then need to adapt the registry implementation to always Base64 encode/decode its value.
2. Declare the property as a plain String and amend its documentation that the value is expected to be a plain String if hash-function is bcrypt and a Base64 encoded byte array otherwise.
3. Declare a separate plain String property *bcrypt-hash* which is only used if hash-function is bcrypt.

IMHO option one is the most consistent one.

**Comment by sophokles73** [comment]
@calohmn @ctron @dejanb @kaniyan WDYT?

**Comment by calohmn** [comment]
Choosing option 1 would mean users have to base64 encode the existing device registry credential values for the Hono 1.5 update, right?
I think I would favour option 2 as the more practical one, as I don't see much benefit implementation-wise to require the `pwd-hash` to be base64 encoded.

**Comment by kaniyan** [comment]
Also with the second option, we could avoid the extra _encode/decode_ of `pwd-hash`  when the `hash-function` is `bcrypt`. I also tend towards option#2. IMHO we could also declare the `pwd-hash`  _type_ using `oneOf` keyword as we do for the `FilterJson#value` _type_.

**Comment by sophokles73** [comment]
> I think I would favour option 2 as the more practical one, as I don't see much benefit implementation-wise to require the pwd-hash to be base64 encoded.

You are talking about bcrypt hashes here, right? Because for other hash functions we *need* the value of the property to be encoded (either Base64 or Base16 or ...) because a plain string cannot hold a byte array otherwise.

**Comment by b-abel** [comment]
How to proceed here? 
@ctron @dejanb Any thoughts from your side?

**Comment by ctron** [comment]
I think it makes sense to:

> 2. Declare the property as a plain String and amend its documentation that the value is expected to be a plain String if hash-function is bcrypt and a Base64 encoded byte array otherwise.

The definition would be: Whatever the hash function requires, encoded into a string.

If that means base64 for sha, then ok. If that means string for bcrypt, fine as well. If a hash type finds a datatype it cannot process -> authentication error.

**Comment by sophokles73** [comment]
Looks like we have a winner :-) I am ok with going for option 2 as well ...

**Comment by b-abel** [comment]
Great. I'll provide a PR for that.
