### ISSUE TITLE
Problem with deploying hono on private K8s cluster

### ISSUE THREAD

**Issue by roullli** [eclipse/hono#2195]
I'm running Hono inside my own cluster built based on RPis.
everything looks like to be fine.
I used helm to install the latest version of Hono.
here is the result for `kubectl get all -n hono`
![image](https://user-images.githubusercontent.com/51787620/93770404-cd344b00-fc24-11ea-9fb6-d995cdaa29f0.png)
It shows everything is fine.
but there is a warning for almost all adapters and servers. here is the output for `kubectl describe pods -n hono`
![image](https://user-images.githubusercontent.com/51787620/93770882-7713d780-fc25-11ea-9413-3a124415db89.png)

I didn't notice this before! and I assumed it is working fine!!

**Comment by sophokles73** [comment]
That only means that the readiness probe did not succeed on a single invocation. It obviously succeeded on subsequent invocations, otherwise the pod wouldn't have become ready. Are you experiencing any issues when using the services?

**Comment by roullli** [comment]
Ok, I thought that there is a serious problem with my cluster!! I'm facing a problem with my application which is using Hono. but since everything is fine with Hono I have to think about what is wrong with the app!
