### ISSUE TITLE
Homepage: Items in 'Who uses Hono' section are hidden

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2197]
The 'Who uses Hono' section on the homepage is currently empty - the items in there seem to be hidden.

**Comment by sophokles73** [comment]
@b-abel would you mind taking a look at this?

**Comment by b-abel** [comment]
Will do.

**Comment by b-abel** [comment]
Blocked by https://github.com/EclipseFdn/iot.eclipse.org/issues/526.

**Comment by b-abel** [comment]
The script breaks regularly. The Eclipse Foundation is working on a new solution. In the meantime, we could just deliver the script ourselves. The only thing is that new adopters would not be added automatically. But this is a pretty rare event.

**Comment by sophokles73** [comment]
@calohmn this seems to be fixed, right?

**Comment by calohmn** [comment]
@sophokles73 Yes, closing it.
