### ISSUE TITLE
Telemetry API : grouping data for IoT gateway

### ISSUE THREAD

**Issue by ppatierno** [eclipse/hono#22]
Just a proposal ...

In a scenario with an IoT gateway in the field which gets data from local devices and then sends them to Hono, it could be useful to provide through the Telemetry API the messages "grouping" feature (with properties like "group-id", "group-sequence" and so on).

Grouping data could be useful to the receiver service for further analysis.

What do you think ?

**Comment by hekonsek** [comment]
Well, you can send any additional metadata as a part of the payload. So if you would like to mark telemetry data with a gateway ID, you can reflect that in your telemetry model. I don't think we should include this as a part of the specification.

Feel free to disagree :) .
