### ISSUE TITLE
Allow colon in default device id pattern

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2201]
From https://github.com/eclipse/hono/issues/1956#issuecomment-696689998:
As it is a common use case to use Hono with Eclipse Ditto, a Hono device identifier should by default also be allowed to contain a colon, since Ditto requires this.

Also the device and tenant identifier pattern should be removed from the device management API definition, as these patterns may be adapted via the device registry config.

**Comment by sophokles73** [comment]
@calohmn are you going to fix this?

**Comment by calohmn** [comment]
@sophokles73 yes
