### ISSUE TITLE
Device Registry Management API accepts credentials without secrets

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#2215]
The Management API currently defines the *secrets* property of the credentials types as optional. However, there is not much use for credentials that do not contain any secrets. FMPOV the property should therefore be mandatory and the secrets array should be required to contain at least one element. Formally, this would constitute a *breaking API change*. However, I wonder if there is a use case that would require adding credentials without secrets and which we want to (continue to) support.
 
The Credentials API already requires the response payload of the *get Credentials* operation to contain a non-empty secrets array, so it should make implementation much easier, if no credentials need to be *invented* by the registry ...

@ctron @dejanb @calohmn WDYT?

**Comment by dejanb** [comment]
@sophokles73 this change sounds reasonable to me

**Comment by sophokles73** [comment]
closed via #2219
