### ISSUE TITLE
Fix information regarding custom properties in Tenant API

### ISSUE THREAD

**Issue by kaniyan** [eclipse/hono#2221]
[Tenant API documentation](https://www.eclipse.org/hono/docs/api/tenant/#tenant-information-format) mentions as below about allowing custom properties.

> The JSON object MAY contain an arbitrary number of additional members with arbitrary names which can be of a scalar or a complex type. This allows for future well-known additions and also allows to add further information which might be relevant to a custom adapter only.

 Also the example in the Tenant API contains some custom properties at both the root level (_customer_) as well as the adapter configuration level (_deployment_).

With PR #2040 from Hono 1.3.0 it is not possible to add any more custom properties using the Tenant Management API as we deem them as unknown properties and reject the request with `400 Bad Request`. IMHO it doesn't make much sense to mention custom properties in READ operation and at the same time not allow them in WRITE operation.

**Comment by sophokles73** [comment]
Well, the Tenant API and the Device Registry Management API are not tied to each other. There is no requirement to use the latter for managing the content of data store that the Tenant API is implemented on top of. I would therefore rather keep the Tenant API as is, even if the protocol adapters (currently) do not make use of any such additional data returned by the *get Tenant* operation.
