### ISSUE TITLE
MQTT refuses connection

### ISSUE THREAD

**Issue by roullli** [eclipse/hono#2238]
Hi,

I'm trying to test the MQTT adapter to see if it is working properly or not! I used this command `mosquitto_pub -u '4711@DEFAULT_TENANT' -P hono-secret -t telemetry -m '{"temp": 5}'` as it was mentioned in the user guide document. It responds me back the connection refused error. 
![image](https://user-images.githubusercontent.com/51787620/95461209-9da07500-097e-11eb-8a05-3f77df97f15a.png)

I used helm to install Hono on my private cluster which has deployed the latest version of Hono(1.4).

**Comment by sophokles73** [comment]
You will need to specify the host and port to connect to as described in the Getting Started guide ...

**Comment by roullli** [comment]
Oh sorry, I didn't read the getting started guide!
I have a question which it was somehow confusing for me while I was reading the documents.
I have a rover and I want to send command and control through the MQTT adapter to control the Rover. I noticed that the rover should subscribe to this 'command/+/+/req/#' topic. but I'm not sure where to publish the command in order to receive to the Rover. 
I have created a tenant named "rover" and to devices with auth_id of 'rover2' and 'rover4'.
Can you help me with the publish and subscribe topic? which I wasn't able to find while I was reading the documents.

**Comment by sophokles73** [comment]
Applications interact with the devices connected to Hono's protocol adapters via Hono's north bound [Telementry, Event and Command & Control APIs](https://www.eclipse.org/hono/docs/api/). These APIs use AMQP 1.0 as the transport protocol, i.e. you need to interact with these service endpoints via AMQP 1.0. The Hono command line client can be used to send commands to devices connected to Hono's protocol adapters. The Getting Started guide describes how to do that in the *Advanced: Sending Commands to a Device* section ...

**Comment by roullli** [comment]
Thanks for your help. I'll go deep through the documentation.
