### ISSUE TITLE
Management API: Search tenants with optional filters, paging and sorting options

### ISSUE THREAD

**Issue by kaniyan** [eclipse/hono#2239]
Device Registry Management API already supports [searching devices](https://www.eclipse.org/hono/docs/api/management/#/devices/searchDevicesForTenant) for a tenant with optional filters, paging and sorting options. 
This is a feature request to have such a search operation also for tenants.

**EDIT:**
Extend _MongoDB device registry_ to support this new feature.

**Comment by sophokles73** [comment]
Sounds like a good idea to complement the existing search Devices operation.

**Comment by andrew-kratik** [comment]
Would be great to extend Management API and allow getting list of tenants. As it will allow business applications to manage tenants better. For example find all tenants that are not linked (by mistake/error) to Ditto tenant and delete/fix this.

**Comment by sophokles73** [comment]
@andrew-kratik Hi Andi, this has been scheduled for Hono 1.6.0 which we hope to release end of Jan 2021 ...

**Comment by andrew-kratik** [comment]
Great
thanks @sophokles73

**Comment by sophokles73** [comment]
@kaniyan what's the status of this?

**Comment by kaniyan** [comment]
@sophokles73 With PR #2383, MongoDB device registry now supports this feature. Currently I am working on the integration tests for this feature.

**Comment by sophokles73** [comment]
@kaniyan any news on this? If you do not intend to implement this feature for the JDBC registry then please split this issue up into two so that we close the one regarding the Mongo DB based implementation. Please also add a note/warning to the JDBC and file based registry, indicating which operations defined by the API are *not* supported by these registries ...

**Comment by kaniyan** [comment]
This has been closed via PRs #2366, #2383 and #2433

**Comment by kaniyan** [comment]
> Would be great to extend Management API and allow getting list of tenants. As it will allow business applications to manage tenants better. For example find all tenants that are not linked (by mistake/error) to Ditto tenant and delete/fix this.

Hi @andrew-kratik, with the recent release of Hono 1.6.0, now the the Device Registry Management API supports retrieving the registered tenants with optional filters, paging and sorting options. The MongoDB based device registry in Hono supports this feature.

**Comment by andrew-kratik** [comment]
Great news, thanks!)
