### ISSUE TITLE
Kura to Hono

### ISSUE THREAD

**Issue by Geonjae-Joo** [eclipse/hono#2246]
I run Kura on rasPi.
I deployed Kubernetes on Local machine, and Hono on kubernetes using helm and minikube.
and I can ping both of them.
![image](https://user-images.githubusercontent.com/62494715/95719235-80371800-0caa-11eb-9311-58aceb387e4a.png)
kura static ip: 10.252.107.238

What I have done is I exposed mqtt adapter deployment and minikube tunnel as depicted below.
![image](https://user-images.githubusercontent.com/62494715/95718666-b922bd00-0ca9-11eb-8a02-ea7b209c8447.png)

minikube tunnel
![image](https://user-images.githubusercontent.com/62494715/95718711-cb046000-0ca9-11eb-836c-61b30da265f9.png)

how should I deal with the Broker-url in MqttData Transport?
![image](https://user-images.githubusercontent.com/62494715/95718892-0868ed80-0caa-11eb-8873-e8c9efab8554.png)

Please help me out!!

**Comment by sophokles73** [comment]
which version of Kura are you using?

**Comment by Geonjae-Joo** [comment]
@sophokles73 
I'm using 4.1.1.

![image](https://user-images.githubusercontent.com/62494715/95733377-05c3c380-0cbd-11eb-83bd-391d1a732a7d.png)

**Comment by sophokles73** [comment]
Then I guess you should be able to follow the instructions provided by the [Kura Documentation](http://eclipse.github.io/kura/cloud-stacks/kura-hono.html)

**Comment by Geonjae-Joo** [comment]
I solved it , I leave how I worked it out in case anyone gets the same issue.

I needed to port-forward my service of adapters
![image](https://user-images.githubusercontent.com/62494715/96067407-a6400080-0ed4-11eb-8b98-355405c3be44.png)

then it's connected
![image](https://user-images.githubusercontent.com/62494715/96067463-c4a5fc00-0ed4-11eb-8918-15be69972f7f.png)

**Comment by sophokles73** [comment]
@Geonjae-Joo Great! Thanks for following up :+1:
