### ISSUE TITLE
Specify the content-type of a telemetry/event message via MQTT property bag

### ISSUE THREAD

**Issue by thjaeckle** [eclipse/hono#2258]
I recently learned that Hono supports MQTT property bags in order to specify e.g. the `hono-ttl` for a published event, see:
https://www.eclipse.org/hono/docs/user-guide/mqtt-adapter/#publishing-events

I really like that approach and would like to suggest/discuss whether it would be possible to also specify the `content-type` of a published telemetry / event message with that mechanism.

As the Hono HTTP adapter already passes through the set HTTP header "Content-Type" for published telemetry/event, this would be symmetrical to the HTTP adapter.

## Background/Scenario

In Eclipse Ditto we define a vendor specific content-type `"application/vnd.eclipse.ditto+json"` declaring that a payload is in [Ditto Protocol JSON](https://www.eclipse.org/ditto/protocol-specification.html). 

A device may now:
1. send arbitrary payload (with e.g. `application/json` content-type) which should be routed to some HTTP WebHook to which Ditto opened a connection (e.g. a data ingestion tool which shall receive all "raw data" emitted from a device)
2. but from time to time decide to update the twin of the device in Ditto - and may explicitly do so by sending a Ditto Protocol message with content-type `application/vnd.eclipse.ditto+json`

So it would be helpful in such scenarios that the device publishes:
1. the raw data message to topic `telemetry`
2. the Ditto Protocol message to topic `telemetry/?content-type=application/vnd.eclipse.ditto%2Bjson` (the `+` needs to be URL encoded as `+` is a reserved character for MQTT topics)

What do you think?
The same could be of course also be supported for other protocol adapters.

**Comment by sophokles73** [comment]
sounds good to me :+1:

**Comment by kaniyan** [comment]
This has been closed via PR #2263 and this feature is scheduled for 1.5.0 release.
