### ISSUE TITLE
Do "adapter enabled for tenant" check before credentials validation

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2260]
Followup of #2115:
Currently, a connection attempt from a device means that the target protocol adapter does some tenant related checks only *after* the credentials given by the device have been validated.

As the credentials validation may be quite expensive, it would be better to do the tenant related checks *before* that already, as soon as tenant information has been obtained from the credentials.

The tenant related checks are:
- check whether  the adapter is enabled for the tenant,
- check whether the connection limit for the tenant is not exceeded,
- check whether the message limit for the tenant is not exceeded by the request payload (HTTP/CoAP adapter).

EDIT: only the check whether the adapter is enabled for the tenant is to be done here - see below.

**Comment by calohmn** [comment]
PRs for the HTTP and MQTT adapter have been created. 
The changes there only cause a minor change of behaviour towards an HTTP device: A connection attempt with wrong credentials and with one of the above checks failing, will now result in an error outcome pointing to the failed check (e.g. "403 (Forbidden)" for the HTTP adapter not being enabled for the tenant), not pointing to the wrong credentials ("401 (Unauthorized)"). This doesn't break the behaviour outlined in the HTTP adapter documentation FMPOV, as there is no order of precedence defined for the different possible error scenarios.

For the AMQP adapter, however, letting the checks be done as part of the credentials validation would result in a more noticeable change of behaviour towards the AMQP device:
Exceeding the tenant connection limit for example would then be met with a SASL handshake error (probably SASL_PERM). The current behaviour on the other hand means that the SASL handshake succeeds (provided credentials are correct) and then the connection is getting closed with an "UNAUTHORIZED_ACCESS" error condition (and possibly an error string, but that isn't used as of now).
I still think it would be good to make that change also for the AMQP adapter, adding an explicit note in the AMQP adapter guide about the possible SASL handshake error reasons.

**Comment by sophokles73** [comment]
> I still think it would be good to make that change also for the AMQP adapter, adding an explicit note in the AMQP adapter guide about the possible SASL handshake error reasons.

That is the behavior that we had in previous version of Hono already. We deliberately chose to change that and do the capacity check etc *after* the SASL handshake because AMQP does not provide means to convey an error message to the client as part of a (failed) SASL handshake. So FMPOV we should keep the AMQP adapter as-is ...

**Comment by calohmn** [comment]
Ok, I see. I'll skip changes to the AMQP adapter here then.

**Comment by kaniyan** [comment]
We could perform the adapter enabled check before the credentials validation but IMHO I am not sure if it is better to perform connection limit checks before the validation of the credentials. Connection limit checks include validation of connection, connection duration and message limits. These checks involve querying data from the Prometheus and those results are cached. Let us assume cases such as falsely configured devices or someone tries to attack the system with false credentials. FMPOV this puts extra load on the system and it could worsen the throughput time of processing messages in the system. WDYT?

**Comment by sophokles73** [comment]
Yes, we could at least do the tenant enabled check before verifying credentials. The other checks should IMHO be done after successful verification of credentials for the reason pointed out above ...

**Comment by calohmn** [comment]
Good point, yes, even though Prometheus data is cached, there would still be quite many superfluous Prometheus requests for repeated connection attempts with wrong credentials.
I'll create a new PR with just the tenant-enabled check.
