### ISSUE TITLE
building from source: Error on running integration tests - certificate expired

### ISSUE THREAD

**Issue by marcel-bluestone** [eclipse/hono#2274]
Hello, 
after I followed the steps for building from source, the build worked without errors.
Running the integration tests however creates a lot of errors, causing everything to shut down.

It seems that the certificate has expired, but that may not be the whole problem. 
The log is attached, I hope someone can help here.

Thanks
[mvn_test.log](https://github.com/eclipse/hono/files/5458193/mvn_test.log)

**Comment by sophokles73** [comment]
Which branch are you trying to build?

**Comment by marcel-bluestone** [comment]
I downloaded the sources from here https://github.com/eclipse/hono/archive/1.4.0.tar.gz

**Comment by sophokles73** [comment]
Indeed, the example certs included in the source code at that tag have expired. You can recreate them before doing the build by running the `demo-certs/create_certs.sh` script. Note that this needs to be done once only, i.e. it is not necessary to do this before each build.

**Comment by marcel-bluestone** [comment]
That did the trick. Thanks a lot!
