### ISSUE TITLE
[#8] Authentication and authorisation of Kafka clients used in Hono

### ISSUE THREAD

**Issue by kaniyan** [eclipse/hono#2282]
There is already an issue #8, which talks about using Kafka as an alternative to the AMQP 1.0 messaging infrastructure. In that issue, we see discussion regarding how Kafka clients can be used in Hono protocol adapters to send _telemetry_ and _event_ data. I opened this issue to discuss about how those Kafka clients can be configured to communicate securely i.e the clients are authenticated and authorised by the Kafka server-side. This issue is scoped only to the client side and it doesn't elaborate on how to configure the server side.

**Authentication of Kafka clients:**

Kafka clients used in protocol adapters can authenticate with the Kafka cluster using SASL or SSL mechanisms. The producer/consumer Kafka clients should present the necessary authentication properties to the Kafka server side so that they can be authenticated and authorised. Below is a sample configuration of a client that uses SASL_PLAINTEXT mechanism to authenticate with the sever. In Hono, these authentication properties can be given as part of the producer or consumer configuration (in adapter's `application.yml`)  as in the below example. I don't think any extra abstraction or pre-processing is needed in Hono for that. 

![image](https://user-images.githubusercontent.com/18659982/98097687-a442df00-1e8d-11eb-9a6c-396113403eee.png)

**Authorisation of Kafka clients:**

Kafka offers authorisation support using  ACL (Access Control List). Once a client is successfully authenticated, the Kafka broker goes through the access control list it has and finds out the privileges of that client i.e if the client is authorised to read from or write to the given topics. ACLs are defined in the general format of `Principal P is [Allowed/Denied] Operation O From Host H on any Resource R matching ResourcePattern RP`. The authentication properties mentioned in the previous part are sufficient for a client to be authorised and no extra configuration are needed in the client side. 

**Out of the box Hono setup in IoT packages:**

In the out of the box setup in IoT packages, the AMQP clients in protocol adapters uses SASL authentication over SSL channel  to connect to the AMQP1.0 network. We can also use the same authentication mechanism for the Kafka messaging infrastructure as in the below image. The Kafka listeners should be configured to turn on the SSL communication and the Kafka server side should be configured for the below users with appropriate ACLs. We can also continue to have the north bound user _consumer@HONO_ with its privileges to read all topics irrespective of the tenant.

![Kafka-auth-sasl_ssl](https://user-images.githubusercontent.com/18659982/98124330-55a83b80-1eb3-11eb-8b9f-d4ef3715a41f.jpg)

Below is an example, which shows how the Kafka producer client used by an HTTP adapter can be configured to authenticate using SASL over secured SSL communication.
```
kafka:
     producerConfig:
	  bootstrap.servers: my-cluster-kafka-bootstrap.kafka:9093
	  security.protocol: SASL_SSL
	  ssl.truststore.location: "/etc/hono/trusted-certs.pem"
	  ssl.truststore.type: PEM
	  sasl.mechanism: SCRAM-SHA-512
	  sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="http-adapter@HONO" password="http-secret";
```

**Comment by sophokles73** [comment]
Thanks for starting this discussion, @kaniyan 
I agree that there shouldn't be an issue using whatever authentication mechanism Kafka supports on the adapter side as this will be completely abstracted away by the Kafka Java client anyway, right? I think the more pressing questions will be:
* How does the Kafka broker validate the client's credentials and can Kafka be integrated with a separate service for doing so, e.g. Hono's AuthServer? 
* How do we need to configure the ACLs and can they be altered dynamically during runtime?

**Comment by kaniyan** [comment]
## Authentication:

> How does the Kafka broker validate the client's credentials and can Kafka be integrated with a separate service for doing so, e.g. Hono's AuthServer?

Kafka server offers various authentication mechanisms as below.
- SASL/GSSAPI (Kerberos) - starting at version 0.9.0.0
- SASL/PLAIN - starting at version 0.10.0.0
- SASL/SCRAM-SHA-256 and SASL/SCRAM-SHA-512 - starting at version 0.10.2.0
- SASL/OAUTHBEARER - starting at version 2.0

I focused only on the below two mechanisms as they are closer to the setup what we have right now in Hono.

**SASL/PLAIN:**
In case of SASL/PLAIN mechanism, the users with their passwords are stored as plain text in a JAAS configuration file in the below example and that JAAS config file location is given as JVM property to each broker.
```
        KafkaServer {
            org.apache.kafka.common.security.plain.PlainLoginModule required
            username="admin"
            password="admin-secret"
	   user_http-adapter@Hono="http-secret";
        };
```
**SASL/SCRAM:**
The default SASL/SCRAM implementation in Kafka uses Zookeeper as the credential store. Credentials are created in zookeeper using a command line tool `kafka-configs.sh`. Below is an example on how to create SCRAM credentials for user `http-adapter@Hono` with password `http-secret`:
```
bin/kafka-configs.sh --zookeeper localhost:2182  --alter --add-config 'SCRAM-SHA-256=[password=http-secret],SCRAM-SHA-512=[password=http-secret]' --entity-type users --entity-name http-adapter@Hono
```
The Kafaka version 2.7.0, which is planned for Nov 2020, offers support to create, describe, and alter SCRAM user configurations via the `KafkaAdminClient`. Vertx also offers an implementation of this API (https://vertx.io/docs/apidocs/io/vertx/kafka/admin/KafkaAdminClient.html).

> can Kafka be integrated with a separate service for doing so, e.g. Hono's AuthServer?

**Configurable SASL callback handlers:**
Kafka supports configurable callback handlers for SASL/PLAIN and SASL/SCRAM through which the default credential providers can be replaced or any external service can be used. SASL/PLAIN authentication in Kafka is based on the hard-coded JAAS configuration. SASL/PLAIN call backs enable password authentication using an external authentication server without requiring Kafka to know the actual passwords. The callback verifies if the provided credentials during SASL/PLAIN exchange is valid.

SASL/SCRAM uses Zookeeper as the password store. In order to not to use Zookeper as the default password store, SASL/SCRAM callbacks can be used. In this case, it requires the salted credentials to perform the authentications and hence the SCRAM credentials for the given user should be returned. 

## Authorization:

> How do we need to configure the ACLs and can they be altered dynamically during runtime?

Apacke Kafka uses a pluggable Authorizer to authorize operations. The default out-of-the-box Authorizer implementation is `AclAuthorizer` that uses Apache Zookeeper to store all the ACLs. Apache Kafka by default offers two ways to manage ACLs dynamically during runtime.
1. A [command line admin tool](https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Authorization+Command+Line+Interface) to manage ACLs.
  		    Example: Add ACL for user `http-adapter@Hono` as a *producer* with permissions to write, list and create topics with pattern "event-*"
```
$ bin/kafka-acls.sh --authorizer-properties zookeeper.connect=localhost:2181 --add --allow-principal User:http-adapter@Hono --producer --topic "event-*"
```
2. Admin client API. The admin client API can be used to create, delete and describe ACLs. Vertx also offers an implementation of this API (https://vertx.io/docs/apidocs/io/vertx/kafka/admin/KafkaAdminClient.html).

**Custom Authorizers:**
Kafka offers flexibility to implement custom authorizers to suit any particular needs. If someone prefers not to use Zookeeper to manage ACLs, then they can implement his/her own custom authorizer. Here is an [example](https://cwiki.apache.org/confluence/display/SENTRY/Apache+Kafka+Authorization+with+Apache+Sentry) on how the authorization can be managed using a custom authorizer provided by Apache Sentry. [Apache Sentry](https://sentry.apache.org/) is a system for enforcing fine grained role based authorization. 


## Possibilities for the Hono setup in IoT packages:

**Simple setup:**
Currently Hono uses file-based auth server to authenticate with the AMQP 1.0 network. The credentials are configured in `example-permissions.json` and AFAIK no users can be added or deleted on the fly. We can also in a similar manner store the credentials in a JAAS config file to support SASL/PLAIN and use that file to configure the brokers. For authorization, the ACLs for those users (adapters and north bound) can be added using helm post install jobs. The disadvantage of this approach is that the users cannot be added/deleted on the fly. As I understood, this can be solved if we use SASL/SCRAM. Initially we can create SCRAM users using post install jobs. Further any users can be added/deleted dynamically using `kafka-configs.sh`. For the Hono setup we have in IoT packages, IMHO this approach should be suffice.

**Custom authentication and authorization service:**
If we prefer not to use Zookeeper to store ACLs, it should be possible to implement a custom Authorizer and custom SASL/PLAIN call back handler to delegate authorization and authentication of the users to an external service. In this case, I can image a service similar to the auth server that we have now and it should take care of the authentication and authorization of the Kafka clients. Then the Kafka servers should be configured to use these custom implementation.

Note:
There are many Kafka operators in the market and they also provide some level of abstraction on how to manage the users and ACLs. For example, Strimzi Kafka operator is being used in the PR #2216 and it enables user management through custom Kubernetes resources namely `KafkaUser`.

**Comment by sophokles73** [comment]
So, my understanding is that kafka can be integrated with Hono in these ways if we have control over the kafka installation/configuration. This, however would probably not work with a managed kafka service offered by third parties, right?

**Comment by kaniyan** [comment]
> So, my understanding is that kafka can be integrated with Hono in these ways if we have control over the kafka installation/configuration. This, however would probably not work with a managed kafka service offered by third parties, right?

I checked few prominent managed services and they support _AdminClient_ and CLI scripts such as `bin/kafka-acls.sh`. But we can't expect all the managed Kafka services to support the above ways. Also some managed services provide additional CLI tools and APIs to provision users and to manage security setup.

**Comment by sophokles73** [comment]
@kaniyan is there anything to be done here?

**Comment by kaniyan** [comment]
> @kaniyan is there anything to be done here?

Nothing more to be done on this issue. I will close this issue.
