### ISSUE TITLE
MQTT Adaptor wrongly prefixes topic to payload if received with TLS

### ISSUE THREAD

**Issue by akofoed** [eclipse/hono#2283]
HONO Adaptor Version: 1.4

**Goal**
To receive the JSON string on AMQP exactly as it was sent. I am using the gateway functionality in HONO meaning that the mqtt-connected-device (gateway) is sending on behalf on another device.

**Problem:**
When sending a simple JSON string to the MQTT adaptor unencrypted (port 1883) it is received by the CLI client correctly. However, if sent encrypted to port to 8883 it is received with some binary stuff and the topic prefixed to the payload!

**How to reproduce:**
Using HONO v1.4
1. Start the CLI client:

        java -jar hono-cli-*-exec.jar --hono.client.host=localhost --hono.client.port=5672 --hono.client.username=consumer@HONO --hono.client.password=verysecret --spring.profiles.active=receiver --tenant.id=tenant1

2. Send a sample JSON to the MQTT adaptor on port 1833 (unencrypted)

        mosquitto_pub -h localhost -t "telemetry/tenant1/6387069b-e5c7-49f7-b92a-dc324281ae2d" -u gw01@tenant1 -P gw01pwd -m '{"temp":8}'

3. Watch the CLI client for the following output:

        22:37:00.361 [vert.x-eventloop-thread-0] INFO  org.eclipse.hono.cli.app.Receiver - received telemetry message [device: 6387069b-e5c7-49f7-b92a-dc324281ae2d, content-type: application/octet-stream]: {"temp":8}
        22:37:00.362 [vert.x-eventloop-thread-0] INFO  org.eclipse.hono.cli.app.Receiver - ... with application properties: {deviceType=com.tenant1.test:ed1:1.0.0, orig_adapter=hono-mqtt, device_id=6387069b-e5c7-49f7-b92a-dc324281ae2d, qos=0, namespace=com.tenant1.test, attributes={
          "location": "Kitchen"
        }, orig_address=telemetry/tenant1/6387069b-e5c7-49f7-b92a-dc324281ae2d, JMS_AMQP_CONTENT_TYPE=application/octet-stream}

Output is correctly **{"temp":8}**

4. Send a sample JSON to the MQTT adaptor on port 8833 (encrypted)

        mosquitto_pub -h localhost -p 8883 --cafile ~/hono/demo-certs/certs/trusted-certs.pem -t "telemetry/tenant1/6387069b-e5c7-49f7-b92a-dc324281ae2d" -u gw01@tenant1 -P gw01pwd -m '{"temp":8}'

5. Watch the CLI client for the following output:

        22:37:53.482 [vert.x-eventloop-thread-0] INFO  org.eclipse.hono.cli.app.Receiver - received telemetry message [device: 6387069b-e5c7-49f7-b92a-dc324281ae2d, content-type: application/octet-stream]: 0B6telemetry/tenant1/6387069b-e5c7-49f7-b92a-dc324281ae2d{"temp":8}
        22:37:53.482 [vert.x-eventloop-thread-0] INFO  org.eclipse.hono.cli.app.Receiver - ... with application properties: {deviceType=com.tenant1.test:ed1:1.0.0, orig_adapter=hono-mqtt, device_id=6387069b-e5c7-49f7-b92a-dc324281ae2d, qos=0, namespace=com.tenant1.test, attributes={
          "location": "Kitchen"
        }, orig_address=telemetry/tenant1/6387069b-e5c7-49f7-b92a-dc324281ae2d, JMS_AMQP_CONTENT_TYPE=application/octet-stream}

Output is not as expected; It has been prefixed:
**0B6telemetry/tenant1/6387069b-e5c7-49f7-b92a-dc324281ae2d{"temp":8}**

---
I have tested this using the [Java Client Consumer](https://www.eclipse.org/hono/docs/dev-guide/java_client_consumer/) as well and the same thing happens. Output is prefixed when sent to port 8883.

Let me know if I can help, and thanks for your efforts and for building this great product.

**Comment by sophokles73** [comment]
@akofoed I can confirm this behavior using the sandbox installation (which is running 1.4.0) as well.
I will take a look at it.

**Comment by sophokles73** [comment]
The 1.4.0 release runs on vert.x 3.9.2 and exposes the problematic behavior. When running the 1.4.0 code on vert.x 3.9.3 the problem seems to be gone. I have no clue, though, what the underlying problem might be.

@akofoed You can build your own images from the 1.4.0 source code as described [here](https://www.eclipse.org/hono/docs/dev-guide/building_hono/). Before running the build, you should run the `demo-certs/create_certs.sh` script to create new demo certificates (the ones in the repo have expired). When running the build, set the *vertx.version* property to value `3.9.3`. That should produce working images:
```sh
mvn clean install -Pbuild-docker-image,metrics-prometheus -Dvertx.version=3.9.3
```

However, you may also wait for the upcoming Hono 1.4.1 service relases which will also contain vert.x 3.9.3 ...

**Comment by akofoed** [comment]
Thanks Kai :)
