### ISSUE TITLE
Inspecting Hono Adapter Metrics using Prometheus/Grafana

### ISSUE THREAD

**Issue by ArashJavan** [eclipse/hono#2291]
I followed the "Getting Started" and installed hono using "helm" in my local minikube instance. 
Everything is running well, I can send and receive messages through hono (mqtt, http, amqp).
Now I would like to inspect these messages via grafana. Both prometheus and grafana are running.

I can also access the grafana dashboard. But how can I inspcet the telemtry data sent from a device to MQTT and HTTP inside grafana?
Should I chnage something in the default prometheus config, comming with hono?

Thanks for any suggestion!

**Comment by sophokles73** [comment]
Not sure what you mean by *inspect the telemetry data*. Hono itself is payload agnostic and has no clue about the semantics of any data being contained in messages. We therefore only report metrics regarding the meta data of messages like message type, protocol adapter, QoS etc.

Based on that, if your devices send data in a particular format, then I am afraid that you will need to process the payload in a consumer yourself. You can then parse the payload according to the expected semantics and put the data into a Prometheus server or any other time series DB. You can then create dashboards in Grafana based on these time series.

**Comment by ArashJavan** [comment]
@sophokles73 Thanks a lot your reply. That is exactly what I wanted to know. So I need to create my own adapter to register on a device and publish teh data to a prometheus server.

**Comment by sophokles73** [comment]
You need to create a consumer for Hono's north bound [Telemetry API](https://www.eclipse.org/hono/docs/api/telemetry/). Such a consumer is scoped to a *tenant*, i.e. it will receive telemetry data for *all* devices that belong to the tenant.

**Comment by ArashJavan** [comment]
@sophokles73 thanks for clarification :)
