### ISSUE TITLE
Putting MQTT client identifier in credentials API 'get' operation

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2292]
In the [MQTT adapter user guide "Authentication" chapter](https://www.eclipse.org/hono/docs/user-guide/mqtt-adapter/#authentication) it is stated that the MQTT client identifier is put as client-id in the Credentials API *get* request payload.

Looking at the implementation, this is only true for the client certificate authentication, not for username/password authentication.

Should this feature be added to the username/password authentication? This would mean less credentials request caching if the MQTT client uses a different client id for each connection..

Or should it be removed from the certificate authentication implementation and the MQTT adapter documentation in general? Such a feature only exists for the MQTT adapter and a special device registry implementation would be needed to make use of this.

**Comment by sophokles73** [comment]
We defined this behavior of the MQTT adapter in order to provide for better integration with Eclipse Kapua, which uses this information to determine the device ID. SO FMPOV this needs to be fixed to also include the clientID in the username/password case ...

**Comment by calohmn** [comment]
@sophokles73 Do you think the fix should also go in 1.4.x?
(Would be a bit more effort than a cherry-pick because of other changes in relevant classes.)

**Comment by sophokles73** [comment]
Looks like nobody is using this feature anyway so far. So IMHO we can omit the fix from 1.4.x and 1.3.x
