### ISSUE TITLE
Move Hono Load Tests module (JMeter plugin) to Hono Extras repository

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2306]
The hono-jmeter maven module with its contained JMeter plugin hasn't been updated much for quite a while, so it is relatively independent from the other Hono codebase. I think it doesn't necessarily need to be in the Hono repository and could instead be moved to the Hono Extras repository.

This would also greatly reduce the number of transitive dependencies reported when checking Hono dependency licenses.

**Comment by sophokles73** [comment]
great idea

**Comment by calohmn** [comment]
Superseded by #2314 (removing the module altogether).
