### ISSUE TITLE
Hono Github home page doesn't show the correct latest release

### ISSUE THREAD

**Issue by kaniyan** [eclipse/hono#2316]
Hono Github home page shows the latest release as 1.0.1 as in the attached screenshot, which is incorrect. As of now, the latest release is 1.4.3. 

![Hono_latest_releases_not_correct](https://user-images.githubusercontent.com/18659982/99946976-8c1cfc00-2d77-11eb-9496-abe7717d1685.png)

**Comment by sophokles73** [comment]
I have created *releases* for the 1.6.x and 1.7.x tags
