### ISSUE TITLE
Add documentation for the JDBC based device registry

### ISSUE THREAD

**Issue by kaniyan** [eclipse/hono#2325]
Add _User Guide_ for the JDBC based device registry. Also update the required pages such as _Device Identity_, _Secure Communication_, _Device Registries_, and _Device Registry Configurations_ .

**Comment by sophokles73** [comment]
we already have an Admi Guide for the JDBC registry

**Comment by kaniyan** [comment]
> we already have an Admin Guide for the JDBC registry

Thanks for the info. I will update the above description.

**Comment by sophokles73** [comment]
closed via 4be9fb260440b34051ad6e2c1762a8ab7021909d
