### ISSUE TITLE
Multiple AMQP consumers

### ISSUE THREAD

**Issue by ArashJavan** [eclipse/hono#2329]
Hello,

currently I have two applications, which are connected to the AMQP-Network (northbound) of Hono and register on "telemetry" endpoint to receive the data sent by the edge-devices. But what I see is that each application get only a part of the telemtry data.
 
From this [post](https://stackoverflow.com/questions/10620976/rabbitmq-amqp-single-queue-multiple-consumers-for-same-message) and the [RabbitMQ tutorials](https://www.rabbitmq.com/getstarted.html) I know that you can configure RabbitMQ for mutiple consumers for the same message. 

But is it also possible in the case of hono or more precisely its AMQP 1.0 Messaging Network? Is it even a good idea to let hono send telemetry data to multipe consumers?

Thanks!

**Comment by sophokles73** [comment]
> But is it also possible in the case of hono or more precisely its AMQP 1.0 Messaging Network?

Yes, this is possible. You will need to configure the *telemetry* address' `distribution` property in the [Qpid Dispatch Router's config file](http://qpid.apache.org/releases/qpid-dispatch-1.13.0/man/qdrouterd.conf.html) accordingly. In the [Hono Helm chart](https://github.com/eclipse/packages/blob/master/charts/hono/config/router/qdrouterd.json), it is configured as `balanced` by default. But it can also be set to `multicast` which will let the router send the messages to all consumers. The same applies to the *event* address ...

> Is it even a good idea to let hono send telemetry data to multipe consumers?

That depends on your use case. If you have multiple applications that need to process all telemetry messages, then I guess configuring Hono accordingly makes sense. You could, of course also put some more sophisticated message routing based on Apache Camel in front of your applications. This would have the advantage that you can better control which application gets which messages e.g. based on content-type or even payload properties.

**Comment by ArashJavan** [comment]
@sophokles73 again thank you for your support :) 
I will try your suggestions.

**Comment by sophokles73** [comment]
@ArashJavan glad to help :-) Let us know about the outcome of your experiments so that others can profit from it as well.
BTW this will be much easier for others if you post questions regarding Hono on stackoverflow in the future instead (see https://www.eclipse.org/hono/community/get-in-touch/) ...

**Comment by ArashJavan** [comment]
@sophokles73 surely, I will share the results here and will use Stackoverflow for the future. Thanks for the hint.
