### ISSUE TITLE
AMQP adapter: Message properties aren't adopted in downstream message anymore

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2341]
The AMQP adapter documentation states that "Arbitrary properties (content-type, correlation-id, …)" can be set on Telemetry/Event messages, implying that these will be adopted in the downstream message.

With the 1.5 changes, such properties (apart from the content type) of the device AMQP message are not taken into account anymore.

That also breaks the contract of the AMQP adapter client interfaces:
https://github.com/eclipse/hono/blob/e07eb4752c9e2d8d45fe380bc999f7ce3e734060/client/src/main/java/org/eclipse/hono/client/device/amqp/TelemetrySender.java#L39

I think this should be fixed by adopting the AMQP message *application-properties*.
About the `correlation-id` AMQP message *property* I'm not so sure. On the one hand it's currently documented to be adopted, on the other hand it's rather an internal, protocol-specific property to maybe better not be taken into account.

(relates to #2338)

**Comment by sophokles73** [comment]
FMPOV the AMQP adapter user guide currently does not explicitly state that all properties and application-properties of a message uploaded by a client are copied to the message being forwarded downstream. However, the guide currently is quite unspecific about which properties are actually required or optional.
