### ISSUE TITLE
Error while running docker image

### ISSUE THREAD

**Issue by ansfarooqq** [eclipse/hono#2348]
Hi,
I am new IoT projects and trying to run eclipse/hono docker images. I am able to pull docker images from docker hub but when I try to run that image I am facing some errors given below. Could you please help me in it whether i need to pass some additional  parameters or dependencies while running these images 
![docker run error](https://user-images.githubusercontent.com/75621738/101357334-966fe780-3899-11eb-8340-5fccabf90719.png)
?

**Comment by sophokles73** [comment]
@ansfarooqq You should follow the [Getting started guide](https://www.eclipse.org/hono/getting-started/) to get yourself acquainted with Hono at first.

**Comment by ansfarooqq** [comment]
@sophokles73 Thanks a lot for your prompt response. I have followed the "getting started guide" and have successfully understood the concept of adding devices/gateways and sending data to the application and so on using Hono sandbox. Now i wish to implement the same using docker images but I am not able to find proper documentation on that, So I am finding it bit difficult to run the docker images. Is there any documentation to run docker images for hono ?

**Comment by sophokles73** [comment]
Please refer to https://www.eclipse.org/hono/docs/deployment/helm-based-deployment/

**Comment by sophokles73** [comment]
@ansfarooqq can this be closed?
