### ISSUE TITLE
Issue with deploying Hono locally

### ISSUE THREAD

**Issue by 82siha1mpg** [eclipse/hono#2368]
Hi,

I am trying to build Hono from the source and deploy it locally. I am running it on Windows 10 using docker. I have successfully build all packages of Hono. 
Now, I am trying to deploy Sandbox locally and while doing that I have been facing few issues:
1. I am not able to create key and certificates which are described in "create_sandbox_cert_secrets.sh" shell scripts. So **I am not able to create "hono.eclipse.org-key.pem" and "hono.eclipse.org-cert.pem".**
2. Secondly, I am trying to run sandbox_deploy.sh shell script commands in  docker, **without** the secret "hono.eclipse.org-key.pem" and "hono.eclipse.org-cert.pem".
I am **able to run few services like grafana, hono-artemis,  hono-dispatch-router, and prometheus-operated**; but apart from these services, **for all other services I am getting the error "could not accessed on a registry to record its digest"**

![image](https://user-images.githubusercontent.com/55166365/101903107-0b059780-3bb4-11eb-8346-13a02a2c7ab8.png)

Could you please help me in deploying Hono sandbox on localhost (OS- Windows 10)?
Thanks in advance,

**Comment by sophokles73** [comment]
We do not support deployment of the sandbox to a plain Docker environment. Hono is supposed to be deployed to a kubernetes cluster using the Helm chart that we maintain in the Eclipse IoT Packages project. Please follow the instructions provided in [Hono's Deployment Guide](https://www.eclipse.org/hono/docs/deployment/helm-based-deployment/).
