### ISSUE TITLE
Device credential actions 'add' and 'update': No details when declining invalid payload (status 400 only)

### ISSUE THREAD

**Issue by jnbsi** [eclipse/hono#2370]
On calling the 'add or 'update' action for managing device credentials via Vert.x event bus and using invalid date-time values the request is rejected (status 400) but no further details are given.
The API expects the date-time values to conform to a specific format. (I.e. it's not possible to send a date only (w/o time) or to omit the time zone.) Due to the fact that only a status code 400 is returned without further details about the reason it's not easy to identify the cause of the rejection of the request.
The issue occurs on sending event bus messages to address `org.eclipse.hono.util.CredentialsConstants.EVENT_BUS_ADDRESS_CREDENTIALS_IN`.

**Comment by sophokles73** [comment]
I am not sure which component/class you are referring to. Hono's device registry implementations have been changed to no longer receive request messages via the vert.x Event Bus quite some time ago. However, if I understand correctly, we are talking about the response to an HTTP request to update credentials as defined in the Device Registry Management API, right?

**Comment by sophokles73** [comment]
@jnbsi can this be closed?

**Comment by jnbsi** [comment]
@sophokles73 Yes, the topic seems to be obsolete. Hence, the ticket can be closed.
