### ISSUE TITLE
Transport protocol agnostic interface for northbound Hono-Client

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#2392]
To use [Kafka for messaging](https://github.com/eclipse/hono/issues/8), we need a northbound client interface that does not depend on AMQP specific types, analogous to the changes in  #2156.

**Comment by b-abel** [comment]
I would like to use the consumer from #2420 for the implementation of the Kafka-based northbound client. This is very little code then for telemetry and events.

**Comment by b-abel** [comment]
PR #2432 offers a Kafka-based implementation of the protocol-agnostic northbound interfaces.

**Comment by b-abel** [comment]
@sophokles73 What about the AMQP-based implementation? Strangling the _hono-cllient_ module is FMPOV best left with you. 
FMPOV, resolving the old "client" module best left in your hands. However, I could provide (as an intermediate step) an implementation that "wraps" the `org.eclipse.hono.client.application.ApplicationClientFactory` and provides it with the new interface `org.eclipse.hono.client.application.ApplicationClientFactory`. Does that make sense?

**Comment by sophokles73** [comment]
@b-abel yes, you can leave the Proton based implementation to me.

**Comment by sophokles73** [comment]
@b-abel @kaniyan Anything left to do here or can this be closed (and be added to 1.7.0)?

**Comment by kaniyan** [comment]
FMPOV this can be closed. We have a separate issue #2478 for C&C.
