### ISSUE TITLE
Make messaging network in use configurable on tenant level

### ISSUE THREAD

**Issue by mhemmeter** [eclipse/hono#2402]
Eclipse Hono 1.6.0 introduces support for Apache Kafka as the messaging network for downstream communication (device-to-cloud communication). In a managed service offering customers should be able to decide which messaging network they want to use (Apache Kafka or AMQP 1.0). Therefore it would be great to make the messaging network configurable on a tenant level. 

I don't see the need to distinguish between Telemetry, Events and C&C. An either or configuration (Apache Kafka or AMQQP 1.0) for the tenant is sufficient.

**Comment by sophokles73** [comment]
@b-abel is this something for you?

**Comment by b-abel** [comment]
> @b-abel is this something for you?

Yes. Please assign to me.

**Comment by b-abel** [comment]
The first idea would be:
1. adding a flag to the tenant configuration that indicates if Kafka should be used for that tenant
2. the protocol adapters start the support for AMQP- _and_ Kafka-based messaging on startup if configurations for both networks are present
3. when a protocol adapter receives a downstream message, it decides  which messaging to use based on the flag (1.)
4. once we have support for C&C with Kafka, it should be not too hard to find a similar solution there

**Comment by mhemmeter** [comment]
Sounds very good to me!

**Comment by sophokles73** [comment]
@b-abel @fkaltner @calohmn Anything else that needs to be done here?

**Comment by b-abel** [comment]
FMPOV this can be closed.

**Comment by calohmn** [comment]
I also think this is done.

**Comment by fkaltner** [comment]
Looks good to me!
