### ISSUE TITLE
Device registry should use dedicated event type for indicating provisioning of a device

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#2408]
The device registry currently uses the well-known *empty notification* in order to indicate the (implicit) provisioning of a device. However, the purpose of the *empty notification* has been defined differently and consumers of the event now need to determine the real purpose of the event by interpreting the presence/absence of particular properties instead of simply inspecting the event's content-type as originally intended.

**Comment by fkaltner** [comment]
Reminder: we have to coordinate these changes with the Ditto team, since Ditto uses the current event definition.

**Comment by sophokles73** [comment]
We could keep backward compatibility until Ditto has been updated: always sending the (new) dedicated event but also sending the the (obsolete) Empty Notification if enabled by a config flag ...

**Comment by fkaltner** [comment]
That's what I had in mind too. Can you assign this issue to me?

**Comment by fkaltner** [comment]
I just had a chat with @thjaeckle: Ditto just relies on the AMQP application property _hono_registration_status_ and does not evaluate the content type.

Hence, if keep the application property, we won't need a config flag as far as I can see. @sophokles73 WDYT?

**Comment by sophokles73** [comment]
Meaning that we can use the dedicated content-type instead of the empty notification's?

**Comment by fkaltner** [comment]
Yes the event could use the dedicated content type but needs to have the application property _hono_registration_status_ set as well.

**Comment by sophokles73** [comment]
I do not see a problem with that at all. This would simply be part of the dedicated event's content model ...
