### ISSUE TITLE
Move general explanations of Kafka-based APIs to separate document

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#2415]
Currently, the specification of the [Telemetry API for Kafka](https://www.eclipse.org/hono/docs/dev/api/telemetry-kafka/) contains a big part of general explanations regarding Kafka-based messaging (section [Kafka-based Messaging](https://www.eclipse.org/hono/docs/dev/api/telemetry-kafka/#kafka-based-messaging)). This is equally relevant for the Event API and the C&C API. It might make sense to move this part into a separate document which serves as an obvious starting point to learn about the Kafka-based APIs. The other documents could then link to it.
WDYT?

**Comment by b-abel** [comment]
Similar to the remarks about producers, it would make sense to add notes regarding consumers.

**Comment by sophokles73** [comment]
sounds reasonable to me :+1:
