### ISSUE TITLE
Adapt package names in module "clients" to common pattern

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#2434]
The package names in some sub-modules of the module _clients_ do not follow a common pattern, as mentioned in the comments:
https://github.com/eclipse/hono/commit/4f32409ef080c5d5b0306a9e773136382b86a701#r46336494
https://github.com/eclipse/hono/commit/4f32409ef080c5d5b0306a9e773136382b86a701#r46336484
https://github.com/eclipse/hono/commit/4f32409ef080c5d5b0306a9e773136382b86a701#r46336467

The need to be adapted.

The pattern looks like this:

`org.eclipse.hono.<kind>.client.<api-type>.<messaging-protocol>` where `<kind>` is e.g. `application` or `adapter`,  `<api-type>` groups API semanticaly (e.g. `telemetry`, `command`, `registry`) and `<messaging-protocol>` is either `amqp` or `kafka`.

Examples:

- `org.eclipse.hono.adapter.client.telemetry.amqp`
- `org.eclipse.hono.application.client.kafka`

**Comment by b-abel** [comment]
There are two modules that contain code specific for a messaging protocol to be used in different kinds of clients. How should the pattern look there?

**Comment by sophokles73** [comment]
The package names in *kafka-common* need to be adapted to start with *org.eclipse.hono.client.kafka*
