### ISSUE TITLE
Metrics reported to influxDB should be parsed into tags

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#245]
The metrics reported to influxDB using the Graphite line protocol should be parsed using a [template](https://github.com/influxdata/influxdb/blob/master/services/graphite/README.md) at the influxDB side in order to extract *tags* from the metric name reported. That way, queries on the data will be easier to express and will perform much better.

**Comment by sophokles73** [comment]
@pellmann 
I think your latest commit is related to this issue, isn't it?

**Comment by pellmann** [comment]
fixed in https://github.com/eclipse/hono/commit/9a48726c902024a1930012cacd72ffa1931dc5ce
