### ISSUE TITLE
Respect maxPayload also for commands

### ISSUE THREAD

**Issue by Christian-Schmid** [eclipse/hono#2457]
The Eclipse Hono protocol adapters offer a configuration property ``maxPayloadSize``, e.g. ``hono.coap.maxPayloadSize``.
With this property it is possible to limit the payload size of incoming requests.

Would it make sense to apply this limit also for outgoing requests (command messages towards the device)?
One benefit I would see, is that device implementors could consider this maximum when creating their firmwares.

Thanks
Chris

**Comment by sophokles73** [comment]
This is already supported at the protocol adapter level: https://www.eclipse.org/hono/docs/admin-guide/hono-client-configuration/#connection-properties

You can set `HONO_MESSAGING_MAXMESSAGESIZE` to the maximum number of bytes that the adapter should accept for upstream commands to send to the devices ....

**Comment by Christian-Schmid** [comment]
Thank you very much. The property we're already using, but I wasn't certain if they are intended for that purpose.
