### ISSUE TITLE
Metrics currently are not scoped to service instance

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#246]
Hono Messaging currently reports all metrics using a single namespace shared by all instances of Hono Messaging. This leads to erroneous values being displayed on the Grafana dashboard when running multiple instances of Hono Messaging because the values are not aggregated but reflect the values of the particular instance which submitted its values to InfluxDB most recently.

**Comment by sophokles73** [comment]
@pellmann 
I think your latest commit is related to this issue, isn't it?

**Comment by pellmann** [comment]
fixed in https://github.com/eclipse/hono/commit/9a48726c902024a1930012cacd72ffa1931dc5ce
