### ISSUE TITLE
[1.5] Protocol adapters reuse obsolete downstream senders after disconnect

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2472]
After a disconnect with the AMQP messaging network has occurred, protocol adapters don't clear the cache containing the downstream sender objects.
This leads to telemetry/event messages not getting sent.

Bug only exists in 1.5, not in 1.6 and master.

**Comment by fkaltner** [comment]
Regarding the labels you added: aren't the device registries affected as well since they also may send events when they use gateway-based auto-provisioning?

**Comment by calohmn** [comment]
Fixed via 8126063e795d06c0de839c09d344653db274cb22.
