### ISSUE TITLE
[#8] Add unit tests for module `hono-client-application-kafka`

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#2476]
Most of the module `hono-client-application-kafka` is not covered with tests yet. The tests in `AbstractAtLeastOnceKafkaConsumerKafkaMockConsumerTest` and `AbstractAtLeastOnceKafkaConsumerMockitoTest` show how the consumer logic can be tested.

**Comment by sophokles73** [comment]
@b-abel is this still an issue?

**Comment by b-abel** [comment]
Closed: There are now a couple of tests in that module.
