### ISSUE TITLE
Add time-to-live to Kafka-based Clients

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#2477]
The Kafka-based downstream message APIs already define an optional header *ttl*, but the producer and consumer implementations do not use them by now. The protocol adapters put a TTL property in the metadata (if defined) that is in seconds. The producer should add the creation-time if missing, like it is already done for *ttd* and change the *ttl* from seconds to milliseconds. On the consumer side, records, where the *ttl* elapsed, should be ignored.

**Comment by b-abel** [comment]
Ignoring records with elapsed *ttl* should be done as early as possible in our Kafka consumer implementation to be close to the behavior of AMQP. WDYT, @sophokles73?

**Comment by sophokles73** [comment]
Sounds good. Maybe we can make this configurable as well with the default being to discard expired records.

**Comment by b-abel** [comment]
> Maybe we can make this configurable as well with the default being to discard expired records.

If we do not discard the record in the consumer, we should add the information in the message object passed to the message handler. In the case of the northbound client, this would mean adding this property to `DownstreamMessage`, which probably makes no sense for AMQP. With AMQP, the message handler would not be called for messages with elapsed *ttl*.
