### ISSUE TITLE
Add Command&Control support to new northbound Client Interface

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#2478]
The new northbound client interface `org.eclipse.hono.application.client.ApplicationClientFactory` currently only supports downstream messaging and misses support for Command&Control.

**Comment by sophokles73** [comment]
@b-abel will this go into 1.7.0?

**Comment by b-abel** [comment]
@calohmn Is this something for you? 
The next issue I plan to work on is #2402. I'm not sure that I can finish both this month.

**Comment by kaniyan** [comment]
@b-abel @calohmn I am working on this.

**Comment by sophokles73** [comment]
@b-abel @kaniyan Can this be closed?

**Comment by kaniyan** [comment]
> @b-abel @kaniyan Can this be closed?

@sophokles73  This can be closed now.

**Comment by kaniyan** [comment]
This has been closed via PRs #2498, #2529, #2533 and #2583.
