### ISSUE TITLE
CommandRouter/Kafka: prevent lost/duplicate message deliveries

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2480]
The Kafka command message consumer in the CommandRouter component is currently configured to auto-commit partition offsets.

This means there is a high likelihood of duplicate command messages when a CommandRouter instance is restarted.

On the other hand, it also means that a command message could get lost, if the commit takes place *before* a command message is forwarded on the internal command topic. To prevent this, the offset commit should take place *after* the ack of the message forwarding operation has been received.

**Comment by sophokles73** [comment]
@calohmn do we need this in 1.7.0 or can/should we postpone this issue?

**Comment by calohmn** [comment]
Yes, we can postpone it.

**Comment by sophokles73** [comment]
@calohmn can this be closed?

**Comment by calohmn** [comment]
@sophokles73 Not yet, I'll create one more PR (manual offset commits in command router).

**Comment by calohmn** [comment]
Implemented via 8569ed9d976bae43d1816db33d077e6861f4ca20, adf43a253be0753e1460093176c96634ceba43f1 and e867fdc84aea3f0c884868c97e5d8cab39c063f6.
