### ISSUE TITLE
Telemetry API : missing tenant-id application property and link disconnection

### ISSUE THREAD

**Issue by ppatierno** [eclipse/hono#25]
Just to be more explicit on the Telemetry API specification ...

In the "Upload Telemetry Data" section after the table of delivery modes we wrote "All other combinations are not supported by Hono and result in a termination of the link". It's totally right.

I think that we should be clearer even when describe the relation of "tenant-id" in the target address and as application property.

The following : 

> 
Client has established an AMQP link in role sender with Hono using target address telemetry/${tenant-id}. If the target address contains a value for tenant-id then each message sent to Hono on this link MUST also contain the tenant-id application-property having the same value. If the target address doesn't contain a tenant-id then Hono will determine the tenant the device belongs to dynamically for each message sent. 

could be ...

> Client has established an AMQP link in role sender with Hono using target address telemetry/${tenant-id}. If the target address contains a value for tenant-id then each message sent to Hono on this link MUST also contain the tenant-id application-property having the same value **otherwise it results in a termination of the link**. If the target address doesn't contain a tenant-id then Hono will determine the tenant the device belongs to dynamically for each message sent.

Finally, in the latter case what's happen if tenant-id is specified as application property (but not in the target address) ? I suppose that Hono doesn't consider it because it determines the tenant dynamically for each message sent. Could we be more explicit on that ? What do you think ?

**Comment by sophokles73** [comment]
I see your point, Paolo, that we should make Hono's behavior in these cases more explicit and I agree that we should. I am not sure, though, if termination of the link is the right behavior in case of a *malformed* message. Until now, my idea was to simply discard such messages but your proposal (terminating the link) also seems feasible.

What do the others think?

**Comment by dguggemos** [comment]
I think simply discarding is dangerous, because the sender will continue to send those malformed messages. Or did you mean to reject the message by means of a `REJECTED` delivery state? But even then how would the sender react to this `REJECTED` message? I don't think there would be some logic to add the missing fields. So I tend to prefer Paolo's suggestion to terminate the link.

**Comment by sophokles73** [comment]
And in the anticipated case that the client sends with *AT MOST ONCE* QoS it will not see the `REJECTED` delivery state anyways ...

**Comment by hekonsek** [comment]
I would also say +1 for terminating the link.

**Comment by sophokles73** [comment]
This is reflected in the Telemetry API spec and master.
