### ISSUE TITLE
Use separate HonoClient in Protocol Adapters for Credentials API access

### ISSUE THREAD

**Issue by sysexcontrol** [eclipse/hono#250]
Despite that Hono provides in it's default configuration the Device Registration API and the Credentials API in one component (the "Device Registry"), the access to the Credentials API in protocol adapters should be done in a separate client.
This enables to implement the two APIs in different microservices.

**Comment by sophokles73** [comment]
@sysexcontrol this is fixed, isn't it?

**Comment by sysexcontrol** [comment]
Fixed in 61ca3e8.
