### ISSUE TITLE
Documentation on Kubernetes deployment

### ISSUE THREAD

**Issue by ppatierno** [eclipse/hono#254]
Even if the Kubernetes deployment is quite similar to the OpenShift one I think that it deserves a section under "Deployment" section on the web site. Maybe we can describe only the way to use Minikube and not Kubernetes on bare metal.

**Comment by sophokles73** [comment]
totally agree

**Comment by ppatierno** [comment]
I'm working on that ;)

**Comment by ppatierno** [comment]
close on behalf of 3c6070aa0ffb9a4e59ccaf86509249db0b928217
