### ISSUE TITLE
Close AMQP adapter device connection on terminal errors

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2545]
When any of the following errors occurs while an AMQP device sends a telemetry/event/command response message, the connection to the device should be closed:

* The adapter is disabled for the tenant that the client belongs to,
* The authenticated device or gateway is disabled or not registered,
* The tenant is disabled or does not exist.

Corresponds to the changes made for the MQTT adapter in #2539.

**Comment by kaniyan** [comment]
This has been closed via PR #2564.
