### ISSUE TITLE
Disable server-side support of specific TLS/SSL cipher suites by configuration

### ISSUE THREAD

**Issue by jnbsi** [eclipse/hono#2556]
As SSL cipher suites' level of security decreases over time and SSL engines might not get adapted promptly it can become necessary to be able to deactivate server-side support for certain SSL cipher suites explicitly.
I.e. there could be an additional configuration property on each service/adapter that takes a list of cipher suite names which will be disabled on the corresponding SSL endpoint.

**Comment by sophokles73** [comment]
I would be more in favor of specifying a white list, i.e. a list of supported cipher suites, instead. Would that work for you?

**Comment by jnbsi** [comment]
Yes, that would work as well!
