### ISSUE TITLE
Add Kafka based integration tests for Request-Response-Commands 

### ISSUE THREAD

**Issue by fkaltner** [eclipse/hono#2569]
Follow-up of #2469

**Comment by sophokles73** [comment]
@fkaltner @kaniyan @b-abel What is the status of this? Is there anything left to be done? Is anybody working on this?

**Comment by fkaltner** [comment]
To my knowledge @kaniyan is working on this. Correct, @kaniyan ?

**Comment by kaniyan** [comment]
I have created a PR #2608 which also includes a commit for this issue too. Once that PR is reviewed and merged, we can close this issue.

**Comment by kaniyan** [comment]
PR #2608 has been approved now and also merged into master. We can close this issue now.
