### ISSUE TITLE
OutOfMemoryError in MQTT adapter

### ISSUE THREAD

**Issue by herfort** [eclipse/hono#257]
We get a OutOfMemoryError in the current version of MQTT adapter by using with docker stack on AWS.
The adapter is running without heavy load, 1-3 messages per minute.
For trace please see attachment:
[mqtt_oom.txt](https://github.com/eclipse/hono/files/1124928/mqtt_oom.txt)

**Comment by sophokles73** [comment]
I may have an idea what is causing this. Let me check ...

**Comment by sophokles73** [comment]
@ppatierno, my understaning is that you have added a handler to the `MqttEndpoint` which takes care of removing the assertion from the map when the client explicitly closes the connection.
In order to also being able to tidy up when the client gets *disconnected*, e.g. because of a network failure and without an explicit DISCONNECT packet, you need to fix the ping mechanism as indicated in #273. Is this correct?

**Comment by ppatierno** [comment]
@sophokles73 the #273 is fixed but I'll develop a work around in the adapter for this before the MQTT server provided keep alive mechanism will be available with next release

**Comment by sophokles73** [comment]
@herfort depending on the behavior of your client, this may already fix the problem for you, i.e. if your client works like this:
1. open MQTT connection
1. send data
1. close connection

then you should be good. If your client does not close the connection, however, the problem will be resolved with @ppatierno 's *interim* fix for the erroneous keep alive ...

**Comment by ppatierno** [comment]
It should work even in case the client doesn't send PINGREQ for keeping connection alive. I was wrong.

**Comment by sophokles73** [comment]
@herfort is this still an issue?

**Comment by sophokles73** [comment]
This might also be related to #276 because the MQTT adapter also tries to maintain a connection with the Device Registration service.

**Comment by herfort** [comment]
We can not reproduce the problem now.

**Comment by ppatierno** [comment]
@herfort so I'm going to close this issue. Feel free to re-open it if you have the problem.
