### ISSUE TITLE
Command Router receives no commands after restart

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2576]
The Command Router component uses tenant-specific receiver links to receive command messages.

When a Command Router crashes and restarts, these links don't get recreated automatically, so that commands for still-subscribed devices are not forwarded to the adapters.

This is a problem when

- all command routers are restarted at the same time
- or one command router gets restarted, and it previously had a tenant-specific receiver link not existing in one of the other command routers.

If a tenant has many devices and they only subscribe for commands with a short ttd (e.g. HTTP/CoAP devices), then this probably won't cause much trouble because the other command routers probably will have been involved with this tenant as well and the restarted command router will soon get a new command-subscription so that the tenant-specific receiver link is recreated.

But for a tenant with a single MQTT/AMQP device, where a command subscription was registered at the now restarted Command Router, commands won't reach the device and only a restart of the MQTT/AMQP adapter or a new subscription by the device will fix this.

**Comment by calohmn** [comment]
A fix for this should address these cases:

**Command Router with embedded cache**
The device connection/command subscription data will need to be restored from the adapters.
The commandRouter config in the adapters will need to have a "restoreOnReconnect: true" setting in this case.
With this flag set, the adapter will handle a reconnect of the AMQP connection to the Command Router by going through its current command-subscriptions and invoking `commandRouterClient.registerCommandSubscription` for each of them.

Since a command-subscription in a adapter could have been made obsolete by a subsequent subscription for the same device from another adapter, the `registerCommandSubscription` operation needs an additional "timestamp" parameter (in the sense of "timestamp of the original request"), so that the Command Router can ignore requests with a timestamp older than one it already got. With this timestamp, the remaining lifespan can then also be determined.

**Command Router with data grid**
Upon startup, the Command Router queries the Device Connection cache entries for the contained tenant IDs and recreates the corresponding AMQP receiver links.
The Hono Cache interface needs to be extended accordingly, allowing retrieval of distinct key prefixes. To be implemented for Infinispan using a keySet() [stream](https://infinispan.org/docs/stable/titles/developing/developing.html#streams).

**Comment by sophokles73** [comment]
For the second case with the Data Grid:
I am not sure if it is a feasible approach to iterate over all keys in the cache to determine the distinct tenant IDs ...
Instead, the protocol adapter instances could keep such a list of distinct tenant IDs themselves and provide it in a separate (AMQP) message sent after (re-)establishment of a lost connection to a Command Router instance. Wouldn't that be more efficient?

**Comment by BobClaerhout** [comment]
Thanks for creating the issue @calohmn.
I would also like to mention that the Lorawan adapter also have this issue so it would be nice if this adapter also gets this fix (which probably requires an implementation in the base adapter or in the http adapter as well).
Considering they ways to solve this: I don't really have a preference. I do not have enough knowledge of the command router yet to add something meaningful to the discussion

**Comment by calohmn** [comment]
> I would also like to mention that the Lorawan adapter also have this issue so it would be nice if this adapter also gets this fix (which probably requires an implementation in the base adapter or in the http adapter as well).

@BobClaerhout The fix is in base/client modules, so the Lora adapter got fixed as well.

**Comment by calohmn** [comment]
Concerning the embedded cache case:
I think we should configure the embedded cache with file persistence by default then and expect the storage directory to be mapped to a persistent volume in the Kubernetes cluster then. That means the mapping data is restored upon Command Router restart.
@sophokles73 WDYT?

**Comment by sophokles73** [comment]
Wouldn't that need to be done in the Helm chart?

**Comment by calohmn** [comment]
The IoT Packages helm chart currently doesn't use a `cache-config.xml` file where the persistence configuration then would have to be put.
We could avoid having to define a `cache-config.xml` for the default embedded cache case by programmatically enabling cache file persistence in case no cache config file exists.

**Comment by sophokles73** [comment]
For the integration tests there is no need for file persistence. For the Helm chart I see the benefit of using file persistence by default but I would then still prefer to include a default `cache-config.xml` file in the chart which can also be used as a blue print for custom configurations ...

**Comment by calohmn** [comment]
Ok, then we'll include a `cache-config.xml` file in the chart, making things more explicit there. I've created #213 for that.
