### ISSUE TITLE
Project vserver - OS support change

### ISSUE THREAD

**Issue by eclipsewebmaster** [eclipse/hono#2588]
Webmaster has been notified that the version of Ubuntu your project vserver is running will no longer be supported after April 30, 2021.  That means no new security patches will be issued and our cloud tools will have reduced functionality.

If the vserver is still needed we can coordinate its replacement via this issue.

Otherwise Webmaster will remove the instance after May 28, 2021 if there hasn't been a response on this issue.

-M.

**Comment by sophokles73** [comment]
@eclipsewebmaster We are currently running
```sh
Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-136-generic x86_64)
```
 Are you sure that this version is running out of support? We can also upgrade to 20.04 if I am not mistaken ...

**Comment by eclipsewebmaster** [comment]
Well according to our cloud management panel the hono instance is running ubuntu-1604-xenial which is what is going out of support.  If you've done an inplace upgrade to 18.04 then you should be fine, but I can't see that(obviously)

**Comment by sophokles73** [comment]
Yes, we upgraded to 18.04 LTS some months ago.

**Comment by eclipsewebmaster** [comment]
In that case I think we're done here.
