### ISSUE TITLE
Move Device Registration REST API from REST Adapter to Device Registry

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#259]
Currently, the REST Adapter exposes resource for managing device registration information as well. This has made sense in the past, when the default device registration service was part of Hono Server.

However, now that we have refactored the default device registation API implementation into its separate component (*Device Registry*), we should have that component expose its own RESTful API for manging the device registration information and remove it from the REST Adapter. This way the REST Adapter's responsibilities can be reduced to its main purpose, which is providing a mapping of the Telemetry and Event APIs to device protocols.

**Comment by b-abel** [comment]
I would like to work on this. 
My approach would be to: 1.) Create a base class for `SimpleDeviceRegistryServer` in `hono-service-base` module. 2.) Add the REST interface from `hono-adapter-rest-vertx` resp. `hono-adapter-http-vertx-base` to the newly created parent of `SimpleDeviceRegistryServer`. 
The second step will probably cause some code duplication to keep the PR small. To remove those duplications further refactorings would be necessary, but I think this should be done with a new issue. Some more generic HTTP server functionality from `hono-adapter-http-vertx-base` could be moved to a place where it could be used independently from a protocol adapter.

**Comment by sophokles73** [comment]
sounds good

**Comment by sophokles73** [comment]
fixed in 75c1acc09e511d5e2371ad661bcfbc29f50b34a2
