### ISSUE TITLE
Support non-static replication factor for internal C&C Kafka topic

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2590]
Currently the replication factor used when creating the internal C&C Kafka topic is always set to 1.
This may cause errors depending on the Kafka cluster setup.
Instead, the broker "default.replication.factor" setting should be used.

**Comment by sophokles73** [comment]
@calohmn what is the status of this in 1.7.x?

**Comment by calohmn** [comment]
@sophokles73 Fix has now been applied to 1.7.x (108f5f80404e39a9c85167cf280284174c107c5e).
