### ISSUE TITLE
Documentation: Paths in Links should end with slash

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#2598]
The addresses that Hugo generates usually end with "/". For example `https://www.eclipse.org/hono/docs/user-guide/` and not `https://www.eclipse.org/hono/docs/user-guide`. Without the trailing slash, the browser gets a 301 redirect which causes the page to be loaded slower and will be punished by search engine ranking algorithms. This is even true when linking to anchors: they should look like e.g. `https://www.eclipse.org/hono/docs/api/management/#tenants`.

**Comment by sophokles73** [comment]
@b-abel Are you working on this?

**Comment by b-abel** [comment]
> @b-abel Are you working on this?

Currently not. I don't see a high priority. Do you?

**Comment by sophokles73** [comment]
I am not sure. If it is not too much effort, I think we should try to get it over with ASAP ...

**Comment by b-abel** [comment]
I did not found the problems described here with the current documentation anymore (maybe due to the newer Hugo version). While investigating I found related problems that are fixed in #2621.
