### ISSUE TITLE
Update Hono Documentation to include Kafka

### ISSUE THREAD

**Issue by fkaltner** [eclipse/hono#2601]
With the upcoming Kafka support the Hono documentation should be adapted, e.g. the CLI documentation, Getting Started and all other places where the messaging network is used.

**Comment by b-abel** [comment]
Regarding the _Getting Started_ guide: the simplest solution would probably be to make a complete copy of the guide with adaptions to Kafka. The two documents can always be integrated later if it becomes apparent that both variants of messaging should be promoted permanently. WDYT?

**Comment by fkaltner** [comment]
>  The two documents can always be integrated later if it becomes apparent that both variants of messaging should be promoted permanently.

@sophokles73 Maybe I missed something, butI thought both variants actually were supposed to coexist permanently?

**Comment by sophokles73** [comment]
FMPOV there is no reason to discontinue the AMQP support. However, we should still have a *preferred* setup that we use by default and which we should then also use in the Getting Started guide, right?

**Comment by b-abel** [comment]
I am not sure now: can we all agree on the proposal to create two separate documents?

I think there needs to be some sort of end-to-end documentation for each type of messaging system that shows how to use the overall system with clients. The existing Getting Started Guide FMPOV does a great job at this. The differences between AMQP-based and Kafka-based messaging are significant enough that I think it makes sense to have two separate documents for them. 
How to name them and where and how prominently they are displayed can still be changed at any time.

**Comment by fkaltner** [comment]
If the documents do differ significantly there's no reason no to have them 😃 

Maybe I misunderstood what you wrote. I got the impression the argument was to have a (mostly) duplicated copy for now and postpone the effort for integrating both documents later, since the assumption was that one copy may become obsolete...

**Comment by sophokles73** [comment]
@b-abel @fkaltner can this be closed?

**Comment by b-abel** [comment]
FMPOV, yes.
