### ISSUE TITLE
Include cipher suite name when reporting connection attempts

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#2620]
The protocol adapters currently report connection attempts with an outcome (successful/unsuccessful) tag. It would be nice to also have a tag `cipher` which contains the cipher suite used when a connection has been established on top of TLS.

**Comment by jnbsi** [comment]
Maybe the TLS version used for the connection could also be tracked by a separate tag. This would ease aggregations based not only on the name of the cipher but also on the TLS version.
