### ISSUE TITLE
Introduce maximum number of devices and credentials per tenant in (MongoDB) device registry

### ISSUE THREAD

**Issue by mbaeuerle** [eclipse/hono#2626]
At the moment a tenant can have an unlimited number of devices and credentials in Hono.
Like for other resources (e.g. maximum connections) a service administrator may want to limit the number of devices which can be created for a tenant.
There are already resource limits on tenant level like the maximum connections which can be configured independently for each tenant. I therefore propose to add two additional resource-limits. One for the maximum number of devices and one for the maximum number of credentials per device (or per tenant).
The device registries then enforce these limits when a tenant creates new devices or credentials.

No limit set could be the default which would allow to still create infinite devices and credentials.

**Comment by sophokles73** [comment]
> One for the maximum number of devices and one for the maximum number of credentials per device (or per tenant).

@mbaeuerle  Is there a particular reason why you want/need to limit the number of credentials?

**Comment by mbaeuerle** [comment]
@sophokles73 yes, a service administrator may want to limit the number of credentials for a tenant e.g. to implement multiple service plans where each plan can have a different amount of maximum devices/credentials.

**Comment by sophokles73** [comment]
Well, I understood that you want to limit them. What I do not understand is *why* you would want to limit the number of credentials? Does having more credentials incur higher cost?

**Comment by jnbsi** [comment]
I think this is a security concern. A (anonymous) user might create reams of credentials which could flood the database (even though the data size per credential is small). This can be prevented i.e. by rate limiting or simply by defining an upper limit of credentials per device. Since the number of devices can be limited, the total number of credentials would be limited as well.

**Comment by sophokles73** [comment]
The maximum number of devices per tenant can already be configured at a global level, i.e. using the same maximum number of devices for all tenants.
