### ISSUE TITLE
Collect data about used TLS cipher suites

### ISSUE THREAD

**Issue by jnbsi** [eclipse/hono#2627]
For operations teams it might be useful to be able to see which cipher suites are effectively used by devices that connect to any of the protocol adapters. Therefore it would be useful to have additional metrics collected by the protocol adapters to allow an analysis of the cipher suites usage.

**Comment by sophokles73** [comment]
@jnbsi This seems to be a duplicate of #2620

**Comment by jnbsi** [comment]
@sophokles73 Yes, you are right. #2620 covers this concern.
