### ISSUE TITLE
HTTP Status Code 503 While CLI is Running

### ISSUE THREAD

**Issue by mrclbrchr** [eclipse/hono#2635]
Hello, i hope this thread isnt unnecessary, but i couldnt find any solution yet.

I'm new to hono and want to find out how it is working and how i can use it.

So i've set everything up, started my minikube and minikube tunnel. The getting started python script was running correctly so i changed the adapter adresses to the ones give from my minikube cluster. My problem is, that amqp does not recieve a http or mqtt message, my http status code is 503 and the content is "no consumer available". So i checked out what could cause that error, and realised that i had to start the hono-cli.jar to simulate a consumer.

So im running my python script( the one given from the hono getting started with adjusted adapter adresses), pause after tenant and device is created, run the hono-cli.jar with the corresponding device and tenant id and after that i continue sending the http request and mqtt publish, but im still facing the same issue. 

Maybe i'm acting stupid, but i cant figure out what causes this problem.

**Comment by kaniyan** [comment]
> run the hono-cli.jar with the corresponding device and tenant id and after that i continue sending the http request and mqtt publish, but im still facing the same issue.

Did you also adapt the address(_hono.client.host_) to point to your local dispatch router instance while running `hono-cli`.jar? 
Some logs would be helpful to debug further. While running `hono-cli.jar` are there any warning/error messages?

**Comment by mrclbrchr** [comment]
You truly made my day! Thank you very much.

There  is a variable amqpNetworkIp in the python script which is used for the hono.client.host, so i looked up my service list and set my eclipse-hono-adapter-amqp-vertx for this variable, seemed to make sense, but obviously it doesnt. After i changed it to the eclipse-hono-dispatch-router-ext everything is working now. 

Could you maybe explain why my approach was not correct, respectively for what purpose the eclipse-hono-adapter-amqp-vertx service exists? As i said i'm new to hono and it did'nt seem that this difficulty is handled in the documentation, or am i wrong?

**Comment by kaniyan** [comment]
@mrclbrchr I am glad it helped :)


> Could you maybe explain why my approach was not correct, respectively for what purpose the eclipse-hono-adapter-amqp-vertx service exists? As i said i'm new to hono and it did'nt seem that this difficulty is handled in the documentation, or am i wrong?

AMQP adapter is another protocol adapter like MQTT and HTTP adapters to which the devices can connect. The north bound applications connect to the AMQP 1.0 network (in the example setup to the dispatch router). Please refer to the [Hono's component diagram](https://www.eclipse.org/hono/docs/architecture/component-view/) to have an overall view of the system.


If this issue is resolved, could you also please close this issue.
