### ISSUE TITLE
Deployment MQTT Broker/Individual MQTT Adapter

### ISSUE THREAD

**Issue by mrclbrchr** [eclipse/hono#2648]
Hello everybody,

recently i'm facing the question, where the hono mqtt broker is placed exactly. Reffering to the architecture component view, is it deployed in the mqtt-adapter or in the AMQP Messaging Network?

Further i'm asking myself, is it possible to deploy my own mqtt service like moqsuitto and integrate it into my hono deployment?

**Comment by sophokles73** [comment]
There is no MQTT broker involved anywhere in Hono. The MQTT protocol adapter simply exposes an endpoint that allows devices to use the MQTT 3.1.1 protocol to exchange messages. However, the MQTT adapter only supports a very limited subset of MQTT 3.1.1 as is described in the [MQTT User Guide](https://www.eclipse.org/hono/docs/user-guide/mqtt-adapter/). All messages that are received from devices using the arbitrary transport protocols the the adapters support are forwarded to the downstream applications using the AMQP 1.0 Messaging Network (see https://www.eclipse.org/hono/docs/architecture/component-view/). In the near future we will also support Kafka as an alternative messaging infrastructure for that purpose.

Based on that, there is no way (nor need) for you to deploy an MQTT broker.

**Comment by sophokles73** [comment]
@mrclbrchr can this be closed?
