### ISSUE TITLE
Kafka: Provide feedback on failed Command messages

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2661]
One main difference between the Kafka and AMQP Command & Control implementations is that with Kafka, there is no protocol-provided way to inform the northbound application about a failed delivery, like there is with AMQP using the delivery disposition update mechanism (using a `rejected`, `modified` or `released` outcome).

A failure to forward a command message to the device could for example be caused by
- the command message being invalid
- the command target device or its tenant being disabled/deleted
- there being no currently subscribed command consumer for the target device
- some network error when forwarding the message
- etc.

## Request/response command messages

When there is an error forwarding a request/response command message, a command response message with the corresponding error could be published on the command-response topic.
That means either the Command Router component or the Protocol Adapter will publish such a message.
The message should have some special header so that it can be distinguished from a command response coming from the device.

## One-way command messages

For one-way command messages, using the command-response topic for reporting errors doesn't seem appropriate, "one way" and "response" being mutually exclusive.
However, having a backchannel for an error notification in a scenario where only one-way commands can be used because the device can't send responses still looks like a useful feature. 

One-way and request-response commands are currently distinguished via the `response-required` header.
For a scenario of sending commands to a device that doesn't support sending response messages, we could use an additional header - `use-delivery-status-response` (or `only-delivery-status-response`). 
With `response-required` and `use-delivery-status-response` set to `true`, the command will be forwarded like a one-way command to the device. But any error during command processing in the command router or the adapter will be reported on the command-response topic and a successful delivery will result in a "status 202" command-response message. Such a response would be equivalent to an `accepted` delivery outcome returned in the AMQP one-way command case - with the same caveat, that a northbound application can't be certain that the device has actually received the command message in that case. Nonetheless, being able to quickly get an error response makes the overall feature worthwhile FMPOV.

**Comment by calohmn** [comment]
The idea is now to (first) implement sending error command responses for _request/response_ command messages.

I would make these messages distinguishable from command responses sent from the device itself by using a special content type, namely `application/vnd.eclipse-hono-delivery-failure-notification+json`.

**Comment by calohmn** [comment]
Implemented for request/response command messages - see #2728, #2712.

**Comment by sophokles73** [comment]
@calohmn can you also add an entry to the release notes?

**Comment by calohmn** [comment]
@sophokles73 done (fa52f41161241b11868e33ecf3ee1c937f6c99bb).
