### ISSUE TITLE
Support device identifier pattern during device/gateway auto-provisioning

### ISSUE THREAD

**Issue by kaniyan** [eclipse/hono#2664]
The _tenant_ configuration should support configuring a _device identifier pattern_ which would be used by the device registries to generate _device identifier_ of _devices/gateways_ during _auto-provisioning_.

See below examples for device-id patterns. For more information on this feature refer to the discussion thread in issue #2272.

- `device-id-pattern: "prefix123:{{subject-DN}}"` -> use "prefix123" and the whole subject DN from the device certificate
- `device-id-pattern: "prefix456:{{subject-CN}}"` -> use "prefix456" and the subject CN from the device certificate
- `device-id-pattern: "{{subject-CN}}"` -> usage of prefix in device-id pattern is optional -> in this case only CN is used in device-id pattern

**Comment by sophokles73** [comment]
@kaniyan FMPOV it would be good to also have this new functionality covered by an integration test ...

**Comment by kaniyan** [comment]
> @kaniyan FMPOV it would be good to also have this new functionality covered by an integration test ...

I have already included the below two new  tests  methods to cover this functionality.

`CredentialsApiTests.testGetCredentialsWithDeviceAutoProvisioningUsingDeviceIdTemplate()`

`CredentialsApiTests.testGetCredentialsWithGatewayAutoProvisioningUsingDeviceIdTemplate()`
