### ISSUE TITLE
Send event notification after successful device/gateway auto-provisioning

### ISSUE THREAD

**Issue by kaniyan** [eclipse/hono#2665]
This is to extend support to send an empty notification event with _content-type_ as `application/vnd.eclipse-hono-device-provisioning-notification` once a device or gateway is successfully auto-provisioned. For more information refer to the [discussion thread](https://github.com/eclipse/hono/issues/2272#issuecomment-723094832) and [documentation](https://www.eclipse.org/hono/docs/api/event/#device-provisioning-notification) on device provisioning notification.

**Comment by kaniyan** [comment]
What should be done if sending an auto-provisioning event notification fails even after specified number of retries?
1. As I understood, in many cases auto-provisioning may not be useful until the north-bound side (e.g ditto) is notified with an provisioning event. FMPOV sending an auto-provisioning event is also a part of the auto-provisioning process. If sending an event fails, then auto-provisioning should fail too. In that case, we should revert all the changes that we made during the auto-provisioning process (i.e remove device registration/credentials).

2. In case of auto-provisioning implementation for edge devices, a property `autoProvisioningNotificationSent`, which is part of the status section in device registration information, is being employed to ensure that a provisioning event is sent at least once. When sending a provisioning event fails, _the auto-provisioning method still returns a failed future_ but auto-provisioning related changes are _not_ being reverted (i.e remove device registration/credentials) and the `autoProvisioningNotificationSent` remains _false_. Every time when devices connect and protocol adapters assert device registration, the device registry checks for the value of the property `autoProvisioningNotificationSent`. If it is _false_, it sends a provisioning event notification and updates this property to _true_ and persists the device registration information. I am not aware of the background why the changes are not being reverted (i.e remove device registration/credentials) and rather making use of a property to resend the event. As far as I understood, if we revert those changes when sending an event fails, then we don't need this property to ensure sending of events and also no need to check this property every time a device registration is being asserted by protocol adapters.  If auto-provisioning of devices and gateways is to follow the same pattern, then credentials record should also contain a status section involving property `autoProvisioningNotificationSent` similar to device registration. When every time credentials are retrieved by protocol adapters, this property should be checked to resend provisioning event. After re-sending a event, credentials should be updated to reflect the actual status.

Wouldn't be straightforward to have option 1 for auto-provisioning of devices/gateways and as well as edge devices? When every time devices connect and authenticate then there is no need to check the status property `autoProvisioningNotificationSent` (also no need to map `RegistrationResult` to `Device` on every request as it is currently being done when provisioning is enabled).  Or am I missing something? @sophokles73 @calohmn @fkaltner WDYT?

**Comment by sophokles73** [comment]
> As far as I understood, if we revert those changes when sending an event fails, then we don't need this property to ensure sending of events and also no need to check this property every time a device registration is being asserted by protocol adapters.

What if we fail to send the event but right before we are able to revert the changes in the DB the process crashes/stops? Then we would need to deal with (i.e. prevent) the (potentially) duplicate creation of the device when it connects the next time right? Is that easier to manage?

>  If auto-provisioning of devices and gateways is to follow the same pattern, then credentials record should also contain a status section involving property autoProvisioningNotificationSent similar to device registration. When every time credentials are retrieved by protocol adapters, this property should be checked to resend provisioning event. After re-sending a event, credentials should be updated to reflect the actual status.

It would feel very strange to me if we would introduce such a property in the credentials object. Why shouldn't we use the same property in the device registration for that purpose?

**Comment by kaniyan** [comment]
> What if we fail to send the event but right before we are able to revert the changes in the DB the process crashes/stops? Then we would need to deal with (i.e. prevent) the (potentially) duplicate creation of the device when it connects the next time right? Is that easier to manage?

In order to handle data integrity when DB process crashes/stops then we need some extra mechanism to deal with. Introducing such mechanism could involve introducing some properties which won't bring any advantages over what we have right now. In that case, we can still continue with the status property what we have right now.

> It would feel very strange to me if we would introduce such a property in the credentials object. Why shouldn't we use the same property in the device registration for that purpose?

Auto-provisioning of devices/gateways take place while fetching credentials by protocol adapters. If we have to use the device registration then every time devices connect to Hono and protocol adapters retrieve credentials the corresponding device registration should also be retrieved from the database in addition to the credentials to check if the auto-provisioning notification has been already successfully sent or not. In case of connection-less protocols like HTTP & COAP when every time a message is sent by a device, the database need to be accessed for device registration in addition to credentials. By introducing such a property in the credentials, this could be avoided as anyway credentials are to be retrieved.

**Comment by sophokles73** [comment]
> n case of connection-less protocols like HTTP & COAP when every time a message is sent by a device, the database need to be accessed for device registration in addition to credentials. By introducing such a property in the credentials, this could be avoided as anyway credentials are to be retrieved.

The protocol adapters (locally) cache the responses from the Credentials service so I guess this wouldn't be much of an issue as the Credentials service will be queried every couple of minutes only anyway ...

**Comment by sophokles73** [comment]
@kaniyan can this be closed?

**Comment by kaniyan** [comment]
> @kaniyan can this be closed?

Currently I am working on documentation. After this we can close this issue.

**Comment by fkaltner** [comment]
@kaniyan I think undoing an auto-provisioned device also may have another unwanted side-effect: the benefit of auto-provisioning feature is that devices just start sending new messages without having to register the device first. Say at the time the very first message is sent, the connection to the messaging network in Hono is interrupted. Then the device would get an error. Probably it would try to redeliver the message. In case of MQTT those retries can be pretty "aggressive", so we may end up creating and removing the device all the time which may increase load on the database of the device registry in use.
