### ISSUE TITLE
Provide means to provide a TTL value for Events published to MQTT Adapter

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#267]
A device should have a way to indicate a time-to-live (TTL) for an event it publishes to Hono's Event API using the MQTT Adapter.

**Comment by pellmann** [comment]
If we set TTL for AMQP, we need to be sure, that this is handled as expected from all involved intermediaries. I think this is not handled by Hono Messaging and I am not sure about the Dispatch Router (?). From the AMQP spec for TTL:

> Duration in milliseconds for which the message is to be considered "live". If this is set then a message expiration time will be computed based on the time of arrival at an intermediary. Messages that live longer than their expiration time will be discarded (or dead lettered). When a message is transmitted by an intermediary that was received with a ttl, the transmitted message's header SHOULD contain a ttl that is computed as the difference between the current time and the formerly computed message expiration time, i.e., the reduced ttl, so that messages will eventually die if they end up in a delivery loop.

For my understanding TTL is more important for command and control and maybe we should think about it together with this? WDYT?

**Comment by ppatierno** [comment]
First of all, I can say that the dispatch router doesn't handle the TTL property. The router doesn't support the "store and forward" mechanism as a broker so the TTL doesn't make sense, because it means to count the time before message is delivered so it means "storing" something that isn't supported by the router.
The Hono messaging doesn't handle it as well and I agree on that.
Only the broker (Artemis) handles TTL.

I think that TTL is important for command and control but even useful for events.
Because we have a queue storing events and the consumer could be offline, it's better to have a mechanism to get rid of "old" events if it doesn't make sense when the consumer comes back online (this is the same concept as what happens with command & control with a really "old" command).

**Comment by ppatierno** [comment]
Regarding the MQTT adapter we know that our supported protocol version 3.1.1 doesn't have something like the TTL (they added the "publication expiry interval" in the next v5).
I think that the only way is to add such value (as any other property) as a sort of "property bag" at the end of the topic as it happens for HTTP query string : 

/telemetry/DEFAULT_TENANT?ttl=10

**Comment by pellmann** [comment]
I also think the property bag option would be the best, if we want to have this feature in the (3.1.1) MQTT adapter. An other possible solution could be an option in the device registry - so you have different TTL for different devices or tenants, maybe for different endpoints.

**Comment by pellmann** [comment]
@ppatierno  - my understanding of the paragraph in the AMQP spec was not, that this would be only true for an intermediary, who stores the message. But you think so, right?

So you would expect, that with e.g. a ttl=1 and a delivery time of 2 ms in hono and 2 ms in dispatch router, the message should be delivered to the consumer and no one of the intermediaries should discard it?

**Comment by ppatierno** [comment]
Chatting with some other AMQP experts in my team it seems we have a problem on the meaning of the TTL ...

If the client (C) specifies a TTL = 1000 it doesn't mean that the TTL at destination (D) will be 1000; it's true only when you have a simple connection C -> D.
If you have hops (intermediaries) between C and D, the TTL at D can be less than the TTL set by C.
Every intermediary (I) has to decrement the received TTL by the time the message spent on I.
In our case we have C -> Hono (H) -> Router (R) -> D so two intermediaries.

Today we are sure that H and R don't touch the TTL so even if it's against the spec we could assume it's ok if H and R just forward message without delay : so today we'll have TTL by C = TTL on D (which is what the client expects).

The right thing to do should be using the "creation-time" and "absolute-expiry-time" properties.
They are immutable and should be set by C.
A reasonable solution to be aligned with spec could be having H sets TTL = absolute-expiry-time - creation-time (just before sending the message). Then the router doesn't touch it and the TTL will arrive with a client desired value to D.
Of course it's an assumption that we can do with this kind of deployment but what if Hono is deployed on something different with more intermediaries which handles the TTL reducing it ?

**Comment by sophokles73** [comment]
fixed via #1524
