### ISSUE TITLE
Status of the Demo certs

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#2678]
Since we have demo certificates and the files for creating them in the _packages_ project, I wonder what the status of the demo certificates in this project is. Where are the certificates supposed to be used? Are we committed to keeping the creation script in sync manually between both projects?

**Comment by sophokles73** [comment]
>  wonder what the status of the demo certificates in this project is

Which project are you referring to by *this project*?

> Where are the certificates supposed to be used?

We use the demo certs for running Hono's unit and integration tests. The Hono chart in the *IoT Packages* project uses the demo certs for TLS enabling the containers' external network endpoints.

**Comment by b-abel** [comment]
@sophokles73 Thank you for your explanation. My understanding is now that the _demo_ certs in Hono are currently more like _test_ certificates. Therefore we do not necessarily need to keep the creation scripts in sync with the ones in the _IoT Packages_ project, but rather tailor them to the needs of the tests in Hono.

**Comment by b-abel** [comment]
What originally got me thinking about this was that Hono's demo certs are configured as _truststore_ in the CLI. This makes little sense if these certificates are not usually used anywhere outside of automated tests.

**Comment by sophokles73** [comment]
> What originally got me thinking about this was that Hono's demo certs are configured as truststore in the CLI.

This is from the time when the deployment scripts for Hono were also part of the Hono project itself. With the chart having been moved to the IoT Packages project, the CLI would rather need to be configured with the trust store containing the CAs of the Hono installation at hand. That might be the (example) certs for the Hono chart or the certs that a user has configured to use when deploying Hono with the chart.

**Comment by sophokles73** [comment]
The Hono Getting Started guides already take this into account.
