### ISSUE TITLE
Enable reporting of jaeger client metrics for quarkus images

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2694]
The `quarkus.jaeger.metrics.enabled` property has to be set to `true` here - see https://github.com/eclipse/hono/pull/2655#discussion_r633283019.

First test have revealed that this doesn't seem to be enough. Also adding the `quarkus-jaeger-deployment` dependency doesn't help here.

**Comment by sophokles73** [comment]
My understanding of the description of the Quarkus property
> Whether or not metrics are published in case a metrics extension is present.

is that it will only be evaluated if there is a Quarkus metrics extension has been added to the project (which we haven't).

**Comment by calohmn** [comment]
This has already been implemented in Hono 1.10.0 via #2861. See also https://github.com/eclipse/hono/pull/3181#discussion_r837058090.
