### ISSUE TITLE
Remove support for Micrometer Graphite/InfluxDB

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#2695]
To my knowledge there has not been anybody using the Graphite nor InfluxDB based Micrometer registry ever. FMPOV we can therefore simply remove the corresponding profiles and dependencies.

WDYT @calohmn @kaniyan @dejanb @ctron

**Comment by calohmn** [comment]
+1. They also currently don't work with the quarkus images, I guess.

**Comment by kaniyan** [comment]
+1
