### ISSUE TITLE
Device Registration API : address for receiver

### ISSUE THREAD

**Issue by ppatierno** [eclipse/hono#27]
In order to send the register/deregister operation command, the "registration" address for the sender seems to be ok.
In order to receive the related reply, the receiver should be attached on a different address.
We could add the "reply-to" property inside the register/deregister message (i.e the client which send the request could define it like something "registration/<uuid>", ...). On that address, Hono will sent the response on the executed operation.

The same is valid for the operation "Retrieve information about a registered device"

**Comment by sophokles73** [comment]
From my point of view usign the *reply-to* mechanism seems to mainly be intended to support kind of a *synchronous* message exchange, i.e. a client sending a request and synchronously (often blocking as well) waiting for the reply. I don't think that this the (primary) way the API will/should be used, e.g. I rather imagine an application doing the registering as part of an automated provisioning process where many devices are registered in batch mode and later (when the replies come in) are *checked off* a list.
I am also not so much in favor of allowing clients to trigger the creation of resources within our infrastructure which seems to be implied when using a dynamic reply address (if using durable messages at least).
As part of Hono's [Resource Model](../wiki/Security) we have also defined a single management endpoint *per tenant* so it seems acceptable/reasonable to me to provide a single reply-to address for all management API messages.

**Comment by ppatierno** [comment]
I agree with you @sophokles73 but we need a different endpoint for reply and not the same request "registration" address. We have to add it to the Resource Model.

Just to be precise providing reply-to doesn't mean synchronous. This mechanism is used a lot in messaging systems and all works asynchronously and decoupled. It's used just to say to the other part where we'll get the reply but it doesn't mean that we'll do that immediately after sending request.

Btw, agree with you on a single endpoint for replies and avoiding resource creation "on fly".

**Comment by hekonsek** [comment]
I agree with Paolo. I also believe that having an option to specify the response address could be useful. You can specify always the same reply address, but for many cases you would like to inspect particular address for registration confirmation, without filtering the messages from a single queue.

What do you think, Kai?

**Comment by sophokles73** [comment]
I am not sold yet. Let's postpone this discussion to the time we start to actually implement the API. If we can *lay off* the handling of multiple reply-to addresses to e.g. the DIspatch Router or an underlying  broker then I think I am fine with it. If it would require complex management of connections and links within Hono Server I'd rather not go down that road ...
Sounds fair?

**Comment by hekonsek** [comment]
OK. Let's keep this issue open.

**Comment by dguggemos** [comment]
I updated the [documentation](https://github.com/eclipse/hono/wiki/Device-Registration-API) to match the current state of the implementation which in short is: 

- a request to the Device Registration API must contain a *reply-to* property where the response should be sent to
- the *correlation-id* of the response contains either the *message-id* or the *correlation-id* of the original message (I think you remember the discussion...)

So from my point of view we could close this issue or did I miss something?
