### ISSUE TITLE
Get device registration returns incorrect status

### ISSUE THREAD

**Issue by kaniyan** [eclipse/hono#2700]
Device registration information contains status properties namely `auto-provisioned` and `auto-provisioning-notification-sent` to indicate if a device has been auto-provisioned and a corresponding notification has been sent or not. Whenever device registration information is retrieved, the value of the these properties are always _false_ even though they are _true_ in the underlying database.

These properties are used to decide if an auto-provisioning event is to be sent or not. Incorrect values impact sending of auto-provisioning events.

**Comment by kaniyan** [comment]
This has been closed via #2699.

**Comment by sophokles73** [comment]
@kaniyan  please also back-port this to 1.8.x and 1.7.x if applicable ...
