### ISSUE TITLE
Command Router: endless "Enable Command Routing" loop

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2705]
We've encountered a scenario, where an "Enable Command Routing" invocation in the Command Router (see #2576) resulted in an endless loop, trying to invoke the command consumer registration for a large list of tenants again and again.

The scenario included a few subsequent "Enable Command Routing" requests with a lot of tenants (several hundred entries all in all, also caused by #2704 in connection with already deleted test tenants).
This resulted in many "get Tenant" invocations, which eventually led to a `org.eclipse.hono.client.ServerErrorException: no credit available for sending request` exception.
The problem is that this caused the corresponding tenant to be again put into the queue of tenants for which "get Tenant" and "register command consumer" was to be invoked (as part of a retry mechanism).
As there is no delay in processing implemented here, the situation could never recover, leading to constant high CPU usage and errors in processing the single incoming "register command consumer" Command Router API requests for yet uncached tenants.
Also the Jaeger Agent was put under high load, leading to most of the tracing spans to get dropped.
(This made it difficult to analyze the original exception, as there is no log output here).

An indication of the problem in the Jaeger UI was that there was no "re-enable command routing for tenants" entry listed in the operations combo box, as this span never got finished.

**Comment by sophokles73** [comment]
@calohmn If I understand correctly, then the root issue is that there are (many) test tenants that do not exist anymore and which are therefore endlessly re-scheduled in the loop, right?

**Comment by calohmn** [comment]
@sophokles73 No, the non-existing tenants result in `ClientErrorExceptions`, meaning there is no retry for that tenant.

There are 2 problems FMPOV: 
- There is no limit to the retry mechanism, so that any re-occuring 500 or 503 error for example will result in endless retries.
- There is no delay in the tenants queue processing, meaning that there may be a "no credit available" error if there are lots of (yet uncached) tenants in the queue. And there is no delay in between retries. This would be relevant in case the device registry AMQP connection is temporarily not there for example.

**Comment by sophokles73** [comment]
@calohmn are you working on this already or should I take a shot?

**Comment by calohmn** [comment]
@sophokles73 I started with some ideas about adding a retry delay.

<details>
<summary>details</summary>

~~~
    @Override
    public Future<CommandRouterResult> enableCommandRouting(final List<String> tenantIds, final Span span) {
        Objects.requireNonNull(tenantIds);
        final List<String> tenantIdsToUse = new LinkedList<>(tenantIds);
        tenantIdsToUse.removeAll(tenantsToEnableRetriesMap.keySet());
        addToTenantQueueAndStartProcessingIfNeeded(tenantIdsToUse, span);
        return Future.succeededFuture(CommandRouterResult.from(HttpURLConnection.HTTP_NO_CONTENT));
    }

    private void addToTenantQueueAndStartProcessingIfNeeded(final List<String> tenantIds, final Span span) {
        final boolean isProcessingRequired = tenantsToEnable.isEmpty();
        tenantsToEnable.addAll(tenantIds);
        if (isProcessingRequired) {
            final Span processingSpan = tracer.buildSpan("re-enable command routing for tenants")
                    .addReference(References.FOLLOWS_FROM, span != null ? span.context() : null)
                    .start();
            processTenantQueue(new ConcurrentHashSet<>(), processingSpan);
        }
    }

    private void processTenantQueue(final Set<String> processedTenants, final Span parentSpan) {
        final String tenantId = tenantsToEnable.poll();
        if (tenantId == null) {
            parentSpan.finish();
            if (!tenantsToEnableRetriesMap.isEmpty()) {
                tenantsToEnableRetryTimer = vertx.setTimer(TENANT_QUEUE_RETRY_DELAY_MILLIS, tid -> {
                    if (!tenantsToEnableRetriesMap.isEmpty()) {
                        final List<String> tenantIds = new LinkedList<>(tenantsToEnableRetriesMap.keySet());
                        addToTenantQueueAndStartProcessingIfNeeded(tenantIds, null);
                    }
                });
            }
            return;
        }
        context.runOnContext(go -> {
            if (processedTenants.contains(tenantId)) {
                parentSpan.log(Map.of(
                        Fields.MESSAGE, "skipping tenant, already processed ...",
                        TracingHelper.TAG_TENANT_ID.getKey(), tenantId));
            } else {
                final Span span = tracer.buildSpan("re-enable command routing for tenant")
                        .addReference(References.CHILD_OF, parentSpan.context())
                        .withTag(TracingHelper.TAG_TENANT_ID, tenantId)
                        .start();
                tenantClient.get(tenantId, span.context())
                    .map(tenantObject -> commandConsumerFactories.getClient(tenantObject))
                    .map(factory -> factory.createCommandConsumer(tenantId, span.context()))
                    .onSuccess(ok -> {
                        span.log("successfully created command consumer");
                        processedTenants.add(tenantId);
                    })
                    .onFailure(t -> {
                        LOG.info("processTenantQueue: failed to create command consumer for tenant {}", tenantId, t);
                        TracingHelper.logError(span, "failed to create command consumer", t);
                        if (t instanceof ServerErrorException) {
                            // add to extra queue in order to retry at a later time
                            span.log("marking tenant for later re-try to create command consumer");
                            tenantsToEnableRetriesMap.compute(tenantId, (key, oldValue) -> {
                                if (oldValue == null) {
                                    return TENANT_ENABLE_RETRIES;
                                }
                                return oldValue > 0 ? oldValue - 1 : null;
                            });
                        }
                    })
                    .onComplete(r -> span.finish());
            }
            processTenantQueue(processedTenants, parentSpan);
        });
    }

~~~

</details>

But in order to prevent the "no credits" error, some more changes are probably needed. So, if you want to work on this, that's fine with me.

**Comment by sophokles73** [comment]
> As there is no delay in processing implemented here, the situation could never recover, leading to constant high CPU usage and errors in processing the single incoming "register command consumer" Command Router API requests for yet uncached tenants.

I do not see why the situation should not recover here. If the client (the Command Router in this case) does not have any credit left then it simply doesn't send the request to the Tenant service but adds the request to the end of the queue to be retried later on. Over time, the client will get credit again from the Tenant service and can then invoke the get Tenant operation and successfully re-establish the command consumer connection, right? So, over time all command consumers should get re-established. It might take some time, depending on the number of tenant IDs and the capacity of the Tenant service, but eventually, everything should be fine. Do you have any indication that in the situation that you had experienced, the number of queued tenant IDs indeed never got smaller?

**Comment by sophokles73** [comment]
The only issue I currently see is that the processingSpan is finished only after the last command consumer has been re-established. Until then, a lot of attempts will likely be made and be logged to the processingSpan. Maybe this causes some problems within the tracing implementation.

**Comment by calohmn** [comment]
> Over time, the client will get credit again from the Tenant service and can then invoke the get Tenant operation and successfully re-establish the command consumer connection, right?

The picture isn't totally clear there.

I can only say that
- a heap dump of the command router showed the `tenantsToEnable` list to have over 1000 entries (container having run with high CPU usage for at least 2-3 days)
- the LoRa adapters have invoked the "Enable Command Routing" operation every 6 hours. The last batch of these invocations has added 60 distinct tenants to the `tenantsToEnable` list, it seems. (With batch I mean 4 invocations - 2 pods with 2 vert.x instances, some unnecessary duplicates there.)
- not only the "Enable Command Routing" processing logic but also single incoming "register command consumer" Command Router API requests (for yet uncached tenants) are waiting for and consuming the credits.

Here is a screenshot with a Command Router trace from when the LoRa adapter and Command Router when they had just been restarted (ie. no requests with deleted tenants anymore)

![grafik](https://user-images.githubusercontent.com/891931/121009133-19fc8980-c794-11eb-95b9-98c8575ad9dd.png)

This shows the fact that many "get Tenant" requests are done almost simultaneously.

**Comment by calohmn** [comment]
It looks like the bug is actually in the `ProtonBasedTenantClient` here.

I've had a closer look at the heap dump from when the Command Router was under high load.
The `CommandRouterServiceImpl` uses a `ProtonBasedTenantClient` which has a `pendingRequests` field.

![grafik](https://user-images.githubusercontent.com/891931/121125389-c8510f00-c826-11eb-88f9-4993aeaee2f0.png)

What is striking here is that the `pendingRequests` map contains 176 _completed_ Futures, all with the "no credits" exception.

In the `ProtonBasedTenantClient#addResultHandler` implementation, a request that fails immediately (without asynchronous decoupling), like with the "no credits" scenario, will first remove a `pendingRequests` map entry (nothing to remove at that point) and then add the already failed Future.

This will cause the subsequent `tenantClient#get` invocations in the `processTenantQueue` method to all use that failed Future - without checking if credits have actually been added again in the meantime.

I've created #2710 to fix this.

**Comment by sophokles73** [comment]
@calohmn can this be closed?

**Comment by calohmn** [comment]
Yes.
