### ISSUE TITLE
Document compatibility of Kafka versions

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#2706]
While Hono's APIs for Kafka only require at least Kafka version `1.0` (brokers and clients), Hono's clients require a much newer version. 

I found the following to be a concise summary of the rules that determine the compatibility of Kafka clients and brokers ([Source](https://docs.cloudera.com/cdp-private-cloud-base/7.1.6/kafka-managing/topics/kafka-manage-client-broker-comp.html)):

> * Newer Kafka brokers can talk to older Kafka clients. The reverse is not true: older Kafka brokers cannot talk to newer Kafka clients.
> * Changes in either the major part or the minor part of the upstream version major.minor determines whether the client and broker are compatible. Differences among the maintenance versions are not considered when determining compatibility.

Hono's clients (in Protocol Adapters, Command Router, Device Registry, ...) use the Kafka clients with a version determined by the Vert.x Kafka client. Currently, Kafka clients in version 2.6 are used. This effectively requires that the brokers have at least version 2.6 too.

This information needs to be added to Hono's documentation. 
A good place for this would probably be a separate "Kafka" page in the admin guide.

**Comment by iamrsaravana** [comment]
Yes. Documentation is not up to date. Kafka based API introduced version 1.7. but still we are not able to use it because of  no proper documentation.

**Comment by sophokles73** [comment]
> A good place for this would probably be a separate "Kafka" page in the admin guide.

FMPOV we should add it to the already existing [Hono Kafka Client Configuration](https://www.eclipse.org/hono/docs/admin-guide/hono-kafka-client-configuration/) where we already describe how the client needs to be configured in order to use a given broker. IMHO this kind of additional information would fit in here quite well.
