### ISSUE TITLE
Provide default implementation of getPort/getInsecurePort in AbstractServiceBase

### ISSUE THREAD

**Issue by sysexcontrol** [eclipse/hono#271]
Currently, these methods are implemented identically in three places:
- AbstractVertxBasedHttpProtocolAdapter
- VertxBasedMqttProtocolAdapter
- AmqpServiceBase

These implementations should instead be overrideable methods in the common AbstractServiceBase IMHO to eliminate the code duplication.
Currently they are abstract methods in this class.

**Comment by sophokles73** [comment]
I do not really see how we would do that, since the server instance (from which the *actual* port is queried) differs in all cases, i.e. it is an `MqttServer` or an `HttpServer` or a `ProtonServer`, depending on the particular protocol used.

**Comment by sysexcontrol** [comment]
That is no doubt the difficulty - resulting from that the 3 different server classes do not implement an interface nor inherit from a common base class, but only all implementing the exact same method "getActualPort()".

One way would be using reflection, a second way would be encapsulation in some kind of HonoMqttServer/HonoHttpServer/HonoProtonServer with the implementation of an interface (which I would both consider an overkill).

Another possibility is to let the child classes only implement the getter for the actual port.
This is what is provided in the pull request as a proposal to get rid of the always reported code duplication.

Please have a look, IMHO it improves the abstraction - WDYT?

**Comment by sophokles73** [comment]
@sysexcontrol can this be closed?

**Comment by sysexcontrol** [comment]
Done with 9df2635.
