### ISSUE TITLE
Add max payload size to all device registry requests

### ISSUE THREAD

**Issue by mbaeuerle** [eclipse/hono#2718]
Currently there is no payload limit for requests to the device registry. Therefore it would be possible to upload and store multible megabytes worth of data, inside a device json for example.
To prevent that, a config property could be added which defines the maximum payload size for device registry requests.
This could work in a similar way to the `maxPayloadSize` config property already present for up/downstream messages.

**Comment by sophokles73** [comment]
sounds reasonable

**Comment by sophokles73** [comment]
I have taken a closer look at the code and found that the registry implementations' */tenant* and */credentials* related resources already support limiting the request payload. The configuration variable to use for setting the limit is `HONO_REGISTRY_HTTP_MAXPAYLOAD_SIZE`. However, this property is not documented yet.

I will also add support for limiting the payload size to the */devices* resources and update the documentation accordingly.

**Comment by mbaeuerle** [comment]
@sophokles73 thank you very much!
