### ISSUE TITLE
Documentation: Styling of "table of contents" is wrong

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#2725]
Currently, the styling of the ToC on the pages of the documentation is wrong: the first level is intended instead of the second. The cause is in the Hugo theme: see https://github.com/matcornic/hugo-theme-learn/issues/378 for a description and a screenshot. The issue is already fixed there, but there has not been a release since then. I created an issue to ask about the planned timeline: https://github.com/matcornic/hugo-theme-learn/issues/502.

**Comment by b-abel** [comment]
I assume that we need to wait for the next release of the theme (instead of just checking it out from the latest commit). If we need a released version for the Eclipse process, I guess we can neither apply the patch provided in the repository there to our css files. Or would that be an option for a temporary workaround?

**Comment by sophokles73** [comment]
If we can rectify the situation by simply taking over the corresponding CSS changes into our own stylesheet, then I see no problem with doing so. You should then add a comment to these additions in the Hono stylesheet indicating where the code came from and how it is licensed.

**Comment by b-abel** [comment]
> If we can rectify the situation by simply taking over the corresponding CSS changes into our own stylesheet, then I see no problem with doing so. You should then add a comment to these additions in the Hono stylesheet indicating where the code came from and how it is licensed.
> 
> @b-abel any opinion on this?

That should work. I'll have a closer look at it. 

Btw: I don't think that versioning matters here because the styling of the documentation is always taken from the "master" branch.
