### ISSUE TITLE
Migrate Sandbox deployment to Helm chart

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#2727]
The Sandbox currently uses a shell script and the Docker command line client to deploy Hono to Docker Swarm running on the Sandbox machine. It would be much more convenient and more consistent with our general approach for deploying Hono if we could run Kubernetes on the Sandbox (e.g. [k3s](https://k3s.io/)) and then simply use the Hono Helm chart to deploy.

**Comment by sophokles73** [comment]
@b-abel I think we should get this done before adding kafka to the Sandbox (#2683).

**Comment by b-abel** [comment]
I would like to work on this issue.
