### ISSUE TITLE
Read truststore password from file

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#2731]
Currently, a password can be provided for a JKS truststore file by setting the property `trustStorePassword`. The client configuration should additionally allow providing a path to a file that contains the password. This would allow reading it from a separate secret instead of putting it plain into a configuration file.

**Comment by sophokles73** [comment]
Sounds reasonable to me :+1:

**Comment by sophokles73** [comment]
@b-abel are you working on this? Otherwise, I could give it a shot ...

**Comment by b-abel** [comment]
I have not started yet. Feel free to take it.
