### ISSUE TITLE
Secret in credential can be added without password

### ISSUE THREAD

**Issue by mbaeuerle** [eclipse/hono#2735]
Observed behavior:
It is possible to create a credential with secrets which do not contain a password.

Expected behavior:
Creating a credential without any passwords should result in an error.

Steps to reproduce:

1. Make sure the credential is empty. If the credential is not empty to my knowledge everything works as expected
  ![grafik](https://user-images.githubusercontent.com/1345394/122050032-5d35a880-cde3-11eb-8ba5-78cf2eba381e.png)
1. Create a credential with one or more secrets just containing an arbitrary `id` and some other field, e.g. `not-after`
      ```json
      [
          {
              "type": "hashed-password",
              "auth-id": "auth-my-test-device",
              "secrets": [
                  {
                      "id": "1065959d-8541-4c71-b475-58f248464bfd",
                      "not-after": "2020-12-31T23:00:00Z"
                  },
                  {
                      "id": "26ffefe0-c0ec-4d42-af2a-70c4e0925a61",
                      "not-after": "2020-12-31T23:00:00Z"
                  }
              ],
              "enabled": true
          }
      ]
      ```
    ![grafik](https://user-images.githubusercontent.com/1345394/122050072-69216a80-cde3-11eb-83b6-7c68a9add701.png)
1. The request succeeds and the credential is stored in the database without passwords
  ![grafik](https://user-images.githubusercontent.com/1345394/122050101-70e10f00-cde3-11eb-9511-c81429bfdd1d.png)

**Comment by sophokles73** [comment]
This problem also exists in the JDBC based and the file based registry.
