### ISSUE TITLE
Skip setLastKnownGatewayForDevice request if device only has one 'via' gateway

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2738]
The 'lastKnownGateway' information is only relevant if a device has more than one gateway defined in its `via` property.
See the list of 3 rules here on how a command target gateway is determined:
https://www.eclipse.org/hono/docs/api/device-connection/#get-command-handling-protocol-adapter-instances-for-device

Therefore the `setLastKnownGatewayForDevice` request could be skipped if the device only has one `via` gateway. This results in less traffic to the Command Router.

**Comment by calohmn** [comment]
One edge scenario affected by such a change would be:
- Device initially only has one `via` gateway and sends telemetry/event messages.
- Device gets a further `via` gateways, doesn't send any new telemetry/event messages yet.
- Multiple of these via gateways then subscribe for commands.

This means a command targeted at the device would be forwarded to whichever of the gateways is first in the `via` list, whereas without the change of the `setLastKnownGatewayForDevice` handling, the initially set and already used `via` gateway would be the target. 
The first telemetry/event message sent after the `via` gateways change will then set the 'lastKnownGateway' of course and cause it to be used as target gateway for commands.

Since this case would be equivalent to one where the device hasn't sent any telemetry/event messages at all yet, I think we can require the device to send at least one telemetry/event message after adding a 2nd `via` gateway here as well.

**Comment by calohmn** [comment]
@sophokles73 Any objections/comments on the above?

**Comment by sophokles73** [comment]
> Multiple of these via gateways then subscribe for commands.

Do they all subscribe for commands of the specific device or for commands for the gateway device?

**Comment by calohmn** [comment]
> Do they all subscribe for commands of the specific device or for commands for the gateway device?

The latter. They subscribe for commands using just their gateway id - i.e. they subscribe to receive commands from _all_ devices that are configured to work with that gateway.

**Comment by sophokles73** [comment]
> Since this case would be equivalent to one where the device hasn't sent any telemetry/event messages at all yet, I think we can require the device to send at least one telemetry/event message after adding a 2nd via gateway here as well.

Sounds reasonable to me.

**Comment by calohmn** [comment]
Fixed via 4d50688482896c26fd708361f2e69233534069ef.
