### ISSUE TITLE
Hono Client for multiple tenants

### ISSUE THREAD

**Issue by mrclbrchr** [eclipse/hono#2757]
Yet i wasnt able to find a answer for my question in the documentation. Is it possible to start a client for multiple tenants?
Instead of "--tenant.id=tenant", something like "--tenant.id=tenant1, tenant2". I tried it that way but it wont work. Is it even possible?

**Comment by sophokles73** [comment]
Technically this is possible. However, the CLI doesn't support it. The client would need to open multiple receiver links, one for each tenant. For simple consumption of messages this shouldn't be a big thing. However, if you also want to use the CLI for sending commands then additional changes would need to be required because then you would also need to specify the tenant ID of the device that the command should be sent to.

**Comment by mrclbrchr** [comment]
Alright, lets say i'm an administrator and want to controll and monitor multiple devices in multiples tenants. What would be your approach to do this? Start multiple clients or configure one client to manage all tenants?

**Comment by sophokles73** [comment]
Can you tell me a little bit about what you have in mind when you say *monitoring* and *controlling*? If you only want to send an occasional command to an arbitrary device, then I guess starting the CLI when necessary should work. Or am I mistaken?

**Comment by mrclbrchr** [comment]
I think about multiple devices like 3d-printers that are running all the time. I want to monitor if one of them sends any event like for example "overheating" and react to that event with a command. For this purpose the CLI must run all the time i think. The question is, do i need to run mutiple CLI's for multiple tenants, or can i just run one CLI for my tenants, which is optimally connected to a frontend.

Maybe i get some basic idea behind hono wrong, but this is approximately the way i think about to use hono.

**Comment by sophokles73** [comment]
What you are talking about is an *application* on top of Hono. The CLI has been created mainly for demonstration purposes as part of the Getting Started guide. For your use case you should implement your own application based on an existing AMQP 1.0 client for your preferred programming language and then interact with Hono's north bound Telemetry, Event and C&C APIs. If you are using Java then you can use Hono's application client in the `clients/application-amqp` module which provides an easy to use interface to create telemetry and event consumers and for sending commands to arbitrary devices.
