### ISSUE TITLE
Memory leak in Hono components on AMQP connection re-connects

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#276]
We have observed a memory leak caused by AMQP connection re-connects.

To reproduce:
- Start the Hono components
- Take a heap dump of the REST adapter
- Stop the device registry application
- notice the re-connect attempt log messages in the REST adapter
```
14:30:04.204 [vert.x-eventloop-thread-0] INFO  o.e.hono.client.impl.HonoClientImpl - attempting to re-connect to server [localhost:26671]
14:30:04.204 [vert.x-eventloop-thread-0] INFO  o.e.h.c.ConnectionFactoryImpl - connecting to AMQP 1.0 container [amqps://localhost:26671]
14:30:04.707 [vert.x-eventloop-thread-0] INFO  o.e.h.c.ConnectionFactoryImpl - can't connect to AMQP 1.0 container [amqps://localhost:26671]: Verbindungsaufbau abgelehnt: localhost/127.0.0.1:26671
14:30:04.707 [vert.x-eventloop-thread-0] DEBUG o.e.hono.client.impl.HonoClientImpl - scheduling re-connect attempt ...
14:30:05.208 [vert.x-eventloop-thread-0] INFO  o.e.hono.client.impl.HonoClientImpl - attempting to re-connect to server [localhost:26671]
14:30:05.208 [vert.x-eventloop-thread-0] INFO  o.e.h.c.ConnectionFactoryImpl - connecting to AMQP 1.0 container [amqps://localhost:26671]
14:30:05.713 [vert.x-eventloop-thread-0] INFO  o.e.h.c.ConnectionFactoryImpl - can't connect to AMQP 1.0 container [amqps://localhost:26671]: Verbindungsaufbau abgelehnt: localhost/127.0.0.1:26671
14:30:05.713 [vert.x-eventloop-thread-0] DEBUG o.e.hono.client.impl.HonoClientImpl - scheduling re-connect attempt ...
14:30:06.213 [vert.x-eventloop-thread-0] INFO  o.e.hono.client.impl.HonoClientImpl - attempting to re-connect to server [localhost:26671]
14:30:06.213 [vert.x-eventloop-thread-0] INFO  o.e.h.c.ConnectionFactoryImpl - connecting to AMQP 1.0 container [amqps://localhost:26671]
14:30:06.717 [vert.x-eventloop-thread-0] INFO  o.e.h.c.ConnectionFactoryImpl - can't connect to AMQP 1.0 container [amqps://localhost:26671]: Verbindungsaufbau abgelehnt: localhost/127.0.0.1:26671
14:30:06.717 [vert.x-eventloop-thread-0] DEBUG o.e.hono.client.impl.HonoClientImpl - scheduling re-connect attempt ...
```
- After some time take another heap dump of the REST adapter and compare it to the first one
=> this shows increased memory consumption

The heap dump diff shows additional `io.vertx.core.net.impl.NetClientImpl` objects (one for each connection attempt). They look like the main part of the memory leak.

**Comment by calohmn** [comment]
First thoughts:
The `io.vertx.core.net.impl.NetClientImpl` objects are still referenced in the `closeHooks` of the Vertx context.

To me it looks like there may be an issue in `io.vertx.proton.impl.ProtonClientImpl.connect()` / `connectNetClient()`.
The created `NetClient` instance is not closed there in case of a failed connection attempt. Thereby the instance is not removed from the Vertx context `closeHooks` and can't be garbage-collected.
If there is consensus on this explanation, we could file a vertx-proton issue for this.

I currently don't see a workaround in Hono. Letting the reconnects be handled by `NetClientImpl` (by using `protonClientOptions.setReconnectAttempts(-1)`) would undo the fix for #209.

**Comment by sophokles73** [comment]
Your analysis looks very reasonable to me. I agree that invoking `NetclientImpl.close()` in the *failing* part of the connection handler in `ProtonClientImpl.connectNetClient()` should properly unregister the *closeHook* from the `Context` and prevent the memory leak.
Luckily, this seems not to be a problem when an existing connection fails as the underlying `ProtonTransport` will invoke `NetClient.close()` in this case.

> I currently don't see a workaround in Hono. Letting the reconnects be handled by NetClientImpl (by using protonClientOptions.setReconnectAttempts(-1)) would undo the fix for #209.

I also do not think that this would actually solve the problem because the `NetClient` is also not closed if the SASL handshake fails (e.g. due to incorrect credentials) :-(

Do you want to open an issue with the *vertx-proton* project or would you like me to do that. I can also create a PR since I am already *cleared* for contributing to Vert.x ...

**Comment by calohmn** [comment]
Yes, would be good if you could open an issue on vertx-proton and create a PR, thanks.

**Comment by sophokles73** [comment]
I have created https://github.com/vert-x3/vertx-proton/issues/51 and pull request https://github.com/vert-x3/vertx-proton/pull/52 

No one seems to have taken a look at it yet, though :-(

**Comment by sophokles73** [comment]
Upstream [proton-vertx pull request](https://github.com/vert-x3/vertx-proton/pull/52) has been merged.
This issue will be fixed once we update to vert.x 3.5.0.

**Comment by sophokles73** [comment]
closing with #383
