### ISSUE TITLE
DEPENDENCIES file content not up to date

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2772]
Invoking `create_dependencies_list.sh` with the newest dash licenses snapshot jar produces a change in the DEPENDENCIES file.
Besides an added entry (`net.i2p.crypto/eddsa/0.3.0, CC0, approved`), the entry for `org.apache.sshd/sshd-common/2.3.0` gets changed from `approved` to `restricted`.

`sshd.common` is a dependency of `org.wildfly.security:wildfly-elytron-auth-util` and `org.wildfly.security:wildfly-elytron-x500-cert` (used by `org.infinispan:infinispan-client-hotrod`).

**Comment by sophokles73** [comment]
I have created a [PR with Clearlydefined](https://github.com/clearlydefined/curated-data/pull/13222) to add the missing declared license information.

**Comment by sophokles73** [comment]
I created another [PR with Clearlydefined](https://github.com/clearlydefined/curated-data/pull/13275) to add the missing source location.

**Comment by calohmn** [comment]
I've added the missing `net.i2p.crypto/eddsa/0.3.0` entry.
