### ISSUE TITLE
"created" timestamp is lost upon update of a tenant in Hono's device registry

### ISSUE THREAD

**Issue by alex-ellwein** [eclipse/hono#2774]
If a tenant is created in Hono's MongoDB device registry via POST request, there is a "created" field containing the timestamp of creation in "tenants" collection. Pretty fine.

Upon update of the same tenant via PUT request, an "updatedOn" field appears -- however, the "created" field has then been deleted, so i suppose this is a bug or an undesired behavior, because the historical information, since when the tenant exists, has been lost.

This behavior doesn't apply to "devices" collection.

Regarding "device-credentials" collection (as there is only PUT, but no POST operation): 
there is an "updateOn" timestamp created upon modification of a device credential, which is maybe fine from the REST perspective, but wouldn't it be more clear to keep track on _creation_ as well as _modification_ of the database entity in separate timestamp fields?

**Comment by sophokles73** [comment]
Which version of Hono are you referring to?

**Comment by alex-ellwein** [comment]
> Which version of Hono are you referring to?

I've tested with Hono 1.8.1.

**Comment by calohmn** [comment]
Looking at the Device Registry Management API spec, there is also a difference in the `Tenant` and `Device` structures in this respect: The `Device` schema defines the `status` entry with `created` and `updated` fields, while the `Tenant` schema doesn't have that.

**Comment by sophokles73** [comment]
> Regarding "device-credentials" collection (as there is only PUT, but no POST operation):
there is an "updateOn" timestamp created upon modification of a device credential, which is maybe fine from the REST perspective, but wouldn't it be more clear to keep track on creation as well as modification of the database entity in separate timestamp fields?

See #2698

**Comment by sophokles73** [comment]
> Upon update of the same tenant via PUT request, an "updatedOn" field appears -- however, the "created" field has then been deleted, so i suppose this is a bug or an undesired behavior, because the historical information, since when the tenant exists, has been lost.

This is indeed undesired, even if we (currently) do not expose this information to clients as @calohmn pointed out.
