### ISSUE TITLE
Integration tests module compilation takes very long

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2777]
Something that has baffled me for quite a while is how long it takes to compile the "tests" Hono module with the integration tests.
On my machine that takes about 60 seconds (for just 63 classes)!
This means there is quite some patience needed when developing integration tests.

I've tried to narrow it down a bit, to see which classes take up the most time.
Removing everything except the `org.eclipse.hono.tests.http.HttpTestBase` class and classes it depends on leads to a compilation time of still about 40 seconds.

Testing some more, the compilation time is increased by several seconds when duplicating the last `assertThat` line multiple times here:
https://github.com/eclipse/hono/blob/969751067daf83a1e4f6dfde5b0b0c7f7cbe5c13/tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java#L1300-L1310

Narrowing it down to just this piece of code
```
    public void test(final java.util.Optional<java.util.List<String>> listOptional) {
        listOptional
                .map(list -> {
                    verify(() -> {
                        org.assertj.core.api.Assertions.assertThat(list.get(1)).isNull();
                        org.assertj.core.api.Assertions.assertThat(list.get(1)).isNull();
                        org.assertj.core.api.Assertions.assertThat(list.get(1)).isNull();
                        org.assertj.core.api.Assertions.assertThat(list.get(1)).isNull();
                        org.assertj.core.api.Assertions.assertThat(list.get(1)).isNull();
                        org.assertj.core.api.Assertions.assertThat(list.get(1)).isNull();
                        org.assertj.core.api.Assertions.assertThat(list.get(1)).isNull();
                        org.assertj.core.api.Assertions.assertThat(list.get(1)).isNull();
                        org.assertj.core.api.Assertions.assertThat(list.get(1)).isNull();
                        org.assertj.core.api.Assertions.assertThat(list.get(1)).isNull();
                    });
                    return list;
                });
    }
    private void verify(final Runnable block) {
        //
    }
```
I arrive at 6 seconds:
```
javac -verbose -version -cp [path]/assertj-core-3.20.2.jar:. Test.java
javac 14.0.2
...
[total 6073ms]
```
Trying out other JDK (versions), there is no significant difference.

This all leads me to believe that the combination of lambdas + generics + the heavily overloaded AssertJ `Assertions.assertThat` methods lead to these long compilation times. Using the latest AssertJ version (3.20.2) has brought no difference.

I've done some tests using an AssertJ alternative, [Truth](https://truth.dev/) by the Guava team.
By just changing the static import
`import static org.assertj.core.api.Assertions.assertThat;`
to
`import static com.google.common.truth.Truth.assertThat;`
in the aforementioned `HttpTestBase` class (and removing two `.as("[something]")` expressions from `assertThat` invocations), the compilation time of the tests module drops from 60s to 30s.

Using Truth `assertThat` in (almost) all test classes leads to a compilation time of 12s!
This requires changes to some assertions, since Truth `assertThat` doesn't have that many assertion methods to choose from.
(For the test I kept these AssertJ assertions, e.g. `assertThat(resp.getAuthorizedGateways()).containsExactlyElementsOf(via);`)

Other possible options here:
- Use AssertJ `AssertionsForClassTypes.assertThat` instead of `Assertions.assertThat` where applicable. This has already brought down the compilation time of the tests module to 35s.
- Use Hamcrest instead. This requires quite some changes though, since the invocation is a bit different: 
`assertThat(a, equalTo(b));` vs AssertJ `assertThat(a).isEqualTo(b);`. I've done no tests here yet.

I would suggest going for Truth here, since the above mentioned combination of `assertThat` with lambdas and also with generics is something we use oftentimes in the Hono code. And the migration from AssertJ doesn't seem to need much of an effort.

I can prepare a PR for the `tests` module to show the needed changes.

@sophokles73, @dejanb, @kaniyan, @ctron WDYT?

**Comment by sophokles73** [comment]
Great analysis :+1: 
Getting down the compilation time is always welcome. AFAIK I do not really care whether we use *Truth* or *AssertJ* but I became quite fond of the syntax used by AssertJ's *assertThat* methods so replacing them with the very similar versions from *Truth* shouldn't be an issue for me.

**Comment by calohmn** [comment]
I've added #2779 to adapt the integration tests module. 
Going further, other modules should be adapted as well - changing "Device Registry Base" brings down compilation time from 33s to 6s.

**Comment by calohmn** [comment]
Tests have been adapted to use `Truth` `assertThat()` now.
