### ISSUE TITLE
Reduce code duplication in AmqpServiceBase child classes

### ISSUE THREAD

**Issue by sysexcontrol** [eclipse/hono#278]
Currently, the services with an AMQP interface inherit from AmqpServiceBase and implement the methods "handleReceiverOpen()/handleSenderOpen()" completely identical.

This should be eliminated by offering the (overwritable) implementation in the base class.

**Comment by sophokles73** [comment]
sounds reasonable :-)

**Comment by sysexcontrol** [comment]
Fixed in 6fba09c.
