### ISSUE TITLE
HTTP401 while trying to use certs

### ISSUE THREAD

**Issue by mrclbrchr** [eclipse/hono#2783]
Hello,

im trying to use certificates to authorize my connection. Im starting my CLI with the hono.http.keyPath und hono.http.certPath option. But if i try to send some http telemetry data, i recieve error 401, and im wondering why. Ive created a device named "3D-Printer-1" and my command looks like followed:
```console
curl -i --cert demo-certs/certs/device-3D-Printer-1-cert.pem --key demo-certs/certs/device-3D-Printer-1-key.pem --cacert demo-certs/certs/t.pem -H 'content-type: application/json' --data-binary '{"temp": 5}' http://10.98.140.92:8080/telemetry
```

**Comment by sophokles73** [comment]
You are posting your data to the non-TLS port of the HTTP adapter (`http://10.98.140.92:8080/telemetry`). You should try to post to the TLS secured port using https as the protocol, probably `https://10.98.140.92:8443/telemetry` ...

**Comment by mrclbrchr** [comment]
Hmm now im facing the problem that i recieve error 404. Are there any requirements while creating the device and tenant that i maybe missed out?

**Comment by sophokles73** [comment]
Have you registered x509 credentials for the device?

**Comment by mrclbrchr** [comment]
Maybe not correctly.
Is this guide https://blog.bosch-si.com/developer/x-509-based-device-authentication-in-eclipse-hono/ still viable?

**Comment by sophokles73** [comment]
It would be very helpful to see the debug output of the HTTP adapter that you are posting to. We could then determine, if this is indeed a credentials related problem or something else.

**Comment by mrclbrchr** [comment]
Currently i'm trying another approach. I'm following the guide mentioned above, but now im facing the following issue, which is probably not that difficult, but i did not solve it yet.

```console
curl -i -H 'Content-Type: application/json' -H 'Expect:' --data @tenant.json http://10.111.159.47:28080/v1/tenants
```

The content of the json is exactly as described in the guide, but im just getting HTTP400 followed by the message "request does not contain a valid Tenant object".

**Comment by sophokles73** [comment]
Can you please post the content of the `tenant.json` file?

**Comment by mrclbrchr** [comment]
```json5
{"tenant-id":"TEST", "trusted-ca":[{"subject-dn":"CN=Sensors,O=ACME Inc.", "public-key":"MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAwTVbTPnD3Rt63oD/W6Rg7EhyYuTUP7wnF19G+pVZ0RA9qvn4xpVr8iCH3nF3PmPyF/9HZZz6k4CxC24FL6PHzoIwu/z2uKMuIekvOQNquMneWXv8G9vcTDdn20V/EGFtuuq+QPAG+USR/h/IfRdjvSkaXtYfGm7I04EZj7OWs9RIepFmznV8EWHOXs7nbSVt9PlTlo2j7jLN+MimvTjTZBOJb2BAOxw+SqieNtwSis8gQuwgG8j5ktdZicJ431XTo0IMjgDH0NvlQbqnDZD7fKPsRt6FZvqrlprnGZZ68kyLpqLE73+KvAMeCRCyGOP2LmkObq36PtUXTRBDu0JM3asuwUSJpXQGiUwsIpSRS5uh+FEGskIqS/YsWyK0tqKwrm7+jPYpXPYPvXJYpFIcSav4otM1viZ6XrSPgSTPYMU1VgmGogQeOhbP2iPm6Mk53/+n6X1JRBevI6IvGkcpM8Xj7MBUSXgHRZ9ko2cYtfnMPLJCjZSLCKP7TQ4Ygj7abXI8ua3srHXzblIQiqfs90c8b449rmbuUUE6V5Wt/rZSc0tQphH7s8nqUbV1YG7uJNMdwEK9tJS2Yl274gHKyYsFcBPA/ohWDAI+iDB7rEXj8PUvRdiw4pY2v/EJ0ewKBhUNwnC5AK/d5ouyVPtR3ebHUSRLMINJ/F38Kf9JNuECAwEAAQ=="}]}
```

**Comment by sophokles73** [comment]
You may want to refer to the [Device Registry Management API](https://www.eclipse.org/hono/docs/api/management/#/tenants/createTenant) for the syntax of the create tenant request payload.

In particular, the trusted CA needs to have *not-before* and *not-after* properties.

The following payload works as desired:
```json
{
  "trusted-ca":[{
    "subject-dn":"CN=Sensors,O=ACME Inc.",
    "public-key":"MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAwTVbTPnD3Rt63oD/W6Rg7EhyYuTUP7wnF19G+pVZ0RA9qvn4xpVr8iCH3nF3PmPyF/9HZZz6k4CxC24FL6PHzoIwu/z2uKMuIekvOQNquMneWXv8G9vcTDdn20V/EGFtuuq+QPAG+USR/h/IfRdjvSkaXtYfGm7I04EZj7OWs9RIepFmznV8EWHOXs7nbSVt9PlTlo2j7jLN+MimvTjTZBOJb2BAOxw+SqieNtwSis8gQuwgG8j5ktdZicJ431XTo0IMjgDH0NvlQbqnDZD7fKPsRt6FZvqrlprnGZZ68kyLpqLE73+KvAMeCRCyGOP2LmkObq36PtUXTRBDu0JM3asuwUSJpXQGiUwsIpSRS5uh+FEGskIqS/YsWyK0tqKwrm7+jPYpXPYPvXJYpFIcSav4otM1viZ6XrSPgSTPYMU1VgmGogQeOhbP2iPm6Mk53/+n6X1JRBevI6IvGkcpM8Xj7MBUSXgHRZ9ko2cYtfnMPLJCjZSLCKP7TQ4Ygj7abXI8ua3srHXzblIQiqfs90c8b449rmbuUUE6V5Wt/rZSc0tQphH7s8nqUbV1YG7uJNMdwEK9tJS2Yl274gHKyYsFcBPA/ohWDAI+iDB7rEXj8PUvRdiw4pY2v/EJ0ewKBhUNwnC5AK/d5ouyVPtR3ebHUSRLMINJ/F38Kf9JNuECAwEAAQ==",
    "not-before": "2021-07-21T12:00:00+02:00",
    "not-after": "2022-07-21T12:00:00+02:00"
  }] 
}
```

**Comment by mrclbrchr** [comment]
That helped me a lot, somehow i missed out the little checkmark for the schema so i could not mention what was wrong.
Unfortunately im facing another problem now. I want to Register the device’s subject DN like followed:
```shell
curl -i -H 'Content-Type: application/json' --data-binary @credentials.json http://10.111.159.47:28080/v1/credentials/$TENANT/hot-fuzz
```
Im recieving HTTP405, Method Not Allowed. Im a bit confused, because this error isnt even mentioned in the Device Registry Management API.

**Comment by sophokles73** [comment]
It is not mentioned because the combination of that resource with the HTTP POST verb is not part of the API.
You need to use HTTP PUT with this resource.
```sh
curl -X PUT -i -H ...
```

**Comment by mrclbrchr** [comment]
Okay, i just referred to the guide. Now im getting Error400 again, Invalid JSON, while my JSON looks like this:
```JSON5
{"device-id": "hot-fuzz", "type": "x509-cert", "auth-id": "CN=Hot Fuzz Device,O=IHBR Comp.", "secrets": [{}]}
```
As far as i can see, tpye, auth-id and secrets is required, so im wondering why my JSON is invalid.

**Comment by sophokles73** [comment]
The request payload needs to be a JSON array (you may also want to refer to the example given in the API):
```json
[
  {
    "device-id": "hot-fuzz",
    "type": "x509-cert",
    "auth-id": "CN=Hot Fuzz Device,O=IHBR Comp.",
    "secrets": [{}]
  }
]
```

**Comment by mrclbrchr** [comment]
First of all thanks for your advice, it helped me a lot!
But unfortunately there is one problem left.

If i want to publish a message with mosquitto or curl, i get similiar erros which say that theres a problem with my certificates. 
To be exact: Error: Problem setting TLS options: File not found.
Thats the error messaging i recieve if i want to use mosquitto_pub like followed:
```shell
mosquitto_pub -h 10.105.26.91 -p 8883 --capath /etc/ssl/certs --cert /etc/ssl/certs/device-cert.pem --key /etc/ssl/certs/device-key.pem -q 1 -t telemetry -m "Hello there"
```
I try it while im in the certs folder, and ls proofs the existance of device-cert and device-key. So my assumption is that somethings wrong with the ca certificate. The problem is, im not sure which certificate is my ca certificate? 

Referring to the bosch guide mentioned above, it should be the tenant-cert.pem? But even if i replace the --capath and set --cafile for the tenant-cert, im still getting this error.

**Comment by sophokles73** [comment]
The `--capath` param is for specifying the certificates that the client (mosquitto_pub) trusts when establishing the TLS connection. Unless your `/etc/ssl/certs` folder contains the root CA of your Hono installation, this will not work.
The easiest way to move forward would be to simply tell mosquitto_pub to trust any certificate presented by the server by means of using the `--insecure` parameter. You might also want to refer to moquitto_pub's man page: `man mosquitto_pub` ...

**Comment by mrclbrchr** [comment]
That took me a step further. Now im starting my client as followed and try to publish telemetry data
´´´shell
sudo java -jar hono-cli-1.8.1-exec.jar --hono.client.host=10.109.207.187 --hono.client.port=15672 --hono.client.username=consumer@HONO --hono.client.password=verysecret --hono.mqtt.keyPath=/home/marcel/Code/Certs-Test --hono.mqtt.certPath=/home/marcel/Code/Certs-Test --spring.profiles.active=receiver --tenant.id=@Marcel
```
```shell
sudo mosquitto_pub -h 10.105.26.91 -p 8883 --insecure --cert /home/marcel/Code/Certs-Test/device-cert.pem --key /home/marcel/Code/Certs-Test/device-key.pem -q 1 -t telemetry -m "Hello there" --debug
```

But im recieving the following error message:
```shell
Client (null) sending CONNECT
OpenSSL Error[0]: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Error: A TLS error occurred.
```

Maybe you saw this error before or know something that could cause this, if no i think i can close the issue and go on on my own. Feels like theres one last little thing which is not correct. Anyway, i really appreciate your help, it helped me a lot.

**Comment by sophokles73** [comment]
Ok, it looks like mosquitto_pub still requires the trust anchors as
> --insecure
           When using certificate based encryption, this option disables verification of the server hostname in the server certificate.

only disables checking of the server cert's host name. So you will need to specify the trusted certificates using the `--cafile` option, passing it the path to Hono's trust store from the `demo-certs/certs` folder ...

**Comment by mrclbrchr** [comment]
Im a bit confused right now which one is the cafile. 

Referring to the create_certs.sh code, which one is exactly my ca certificate ?

And where from does my hono adapter know that this is the right ca certificate?

Unfortunately my knowloedge but certificates is just very basic and i cant transfer it to honos working method.

**Comment by sophokles73** [comment]
You should be able to use the `trusted-certs.pem` file.

**Comment by mrclbrchr** [comment]
Yes i deployed it using Helm. But what do you mean by using the right one? Theres just one.

**Comment by mrclbrchr** [comment]
HTTP isnt working as well. Maybe its caused by the wrong key format? I remember a problem i had where my .pem contained PKCS8 formut but traditional rsa was requirred.

I can show you my curl logs with and without -k flag. Maybe thats helps.

```shell
curl -i --cacert /home/marcel/Code/Certs-Test/trusted-certs.pem --cert /home/marcel/Code/Certs-Test/device-cert.pem --key /home/marcel/Code/Certs-Test/device-key.pem -H 'Content-Type: plain/text' -H 'Expect:' --data-binary 'Hello there' https://10.98.140.92:8443/telemetry -v 
*   Trying 10.98.140.92:8443...
* TCP_NODELAY set
* Connected to 10.98.140.92 (10.98.140.92) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /home/marcel/Code/Certs-Test/trusted-certs.pem
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, decrypt error (563):
* error:0D0C5006:asn1 encoding routines:ASN1_item_verify:EVP lib
* Closing connection 0
curl: (35) error:0D0C5006:asn1 encoding routines:ASN1_item_verify:EVP lib
```
```shell
curl -i --cacert /home/marcel/Code/Certs-Test/trusted-certs.pem --cert /home/marcel/Code/Certs-Test/device-cert.pem --key /home/marcel/Code/Certs-Test/device-key.pem -H 'Content-Type: plain/text' -H 'Expect:' --data-binary 'Hello there' https://10.98.140.92:8443/telemetry -v -k
*   Trying 10.98.140.92:8443...
* TCP_NODELAY set
* Connected to 10.98.140.92 (10.98.140.92) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /home/marcel/Code/Certs-Test/trusted-certs.pem
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS handshake, CERT verify (15):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=CA; L=Ottawa; O=Eclipse IoT; OU=Hono; CN=http-adapter
*  start date: Jan 26 13:13:26 2021 GMT
*  expire date: Jan 26 13:13:26 2022 GMT
*  issuer: C=CA; L=Ottawa; O=Eclipse IoT; OU=Hono; CN=ca
*  SSL certificate verify result: certificate signature failure (7), continuing anyway.
> POST /telemetry HTTP/1.1
> Host: 10.98.140.92:8443
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Type: plain/text
> Content-Length: 11
> 
* upload completely sent off: 11 out of 11 bytes
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
HTTP/1.1 401 Unauthorized
< content-type: text/plain; charset=utf-8
content-type: text/plain; charset=utf-8
< content-length: 39
content-length: 39

< 
* Connection #0 to host 10.98.140.92 left intact
validation of device certificate failed
```

**Comment by sophokles73** [comment]
> Yes i deployed it using Helm. But what do you mean by using the right one? Theres just one.

The Helm chart comes with its own set of demo-certs which it uses when deploying. The trusted CA store can be found at https://github.com/eclipse/packages/tree/master/charts/hono/example/certs ...

**Comment by mrclbrchr** [comment]
Okay that took my a step further. Unfortunately just my error log changed.

```shell
curl -i --cacert /home/marcel/Code/Hono/eclipse/packages/charts/hono/example/certs/trusted-certs.pem --cert /home/marcel/Code/Certs-Test/device-cert.pem --key /home/marcel/Code/Certs-Test/device-key.pem -H 'Content-Type: plain/text' -H 'Expect:' --data-binary 'Hello there' https://10.98.140.92:8443/telemetry -v
*   Trying 10.98.140.92:8443...
* TCP_NODELAY set
* Connected to 10.98.140.92 (10.98.140.92) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /home/marcel/Code/Hono/eclipse/packages/charts/hono/example/certs/trusted-certs.pem
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS handshake, CERT verify (15):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=CA; L=Ottawa; O=Eclipse IoT; OU=Hono; CN=http-adapter
*  start date: Jan 26 13:13:26 2021 GMT
*  expire date: Jan 26 13:13:26 2022 GMT
*  subjectAltName does not match 10.98.140.92
* SSL: no alternative certificate subject name matches target host name '10.98.140.92'
* Closing connection 0
* TLSv1.3 (OUT), TLS alert, close notify (256):
curl: (60) SSL: no alternative certificate subject name matches target host name '10.98.140.92'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by sophokles73** [comment]
As the error message suggests, curl is not able to match the server certificate's subject with the host name used in the request URL. This comes as no surprise as we had no clue about your IP address when we created the server certificate.
In order to prevent curl from doing this check, use the `--insecure` parameter ...
