### ISSUE TITLE
MongoDB device registry does not delete devices & credentials on tenant delete

### ISSUE THREAD

**Issue by mbaeuerle** [eclipse/hono#2793]
The MongoDB device registry currently does not delete devices and credentials belonging to a tenant that gets deleted.
These devices and credentials are then orphaned in the database and it's not possible to delete them afterwards.

That's because the `delete` operation on devices of the device management API checks for the existance of the tenant.

It's  not possible to create a device without creating the tenant first therefore it seems like a device is bound to the tenant lifecycle just as a device-credential is bound to the device lifecycle.

The proposal is therefore to cascade the deletion of the tenant so devices (and credentials) belonging to it are deleted as well.

If the loose coupling of tenants and devices in Hono is wanted, a workaround could be the introduction of a new API request:
"delete all devices" which deletes all the devices and credentials of a tenant (preferrably this operation should also work when the tenant is already gone).

**Comment by sophokles73** [comment]
> The proposal is therefore to cascade the deletion of the tenant so devices (and credentials) belonging to it are deleted as well.

I guess this will only properly work when using a transaction spanning multiple collections (tenants, devices, credentials). Otherwise we could end up in a situation where some objects still exist while others are already removed. The vertx-mongo-client 3.9.x which we are using does not support such transactions so I guess this is not a (short term) option.

> If the loose coupling of tenants and devices in Hono is wanted, a workaround could be the introduction of a new API request:
"delete all devices" which deletes all the devices and credentials of a tenant (preferably this operation should also work when the tenant is already gone).

This would also pose the risk of ending up in an inconsistent state. However, we are already accepting this risk when deleting a single device where we also (try to) delete the device's credentials. So I guess this would be the more viable (short term) option.

**Comment by Christian-Schmid** [comment]
The hono mongo device registry offers a ``GET ​/devices​/{tenantId}`` operation with a query parameter ``filterJson``, which can be used to search for devices matching a certain criteria. 

A possible solution for the use case described in this issue could also be to introduce a ``DELETE​/devices​/{tenantId}`` operation with the same ``filterJson`` parameter.
Such operation could also be useful for other use cases, e.g. mass delete of all disabled devices etc. 

Like this there wouldn't be the need for a "delete all devices" operation and maybe the existing logic can be reused.
Furthermore this would also not require a transaction between the ``tenant`` and ``devices collection``.

**Comment by sophokles73** [comment]
> These devices and credentials are then orphaned in the database and it's not possible to delete them afterwards. That's because the delete operation on devices of the device management API checks for the existance of the tenant.

This is probably a bug in itself, i.e. it should always be possible to delete an entity without the check for the existence of the tenant.

> A possible solution for the use case described in this issue could also be to introduce a DELETE​/devices​/{tenantId} operation with the same filterJson parameter. Such operation could also be useful for other use cases, e.g. mass delete of all disabled devices etc.

Would it be sufficient to have a `DELETE /devices/{tenantId}` at first, which can be used to simply remove *all* devices of a tenant (regardless of whether the tenant had been deleted already or not)?

**Comment by Christian-Schmid** [comment]
> Would it be sufficient to have a DELETE /devices/{tenantId} at first, which can be used to simply remove all devices of a tenant (regardless of whether the tenant had been deleted already or not)?

For our use case this would be sufficient. I just proposed the other idea in case some code could already be reused for that purpose. This use case however we don't have yet (and I don't expect it in the nearby future either)

> Even if step 2 fails, you could still (manually) remove them later on from the DB but devices are never able to log in again with these credentials.

Agreed. From time to time we could perform a check if there are orphaned entries and remove them.

**Comment by sophokles73** [comment]
Great, then let's move on in that direction.
