### ISSUE TITLE
Make validation of authIds configurable

### ISSUE THREAD

**Issue by fkaltner** [eclipse/hono#2797]
Validation of device ids is already configurable by `HONO_REGISTRY_HTTP_DEVICE_ID_PATTERN`/ `--hono.registry.http.deviceIdPattern` as described on https://www.eclipse.org/hono/docs/admin-guide/mongodb-device-registry-config/

In order to match different notions of validity for authIds as well it would be useful to make validation of authIds also configurable.

**Comment by sophokles73** [comment]
I suppose we are talking about the auth-id pattern used in *hashed-password* credentials, right?

**Comment by sophokles73** [comment]
@fkaltner this seems to be a duplicate of #2559

**Comment by fkaltner** [comment]
Yes, that is true. Since it was there before, I'll close this one.
