### ISSUE TITLE
Device Registration API : correlation-id

### ISSUE THREAD

**Issue by ppatierno** [eclipse/hono#28]
The correlation-id inside the register/deregister operation message doesn't make sense to me.

In order to correlate request and response we have to use the correlation-id only inside the response. This id should match with the message-id which is inside the request.
It's something like the command and control, so message-id and correlation-id descriptions could be got from there.

It means to me : 
- adding message-id into the register/deregister operation message
- removing correlation-id from the register/deregister operation message
- better description for the correlation-id inside the reply

The same is valid for the operation "Retrieve information about a registered device"

**Comment by dguggemos** [comment]
You're right, I changed it accordingly. Thanks!

**Comment by sophokles73** [comment]
Can we close this then?

**Comment by dguggemos** [comment]
Now it is, my first push was not successful...

**Comment by ppatierno** [comment]
Now it's ok. I close it.
