### ISSUE TITLE
is it possible to choose/assign topic name in kafkabased messaging system.

### ISSUE THREAD

**Issue by iamrsaravana** [eclipse/hono#2800]
Dear committer,

under Single tenant we are planning to register different type of devices(Car, Dumper, lorry, etc)with huge quantity. Based of business use cases,we feel that each device data has to process independently. is it possible to send data to different topics(based on device type) from hono.  if so, could share the steps

**Comment by sophokles73** [comment]
No, this not possible. However, you could do this kind of routing using something like Apache Camel
