### ISSUE TITLE
Remove Device Connection service

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2818]
The Device Connection service has been marked as deprecated since Hono 1.5.0.
Its successor, the Command Router service is marked as fully supported since Hono 1.7.0.

When using Quarkus, the Device Connection service implementation can't already be used anymore.

I think we should remove the Device Connection service in one of the next versions.

**Comment by sophokles73** [comment]
FMPOV we can remove this component in any of the upcoming minor or major versions as it has never been public API anyway but merely a helper API for implementing command routing internally.

@dejanb @ctron @kaniyan WDYT?

**Comment by sophokles73** [comment]
In the [1.7.0 release review information](https://projects.eclipse.org/projects/iot.hono/releases/1.7.0/review), where we announced the deprecation of the Device Connection service, we actually indicated to remove it in Hono 2.0.0. So I guess we should better stick to that plan ...

**Comment by calohmn** [comment]
Also to be removed here is the `forceCommandRerouting` parameter in `IntegrationTestSupport`.
