### ISSUE TITLE
Mongo DB Device Registry: Allow configuration of auth provider properties  

### ISSUE THREAD

**Issue by Christian-Schmid** [eclipse/hono#2826]
Hi,

when using the MongoDB based Device Registry it's possible to enable basic auth using the ``authenticationRequired`` property which will utilize [vertx-auth-mongo](https://vertx.io/docs/vertx-auth-mongo/java/).

This auth provider allows configuration of various [options](https://vertx.io/docs/apidocs/io/vertx/ext/auth/mongo/MongoAuthenticationOptions.html).  (For our use case especially the ``#collectionName``  would be of interest.) 

As far as I can see the configuration is not yet possible, as the provider is initialized with an empty options object:

```org.eclipse.hono.deviceregistry.mongodb.ApplicationConfig#createAuthHandler```:
````
  return BasicAuthHandler.create(
          MongoAuth.create(mongoClient(), new JsonObject()),
          httpServerProperties().getRealm());
````

Would it be possible to make this properties somehow available in the hono registry configuration?

Thanks!
Chris

**Comment by sophokles73** [comment]
@Christian-Schmid I guess making the collection name configurable shouldn't be a big thing. Are you ok with keeping the default hashing strategy? How are you currently adding users and their passwords to the collection?

**Comment by Christian-Schmid** [comment]
Hi, 
that would be cool. 
Keeping the default strategy is fine for us, as we use the default one. 
Our users are added in a Jenkins scripted pipeline.

Thanks Chris

**Comment by sophokles73** [comment]
That means you are creating SHA512 hashes using a salt per user which you keep in the *salt* property, right?

**Comment by Christian-Schmid** [comment]
> That means you are creating SHA512 hashes using a salt per user which you keep in the _salt_ property, right?

Exactly like this
