### ISSUE TITLE
Separate configuration properties for frontend and backend verticles

### ISSUE THREAD

**Issue by sysexcontrol** [eclipse/hono#283]
Currently, the configuration properties for configuring the ports, certificate paths etc. **and** the properties for the implementing classes, like file path for the file based implementations or a database descriptor for a database implementation are all contained in one property class.

This is not appropriate for configuring several protocols in one microservice (e.g. amqp and http) , since the frontend properties need to be available per protocol but the properties for the backend verticles remain the same.
Thus they should be splitted into two config classes.

This holds true for the device registry and the authorization service.

**Comment by sophokles73** [comment]
fixed in eabe115d79dd23377f1298f6a39a6d70ac71cdb8
