### ISSUE TITLE
KafkaProducerFactory#sharedProducerFactory potentially misleading in how producers are shared

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2836]
Consider a scenario where you want to use different `KafkaApplicationClient` instances, each working with Kafka configuration properties containing different login credentials, giving access to a specific set of topics.

For a these clients you need a `KafkaProducerFactory` instance. The intuitive way to create one is to use `KafkaProducerFactory#sharedProducerFactory`.

Even when using different `KafkaProducerFactory` instances created with that method for these client, the created Kafka producers with the same name still are getting shared between all client instances. This results in authentication/authorisation errors when working with the producers.

This is especially a problem concerning the command producer created in the `KafkaApplicationClient` because it gets created with a fixed name ("command-sender").

Caching of Kafka producer instances for such a scenario should only be done per `KafkaProducerFactory` instance.

EDIT: made it clear that this is about the `KafkaProducerFactory#sharedProducerFactory` factory method.

**Comment by calohmn** [comment]
When using `KafkaProducerFactory#sharedProducerFactory()`, producers seem to get cached in two locations.
Once in the Hono `CachingKafkaProducerFactory` and once in vert.x Kafka `KafkaProducerImpl` (via `KafkaProducer.createShared`).
I wonder whether that's necessary.

**Comment by b-abel** [comment]
I am not sure that I fully get the problem. The point of _shared producers_ is that the same producer name returns you the same KafkaProducer instance to enable sharing of producers between verticles. This behavior is provided by the Vert.x Kafka client (`KafkaProducerImpl`) and makes a lot of sense at least from a protocol adapter's POV. For the problem at hand, I guess `KafkaProducerFactory#sharedProducerFactory()` had been used, which is exactly meant to share producers by name. What keeps you from providing a different `KafkaProducerFactory` implementation?

**Comment by b-abel** [comment]
> When using `KafkaProducerFactory#sharedProducerFactory()`, producers seem to get cached in two locations.
> Once in the Hono `CachingKafkaProducerFactory` and once in vert.x Kafka `KafkaProducerImpl` (via `KafkaProducer.createShared`).
> I wonder whether that's necessary.

That `CachingKafkaProducerFactory` keeps track of the active producers, allows using other producers than _shared producers_ with a consistent behavior. This is not only useful for testing but might already be the solution for this issue.

**Comment by calohmn** [comment]
> I guess `KafkaProducerFactory#sharedProducerFactory()` had been used, which is exactly meant to share producers by name. What keeps you from providing a different `KafkaProducerFactory` implementation?

The question is, what if I have invoked `KafkaProducerFactory#sharedProducerFactory()` multiple times?
The javadoc speaks of "a new factory" being created, but in essence, these factories are all the same because they use the shared, static state in `KafkaProducerImpl`. I think the javadoc should make that more explicit. 
It looks to me that it doesn't make sense to have multiple `KafkaProducerFactory#sharedProducerFactory()` instances, so in my view that method should better return always the same factory instance (possibly throwing an exception if a different vert.x parameter is used).

I think it also makes sense to provide another factory creation method then: `KafkaProducerFactory#cachingProducerFactory()`.
This method could also use vert.x `KafkaProducer.createShared` - always adding a `KafkaProducerFactory` instance specific prefix to the name parameter of `KafkaProducer.createShared`.

**Comment by calohmn** [comment]
> That `CachingKafkaProducerFactory` keeps track of the active producers, allows using other producers than _shared producers_ with a consistent behavior. This is not only useful for testing but might already be the solution for this issue. 

I just mean the combination of `CachingKafkaProducerFactory` along with a `producerInstanceSupplier` that uses the vert.x `KafkaProducer.createShared` method here - as used by `KafkaProducerFactory#sharedProducerFactory()`.

To me it looks as if `KafkaProducerFactory#sharedProducerFactory(vertx)` (and a new `#cachingProducerFactory(vertx)`) could use a simpler factory implementation that doesn't have the `activeProducers` map. An advantage here would be that you could just invoke `producer.close` to remove it from the cache (not having to use `producerFactory.closeProducer`).

**Comment by b-abel** [comment]
FMPOV the situation is the following:

`KafkaProducerFactory` has an API that has been designed to encapsulate the error handling of Kafka producers that need to be closed when fatal errors occur. The using code (i.e. the class `AbstractKafkaBasedMessageSender`) always fetches a producer with `KafkaProducerFactory#getOrCreateProducer()` to send messages and does not have to care whether it is an existing producer or a newly created one. The factory has to remember the producers to be able to close them.
In a scenario where multiple Verticles are used, it is a good idea to use the [shared producer](https://vertx.io/docs/vertx-kafka-client/java/#_sharing_a_producer) provided by the Vert.x Kafka client. You cannot access the internal state of it, so you need a reference to it to close a producer. The _shared producer_ does the synchronization needed to access it from multiple Verticles, so the factory does not need its own synchronization. Thus, each Verticle can have its own instance of the factory, which issues either _shared_ or "non-shared" producers. The latter is helpful for unit tests. Also, this could be useful for the problem at hand, but unfortunately, I haven't quite grasped the use case yet.

The method `KafkaProducerFactory#sharedProducerFactory()` I consider more as a kind of convenience method (I personally don't like that an interface should know its implementation) for the initial purpose of the code, namely the internal use in the protocol adapters. Maybe the code is too complex or doesn't fit well for use in the northbound client. 

In any case, we should refer prominently to the documentation of the _shared producer_, because its understanding is required when using the code.

Beyond that, what problem do we want to solve here?

**Comment by calohmn** [comment]
As stated in the ticket text, the starting point here is the use of different `KafkaApplicationClient` instances, each geared towards working with different tenants, also regarding login credentials in the given Kafka producer configuration properties.

In order to create a `KafkaApplicationClient`, a `KafkaProducerFactory` instance is needed. 
Since in the above scenario Kafka producers mustn't be shared across `KafkaApplicationClient` instances (there will be errors otherwise), it has become obvious now that the `KafkaProducerFactory#sharedProducerFactory()` factory can't be used here.
So, currently you would have to create a `CachingKafkaProducerFactory` instance with your own `producerInstanceSupplier`, which is a bit cumbersome. 
Therefore I think it would be good to provide a `KafkaProducerFactory` implementation, **where Kafka producers are only cached *per* `KafkaProducerFactory` instance**.

> `KafkaProducerFactory` has an API that has been designed to encapsulate the error handling of Kafka producers that need to be closed when fatal errors occur. The using code (i.e. the class `AbstractKafkaBasedMessageSender`) always fetches a producer with `KafkaProducerFactory#getOrCreateProducer()` to send messages and does not have to care whether it is an existing producer or a newly created one. The factory has to remember the producers to be able to close them.

It seems to me that the `CachingKafkaProducerFactory#activeProducers` Map isn't needed for applying the `exceptionHandler` that does the handling of fatal errors. (And the `exceptionHandler` setter method can be invoked multiple times - there is only one handler being kept.) And the closeHandler set on the producers created in `KafkaProducerImpl` will remove the producer from the list of cached producers in `KafkaProducerImpl`.
Therefore my impression was that a `KafkaProducerFactory#sharedProducerFactory()` implementation with the same features as today could be done without having to keep the `activeProducers` map.
But that would just be an optimization (and a way for not having to use `producerFactory.closeProducer`). The main objective of this issue here is to have a `KafkaProducerFactory` implementation, where Kafka producers are only cached *per* `KafkaProducerFactory` instance.

**Comment by b-abel** [comment]
> The main objective of this issue here is to have a `KafkaProducerFactory` implementation, where Kafka producers are only cached _per_ `KafkaProducerFactory` instance.

The existing implementation of `KafkaProducerFactory` does exactly that. Unless you apply the optimization you proposed before (removing the producers map from it). 

So, the only thing you seem to need is a convenience method that reuturns:

~~~java
new CachingKafkaProducerFactory<K, V>((name, config) -> KafkaProducer.create(vertx, config));
~~~

**Comment by b-abel** [comment]
FMPOV the title of this issue should be changed because `KafkaProducerFactory` instances do not share Kafka producers. It only may contain shared producers, which share state by design. 
It is also not a bug.

**Comment by calohmn** [comment]
I've updated title and issue description.

> So, the only thing you seem to need is a convenience method that reuturns:
`new CachingKafkaProducerFactory<K, V>((name, config) -> KafkaProducer.create(vertx, config));`

Such a method, yes, and updating the `sharedProducerFactory` javadoc, indicating that producers are shared globally.
