### ISSUE TITLE
Command Router: prevent offset commits and record-fetching on topics of deleted tenants

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2838]
Requires #2837 to be implemented first:

Having got the information (via the new internal event API) that a tenant got deleted, the Command Router should skip any offset commits regarding the command topic of that tenant.
This is to prevent delays (because of commit retries of the underlying Kafka client) that would occur if that topic had already been deleted (see [KAFKA-12256](https://issues.apache.org/jira/browse/KAFKA-12256)).

Also, fetching of records for these topic partitions should be prevented (using `consumer.pause(partitions)` - see [here](https://github.com/eclipse/hono/blob/491d3b20234c9cabec1376e8356697c3461d5fc9/clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java#L285)).
It seems that this will at least prevent the
`Received unknown topic or partition error in fetch for partition hono.command.XY-0`
errors that would otherwise be logged after the topic got deleted.

**Comment by calohmn** [comment]
@b-abel I could imagine adding a `AsyncHandlingAutoCommitKafkaConsumer#skipOffsetCommits(String topic)` method ("skip offset commits for currently assigned partitions of the given topic"), which will set a new "skipCommit" flag in the `AsyncHandlingAutoCommitKafkaConsumer#TopicPartitionOffsets` objects corresponding to the topic partitions.

In the `KafkaBasedCommandConsumerFactoryImpl.kafkaConsumer` `OnRebalanceDoneHandler` this `skipOffsetCommits()` method needs to be called again if a topic partition of an already deleted tenant gets re-assigned.
So, yes, I think we should keep track of the deleted tenants. Entries in the corresponding map could expire after some time though (e.g. 2 hours, should be more than `AsyncHandlingAutoCommitKafkaConsumer.DEFAULT_OFFSETS_SKIP_RECOMMIT_PERIOD`).

An edge case would be here if a command router starts just after a tenant got deleted and before the tenant topic gets deleted, so that the command router doesn't get the event. Some more thinking needed on this.

**Comment by calohmn** [comment]
I think we should re-evaluate whether changes are needed here.

> Having got the information (via the new internal event API) that a tenant got deleted, the Command Router should skip any offset commits regarding the command topic of that tenant.
This is to prevent delays (because of commit retries of the underlying Kafka client) that would occur if that topic had already been deleted (see [KAFKA-12256](https://issues.apache.org/jira/browse/KAFKA-12256)).

Before switching to "earliest" as offset reset strategy (see #2931), there were offset commits being done each time a partition got reassigned. Now, this doesn't happen any more.
This means, that offset commit issues because of a deleted tenant can usually only occur, if the tenant topic gets deleted sooner than 5s (i.e. the consumer `auto.commit.interval.ms` config value) after the last message was received by the consumer on the tenant topic.
Therefore I think we could just say that upon deletion of a tenant in the device registry, the tenant topic should be deleted with a delay of at least 5s.

> Also, fetching of records for these topic partitions should be prevented (using `consumer.pause(partitions)` - see [here](https://github.com/eclipse/hono/blob/491d3b20234c9cabec1376e8356697c3461d5fc9/clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java#L285)).
It seems that this will at least prevent the
`Received unknown topic or partition error in fetch for partition hono.command.XY-0`
errors that would otherwise be logged after the topic got deleted.

Here it should be tested first whether the errors in the log really go hand in hand with noticeable delays in the consumer (maybe because of extra metadata refresh requests).

**Comment by sophokles73** [comment]
@calohmn is this still relevant?

**Comment by calohmn** [comment]
I think we can close this for now - there don't seem to be any issues, as long as tenant-topics aren't deleted immediately after a message on the tenant command topic got sent.
