### ISSUE TITLE
Log errors sending event messages on INFO level again

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2842]
In a previous Hono version, errors occurring in the protocol adapter while sending event messages to the AMQP messaging network were logged on INFO level.
See https://github.com/eclipse/hono/commit/f56c69341fcc6967916675da8118de2546361e13#diff-b6aa7231a1e63bab2e1ac43dc820277b4bc3e6b7656faef7c8985f31f6be3c8aR161

With the changes towards using the new client modules (i.e. the AMQP `GenericSenderLink` getting used by adapters now), this isn't done any more.

**Comment by sophokles73** [comment]
Do you see this as a problem? FMPOV we are handling this case properly by returning a corresponding error back to the client/device. I also do not think that we should rely on the log containing these entries to determine a broker error as the comment in the diff suggests. WDYT?

**Comment by calohmn** [comment]
> Do you see this as a problem? FMPOV we are handling this case properly by returning a corresponding error back to the client/device.

This log information is for monitoring the hono components, individual errors sent back to the client/device may otherwise not be available in the logs (on INFO level). Interesting are especially errors like `waiting for delivery update timed out after 1000ms`, indicating an issue with the broker.

> I also do not think that we should rely on the log containing these entries to determine a broker error as the comment in the diff suggests.

In general, I think the first place to determine broker issues would be having monitoring in place concerning the "undeliverable rate" event message metrics. Seeing high values there, the next step could be having a look at log messages like the one suggested here, to get more details about the errors.
