### ISSUE TITLE
Docu: Order User Guides by complexety / relevance

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#2849]
The order in which the user guides are listed in the documentation is the following:

1. MongoDB Based Device Registry
1. JDBC Based Device Registry
1. File Based Device Registry
1. HTTP Adapter
1. MQTT Adapter
1. AMQP Adapter
1. CoAP Adapter
1. Kura Adapter
1. Sigfox Adapter

For new users who are just starting to learn about Hono, it would probably be clearer to start with the protocol adapters and then list the device registries. My proposal is:

1. HTTP Adapter
1. MQTT Adapter
1. AMQP Adapter
1. CoAP Adapter
1. Kura Adapter
1. Sigfox Adapter
1. MongoDB Based Device Registry
1. JDBC Based Device Registry
1. File Based Device Registry

**Comment by sophokles73** [comment]
I guess that depends on your point of view. You could also argue, that any use case will start with registering devices, then the devices can connect to adapters and then you can process the data.
FMPOV we do not need to change the order but if others think that we should, I have no problem with it. However, I would like to point out that personally, I find it irritating if the (well known) structure of the documentation changes all of a sudden. In particular, I find that very confusing with the kubernetes documentation which changes with every release ...

**Comment by sophokles73** [comment]
@calohmn any thoughts?

**Comment by sophokles73** [comment]
I will create a PR for merging the user guide ...

**Comment by sophokles73** [comment]
done in 1.12.x
