### ISSUE TITLE
Bug: TTL in downstream messages with Kafka is in seconds

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#2854]
The [Telemetry API for Kafka](https://www.eclipse.org/hono/docs/api/telemetry-kafka/) defines a _ttl_ header in milliseconds but the Kafka-based downstream sender implementations set the value in seconds.

**Comment by b-abel** [comment]
This bug seems to be in all versions from 1.7.0 on. 
@sophokles73 Do we want to provide the fix also for released versions or do we don't, because the Kafka-based messaging is still a "technical preview" anyway?

**Comment by sophokles73** [comment]
I guess it is sufficient to fix it on master
