### ISSUE TITLE
How to configure log level for "quarkus" image type?

### ISSUE THREAD

**Issue by gongzhao2** [eclipse/hono#2883]
Hello,

we try to deploy 1.10.0 version of Hono on kubernetes cluster by using helm.
We use below honoImagesType:
```
honoImagesType: "quarkus"
```
and we use default applicationProfiles
```
applicationProfiles: "dev"
```
but I still can't see debug logs from mqtt-adapter.

So how canwe configure log level if we choose quarkus image type?

thanks!

**Comment by sophokles73** [comment]
Hi, the Helm chart you are referring to is maintained by the [Eclipse Packages project](https://github.com/eclipse/packages). Can you therefore please post your question there?

Thanks
