### ISSUE TITLE
Add username/password authentication of clients to Telemetry Endpoint

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#29]
Clients connecting to Hono's telemetry endpoint need to be authenticated in order to be able to authorize the upload or retrieval of telemetry data.

We need at least username/password based authentication but we should also support token based authentication, e.g. Json Web Tokens issued via OAuth.

**Comment by sophokles73** [comment]
vertx-proton currently [doesn't support any client authentication using SASL](https://github.com/vert-x3/vertx-proton/issues/18) :-(

I would really like to contribute some changes that would allow for registering a SASL authentication provider in vertx-proton. However, we are (currently) not allowed to contribute code to projects under ASL 2.
 
Maybe some of our RedHat friends can help out? @hekonsek, @dejanb, @ppatierno :-)

**Comment by hekonsek** [comment]
I will try to make this implemented. Stay tuned!

**Comment by sophokles73** [comment]
Cool! You are my hero, @hekonsek ;-)

**Comment by hekonsek** [comment]
I have created pull request for Vert.x Proton to address this issue. Can you take a look at it and tell me what you think?

**Comment by dguggemos** [comment]
@hekonsek I think your pull request made it to the Vert.x Proton release 3.3.2, right? So how do we proceed here? As @sophokles73 said in the initial comment, we need at least plain username/password authentication. So we should implement this for the 0.1 milestone and add token based authentication later?

**Comment by sophokles73** [comment]
I have started to work on a PLAIN implementation of the `SaslAuthenticator` already on a (private) branch. It works nicely so far but I ran into some issues because of the (synchronous) way the API is defined currently. I have created [another issue](https://github.com/vert-x3/vertx-proton/issues/31) for this ...

**Comment by sophokles73** [comment]
For the first milestone we will need to live without username/password based authentication because we currently have no central identity management component that is supported by both Hono Server and Dispatch Router.

**Comment by sophokles73** [comment]
We are somewhat limited in options for using an identity store shared between *Hono server* and *Dispatch Router* by the `Cyrus SASL` lib used by Dispatch Router for performing SASL authentication. In particular, it doesn't support calling out to a URL for verifying credentials. The closest we get to a *shared* credential store is using an SQL DB which Cyrus SASL can use to read passwords in plaintext from :-(
We will need to implement a new auxprop plugin for Cyrus SASL in order to remedy the situation ...
Removing 0.5-M4 label for now.

**Comment by sophokles73** [comment]
This issue is superseded by #54, #261, #262
