### ISSUE TITLE
Handle failure to create Kafka "command_internal" topic

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2910]
A failure to create the Kafka `hono.command_internal.[id]` topic on protocol adapter startup is currently not getting handled.
This causes errors in the Command Router when trying to publish on this topic.

There should be retries on such failures and in general, the adapter shouldn't invoke the `Register command consumer for device` operation of the Command Router API if the topic doesn't exist yet.

**Comment by kaniyan** [comment]
This has been closed via  #2930.
