### ISSUE TITLE
Migrate CoAP adapter to Californium 3.x

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#2922]

**Comment by boaks** [comment]
After applying the migration updates in branch [cali_3_0](https://github.com/bosch-io/hono/tree/cali_3_0) I stumbled over the hono API grants for "configuration files". Though the properties files of Californium are new designed, the old format is not longer supported. I don't consider, that this feature to use Californium.properties for "fine tuning" is widely spread, but it's a possibility for those, who have issues with the default values. For a new Californium release, I would recommend, to retest the "fine-tuning", it may not have the benefits as with the old release.

So, my conclusion therefore is:
Hono can only be updated to Californium 3.0 with the next major hono release.

Any other opinions?

**Comment by sophokles73** [comment]
A potential alternative would be to *migrate* the old property files to the new format implicitly during start up. If that is not an option, then I agree that we should postpone upgrading to Cf 3 to the Hono 2.0.0 release.

**Comment by boaks** [comment]
The point will be:

Don't use the old configuration for the new version of Californium without retesting it.

The expected culprit is the changed behavior of the major Californium 3.0, not the changed configuration file.
e.g.: large number of thread => not longer required and may so turn the old benefit in to a drawback.

Some of that stuff (e.g. number of threads") have already changed during the 2.x development. 
But therefore: switching to 3.0 is ideal to retest the applied fine-tuning.
And therefore, migrating the old file doesn't make too much sense.

**Comment by sophokles73** [comment]
Ok, then let's move this to Hono 2.0.0

**Comment by sophokles73** [comment]
closed via #3179
