### ISSUE TITLE
Quarkus adapter startup fails with Kafka config property having empty string value

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2941]
Trying to deploy a Quarkus-based protocol adapter built using current master, startup fails with this exception:
> ERROR: Failed to start application (with profile prod)
java.util.NoSuchElementException: SRCFG00040: The config property hono.kafka.commonClientConfig."ssl.endpoint.identification.algorithm" is defined as the empty String ("") which the following Converter considered to be null: io.smallrye.config.Converters$BuiltInConverter
at io.smallrye.config.SmallRyeConfig.convertValue(SmallRyeConfig.java:284)
at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:239)
at io.smallrye.config.ConfigMappingProvider.lambda$processLazyMap$0(ConfigMappingProvider.java:540)
at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:844)

The issue can be reproduced with the `QuarkusPropertyBindingTest` unit test (in the `adapter-base-quarkus` module) by adding a property with an empty string value in `adapter-base-quarkus/src/test/resources/application.yaml`.

**Comment by calohmn** [comment]
I thought, using `Map<String, Optional<String>>` as return values in the `KafkaClientOptions` methods would help here, but that causes a `ClassCastException`. I also had no luck with a custom converter. @sophokles73 Any idea here?

**Comment by calohmn** [comment]
When using the IoT Packages Hono helm chart with Kafka parameters, the Kafka config contains this by default:
```
      kafka:
        commonClientConfig:
          ssl.endpoint.identification.algorithm: ""
```
When installing the Helm chart, using Kafka and using the Hono quarkus images from current master, the adapter startup fails with the above exception.
The same kind of error comes when running `QuarkusPropertyBindingTest`, having added a field with an empty string value in `adapter-base-quarkus/src/test/resources/application.yaml`, like this:
```
[...]
  kafka:
    commonClientConfig:
      empty: ""
[...]
```
So, the question is how to make it possible that the Maps returned by the `KafkaClientOptions` class can contain empty-string values.

**Comment by sophokles73** [comment]
Well, we could also simply prevent the empty string being used as the property value, couldn't we? I think it works if you simply omit the `""` ...

**Comment by calohmn** [comment]
When omitting the `""`, there won't be the `NoSuchElementException`, but then the map entry value will be `null`.
And this has different semantics and will also cause the adapter startup to fail. 
The intention is here to explicitly set the "ssl.endpoint.identification.algorithm" property value to the empty string in order to override the default value (`https`). It looks like a `null` value would let the default value be used.

There are long discussions on the handling of empty string values in SmallRye/Eclipse MicroProfile Config - see https://github.com/eclipse/microprofile-config/issues/671. Unfortunately, there currently doesn't seem to be a straightforward way to differentiate between a String with a `null` value and an empty String.

I've created #2944 now to apply the solution mentioned in https://github.com/eclipse/microprofile-config/issues/671 - using the `ConfigValue` API.
