### ISSUE TITLE
Support usage of logback.xml in quarkus images

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2957]
It would be good if the quarkus images also supported logger configuration via `logback.xml`, just like the spring-boot images.

Can be done via the Quarkus Logging Logback extension:
https://github.com/quarkiverse/quarkus-logging-logback

**Comment by sophokles73** [comment]
@calohmn  I currently do not see why that would be desirable/needed. The Helm chart supports configuration of the logging levels via additional yaml files that can be configured by means of chart properties.

**Comment by calohmn** [comment]
@sophokles73 Yes, this issue is obsolete now that all Hono components are Quarkus based.
