### ISSUE TITLE
Improve validation of registration assertions

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#296]
Currently, Hono Messaging cryptographically validates each registration assertion's signature it receives via its Telemetry/Event endpoints. This is quite time consuming (simple tests have indicated that this accounts for roughly 20 - 25% of the overall processing time of a message and so it would be great if we could reduce the average time this takes per message.

One approach would be to validate a signature once only and then cache the successful validation for up  to the assertion's remaining lifetime in memory. This way, the validation of the assertion would involve a simple lookup in the cache only vs. doing a full cryptographic signature validation again for messages containing an assertion that has been validated before.

**Comment by oliverfischer83** [comment]
Bosch IoT-Hub team "yukon" will work on this issue in the current sprint.

**Comment by KenTacki** [comment]
Idea for further improvements

maximumSize() of Guava (see [PullRequest](https://github.com/eclipse/hono/pull/335)) uses the least-recently-used (LRU) algorithm for eviction when a maximum size is exceeded.
If frequency is a matter of interest (more than recency) a different algorithm should be used.

First idea: Use Caffeine in addition to Guava. Caffeine uses the Window TinyLFU algorithm for eviction, which is based on frequency and recency.

Helpful Links:
[Caffeine](https://github.com/ben-manes/caffeine)
[Efficiency (of Caffeine)](https://github.com/ben-manes/caffeine/wiki/Efficiency)
[Caffeine compared to Guava](https://github.com/ben-manes/caffeine/wiki/Guava)
[TinyLFU: A Highly Efficient Cache Admission Policy](https://arxiv.org/pdf/1512.00727.pdf)

**Comment by sophokles73** [comment]
This is no longer relevant with the removal of Hono Messaging.
