### ISSUE TITLE
Quarkus images with Kafka: hono.kafka.defaultClientIdPrefix does not map to any root

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2960]
When starting current master Quarkus images with Kafka, using the IoT Packages Helm chart, there is this exception
```
Nov 18, 2021 2:33:11 PM io.quarkus.runtime.ApplicationLifecycleManager run
ERROR: Failed to start application (with profile prod)
io.smallrye.config.ConfigValidationException: Configuration validation failed:
	hono.kafka.defaultClientIdPrefix does not map to any root
	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:855)
	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:811)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:403)
	at io.quarkus.runtime.generated.Config.readConfig(Config.zig:1293)
	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(RuntimeConfigSetup.zig:42)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:326)
```

**Comment by sophokles73** [comment]
The *defaultClientIdPrefix* is currently not documented at all in https://www.eclipse.org/hono/docs/admin-guide/hono-kafka-client-configuration/ 

I assume, however, that it is indeed relevant?

**Comment by sophokles73** [comment]
@calohmn just out of curiosity: did you check if the Kafka client metrics can be configured using the `hono.kafka.metrics` prefix?

**Comment by calohmn** [comment]
Just tested it: The configured metrics prefixes don't seem to get set in the `KafkaMetricsOptions` instance. There is no `ConfigValidationException` as above, though.

**Comment by sophokles73** [comment]
> The configured metrics prefixes don't seem to get set in the KafkaMetricsOptions instance.

Hmm, I have added a corresponding unit test which indicates that the properties are being picked up correctly by `KafkaMetricsOptions`. What makes you think that they are not getting picked up?

**Comment by sophokles73** [comment]
This is what the HTTP adapter writes to the console during startup when I deploy branch https://github.com/bosch-io/hono/tree/add_missing_kafka_config_property using the current Helm chart:

```sh
2021-11-19 08:51:50,122 INFO  [org.ecl.hon.cli.kaf.met.MicrometerKafkaClientMetricsSupport] (main) activating Kafka client metrics support; used metrics prefixes: [kafka.producer.topic.record.send.rate, kafka.producer.topic.record.error.rate, kafka.producer.node.request.rate, kafka.producer.node.response.rate, kafka.producer.node.request.latency.avg, kafka.producer.node.outgoing.byte.rate, kafka.producer.io.wait.time.ns.avg, kafka.producer.batch.size.avg, kafka.producer.produce.throttle.time.avg, kafka.producer.produce.throttle.time.max, kafka.consumer.fetch.manager.records.lag, kafka.consumer.fetch.manager.records.lag.max, kafka.consumer.fetch.manager.records.lead.min, kafka.consumer.fetch.manager.bytes.consumed.rate, kafka.consumer.fetch.manager.records.consumed.rate, kafka.consumer.fetch.manager.fetch.rate, kafka.consumer.fetch.manager.fetch.throttle.time.avg, kafka.consumer.fetch.manager.fetch.throttle.time.max, kafka.consumer.coordinator.rebalance.total, kafka.consumer.coordinator.failed.rebalance.total, kafka.consumer.coordinator.rebalance.latency.avg]
```

Isn't this the expected default configuration?

**Comment by calohmn** [comment]
> Hmm, I have added a corresponding unit test which indicates that the properties are being picked up correctly by `KafkaMetricsOptions`. What makes you think that they are not getting picked up?

@sophokles73 Sorry, I recently changed my local test config for the helm chart and misplaced the `metrics` properties there. I've now fixed that and tested it again with your PR changes and it works as expected.

And yes, the above is the expected default configuration.

**Comment by b-abel** [comment]
> I assume, however, that it is indeed relevant?

I know I am too late. But FMPOV this has been the right question. Setting the client ID is a minor feature anyways. The property has initially been added to programmatically set a value as a _fallback_ if no client ID has been provided in the configuration for the Kafka client (like e.g. `hono.kafka.producerConfig.client.id`). It was never meant to be dynamically configured.
The changes for #2904 will bring separate configurations per client. There it will add more unnecessary complexity and I am inclined to remove it from the _options_.
@calohmn @sophokles73 Or does anyone think it's important to have the property configurable?

**Comment by b-abel** [comment]
FMPOV the best solution for this issue would be to remove the line that sets the client id prefix from the _IoT packages_ project. It does not make much sense to configure a default with Helm because the protocol adapters already set the component name as the default fallback, as it has always been the case with Spring and #2962 adds this for Quarkus as well.

**Comment by sophokles73** [comment]
@b-abel Not sure if I understand correctly. Are you proposing to revert the change that I introduced in order to make this property configurable via environment variables and/or Java system properties?

**Comment by calohmn** [comment]
@b-abel Having a dedicated `defaultClientIdPrefix` property here looks at least like the cleaner solution to me. The fact that `hono.kafka.producerConfig.client.id` isn't adopted literally but is used as a prefix to which "clientName" (=fixed value set where the client object is used in the code) and a UUID get attached, isn't so obvious.

I think the first question is, what we want to achieve with letting the user set a custom prefix in the first place. Is it so that the user can for example define prefixes like `dev-env` and `prod-env` to distinguish different Hono setups using the same Kafka cluster? At least that was my guess here.
For that, one could define a `defaultClientIdPrefix` property (with values like `dev-env-mqtt-adapter`) in the common client config.

**Comment by b-abel** [comment]
My suggestion is to restore the original behavior. That was: as a user you can set (almost) all configuration properties of the (native) Kafka client. By default, the protocol adapter sets its name as client id (hence the prefix _default_). You can override this behavior by specifying the property [client.id](https://kafka.apache.org/documentation/#producerconfigs_client.id) in the Kafka properties. Then this value is taken. This behavior is roughly analogous to ClientConfigProperties.setNameIfNotSet(). 
I don't know of any particular reason why you should configure client IDs and don't consider it an important feature. I merely built the original behavior with the idea that having the component name instead of an empty client ID is a good fallback. Now providing 2 mechanisms to configure the same value (`hono.kafka.producerConfig.client.id` and `hono.kafka.defaultClientIdPrefix`) I see as unnecessary and confusing (why do I configure a default value that I can only override with another value in the same config block?).
The fact that you could set the defaultClientIdPrefix property at all is just a side effect of the Configuration Properties being pure Pojo and Spring setting the value when it finds it.

**Comment by b-abel** [comment]
> I think the first question is, what we want to achieve with letting the user set a custom prefix in the first place.

Nothing. I want to neither support nor forbid that explicitly. The only thing is that we promise that the (native) Kafka client configuration passed in is respected as far as possible. If a user for whatever reason wants to provide a client ID as with all other Kafka client config properties, we can use it, if not we provide a sensible default.
In any case, we need to append a unique suffix because we start multiple Verticles and Kafka expects client IDs to be unique.

**Comment by calohmn** [comment]
> I don't know of any particular reason why you should configure client IDs

With the client IDs, the different clients can be identified in the Kafka client metrics - see #2906. I therefore think we should take some care in choosing the format here, also having the IDs not be too long.

As noted in #2906, I also think it would be good to be more flexible in terms of how the client identifier is created.
That means for example to possibly use a `[container id]_[counter]` suffix instead of a UUID, making the ID short while adding extra info about the container.

> Now providing 2 mechanisms to configure the same value (`hono.kafka.producerConfig.client.id` and `hono.kafka.defaultClientIdPrefix`) I see as unnecessary and confusing (why do I configure a default value that I can only override with another value in the same config block?).

I would then rather not support the `client.id` property to be configured at all, it won't be taken `as is` anyway.
We could then decide if we want to support providing a prefix (naming the property `hono.kafka.clientIdPrefix` - without the `default`). FMPOV, it's not strictly needed, but could come in handy (see the above scenario with prod/dev environments).

In any case, changes in terms of the client id handling should be done with #2906 in mind.

**Comment by b-abel** [comment]
#2906 look perfectly valid to me. 
Using the same Kafka cluster with multiple separate Hono installations doesn't seem to make much sense to me. I would rather not build features for such hypothetical use cases. If at some point there is a concrete need with concrete requirements, we can always add that (and then hopefully we won't have to build configurations with Quarkus and Spring separately with identical behavior).

**Comment by calohmn** [comment]
I'm fine with removing the `defaultClientIdPrefix` then for now. 
For the Kafka clients used in the Hono components, I would also always set a specific client id, ignoring any `client.id` config property.

**Comment by sophokles73** [comment]
@calohmn @b-abel Can you then please create a new issue regarding the changes that you have agreed on?

**Comment by b-abel** [comment]
> For the Kafka clients used in the Hono components, I would also always set a specific client id, ignoring any client.id config property.

Why that? This is a completely new requirement. Currently, the configuration takes precedence. How would you know during configuration if the value will be used? If you really think the configured client ID should be ignored, then I would rather do that always and not depending on where the client is being used.

**Comment by calohmn** [comment]
I mean ignoring in the sense of always overwriting it in the code where the properties get assembled before initializing the Kafka clients used in the adapters/device-registry/command-router components. The clients each get their specific and distinct id there, no need to adopt a prefix from the config there for now (as discussed above).

In general, I think it's best to discuss the details here in the PR for #2906.

**Comment by b-abel** [comment]
@calohmn I am still not sure that I get what you mean. Maybe we can split this into two separate tasks: a) reporting the support for the configuration property  `hono.kafka.defaultClientIdPrefix` and b) deciding if the client ID configured at the Kafka client config should be taken into account. I could create an issue for a) and we can discuss b) in the PR for #2906. WDYT?

**Comment by calohmn** [comment]
@b-abel If you prefer, we can track removing the prefix property separately, yes.

**Comment by b-abel** [comment]
I created #2967.
