### ISSUE TITLE
Clear tenant/device related cache data after tenant/device got deleted/disabled

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2984]
Relies on #2837:
The new notification API should be used to invalidate tenant/device-specific cache data used in the `DeviceRegistrationClient`/`TenantClient` when the corresponding tenant/device got deleted or disabled.

**Comment by b-abel** [comment]
This also applies to the `CredentialsClient`.

**Comment by b-abel** [comment]
If for example the tenant is deleted, do we want to invalidate the cache entries for its devices as well? Or do we want to expect that the code that uses a `DeviceRegistrationClient` also checks for the tenant?
The same question arises for the `CredentialsClient` where entries may be removed if the tenant or device is changed.

**Comment by b-abel** [comment]
> If for example the tenant is deleted, do we want to invalidate the cache entries for its devices as well? Or do we want to expect that the code that uses a `DeviceRegistrationClient` also checks for the tenant? The same question arises for the `CredentialsClient` where entries may be removed if the tenant or device is changed.

@calohmn @sophokles73 Any thoughts on this?

**Comment by calohmn** [comment]
> If for example the tenant is deleted, do we want to invalidate the cache entries for its devices as well? Or do we want to expect that the code that uses a `DeviceRegistrationClient` also checks for the tenant?

I think we can keep it simple here for now and expect that the tenant is getting checked as well.
