### ISSUE TITLE
An MQTT client which doesn't provide a client-id should be refused

### ISSUE THREAD

**Issue by ppatierno** [eclipse/hono#304]
The MQTT 3.1.1 spec allows a client to connect without providing a client-id (0 length) but only if clean-session is TRUE.
In any case we use the client-id in the adapter, so I think that for Hono the case should be that the MQTT adapter just refuse the connection to a client which doesn't provide a client-id with error code 0x02 (Connection Refused, identifier rejected) in the CONNACK packet.

**Comment by sophokles73** [comment]
> In any case we use the client-id in the adapter

I do not think that this is the case. Based on my proposal in #86 the client identifier actually becomes quite irrelevant ...

**Comment by ppatierno** [comment]
Hi @sophokles73 I agree, closing this issue.
