### ISSUE TITLE
Configuring device registry with sharedSecret that is too short causes no error

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#305]
If the device registry is run with a `hono.registry.svc.signing.sharedSecret` config value smaller than 32 bytes, there is no error being thrown and there is also no error in the log output.

The `IllegalArgumentException("shared secret must be at least 32 bytes")` thrown in `SignatureSupportingConfigProperties#setSharedSecret` seems to get caught somewhere.

**Comment by skobow** [comment]
Is this bug still open? When I start the device registry spring boot application I do get an error including log message with the corresponding message emitted by spring's `PropertiesConfigurationFactory`

**Comment by sophokles73** [comment]
@skobow Indeed, this problem seems to have vanished. It might have been remedied by upgrading to a more recent version of Spring/Spring Boot in the meantime. Thanks for reporting :-)
