### ISSUE TITLE
MongoDB Device Registry using different hash algorithm in Hono 1.12

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#3068]
When using the MongoDB device registry with enabled authentication concerning the HTTP endpoint of the Device Registry, an update to Hono 1.12 will cause existing user credentials stored in the MongoDB to not be accepted anymore.

This is caused by Hono 1.12 now using `PBKDF2` as the default hash algorithm, whereas in earlier versions `SHA512` was used.

Workaround is to set `hono.registry.http.auth.hashAlgorithm` to `SHA512` in the device registry configuration. This property is currently not documented.

**Comment by sophokles73** [comment]
So, the *fix* is to properly document the configuration property?

**Comment by calohmn** [comment]
Well, for people updating from Hono <= 1.11 to not run into this issue concerning existing `user` database entries it would be better to reset the default back to `SHA512` in 1.12.1. 
Otherwise a prominent note in the 1.12 release notes is needed that users updating from an earlier version and using this feature need to set the `hashAlgorithm` config property to `SHA512` now.

**Comment by sophokles73** [comment]
> Otherwise a prominent note in the 1.12 release notes is needed that users updating from an earlier version and using this feature need to set the hashAlgorithm config property to SHA512 now.

I'd rather do that instead of using an insecure hash algorithm by default.
