### ISSUE TITLE
Update example to use Hono Server & Dispatch Router

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#31]
The example module needs to be updated to use the Hono Server module instead of the (deprecated) *Hono Dispatcher* module (which will soon be removed).

**Comment by hekonsek** [comment]
Do you have the proper Qpid Dispatch image? Does it work as expected?

**Comment by sophokles73** [comment]
We are using the [one Gordon created](https://hub.docker.com/r/gordons/qpid-dispatch/) which so far works fine (apart from the missing features ni Dispatch Router, that is ;-)) ...

**Comment by dguggemos** [comment]
I updated the readme with regard to the configuration container. I think we can close this issue?
