### ISSUE TITLE
Add number of connected devices metric to MQTT adapter

### ISSUE THREAD

**Issue by DanielMaier-BSI** [eclipse/hono#312]
At the moment hono has metrics as number of processed and undeliverable MQTT messages.

From my point of view it would be also useful to have a metric regarding currently connected MQTT devices.

**Comment by pellmann** [comment]
Metrics for connections of MQTT and Kura adapters will be written now with https://github.com/eclipse/hono/commit/ed4c56fe2bd186583b011c24ab69ac750eaf3524. 

New dashboard is still needed.

**Comment by pellmann** [comment]
Also available in dashboard. (https://github.com/eclipse/hono/commit/2690db33a96cbcbdc3453fb5eb3527f3da8af2b4)
