### ISSUE TITLE
Extend invalidating cache entries mechanism in protocol adapters

### ISSUE THREAD

**Issue by kaniyan** [eclipse/hono#3131]
Protocol adapters after fetching resources namely tenant, device and credentials from device registry, cache those resources. How long those resources are to be cached can be configured at system level irrespective of the tenants.  Lets say in a system this cache timeout is configured to 15 minutes. A new trust anchor has been added to a tenant and some devices of that tenant try to connect to the system using a client certificate corresponding to the newly added trust anchor. Since the cache timeout is set to 15 minutes, the devices may have to wait 15 minutes before connecting. In real time scenario with devices on the field it is acceptable to wait before connecting. There are scenarios like system tests and demo where after adding a trust anchor, it would be very convenient to immediately connect devices instead of waiting till cache timeout is over. 

To facilitate this, we can invalidate cache entries whenever update of resources take place in the device registry using notifications. Such a mechanism is already in place but only when resources get deleted or disabled. We can extend this also to include update operation. Additionally, we can provide a flag (at system level or tenant level), so that whenever this flag is enabled this feature will be turned on.
 
@sophokles73 @calohmn WDYT?

**Comment by sophokles73** [comment]
The device registry services already publish notifications for the CRUD operations. The protocol adapters currently only invalidate cache entries based on DELETE notifications and UPDATE notifications that are used to disable an entity. FMPOV we should introduce a tenant level flag that can used to turn on/off invalidation of cache entries based on *all* UPDATE notifications.

**Comment by n-deliyski** [comment]
I would be interested to work on that.

**Comment by n-deliyski** [comment]
Could you help me if I am on the right direction?
My idea is to add Predicate parameter to the DeviceRegistrationClient, TenantClient and CredentialsClient that will control the cache invalidation. The Predicate will be passed via method e.g configureCacheInvalidation that could be defined into dedicated Interface. Also there will be new Tenant field  "invalidate-cache-on-update".

For example ProtonBasedTenantClient will have new the method

    public void configureCacheInvalidation(final Predicate<TenantChangeNotification> invalidateCachePredicate) {
        if (isCachingEnabled()) {
            NotificationEventBusSupport.registerConsumer(connection.getVertx(), TenantChangeNotification.TYPE,
                    n -> {
                        if (invalidateCachePredicate.test(n)) {
                            removeResultFromCache(n.getTenantId());
                        }
                    });
        }
    }
And inside AbstractProtocolAdapterApplication#setCollaborators() there will be

    ...
    final var kafkaClientMetricsSupport = kafkaClientMetricsSupport(kafkaMetricsOptions);
    final var tenantClient = tenantClient();
    
    tenantClient.configuteCacheInvalidation(n -> (LifecycleChange.DELETE.equals(n.getChange())
                || (LifecycleChange.UPDATE.equals(n.getChange()) && !n.isEnabled()) ||
                tenantClient.get(n.getTenantId(), null).map(TenantObject::isInvalidateCacheOnUpdate).otherwise(false)
                        .result()));

**Comment by sophokles73** [comment]
> My idea is to add Predicate parameter to the DeviceRegistrationClient, TenantClient and CredentialsClient that will control the cache invalidation.

For the time being, I guess we could simply add the missing code to the existing cache invalidation logic that is set in `ProtonBasedTenantClient`'s constructor, or is there a compelling reason to re-factor this into a dedicated setter?

> Also there will be new Tenant field "invalidate-cache-on-update".

Yes, however, FMPOV we could simply allow this to be added to the Tenant's *ext* properties, i.e. we do not need to change the Registry Management API for this but simply need to document that a particular registry implementation supports this flag.

I guess we will also need to extend the TenantChangeNotification with a corresponding boolean property ...

**Comment by n-deliyski** [comment]
Do we need to have the cache invalidation extension logic for ProtonBasedTenantClient only or also for ProtonBasedDeviceRegistrationClient and ProtonBasedCredentialsClient?

My understanding is that it should work for all of them.

**Comment by sophokles73** [comment]
The original description of this issue should only affect the Tenant information being purged from the cache. However, I can also see other potential scenarios:
1. Purge all of a tenant's entities from the client side cache when a *TenantChangeNotification* arrives in which the *invalidate-cache-on-update* flag is `true`.
2. Support the *invalidate-cache-on-update* flag in *DeviceChangeNotification* and  *CredentialsChangeNotification* as well.
   1. Use the *invalidate-cache-on-update* flag configured at the tenant level in the registry to control if other entities should be purged on changes, or
   2. Support configuration of an *invalidate-cache-on-update* flag on device and credentials entities in the registry as well.

IMHO 2.ii would be overkill, but I can imagine doing 2.i. Other opinions? @calohmn @kaniyan

**Comment by n-deliyski** [comment]
OK, thanks, let see opinion of others.

Meanwhile I will start to prepare PR covering:
- original description of purging Tenant information from the cache.
- option 2.i. There will be explicit read of Tenant ext properties during purging of Registration and Credential caches.

**Comment by calohmn** [comment]
Regarding option 2.i:
As I understood, the question would be if we want to remove a device-cache entry if `invalidate-cache-on-update` for the tenant is `true` and the device has been changed, updating the device `via` for example, or the `downstream-message-mapper`.

Such a device change does influence the way messages for that device get processed. So, whether or not the cache gets invalidated here does make a difference (especially when developing/testing Hono devices and downstream applications).

Therefore, I would remove the device-cache entry here (credentials-cache entries for the device don't need to be deleted). I think this can even be done regardless of the `invalidate-cache-on-update` flag of the tenant.

**Comment by sophokles73** [comment]
> Therefore, I would remove the device-cache entry here (credentials-cache entries for the device don't need to be deleted). I think this can even be done regardless of the invalidate-cache-on-update flag of the tenant.

Meaning that an adapter should **always** remove a device from its cache whenever it receives a corresponding DeviceChangeNotification?
