### ISSUE TITLE
Raw Data Visualization - Message Body

### ISSUE THREAD

**Issue by vishalk2203** [eclipse/hono#3146]
Hi @sophokles73 @ppatierno 

I was working on the possibilities to visualize the raw data which is consumed in hono hub via mqtt protocol. I would like to see the data either in DB or other options.

For Example: In Azure IOT Hub, there is a option to view the raw data through blob storage and endpoints.

Just wanted to know the possibilities for this feature.

[Ref: https://github.com/eclipse/hono/issues/20]

**Comment by sophokles73** [comment]
I guess that depends on your setup and use case. If you are using Kafka as the messaging infrastructure (recommended!), you could use one of the Kafka sink Connectors for moving your data from the Kafka telemetry and event topics to e.g. a database ...

**Comment by vishalk2203** [comment]
Thanks for your update. However, we are currently using the same setup you mentioned. I thought some alternate solution will also be there.
