### ISSUE TITLE
No JVM metrics available for Quarkus-based Hono Auth / Device Registry component

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#3157]
When deploying the Quarkus based Hono components with the IoT packages Helm chart, there are no JVM metrics being shown for the Hono Auth component in Grafana.

Prometheus is able to scrape the component, though. Also the "scrape_duration_seconds" metric for example gets shown in the Prometheus UI for the Hono Auth component.

This also applies to the Quarkus-based Device Registry (not in 1.11.x).

**Comment by sophokles73** [comment]
which Hono version did this occur with?

**Comment by calohmn** [comment]
@sophokles73 occurred with Hono 1.12.

The issue here is actually, that the metrics are missing the common tags set for the Hono components:
Hono auth:
`jvm_memory_committed_bytes{area="heap",id="Tenured Gen",} 1.8644992E7`

Command Router:
`jvm_memory_committed_bytes{area="heap",component_name="hono-command-router",component_type="service",host="eclipse-hono-service-command-router-788c5d8b8c-87njw",id="Survivor Space",} 1507328.0`

This means the "JVM metrics" graph in the Hono Grafana charts doesn't show anything for the Hono auth component, because it uses the `host` tag as filter.

**Comment by calohmn** [comment]
@sophokles73 I'm already preparing a PR.
