### ISSUE TITLE
Add support for centralized log management systems like Logstash, Fluentd

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#3161]
We were trying to add support for a centralized log management system like Logstash or Fluentd by adding the `quarkus-logging-gelf` jar in the extensions folder (see #3108). This didn't work though.
It looks like this quarkus extension has to be loaded by the system ClassLoader, as noted in https://quarkus.io/guides/class-loading-reference#parent-first-dependencies.
I guess this could be made to work by setting `quarkus.class-loading.parent-first-artifacts` in `application.properties`, but this requires adaptations to the Hono deployment to add that config file.

Since this extension should be needed in many Hono deployment scenarios, I would suggest adding the `quarkus-logging-gelf` dependency by default to the Hono components. It could also be done via a Maven profile - but I would make that profile enabled by default then for building the standard Hono images.

**Comment by sophokles73** [comment]
My understanding is that most (if not all) of Quarkus' extension jars need to available during build time as Quarkus tries to initialize and configure everything at the earliest time possible. On first glance, I do not see why we shouldn't include the gelf extension by default.
