### ISSUE TITLE
AMQP device client should not support sending arbitrary properties

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#3163]
Hono's User Guide for the AMQP 1.0 protocol adapter specifies the format of the messages that a device sends/receives to/from the adapter. The user guide neither mentions the possibility to receive arbitrary properties in command messages nor the possibility to include such properties in the telemetry messages being uploaded by a device.
The *amqp-device* client module's interfaces do specify methods that accept arbitrary properties, though. It is unclear what will happen with the properties in the AMQP adapter so it seems to be best to simply remove them from the interface methods.

**Comment by calohmn** [comment]
I think an alternative would be here to properly define how devices can set custom properties outside of the message payload.
For many device protocols, there would be ways to transport these (HTTP headers, AMQP application properties, MQTT topic property bag parameters, etc.). Downstream applications could get them as AMQP message application properties or Kafka message headers. We could mandate/use a Hono specific prefix for these properties.

I could imagine that being a useful new feature.

Just looking at the currently supported functionality though, I agree that the *amqp-device* interface methods can be adapted in the suggested way. If the above feature will be implemented at some point, the modifications done here could then be reverted (or added as additional methods).

Just from a code standpoint, the changes done in the PR here mean, that the hono-extras "Azure IoT Hub Protocol Gateway" example will then not be able to set some properties here:
https://github.com/eclipse/hono-extras/blob/7c2945c8683a96cfd99b474db2717863f7fd18dd/protocol-gateway/azure-mqtt-protocol-gateway/src/main/java/org/eclipse/hono/gateway/azure/AzureIotHubMqttGateway.java#L190-L193
So, that wouldn't be supported then any more, which I think wouldn't be a problem in terms of the protocol gateway example, though.

**Comment by sophokles73** [comment]
> I could imagine that being a useful new feature.

I had the same thought, but then: nobody has actually asked for this so far, or am I mistaken?

> If the above feature will be implemented at some point, the modifications done here could then be reverted (or added as additional methods).

That's what I thought as well.

**Comment by calohmn** [comment]
> I had the same thought, but then: nobody has actually asked for this so far, or am I mistaken?

I've only just seen #1629, but there hasn't been any activity there for more than 2 years.
