### ISSUE TITLE
Use Quarkus micrometer extension

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#3166]
The extension will allow for centralized, consistent configuration of the Micrometer registry and will also allow us to enable the vert.x metrics. This will also have an impact on the way we currently expose the scraping endpoint by means of the Hono specific HealthCheckServer which we can probably replace by Quarkus standard functionality then.

**Comment by calohmn** [comment]
After having added the extension, it should be checked whether #2694 is solved by this.
