### ISSUE TITLE
Local hono build fails with "Unable to pull 'index.docker.io/eclipse/hono-service-auth-quarkus:2.0.0-SNAPSHOT' from registry 'index.docker.io'"

### ISSUE THREAD

**Issue by boaks** [eclipse/hono#3184]
```
mvn clean install failsafe:verify -DCI=true -Dhono.components.type=quarkus -Dhono.deviceregistry.type=mongodb -Dhono.messaging-infra.type=kafka -Dhono.commandrouting.cache=server -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -DskipStaging=true -Pmetrics-prometheus,jaeger,run-tests
```

fails with:

> [INFO] DOCKER> [index.docker.io/eclipse/hono-infinispan-test:2.0.0-SNAPSHOT]: Built image sha256:57c05
> [INFO] DOCKER> [index.docker.io/eclipse/hono-jaeger-test:2.0.0-SNAPSHOT] : Skipped building
> [INFO] Copying files to /home/achim/repos/hono/tests/target/docker/index.docker.io/eclipse/hono-service-auth-test/2.0.0-SNAPSHOT/build/maven
> [INFO] Building tar: /home/achim/repos/hono/tests/target/docker/index.docker.io/eclipse/hono-service-auth-test/2.0.0-SNAPSHOT/tmp/docker-build.tar
> [INFO] DOCKER> [index.docker.io/eclipse/hono-service-auth-test:2.0.0-SNAPSHOT]: Created docker-build.tar in 2 seconds 
> [ERROR] DOCKER> Unable to pull 'index.docker.io/eclipse/hono-service-auth-quarkus:2.0.0-SNAPSHOT' from registry 'index.docker.io' : {"message":"manifest for eclipse/hono-service-auth-quarkus:2.0.0-SNAPSHOT not found: manifest unknown: manifest unknown"} (Not Found: 404) [{"message":"manifest for eclipse/hono-service-auth-quarkus:2.0.0-SNAPSHOT not found: manifest unknown: manifest unknown"} (Not Found: 404)]
> 

Do I need to change the mvn parameter?

**Comment by boaks** [comment]
```
Maven home: /usr/share/apache-maven-3.8.2
Java version: 17.0.2, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-173-generic", arch: "amd64", family: "unix"

```

**Comment by sophokles73** [comment]
I am not sure what you are trying to achieve, are you trying to run the integration tests?

In general, questions should better be asked on stackoverflow or, even better, our Gitter channel where we can respond more interactively. See https://www.eclipse.org/hono/community/get-in-touch/

**Comment by boaks** [comment]
> I am not sure what you are trying to achieve, are you trying to run the integration tests?

Yes, otherwise the question would not make too much sense. Without the `run-tests`profile, the error should not occur, or?

I can ask via stackoverflow, I didn't use gitter.

And you really consider, that a question to a failing local build is no `issue`?

**Comment by sophokles73** [comment]
It might result in an issue once we have found out that running the integration tests does not work. In any case, many people run the integration tests day-in, day-out, so I would like to focus on what you are trying to do and why the outcome of the commands you are running doesn't meet up to the expectations :-)

Have you also built the docker images before executing the integration tests?

**Comment by boaks** [comment]
I considered, that 

mvn clean install failsafe:verify -DCI=true -Dhono.components.type=quarkus -Dhono.deviceregistry.type=mongodb -Dhono.messaging-infra.type=kafka -Dhono.commandrouting.cache=server -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -DskipStaging=true -Pmetrics-prometheus,jaeger,run-tests

does the work. I'm not aware, that `run-tests`requires a 2 step build. If so, could you please provide instructions for the two separate steps? Last week I was successful with 1 step

**Comment by boaks** [comment]
To be a little more precise, last week, building version 1.11.2 succeeded. Today building commit 50589ce7669e45400fa006263a1f64d90945b7d9 fails.

**Comment by sophokles73** [comment]
You are right in that we are using a similar command in the GitHub actions for the CI build where the container images are built using a local Docker daemon and stored in the Docker daemon's (local) registry. What is the output of

```sh
docker image ls | grep hono-service
```

after running your maven command?

**Comment by boaks** [comment]
```
docker image ls | grep hono
eclipse/hono-jaeger-test           2.0.0-SNAPSHOT   669ceefeccf6   3 hours ago    57.5MB
eclipse/hono-infinispan-test       2.0.0-SNAPSHOT   57c05fa02e9d   3 hours ago    305MB
```

Maybe the `-DCI=true` should not be used for local builds?

**Comment by sophokles73** [comment]
No, that is not a problem. IMHO the problem is that you are not activating the Maven profile that actually builds the images.
It should probably simply be
```sh
mvn clean install failsafe:verify -Pbuild-docker-image,metrics-prometheus,jaeger,run-tests
```
the other properties are only required if you want to run with a non-default configuration. See https://github.com/eclipse/hono/blob/master/tests/readme.md

**Comment by boaks** [comment]
Thanks!

(Right now I also detected, that `build-docker-image` is missing. Last week, the tests seems to have used old docker images from previous runs. Today I cleaned the docker images and so the tests failed.)

**Comment by boaks** [comment]
```
[INFO] Hono Integration Tests ............................. SUCCESS [12:20 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```

Thanks!

**Comment by sophokles73** [comment]
see? No issue ;-)
