### ISSUE TITLE
Verify if it is OK to push Docker images into our "eclipsehono" account

### ISSUE THREAD

**Issue by hekonsek** [eclipse/hono#32]
@kartben Benjamin, Do you think it is OK to push early versions of our images to that DockerHub account? Or maybe Eclipse has some restrictions in this regards.

**Comment by sophokles73** [comment]
I will also talk to Mike Milinkovich about this issue on Wednesday ... I'll keep you posted.

**Comment by kartben** [comment]
I think I've answered that one here: https://dev.eclipse.org/mhonarc/lists/hono-dev/msg00125.html

**Comment by sophokles73** [comment]
I have created a [bugzilla issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=493499) for this as well.

**Comment by hekonsek** [comment]
OK. So we should just remember to add SNAPTSHOT when pushing images for development. Closing this one.
