### ISSUE TITLE
Permit usage of all specified Credentials API Operations in BaseCredentialsService

### ISSUE THREAD

**Issue by Christian-Schmid** [eclipse/hono#321]
Hi Hono-Devs,

recently I started work on my own implementation of [Hono's Credentials API][1], in which I would like to implement **all** of the in the Credential API defined operations (`Add` / `Get` / `Update` / `Remove`).

As a starting point I had a look at the default `FileBasedCredentialsService` implementation which is shipped with hono.  As the `BaseCredentialsService` used there, already offers an implementation of all the vert.x EventBus stuff, I also would like to use this implementation as a superclass for my own implementation. 
This works fine for the mandatory `Get` Operation. However all other operations are rejected in the [`processCredentialsMessage())`][2] method. 

Having a look at the similar service for the Registration API, I can see that there also the non-mandatory methods are implemented in the [`processRegistrationMessage()`][3] method.

**My question:**
Is there a particular reason why the non-mandatory operations are not available in `BaseCredentialsService`.
If they are just not implemented yet, I could create a PR to implement them. 

Thanks :-)
Chris 

[1]: https://www.eclipse.org/hono/api/Credentials-API/
[2]: https://github.com/eclipse/hono/blob/427351a82b1509cce2cd00abfce39b0b1f07046b/service-base/src/main/java/org/eclipse/hono/service/credentials/BaseCredentialsService.java#L112
[3]: https://github.com/eclipse/hono/blob/427351a82b1509cce2cd00abfce39b0b1f07046b/service-base/src/main/java/org/eclipse/hono/service/registration/BaseRegistrationService.java#L137

**Comment by sysexcontrol** [comment]
Hi Chris,

until the last official milestone of Hono we did not implement the support for implementing the optional parts of the credentials API.

This should definitely change, so my proposal is to do the following steps:
- implement skeletons methods for add,remove,update like already existing for the get operation
  they just call the corresponding method of the already fully defined IF
- extend the switch statement to use these methods
- do not forget the javadoc for them :-)


If you create a PR for that : +1
I will take care of it then.

**Comment by Christian-Schmid** [comment]
Hi,

I just created the following PR https://github.com/eclipse/hono/pull/325
It contains the implementation of the skeleton methods + some unit tests.
No new `public` / `protected` methods were added, so I didn't create new javadoc.

If you have any questions feel free to ask :-) 

Thanks!

Chris

**Comment by sophokles73** [comment]
Looks like this issue has been resolved by having your PR merged, @Christian-Schmid 
If so, can you close the issue?
