### ISSUE TITLE
Feature usage of Kafka more prominently on homepage and in documentation

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#3218]
The main image on the homepage (https://www.eclipse.org/hono/hono_landing_page.svg) and on the main documentation page (https://www.eclipse.org/hono/docs/images/overview_hono.svg) only features AMQP 1.0.

Also the component view in the architecture documentation only mentions AMQP 1.0:
https://www.eclipse.org/hono/docs/architecture/component-view/

Kafka should be mentioned there as well.

**Comment by sophokles73** [comment]
Absolutely. In particular, because Kafka will be the default option with Hono 2.0.0 ...

**Comment by sophokles73** [comment]
IMHO we should also switch the Getting Started guides, i.e. the default one should be the Kafka based one ...

**Comment by sophokles73** [comment]
> I think the names of the Hono messaging APIs should be adapted as well

@calohmn are you already on this? I could do it as well because I would like to adapt the wording in several places ... let me know what you want to do...

**Comment by calohmn** [comment]
@sophokles73 You can take over here, I'm currently working on the HTTP tracing topic.

**Comment by sophokles73** [comment]
@calohmn anything else that needs to be done here?

**Comment by calohmn** [comment]
@sophokles73 It seems there is only this page https://www.eclipse.org/hono/docs/dev/architecture/auth/ left, mentioning only the AMQP messaging network and not Kafka.

**Comment by sophokles73** [comment]
Ok, I'll see that I can provide an updated version ...

**Comment by sophokles73** [comment]
@calohmn  IMHO we are done here, right?
