### ISSUE TITLE
CoAP adapter should support short endpoint names

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#3247]
Given that CoAP mainly addresses use cases where constrained devices are involved, it seems reasonable to support short versions of endpoint names in request URIs as well. That is `t` in addition to `telemetry`, `e` in addition to `event` and `r` in addition to `command_response`.

This would save a few bytes with each request message.

**Comment by boaks** [comment]
Yes, it saves some bytes.
 
FMPOV, assuming that DTLS is used, even an empty message already takes about 60 bytes (IP+UDP+DTLS), so the real benefit maybe not that large.

Anyway, it is also very easy to implement.
