### ISSUE TITLE
Prevent excessive protocol adapter load in case of high incoming command rate (Kafka)

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#3259]
Protocol adapters currently have no mechanism in place to limit the number of (Kafka-based) command messages being handled concurrently. When there is a high number of command messages in the corresponding `cmd-internal` topic, the Kafka consumer in the protocol adapter will read these messages without pause, potentially causing a very high load and subsequent timeouts on many kinds of operations in the protocol adapter.

Such a scenario could occur when there is a very uneven distribution of command messages sent by downstream application, with most commands being directed at devices connected to a single protocol adapter instance. When commands are received in the command router, there is a throttling mechanism in place. So, if commands are then evenly distributed among many protocol adapter instances, the probability for causing too much load on individual adapters is usually not that high. But, an uneven distribution (possibly also caused by scaling down the number of protocol adapter instances) can lead to adapters not being able to forward commands to devices in the rate they receive them from the command router.

Therefore, a throttling mechanism like in the command router should be put in place for the Kafka consumers used in the protocol adapters.

**Comment by calohmn** [comment]
It looks like this is not a big change (switching to usage of `AsyncHandlingAutoCommitKafkaConsumer` containing the throttling mechanism). So I think it would be good to have this in Hono 2.0.0. I'm currently testing the changes.

**Comment by sophokles73** [comment]
@calohmn can this be closed?

**Comment by calohmn** [comment]
> But, an uneven distribution [...] can lead to adapters not being able to forward commands to devices in the rate they receive them from the command router.

Actually, doing some load tests here, I couldn't create a scenario where the rate limiting introduced in #3260 was hit. Records were processed as fast as they were read from Kafka. 
Still, one could imagine a scenario where command processing in the adapter involves doing device registry requests that take longer than usual. So, better to have the extra safety mechanism introduced in #3260.
