### ISSUE TITLE
Device Registry: Inconsistent naming of device id field in request and response JSON

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#326]
When registering a device in the Device Registry, the field for the device id in the request JSON is named "**device_id**":
````
curl -i -X POST -d '{"device_id":"4711"}' -H 'Content-Type: application/json' http://localhost:28080/registration/DEFAULT_TENANT
````

When querying device data, the corresponding field in the response JSON is named "**device-id**", though.
````
curl -i http://localhost:28080/registration/DEFAULT_TENANT/4711
````
returns
````
{
  "data" : {
     "enabled": true
  },
  "device-id" : "4711"
}
````

**Comment by pellmann** [comment]
In all JSONs we typically have "device-id" (naming with a hyphen). Only for the application properties of AMQP we decided to use a underscore to be compatible with AMQP to JMS mapping of properties. So at least in all JSONs we should use "device-id" and if there is no specific reason I think we should also use the hyphen in the form-urlencoded requests. @sophokles73 - WDYT?

**Comment by sophokles73** [comment]
I do not have a problem with exposing the device ID property as [device-id] instead of [device_id]. We just need to make sure then to translate it from [device-id] (received from the HTTP client) to [device_id] before sending it to the Registration service via AMQP. Since we haven't formally defined the REST API, we are pretty flexible here.

**Comment by calohmn** [comment]
I have created PR #336 for that - changing the name in the request JSON structure as well as the form-urlencoded request param name.

To test this, the unit test provided in PR #317 can be used - with the value of `REQUEST_PARAM_DEVICE_ID` changed to "device-id" (i.e. `org.eclipse.hono.util.RequestResponseApiConstants.FIELD_DEVICE_ID`).

**Comment by sophokles73** [comment]
Can you close this issue if you think that it has been resolved, @calohmn ?
