### ISSUE TITLE
Incomplete/misleading "hono.downstream.*" metrics

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#3272]
The term "downstream" in Hono is usually associated with the direction from the device to the messaging network and from there to the Business Application. Therefore, my expectation for the `hono.downstream.*` protocol adapter metrics would be that these are about the messages sent from the protocol adapter to the messaging network.

However, that is not exactly the case. The message transfers covered by these metrics are:
- telemetry/event/command-response messages sent to the _**AMQP** messaging network_
- AMQP messages sent to the device registry (for retrieving tenant/device/credentials information)
- AMQP messages sent to the command router (for updating command subscription information)

Missing are telemetry/event/command-response messages sent to Kafka.

I think it would be better to have the AMQP messages sent to device registry and command router be covered by a different metric (not with "downstream" in the name).

After having added Kafka support, the documentation should also emphasize that `hono.downstream.full` ("The number of times a message should be sent, but could not because the sender was out of credit.") only refers to AMQP message transfers.

**Comment by sophokles73** [comment]
I agree that the naming of the metrics is ambiguous (if not misleading) now that we also have Kafka transport.
FMPOV these existing metrics are specific to AMQP's underlying message transfer mechanics and should therefore be seen in comparison to the metrics generated by the Kafka client. I can therefore imagine to simply rename these metrics to better express this fact. WDYT?

**Comment by calohmn** [comment]
@sophokles73 Good point, I agree.
I would suggest renaming the metrics like this then:
| Old | New |
| ------------- | ------------- |
| hono.downstream.full   | hono.amqp.full  |
| hono.downstream.timeout | hono.amqp.timeout  |
| hono.downstream.sent| hono.amqp.sendingDuration (emphasizing that this is a timer)  |
| hono.commands.received | hono.commands.processingDuration  |
| hono.messages.received| hono.telemetry.processingDuration  |
| hono.messages.payload | hono.telemetry.payload  |

For completeness (and for detecting "out-of-credits" errors), the `hono.amqp.*` metrics should then also be used in the Command Router and device registry components (e.g. for CommandRouter-to-DeviceRegistry communication).

**Comment by sophokles73** [comment]
If we want to use the *command* vs. *telemetry* terminology, then IMHO it should be *hono.command.** instead of *hono.commands.**. I do not believe that the name must necessarily reflect the underlying type of meter being used but should rather reflect the context in which the metrics are being produced. If we need to change the *received* suffix at all, then I would prefer *processed* over *processingDuration*.

Regarding the *hono.amqp* meter: IMHO we could remove the *full* and *timeout* metrics by simply adding values *out-of-credit* and *timed-out* to the list of possible *outcome*s. The meter could then be renamed from *hono.downstream,sent* to *hono.amqp.transferred* to stick with the AMQP term for actually sending the message ...

**Comment by calohmn** [comment]
> hono_telemetry_processing_duration_seconds_sum 

Actually, `hono_telemetry_delivery_duration_seconds_sum` would be better, I think.

> Regarding the *hono.amqp* meter: IMHO we could remove the *full* and *timeout* metrics by simply adding values *out-of-credit* and *timed-out* to the list of possible *outcome*s. The meter could then be renamed from *hono.downstream,sent* to *hono.amqp.transferred* to stick with the AMQP term for actually sending the message ...

The `timed-out` requests are currently put explicitly in a separate metric. See the comment in `MicrometerBasedMetrics`:
```
 * We report timeouts with a different meter, since the message might still be
 * accepted by the remote peer, at a time after the timeout expired. And so we
 * can still track those times.
```

Including the *out-of-credit* counter metric cases in the existing timer metric would not be optimal, I think.
This timer metric is really about the delivery time of the AMQP message. When there are no credits, there is no delivery in the first place. And including *out-of-credit* cases would mean including near zero timer values.
Without excluding such values in a graph, the shown average of delivery times could be quite misleading if there are many *out-of-credit* cases.

**Comment by sophokles73** [comment]
> Actually, hono_telemetry_delivery_duration_seconds_sum would be better, I think

But it is not only about the delivery to the downstream messaging infrastructure but also includes the time it takes to actually process the message within the adapter, or isn't it? Based on that, I would be ok with *hono_telemetry_processing_duration* if you need to have the *duration* in the name ...

> And including out-of-credit cases would mean including near zero timer values.

I get your point. Then let's stick with the *hono.amqp.** names you proposed ...

**Comment by calohmn** [comment]
> But it is not only about the delivery to the downstream messaging infrastructure but also includes the time it takes to actually process the message within the adapter, or isn't it?

Right, the "delivery duration" term should only be applied to the "hono.amqp.*" metrics.
So, it's `hono_telemetry_processing_duration` and `hono_amqp_delivery_duration` then.

**Comment by sophokles73** [comment]
don't forget to create a corresponding API change entry in the release notes ...
