### ISSUE TITLE
Default deploy config: Qpid and Artemis aren't connected

### ISSUE THREAD

**Issue by kainoj** [eclipse/hono#328]
Based on [the guide](https://www.eclipse.org/hono/deployment/kubernetes/):

I cloned fresh repo, built the project and deployed it: `hono/example/target/deploy/kubernetes/kubernetes_deploy.sh`

Having successfully registered device: 
```bash
curl -X PUT -i -H 'Content-Type: application/json' --data-binary '{"temp": 55}' http://192.168.99.100:30080/telemetry/DEFAULT_TENANT/4722
```` 
and sent message via: 
```bash 
curl -X PUT -i -H 'Content-Type: application/json' --data-binary '{"temp": 55}' http://192.168.99.100:30080/telemetry/DEFAULT_TENANT/4722
```
I expected the message to flow through Qpid to Artemis but it didn't happen. I got ` 503 Service Unavailable` instead.

Running consumer:
```bash
~/hono mvn spring-boot:run -Drun.arguments=--hono.client.host=192.168.99.100,--hono.client.port=30671,--hono.client.username=consumer@HONO,--hono.client.password=verysecret 
```
causes `202 Accepted` but the message still isn't available on Artemis

**Comment by pellmann** [comment]
The telemetry is not forwarded to Artemis, but directly to the consumer. Only the events flow through Artemis.

**Comment by pellmann** [comment]
@kainoj - is this ticket obsolete now, or do still see problems? I see that you send the telemetry message to the same port as the device registration. That are different services and should be available under different ports.

**Comment by sophokles73** [comment]
closing issue due to no response from reporter
