### ISSUE TITLE
MQTT Adapter- Connection Reset By Peer

### ISSUE THREAD

**Issue by prabhaone** [eclipse/hono#3292]
**Source - Edge Gateway(Embedded C based MqttClient)**
						
**Destination -Eclipse Hono(Mqtt Adapter)**

**Environment & Network :**

Hono Latest version(1.12) deployed in Azure Kubernetes Service(AKS).

**Scenario:**

Gateway can connect to Hono Mqtt Adapter and publish the data without any issue at first time .

And if any network issue happened at gateway end, gateway is not able to connect to mqtt adapter again(Even proper network) for certain period.

After certain hours gateway is again connected and publishing the data without issue and same scenario happened again. 

**Observation:**

Client keep on trying to connect but not able to connect at same time in Hono Mqtt Adapter log we are getting "Connection reset by peer" error.
![Mqtt-Error](https://user-images.githubusercontent.com/52821073/173284922-0ea9962b-96c5-4a30-a938-cb36ebd399b0.PNG)

At same time the same gateway is able to connect the Azure IOT Hub and publish the data without any issue.

Can you please help us to identify the issues? Please let us now if any details required to analyze.

Please find the above logs for your reference.

**Comment by sophokles73** [comment]
What is your gateway doing when it is connected to the MQTT adapter? You wrote that it publishes telemetry, but does it also subscribe for commands? Can you increase the logging level of the MQTT adapter to DEBUG?

**Comment by prabhaone** [comment]
Hi Sophokles,

Yes when first time gateway connected to Mqtt adapter it was connected and publish the data, if any network issue happened at gateway level connection got interrupted and again gateway is trying to connect the mqttadapater with new mqttclientid but not able to connect.

Even we enable Debug also we are not able to any specific error except connection reset error.

**Comment by prabhaone** [comment]
Hi Sophokles,
This gateway is not subscribing the any data from mqtt adapter, we are trying  only publish the telemetry data to mqtt adapter.

**Comment by prabhaone** [comment]
Hi Sophokles,

I will share the details what client is doing while connecting to our Mqtt adapter. 

Find the below Mqtt Adapter debug log for you reference 

![MQTT-Debug](https://user-images.githubusercontent.com/52821073/173316245-26f09930-c302-4d97-b4ae-919a118aa0b1.PNG)


![Hono_Pod_Info](https://user-images.githubusercontent.com/52821073/173315977-70c92291-48ae-4a91-a7c2-ffefbc9529a6.PNG)

Regards,
Prabakaran.

**Comment by sophokles73** [comment]
The log file doesn't indicate anything special to me apart from the *Connection reset* entries. In what context do these occur? What does the client (the device) actually do during all of the time that is covered by the log?

**Comment by sophokles73** [comment]
@prabhaone is this still an issue or can we close this?

**Comment by prabhaone** [comment]
@sophokles73 still facing the issue, requested the logs and flow from mqttclient to Hono (actual edge gateways) but not yet received. As of now we can close this issue will connect once appropriate data's are available.Thanks.
