### ISSUE TITLE
HTTP request tracing: Trace names with high cardinality created for invalid requests

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#3297]
HTTP requests received by the Hono HTTP protocol adapter or device registry should appear in the tracing UI either with the name of the specific, matched route (e.g. `/telemetry`) or with a catch-all name (`/* (default route)`). Notably, trace names should not be adopted from the HTTP request path as is, otherwise the span selection combobox in the tracing UI will be cluttered with unwanted entries.

However, with the current tracing implementation, there are cases where the span name indeed gets wrongly set to the HTTP request path. This seems to occur for invalid HTTP requests, where the path does not begin with a slash.

Example:
![WrongSpanName](https://user-images.githubusercontent.com/891931/173377242-acf91f4a-a6d0-458c-9ca6-5312eb2a9605.png)

**Comment by sophokles73** [comment]
According to [RFC 2616 HTTP 1.1](https://www.rfc-editor.org/rfc/rfc2616#section-3.2.2) a resource identifier in an HTTP request MUST contain an *abs_path* which MUST begin with a `/` character. If the HTTP adapter is processing requests that do not begin with a `/` then I wonder if this is actually a bug in Netty and/or Vert.x.

**Comment by sophokles73** [comment]
Actually, the *Request Line* of an HTTP request may contain
> Request-URI    = "*" | absoluteURI | abs_path | authority

My understanding is that Netty does not actually verify the URI because it would require quite some processing to cover all options ...
