### ISSUE TITLE
Reduce topology options to hybrid only?

### ISSUE THREAD

**Issue by hekonsek** [eclipse/hono#33]
Hi,

Maybe we could remove all the other topologies options from Topology Options page [1] and leave Hybrid only? Is there anybody in our community interested in using non-hybrid topologies? If not, then I propose to remove them to make our architectural view clearer for people new to Hono.

Just an idea :) .

[1] https://github.com/eclipse/hono/wiki/Topology-Options

**Comment by sophokles73** [comment]
I agree, at least we could move the rest of them to a dedicated "attic" section or "also considered but not used".

**Comment by ppatierno** [comment]
I agree. Not removing other models will show the flexibility of Hono. So one wiki page with THE model and another wiki page with OTHER supported model.

**Comment by sophokles73** [comment]
Let's not get confused here. We are yet to establish/prove that other options than the *hybrid model* we are currently working on will also be supported.
So, for the time being, the other options should be labeled *Also considered* or something like that ...

**Comment by hekonsek** [comment]
I'm personally a little skeptical when it comes to supporting more than one topology. Supporting many topologies means that we constantly need to invest time into testing/maintenance/etc of each topology. I would personally be happy if we could just stick to hybrid approach, as the most universal solution and focus on supporting only this. Time will prove if my wish can be true :) .

For now I will change topology page to highlight that hybrid approach is our main goal here.

**Comment by hekonsek** [comment]
Done [1]. Please keep in mind that I removed "hybrid" term from the topology descriptions. This is the primary topology model, then we should avoid referring to other models in its name. I would say that it is just a "Hono topology model" :) . 

I kept the other models in a separated section "Other topologies under consideration".

Let me know what you think.

[1] https://github.com/eclipse/hono/wiki/Topology-Options

**Comment by hekonsek** [comment]
I'm closing the issue for a while. We can reopen it if people disagree with my changes.
