### ISSUE TITLE
CoAP-Adapter: Use request-path/route-name as tracing span name

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#3301]
Incoming telemetry/event/command-response messages in the CoAP adapter are currently represented by tracing spans with the used method (`POST`, `PUT`) as span name.

This should be changed to use the request-path/route-name instead, e.g. `/event` or `/event/:tenant_id/:device_id`. 
Notably, the span name should contain placeholders like `:tenant_id` instead of actual identifiers.

This will align the span names used in the CoAP adapter with the ones used in the HTTP adapter.

**Comment by sophokles73** [comment]
I was actually wondering if we should change the HTTP adapter's behavior back to how it was before the switch to OTEL because I found the `/event/:tenant_id/:device_id` span names rather confusing. But that is probably just my personal feeling ...

**Comment by calohmn** [comment]
When looking at a list of HTTP adapter traces and seeing traces with root span names 
`/telemetry/:tenant_id/:device_id` and 
`/command/res/:tenant_id/:device_id/:cmd_req_id`, 
I think it will already be clearer what kind of request these are compared to having a name of `POST` in both cases.
