### ISSUE TITLE
Adapters should fall back to messaging type Kafka by default

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#3306]
The protocol adapters dynamically determine the type of messaging infrastructure to use by means of looking up the tenant's *ext/messaging-type* configuration property. However, if no type is configured explicitly and both AMQP 1.0 and Kafka based messaging infrastructure is available, the adapters will fall back to use AMQP 1.0 based infrastructure.

With Hono 2.0.0 Kafka has been defined as the default messaging infrastructure, thus the `org.eclipse.hono.client.util.MessagingClientProvider` should be adapted to fall back to Kafka instead.

**Comment by kduba** [comment]
I would like to work on this issue.

**Comment by sophokles73** [comment]
Fixed via #3324
