### ISSUE TITLE
Add rate-limiting OpenTelemetry tracing sampler

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#3318]
In Hono <2.0, when Hono was still using the Jaeger client for tracing, trace sampling could be configured in such a way that the number of traces forwarded per second doesn't exceed a configured value. With the OpenTelemetry based client in Hono 2.0, there is currently no such feature. There is only the possibility to configure a sampling ratio. 

In order to offer an equivalent for Hono <2.0 users with a rate-limiting sampler configuration when updating to Hono 2.0, such a feature should be added.

Implementation can be done via the OpenTelemetry SDK `RateLimiter` (as used in the `Jaeger Remote Sampler` extension `RateLimitingSampler`).

**Comment by sophokles73** [comment]
@calohmn I'd rather add this to 2.1.0 only as service releases are not supposed to include new features but focus on bug fixes.

**Comment by calohmn** [comment]
@sophokles73 ok. Integration of this feature with the existing configuration doesn't seem that straightforward anyway.

**Comment by calohmn** [comment]
`quarkus-opentelemetry` doesn't support a rate-limiting sampler in its sampler configuration.
Supported values for the `quarkus.opentelemetry.tracer.sampler` configuration property are only `off, on, ratio`.

In a future Quarkus version, the sampler configuration will most probably be changed, supporting a sampler selection like the one defined [here](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#sampler) (see https://github.com/quarkusio/quarkus/discussions/26438).

So, in order for Hono to support a rate-limiting sampler before that future Quarkus version, the question is how usage of the rate-limiting sampler should be configured.

I would suggest adding support for the `otel.traces.sampler` system property/env variable only with value `rate-limiting` (along with `otel.traces.sampler.arg` containing the rate-limit value). All other samplers should be configurable like it is currently done.

This means we don't have to change the configuration completely now and potentially again when Quarkus changes its sampler configuration.
@sophokles73 WDYT?

**Comment by calohmn** [comment]
Feature added via #3335.
