### ISSUE TITLE
Hono Reciever DNS resolution problem in Windows

### ISSUE THREAD

**Issue by balsmn** [eclipse/hono#332]
This is a very special case scenario where Hono reciever running on a windows system is not able to connect to to Hono messaging.

In Linux based systems, the /etc/resolv file used and all the DNS servers listed there are queried one after the other until the DNS name is resolved. But unfortunately this rotating of DNS servers is not done for Windows in Vertx. See [1]

But can be enforced by setting the AddressResolverOptions.setRotateServers(true) in [2]

[1] https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/impl/AddressResolver.java#L53
[2] https://github.com/eclipse/hono/blob/master/example/src/main/java/org/eclipse/hono/example/AppConfiguration.java#L45

**Comment by sysexcontrol** [comment]
@balsmn : can this issue be closed?

**Comment by sophokles73** [comment]
@balsmn can you elaborate a little on the problem you are trying to solve?
My understanding is that on a Windows system the DNS lookup of the Hono Messaging host fails, right?
Are you saying that on the specific system there are multiple DNS servers configured but you suspect that the receiver uses only the first DNS server during the lookup, even if it fails?

**Comment by balsmn** [comment]
> My understanding is that on a Windows system the DNS lookup of the Hono Messaging host fails, right?
Yes

> Are you saying that on the specific system there are multiple DNS servers configured but you suspect that the receiver uses only the first DNS server during the lookup, even if it fails?
I don't suspect but it is a fact. See the linked vertx code. DNS lookup with Rotation is configured only for Linux systems unless this flag is set.

**Comment by balsmn** [comment]
@sysexcontrol This issue can be closed if it is fixed (I have provided a PR [1] for fixing it) 
[1] https://github.com/eclipse/hono/issues/332

**Comment by sysexcontrol** [comment]
@balsmn : I know, it was merged 6 days ago already :-)
So FMPOV it could be closed...

**Comment by sophokles73** [comment]
> I don't suspect but it is a fact. See the linked vertx code. DNS lookup with Rotation is configured only for Linux systems unless this flag is set.

DNS rotation is used to balance DNS requests among multiple DNS servers, i.e. if you have two DNS servers configured, then the first DNS server will receive all uneven requests and the second one will receive all even requests. However, the problem you seem to experience is a different one: if a host cannot be resolved using the first DNS server, then the second DNS server is not queried on Windows whereas you say that on Linux the second server *is* queried if the first server cannot resolve the host.
This sounds more like a fundamental difference in the way DNS lookups are done.
However, using DNS rotation seems to be a reasonable feature to enable in any case and if this solves your problem with Windows, even better ...

**Comment by balsmn** [comment]
@sysexcontrol yes you are correct. It got merged. I overlooked at the issue instead of the PR. Yes this issue can be closed.
