### ISSUE TITLE
Not properly closing a future in AbstractVertxBasedHttpProtocolAdapter

### ISSUE THREAD

**Issue by suzanaAngelovaIvanova** [eclipse/hono#3366]
While fixing the  [issue,](https://github.com/eclipse/hono/issues/2892) we saw that there was a problem with closing one future.

The problem is in `AbstractVertxBasedHttpProtocolAdapter->doUploadMessage()`

Test request:
`curl -i -u $MY_DEVICE@$MY_TENANT:$MY_PWD -H 'Content-Type: application/json' -H "hono-ttd: 30" --data-binary '{"alarm": "fire"}' http://$HTTP_ADAPTER_IP:8080/event -v`

**Comment by calohmn** [comment]
This is about the `responseReady` *Promise* in `doUploadMessage()` not getting completed in case a `hono-ttd` request gets cancelled by the client (as mentioned in https://github.com/eclipse/hono/issues/2892#issuecomment-1177154797), right?

**Comment by avgustinmm** [comment]
Yes, I think so.
I could take a look at the issue

**Comment by calohmn** [comment]
@avgustinmm Can this be closed now that #3373 is merged?

**Comment by avgustinmm** [comment]
I think so.
