### ISSUE TITLE
Usage of Future onSuccess/onFailure/onComplete with regards to expected invocation order

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#3375]
Quote from https://vertx.io/docs/vertx-core/java/#_future_results:

> Terminal operations like `onSuccess`, `onFailure` and `onComplete` provide no guarantee whatsoever regarding the invocation order of callbacks.
> Consider a future on which 2 callbacks are registered: 
```
future.onComplete(ar -> {
  // Do something
});
future.onComplete(ar -> {
  // May be invoked first
});
```
> It is possible that the second callback is invoked before the first one.

([more info](https://groups.google.com/g/vertx/c/cA_MBo2ljME))

Places in Hono code using these methods and requiring a certain invocation order need to be adapted.

Example of affected code  in TenantServiceBasedX509Authentication:
```
                .onSuccess(authInfo -> span.log("certificate validated successfully"))
                .onFailure(t -> {
                    log.debug("validation of client certificate failed", t);
                    TracingHelper.logError(span, t);
                })
                .onComplete(ar -> span.finish());
```

**Comment by calohmn** [comment]
It looks like this is only an issue if `onSuccess`/`onFailure`/`onComplete` get invoked on a different thread than the one completing the Future, or, if `onSuccess`/`onFailure`/`onComplete` get invoked on the event loop thread but the Future has directly been created via `Vertx.executeBlocking` (with no further composition - see the [mailing list thread](https://groups.google.com/g/vertx/c/cA_MBo2ljME)).
The former case should generally be avoided (it could case other concurrency issues as well) and the latter case looks like a race condition that will be fixed in an upcoming vert.x release, with the workaround being to add a `.map(result -> result)` composition on the `Vertx.executeBlocking` future.

**Comment by calohmn** [comment]
Looking at the places where `vertx.executeBlocking` is used in Hono, I don't see any potential issues here.

**Comment by avgustinmm** [comment]
Since the javadoc explicitly states (and will state) that order is not guaranteed I think this pattern (onSuccess/onFailure -> onComplete) shall be removed from Hono (at least where order is important).
Yes, with the current Future implementation maybe there is no problem but Future implementation could be changed in future and the Hono code might unexpectedly start to behave inappropriately.

**Comment by calohmn** [comment]
I think it's best to wait for the Vert.x changes still to come out of the [mailing list discussion](https://groups.google.com/g/vertx/c/cA_MBo2ljME). I would expect the recent Vert.x javadoc additions to be removed again or to be adapted with a note that this only applies to cases where Future completion is done on another thread - a case that should be avoided anyway.
