### ISSUE TITLE
Hono Client does not stop re-connect after shutdown()

### ISSUE THREAD

**Issue by DanielMaier-BSI** [eclipse/hono#339]
When Hono Client is configured with `ProtonClientOptions().setReconnectAttempts(1)` and cannot establish connection, e.g. target is unreachable, it tries to re-connect periodically. While this behavior is just fine, I would expect that re-connection stops when `shutdown()` on Hono Client gets invoked. However, this is not the case and also prevents Hono Client from terminating threads.

Example Code:

    final Vertx vertx = Vertx.vertx(new VertxOptions());

    final ConnectionFactory amqpNetworkConnectionFactory = ConnectionFactoryImpl.ConnectionFactoryBuilder
            .newBuilder().disableHostnameVerification().host("127.0.0.1").name("container").port(5672).vertx(vertx)
            .build();

    final ProtonClientOptions protonClientOptions = new ProtonClientOptions().setReconnectAttempts(1);
    final HonoClient client = new HonoClientImpl(vertx, amqpNetworkConnectionFactory);
    client.connect(protonClientOptions, connectionHandler -> {
        if (connectionHandler.failed()) {
            LOGGER.error("HonoClient.connect() failed", connectionHandler.cause());
        }
    });

    client.shutdown();
    // does not terminate

**Comment by DanielMaier-BSI** [comment]
Hi,

I have a look at this issue. My questions so far:

- Is HonoClientImpl intended to be thread-safe?
- Is it required that HonoClientImpl can be "restarted", i.e. connect() still works, after invocation of shutdown? IMO this creates unnecessary state. I would prefer an approach like ExecutorService or vertx NetClient that are no longer usable after shutdown()/close(). 
- Do we also need to cleanup active* Maps on shutdown?
- Also HonoClient gets connection only when connection establishment was successful, i.e. we can not stop NetClient re-connect attempts on shutdown(). Any thoughts if this is acceptable or do we also need solution for this case?

Thanks
Daniel

**Comment by sophokles73** [comment]
> Is HonoClientImpl intended to be thread-safe?

No.

> Is it required that HonoClientImpl can be "restarted", i.e. connect() still works, after invocation of shutdown? IMO this creates unnecessary state. I would prefer an approach like ExecutorService or vertx NetClient that are no longer usable after shutdown()/close().

No.

> Do we also need to cleanup active* Maps on shutdown?

Not sure what you mean by *active Maps*.

> Also HonoClient gets connection only when connection establishment was successful, i.e. we can not stop NetClient re-connect attempts on shutdown(). Any thoughts if this is acceptable or do we also need solution for this case?

You are referring to the case when client passes in `ProtonClientOptions` which e.g. do not limit (TCP) reconnection attempts or a (TCP) connect timeout?

**Comment by DanielMaier-BSI** [comment]
> Not sure what you mean by active Maps.

I was referring to _activeRegClients_ and activeCredClients Maps

> You are referring to the case when client passes in ProtonClientOptions which e.g. do not limit (TCP) reconnection attempts or a (TCP) connect timeout?

Exactly, or e.g. many attempts with huge interval

**Comment by sophokles73** [comment]
> I was referring to activeRegClients and activeCredClients Maps

I see, no, these maps will be cleared when the connection unexpectedly fails.

> Exactly, or e.g. many attempts with huge interval

Good point. I guess we should probably not allow the client to provide *problematic* connect options in the first place ...

**Comment by DanielMaier-BSI** [comment]
Fixed with #371 except that NetClient cannot be stopped before first successful connection establishment. But current behavior is sufficient for us.
