### ISSUE TITLE
MQTT adapter doesn't send messages anymore after access token expiration

### ISSUE THREAD

**Issue by ppatierno** [eclipse/hono#343]
After the access token expiration and reconnection to the messaging, device registry and credentials services, the MQTT adapter isn't able to publish messages downstream anymore.
It seems to me that the problem is reaching the Credentials service which doesn't return any information on getting credentials for the device.

**Comment by sophokles73** [comment]
I think this is caused by a stale `CredentialsClient` being used after `HonoClient` has re-established the connection to the Credentials service. Is suspect the problem to be that `HonoClientImpl.activeCredClients` is not cleared in `HonoClientImpl.onRemoteDisconnect` like the other caches are ...

**Comment by sophokles73** [comment]
Looks like @sysexcontrol has had the same idea :-)

**Comment by sysexcontrol** [comment]
@sophokles73 : I just fixed that. Sorry, used the chat for communication that and wanted to post it just now here...
Thanks for analyzing as well!

**Comment by sysexcontrol** [comment]
@ppatierno : can you see if the fix works for you and if yes close this issue? Thanks!

**Comment by ppatierno** [comment]
@sysexcontrol it works now ! thanks ;)
