### ISSUE TITLE
Default for hash-function in Credentials API is not implemented

### ISSUE THREAD

**Issue by DanielMaier-BSI** [eclipse/hono#347]
The Docs for Credentials API (https://github.com/eclipse/hono/blame/master/site/content/api/Credentials-API.md#L350) state that default value for hash-function is sha256. But if a create credentials without hash-function, it still stays `null` and a device is not able to authenticate.

**Comment by sophokles73** [comment]
fixed in 7ed4355bbff67b7a303f81ca9f2d1944a4cab26e
@DanielMaier-BSI can you check if this works for you and then close the issue?

**Comment by DanielMaier-BSI** [comment]
Ok that was fast :). Looks fine to me and I also like the clarification and implementation of using UTF-8 as charset encoding.
