### ISSUE TITLE
Support authentication of devices using X.509 certificates in MQTT adapter

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#349]
The MQTT adapter should support devices using an X.509 client certificate for authenticating.

**Comment by sophokles73** [comment]
Vert.x 3.4.2 does not support accessing the MQTT client's certificate (yet).
@ppatierno any plans for adding this kind of functionality in `MqttEndpoint`?

**Comment by ppatierno** [comment]
@sophokles73 there is this PR for that https://github.com/vert-x3/vertx-mqtt/pull/42. It should be in the 3.5.0 release.

**Comment by sophokles73** [comment]
Ok, now that we have upgraded to vertx 3.5.0 I can start working on this.
The first question I stumbled upon is this: how do we determine the *tenant* of a device presenting a client certificate during authentication? An obvious option is to extract that information from the certificate, of course. We could e.g. parse the DN from the subject identifier and e.g. expect the tenant to be contained in the OU or DC. However, this would require organisations to create certificates for their devices which are either somehow specific to Hono (including a Hono tenant ID in the cert) or using standard information included in the certificates as the tenant ID (e.g. the concatenated DC values, effectively forming a *domain name*).

Any thoughts? @pellmann @dejanb @ppatierno @sysexcontrol

**Comment by sophokles73** [comment]
Based on some discussions we had about the options for determining the device's tenant based on the certificate it presents during authentication, here's what I think:

Parsing the tenant from the DN of the certificate would require us to either mandate the usage of a certain component of the DN for holding the tenant ID (e.g. `O` or `OU`) or we would need to allow for the user/admin to configure e.g. a *pattern* indicating how to extract the tenant ID from the DN.

Both approaches do not seem overly appealing to me. The former would potentially render existing certificates useless for usage with Hono because the particular component of the DN is either not set at all or is already used for other purpose. The latter would require us to implement error prone pattern matching code while still requiring users to encode the tenant ID within the DN.

I am currently more in favor of using a different approach for determining the device's tenant based on the X.509 certificate presented during authentication:

In order to successfully authenticate a device based on its X.509 cert, we need to configure the protocol adapter(s) with the certificate of the CA that has signed the device's certificate. This is usually done by adding the CA certificate to the protocol adapter's *trust store*.

When a device is (successfully) authenticated, the protocol adapter establishes a chain of trust from the device's certificate up to a certificate contained in the adapter's trust store. This *certificate chain* is made available to the protocol adapter code during connection establishment.

The protocol adapter now needs a way of determining the tenant ID of the device based on the certificate chain. In order to do so, we can use the upcoming *Tenant API* as proposed in #402. We can use the Tenant API to store a hash over the tenant's corresponding CA certificate's Subject Identifier as described in [RFC 6920](https://tools.ietf.org/html/rfc6920).

We then also need an additional operation in the Tenant API for looking up a tenant based on such a hash. This operation can then be used by the protocol adapter to determine the tenant based on the hash it derived from the CA certificate contained in the device's *certificate chain*.

The advantage of this approach would be that we do not make any assumptions regarding the information contained in the device certificate's subject identifier which would allow tenants to use existing certificates of their choice for authenticating devices.

**Comment by sophokles73** [comment]
Sadly, but truly, the PR mentioned by @ppatierno has not made it into vertx. MQTT yet. We will therefore need to postpone this issue.

**Comment by sophokles73** [comment]
Based on a mail I received from Julien Vieth of the vert.x project, the 3.6.0 release will not be available until sometime in November 2018. So it seems appropriate to postpone to > Hono 0.8

**Comment by sophokles73** [comment]
fixed in 75fc627563973e7726ceffdaf0620c5d4dee6e31
