### ISSUE TITLE
Create general Hono architecture blog post and DZone article

### ISSUE THREAD

**Issue by hekonsek** [eclipse/hono#35]
We should promote Hono architecture and project from early days of the project. I will write initial article to make some noise around the project.

Action items:
- publish article on DZone

**Comment by sophokles73** [comment]
That's a great idea, @hekonsek :+1: 
Glad you're picking up on this since I am not that good at it ...

**Comment by hekonsek** [comment]
I have created a very brief article [1]. I'm working now or reposting it on DZone.

[1] https://medium.com/@hekonsek/scalable-iot-messaging-with-eclipse-hono-1d3f6a1b68c3#.xz4brjz7i
