### ISSUE TITLE
Define Device Registration and Credentials APIs based on REST

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#352]
Currently the [Device Registration](https://www.eclipse.org/hono/api/Device-Registration-API/) and [Credentials](https://www.eclipse.org/hono/api/Credentials-API/) APIs are (officially) defined based upon the AMQP protocol.

These APIs are not relying on AMQP features though. Using a REST-based definition instead would be an easier and more straightforward approach concerning the implementation and usage of these APIs.

When the Credentials API REST implementation is complete, both API specification documents could be rewritten to refer to the REST-based APIs. 
The AMQP implementation could possibly then be removed. Having only one implementation would also mean less maintenance effort.

**Comment by sysexcontrol** [comment]
@calohmn @sophokles73 @pellmann @ppatierno : 
Refering to #365 it becomes clear IMHO that we should use the credit based flow control of AMQP for these APIs as well.
This "only" affects the mandatory operations of the APIS, i.e.

- Assert Device Registration (for the Device Registratrion API)
- Get Credentials (for the Credentials API)

and not necessarily the optional operations (that mainly cover the administration of the entities that are addressed by the APIs).

So, I clearly think that we should not delete the AMQP based implementation, at least not for these mandatory operations, but instead use the credits for a better handling of overload (see scenario described well in #365).

WDYT?

**Comment by ppatierno** [comment]
I'm with @sysexcontrol considering what happened in #365.
Getting assertion and credentials needs flow control, so I would stay with the AMQP based implementation.

**Comment by calohmn** [comment]
Ok, makes sense.
