### ISSUE TITLE
MQTT adapter stops working as soon as AMQP credits run out

### ISSUE THREAD

**Issue by alexmabsi** [eclipse/hono#365]
Hey,

I think there's an issue with the current protocol adapter imeplementations.

I ran some load tests against the mqtt adapter and have some findings. I wonder if there are any configuration gotchas or something I might have missed.

Let's start with the test scenario:

6 AWS EC2 instances fire against the hono mqtt adapter using jmeter. Device authentication is enabled (pwd, sha-512). The hono cluster is rather small, 3 t2.medium nodes running kubernetes with 3 masters. 
One message has a 512 byte payload.

Everything works fine with a total throttled throughput of 200 messages/sec. (10 devices on 1 tenant)
As soon as I ramp up the load everything breaks (2000 messages/sec total from 10 devices and 2000 messages/sec from 200 devices). 

The problem as far as I can tell is: 

The mqtt adapter runs out of credits and closes the connection, see this log message:

VertxBasedMqttProtocolAdapter - cannot process message for device [tenantId: DEFAULT_TENANT, deviceId: loadTestClient-4, topic: telemetry/DEFAULT_TENANT/loadTestClient-4, QoS: AT_MOST_ONCE, cause: no credit available for sending message

Closing the conncetion also deletes the registration assertion which in turn makes it necessary to gather the registration data from the device registry service on the next message. The device registry gets overwhelmed by those requests (100k in a 10min test run in my case).
The messaging service does not receive any more messages the mqtt adapter failes to recover by itself. I would expect the system to behave differently: Drop new messages from the affected tenant, instead it tries to accept them and 'kills' backend services. 

Are there any problems with my setup as far as you can tell? Imo the behavior is not acceptable, as there is a hard limit on throughput that brings down a deployment and requires manual intervention.

I'm happy to provide more information, just give me some pointers if necessary

Cheers

**Comment by sophokles73** [comment]
None of the observed behavior is acceptable FMPOV. From what you describe, I see multiple issues we should probably address:
1.As you already mentioned, closing the connection also entails discarding of the registration assertion. Given the cost at which it needs to be created, one could ask whether it makes sense to close the connection at all once the adapter runs out of credits. On the other hand, closing the connection may trigger the client to (re-)connect to another adapter instance which hopefully has credits available.
1.The adapters currently assume that the registry is always available for issuing an assertion. However, IIRC the device registry just hands out 20 credits to an adapter for issuing requests. I think this will prove to be a bottleneck in the scenario described by you when hundreds of devices re-connect and send their first message. We should probably take precautions in the adapters to refuse messages if there are no credits available for requesting assertions from the Device Registration service.

In any case, your expectation regarding the system remaining in a stable state and degrading gracefully is more than appropriate.

**Comment by sophokles73** [comment]
@pellmann @sysexcontrol @ppatierno @dejanb 

Guys, I think that we should make the behavior described in 1) configurable, i.e. if the MQTT adapter should close the connection if it runs out of credits for any of the following: forwarding the data to Hono Messaging or getting a registration status assertion from Device Registration.

WDYT?

**Comment by sysexcontrol** [comment]
Actually I think **running out of credits** should not be considered as an error case , but rather as a situation that at least every once in a while happens as normal behaviour.

Thus to close the connection to the client in such a case sounds to me like a "brutal" reaction - especially if the client did not misbehave at all, but only too many devices of the same tenant just sent data via the affected protocol adapter instance.

So, +1 for not closing the connection when running out of credits.

But I am not sure about why this should be configurable: I guess the configuration would then behave like it is now and disconnects the device? So if overload is the source of running out of credits, a large number of devices would constantly reconnect and jump through all adapter instances?
I would think this behaviour is hardly ever desired - rather more sophisticated strategies (like no single device can completely prevent other devices at the same adapter coming through with their payload) could be a midterm-solution.
WDYT?

**Comment by pellmann** [comment]
I am with @sysexcontrol and think running out of credits is a normal case and should not end in disconnection. The case that this might be true for a longer time, is something we need to figure out and how to handle it. So I think we should start with not closing the connection and collect experiences with this. If we make this configurable we do not have a real solution but a bigger amount of possible system states, which makes understanding of the system as a whole harder.

**Comment by ppatierno** [comment]
Unluckily, MQTT 3.1.1 doesn't have a way for providing errors to the client (it will be addressed with MQTT v5) and the only way is to close connection if errors occur.
In this specific case I agree on not closing the connection but just because we are supporting only "AT MOST ONCE" delivery so the client can expect that a packet is lost and is not delivered to the service.
If we'll move to support telemetry with "AT LEAST ONCE" then we can't just drop the message when the adapter runs out of credits.
For now, +1 for not closing the connection.

**Comment by dejanb** [comment]
I agree as well. For me it seems natural to just drop telemetry messages if there's no credit. For event (and other QoS1) messages, we should drop the message and not send puback back. IIRC that should indicate the client that message is not received and it can try to redeliver after a timeout.

**Comment by sophokles73** [comment]
> For event (and other QoS1) messages, we should drop the message and not send puback back. IIRC that should indicate the client that message is not received and it can try to redeliver after a timeout.

I agree with @dejanb, even for QoS 1 we do not need to close the connection, we just do not send the PUBACK. This is already implemented.

I will then change the code accordingly, i.e. do not close the connection if we run out of credits (regardless of whether it is credits for Registration or Hono Messaging).

Thanks for your opinion, guys :+1:

**Comment by ppatierno** [comment]
Yes I agree with @dejanb regarding QoS 1, I made a mistake saying that "we can't just drop the message" ... the good idea is dropping message and not sending the PUBACK hoping that the adapter will receive more credit in the future.

**Comment by sophokles73** [comment]
should be fixed in 41067c1d5ff1455d09c3cd2f73616bdfc50ec632

@alexmabsi can you give it a try and see if the MQTT Adapter remains in a stable state with these changes?

**Comment by sophokles73** [comment]
@alexmabsi please re-open if this does not improve things for you.
