### ISSUE TITLE
Not able to checkout Hono with Windows anymore

### ISSUE THREAD

**Issue by DanielMaier-BSI** [eclipse/hono#384]
Hi,

with commit [b5aa7c70d4c](https://github.com/eclipse/hono/commit/b5aa7c70d4c5eb92354b09d9bc56eb27d3626540) a file named "LICENSE" (uppercase) in folder legal/legal was introduced. However there exists also a folder named "license" (lowercase). This does not work with windows and git clone/pull ends with an error because of this.

**Comment by sophokles73** [comment]
Wow, that's annoying, indeed.
I will rename the LICENSE file to LICENSE.txt. That should probably do the trick, right?

**Comment by DanielMaier-BSI** [comment]
Right.

**Comment by sophokles73** [comment]
should be fixed in 84fb7bf17d4ecd053998b96a1e0aef14dd5669c2

@DanielMaier-BSI can you test if this solves your problem on Windows?

**Comment by DanielMaier-BSI** [comment]
Works. Thanks a lot :).
