### ISSUE TITLE
Documentation of Credentails APIs not-before property is incomplete

### ISSUE THREAD

**Issue by pho-enix** [eclipse/hono#385]
https://github.com/eclipse/hono/blob/master/site/content/api/Credentials-API.md#secrets-format

_ISO 8601 compliant combined date and time representation_

Actually the API only accepts

_ISO 8601 compliant combined date and time representation in extended format_

The examples also use the basic format which is rejected by the API.

Basic: 20171224T1900Z+0100
Extended: 2017-12-24T19:00:00+01:00

**Comment by sophokles73** [comment]
Thanks for reporting :+1: 
I will update the documentation accordingly.

**Comment by sophokles73** [comment]
fixed in d0cda44db1312e7fcd4c75242fb12ee3fe2b3987

Will be published to the Hono website by Oct. 24th 2017
