### ISSUE TITLE
Tenant API Component

### ISSUE THREAD

**Issue by Christian-Schmid** [eclipse/hono#388]
Hi Hono Devs, 

In a corporate set up you often want to operate hono as a shared service among different tenants. The tenants in such an environment usually do not share all the same privileges. 

One could imagine for example the following use cases: 
- A tenant is only allowed to use certain adapters (e.q. REST but no MQTT). 
- A tenant is only allowed to use a certain bandwidth (rate of events / telemetry) for a specific adapter.
- …

As a first step to enable such use cases, I propose to introduce a "Tenant API" component in Eclipse Hono. The Tenant API should be designed in an analogous way as for example the Credentials or Device API. This would give it the following features:
- Runs as new independent hono component. 
- AMQP 1.0 Interface for CRUD operations to other hono components. 
- Data is specified in JSON with the possabillity to store additionall meta data. 
- File based default implementation, which just implements the Read operation.

In further follow-up stories the adapters could be extended to consider the information from the Tenant API.

WDYT: Makes such a component sense in the hono environment? If so I would like to
- provide an API draft for the new component
- Implement a file based default implementation

Thanks Chris

**Comment by sophokles73** [comment]
Hi @Christian-Schmid,

this sounds very reasonable to me. We were already discussing similar use cases where we would e.g. like to be able to enforce device authentication per tenant. Currently, we can only configure this at the protocol adapter level which does not seem appropriate for a multi tenant shared service as you describe.
I would be glad to receive a corresponding PR for the API. It would be great if you could use the Credentials or Device Registration API as a template.

**Comment by Christian-Schmid** [comment]
Hi, 

I have created a draft for the tenant api in PR #402

Thanks Chris

**Comment by sysexcontrol** [comment]
Completed in 0.6-M1.
