### ISSUE TITLE
HonoClientImpl: Create only one Credentials client per tenant

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#390]
The `activeCredClients` map in `HonoClientImpl` contains `CredentialsClient` objects per tenant, which suggests that only one `CredentialsClient` per tenant is used at the same time.

But this still needs to be enforced, preventing concurrent creation of `CredentialsClient` objects for the same tenant.

**Comment by sophokles73** [comment]
fixed in 053c2092e0ca8b2354afd947e724e46a81665ada
