### ISSUE TITLE
REST Adapter: let the CredentialsClient wait a bit for credits before returning an error

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#392]
Before returning a 503 response (as implemented in #391) because the credentialsClient doesn't have credits yet, the REST Adapter should wait a bit for the credits to arrive.

**Comment by pellmann** [comment]
Should maybe a general mechanism of the HonoClient with all links

**Comment by pellmann** [comment]
Fixed in https://github.com/eclipse/hono/commit/a51598720c7e84a785611faaeeb5b7ec0c5f3b3a

(Will be configurable with next step)
