### ISSUE TITLE
Make AMQP accessible for hono.eclipse.org

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#394]
As discussed during EclipseCon last week I would like to see the AMQP ports of hono.eclipse.org be remotely accessible.

This would allow us to talk to the Hono sandbox using AMQP.

**Comment by sophokles73** [comment]
which operations would you be interested in, i.e. what would you like to achieve?

**Comment by ppatierno** [comment]
I think that what we need is an AMQP adapter. Interacting with the Hono AMQP ports means using the authentication system that we have in place between "internal" components. We need an AMQP adapter which is able to handle credentials in the same way it happens with HTTP and MQTT.

**Comment by ctron** [comment]
This is another topic. Which is good as well.

But I was more interested in accessing the internal services, like the device registry, via AMQP.

**Comment by sophokles73** [comment]
The AMQP endpoint for the Device Registy is in fact already exposed via port 25671. However, clients are required to authenticate via SASL PLAIN and access to the service operations is restricted. What we could do is add a new set of credentials for accessing the Device Registry via AMQP. However, it feels kind of strange to restrict access via AMQP when we do not require auth via REST, doesn't it?

**Comment by ctron** [comment]
Yea, it is indeed strange, but still acceptable IMHO.

I do understand that this is not a "normal" setup, as those are internal services, but still it would be nice to have the same access over AMQP which you have over REST.

**Comment by sophokles73** [comment]
Actually, they are not really *internal* services. They are supposed to be used by e.g. a device provisioning process. So it does make sense to expose the API via AMQP. And we do. The only question is whether we can live with the inconsistency between the two endpoints (HTTP vs. AMQP) regarding auth.
@ppatierno @dejanb @pellmann @sysexcontrol WDYT?

**Comment by ppatierno** [comment]
Good point. I think that having two different protocols for exposing the same API is a good thing but they need to be consistent. Having an "insecure" way (as workaround) for doing something against the secure one is not so good; actually it's the HTTP REST endpoint vs the AMQP one.

**Comment by sophokles73** [comment]
@ctron is this still an issue now that we have the Management API?

**Comment by ctron** [comment]
Yes, indeed!
