### ISSUE TITLE
Choose AMQP 1.0 framework

### ISSUE THREAD

**Issue by hekonsek** [eclipse/hono#4]
We are currently working on the Vertx-Proton client, which we recommend for new development of AMQP 1.0 client code. Here is the example of the vertx-proton API usage [1].

You can find the latest snapshot of the vertx-proton in this [2] repository.

I would say +1 for using vertx-proton for AMQP 1.0 communication. What do you think?

[1] https://github.com/vert-x3/vertx-proton/blob/initial-work/src/test/java/io/vertx/proton/example/HelloWorld.java
[2] https://oss.sonatype.org/content/repositories/snapshots/io/rhiot/vertx-proton/

**Comment by sophokles73** [comment]
That looks interesting (and simple :-)). However, we are building an AMQP 1.0 server, i.e. we want clients to connect to Hono using AMQP 1.0 and we (internally) then route the messages via different underlying brokers, e.g. RabbitMQ or ActiveMQ or Kafka. We therefore need to find the technology to use to implement a highly scalable AMQP 1.0 server (facade) that we can build upon. My understanding is that Proton can be used for that as well or am I mistaken?

I am also not sure about using vertx as the runtime environment. To me it always seemed to be a little restrictive regarding deployment options. But maybe I only do not have enough experience with it and can be convinced that it would be a good choice :-)

**Comment by ppatierno** [comment]
The Vertx-Proton client seems to be a very good "wrapper" using Vertx technology around the Qpid ProtonJ engine. It provides a good abstraction level on top of AMQP concepts like connection, session, link and so on.
The other ProtonJ Messenger project provided by Qpid seems to be not supported anymore.
It means that the only good AMQP 1.0 implementation is based on ProtonJ Engine and instead to develop a new client from scratch around it ... using Vertx implementation is a very good idea.

**Comment by hekonsek** [comment]
Vert.x-proton allows you to create reactive AMQP servers [1] as well. So this is definitely one option to consider.

BTW I'm also think that we should consider providing an option of using the AMQP broker itself as a facade and bridge the incoming traffic to the IoT Connector from there. So for example I could use my existing AMQP brokers infrastructure as a facade for the Connector and then forward brokers traffic to the IoT Connector dispatcher. I will write more about this after digging into existing code.

[1] https://github.com/vert-x3/vertx-proton/blob/initial-work/src/test/java/io/vertx/proton/example/HelloWorldServer.java

**Comment by sophokles73** [comment]
It seems like some things have changed with the release of vert.x 3. in particular, it seems like it is now much easier to embed vert.x in another application, i.e. we are not required to run the vert.x container and use verticles anymore. I have always liked vert.x simple (single threaded) programming model so it might be well worth exploring ...

**Comment by sophokles73** [comment]
@hekonsek,

I have played around with vertx-proton over the week end (see https://github.com/eclipse/hono/tree/vertx_server) and was impressed by how easy it was to get it up and running :-) However, it looks like there is only one person working on vertx-proton and there is no license indicated under which the code can be used :-( You said earlier that

> We are currently working on the Vertx-Proton client, which we recommend for new development of AMQP 1.0 client code. Here is the example of the vertx-proton API usage [1].

Does that mean that you are a contributor or committer on that project as well or did you mean *RedHat* in general? If the latter is the case, can you reach out to the people working on it in order to discuss some issues?

**Comment by hekonsek** [comment]
Hi Kai,

The vertx-proton will be available under Eclipse license, as Vert.x is an Eclipse project.

I mean that our messaging team here at Red Hat recommends using Vert.x Proton instead of old Proton Messenger API. If you have a questions regarding the current implementation, ping @gemmellr. Robbie is one of our engineers working on the vertx-proton, he should be able to answer your doubts.

Cheers!

**Comment by sophokles73** [comment]
This issues seems to be [subject to discussion in the Vert.x community](https://github.com/vert-x3/vertx-proton/issues/14) ;-)

**Comment by sophokles73** [comment]
@hekonsek,

it looks like there is currently no *official* nightly build of *vertx-proton* running that would create `io.vertx:vertx-proton:1.0-SNAPSHOT` but only the build you guys are doing for *rhiot` that creates `io.rhiot:vertx-proton:1.0-SNAPSHOT`, right?
However, it seems that this build is not running very frequently, i.e. it doesn't pick up any changes in vertx-proton quickly. Can you increase the build frequency to at least nightly, or even better triggered by changes in the repo?

**Comment by hekonsek** [comment]
Well, this rhiot build is a manual process. I created it to have any snapshot deployed.

I have deployed a recent snapshot just a moment before. I will also try to assign higher priority for vertx-proton official snapshots to be released after every CI build.

**Comment by sophokles73** [comment]
We seem to have agreed to use [vertx-proton 3.2.0](https://github.com/vert-x3/vertx-proton/releases/tag/3.2.0) based on vert.x 3.2.

I have created [corresponding CQ 11241](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11241) for using vertx-proton as a pre-req dependency.

**Comment by hekonsek** [comment]
In case of any issues with vertx-proton feel free to ping Robbie. He's our guy and is always very helpful.
