### ISSUE TITLE
Fix example-config Docker image owner and push initial image

### ISSUE THREAD

**Issue by hekonsek** [eclipse/hono#40]
We should use `eclipsehono` [1] DockerHub username, not `hono`. The latter has been already taken by somebody not associated with Eclipse.

Also, we should push example config to DockerHub (ideally automate the process) in order to allow people to run example as Docker image out of the box.

[1] https://hub.docker.com/r/eclipsehono

**Comment by hekonsek** [comment]
Done.

**Comment by hekonsek** [comment]
The image is available here - https://hub.docker.com/r/eclipsehono/example-config/ .

**Comment by sophokles73** [comment]
@hekonsek, I had the chance to talk about the whole *publishing Docker images* thing with Mike Milinkovich last week. He will set up a phone call with Wayne Beaton and me (us?) in order to talk through what we should do to make it work.
In general, he sees no problem to do so, he actually encouraged us to pursue this road. There even exists an *eclipse* repository on Docker Hub already which is supposed to be used for this purpose...

**Comment by hekonsek** [comment]
But Docker organizations are supposed to be mapped per project. Like every Eclipse project has its own Maven `groupId`. Such `groupId` has `eclipse` in its name, but still every project has its own namespace.

Such separation is needed for example in order to provide reasonable security. I don't want other Eclipse project leads to have a write access to our images. I also should not have an access to images of other Eclipse projects.

Using shared "eclipse" DockerHub organization is wrong on so many levels :) .

Oh and feel free to include me in a phone call with Eclipse folks regarding Docker images. :)

**Comment by sophokles73** [comment]
Docker Organizations now seem to be able to restrict access to repositories based on group membership. The guys from Eclipse have created a Hono group (for the committers) and can now create repositories as we see fit, e.g. `hono-server`, `hono-adapter-rest-vertx` etc to which only members of group Hono can push.

**Comment by sophokles73** [comment]
Docker images are being published to the [*eclipsehono* organization on Docker Hub](https://hub.docker.com/u/eclipsehono/dashboard/).
