### ISSUE TITLE
How do you inject custom metadata into the AMQP Message? best practice?

### ISSUE THREAD

**Issue by zubairhamed** [eclipse/hono#401]
So the use-case might be data which could be considered metadata and not telemetry data payload.

e.g.: RSSI, Base Station IDs/Origin Gateway IDs, timestamps, Triangulated Long/Lat.

How does an adapter inject these metadata instead of including this as part of the body/payload?
Or would the whole glut of  metadata be also part of the payload? (Which means the Adapter would need to construct a JSON structure, insert all the metadata and perhaps the actual telemetry payload goes into a "data" field?)

Hope that was coherent :-D

Z

**Comment by pellmann** [comment]
As written in die API definitions of e.g. telemetry, all own application properties will be delivered to the consumer. In AMQP this is typically the place for own metadata, which is intended for the consumer.

If it is the best to encode such in the data section as e.g. JSON or to use application properties for some of them depends on the use case. Hono does not require you to do so. I think for real meta data, the application properties are perfect.

**Comment by zubairhamed** [comment]
Ah yes ok i see its one of the methods in MessageSender.

However, it looks like, in order to customize this, the AbstractVertxBasedHttpProtocolAdapter file would need to be customized (uploadTelemetryMessage is finalized)

**Comment by sophokles73** [comment]
I think you are right, @zubairhamed. We will need to refactor the `AbstractVertxBasedHttpProtocolAdapter` somewhat in order to provide more control over the AMQP message being created. IMHO we should do that in analogy to what we do in the `AbstractVertxBasedMqttProtocolAdapter` where we delegate creation of the `Message` to the subclass ...

**Comment by sophokles73** [comment]
@zubairhamed 
I have added a *customizeDownstreamMessage* method to `AbstractVertxBasedHttpProtocolAdapter` which you can override in order to add custom properties to the message before it is sent downstream. Take a look at the JavaDocs and let me know if this is helpful :-)

**Comment by sophokles73** [comment]
@zubairhamed 
`AbstractVertxBasedMqttProtocolAdapter` also has a *customizeDownstreamMessage* method which you can override to add custom properties.

If this helpful?
