### ISSUE TITLE
Use common template for tagging protocol adapter metrics in influxDB

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#406]
Currently, the influxDB config file contains a separate template for each protocol adapter to add *tags* to the metrics reported by protocol adapters. Taking a closer look, it seems that we could use a single template for all (current and future) protocol adapters using a wildcard on the adapter's *type name* (see #387).

**Comment by pellmann** [comment]
Together with this, we could also rethink the naming structure. the actual metrics names, which will be converted by the InfluxDB templates are:

**Messaging**
[host.]hono.messaging.connections.downstream
[host.]hono.messaging.link.downstream.credits.<'telemetry'|'event'>.<tenant>
[host.]hono.messaging.senders.downstream.credits.<'telemetry'|'event'>.<tenant>
[host.]hono.messaging.receivers.upstream.links.<'telemetry'|'event'>.<tenant>
[host.]meter.hono.messaging.messages.<'telemetry'|'event'>.<tenant>.processed
[host.]hono.messaging.messages.<'telemetry'|'event'>.<tenant>.discarded
[host.]hono.messaging.messages.<'telemetry'|'event'>.<tenant>.undeliverable

**Adapters**
[host.]meter.hono.<'http'|'mqtt'>.messages.<'telemetry'|'event'>.<tenant>.processed
[host.]hono.<'http'|'mqtt'>.messages.<'telemetry'|'event'>.<tenant>.undeliverable

The templates create tags for host, type (telemetry/event) and tenant at the moment. In the future I think the adapter type should also be a tag.

The "meter" is used by Spring Boot to create the Dropwizard meters. It could be discussed, if we really need this (mean rate, 1-, 5-, and 15-minute moving averages).

**Comment by pellmann** [comment]
Fixed with https://github.com/eclipse/hono/commit/ed4c56fe2bd186583b011c24ab69ac750eaf3524
