### ISSUE TITLE
Negative credit in the log

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#407]
I just spotted the following line in the log of the "hono-adapter-mqtt-vertx" container when trying to scale up producers against a running Hono instance:

~~~
09:56:16.881 [vert.x-eventloop-thread-1] DEBUG o.e.hono.client.impl.HonoClientImpl - reusing existing message sender [target: telemetry/DEFAULT_TENANT, credit: -57]
~~~

I guess a credit of "-57" is not correct in any case. However it might not be caused by Hono itself. I didn't dig into it any further for the moment.

**Comment by pellmann** [comment]
I think this is how protonj works on the sender side. Each time it tries to send, but has no credits, it decrements its credits count. As soon as it gets credits they will be correct again.

**Comment by sophokles73** [comment]
A negative credit indicates that the link currently has no credit available but has messages in the outbound buffer which will be sent once credit arrives (or not, if no credit gets replenished).

**Comment by ctron** [comment]
Ok, then that it is a normal condition from the protonj perspective.

But is that also ok for Hono? My understanding was that messages will not be accepted when there is no credit.

**Comment by sophokles73** [comment]
Yes, that is the (intended) behavior. Your log snippet does not indicate whether the message has actually being sent or not. My hope is that is has been rejected (because the link has no credit left).

**Comment by sophokles73** [comment]
@ctron how many producers have you created? How many messages/s have they sent to the protocol adapter?

**Comment by ctron** [comment]
If tthe "discarded telemetry" metric is an indicator for that, then the no message had been rejected. As that counter always stayed at zero. Otherwise I can't tell.

I created 2.000 MQTT producers sending one message each second. However in Hono I never saw it reach 2.000 msg/s. **But** I am not sure what and how this happened. There are so many locations where things could have gone wrong. I am currently trying to dig through all of this.

A negative credit just seemed weird to me, something worth looking into.

**Comment by sophokles73** [comment]
> If tthe "discarded telemetry" metric is an indicator for that, then the no message had been rejected. As that counter always stayed at zero. Otherwise I can't tell.

No, this is the metric for the messages that are discarded by the Hono Messaging service.
You should check the MQTT Telemetry Undeliverable metric for the MQTT adapter if you are  connecting to the MQTT adapter (not the Kura adapter, that is). That metric indicates how many messages have been discarded by the MQTT adapter because of lack of credits on its link to Hono Messaging.

**Comment by ctron** [comment]
I can't remember to see anything else than zero there as well. I but I am not 100% sure to be honest.

When I re-test this this week, I will pay specific attention to that. Is there anything else I should watch out for?

**Comment by sophokles73** [comment]
I can't think of anything specific. Make sure to use latest master though ...

**Comment by sophokles73** [comment]
@ctron can we (i.e. you) close this issue?

**Comment by ctron** [comment]
I haven't see this anymore. Let's close it.
