### ISSUE TITLE
EnMasse integration

### ISSUE THREAD

**Issue by dejanb** [eclipse/hono#408]
Provide an option for deploying Hono together with EnMasse

**Comment by dejanb** [comment]
Relevant PR https://github.com/eclipse/hono/pull/399

**Comment by sophokles73** [comment]
@dejanb is this fixed with 58c99a0ca921388f9b8b023e13b122e64d075dda

**Comment by sophokles73** [comment]
@dejanb are you still working on this?

**Comment by dejanb** [comment]
This should be now all merged to master branch
