### ISSUE TITLE
Reduce example code in documentation and provide it inside Hono's codebase instead

### ISSUE THREAD

**Issue by sysexcontrol** [eclipse/hono#409]
For arbitrary clients of Hono, we have a tutorial how to write a simple client with minimum dependencies to Java artifacts:
- http://localhost:1313/hono/user-guide/java_client_sender/
- http://localhost:1313/hono/user-guide/java_client_consumer/

While this is fine for enabling new developers quickly to write their application that uses Hono, this constantly needs to be updated.
And since it is documentation only, there is never a compilation or test failing if something needs to be updated.

This led to the current situation that the description is not valid anymore and just does not work.

New strategy should be:
- provide the java application with minimum dependencies inside the Hono codebase
- reduce documentation and do not fully "develop" a java application in the tutorial, but only reference the provided java application

**Comment by zubairhamed** [comment]
Although I can apprecate the documents falling into atrophy, I have found the docs to be immensely useful, going back to it often and over and over, so do consider not reducing the docs too much :)

**Comment by sysexcontrol** [comment]
@zubairhamed : thanks a lot, glad you found the docs so useful!
May I ask you to have a look at the now published version and if you are missing things that were previously useful, drop a comment or better even write an issue for that?
Thanks for cooperation to get things as good as possible!

**Comment by sysexcontrol** [comment]
Done with 30b80e4.
