### ISSUE TITLE
REST Adapter: returns 500 when credentialsClient has no credits yet

### ISSUE THREAD

**Issue by herfort** [eclipse/hono#418]
During the tests of nightly version after fix of #391, I found a  next problem. The REST Adapter returns now error code 500. 
See attached log of REST Adapter
[rest-adapter.log](https://github.com/eclipse/hono/files/1501627/rest-adapter.log)

**Comment by sophokles73** [comment]
the message being logged (`bad credentials`) suggests that the credentials provided by the client cannot be parsed. Does your client include a tenant in the username, e.g. as in `peter@DEFAULT_TENANT`?

**Comment by herfort** [comment]
This is correct. Our negative authentication test sends "someuser" without tenant as username. This was changed now on the IoT Hub site.

**Comment by sophokles73** [comment]
fixed in 609d20a2ee4a2eab7e1fe0f0b9b9c06496125150
