### ISSUE TITLE
Hono doesn't load PEM keys if file doesn't have the suffix `.pem`

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#426]
Currently Hono doesn't load PEM keys from a file unless the file also ends with the suffix `.pem`.

As OpenShift creates keys with the filename `tls.key` and `tls.crt`, this rules out an easy integration [1]

My proposal would be to add a parameter to the loader which allows specifying the file type explicitly. If the type is `null` the current detection will be used. Otherwise the explicit type. The type is `null` by default, but can be configured alongside the file name.

[1] https://docs.openshift.com/container-platform/3.6/dev_guide/secrets.html#service-serving-certificate-secrets

**Comment by ctron** [comment]
Ok, the problem goes a bit deeper. Hono expects the PEM files to actually be PKCS#8. Whereas OpenShift provides keys as PKCS#1.

Those can be loaded easily using Netty (which already is a dependency on the module anyways):

~~~java
import io.netty.handler.ssl.PemPrivateKey;
privateKey = PemPrivateKey.valueOf(Base64.getMimeDecoder().decode(temp));
~~~

Also those keys start/end with `BEGIN **RSA** PRIVATE KEY`, which could also be used to detect if PKCS#8 or PKCS#1 is being used.

As both PKCS#8 and PKCS#1 may use `.pem` as suffix. But also use others, it makes even more sense to me to drop the file suffix detection altogether and focus on providing the key type explicitly. Of course I do understand keeping the current behavior for compatibility reasons.

**Comment by sophokles73** [comment]
Sounds interesting. Maybe you want to create a PR?

**Comment by sophokles73** [comment]
fixed in https://github.com/eclipse/hono/commit/a801d867858a197a0dd40149c70712ce21690254
