### ISSUE TITLE
Create Grafana dashboard and datasource from JSON

### ISSUE THREAD

**Issue by pellmann** [eclipse/hono#428]
To get rid of the binary database file, the Grafana dashboard should be saved/stored as JSON and imported in Grafana at deployment time. Same for the datasource.

**Comment by sophokles73** [comment]
@pellmann is this done? Can we close this issue?

**Comment by pellmann** [comment]
https://github.com/eclipse/hono/commit/2690db33a96cbcbdc3453fb5eb3527f3da8af2b4
