### ISSUE TITLE
HonoServerTest fails intermittently on Travis CI

### ISSUE THREAD

**Issue by hekonsek** [eclipse/hono#43]
From time to time [1] Hono Server tests are failing for reasons similar to those:

```
Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.756 sec <<< FAILURE! - in org.eclipse.hono.server.HonoServerTest
testTelemetryUpload(org.eclipse.hono.server.HonoServerTest)  Time elapsed: 3.46 sec  <<< ERROR!
java.util.concurrent.TimeoutException: Timed out
	at org.eclipse.hono.server.HonoServerTest.testTelemetryUpload(HonoServerTest.java:214)
```

This happens only in CI environment. I didn't manage to reproduce this issues on my local machine.

[1] https://travis-ci.org/eclipse/hono/builds

**Comment by sophokles73** [comment]
Yes, I am also (infrequently) running into problems running this test locally, e.g. when I enable FINEST logging for vertx-proton. I have done some tests using Qpid JMS instead for the test driver (e.g. for connecting to the Hono Server instance) and that seems to be much easier to use and in general seems to be a better fit with the standard threading model used in unit tests.

@dguggemos: I think it would be worth a try to use Qpid JMS for the integration tests you are working on as well ...

**Comment by dguggemos** [comment]
I'll give it a try in the integration tests.

**Comment by hekonsek** [comment]
Actually the testing code is fine, we just need to synchronize it a little bit. I've just used Awaitility [1] in unit tests on my local machine and it seems to resolve the timeout problems. I used Awaitility to block execution until certain callbacks are invoked.

I have created [2] those [3] three [4] CQs for Awaitility. I will commit my tests stability improvements as soon as we got them approved.

[1] https://github.com/jayway/awaitility
[2] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11430
[3] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11428
[4] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11429

**Comment by dguggemos** [comment]
As far as I can see the Qpid JMS client does not (yet?) support the AMQP 1.0 flow control? Maybe someone can confirm this? So I can send and receive messages using the JMS client, but I think for telemetry the flow control is important.

**Comment by sophokles73** [comment]
I have tested flow control support in the Qpid (AMQP 1.0) JMS client yesterday ni conjunction with the `TelemetryEndpoint`. It seems like I did not use manual flow control in the Proton Receiver correctly. I have no fixed this and from my point of view, the JMS client correclty supports sender flow control. I do not know about the other way around, i.e. when you use the JMS client to receive messages from another AMQP node, though.
I will push my fix for `TelemetryAdapter` in the next hour ...

**Comment by sophokles73** [comment]
I have created a CQ for [Qpid JMS](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11469) ...

**Comment by dguggemos** [comment]
@hekonsek where do you block/wait in the tests to resolve the timing problems? Because I'm facing a similar issue when executing multiple unit tests subsequently. Actually that's the reason why the `RegistrationTest` is `@Ignored`. Most of the time the test fails if `HonoServerTest` did run before.

**Comment by hekonsek** [comment]
Actually my waiting fix doesn't help for all the cases. I managed to reproduce the issues :( . Currently I'm trying to debug this.

**Comment by dguggemos** [comment]
We made some stabilizations to the way

**Comment by dguggemos** [comment]
Tests seem to be stable now, closing this issue.
