### ISSUE TITLE
Credentials API: The `auth-id` should be validated to not contain certain special chars

### ISSUE THREAD

**Issue by Christian-Schmid** [eclipse/hono#430]
Currently it is possible to create credentials with an `auth-id` containing values like `:` and `@`.
Such values lead to problems when later on used in for example in http basic auth headers. 
See https://stackoverflow.com/questions/11612854/http-https-basic-authentication-colon-in-username 

I would suggest to extend the validation to dissallow for such ids in the `org.eclipse.hono.service.credentials.BaseCredentialsService<T>` class

**Comment by sophokles73** [comment]
Well, this problem only exists with HTTP Basic auth but not necessarily for other authentication mechanisms, e.g. using username/password in MQTT should not be a problem at all with a username containing a colon.

So I am not sure if we should prohibit such authentication identifiers altogether or should just issue a warning in the response indicating that this auth-id will not be usable with HTTP Basic auth.

**Comment by Christian-Schmid** [comment]
Good point, other protocols might have other restrictions. So basically I see two options: 
a) We just add a hint in the documentation that one should use an identifier which will work with all desired adapters.
b) We define a rather restrictive pattern (maybe just `[a-zA-Z0-9_]`) which will probably fit _most_ of the time.

I'm fine with both :-)

**Comment by sophokles73** [comment]
Since we cannot anticipate all potential protocols and their particular restrictions regarding the authentication identifier, I would rather go for option a) and include a corresponding note in the Credentials API spec.
