### ISSUE TITLE
Mismatching statistics

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#439]
To me it looks like as if there is a mismatch in statistics:

![image](https://user-images.githubusercontent.com/202474/33947016-a0faf3ba-e023-11e7-8ae6-8a3709a77e77.png)

It looks like the formula summing up the "total" adds the last known value of previous instances to the number in addition with a time range of one day.

**Comment by pellmann** [comment]
The time frame for the queries is now always the user selected time frame in the dashboard. So the user could influence the inclusion of old (not running) instances in the numbers. The running instances report each 5 sec in the standard example.
