### ISSUE TITLE
Create Java client API for Hono

### ISSUE THREAD

**Issue by hekonsek** [eclipse/hono#44]
@dejanb:

> having a nice Java API library as a deliverable would, IMHO, help newcomers get started easily with the project (and write their own adapters). So maybe we should think about adding that to list of official artifacts we will deliver and support.

**Comment by ppatierno** [comment]
I suggested this during the last Hono meeting but not many people did agree with me :-(
From my point of you, we provide AMQP APIs but not all devs should know it ... using a Java API library will simplify developing on Hono and its adoption.
At same time I'm quite sure that devs could love having a library on device side too in order to use AMQP APIs but without knowing them (when they don't want to use another protocol for which an adapter is needed).
Totally agree ... of course !

**Comment by hekonsek** [comment]
The Java client doesn't have to be even production-grade. But it will make adoption of the project much easier. What do you think, Kai?

/CC @sophokles73

**Comment by dguggemos** [comment]
In our experience it's difficult to provide a Java Client that fits the various interests e.g. the underlying framework, a possibly constrained runtime environment close to the devices etc.
Nevertheless I agree that we should have a Java Client to get started quickly, but that the AMQP API should be our "major API".

**Comment by hekonsek** [comment]
Just to be clear - AMQP is THE API for Hono. Java client is more like a helper for new developers to make it easier for them to connect to Hono before they feel comfortable with using native AMQP API (which should be the preferred way of using Hono).

**Comment by sophokles73** [comment]
I agree with all of the above :-)
Having a Java client will be helpful and I agree with Dominik and Henryk that the AMQP API is the standard API that we specify (by means of the message exchanges) whereas the Java client is derived from it but should not (initially) be considered optimized and production quality.
Considering that we have very limited resources working on Hono currently I would like to leave it up to the community to evolve this client into any direction the community sees fit.

**Comment by ppatierno** [comment]
@hekonsek it's exactly what I mean ... and totally agree

**Comment by hekonsek** [comment]
+1 Let's keep this ticket open, but just keep in mind that it has low priority.

**Comment by sophokles73** [comment]
The `client` module contains a `vertx-proton` based client that can be used to access the Telemetry and Registration APIs.
