### ISSUE TITLE
Improve adapter logging as device ID is often NULL

### ISSUE THREAD

**Issue by chapitos** [eclipse/hono#445]
In adapter log files (e.g. MQTT adapter) the device ID is often reported as NULL:

14:00:26.628 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.i.AbstractRequestResponseClient - sent request [target address: credentials/HUB_TEAM_TENANT, action: get, device ID: null, message-id: cred-client-70674036-e4e3-4441-8586-96537055510a] to service

Depending whether this information is at hand, the entry for device ID should be either omitted or correctly provided.

**Comment by sophokles73** [comment]
The device ID is `null` when a request of an operation is logged that does not require a device ID param, e.g. a request for retrieving Credentials.
