### ISSUE TITLE
Unble to publish MQTT messages

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#449]
Currently I am unable to publish MQTT messages. I think this issue was introduced by commit f7924edaf94dfc59532d2f6c6717dd79459ec1bd

The behavior is see is:

In the MQT adapter:
~~~
13:42:20.473 [vert.x-eventloop-thread-0] DEBUG o.e.hono.client.impl.HonoClientImpl - reusing existing message sender [target: telemetry/DEFAULT_TENANT, credit: 1]
13:42:20.474 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.TelemetrySenderImpl - message [message ID: TelemetrySenderImpl-422] rejected by peer: amqp:decode-error, malformed message 
~~~

And in the messaging service:

~~~
14:27:42.474 [vert.x-eventloop-thread-2] DEBUG o.e.h.m.HonoMessagingMessageFilter - message [TelemetrySenderImpl-300] has no content type
~~~

Now the check in `org.eclipse.hono.messaging.HonoMessagingMessageFilter.verify(ResourceIdentifier, Message)` requires the "content type" to be set:

~~~java
} else if (msg.getContentType() == null) {
  LOG.debug("message [{}] has no content type", msg.getMessageId());
  return false;
~~~

However the MQTT adapter only calls `org.eclipse.hono.service.AbstractProtocolAdapterBase.newMessage(String, String)` which will always provide `null` as content type.

**Comment by sophokles73** [comment]
Yes, we currently seem to fail to set a fallback content-type when the device does not provide a content type and no default content type has been specified for the device.

**Comment by sophokles73** [comment]
I will provide a fix shortly.

**Comment by ctron** [comment]
Awesome. Thanks for the quick fix!
