### ISSUE TITLE
Error initializing device registry in OpenShift

### ISSUE THREAD

**Issue by dejanb** [eclipse/hono#450]
When running the latest master on OpenShift (Minishift), I'm getting device registry stuck in the "Pod Initializing" phase with the following error

`E0115 12:12:19.364689    2941 kuberuntime_manager.go:662] Error running pod "hono-service-device-registry-1-x099z_hono(b4682834-f9ec-11e7-9c2b-9a0ed4a75289)" init container "copy-example-credentials", restarting: &container.ContainerStatus{ID:container.ContainerID{Type:"docker", ID:"f3a33f8dd8e05e1e056eb6b42136c049751651f3ebf33e0293b0a358ff3d9a7c"}, Name:"copy-example-credentials", State:"exited", CreatedAt:time.Time{sec:63651615121, nsec:935024115, loc:(*time.Location)(0xc042180)}, StartedAt:time.Time{sec:63651615122, nsec:399034980, loc:(*time.Location)(0xc042180)}, FinishedAt:time.Time{sec:63651615122, nsec:475141915, loc:(*time.Location)(0xc042180)}, ExitCode:1, Image:"busybox:latest", ImageID:"docker-pullable://busybox@sha256:436bbf48aa1198ebca8eac0ad9a9c80c8929d9242e02608f76ce18334e0cfe6a", Hash:0x1d55faca, RestartCount:4, Reason:"Error", Message:""}`

This is a placeholder to investigate this further.

**Comment by ppatierno** [comment]
@dejanb can you check the persistentvolumeclaim if it's bounded to a persistent volume when it happens ? Maybe the init-container is trying to access the volume for copying the credentials but it's not bounded.

**Comment by dejanb** [comment]
@ppatierno PEBKAC, I missed the step for creating a directory inside minishift. We need to improve this in the future. I'll open another issue for that for 0.6
