### ISSUE TITLE
Registration assertions seem not to work with the HTTP adapter

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#452]
The HTTP adapter configuration allows to enable "device registry asertions" [1] using `HONO_HTTP_REG_ASSERTION_ENABLED`, which should return a Java Web Token in the HTTP header `Hono-Reg-Assertion`.

However enabling this option doesn't change the HTTP response and also can't I find any reference in the Hono source code which would take care of this functionality. The HTTP header defined is defined in `AbstractVertxBasedHttpProtocolAdapter.java` but never referenced.

Maybe I did something wrong or overlooked it.

[1] https://www.eclipse.org/hono/user-guide/http-adapter/#service-configuration

**Comment by sophokles73** [comment]
We have removed this feature some time ago because from our point of view most clients that we had in mind would not support it anyway. We need to remove the configuration variable from the HTTP adapter docs, though. Thanks for spotting :-)
