### ISSUE TITLE
HonoClient: handle a failed "attach" when creating Consumers/Receivers

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#459]
When using the `createEventConsumer()` or `createTelementryConsumer()`methods on a `HonoClient`, the given `creationHandler` param should fail if the "attach" on the link fails (i.e. "detach" was received).

**Comment by pellmann** [comment]
Should be fixed with https://github.com/eclipse/hono/commit/f4a667aab814e51988d87af2712d6c1faa112871. Could you check?

**Comment by calohmn** [comment]
LGTM. I see the missing handling of `detach(close=false)` is part of a different ticket now (#467).

**Comment by sophokles73** [comment]
@calohmn can you verify and close this issue if the problem is fixed from your point of view?
