### ISSUE TITLE
Provide the possibility to configure a proxy at the Hono Client

### ISSUE THREAD

**Issue by danielbohn** [eclipse/hono#46]
In order to connect the Hono Client to the Hono Server which is located behind the proxy.

**Comment by sophokles73** [comment]
Are you talking about a client that has no transparent access to the network the server runs on? What kind of proxy do you have in mind?

**Comment by danielbohn** [comment]
Yes correct. E.g. my Hono Server runs on a central Docker Host which is only accessible via the DNS name

**Comment by sophokles73** [comment]
I don't think I quite get the problem here. I assume that by *Docker host* you mean the host that the Docker image has been started on, right? That host will probably have an IP address on the BCN, doesn't it? So, why don't you simply connect to that IP address?

**Comment by danielbohn** [comment]
Yes another possibility is to use the IP adress. But I missed something, you are connecting the Hono client via AMQP (TCP) to the Hono Server. So it make no sence to configure a HTTP proxy. I will close the issue. Thanks for the clarification.
