### ISSUE TITLE
Documentation of RESTful resources of Device Registry hard to find

### ISSUE THREAD

**Issue by sysexcontrol** [eclipse/hono#465]
While the current RESTful resources of the Device Registry (to easily administer devices and credentials) are well documented, they are hard to find IMHO.
They are documented at "User Guide / Setup Device Registry", where first the configuration options and the setup of the microservice itself is found (as expected), PLUS the RESTful resources afterwards.

To me, this overloads the page with too much (and then hard to find) information. And I searched myself several times before I found it.

A better structure would be IMHO an extra page with the title "Device Registry - RESTful resources" at the main page "User Guide" as well.

**Comment by sophokles73** [comment]
@sysexcontrol is this fixed?

**Comment by sysexcontrol** [comment]
@sophokles73 : yes, thanks for spotting!

Fixed with 74df3e7 and 0183f1e.
