### ISSUE TITLE
Propagate detach(close=false) back und allow reopen

### ISSUE THREAD

**Issue by pellmann** [eclipse/hono#467]
As a receiver (link) in the Hono client a detach(close=false) needs to be answered the same way and later a open on this detached link need to be handled.

**Comment by pellmann** [comment]
It is needed to reopen (=poll) from the receiver side.

http://qpid.2158936.n2.nabble.com/Link-handling-after-detach-close-false-td7672272.html

**Comment by sophokles73** [comment]
@pellmann is this fixed with your latest commit?

**Comment by pellmann** [comment]
https://github.com/eclipse/hono/commit/d0bb9aa4310ccf68b8079481b51225c157037987
