### ISSUE TITLE
Add ingestion and consumption endpoint for high-priority messages

### ISSUE THREAD

**Issue by dguggemos** [eclipse/hono#47]
Provide an additional endpoint for crucial messages, like alarm messages, which are handled with a higher priority and better better qos (than telemetry messages).

**Comment by sophokles73** [comment]
@dguggemos 

how are you doing regarding this issue? Can we add this to the M2 or M3 milestone?

**Comment by dguggemos** [comment]
The initial version of the `event` endpoint was added, the _Event API_ is documented [here](https://github.com/eclipse/hono/wiki/Event-API).
