### ISSUE TITLE
Improve error reporting for HonoClient for unauthorized/unauthenticated connection attempts

### ISSUE THREAD

**Issue by pho-enix** [eclipse/hono#470]
In my application I use HonoClient to connect to a hono installation with EnMasse as a messaging backend. There is user authentication and authorization (on address level enabled). Unfortunately HonoClient gives different types of error objects on connect():

Unauthenticated:
```
org.eclipse.hono.client.ServerErrorException: failed to connect
```

Unauthorized:
```
io.vertx.core.impl.NoStackTraceThrowable: Error{condition=amqp:unauthorized-access, description='link disallowed by local policy', info=null}
```

As a user of HonoClient I would prefer to see the same error object all the time, preferably with a HTTP like error code (e.g. Forbidden vs. Unauthorized).

**Comment by sophokles73** [comment]
fixed in https://github.com/eclipse/hono/commit/5047ecd697dd6d298f8127f881dc66e635a51dd2
