### ISSUE TITLE
Create OSGi metadata for Hono artifacts

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#475]
It would be helpful if Hono artifacts contain OSGi manifest metdata. This could be achieved by using the maven-bundle-plugin.

**Comment by sophokles73** [comment]
thanks for the help, @ctron :+1:

**Comment by ctron** [comment]
vert.x has merged this.

So the only problematic components seems to be spring. Either we make this optional. Or we could manually align the OSGi metadata with spring 4.x as the Apache ServiceMix project does offer OSGi-fied spring versions.

**Comment by ctron** [comment]
Fixing #478 would also make it way easier this this issue.

**Comment by sophokles73** [comment]
I agree. See my latest comment in #478.
Do you want to give it a shot?

**Comment by ctron** [comment]
Working on #478? Yes, I was hoping for that :wink:

**Comment by ctron** [comment]
So the only missing piece is vertx-proton 3.6.0 now.

I would propose to merge in the OSGi metadata generation anyway. Leaving this issue open until we switched to vertx-proton 3.6.0+ and live with the fact that we ship ugly OSGi metadata until then.

**Comment by sophokles73** [comment]
> and live with the fact that we ship ugly OSGi metadata until then.

Why would the OSGi metadata be ugly?

**Comment by ctron** [comment]
Because it would create an import of "io.vertx.proton" with no version, which currently no bundle could provide. Unless you are using Karaf with the "wrap" option.

However, once we update the dependency of vertx-proton, that issue would be gone with no further change on the maven OSGi settings on our side.

**Comment by ctron** [comment]
> The bad thing being that nobody can currently provide the package, right?

Correct. But as I mentioned, Karaf can handle this using the "wrap" deployer [1], so depending in the specific OSGi container/distribution, this may or may not be a problem.

[1] https://karaf.apache.org/manual/latest/#_wrap_deployer

**Comment by sophokles73** [comment]
@ctron is this issue fixed with https://github.com/eclipse/hono/commit/dacbdbd5517fb9ab72ddbc20800b40353939787a ?

**Comment by ctron** [comment]
It kind of is. We could leave this issue open though until we use vertx 3.6. Referencing this to some vertx 3.6 tracking issue which we need for the MQTT client cert issue as well.

**Comment by sophokles73** [comment]
Will we change anything in the affected components (core, client) once vert.x 3.6 is released and includes OSGi manifest headers?

**Comment by ctron** [comment]
No

**Comment by sophokles73** [comment]
Then why would we want to keep this issue open?

**Comment by ctron** [comment]
Because the ultimate goal of having complete and shiny OSGi metadata has not been achieved yet. So the issue is not fully solved. Although the only thing this issue can do is waiting.

If you prefer to close it anyway, I am fine with that as well.

**Comment by sophokles73** [comment]
FMPOV the goal of this issue is achieved. I would be totally fine with creating a follow up issue for *Upgrade to vert.x 3.6.0* and add a link to it to this issue. But then, IMHO, we should close this issue.
