### ISSUE TITLE
Remove Hono Client dependencies on Spring Framework

### ISSUE THREAD

**Issue by avgustinmm** [eclipse/hono#478]
I order to minimize Hono client (hono-core & hono-client) dependencies on other libraries (in order to be easier for users to integrate it into their frameworks) it will be good to remove dependency on Spring Framework and stick to that in the future (if there is no real reason to add such dependency). Motivation:
1. It is always good to have as little dependencies as possible
2. Spring framework is not really needed. The only uses are:
  -  SpringUtils.isEmpty() which could be easily replaced with something like:
`public boolean isEmpty(String str) {`
` return str == null || str.length() == 0; // or str == null || str.isEmpty()`
` }`
 Note that SpringUtils.isEmpty() checks objects (not strings only) but Hono client uses it only for strings (as far as I understand).
  - For Cache manager API which is used to hold named caches. This could be easily replaced (if I'm not missing something) with a lightweight abstraction like:
 ` interface  CacheManager {`
 `   Cache getCache(String name);`
 ` }`
 ` interface Cache<K, V> {`
 `    void put(K key, V value);`
 `    V get(K key);`
 `    void evict(K key); // or invalidate `
 ` }`
   This could be instantiated wrapping Spring cache manger or other cache implementation, e.g. Guava cache. If you do that you will support easier integration of other caches (not Spring only) and it will be a benefit for the users.

**Comment by sophokles73** [comment]
I agree that we can define our own cache abstraction and get rid of the (compile time) dependency on Spring. Would you like to prepare a PR for the changes you suggest?

**Comment by sophokles73** [comment]
Maybe we could simply move the `SpringBasedExpiringValueCache` to the `hono-service-base` module and replace the remaining `StringUtils.isEmpty()` method invocation.

The Spring based cache is mainly used in the Protocol Adapters anyway ...

**Comment by ctron** [comment]
Giving this a first look, the cache is also present in `HonoClientImpl`, `RegistrationClientImpl` and `TenantClientImpl`. So I guess simply moving stuff away to `hono-service-base` isn't good enough.

My proposal would be to create a cache abstraction interface in `hono-core` and do a thin spring implementation layer in `hono-cache-spring`. Defaulting the client to not use caching.

I will prepare this in a feature branch and create a PR once it is complete.

**Comment by sophokles73** [comment]
fixed in https://github.com/eclipse/hono/commit/b8583ba7bcce1d15391efc8a45171af03f5184ba
