### ISSUE TITLE
Implement connection failover strategy for Hono Server

### ISSUE THREAD

**Issue by dguggemos** [eclipse/hono#48]
Implement failover strategy for client connections between Hono Server and Qpid Dispatch Router. To keep it simple we could start by detecting the connection loss and reconnect to another node of the router network. May we can the circuit breaker pattern for this purpose? Suggestions and ideas welcome!

**Comment by sophokles73** [comment]
We are currently following a simple approach:
1. Client detects (hopefully) that the server is gone (`ProtonConnection.disconnectHandler()` should fire in this case).
2. Client looks up the server using DNS (DNS caching is disabled on all components) and re-connects to the resolved server IP.

**Comment by sophokles73** [comment]
`HonoClient` provides means to register a handler for the event that a connection fails.
we currently use this to re-connect to a service instance resolved via DNS.
