### ISSUE TITLE
Command and Control API : response status

### ISSUE THREAD

**Issue by ppatierno** [eclipse/hono#49]
Hi,

I like too much the idea to use HTTP status code (in the REST style) for status in the response of device registration API.
Why don't we use it in the same way for command and control API instead of just a 0 or 1 as status ?

For example : 

200 command executed and the response has a payload
204 command executed but no payload
202 command accepted (it could be useful for long running command on the device)

405 method not allowed (method in terms of command sent to the client)
400 bad request

.. and so on ...

what do you think ?

Paolo.

**Comment by sophokles73** [comment]
Makes total sense to me and we already use HTTP status codes for the Registration API.
I agree that we should use them for the C&C API as well. However, we haven't started working on it (yet) so the current documentation does not reflect this insight yet.

**Comment by dguggemos** [comment]
Maybe we can provide the suggested "feedback channel" (see #18) via the `202 ACCEPTED` response, which means the device has accepted the command for processing. Once the command was executed another response is sent e.g. `200` or some `4xx` in case an error occurred.

**Comment by ppatierno** [comment]
Yes it makes sense. The device could reply directly with something like 200 with result for a very quick and already executed command. It could reply with 202 in order to mean "command accepted" but not executed yet (i.e. long running or planned to run on the device, it depends on device side). After a while the device could send a message with 200 and the related result.

**Comment by pellmann** [comment]
@ppatierno - I think the response status codes of the Command and Control API in 0.6 fulfill this issue. Can we close this issue? https://www.eclipse.org/hono/api/command-and-control-api/#status

**Comment by sophokles73** [comment]
@ppatierno can we close this issue? I agree with @pellmann in that the current C&C API actually does what you proposed ...
