### ISSUE TITLE
HonoClient does only re-connect one time if no disconnect handler was provided in connect()

### ISSUE THREAD

**Issue by DanielMaier-BSI** [eclipse/hono#493]
Hi,

when I use hono client connect() without disconnect handler, re-connection just works fine for the very first time. But when client looses connection again there are no more re-connects. As JWT token expires every 10 minutes, hono clients configured like this do never re-connect after 20 minutes. This is also already mentioned #239 

Problem seems to be that when no disconnect handler is set, a handler gets set for reconnect that just invokes onRemoteDisconnect(): https://github.com/eclipse/hono/blob/6777c3e048a46d95c7985d441c7ac485eeb23858/client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java#L251-L269

Then during next re-connect, disconnect handler is not longer null and gets invoked, i.e. onRemoteDisconnect gets invoked. However, before invocation, connection gets set to null. But now failed connection and current connection (which is null now) are not the same and re-connect stops with a warn log statement: 

https://github.com/eclipse/hono/blob/6777c3e048a46d95c7985d441c7ac485eeb23858/client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java#L241-L249

Was there a reason why reconnect gets called with a disconnect handler, even when the user did not set one? Why not just invoke reconnect with null disconnect handler?

Thanks 
Daniel

**Comment by sophokles73** [comment]
Hmmm, I tend to agree with your analysis and consider this a bug. It indeed doesn't seem to make much sense to invoke the *reconnect* method with a disconnect handler when the client originally did not provide one.

**Comment by sophokles73** [comment]
Just to make sure:  you are not experiencing this problem when the client does indeed provide a disconnect handler, right? The protocol adapters provide one that simply invokes *connect* again. At least I haven't seen them having any problems re-connecting after the token has expired for the second time.

**Comment by DanielMaier-BSI** [comment]
Exactly, we use setting disconnect handler that reconnects also as a workaround at the moment and problem does not occur in this setup.
