### ISSUE TITLE
Extend MQTT protocol adapter to support shortened topic prefixes

### ISSUE THREAD

**Issue by dejanb** [eclipse/hono#503]
As discussed in Eclipse Integration WG we want to shorten topic prefixes used by MQTT protocol adapter, in order to decrease message sizes.

`telemetry/` -> `t/`
`event/` -> `e/`

**Comment by ppatierno** [comment]
Interesting but ... are we really saving space decreasing by 5 to 10 bytes ? Considering that most of the communication should be encrypted (so on TLS) between devices and adapter I don't see a really advantage on doing that. The TLS overhead increase the message size itself.

The great advantage comes with MQTT v5 where after publishing on a topic, the next PUBLISH can have a zero length topic and the broker will publish on the same topic as before. Btw we don't have MQTT v5 ... yet

**Comment by sophokles73** [comment]
> The great advantage comes with MQTT v5 where after publishing on a topic, the next PUBLISH can have a zero length topic and the broker will publish on the same topic as before

Agreed. In the meantime, the Kapua folks considered it worthwhile to shorten the prefixes. FMPOV the MQTT adapter should simply support both the original prefixes as well as the shortened ones so the device can use whatever it feels comfortable with.

**Comment by ppatierno** [comment]
Agree. If it comes from a real needed for Kapua + Kura (maybe ?) then it's fine.
