### ISSUE TITLE
Support notifications on device connection status

### ISSUE THREAD

**Issue by dejanb** [eclipse/hono#506]
Hono should provide means for other applications to be notified about changes in device connectivity status. This can be for example be used to trigger sending of a commands only when the device connects. Hono should guarantee notifications of devices connecting to the protocol adapter, but is only required to send notifications about disconnects on the best effort basis.

**Comment by sysexcontrol** [comment]
Now implemented by all commits refering to the PRs #535 , #565 and #576.
