### ISSUE TITLE
Define device connection notifications

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#535]
This is a sub-task of #506

In order to close #506 we need to define an API (services, addresses, messages, …) on how the device connection notifications should look like.

**Comment by ctron** [comment]
We are currently running a discussion around that on the mailing list: https://dev.eclipse.org/mhonarc/lists/hono-dev/msg00753.html

**Comment by sysexcontrol** [comment]
@ctron : I made a PR for discussion only #537 with a seq diag containing a possible message flow (including your ideas mentioned on the mailing list). Can you have a look and comment? Thanks!

**Comment by ctron** [comment]
Continuing from the mailing list:

>    > Properties:
>    >     content-type = "hono/connectivity"
>
> "hono/notification"

My idea behind the content type was to use "notification" as address, but be more specific with the message (`hono/connectivity`). If we have others, the consumer could filter based on that.

>    >    subject = "connected" | "disconnected"
>
> "connect" | "disconnect"

I used "connect" and "disconnect" initially. I am fine with both. But having the past tense seemed more appropriate as the event did already happen. "connect" and "disconnect" could be misinterpreted as a request to connect/disconnect. But I am fine with both.

>    > Application Properties
>    >     device_id = <device id>
>    >     tenant_id = <tenant_id>
>
>
> We have the tenant already in the address and with other APIs defined on a tenant base, we require  > only the device_id to be avail
> as application property.
> So: I would skip the tenant_id here.

I agree we could drop the tenant ID. But I followed the "standard response properties" of the device registry [1], which includes it.

[1] https://www.eclipse.org/hono/api/device-registration-api/#standard-response-properties

**Comment by sysexcontrol** [comment]
> My idea behind the content type was to use "notification" as address, but be more specific with the message (`hono/connectivity`). If we have others, the consumer could filter based on that.

I see - so  `hono/connectivity` is fine for me.

>I used "connect" and "disconnect" initially. I am fine with both. But having the past tense seemed more appropriate as the event did already happen. "connect" and "disconnect" could be misinterpreted as a request to connect/disconnect. But I am fine with both.

Here I also see your point and agree to that - doesn't make a huge difference, but sounds reasonable.
So: "connected | disconnected" should be the name of the notification :+1: 


> I agree we could drop the tenant ID. But I followed the "standard response properties" of the device registry [1], which includes it.

I know - but this is only in the response. Having said that I have to admit it is a little asymetrical, since the response (in request-response APIs like registration) is sent via a different link that has the tenant in the address again, so it could be skipped there, too. But there might be a reason - @sophokles73 : can you clarify the question why we have the tenant_id mandatory in responses app props, but not in the request app props? Thanks!

**Comment by sophokles73** [comment]
@ctron  @sysexcontrol  is this issue still relevant? or has it been replaced by something else?

**Comment by sysexcontrol** [comment]
@sophokles73 FMPOV we should close this issue.
The PR #584 is just merged and specifies "half" of this issue (quite differently from originally thought).
The other "half" is the specification of the "connected/disconnected" notifications, which would then make sense to cover by a new issue.
So much history in here, I find it quite confusing now.

@ctron do you agree? And if yes, can you close the issue then? Thx.

**Comment by ctron** [comment]
On a second thought … #569 might be covered by this issue as well … so maybe let's close this first as well.
