### ISSUE TITLE
Provide means for centrally managing client authorizations

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#54]
Hono is supposed to make sure that telemetry data flowing downstream, i.e. from devices to the back end, can only be received and processed by consumers that are authorized to do so. For that to work the data needs to be associated with a security context containing, among other things, the subjects representing the device identity and (optionally) the device owner (tenant).

Routing and access decisions can then be made by Hono based on this information. In order to make consistent authorization decisions throughout Hono's components, e.g. Hono Messaging, Dispatch Router and protocol adapters, we need a system/component for centrally managing authorizations. Ideally we do not need to implement such a component ourselves but can instead use an existing one like [KeyCloak](http://www.keycloak.org/) or [Eclipse ACS](https://projects.eclipse.org/proposals/access-control-service-acs-0).

**Comment by dguggemos** [comment]
I just came across this [AMQP specification draft](https://www.oasis-open.org/committees/document.php?document_id=50506&wg_abbrev=amqp) for _Claims-based Security_ which could be a nice abstraction of the underlying authorization component.

**Comment by francois-travais** [comment]
+1 for KeyCloak

**Comment by sophokles73** [comment]
Dispatch Router will probably be extended to support using a third party component for authentication of clients [1]. Ideally, we would ensure that the mechanism for interacting with the 3rd party service is compatibe with or even the same as the one we are currently using with the Auth Server.

[1] http://qpid.2158936.n2.nabble.com/dispatch-router-authenticating-against-a-remote-service-tp7664264.html

**Comment by sophokles73** [comment]
requires #580

**Comment by sophokles73** [comment]
Auth Server provides this service to all Hono components as well as to Dispatch Router by means of implementing its *authentication service* API.
