### ISSUE TITLE
Hono and Ditto connect on AMQP

### ISSUE THREAD

**Issue by kuzuilker** [eclipse/hono#548]
Hello. I'm trying to connect hono and ditto on amqp. 

Hono and ditto already running on my pc. My ditto connected to hono.eclipse.org server. 
But ditto didn't connect to my hono. 

Is there a setting I need to make for this connection? 

or where am I making a mistake?

**Comment by kuzuilker** [comment]
I realize some error compiling hono. And i add compile logs.
[error.zip](https://github.com/eclipse/hono/files/1841335/error.zip)

**Comment by sophokles73** [comment]
> I realize some error compiling hono. And i add compile logs.

The zip you attached does not contain a compile log. It is the log written by the deployment script for Docker Swarm. It does not indicate any problem deploying Hono but it does indicate that you are deploying quite an old version of Hono (0.5-M11-SNAPSHOT). Have you tried downloading and deploying the latest released version 0.5 available from the [download page](https://www.eclipse.org/hono/download/)?

**Comment by sophokles73** [comment]
> Hono and ditto already running on my pc. My ditto connected to hono.eclipse.org server.
But ditto didn't connect to my hono.

If Hono and ditto run on the same machine (your local pc) then why do you want ditto to connect to `hono.eclipse.org`? You should configure it to connect to your (local) Hono instance. Please take a look at the [ditto documentation](https://www.eclipse.org/ditto/installation-operating.html) for how to do that.

**Comment by mhumoglu** [comment]
I have same a problem. Ditto and Hono are running in my local. My ditto connected to hono.eclipse.org server but it didnt connect to  hono running in local.

I got response from ditto in following

gateway_1        | 2018-03-26 09:11:15,610 INFO  [7b72f8ab-17d4-4389-80a7-65d91280f727] o.e.d.s.u.d.DevOpsCommandsActor akka://ditto-cluster/user/gatewayRoot/devOpsCommandsActor - Publishing DevOpsCommand <devops.commands:executePiggybackCommand> into cluster on topic <devops.commands:executePiggybackCommand:amqp-bridge>
amqp-bridge_1    | 2018-03-26 09:11:15,640 INFO  [7b72f8ab-17d4-4389-80a7-65d91280f727] o.e.d.s.u.d.DevOpsCommandsActor akka://ditto-cluster/user/devOpsCommandsActor - Received PiggybackCommand: <CreateConnection [type=amqp.bridge.commands:createConnection, dittoHeaders=ImmutableDittoHeaders [{correlation-id=7b72f8ab-17d4-4389-80a7-65d91280f727}], connection=ImmutableAmqpConnection [id=honoverysecrethono, authorizationSubject=ADMINISTRATE, sources=[telemetry/DEFAULT_TENANT], failoverEnabled=false, uri=amqp://consumer@HONO:verysecret@0.0.0.0:15671, protocol=amqp, username=consumer@HONO, password=verysecret, hostname=0.0.0.0, port=15671]]> - telling to: </system/sharding/amqp-connection>
gateway_1        | 2018-03-26 09:11:15,727 INFO  [7b72f8ab-17d4-4389-80a7-65d91280f727] o.e.d.s.u.d.DevOpsCommandsActor$DevOpsCommandResponseCorrelationActor akka://ditto-cluster/user/gatewayRoot/devOpsCommandsActor/7b72f8ab-17d4-4389-80a7-65d91280f727 - Got ReceiveTimeout, answering with all aggregated DevOpsCommandResponses and stopping ourself..
gateway_1        | 2018-03-26 09:11:15,729 INFO  [3cf6fb86-9230-474d-8f0b-e1d7b0cbcf26] o.e.d.s.g.e.d.RequestResultLoggingDirective  - StatusCode of request POST '/devops/piggyback/amqp-bridge' was: 408


I sent message from postman to ditto in following

"targetActorSelection": "/system/sharding/amqp-connection",
    "headers": {},
    "piggybackCommand": {
        "type": "amqp.bridge.commands:createConnection",
        "connection": {
            "id": "honoverysecrethono",
            "authorizationSubject": "ADMINISTRATE",
            "failoverEnabled": false,
            "uri": "amqp://consumer@HONO:verysecret@0.0.0.0:15671",
            "sources": [
              "telemetry/DEFAULT_TENANT"
            ]
        }
    }
}

**Comment by sophokles73** [comment]
> I sent message from postman to ditto in following
"targetActorSelection": "/system/sharding/amqp-connection",
"headers": {},
"piggybackCommand": {
"type": "amqp.bridge.commands:createConnection",
"connection": {
"id": "honoverysecrethono",
"authorizationSubject": "ADMINISTRATE",
"failoverEnabled": false,
"uri": "amqp://consumer@HONO:verysecret@0.0.0.0:15671",
"sources": [
"telemetry/DEFAULT_TENANT"
]
}
}
}

At least one of the problems you are facing is that the Hono URI does not contain a proper IP address/host name. `0.0.0.0` is the wildcard address which can be used to specify that a server socket should bind to all (local) network interfaces but which cannot be used to connect to a socket. You need to specify the IP address or hostname of the host where Hono is running.

**Comment by kuzuilker** [comment]
This problem solved. 

if you connect ditto and hono on amqp bridge. you must give acces permint to hono ip adress.

like this:

mvn spring-boot:run -Drun.profiles=authentication-impl -Drun.arguments=--hono.auth.amqp.bindAddress=<your local ip adress>,--hono.auth.amqp.keyPath=target/certs/auth-server-key.pem,--hono.auth.amqp.certPath=target/certs/auth-server-cert.pem,--hono.auth.amqp.trustStorePath=target/certs/trusted-certs.pem


thank you @sophokles73
