### ISSUE TITLE
HonoClient : qos and application properties

### ISSUE THREAD

**Issue by ppatierno** [eclipse/hono#55]
Hi,

I see that the creation of a sender by the HonoClient doesn't allow to specify the QoS but it uses AT_MOST_ONCE internally. Hono API supports telemetry with AT_LEAST_ONCE delivery, so it could be good to add this possibility to the HonoClient.

The other point is that the TelemetrySender class provides more overloads of "send" method but not one with possibility to pass "application properties". Of course, the user can use the overload with Message as parameter but he has to deal with AMQP message structure. It could be good to have an overload with a Map for application properties. In my experience, sometimes users prefer to use application properties and not payload to carry information.

What do you think ? If you agree I can take care about that :-) 

Paolo.

**Comment by sophokles73** [comment]
`HonoClient` itself doesn't create any senders. This is done implicitly by either `TelemetryClientImpl` or `RegistrationClientImpl`. They both use the QoS that we have specified for the respective APIs. Why would we need to let client code specify the QoS?

Regarding the application properties for the `TelemetryClient` I agree with you. It would be great if you could add this :-)

**Comment by ppatierno** [comment]
Yes I was referring to the TelemetryClientImpl ... but does telemetry API support AT_LEAST_ONCE delivery as well ? The snd-settle-mode as "unsettled" is allowed based on what I read.

**Comment by sophokles73** [comment]
`TelemetryClientImpl` uses AT_MOST_ONCE. On the server side (`TelemetryEndpoint`) we ignore a client's preference to use AT_LEAST_ONCE, i.e. we still accept the data being sent but do not send disposition frames (at least that is the intention).

**Comment by ppatierno** [comment]
What you said exaplain me this code that was useless to me (just for debugging) :-) 

`if (ProtonQoS.AT_LEAST_ONCE.equals(receiver.getRemoteQoS())) {
            LOG.debug("client wants to use AT LEAST ONCE delivery mode, ignoring ...");
        }`

Btw I see that even using AT_LEAST_ONCE, the disposition frame is sent to the sender.

The other point to summarize is that we support only "fire and forget" for telemetry but at AMQP level we accept QoS 0 and QoS 1 even if we should not send disposition in the second case. It seems to me something that breaks the AMQP spec. We are defining a "fire and forget" at high level based on both QoS 0 and QoS 1 provided by AMQP at lower level but Hono API is AMQP based so I think we should be compliant with that. 

We could change API to not support snd-settle-mode as mixed or unstelled but only settle to be sure having always the AMQP semantic of AT_MOST_ONCE.

At least ... it wasn't so clear to me from the Wiki :-)

I hope I was clear in my explanation :-)

**Comment by sophokles73** [comment]
IMHO it doesn't make any difference from Hono's perspective whether the client sends its messages settled or not. That is because Hono doesn't care whether a client wants to re-transmit a message or not because Hono does not even try to detect duplicates but instead simply forwards every message it receives to the downstream container. In both cases Hono uses rcv-settle-mode *first*.
If we only support AT_MOST_ONCE then a client using Qpid JMS client would need to open two connections to Hono if it wanted to access both the Telemetry and Registration API because Qpid JMS client only allows to configure settle mode per connection :-(

**Comment by ppatierno** [comment]
I agree with you from a Hono point of view.

I was thinking more about that and I think that from an AMQP client point of view it works fine because Hono works in the right way (no disposition sent with AT_MOST_ONCE, disposition sent with AT_LEAST_ONCE). It's just why we don't allow to specify the different QoS in the TelemetryClientImpl ... I guess it's just because we abstract the underlying layer and there is no difference from Hono point of view so just use AT_MOST_ONCE (but it would work fine even with AT_LEAST_ONCE).

So for what you say about JMS ... a JMS client should open the connection with AT_LEAST_ONCE for having both Telemetry and Registration ... damn :-(

**Comment by sophokles73** [comment]
Maybe you can fix that in Qpid JMS client :-) I don not see why it shouldn't be possible to configure it per Destination instead of Connection.

**Comment by ppatierno** [comment]
Yes I agree with you !

**Comment by ppatierno** [comment]
It should be done with PR #56

**Comment by sophokles73** [comment]
@ppatierno,

I have merged #56, can you close this issue?
