### ISSUE TITLE
Bruteforce Protection for Protocol Adapters

### ISSUE THREAD

**Issue by pho-enix** [eclipse/hono#551]
Hello Hono Community

We are running a Cloud Service based on Eclipse Hono, providing device connectivity.

During a security audit we discovered that there is no built-in mechanism is Hono to protect against attackers trying out arbitrary password combinations.

Right now this is an issue, because the attacker could probe those combinations until there is a successful authentication.

This might become a even bigger issue, as soon as Hono or Hono derived implementations will implement more expensive hashing and secret validation algorithms (e.g. pbkdf2). Then the server side would suffer from significant processing load.

I am not sure if a simple ban mechanism is sufficient for this use-case: An attacker might DoS a device by flooding the service with invalid authentication requests.

I am looking forward for interesting discussions.

**Comment by sophokles73** [comment]
Just to be clear, we are talking about attackers trying to use any of the protocol adapters to publish data on behalf of a device, right?
Assuming that this is what you have in mind, then I guess that the current protocol adapters indeed do not prevent attackers from continuously trying to authenticate using arbitrary credentials.

**Comment by pho-enix** [comment]
Exactly, this is not about the Device Registration or Credentials API.

Preferably the solution would be generic, so not each PA has to implement its own bruteforce protection.

For our use-case we would like to ban clients which exceed a specific number of failed authentication requests based on theirs source ip address. But there might be scenarios where another differentiator might me more useful (for example the device id in Gateway Mode).

I would suggest to extend the SASL request towards Authentication API by something like a `origin` property. The Authentication API could then do bookkeeping of failed authentication requests. If the limit is exceeded, further requests from the same origin can be delayed and rejected without validation.

**Comment by sophokles73** [comment]
> I would suggest to extend the SASL request towards Authentication API by something like a origin property. The Authentication API could then do bookkeeping of failed authentication requests. If the limit is exceeded, further requests from the same origin can be delayed and rejected without validation.

This will not help with the problem because the protocol adapters authenticate the devices using information retrieved from the Credentials API. The Authentication service is only used for authentication of Hono components to each other. So, the bookkeeping will probably need to be done by the protocol adapters, which may turn out to be tricky because a device will most likely connect to another adapter instance on each attempt it conducts.

**Comment by pho-enix** [comment]
Yes, the fact that the actual validation of credentials happens in the PAs does make the whole scenario more complex.

However I think for a first step doing (service instance) local bookkeeping could be quite fine.

If someone runs a tiny eval setup with only one instance that's fine anyways.
If there is a larger scale setup then traffic locality will be a must-have. Otherwise there will be significant performance drawbacks.

At least for our setup I can see the scenario that an attacker can only be identified and banned by its source ip address. On the cluster level there should be source address aware routing, to ensure that traffic from one source address always gets routed to the very same node. On the service level there should be locality too, so it is taken care of that traffic for one device always gets processed on the same instance of the PA.

This concept could later on be extended by a shared state store.

**Comment by DanielMaier-BSI** [comment]
One problem of IP based banning could be that in deployment setups where hono gets operated behind load balancers source IP might not be available.

I think the only generic approach inside hono is to ban accounts with failed login attempts, without regarding source IP. If someone needs source IP based bans, this probably needs to be done in front of protocol adapter (aligned to deployment setup and perhaps protocol specific).

Of course we would introduce a new attack vector with this solution. An attacker might just guess usernames (if he knows tenant id) and he is able to lock out some devices.

This leads me to the question: Can this issue be solved within hono at all in a generic approach? What do you think?

**Comment by ctron** [comment]
I think one simple step to improve this situation could be to delay a response in the case of a failed authentication. Thus slowing down the attacker. A simple implementation could be done without storing any state.

**Comment by pho-enix** [comment]
@ctron I really like this first approach. It will be simple to implement and shouldn't raise any other attack vectors like DoS.

How will we deal with parallel requests in this case? Maybe we can restrict the validation of credentials to one operation per auth-id. This would even go very well with scaled deployment setups (due to the fact that load balancers might balance different source IP address to different service instances).

**Comment by pho-enix** [comment]
Hi @ctron would this be the place to do the change? I wanted to test this in my setup, but I was using a 0.5 hono core with a 0.6 adapter which does not work of course :(

```
diff --git a/service-base/src/main/java/org/eclipse/hono/service/auth/device/HonoAuthHandler.java b/service-base/src/main/java/org/eclipse/hono/service/auth/device/HonoAuthHandler.java
index 2ad8be7..835e796 100644
--- a/service-base/src/main/java/org/eclipse/hono/service/auth/device/HonoAuthHandler.java
+++ b/service-base/src/main/java/org/eclipse/hono/service/auth/device/HonoAuthHandler.java
@@ -18,6 +18,7 @@ import java.util.Set;
 import java.util.concurrent.atomic.AtomicBoolean;
 import java.util.concurrent.atomic.AtomicInteger;
 
+import io.vertx.core.Vertx;
 import org.eclipse.hono.client.ServiceInvocationException;
 
 import io.vertx.core.AsyncResult;
@@ -107,7 +108,9 @@ public abstract class HonoAuthHandler implements AuthHandler {
               }
             } else {
               if (sentFailure.compareAndSet(false, true)) {
-                handler.handle(Future.failedFuture(FORBIDDEN));
+                  Vertx.vertx().setTimer(10000, id -> {
+                      handler.handle(Future.failedFuture(FORBIDDEN));
+                  });
               }
             }
           } else {
```

**Comment by ctron** [comment]
Hi @pho-enix … This could be one way to do it. However you should re-use an existing vertx context instead of creating a new one.

**Comment by pho-enix** [comment]
Sorry for the long quiet time on this.

I had a look on the code again. The code change looks simple on the first glance. But I am afraid it is hard to understand especially in which context it runs. I also didn't find a unittest that would detect potential regressions.

I am not sure how I can achieve progress on this? I will not be capable of doing a proper PR for this.

**Comment by b-abel** [comment]
I think I could provide a PR for the delay of the response after authentication failed (similar to the snippet @pho-enix provided above). Is this still of interest?
And if yes, should we start with a fixed time span or make it configurable?

**Comment by sophokles73** [comment]
One of the reasons why more sophisticated hash functions like Bcrypt are used/recommended, is that by design they require some time to calculate the hash and therefore already provide some implicit *protection* from brute force attacks (simply because each request to test a password takes quite long).

However, this does not prevent an attacker from putting a lot of stress on the protocol adapters this way, which could eventually result in a DOS

**Comment by sophokles73** [comment]
Hono itself does not know which environment it is running in. Thus, there is not much more for Hono to do than what hsa already been done, i.e. using a hash function that makes brute force attacks less attractive.
A DoS attack needs to be prevented by other means, typically at the networking layer.
