### ISSUE TITLE
Protocol connection events

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#565]
In addition to the device notification functionality, we discussed in Berlin that we do need some kind event which notifies of the fact that "someone" (not necessarily a device) connected.

This would be a more "debug" like event and might not make sense for all protocol adapters. It may however make sense for MQTT, where a connection can be successfully established and be kept open for a longer period of time. This might be useful when the device/gateway connections successfully, but doesn't transmit any data over the MQTT link.

The same might be useful for the (hopefully) upcoming AMQP protocol adapter.

This functionality should not be seen as a replacement for the "device notification" feature currently being discussed in #562, #535 and #537.

---

My proposal would be to start with an interface which being called to handle those events. Providing a "logging only" implementation.

---

I tried to re-cap in this issue the discussion we had in the last Hono call, splitting off the "device notification" we need for command & control, vs the MQTT connection notification event we need for better debugging.

**Comment by sophokles73** [comment]
@ctron can we remove the term *alerting* from this issue? It seems to interfere with #502 which is about something different but might be mistaken for this one here.

**Comment by ctron** [comment]
> can we remove the term alerting from this issue? It seems to interfere with #502 which is about something different but might be mistaken for this one here.

We could also send the notifications over this new "alerting" functionality. But we could change the naming of this functionality to not imply the *alerting* functionality has to be used.

**Comment by ctron** [comment]
Maybe "protocol connection events" work better:

*  Actually we are not talking about devices/gateways here, but about connections on the side of the protocol adapter.
*  It is all about the technical connection which got opened with the protocol adapter

**Comment by sophokles73** [comment]
> But we could change the naming of this functionality to not imply the alerting functionality has to be used.

That was my concern.

**Comment by ctron** [comment]
Is the changed title an improvement?

**Comment by ctron** [comment]
Closed by PR #569
