### ISSUE TITLE
Add OpenShift S2I deployment as example

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#570]
I would like to add the OpenShift S2I templates I did create for Hono 0.5 to the Hono master branch. The 0.5 version of this can be seen in the feature branch at my cloned repository: https://github.com/ctron/hono/tree/feature/support_s2i_05x

I do understand that this duplicates code which currently is in a different set of YAML files in different locations of Hono. However I do see this single template more like one big example deployment scenario for Hono.

I am willing to maintain this and ensure that this is working at least for every final release.

In the provided feature branch the code is located under the `openshift` folder in the root of the repository, I would migrate this to `hono/example/src/main/deploy/openshift_s2i`.

Let me know what you think. Any objections or suggestions?

**Comment by ctron** [comment]
Closed by PR #594

**Comment by sophokles73** [comment]
@ctron can we close this issue?
