### ISSUE TITLE
(Docker Swarm/ OpenShift/ EnMasse) Device Registry fails to start

### ISSUE THREAD

**Issue by TheBeachMaster** [eclipse/hono#573]
Hey Team Hono,

OS : Centos 7
Hono-V :  latest from master branch (0.6-SNAPSHOT)

Deployments on OpenShift/EnMasse/Docker Swarm always end up with the same behavior. 
_Device Registry is unable to start_.

I've tried several work-arounds including different deployment environments (OpenShift, Docker Swarm mode, EnMasse) and even provisioned new Centos VMs but it's the same behavior. All containers are running except *busybox*.

See logs attached from a fresh deployment and service list.

[services.txt](https://github.com/eclipse/hono/files/1902403/services.txt)
[logs.txt](https://github.com/eclipse/hono/files/1902404/logs.txt)

I hope this will not be too much of a bother :)

Use [this resource](http://txtformat.com/) to pretty-print the texts.

**Comment by ctron** [comment]
Please see the last comments on #572 for a workaround

**Comment by sophokles73** [comment]
What makes you believe that the Device Registry hasn't started? The logs you provided indicate that it is up and running ...
The services.tx file also indicates that the registry is running:
> 78d498c8c0cb        eclipse/hono-service-device-registry:0.6-SNAPSHOT   "java -Dvertx.cacheD…"   40 minutes ago      Up 40 minutes               5671-5672/tcp, 8080/tcp, 8443/tcp   hono-service-device-registry.1.xnp52pixq8iku148usxilhhpe

**Comment by TheBeachMaster** [comment]
@sophokles73  
 From this  
`[~~##@v~~## docker]# docker ps -a | grep Exited
343387e89af0        busybox:latest                                      "sh -c 'cp -u /run/s…"   3 hours ago         Exited (0) 3 hours ago                                       init-device-registry-data.1.jzra8hcwtxsjp73b9f84dgigj
`

**Comment by sophokles73** [comment]
This just means that the init container has finished its work (copying the example tenants and device credentials to the volume mounted by the Device Registry) and then has exited because there was nothing more to do. The init container is run (and must finish/exit) *before* the device registry container starts up. So, in your case, everything worked as designed FMPOV.

**Comment by TheBeachMaster** [comment]
Whoa okay... 🤔
 
I've always though that this was an error. 
 
Let me start the Consumers then.

Thanks @ctron  and @sophokles73  for the help.

Closing...
