### ISSUE TITLE
Max size of payload for larger content

### ISSUE THREAD

**Issue by zubairhamed** [eclipse/hono#578]
Hi,

The maximum size of payload is set to 2KB by default. Would this mean that use-case where you're sending via event or telemetry a binary image (e.g. a camera) is not an intended use-case?

Z

**Comment by sophokles73** [comment]
It is as much an intended use case as you are able to run with the necessary amount of memory. All messages are ultimately assembled/processed in memory. So if you send a 200kb image in a message, then you will be limited in the number of messages that you can process. However, Hono should be able to limit the message flow based on the *max session window* configuration parameter of Hono Messaging and/or Dispatch Router respectively.

That said, personally, I would not send large binary data via Hono but would instead try to store the data in a (cloud) storage service and only send a pointer (URI) to the data as part of the telemetry/event message ...

**Comment by zubairhamed** [comment]
Since content like Images from, say, a camera can be treated as telemetry, it might make sense that such larger sized payload could come through Hono. Images also can contain metadata and sensor data embedded as well.

e.g. use case of a camera (e..g NestCam) which is continuously capturing video content but as soon as  movement occurs, it would take a frame and send it to the cloud as a Notification (e.g. Event in Hono terms). 

Z

**Comment by sophokles73** [comment]
As I said before, Hono does not *per-se* prevent you from doing this. You can configure the maximum payload size on protocol adapters. However, you will also need to adjust memory and session window size of Hono Messaging and the AMQP messaging network according to expected throughput as well.

**Comment by sophokles73** [comment]
@zubairhamed is your question sufficiently answered so that we can close this issue?
