### ISSUE TITLE
ResourceIdentifier : the device id field isn't always ... a device id

### ISSUE THREAD

**Issue by ppatierno** [eclipse/hono#58]
Hi,

the ResourceIdentifier class is used for every resource in Hono so even when there is a receiver on a address like this : 

registration/[TENAND_ID]/[REPLY_TO]

which is used for receiving reply on a registration request.

The third field in this case isn't a device id as it supposed to be in the ResourceIdentifier class (IDX_DEVICE_ID, getDeviceId() method, ...).

My idea is that field could be defined as "resourceId" (so IDX_RESOURCE_ID, getResourceId(), ...).

The ResourceIdentifier constructor already has a resourceId as parameter that could be just a "resource".

What do you think ?

if you agree I can handle this.

Paolo.

**Comment by dguggemos** [comment]
I remember having this discussion with @sophokles73 a while ago :) Originally I wanted to implement the reply-to with a dynamic address, but this would not work with the Qpid JMS Client. So I "misused" the ResourceIdentifier for this purpose... But now as it's clear that we want to support JMS, we will need this kind of resources at other places, too. So I think it's ok to rename the class.

**Comment by ppatierno** [comment]
Even with the verifyStandardProperties() method (BaseMessageFilter class) a miss understanding is possible because it's called by the RegistrationMessageFilter() but the deviceIdProperty doesn't make sense in that case.

**Comment by sophokles73** [comment]
I hope we do not want to rename the class but the field only :-) However, I have no problem with renaming `deviceId` field to `resourceId`. Makes sense to me. Go ahead, @ppatierno :-)

**Comment by ppatierno** [comment]
@sophokles73 I agree ... the class name makes sense absolutely. I'll do that. ;)

**Comment by ppatierno** [comment]
I have just opened a PR for that #59

**Comment by sophokles73** [comment]
merged in 175f99947a324a07ea1a875cfc7ab7087a075e69
