### ISSUE TITLE
How to deploy Eclipse Hono from Docker Hub to Kubernetes cluster?

### ISSUE THREAD

**Issue by hpham04** [eclipse/hono#587]
I just want to play around with Eclipse Hono to see how it works on my Kubernetes cluster
Can anyone please help to advise

**Comment by sophokles73** [comment]
see https://www.eclipse.org/hono/download/

**Comment by hpham04** [comment]
Thank you so much @sophokles73
I just wonder what we can benefit when deploying this stack on kubernetes

**Comment by hpham04** [comment]
@sophokles73 
I tried to install hono in my kubernetes cluster but it failed
<img width="1075" alt="screenshot 2018-04-20 08 51 45" src="https://user-images.githubusercontent.com/7788448/39026593-252f1e28-4478-11e8-8c12-7ac37b83d7da.png">
Can you please advise how to troubleshoot this
Thank you so much

**Comment by hpham04** [comment]
I use eclipse-hono-example-0.6-M2.tar.gz version
My Kubernetes version is 1.8, not minikube

**Comment by sophokles73** [comment]
@hpham04 can this be closed?
