### ISSUE TITLE
AmqpServiceBase: No errors in log in case secure AMQP server doesn't start because of missing cert

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#590]
We had a scenario where Hono Messaging didn't start because the certificate referenced under "hono.messaging.certPath" didn't exist (we forgot to mount the file in the pod).

This error was not at all obvious though - there was no indication in the log file. This should be improved by adding corresponding error output in the log.

**Comment by ctron** [comment]
This should be fixed by commits 75a45d8a044c18c27cfac569a3fba702c2f5beee and c418256231d6e7956a6959589fd5b6de0b8bc481
