### ISSUE TITLE
HTTP protocoll adapter does not allow to PUT events to path /event/${tenantId}/${deviceId} for authenticated devices any longer 

### ISSUE THREAD

**Issue by DanielMaier-BSI** [eclipse/hono#598]
In https://github.com/eclipse/hono/blob/d0dcfebd7f796185bfd3c5c8c2caf983240c3e9f/adapters/http-vertx/src/main/java/org/eclipse/hono/adapter/http/vertx/VertxBasedHttpProtocolAdapter.java#L128-L153

there is no basic auth handler set for route /event/${tenantId}/${deviceId}, i.e. it is not possible to send events to this path in authentication required mode. I am not sure if this was intended as we have short path with /event for authenticated devices. However for telemetry it is still possible to send to /telemetry/${tenantId}/${deviceId} for authenticated devices.

This needs to be handled consistently fmpov.

**Comment by sophokles73** [comment]
I agree, this seems to be missing. Would you mind creating a PR?

**Comment by DanielMaier-BSI** [comment]
Ok, I will provide a PR for this the next days.

**Comment by DanielMaier-BSI** [comment]
Fixed with #602
