### ISSUE TITLE
Enable Travis CI builds for the project

### ISSUE THREAD

**Issue by hekonsek** [eclipse/hono#6]
Before I commit anything into a project, I have to have at least one CI server monitoring it :) .

I propose to add Travis CI configuration to the project. It allows us to have free CI builds for our project for free. We use Travis for many of our projects here at Red Hat.

**Comment by sophokles73** [comment]
We can either do that or use the existing Hudson infrastructure provided by Eclipse for that purpose. We can get our own Hudson instance (called *HIPP* in Eclipse parlais). Or is there a particular reason why it should/must be Travis?

**Comment by sophokles73** [comment]
Interestingly, I just noticed that Travis CI GmbH (the company offering the service) is located three blocks from where I live in Berlin :-)

**Comment by hekonsek** [comment]
I'm not tell that it must be Travis. However setting up Travis takes about 5 minutes. 

So I would say that we can start with Travis even today and then add Hudson builds if needed. I just would like to have something building our project ASAP :) .

So I can commit Travis configuration even now, if you agree :) . Then somebody with admin rights has to click one button on the Travis page (you can log into it using your GitHub account) and we have CI pipeline up and running.

**Comment by sophokles73** [comment]
Are you saying that we need credentials for the Hono GitHub repo to set up the Travis build?
If that is the case then we need to involve Eclipse Webmasters because we do not have those credentials. They can create a deploy key if that is helpful, though?

**Comment by hekonsek** [comment]
All the Eclipse GitHub admin has to do is to enable the build for the project. This is single-click operation via UI :) . Then we can configure the build itself by changing configuration file committed to the project. 

Do you know who is Eclipse GitHub Webmaster? :)

**Comment by hekonsek** [comment]
I have committed build configuration for Travis. Now we just need Eclipse Admin to press "Enable" button for the Hono project on the  Travis page and we will have CI pipeline up and running.

Do you know who should we contact? :)

**Comment by sophokles73** [comment]
The webmasters are a group of people who govern all of the infrastructure for all Eclipse projects. It's easy to get in touch with them, we simply need to open an issue on Eclipse Bugzilla or send an email to webmaster@eclipse.org.

However, in order to be able to track progress transparently, I think we should open up an issue. You can do that by going to https://bugs.eclipse.org and log in with your eclipse credentials. Then create anew issue under the **IoT** top level project ... I thought this would be a nice exercise for you to get accustomed to the Eclipse environment :-) What do you think?

**Comment by kartben** [comment]
Actually, bugs against Webmaster have their own category: Eclipse Foundation / Community / Github

**Comment by sophokles73** [comment]
Hey @kartben, good to see you here :-) Do you happen to know whether using Travis builds is common practice or are we only allowed to use HIPP instances?

**Comment by kartben** [comment]
A few projects do it, so while not a common practice, there's no reason you shouldn't do it AFAICT.
I would just clone https://bugs.eclipse.org/bugs/show_bug.cgi?id=487344

**Comment by hekonsek** [comment]
I will open the ticket then.

As far as Travis vs HIPP is concerned - actually having more than single CI server is not a bad idea. Some issues can be reproduces only in a certain environments and having multiple build environments can detect such problems early.

**Comment by sophokles73** [comment]
Great :-) Thanks, Henryk (and Benjamin)!

**Comment by sophokles73** [comment]
I have opened an (issue for getting a HIPP instance)[https://bugs.eclipse.org/bugs/show_bug.cgi?id=488955] ...

**Comment by hekonsek** [comment]
Created bugzilla ticket - https://bugs.eclipse.org/bugs/show_bug.cgi?id=489135 .

**Comment by hekonsek** [comment]
Yay! So we have both Travis and Hudsun running. I have added "Build status" section to the main page [1].

Closing!

[1] https://github.com/eclipse/hono#build-status
