### ISSUE TITLE
Hono client fails to authenticate with hono auth service on bad timing even with correct credentials

### ISSUE THREAD

**Issue by DanielMaier-BSI** [eclipse/hono#605]
When I connect with hono client to a hono service, e.g. hono messaging, while hono auth is still in startup phase, authentication with server fails even with correct credentials.

As hono client does not re-connect on authentication issues hono client never recovers from this state. This is especially problematic when we start the whole hono stack after deployment in kubernetes cluster.

Hono client assumes authentication failed on a SecurityException:
https://github.com/eclipse/hono/blob/36808947964c1cb4299008151dd28b8ca52a3542/client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java#L287-L294

But in the case described above hono auth does not reject authentication request actively.

I have added a log statement to hono client to get logged the security exception. The logs are all from the same machine, i.e. you can rely on timestamp order. Affected user is bumlux@HONO. 

In the attached logs ([client.log](https://github.com/eclipse/hono/files/1955090/client.log),[hono-auth-s.log](https://github.com/eclipse/hono/files/1955091/hono-auth-s.log)) you can see:
- hono client gets SecurityException
- hono auth accepts request afterwards

This issue can be reproduced for example by connecting a hono client to a hono service while hono auth service gets restarted.

For me this leads to two questions:
- Is it sufficient to check for SecurityException to assume authentication failed, or do we need more fine grained handling?
- Does hono auth accept requests too early (before setup completely)

**Comment by sophokles73** [comment]
> Does hono auth accept requests too early (before setup completely)

I would say it depends on the platform you're running on. On Docker Swarm this might happen because the service will be resolvable via DNS as soon as Docker has started the container (I believe). On Kubernetes it will be resolvable only once the configured readiness check succeeds. Have you configured a readiness check? In general, though, the verticle implementing the service as well as the endpoint implementation that handles requests, are started before the AMQP listener is bound. So I would assume that once a client can actually connect to the Auth Server's AMQP port, a SASL handshake should be possible.

It would be helpful to see the log output of the Auth Server at the time the client tries to connect.

**Comment by DanielMaier-BSI** [comment]
Here are the full logs of hono auth: [hono-auth.log](https://github.com/eclipse/hono/files/1960440/hono-auth.log)

We have set readiness check on hono auth to check for TCP port 5672. For hono messaging we use the unmodified "/readiness" resource. Indeed I can't find a log statement in our tenant manager that readiness check of DelegatingAuthenticationService was registered. I will investigate this further.

To reproduce this issue the client from the logs above connects to hono messaging from outside of kubernetes (to IP and node port), i.e. does not respect readiness check. So perhaps AMQP connection on TCP layer to messaging is already successful before hono auth is ready? In our real deployment scenario I only observed this behaviour with connections to tenant manager.

 What do you  think about my second question

> Is it sufficient to check for SecurityException to assume authentication failed, or do we need more fine grained handling?

In my point of view the client does nothing wrong here and should not get a client error.

**Comment by DanielMaier-BSI** [comment]
After registering health check for authenticationService in our own tenant manager implementation this issue seems not to occur in our actual deployment any longer. Thanks for this hint @sophokles73 

However, with bad timing, e.g. last readiness check is still OK but connection to authenticationService is actually broken, this issue may still occur. In my artificial scenario I created to reproduce this issue I get a timeout exception in hono messaging (as expected):

``15:18:34.318 [vert.x-eventloop-thread-2] DEBUG o.e.h.s.auth.HonoSaslAuthenticator - initializing SASL authenticator
15:18:34.319 [vert.x-eventloop-thread-2] DEBUG o.e.h.s.auth.HonoSaslAuthenticator - client connected using TLS, extracting client certificate chain
15:18:34.319 [vert.x-eventloop-thread-2] DEBUG o.e.h.s.auth.HonoSaslAuthenticator - could not extract client certificate chain, maybe TLS based client auth is not required
15:18:34.483 [vert.x-eventloop-thread-2] DEBUG o.e.h.s.auth.HonoSaslAuthenticator - client provided an empty list of SASL mechanisms [hostname: null, state: PN_SASL_IDLE]
15:18:34.558 [vert.x-eventloop-thread-2] DEBUG o.e.h.s.auth.HonoSaslAuthenticator - client wants to authenticate using SASL [mechanism: PLAIN, host: null, state: PN_SASL_STEP]
15:18:37.567 [vert.x-eventloop-thread-2] DEBUG o.e.h.s.auth.HonoSaslAuthenticator - authentication failed: Timed out after waiting 3000(ms) for a reply. address: 24, repliedAddress: authentication.in
``
As I mentioned above I think this should not lead to a client error which stops the client from re-connecting.

**Comment by sophokles73** [comment]
When you say
> the client from the logs above connects to hono messaging from outside of kubernetes (to IP and node port), i.e. does not respect readiness check. 

what do you actually mean? Is the client trying to connect to the node IP of the Kubernetes *service* registered for Hono Messaging? If so, then I would expect its connection attempt to the port to fail at the TCP layer until the service's pods are ready, i.e. their readiness checks succeed.

**Comment by sophokles73** [comment]
> After registering health check for authenticationService in our own tenant manager implementation this issue seems not to occur in our actual deployment any longer. Thanks for this hint @sophokles73
However, with bad timing, e.g. last readiness check is still OK but connection to authenticationService is actually broken, this issue may still occur. In my artificial scenario I created to reproduce this issue I get a timeout exception in hono messaging (as expected):

I am sorry, but I do not understand what you are talking about. The logs do not indicate any problem at all to me. Can you be a little more specific regarding the use case/scenario that you experience the problem for?

**Comment by DanielMaier-BSI** [comment]
OK , perhaps we have to go some steps back.

As I am not so deep in the code as you it would help me if you can confirm some assumptions. My observation is and as I understand the code when you connect to a hono service, e.g. hono messaging, and this service fails to reach hono auth, e.g. because of a network timeout, then the client gets a client error with cause unauthorized. Is this correct?

**Comment by sophokles73** [comment]
>  My observation is and as I understand the code when you connect to a hono service, e.g. hono messaging, and this service fails to reach hono auth, e.g. because of a network timeout, then the client gets a client error with cause unauthorized. Is this correct?

HonoClient's connect method fails the returned Future with a ClientErrorException with code 401 if the SASL handshake does not succeed (for whatever reason).

**Comment by DanielMaier-BSI** [comment]
> HonoClient's connect method fails the returned Future with a ClientErrorException with code 401 if the SASL handshake does not succeed (for whatever reason).

Hono Client also stops re-connect on SASL handshake failures.

This leads to problems when users rely on re-connect capability of hono client. One example are hono protocol adapters. AbstractProtocolAdapterBase stops re-connecting when a re-connect fails because of SASL failures. This actually happens in my kubernetes deployment when I restart hono auth pod and concurrently auth token of amqp connections in protocol adapter expire (which leads to a re-connect).

**Comment by sophokles73** [comment]
The idea behind the special handling of a `SecurityException` being thrown by the Sasl client is that in most cases the reason for the failed SASL handshake are bad credentials. Re-trying the connection does not make much sense in this case because the credentials will remain invalid, thus trapping the client in an endless loop of (futile) re-connect attempts.

The vertx-proton SASL client currently provides no means to determine the root cause of a failed SASL handshake, e.g. an internal problem with accessing the backend store (a DB or Hono Auth). Whenever a handshake fails, the client assumes that it is because of bad credentials.

So, what can we do? We could either reinstate the original behavior of the HonoClient to always try to re-connect, regardless of the reason for failure. Or your client code could handle the ClientErrorException with the 401 code and try to connect again.

In the long run it would probably make sense to create a PR in vertx-proton to allow clients to access the outcome of a SASL handshake in order to determine the root cause (bad credentials vs. system problem) and handle them differently.

**Comment by DanielMaier-BSI** [comment]
As this also affects hono components (mqtt and http adapter) that we use out-of-the-box and also other users might run into this problem I vote for reinstate the original behaviour until there is a possibility to differentiate the root cause of the SASL handshake failure.

**Comment by sophokles73** [comment]
I agree. I will change the client accordingly.

**Comment by sophokles73** [comment]
I have created https://github.com/vert-x3/vertx-proton/issues/69 to track the issue.
