### ISSUE TITLE
Protocol Adapter support for type psk credentials

### ISSUE THREAD

**Issue by pho-enix** [eclipse/hono#612]
Hello Hono project

According to the Credentials API documentation, there is a Pre-Shared Key secret:
https://www.eclipse.org/hono/api/credentials-api/#pre-shared-key

Having a look on the HTTP Adapter I could only find installation of a BasicAuth handler in the router.

I am wondering whether this is currently supported by the Hono provided Protocol Adapters?

**Comment by sophokles73** [comment]
The HTTP and MQTT adapters do not support it because the standard JVM SSLEngine does not support PSK based cipher suites. The CoAP protocol adapter, however, will support PSK based cipher suites because it contains a clean room DTLS implementation.

**Comment by pho-enix** [comment]
Thanks for the answer.

For users of the Hono project a table which summarizes the features of the individual Protocol Adapters could be very helpful. One could collect the supported authentication mechanisms or the support for Gateways, etc. .
