### ISSUE TITLE
Add integration tests for Command & Control via HTTP adapter.

### ISSUE THREAD

**Issue by sysexcontrol** [eclipse/hono#614]
As soon as Command and Control is fully implemented in a first version, we need integration tests that

- simulate a device that stays connected for a while (using the ttd parameter of e.g. a HTTP request) after sending a message
- an application that receives this message and triggers the sending of a command upstream to the device
- the device receives the command

to test the complete message flow through the microservices.

**Comment by kuzuilker** [comment]
Hello @sysexcontrol,

Can you share with me command and control test steps?

**Comment by sysexcontrol** [comment]
Hello @kuzuilker ,

currently there is only the description inside this issue, since the implementation is not yet fully finished.
As soon as this is done, there will be integration tests written which contain the described test steps.

This is planned to happen by referencing this issue, so you won't miss anything :-)

**Comment by mhumoglu** [comment]
Can we help you for  test cases or anything ?  :)

**Comment by sysexcontrol** [comment]
@mhumoglu : thanks for the offer! For the time being we are actually finishing the very first implementation for the upcoming release next week. Afterwards there is a base where help may make a lot of sense :-)

**Comment by mhumoglu** [comment]
Okay  I'm waiting for your response. Good luck  @sysexcontrol  :)

**Comment by sophokles73** [comment]
fixed in https://github.com/eclipse/hono/commit/ba5839eef35088fbd13b4f89950cd29a5a224822
