### ISSUE TITLE
Telemetry sender creation with deviceid in the resource path

### ISSUE THREAD

**Issue by ppatierno** [eclipse/hono#63]
The current TelemetrySenderImpl seems to work fine for adapter where the attached link is always on telemetry/TENANT_ID (defined by the TELEMETRY_ADDRESS_TEMPLATE) where the adapter is authorized by Hono.

We know that without an adapter in the middle, a device should send data only with its deviceid ... so it attaches to telemetry/TENANT_ID/DEVICE_ID in order to be authorized.

We should support that in TelemetrySenderImpl providing a createSender overload with the additional paramater "deviceid" using a different template like telemetry/%s/%s.

WDYT ?

Paolo.

**Comment by sophokles73** [comment]
That's a good idea :+1: 
I am not sure whether we are currently handling this correctly in the TelemetryEndpoint as well. We would need to make sure that the `device_id` header has the same value as the `ResourceIdentifier.resourceId` property, right?

**Comment by ppatierno** [comment]
Yes right.

As always .. if you want I can take care of it ;)

**Comment by ppatierno** [comment]
@sophokles73 here another problem in the HonoClient that seems to be develop for adapters only.
The activeSenders map uses tenantId as key ... but it could be not enough for different senders related to same tenantid but different deviceid so on addresses like : 

telemetry/TENANT_ID/device1
telemetry/TENANT_ID/device2

we should have a composite key (tenantid, deviceid) where deviceid could be null.

**Comment by sophokles73** [comment]
Do you think that this is a pressing issue? IMHO most devices will not connect directly to the server but indirectly via a protocol adapter... maybe we can put this to the *backlog* ...

**Comment by sophokles73** [comment]
@ppatierno I agree regarding the usage of tenant + device id as key in the map.

**Comment by ppatierno** [comment]
IMHO it's not so good having an IoT platform completely based on AMQP 1.0 with AMQP API and then we don't provide direct AMQP access instead of adapters only. I think we should have it.

**Comment by sophokles73** [comment]
@ppatierno well, I will not stop you :-) I was just assuming that you are currently pretty busy implementing the MQTT adapter :-)

**Comment by ppatierno** [comment]
I'm busy on the Hono project :-) 

Regarding the key a String could be good in any case having tenantid_deviceid or only tenantid ... even if in this case we should not have "_" character .. I don't know if it's a strong limitation. WDYT ?

**Comment by sophokles73** [comment]
I do not understand what you mean by *limitation*. What will or could be limited in your opinion?

**Comment by ppatierno** [comment]
Never mind ... we can have "_" in tenantid and deviceid .... the composite key has always meaning even if it's like : 

my_tenant_my_device 

Never mind ... :-)

**Comment by sophokles73** [comment]
Ok, the `TelemetryMessageFilter` already verifies that if the target address contains a resource ID it must match the device ID application property.

**Comment by sophokles73** [comment]
fixed in 48fe311872ae99212456aa73a23d719ad8727f35

`HonoClient` now supports creation of senders scoped to a particular device. When a message is sent using such a sender that has a `device_id` other than the one that has been used to create the sender, the link is closed by Hono.
Note that only the sender is scoped this way, i.e. consumers still are created at the tenant level only since this is the granularity of the resource model there.
