### ISSUE TITLE
Allow HTTP device to respond to commands

### ISSUE THREAD

**Issue by sysexcontrol** [eclipse/hono#630]
The application should be able to receive a response in reply to a command that was sent to a device.

An HTTP device already receives a unique request-id with a command that can be used to correlate a response to the command.

**Comment by sophokles73** [comment]
@sysexcontrol is this done, i.e. can it be closed?

**Comment by sysexcontrol** [comment]
Command responses and all code improvements merged - thus closing this issue now.
