### ISSUE TITLE
Specify event type for connection/disconnection events of protocol adapters in API

### ISSUE THREAD

**Issue by sysexcontrol** [eclipse/hono#638]
With Hono 0.6 we have support for sending connection/disconnection events from the MQTT protocol adapter to devices (if configured).
But we have not described this as specific event type in the Event API page of our documentation (analogous to the introduced empty event notification for command and control).
This event type must be added at the end in the section "Well-known event message types".

**Comment by sysexcontrol** [comment]
@ctron can this issue be closed?
I think has been documented now and nothing else is left to be done, right?

**Comment by ctron** [comment]
Yes, IIRC this was fixed during 0.7.
