### ISSUE TITLE
Telemetry sender checks for contentType not null

### ISSUE THREAD

**Issue by ppatierno** [eclipse/hono#64]
The current Telemetry sender implementation has send methods that check if contentType is null : 

Objects.requireNonNull(contentType);

With MQTT protocol with don't have such information (no metadata supported by the protocol as for AMQP and HTTP) so I think that contentType could be null in this case.

**Comment by sophokles73** [comment]
Then the MQTT adapter should set the content type to `application/octet-stream` and put the payload into an AMQP *Data* section ...

**Comment by ppatierno** [comment]
Yes right ... better to specify such a payload type.
