### ISSUE TITLE
Migrate metrics to Prometheus

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#642]
For internal metrics we want to use Prometheus.

**Comment by ctron** [comment]
Also see: https://dev.eclipse.org/mhonarc/lists/hono-dev/msg00852.html

**Comment by ctron** [comment]
Decisions from today's project call:

* We need to keep the current metrics structure in the InfluxDB for at least the next release of Hono
  * The first step is to document the existing metrics – #645
* We do not necessarily need the graphite reporter for that as long as the InfluxDB structure can be provided in the same way
* The upgrade to Spring Boot 2 will be postponed and not done before this topic
* We will investigate if we can switch to Micrometer and drop the workaround of the current metrics naming and re-labeling using the graphite exporter. Possibly using a direct Micrometer to InfluxDB (and Prometheus) reporter
* The best possible solution would be to ship Hono 0.7 with two reporter options, InfluxDB and Prometheus
* We will re-visit this topic in the next project calls and continue discussions as we learn more

**Comment by sophokles73** [comment]
fixed in https://github.com/eclipse/hono/commit/dbffcfaa68cc26c4a37cb66f57216722df4420a4
