### ISSUE TITLE
AMQP Protocol Adapter

### ISSUE THREAD

**Issue by Alfusainey** [eclipse/hono#643]
This is a container issue for the AMQP protocol adapter. All PRs for the adapter will reference this issue

**Comment by Alfusainey** [comment]
@sophokles73: i just want to follow-up on your previous comment regarding integration tests. 
what do you think about adding the integration test for the amqp adapter (unauthenticated devices) before moving to the next step? like this i can have an initial test setup in the `tests` module before moving further. WDYT?

**Comment by sophokles73** [comment]
Absolutely. Having an initial integration test that you can extend with additional test cases makes total sense to me.

**Comment by Alfusainey** [comment]
> sounds reasonable, however, it would also be nice to check if it also works with e.g. the Qpid JMS provider 

@sophokles73: Am now working on this task

**Comment by sophokles73** [comment]
@Alfusainey I think this can wait. Based on the fact that GSoC ends mid August, we should probably talk about prioritization. What about using our Thursday call to discuss?

**Comment by Alfusainey** [comment]
> What about using our Thursday call to discuss?

Yes sure, we can meet this thursday

**Comment by pho-enix** [comment]
Great to see the progress and that there is authentication for AMQP PA now :)

When will it be ready to use? With 0.7?

**Comment by sophokles73** [comment]
We plan to have an initial version in 0.7. However, I think that it will most likely not yet support C&C..

**Comment by sophokles73** [comment]
fixed in https://github.com/eclipse/hono/commit/f502009e47b7f84db852a319605217591485dd82
