### ISSUE TITLE
HonoClient is not able to refresh its access token for connections to hono components without re-create connection

### ISSUE THREAD

**Issue by DanielMaier-BSI** [eclipse/hono#647]
Per default hono client gets disconnected from other hono components every 10 minutes with a "amqp:unauthorized-access" error because access token is expired.

This leads to undesirable behavior for users, e.g. protocol adapter reject messages with "Service Unavailable" when this happens. While "Service Unavailable" is just fine in exceptional cases, in my opinion it is not acceptable to occur on a regular basis. It is also hard to implement custom hono components with dependencies to other hono components without exposing this behavior to users.

As I understood hono client has no possibility to refresh its access token without creating a new connection. Would be great if hono client is able to refresh the access token on itself while keeping the connection alive.

What do you think about this issue? What needs to be changed to implement this?

**Comment by sophokles73** [comment]
see #530

**Comment by DanielMaier-BSI** [comment]
Great this is exactly what I need. 

I close my issue because it duplicates #530.

**Comment by sophokles73** [comment]
A short term solution might be to set the timeout of the JWTs to a high value or to completely disable expiration (however, that would require  a small code change).
Note that when connecting to enMasse, the connections will never be closed by the Dispatch Router in enMasse as well.  So following my proposal would probably not make things worse ...

**Comment by DanielMaier-BSI** [comment]
Hi @sophokles73 ,

we will think about your suggestion as a mid term solution. Perhaps it would be a good idea to be able to configure token expiration per user? The only difference to qdrouter endpoint I see is that the other endpoints might reveal even more sensitive data, e.g. credentials.
