### ISSUE TITLE
Reconnect behavior of Clients can be improved

### ISSUE THREAD

**Issue by pho-enix** [eclipse/hono#649]
**Originally observed behaviour:**
1) Hono PA connecting to Hono Messaging
2) Due to issues on network layer the IP address of Hono Messaging was a blackhole (receiving messages but never replying)
3) Due to ProtonClientOptions.setReconnectAttempts(-1)
io/vertx/core/impl/netClientImpl.java:doConnect will retry forever (TCP SYN).

**Points that need improvement:**
* This will not perform a new lookup of the IP address. Especially in the situations when a DNS name is backed by many (changing) IP addresses, the client might be able to recover by doing a fresh lookup.
* Hono disconnect handler does not get called, thus no logging.

**I was able to reproduce the behaviour using the Example client:**
* ProtonClientOptions.setReconnectAttempts(-1)
* Use an http endpoint as destination (which will silently discard amqp traffic)
* I see the same TCP SYN forever without recovery

My suggestion is to change the Proton reconnect to a value that makes sense: 2
If the handshake does not work on the Proton level, control shall move back to Hono's reconnect handler.

We can then introduce a HonoReconnectAttempts that will control the number of reattempts done by Hono's reconnect handler.

The reason I am proposing this is that in my opinion a client should behave as graceful as possible. With this behavioural change, the client will be able to recover from some real world error conditions.

Some pseudo code:
```
diff --git a/client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java b/client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java
index 27c8efa..3872ace 100644
--- a/client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java
+++ b/client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java
@@ -30,6 +30,7 @@ import java.util.function.BiConsumer;
 import java.util.function.Consumer;
 import java.util.function.Supplier;
 
+import io.vertx.core.net.NetClientOptions;
 import org.apache.qpid.proton.amqp.Symbol;
 import org.apache.qpid.proton.message.Message;
 import org.eclipse.hono.cache.CacheProvider;
@@ -389,13 +390,16 @@ public class HonoClientImpl implements HonoClient {
             final Handler<AsyncResult<HonoClient>> connectionHandler,
             final Handler<ProtonConnection> disconnectHandler) {
 
+        int honoReconnects = 1000;
+        LOG.info("Failed :(", connectionFailureCause);
+
         if (shuttingDown.get()) {
             // no need to try to re-connect
             connectionHandler.handle(Future.failedFuture(new IllegalStateException("client is shut down")));
-        } else if (clientOptions.getReconnectAttempts() - reconnectAttempts.get() == 0) {
+        } else if (honoReconnects - reconnectAttempts.get() == 0) {
             reconnectAttempts = new AtomicInteger(0);
             LOG.debug("max number of attempts [{}] to re-connect to peer [{}:{}] have been made, giving up",
-                    clientOptions.getReconnectAttempts(), connectionFactory.getHost(), connectionFactory.getPort());
+                    honoReconnects, connectionFactory.getHost(), connectionFactory.getPort());
             if (connectionFailureCause == null) {
                 connectionHandler.handle(Future.failedFuture(
                         new ServerErrorException(HttpURLConnection.HTTP_UNAVAILABLE, "failed to connect")));
diff --git a/example/src/main/java/org/eclipse/hono/example/AbstractExampleClient.java b/example/src/main/java/org/eclipse/hono/example/AbstractExampleClient.java
index 6a9d135..35ff0d9 100644
--- a/example/src/main/java/org/eclipse/hono/example/AbstractExampleClient.java
+++ b/example/src/main/java/org/eclipse/hono/example/AbstractExampleClient.java
@@ -35,6 +35,7 @@ abstract class AbstractExampleClient {
 
     protected final Logger LOG = LoggerFactory.getLogger(getClass());
     protected final int DEFAULT_CONNECT_TIMEOUT_MILLIS = 1000;
+    protected final int DEFAULT_PROTON_CONNECT_RETRIES = 2;
 
     protected Context ctx;
     @Value(value = "${tenant.id}")
@@ -66,6 +67,6 @@ abstract class AbstractExampleClient {
     }
 
     protected final ProtonClientOptions getClientOptions() {
-        return new ProtonClientOptions().setConnectTimeout(DEFAULT_CONNECT_TIMEOUT_MILLIS).setReconnectAttempts(2);
+        return new ProtonClientOptions().setConnectTimeout(DEFAULT_CONNECT_TIMEOUT_MILLIS).setReconnectAttempts(DEFAULT_PROTON_CONNECT_RETRIES);
     }
 }
```

**Comment by sophokles73** [comment]
A connection attempt of a HonoClient can fail at different levels:
1. TCP level - possible reasons: host name cannot be resolved, no route to host, peer is not responding
2. SASL level - possible reasons: client provided incorrect credentials, peer cannot verify credentials because credentials store is not available, client does not support SASL mechanisms offered by peer
3. AMQP level - possible reasons: client requires capabilities not offered by the peer, desired session size not supported by peer etc.

We should try to address these issues in a way that the client can recover from most of these problems autonomously, i.e. without requiring a restart of the component that the client is part of.

Your investigation seems to have revealed that at the TCP level, the proton client does not do a fresh DNS lookup for each (re-)connection attempt which can result in attempts to connect to a *stale* or *non-existent* peer address. I agree that in order to address this problem, we could set the reconnect attempts at the TCP level to a fixed number (e.g. 3) and after that, trigger a new connection attempt based on a configuration option at the Hono Client level.

Problems at level 2 occur only after a TCP connection has been successfully established. For the time being we are not able to distinguish between the possible causes for the SASL handshake failure, so we currently simply try to re-connect to the peer based on the number of reconnection attempts configured at the TCP level. I also think that we should decouple this behavior from the configuration at the TCP level, e.g. by introducing a new configuration property at the HonoClient level for setting the number of reconnection attempts to perform at the SASL and AMQP level.

Finally, at the AMQP level, we are mostly dealing with implementation errors which need to be addressed by fixing the corresponding source code. FMPOV we currently do not have a problem at this level.

@pho-enix does this match your assessment?

**Comment by pho-enix** [comment]
@sophokles73 great to hear that you share my objections. Yes, with the proposed changes we will provide improvements for issues on level 1. I also agree that this will no influence levels 2 and 3 - I didn't observe any particular issues in those areas.

Looking forward for this new HonoClient property.

**Comment by sophokles73** [comment]
@pho-enix I have pushed some changes that should address the issue. See `HonoClient` JavaDoc for details. Can you check if this indeed solves your problem and if so, close this issue?

**Comment by pho-enix** [comment]
I took your changes and configured `config.setReconnectAttempts(10);`.

* The client correctly stops reconnects after 11 attempts in reconnect handler
* For each call of the reconnect handler there is a fresh DNS lookup performed

Works very good for me. Thanks for this improvement.

Maybe you want to simply the Example Client:
```
diff --git a/example/src/main/java/org/eclipse/hono/example/AbstractExampleClient.java b/example/src/main/java/org/eclipse/hono/example/AbstractExampleClient.java
index 6a9d135..9348d87 100644
--- a/example/src/main/java/org/eclipse/hono/example/AbstractExampleClient.java
+++ b/example/src/main/java/org/eclipse/hono/example/AbstractExampleClient.java
@@ -34,7 +34,6 @@ import io.vertx.proton.ProtonClientOptions;
 abstract class AbstractExampleClient {
 
     protected final Logger LOG = LoggerFactory.getLogger(getClass());
-    protected final int DEFAULT_CONNECT_TIMEOUT_MILLIS = 1000;
 
     protected Context ctx;
     @Value(value = "${tenant.id}")
@@ -64,8 +63,4 @@ abstract class AbstractExampleClient {
     public final void setHonoClient(final HonoClient client) {
         this.client = Objects.requireNonNull(client);
     }
-
-    protected final ProtonClientOptions getClientOptions() {
-        return new ProtonClientOptions().setConnectTimeout(DEFAULT_CONNECT_TIMEOUT_MILLIS).setReconnectAttempts(2);
-    }
 }
diff --git a/example/src/main/java/org/eclipse/hono/example/AppConfiguration.java b/example/src/main/java/org/eclipse/hono/example/AppConfiguration.java
index 52c1529..41a1554 100644
--- a/example/src/main/java/org/eclipse/hono/example/AppConfiguration.java
+++ b/example/src/main/java/org/eclipse/hono/example/AppConfiguration.java
@@ -60,6 +60,7 @@ public class AppConfiguration {
     @Bean
     public ClientConfigProperties honoClientConfig() {
         final ClientConfigProperties config = new ClientConfigProperties();
+        config.setReconnectAttempts(2);
         return config;
     }
 
diff --git a/example/src/main/java/org/eclipse/hono/example/ExampleReceiver.java b/example/src/main/java/org/eclipse/hono/example/ExampleReceiver.java
index 74ec9f0..7b1f272 100644
--- a/example/src/main/java/org/eclipse/hono/example/ExampleReceiver.java
+++ b/example/src/main/java/org/eclipse/hono/example/ExampleReceiver.java
@@ -46,7 +46,7 @@ public class ExampleReceiver extends AbstractExampleClient {
     @PostConstruct
     private void start() {
 
-        client.connect(getClientOptions(), this::onDisconnect)
+        client.connect(this::onDisconnect)
             .compose(connectedClient -> createConsumer(connectedClient))
             .setHandler(startup -> {
                 if (startup.succeeded()) {
@@ -81,7 +81,7 @@ public class ExampleReceiver extends AbstractExampleClient {
         // give Vert.x some time to clean up NetClient
         vertx.setTimer(DEFAULT_CONNECT_TIMEOUT_MILLIS, reconnect -> {
             LOG.info("attempting to re-connect to Hono ...");
-            client.connect(getClientOptions(), this::onDisconnect).compose(connectedClient -> createConsumer(connectedClient));
+            client.connect(this::onDisconnect).compose(connectedClient -> createConsumer(connectedClient));
         });
     }
 ```

**Comment by sophokles73** [comment]
@pho-enix  anything else?

**Comment by pho-enix** [comment]
@sophokles73 Yes, closing the issue ;) Resolved
