### ISSUE TITLE
Upgrade to Vert.x 3.5.2

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#657]
Now that Vert.x 3.5.2 is available, we should upgrade to this version (and its dependencies).
Based on my assessment of the release notes [1], 3.5.2 constitutes a bug fix release and thus does not require us to create new CQs.

[1] https://github.com/vert-x3/wiki/wiki/3.5.2-Release-Notes

**Comment by sophokles73** [comment]
@ctron what's your opinion on this? would you agree that we are dealing with a bug fix release only?

**Comment by ctron** [comment]
Yes, it would say it is. Let's do that.
