### ISSUE TITLE
Support "one way" command pattern

### ISSUE THREAD

**Issue by sysexcontrol** [eclipse/hono#669]
Currently a command sent by an application waits for a response sent by the device to become successful.

Since some devices are just not capable of ever sending a response, we need an additional pattern for commands without a response:

- the application should be able to signal that there is no response expected (in this case no receiver link for a response would be opened at all). 
- on the AMQP 1.0 message level this probably is best handled by a missing `reply-to`.
- on the API level there must be some extension implemented that lets the application control that the command is to be considered "one-way".

**Comment by sophokles73** [comment]
> * the application should be able to signal that there is no response expected (in this case no receiver link for a response would be opened at all)

The application should then simply not set the *reply-to* property in the command message.

> * the device should be able to signal for downstream messages in addition to the ttd parameter that there will be no response sent to a potentially received command (called e.g. nor for no response

I do not think that I understand the purpose of this.

> * the adapter should be able to detect a default value for the device regarding the nor parameter

What is this supposed to be good for?

**Comment by sophokles73** [comment]
We already have added the concept of a *one-way* command to the [C&C API](https://www.eclipse.org/hono/api/command-and-control-api/#send-a-one-way-command).

However, the protocol adapters need to be adapted accordingly, e.g. the HTTP adapter needs to be changed to not include the *hono-cmd-id* header in the HTTP response if no *reply-to* property is set in the command.

**Comment by sophokles73** [comment]
@sysexcontrol are you currently working on this issue?  It is assigned to you but it is not in progress (yet) ...

**Comment by sysexcontrol** [comment]
> > * the application should be able to signal that there is no response expected (in this case no receiver link for a response would be opened at all)
> 
> The application should then simply not set the _reply-to_ property in the command message.

That is a reasonable implementation detail. However, the current API needs to be somehow extended as well, since for the client the _reply-to_ property is completely transparent currently (and thus would always be set).
I will extend this part in the description.

**Comment by sysexcontrol** [comment]
> > * the device should be able to signal for downstream messages in addition to the ttd parameter that there will be no response sent to a potentially received command (called e.g. nor for no response
> 
> I do not think that I understand the purpose of this.

This was meant as the possibility for a device to signal that it will (or cannot) reply to any command. At the same time as the `ttd` parameter is given.

The first option demands that the application itself needs to know if a command can be responded by the device or not. This 2nd option would enable an application to send a command, and the underlying API can decide itself if there should be a response from the device or not - the application would be free from this decision.

Thinking about it now, it does not seem to be so obvious to me anymore that this is a necessary feature to have - maybe it is ok to always let the application decide that a command shall be "one-way" or not.
I will remove this point from the issue - it could be implemented later on anyway, if it should be important.

> 
> > * the adapter should be able to detect a default value for the device regarding the nor parameter
> 
> What is this supposed to be good for?

Is (or better: was) meant as an automatic way of setting that a device will not send a reponse to a command. IMHO this should be implemented iff option 2 is implemented (to free the device from having to set it explicitly), but will remove this together with option 2 now from the issue.

**Comment by sysexcontrol** [comment]
Fixed by PR #912, #908  and #893.
