### ISSUE TITLE
Use-cases for AMQP Protocol Adapter

### ISSUE THREAD

**Issue by pho-enix** [eclipse/hono#676]
I just noticed that there is now a protocol adapter for AMQP 1.0. That's very good news. I think that usage of AMQP 1.0 is a very good fit, if it comes to connectivity of a gateway which serves a huge number of devices and significant message throughput. Furthermore usage of AMQP 1.0 for end-device communication has be postulated - and it definitively has tremendous advantages over HTTP.

However I wonder if this new interface could also be used to connect potentially untrusted custom protocol adapters from 3rd parties. For this use-case authentication and authorization is crucial and one might be reluctant of giving direct access to hono-messaging or the messaging network itself.

**Comment by Alfusainey** [comment]
thanks. there is already a [dedicated issue ticket](https://github.com/eclipse/hono/issues/643) regarding the amqp adapter and would be nice if we can centralize discussions regarding it there (since the development is still in progress)..

> However I wonder if this new interface could also be used to connect potentially untrusted custom ..

are you talking about the protocol adapter base implementation? the amqp adapter is a custom implementation of the base protocol adapter for use with amqp 1.0 devices

**Comment by sophokles73** [comment]
> However I wonder if this new interface could also be used to connect potentially untrusted custom protocol adapters from 3rd parties. For this use-case authentication and authorization is crucial and one might be reluctant of giving direct access to hono-messaging or the messaging network itself.

This might indeed be possible if the *untrusted custom protocol adapter* behaves like a gateway. Once the AMQP 1.0 adapter supports authentication of devices, you could take it for a spin in that direction ...

**Comment by pho-enix** [comment]
Maybe the term _untrusted custom protocol adapter_ is misleading. It would be more of a _protocol translator_. The big different is that the _protocol adapter_ terminates this protocol and does things like authentication or flow control. The _protocol translator_ in contrast only translates one protocol to another protocol.

> This might indeed be possible if the untrusted custom protocol adapter behaves like a gateway. Once the AMQP 1.0 adapter supports authentication of devices, you could take it for a spin in that direction ...

This is one use-case. The other one is that the _protocol translator_ only forwards the authentication information to Hono (of course the authentication mechanism must be compatible with the authentication mechanisms supported by Hono).
