### ISSUE TITLE
HTTP adapter leaks CommandConsumer instances

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#677]
The HTTP protocol adapter creates an instance of CommandConsumer for each request that includes the *hono-ttd* request parameter or header in order to receive a pending command for the device.
However, the CommandConsumer object created doesn't get GCed anymore.

**Comment by calohmn** [comment]
@sysexcontrol Fix regarding links used in `HonoClient` is in #680. 
As the issue also involves other components (to a lesser degree), the corresponding places where Links are closed should be checked as well - that is still to be done.

**Comment by sysexcontrol** [comment]
As indicated above - fixed by 15772bb.

**Comment by sophokles73** [comment]
@sysexcontrol I think we should not consider this fixed before we also have made sure that we also do not leak sessions and links from all the other places in the code where `HonoClientImpl` is not involved.
Also, I would like to stick to the pattern of letting the person who opened an issue also close it, if possible.

**Comment by sophokles73** [comment]
fixed in 658fc04724652098939b0422f0ce25838bf5e168
