### ISSUE TITLE
JMeter plugin: improve errorhandling in Receiver part

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#684]
When the Receiver of the JMeter plugin receives an illegal message (without information about the sender time), an exception is thrown. 

Instead the errorCount should be increased for the corresponding batch and a proper log message should be used.

**Comment by calohmn** [comment]
Setting the errorCount has no effect with JMeter 3.3/4.0 (see https://github.com/apache/jmeter/blob/0309b6fc6009d3f01eb5bcd9b980cce24483a26d/src/core/org/apache/jmeter/samplers/SampleResult.java#L1173-L1175).
Sample should be marked as unsuccessful instead if there were errors.

**Comment by sophokles73** [comment]
@calohmn can this be closed?
