### ISSUE TITLE
Update JMeter Plugin to JMeter 4.0

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#686]
JMeter 4.0 adds support for Java 9 and has various improvements:
https://jmeter.apache.org/changes.html

**Comment by sophokles73** [comment]
Do you happen to know if we can simply compile and run our plugin against JMeter 4.0 or do we need to make changes to the code as well?

**Comment by sophokles73** [comment]
So, would upgrading to 4.x still be helpful to you?

**Comment by calohmn** [comment]
No, it's not needed.
