### ISSUE TITLE
AMQP endpoint for provisioning device identities

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#7]
Hono is supposed to make sure that telemetry data flowing *downstream*, i.e. from devices to the back end, can only be received and processed by consumers that are authorized to do so. For that to work the data needs to be associated with a *security context* containing, among other things, the *subjects* representing the device identity and (optionally) the device owner.

Routing and access decisions can then be made by Hono based on this information. Provisioning of that kind of data will be easier to automate if we provide an API for managing device identity information.

**Comment by dguggemos** [comment]
I came across some open issues while implementing the registration endpoint. For the Telemetry API we dropped the `device-id` and `tenant-id` properties in favor of providing these in the `to` field. I think to be consistent across our API we should do the same for the Registration API (and for other future APIs). That means to register/deregister a device we have a `to` field of `registration/<tenant-id>/<device-id>`.
And another question concerning the qos level/settle mode: should we handle invalid messages the same way as we do for telemetry messages (forcibly closing the link)? Or should we use the `rejected` state in this case? And does this mean we do not allow pre-settled message for the registration endpoint?

**Comment by dguggemos** [comment]
I'm currently thinking about which restrictions we should impose based on the registered devices. For example is a device that is unknown to Hono able to upload telemetry data? Or is it registered automatically the first time it sends data? What do you think?

**Comment by sophokles73** [comment]
I think that Hono should refuse to receive data for an unknown device. All devices need to be provisioned before telemetry data or commands can be uploaded to Hono for a device.

**Comment by sophokles73** [comment]
Coming back to a previous question of yours:
> And another question concerning the qos level/settle mode: should we handle invalid messages the same way as we do for telemetry messages (forcibly closing the link)? Or should we use the rejected state in this case? And does this mean we do not allow pre-settled message for the registration endpoint?

I think that for the registration API we will *only* want to support unsettled messages, i.e. we should support *at least once* delivery only in order to make sure that a client's registration request has been accepted or not. The other question is whether we want to use the disposition to indicate the outcome of the registration itself, i.e. "registration succeed" vs. "registration failed". I guess this would be the easiest way to implement it, in particular if we do not want to persist registration requests before processing them. On the other hand this basically implies a "blocking" API which we generally do not want to have, or do we?

**Comment by ppatierno** [comment]
My opinion is that something like a registration mechanism is an "offline" operation in a lot of scenario; it means that we should store registration requests. We may have a "blocking" API using the disposition for success or not but it could be important to distinguish between registration and enabling. After the request to the registration API, a device can be registered immediately but it doesn't mean that it can send data immediately; someone or some rules need to enable it to do so.

Agree with @sophokles73 on supporting only unsettled messages; when a device sends a registration request, it has some interest to know if the request was received and the related result.
