### ISSUE TITLE
Bind automatic emission of `ttd` events to subscribe/unsubscribe in the MQTT adapter

### ISSUE THREAD

**Issue by sysexcontrol** [eclipse/hono#709]
Currently we already provide `lifecycle events`, that can be emitted if a MQTT device connects to or disconnects from the MQTT adapter.
Besides that a device can signal that it is ready to receive a command by sending downstream messages with the `ttd` parameter set.

Some devices may not be capable of sending any Hono specific message parameters and need the protocol adapter to do this for them.

Such a support should be implemented by 
- emitting an empty notification with `ttd = -1` at the time a device subscribes to the command topic (`SUBSCRIBE` message)
- emitting an empty notification with `ttd = 0` at the time a device unsubscribes from the command topic (`UNSUBSCRIBE` message)
- configurable on a tenant level (if switched off, the adapter would never emit such events for this tenant)
- configurable on a device level (if switched off, the adapter would never emit such events for this device)

**Comment by pellmann** [comment]
The emitting of the events at subscribe/unsubscribe is the implemented behavior in the MQTT command and control implementation. Why should such an event at subscribe/unsubscribe not always be fired?

**Comment by sophokles73** [comment]
You might argue that in some cases you want the device be in total control of when it wants to receive a command or not. However, in MQTT the SUBSCRIBE and UNSUBSCRIBE packets seem to be used for exactly this purpose anyway, i.e. if a device doesn't want to receive commands, it simply doesn't SUBSCRIBE to the command topic, right?

So, I agree, it seems that we do not really need to make this configurable.

**Comment by sophokles73** [comment]
fixed in 5dae0f6fc0761625721191176ca5402a43172286
