### ISSUE TITLE
Any plans to support client certificate based authentication "out of the box" for the example deployment?

### ISSUE THREAD

**Issue by boaks** [eclipse/hono#732]
Are there any plans to support client certificate based authentication "out of the box" for the example deployment? If so, which `trusted-ca` certificate is intended to be used? 
FMPOV the setup is not that easy, so I think, prepare the example deployment will do a good job to make some promotion for that feature.

**Comment by sophokles73** [comment]
That sounds like a good idea :-) An obvious choice would be to use the `cn=ca` certificate as the trust anchor, I guess.

**Comment by b-abel** [comment]
I think this is depended on #349.

**Comment by b-abel** [comment]
I am working on this issue.

**Comment by sophokles73** [comment]
fixed in 4e5902d5df62c93583d9ab7f6c7ec842a362c536
