### ISSUE TITLE
Hono build breaks with missing vertx-mqtt-server dependency

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#74]
The SNAPSHOT version referred to by the mqtt-adapter module cannot be resolved.

This seems to be because Sonatype's repository (where the snapshot is retrieved from) does not keep all snapshot versions forever.

**Comment by sophokles73** [comment]
In order to not run into this problem again in several weeks we should probably include the snapshot artifact (the jar) into our code base and use the `system` scope when declaring the maven dependency to refer to the local jar file instead of having it downloaded from Sonatype's repo (where it will be removed form after some weeks) ...

**Comment by sophokles73** [comment]
@ppatierno,

are you already working on this?

**Comment by ppatierno** [comment]
@sophokles73 yes ! Just started to work on this. I need to add the artifact and update the MQTT adapter for the new API.

**Comment by sophokles73** [comment]
thanks, paolo.

BTW your commit shows up as *ppatierno committed with ppatierno*. I think this is because you are still adding a `signed-off-by` footer in your commits. This is totally okay but not strictly necessary since you are a committer now. You only need to make sure that commits that you merge to the repo, e.g. a PR from somebody else, has the `signed-off-by` footer.
