### ISSUE TITLE
Not all service instances are "healthchecked"

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#750]
To me it looks like that only the first instance of a service is being monitored:

Looking at `org.eclipse.hono.service.AbstractApplication.deployServiceVerticles()`:
~~~java
for (final ObjectFactory<? extends AbstractServiceBase<?>> serviceFactory : serviceFactories) {

    AbstractServiceBase<?> serviceInstance = serviceFactory.getObject();

    // registered
    healthCheckServer.registerHealthCheckResources(serviceInstance);

    final Future<String> deployTracker = Future.future();
    vertx.deployVerticle(serviceInstance, deployTracker.completer());
    deploymentTracker.add(deployTracker);

    for (int i = 1; i < maxInstances; i++) { // first instance has already been deployed
        serviceInstance = serviceFactory.getObject();

        // NOT registered

        log.debug("created new instance of service: {}", serviceInstance);
        final Future<String> tracker = Future.future();
        vertx.deployVerticle(serviceInstance, tracker.completer());
        deploymentTracker.add(tracker);
    }
}
~~~

Wouldn't it make sense to use the "instances" option from the `DeploymentOptions` and let vertx handle the number of instances. And then invert the way the services find the health check server by using Spring functionality (injection).

**Comment by sophokles73** [comment]
We are talking about *Verticle* instances running inside the same vert.x instance, right?

**Comment by b-abel** [comment]
The general question for me is how to define the health state of the application with respect to multiple instances of a Verticle: Is the whole application DOWN if one Verticle instance is DOWN? And, if yes, how is this determined.
If different Verticle instances report a different health state, the health check would not provide a consistent result. I don't see a simple solution for this problem and would argue that it is beyond the scope of this issue. The current behaviour of having only the first Verticle instance checked is not more accurate or reliable.
So, **TL;DR** I would go with @ctron and register the health checks for every Verticle instance.

Other opinions on that?

**Comment by sophokles73** [comment]
> So, TL;DR I would go with @ctron and register the health checks for every Verticle instance.

sounds good to me

**Comment by b-abel** [comment]
I opened a PR, but I would like to provide another one with a different solution. The idea there is that the Verticles actively notify the `HealthCheckServer` via EventBus about health changes, the `HealthCheckServer` holds the health state of all verticle instances and can immediately answer all health check requests.
We could then compare and discuss the two PRs.

**Comment by sophokles73** [comment]
fixed in https://github.com/eclipse/hono/commit/af79111f808638c786634c3384a66c421cda3d22
