### ISSUE TITLE
getTypesafeValueForField not working as intended

### ISSUE THREAD

**Issue by pho-enix** [eclipse/hono#751]
I just dropped some code there, illustrating my issue:
https://github.com/eclipse/hono/pull/745

Probably nobody spotted it cause the build is (intentionally) broken.

**Comment by sophokles73** [comment]
In fact, your test case illustrates that `EventBusService.getRequestPayload()` does not work as expected. The root cause for this indeed is an erroneous assumption about the way that generics work in Java in *getTypesafeValueForField*.

However, the question is: do you need a working *getRequestPayload* method or do you need a working *getTypesafeValueForField* method? Could you then please adapt the title of this issue accordingly?

**Comment by pho-enix** [comment]
The function `getTypesafeValueForField`makes a promise: To get the value for a field in a typesafe way.
But it does not keep the promise and `getRequestPayload` (and other callers as well) will suffer from it.

I like the idea of `getTypesafeValueForField` a lot, as it makes the caller's code much easier and separates concerns. I very much prefer a solution that fixes `getTypesafeValueForField` so all callers can benefit from the improvement.

Does that answer your questions?

**Comment by sophokles73** [comment]
No, it doesn't. My question is: do you have any code that fails due to it invoking *getRequestPayload* or do you have code that fails due to it (directly) invoking *getTypesafeValueForField*?

**Comment by pho-enix** [comment]
I have code that fails invoking `getRequestPayload` (please have a look on the PR).

**Comment by sophokles73** [comment]
I have taken a look at the PR, that's the reason why I ask. The title of this issue suggests that you have trouble invoking *getTypesafeValueForField* ...

**Comment by ctron** [comment]
I any case, I think that `getTypesafeValueForField` is broken. I also do think it should be a static method.

The following test case would fail:

~~~java
@Test
public void testInvalidType() {
    final JsonObject device = new JsonObject().put("device-id", "someValue");

    final String stringValue = service.getTypesafeValueForField(device, "device-id");
    Assert.assertEquals("someValue", stringValue);

    final Integer intValue = service.getTypesafeValueForField(device, "device-id");
    Assert.assertNull(intValue);
}
~~~

According to the JavaDoc this should be `null`:

> @return The property value or {@code null} if no such property exists or is not of the expected type.

I think a proper solution would be:

~~~java
protected final <T> T getTypesafeValueForField(final Class<T> clazz, final JsonObject payload, final String field) {

    Objects.requireNonNull(clazz);
    Objects.requireNonNull(payload);
    Objects.requireNonNull(field);

    try {
        return clazz.cast(payload.getValue(field));
    } catch (final ClassCastException e) {
        return null;
    }
}
~~~

**Comment by ctron** [comment]
I created a PR which could be a solution to this.

**Comment by sophokles73** [comment]
@ctron I agree, the method does not comply with its documented contract. Sadly, though, I think that it cannot be fixed without changing the method's signature. I wrote the method with an (obviously) erroneous understanding of how generics work. In order for the method to work as documented a `Class` typed parameter would need to be passed in (as you also seem to believe according to your PR).

I would, however, rather have a new issue for changing the method signature, as https://github.com/eclipse/hono/commit/af33fb1be1f62e506812a26303acbcab58c43bc5 already fixes the problem at hand.

**Comment by ctron** [comment]
I think changing the method signature is fine, as this is a protected method anyway.

**Comment by sophokles73** [comment]
@ctron I think so too but I still would like to use a separate issue for it.

@pho-enix can you verify if https://github.com/eclipse/hono/commit/af33fb1be1f62e506812a26303acbcab58c43bc5 fixes your problem and if so, close this issue?

**Comment by pho-enix** [comment]
Yes, af33fb1 fixes the issue I discovered.

However I prefer @ctron 's approach of fixing this for all callers and it does not bloat the code.
