### ISSUE TITLE
Potential NPE in subclasses of AbstractAmqpEndpoint

### ISSUE THREAD

**Issue by DanielMaier-BSI** [eclipse/hono#752]
AbstractAmqpEndpoint has a protected field "config" which gets autowired with required set to false, i.e. field may be null. However all existing subclasses (RequestResponseEndpoint, MessageForwardingEndpoint) rely on non-null field, i.e. do not make any null checks before access. 

In my opinion when the config is mandatory implicitly anyways it should be autowired with required set to true. If there are scenarios thinkable in the future where the field is nullable, the field should be moved into the subclasses as it gets not used in parent class anywhere.

By the way: Currently we do not have any problems with that. Issue only occurred in some tests of us where we instantiate stuff without spring, i.e. issue is not urgent from our point of view.

What do you think? Is it worthwhile to fix this?

**Comment by sophokles73** [comment]
I agree that this is not ideal. However, so far we didn't run into any bigger issues using the current approach.

Even if we set *Autowired(required = true)* the *config* field would still not get set/initialized in your non-Spring based tests, right? So I am not sure what would be gained ...

**Comment by DanielMaier-BSI** [comment]
No strong opinion. Intention of the issue was just to prevent others run into this in "real" deployments. If there are more important things for now and no "5 minutes fix" I have no problem with closing it.
