### ISSUE TITLE
Encoding payload as Data section

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#765]
While looking into performance issues I stumbled over the fact that a significant amount of time in Hono is used for encoding AMQP messages. So I dug a little bit deeper with the profiler and figured out an issue in the string encoder -> https://issues.apache.org/jira/browse/PROTON-1911

However, the hint from @gemmellr pointed me towards another issue in the way Hono encodes its payload. We sometimes do something like this:

~~~java
request.setBody(new AmqpValue(payload.getBytes()));
~~~

However that means, encode payload as an array of bytes. Which looks like this, if put under the microscope:

![testm1-2018-08-08-shutdown-1 snapshot -home-jreimann-snapshots - yourkit java profiler 2018 04-b81 - 64-bit_509](https://user-images.githubusercontent.com/202474/43823688-2f1928a6-9af0-11e8-8482-acb2f6a99dec.png)

Encoding the same message 1024 times takes around 6 seconds, the most time is spent encoding an array of bytes. Because it is actually encoding a byte array in the AMQP type system.

However what we actually want is to encode a BLOB, as we have our type system. We are not using the AMQP type system. So switching to:

~~~java
request.setBody(new Data(Binary.create(ByteBuffer.wrap(payload.getBytes()))));
~~~

Will result in a way faster encoding:

![testm1-2018-08-08-shutdown-2 snapshot -home-jreimann-snapshots - yourkit java profiler 2018 04-b81 - 64-bit_510](https://user-images.githubusercontent.com/202474/43824033-356c199c-9af1-11e8-81ad-a2ae08415a9f.png)

![testm1-2018-08-08-shutdown-2 snapshot -home-jreimann-snapshots - yourkit java profiler 2018 04-b81 - 64-bit_511](https://user-images.githubusercontent.com/202474/43824049-3c49a75c-9af1-11e8-91be-fc0f761dfece.png)

While keeping the memory consumption the same:

![testm1-2018-08-08-shutdown-2 snapshot -home-jreimann-snapshots - yourkit java profiler 2018 04-b81 - 64-bit_512](https://user-images.githubusercontent.com/202474/43824066-45442170-9af1-11e8-9f3c-09aad943bb58.png)

So my proposal would be to use data sections instead of values when transmitting BLOBs. However, that will have an on the public API of Hono, as that will change how the data is being transmitted. But I also think that using Data section the right way when handling BLOBs.

As a first step we could change Hono in a way that 0.7 accepts data sections in addition to AmqpValues of type `byte[]`.

**Comment by ctron** [comment]
Here is the reproducer for the data above:

~~~java
package foo.bar;

import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;

import org.apache.qpid.proton.amqp.Binary;
import org.apache.qpid.proton.amqp.messaging.AmqpValue;
import org.apache.qpid.proton.amqp.messaging.Data;
import org.apache.qpid.proton.message.Message;

public class Application {

    private static final String DATA = "0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789"
            + "0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789"
            + "0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789"
            + "0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789"
            + "0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789";

    public static void main(final String[] args) throws Exception {

        final Message m = Message.Factory.create();

        m.setSubject("FOO");
        m.setAddress("send-to");
        m.setContentType("foo/bar");

        // m.setBody(new AmqpValue(DATA));
        // m.setBody(new AmqpValue(DATA.getBytes(StandardCharsets.UTF_8)));
        m.setBody(new Data(Binary.create(ByteBuffer.wrap(DATA.getBytes(StandardCharsets.UTF_8)))));

        final byte[] buffer = new byte[64 * 1024];

        for (int i = 0; i < 1024; i++) {
            m.encode(buffer, 0, buffer.length);
        }
    }
}

~~~

**Comment by gemmellr** [comment]
Wont make a difference here, but you don't need the intermediate ByteBuffer above, you can just pass the array directly to a new Binary instance.

**Comment by sophokles73** [comment]
@ctron isn't this done already?

**Comment by ctron** [comment]
> @ctron isn't this done already?

Indeed.
