### ISSUE TITLE
Align the way Hono encode the body section of AMQP messages

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#766]
While looking into #765 I found out that Hono in most cases uses Data sections:

~~~java
msg.setBody(new Data(new Binary(payload)));
~~~

Sometimes AmqpValues of type `byte[]`:

~~~java
request.setBody(new AmqpValue(payload.getBytes()));
~~~

Sometimes AmqpValues of type String:

~~~java
message.setContentType(CONTENT_TYPE_APPLICATION_JSON);
message.setBody(new AmqpValue(payload.encode()));
~~~

I think this should be aligned to use the same way in every case. Preferably using data sections.

**Comment by pellmann** [comment]
See also https://github.com/eclipse/hono/issues/607

**Comment by ctron** [comment]
Duplicate of #607
