### ISSUE TITLE
Support tenant-scoped command response link in HonoClient

### ISSUE THREAD

**Issue by pellmann** [eclipse/hono#775]
With #708 we allowed command response links, that are not scoped for a device but for a tenant (or min. for tenant). Currently we do not yet support this case in HonoClient.

In the current variant, the command is sent to a device and the device responds directly. From the HonoClient's point of view, the application instance that sent the command also receives the answer directly and can continue working with it or resend the command in the event of an error.

In the variant with one response-link pro tenant it is not clear which instance of the application receives the response. The delivery is the same as for events and any instance that listens for responses can get the response. This makes sense if the response can be delivered to a central component (such as a persistence layer), as e.g. in Ditto. The direct connection between request and response is lost in this case.

**Comment by DanielMaier-BSI** [comment]
Fixed with #1028. I think we can close this issue.
