### ISSUE TITLE
Add maven profile to include Jaeger client

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#777]
It would be convenient to have a maven profile in Hono, with which Docker images of the Hono components get built that have the Jaeger OpenTracing client included.

**Comment by sophokles73** [comment]
Sounds reasonable

**Comment by ctron** [comment]
Yes, that would be great.

**Comment by sophokles73** [comment]
@calohmn can this be closed with https://github.com/eclipse/hono/commit/4361c352d96ecbccd7f860268ec2d86606cb6247 ?

**Comment by sophokles73** [comment]
@calohmn can this be closed now? If so, please do :-)
