### ISSUE TITLE
Separate interfaces for implementing mandatory and optional service operations

### ISSUE THREAD

**Issue by dejanb** [eclipse/hono#783]
Currently service interfaces define all operation that are defined by the API. Most of third-party registry implementations will only be interested in mandatory operations (as they have their own mechanisms for maintaining the data). It'd be good to separate mandatory and optional (CRUD) operations in separate interfaces, to ease implementation of third-party registers.

**Comment by sophokles73** [comment]
@dejanb can you close this issue if you think it is fixed with https://github.com/eclipse/hono/commit/98e2c573310bf997809d51bbe55e25c1cd78fac0

**Comment by jbtrystram** [comment]
maybe some other APIs that could benefit the same approach ?

**Comment by sophokles73** [comment]
@dejanb @jbtrystram Oh, my bad, I thought this issue was only about the RegistrationService ...

@jbtrystram sure, additional PRs for the other service interfaces are welcome :-)

**Comment by dejanb** [comment]
@sophokles73 @jbtrystram Yeah, I think we should do it for all "service" APIs:

* Credentials
* Tenants
* Authentication

Let's keep this issue as a placeholder for the work and do the work in the additional PRs

It'd be good to change the docs a bit as well, to better separate what's mandatory and what's optional for every API?

**Comment by jbtrystram** [comment]
Credentials, tenants and registration API have been refactored. (PRs #802 and #795 are still to be merged.)
However, the Authentication API only expose one operation, which is mandatory. So nothing to separate there. 
Should we close this ?

**Comment by sophokles73** [comment]
@jbtrystram Before closing this issue, we also need an entry in the [release notes](https://github.com/eclipse/hono/blob/master/site/content/release-notes.md) describing this API change.

**Comment by jbtrystram** [comment]
@sophokles73 would that work ? 
#806

**Comment by sophokles73** [comment]
@dejanb all changes have been made, so FMPOV you can close this issue ...

**Comment by dejanb** [comment]
@sophokles73 Great. Thanks @jbtrystram
