### ISSUE TITLE
AMQP Adapter: Implement Command & Control API

### ISSUE THREAD

**Issue by Alfusainey** [eclipse/hono#784]
This is a container issue for implementing the `Command & Control` API for the AMQP protocol adapter. All pull requests relating to `C&C` for the AMQP adapter will reference this issue.

**Comment by Alfusainey** [comment]
@sophokles73 

I have spent sometime looking at how C&C is implemented for both the HTTP and MQTT adapters to get a feel for how to approach it for the AMQP adapter. I see the implementation for the AMQP adapter following a similar pattern to how it is done for the MQTT adapter (as summarized below):

1. Device indicates that it is ready to receive commands (until further notice)
   - device publishes a message to an address encapsulating the `subscribe` operation in the message's subject.
     * message.address (authenticated device): `control/+/+/req/#` (i.e # is a placeholder for additional parameters e.g property bags)
     * message.address (unauthenticated device): `control/[tenant-id]/[device-id]/req/#`
     * message.subject = `subscribe`

     Device can only subscribe to receiving commands using one valid subscription address. This is 
     different from the MQTT adapter which allows devices to subscribe to a list of topics.

  - Upon the adapter receiving the message to subscribe for commands:
      * it sends a `device ready for command` notification downstream (with a ttd=-1).
  - Upon the adapter receiving a command from applications:
      * it forwards the command to the device connected to the adapter.
        * message.address (authenticated device): `control///req/<req-id>`
        * message.address (unauthenticated device): `control/[tenant]/[device-id]/req/<req-id>`
        * message.subject: `<command>` (command encapsulated in the message's subject)

2. Device indicates that it can no longer receive commands from applications
   - device publishes a message to an address encapsulating the `unsubscribe` operation in the message's subject.
     * message.address (authenticated device): `control/+/+/req/#`
     * message.address (unauthenticated device): `control/[tenant-id]/[device-id]/req/#`
     * message.subject = `unsubscribe`

3. Device publishes a message in response to a command received from applications.
   * message.address (authenticated) = `control///res/<req-id>/<status>`
   * message.address (unauthenticated) = `control/[tenant]/[device-id]/res/<req-id>/<status>`

WDYT?

**Comment by sophokles73** [comment]
> device publishes a message to an address encapsulating the subscribe operation in the message's subject.

No, the device opens a receiver link for that purpose, using an appropriate source address, e.g. `control/$tenant/$device/req` (where $tenant stands for the device's real tenant ID).

> Device publishes a message in response to a command received from applications.

yes, since the device already has an anonymous sender link open (for sending telemetry and events), it can use this same link to also send command response messages using one of the addresses you proposed.

**Comment by sophokles73** [comment]
@Alfusainey do you want to close this issue based on the outcome of your latest PR or do you want to continue to use it for adding integration tests? I would be fine with closing this issue now but still refer to it when you create a new PR for adding the integration tests ...

**Comment by Alfusainey** [comment]
> I would be fine with closing this issue now but still refer to it when you create a new PR for adding the integration tests ...

okay, I didn't know that was possible. I will close it now
