### ISSUE TITLE
Cannot use recent version of netty-tcnative-boringssl

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#785]
It turns out that the changes made in #698 lead to a situation where you can only use a concrete netty-tcnative library of the same version as is now included in the Docker images. The version currently included is netty-tcnative-2.0.10.Final. This means that if you want to use the BoringSSL implementation with the image, you are stuck to version 2.0.10.Final of that library as well. Using the most recent version (2.0.12) yields a segfault of the VM during startup. This is actually an issue because one of the advantages of using the PropertyLoader for adding (user provided) jars to the classpath is the flexibility it brings wrt the used version of the added libraries ...

**Comment by ctron** [comment]
Well, that is an issue with version 2.0.11 of netty-tcnative. They did some kind of super-breaking change between micro version changes.

What I could imagine is that we enable the use of netty-tcnative (all variants) using a maven profile. I did use that when doing the scale testing, enabling the epoll netty implementation, and I think the same approach as also suggested for enabling jaeger. I think this would work here as well.

**Comment by sophokles73** [comment]
@ctron but that means that we *do not* include `netty-tcnative` in the Docker images by default anymore, right?

**Comment by ctron** [comment]
Yes. The profile would add whatever version of netty-tcnative you want. By default I wouldn't enable any profile regarding netty-tcnative. So you would have to explicitly opt-in to any of the variants.

One variant would be the current variant. But if you don't select anything (as the docker images would) then nothing of netty-tcnative would get added.

**Comment by sophokles73** [comment]
@ctron  So, as a first step, in order to allow people to use a version > 2.0.11 we should first remove netty-tcnative from the Docker images. My understanding is that you only need/want it in the S2I builds for now. And there you are custom building netty-tcnative for the OopenSSL version at hand anyway, right?

**Comment by ctron** [comment]
The OpenShift S2I only provides the JNI layer of netty-tcnative. So that alone wouldn't be enough.

**Comment by sophokles73** [comment]
@ctron So, assuming that I remove the `netty-tcnative` dependency from hono-service-base, would you be able to do whatever it is you want to do in the S2I build?

**Comment by ctron** [comment]
> @ctron So, assuming that I remove the netty-tcnative dependency from hono-service-base, would you be able to do whatever it is you want to do in the S2I build?

No.

I created PR #787 to show what would be required. The PR would remove netty-tcnative from the docker images, but would also allow it to be enabled using profiles. Which S2I could then make use of.

**Comment by ctron** [comment]
PR #787 looks good from my perspective.

**Comment by sophokles73** [comment]
fixed in https://github.com/eclipse/hono/commit/e5d41a53572ea91e3628bb6d1568e1d126d14f9a
