### ISSUE TITLE
Issue in starting Hono client using Java command

### ISSUE THREAD

**Issue by shailesharya** [eclipse/hono#786]
Hey there,
I'm trying to start hono client using the following command

 java -jar hono-example-0.6-exec.jar --hono.client.host=hono.eclipse.org --hono.client.port=15671 \
--hono.client.tlsEnabled=true --hono.client.username=consumer@HONO --hono.client.password=verysecret \
--spring.profiles.active=receiver --tenant.id=DEFAULT_TENANT

but I'm facing some error
![screenshot from 2018-08-16 00-05-28](https://user-images.githubusercontent.com/41483772/44166782-e6837880-a0e9-11e8-94eb-44ef0d70cce8.png)

![screenshot from 2018-08-16 00-05-32](https://user-images.githubusercontent.com/41483772/44166808-f3a06780-a0e9-11e8-9c14-73ca834ba9bc.png)
I have tried different configuration but nothing worked 

please help me in this
thank you.

**Comment by Alfusainey** [comment]
is there any reason why you're omitting the `ssl`  profile? try to see what happens by doing `--spring.profiles.active=receiver,ssl`. BTW, a lot of the parameters you supplied (port, profile, etc) are available by default and can be omitted

also, do you have a  reason why you are running the example consumer as a packaged application instead of running it using the maven plugin (as outlined in [getting started guide](https://www.eclipse.org/hono/getting-started/))?

**Comment by sophokles73** [comment]
@shailesharya the command line you used is correct and should work. What I can see from the logs is that the client wasn't even able to establish a TCP connection to hono.eclipse.org:15671. Are you sure that you can access hosts on the internet on other ports than HTTP (80), i.e. are you on a corporate network that does not provide transparent access to the internet?

Another possibility is that you tried to connect at a time when we were restarting the host (which sometimes is required to apply OS updates). Can you try again to connect using your original command line?

**Comment by sophokles73** [comment]
Can you simply run
```
$ java -jar hono-example-0.6-exec.jar --hono.client.host=hono.eclipse.org --hono.client.port=15671 --hono.client.tlsEnabled=true --hono.client.username=consumer@HONO --hono.client.password=verysecret --spring.profiles.active=receiver
```
and post the output of it?

**Comment by shailesharya** [comment]
Guess what
it's working fine on my AWS instance now but not on my laptop

**Comment by sophokles73** [comment]
you mean: when you run the client from a VM on AWS it works but when you run the client on your laptop it doesn't? That would actually be an indicator for what I suspected earlier, i.e. that your laptop has no transparent internet connection ...

**Comment by shailesharya** [comment]
Got it. Thanks for your help sir

**Comment by sophokles73** [comment]
@shailesharya  can we close this issue?

**Comment by shailesharya** [comment]
yes, sir.
