### ISSUE TITLE
MQTT adapter does not check topic name prefix

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#79]
The MQTT adapter currently routes all incoming messages to Hono's *telemetry* endpoint. However, it should probably use the message's topic to determine the correct endpoint, i.e. messages sent to a topic starting with `telemetry/` should be routed to the *telemetry* endpoint whereas messages sent to a topic starting with `event/` should be routed to the *event* endpoint.

**Comment by ppatierno** [comment]
Closed on behalf of 0384e1c7726886f7a63fd788e5978e599d8a4383
