### ISSUE TITLE
Jmeter not able to end tests 

### ISSUE THREAD

**Issue by kaniyan** [eclipse/hono#804]
Not able to end Jmeter tests invloving HonoReceiverSampler and HonoSenderSampler, if HonoClient is unable to connect to hono.

![image](https://user-images.githubusercontent.com/18659982/44718009-fd997180-aabe-11e8-95af-c2e3306605ed.png)

**Comment by sophokles73** [comment]
@kaniyan can this be closed?

**Comment by kaniyan** [comment]
yes
