### ISSUE TITLE
Provide tenant scoped command receiver link for custom protocol adapters

### ISSUE THREAD

**Issue by sysexcontrol** [eclipse/hono#824]
Today, Command and Control receiver links in protocol adapters are always scoped to a device (that itself belongs to a tenant).
This is what is always used in Hono's protocol adapters that support Command and Control.

For some scenarios it can be desirable to open a Command and Control receiver link on the tenant level, so the protocol adapter can decide itself to which device(s) a command shall be delivered.
This may be combined with the possibility to set application properties for a command in the application and retrieve them in the protocol adapter (see commits 5020279 and 1a4ef1c1).

So the internal API must offer the possibility to skip the deviceId when opening the Command and Control receiver link.

**Comment by sophokles73** [comment]
> For some scenarios it can be desirable to open a Command and Control receiver link on the tenant level, so the protocol adapter can decide itself to which device(s) a command shall be delivered.

@sysexcontrol can you give an example of a scenario where this is required/useful?

**Comment by sysexcontrol** [comment]
@sophokles73 Sure!
This addresses protocols that are usually accessed by an intermediate layer ("`Network manager`"?), e.g. LoRaWAN.

To write a custom protocol adapter for such implementations/protocols, a receiver link is needed that is always open to receive commands for arbitrary devices. These commands are then usually routed to the `network manager`.

This issue is about to be able to open such a link on a tenant level by using the API with providing only the tenant - currently the deviceId also has to be provided.

**Comment by sophokles73** [comment]
@sysexcontrol I'm not sure if opening a receiver link like `control/${tenant}` would do the trick. What if you have other devices that e.g. use HTTP in this tenant as well? Opening the above mentioned link would then allow the AMQP 1.0 Network to route commands intended for a specific (HTTP based) device to the custom adapter instead of the HTTP adapter, which would have opened a standard receiver link on something like `control/${tenant}/${device}`, don't you think?

**Comment by sysexcontrol** [comment]
@sophokles73 : I fully understand your concerns and have 2 answers to that:

1.) multiple use of the `tenant` (e.g. in different protocol adapters):
this is indeed a problem. The idea was (and I did not mention this so far) to only extend the API but not to make use of this extension in Hono's standard PAs. However, custom PAs (e.g. to implement access to some LoRaWAN provider) can use this extension to build a tenant level receiver link for commands. 

They usually should be setup at the same time by narrowing the chosen tenant to only use the custom PA that is using this extension.

By such a configuration, the HTTP adapter could not receive messages for this tenant, and then we would not have this problem.

A pragmatic approach for supporting specific custom PAs.

2.) `control/${tenant}/${device}`: in my understanding this would not even be a problem, would it? 

If the application sends a command to `control/${tenant}/${device}`, it would reach the HTTP adapter,
if using the `control/${tenant}` link address, it would reach the custom PA.
The only thing that would NOT work is to customize the HTTP adapter and also open a link on the tenant level (but why should this be done?).

Or am I missing something?

**Comment by sophokles73** [comment]
> If the application sends a command to control/${tenant}/${device}, it would reach the HTTP adapter,
if using the control/${tenant} link address, it would reach the custom PA.

Have you actually verified this using the Dispatch Router? I suspect that the receiver link using `control/${tenant}` as the source address would also be considered a legit destination for a command sent over a link with a target address of `control/${tenant}/${device}`, but I am not 100% sure ...

**Comment by sysexcontrol** [comment]
@sophokles73 : ok, if you are not certain, I better check this, I agree!
It was my understanding, but I might be mistaken.

Will post the result here afterwards (will take a short while due to other prios currently).

**Comment by sysexcontrol** [comment]
Currently on hold, probably will not be implemented.
After having clarified this, I would close the issue - until then (probably tomorrow) it remains open.

**Comment by sysexcontrol** [comment]
Clarified - currently no one needs this solution anymore.
And since it is to some extent contradicting to the fundamental design of Hono to offer uniform access to devices, I close the issue now.
