### ISSUE TITLE
Command receiver links do not reopen after reconnection

### ISSUE THREAD

**Issue by sysexcontrol** [eclipse/hono#830]
Protocol adapters do not automatically reopen command receiver links if the connection to the AMQP 1.0 network fails.
For long living command receiver links that can occur for:
- MQTT connected devices
- HTTP connected devices with a high ttd value
- tenant scoped command receiver links for custom protocol adapters (soon being available)

this can be a major problem since the commands cannot be sent from applications anymore after temporary network problems.

**Comment by sysexcontrol** [comment]
@sophokles73 : With having PR #875 we now have a solution so that custom protocol adapters can reopen command receiver links themselves.
So I propose to remove this issue from the 0.8 project.

What remains a *fundamental* problem IMHO though are command receiver links for MQTT devices that stay connected for long.

Maybe the default implementation of the `connectionLost` handler in the MQTT adapter should close the MQTT connection (instead of inheriting the NOP implementation of the base class), or am I missing something?
This should be small work and could be done instead of fixing this issue in 0.8.

WDYT?

**Comment by sophokles73** [comment]
> Maybe the default implementation of the connectionLost handler in the MQTT adapter should close the MQTT connection (instead of inheriting the NOP implementation of the base class), or am I missing something?

That should do the trick, yes. In fact, only those connections to devices need to be closed, which have subscribed to the control topic. BTW the same holds true for the AMQP adapter.

If we implement this default behavior in the MQTT and AMQP adapter, don't you think we could close this issue as fixed?

**Comment by sysexcontrol** [comment]
> In fact, only those connections to devices need to be closed, which have subscribed to the control topic. 

:+1: this is true.

> If we implemented this default behavior in the MQTT and AMQP adapter, don't you think we could close this issue as fixed?

Yes, after the MQTT and AMQP adapters are equipped with such a connection-loss handler, this issue can be closed IMHO.

**Comment by sophokles73** [comment]
@sysexcontrol I think this has been fixed with #875 and #902 
if you agree, can you close this issue?

**Comment by sysexcontrol** [comment]
Yes, I agree - this is now fixed. Closing the issue.
