### ISSUE TITLE
Password Encoder supports more hash functions than documented

### ISSUE THREAD

**Issue by mbaeuerle** [eclipse/hono#835]
The `org.eclipse.hono.util.PasswordEncoderFactory` lists 5 password hashing algorithms:
- sha-256
- sha-512
- pbkdf2
- scrypt
- bcrypt

The [documentation](https://www.eclipse.org/hono/api/credentials-api/#hashed-password) just lists 3 of them:
- sha-256
- sha-512
- bcrypt

Are `pbkdf2` and `scrypt` fully supported yet and can be added to the docs?

**Comment by sophokles73** [comment]
FMPOV the hash algorithms are not supported (officially) unless we explicitly document them in the Credentials API. The library we use for computing hashes indeed supports the additional algorithms. However, we need to define how the hashed password maps to the *secret* structure (as we did for bcrypt). We then (may) need to implement this mapping in the Credentials validation code.

@dejanb Any further insights regarding this question?
@mbaeuerle Are any of these algorithms of particular interest to you?

**Comment by mbaeuerle** [comment]
PBKDF2 and scrypt are interesting on the long term as they are standardized by the IETF and proposed by the ENISA (in case of scrypt).

I am closing this issue, as my question is answered!
