### ISSUE TITLE
Hono Examples: client doesn't send any data to server

### ISSUE THREAD

**Issue by oliverfischer83** [eclipse/hono#84]
Hi Hono-team,

after trying out the Hono examples, it seems that the Hono client for telemetry data (started with` java -jar target/hono-example-0.5-M3-SNAPSHOT.jar --spring.profiles.active=sender --hono.client.host=<myIp>`) is not sending any data to the server. There is **no output** within the logging console (started with `java -jar target/hono-example-0.5-M3-SNAPSHOT.jar --hono.client.host=192.168.99.100`). The scenario works fine using the REST adapter.

regards,
Oliver

**Comment by sophokles73** [comment]
Thanks for reporting. This seems to be a problem with the sender establishing the connection with the Hono server on the (now) TLS secured port 5672.

**Comment by sophokles73** [comment]
Should be fixed in c36629ff337f5383b68acd2089c18e5498a5f2c3

Can you give it a try and close the issue if everything works as expected?

**Comment by oliverfischer83** [comment]
Works as expected. Thanks!
