### ISSUE TITLE
The pwd-hash base64 encoding is only required for sha hashes

### ISSUE THREAD

**Issue by mbaeuerle** [eclipse/hono#841]
Currently only `sha-256` and `sha-512` should be base64 encoded when creating credentials in the device registry but `bcrypt` hashes should not be. 
- On the one hand it is not necessary to base64 encode bcrypt hashes because they don't contain any special characters
- One the other hand a standardized secrets format where each hash algorithm behaves the same way is also desirable (i.e. where every hashed password is encrypted in base64)

**Comment by sophokles73** [comment]
The Credentials API already describes the specific format of the different hash values explicitly. FMPOV we  only need to remove `The Base64 encoding of` from the description of the *pwd-hash* field in the table for the *hashed-password* credentials type.
WDYT?

**Comment by mbaeuerle** [comment]
👍 That sounds reasonable to me!
