### ISSUE TITLE
MQTT connectivity issues with clients other than mosquitto_pub

### ISSUE THREAD

**Issue by crenz** [eclipse/hono#85]
I've been successfully publishing MQTT telemetry messages with mosquitto_pub as shown in the READMEs. However, I am encountering issues when connecting other MQTT clients:

- When connecting node_red to the Hono MQTT port, node_red keeps on immediately disconnecting and is unable to send out messages.
- When connecting mqtt-spy to the Hono MQT port, establishing a connection works, but once any message is sent, the client gets disconnected.

I've tried connecting both with empty username/password as well as a dummy credential set (“user:pass”), even though with mosquitto_pub it's not actually necessary to specify username and password.

**Comment by crenz** [comment]
I tried it out again just now and realized the issue was that I was using the wrong client ID – once I changed the client ID in both node_red and mqtt-spy to e.g. “4711”, and re-registered that device, it worked.

**Comment by ppatierno** [comment]
@crenz happy to know that it worked. So are you using the Node-RED stuff without problems ? Is it a specific use case for you ?

**Comment by crenz** [comment]
@ppatierno I was actually just testing MQTT connectivity. Node-RED was an easy way of pushing an existing MQTT sensor's values to the Hono MQTT connector without having to reconfigure the sensor. It seems to work out fine:

`23:35:33.034 [vert.x-eventloop-thread-0] INFO  o.e.hono.example.ExampleReceiver - received telemetry message [device: 4711, content-type: application/octet-stream]: {"temp":19.63,"pressure":1.028536e3,"humidity":36.02}`

I did notice that having to set the client ID to the device ID could be kind of limiting – if you have a scenario where a kind of gateway receives MQTT messages from a number of devices and wants to forward those to Hono, it would have to establish a separate connection (with separate client ID) for each device. But I'm not sure whether that scenario is very relevant for real-world applications.
