### ISSUE TITLE
MQTT Jmeter Sampler for Command and Control

### ISSUE THREAD

**Issue by kaniyan** [eclipse/hono#853]
Currently [emqx/mqtt-jmeter](https://github.com/emqx/mqtt-jmeter) plugin is being used to perform our load tests (to publish telemetry and events using MQTT). Unfortunately we cannot use it to test the command and control. We need a new Sampler that subscribes to a control topic, receives commands, parses request-id from topics and sends command responses.

**Comment by sophokles73** [comment]
The JMeter module has been removed from Hono some time ago already
