### ISSUE TITLE
Pass clients to connection events API as context object

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#865]
Currently one of the connection events implementation requires to have access to a messaging and registry client. However it is not possible to re-use the existing client instances. Also doesn't the connection events implementation start the clients, and track their health. This is required to be provided by the application. This also has to take threading models into account.

However, it would be possible to create a context object, passing the clients of the protocol adapter in each call to the connection events API, allowing the implementation to re-use the protocol adapters instances. That would eliminate the need for lifecycle management, thread management and health checking.

**Comment by sophokles73** [comment]
@ctron This seems to be fixed, isn't it?
