### ISSUE TITLE
Upgrade to Docker 1.13.1

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#87]
Docker 1.13 has been released recently and introduced support for deploying multi-host, multi-service applications by means of Docker Compose files which would be very helpful to us.
However, during the course of doing so, they have dropped support for the *volumes_from* feature in the compose file which we are currently using to share certificates and configuration among containers.

We need to replace the *volumes_from* approach with some alternative, e.g. using the new [Docker Swarm Secrets](https://docs.docker.com/engine/swarm/secrets/) mechanism and maybe generating the Dispatch Router config files on the fly during start-up from environment variables using [dockerize](https://github.com/jwilder/dockerize).

**Comment by ppatierno** [comment]
I started to get rid of volumes_from in the #93 PR for Kubernetes/Openshift support. Maybe it could be a good starting point for upgrading to Docker 1.13.

**Comment by sophokles73** [comment]
Absolutely, that's what I thought as well :-)

In the meantime, Docker 1.13.1 has been released which also supports defining and configuring the use of secrets within the compose file ...

**Comment by sophokles73** [comment]
Most of the work for removing *volumes_from* has already been done by Paolo as part of #93.
fixed in 617390be59c90569c4055401d24fc3701b216b1f
