### ISSUE TITLE
Add possibility to register credentials with cleartext password

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#871]
For prototyping and learning it would be helpful to have an operation in the Credentials (REST) API which allows to register new credentials without the need to hash the password. The `CredentialsHttpEndpoint` could be extended with an operation that takes a cleartext password and handles the hashing.

**Comment by sophokles73** [comment]
That would be highly appreciated :+1: 
It would be cool if the hash function to use could be configured by means of an environment variable with a default of *bcrypt*. WDYT?

**Comment by b-abel** [comment]
Implemented by PR  #949.
