### ISSUE TITLE
MQTT/AMQP adapter: Deleted/disabled devices should not be able to connect

### ISSUE THREAD

**Issue by kaniyan** [eclipse/hono#876]
A device has been registered and credentials for that device has also been added.  Then the device is deleted but not the corresponding credentials. In this case, the deleted device is still able to subscribe to control endpoint, receive commands and send command responses.

**Comment by sophokles73** [comment]
If a device is deleted (I assume you are referring to the process of removing its registration information from the Device Registration service) then the device should no longer be able to connect to the MQTT adapter at all, and thus not be able to subscribe to the command topic.

I suspect that the behavior you experience is merely because the registration information (the assertion, to be precise) is cached in the protocol adapter for a configurable amount of time. We (currently) do not invalidate the cache if the underlying information is removed from the registry. Can you validate this by e.g. restarting the MQTT adapter after deleting the registration information and see if the device can still connect? You should also be able to simply wait for the cache to expire (5 minutes?) instead of restarting the adapter.

**Comment by kaniyan** [comment]
> If a device is deleted (I assume you are referring to the process of removing its registration information from the Device Registration service) then the device should no longer be able to connect to the MQTT adapter at all, and thus not be able to subscribe to the command topic.
> 
> I suspect that the behavior you experience is merely because the registration information (the assertion, to be precise) is cached in the protocol adapter for a configurable amount of time. We (currently) do not invalidate the cache if the underlying information is removed from the registry. Can you validate this by e.g. restarting the MQTT adapter after deleting the registration information and see if the device can still connect? You should also be able to simply wait for the cache to expire (5 minutes?) instead of restarting the adapter.

I tried by restarting the MQTT adapter and I am still able to connect to the Mqtt adapter, subscribe to the control endpoint, receive commands and send responses.

**Comment by kaniyan** [comment]
Currently for telemetry and event messages, this check is being done on receiving those messages. I agree that it should be done as part of establishing the connection.

**Comment by sophokles73** [comment]
Would you like to create a PR for fixing this?

**Comment by kaniyan** [comment]
sure.

**Comment by kaniyan** [comment]
As per this solution, we check the device registration at the time of the connection establishment.  Assume a device, which is connected to the Mqtt adapter, is deleted. In this case, the deleted device, 
 that remains connected, can still perform telemetry, event and command operations until the Mqtt adapter is restarted or the device reconnects.  I think that this scenario (Handling deletion of connected devices) is also applicable to other adapters.

**Comment by sysexcontrol** [comment]
I had similar thoughts already and kind of agree to what @kaniyan outlines here.
How about a compromise solution :
- check during connection establishment
- check again for any downstream or upstream operations every "once in a while", e.g. all 10 or 30 minutes

Would require an associated timestamp or something similar to be stored `per connection` and evaluated when handling such an operation.

Makes things a little more complicated, but for security reasons we do not have a choice, do we?
Another choice would be to broadcast an event if a device was deleted or disabled (this case was not discussed so far IMHO) - but this is making things even more complicated.

**Comment by sophokles73** [comment]
@kaniyan I think we have addressed and resolved the most imminent issue, i.e. rejecting connect attempts from disabled/deleted devices. The other problems discussed in this issue are still valid. However, for reasons of clarity, I would prefer to have separate/new issues being created for them, e.g. preventing disabled/deleted (but already connected) devices from subscribing to commands and actively disconnecting devices that have been disabled/deleted (see #293). Can you please create those issues and then close this issue, if you agree that we have addressed the underlying problem?
