### ISSUE TITLE
Website typos

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#88]
- on https://www.eclipse.org/hono/component/mqtt-adapter/
the layout is broken in the middle of the page (missing block termination before "Run using Docker Compose").
- on https://www.eclipse.org/hono/component/hono-server/
the default for HONO_DOWNSTREAM_PORT in the table is 5673 (not 5672)

**Comment by sophokles73** [comment]
Thanks for reporting :-)

Should be fixed in b9337a35b0e0b4e38d342ae2265b5e4fce0e585c
