### ISSUE TITLE
CommandConnection#getOrCreateCommandConsumer does not fail returned future in case of some errors while link establishment

### ISSUE THREAD

**Issue by DanielMaier-BSI** [eclipse/hono#886]
CommandConnection#getOrCreateCommandConsumer does not fail the returned future in case of some errors while link establishment, e.g. server returns "Node not found". Instead it returns future with result of null. Root cause seems to be that
https://github.com/eclipse/hono/blob/d4a0a128c23e15d8f46b9e096087f03e51598a20/client/src/main/java/org/eclipse/hono/client/impl/CommandConnectionImpl.java#L101-L120 completes the future regardless of the result. 

Is this expected behaviour? I expected the future to fail if the server returns some error codes.

By the way: This issue is not urgent for us as we just map the future in our code to a failed future when we get a null result.

**Comment by sysexcontrol** [comment]
This is IMHO `not` an expected behaviour, but just a bug - thanks for reporting @DanielMaier-BSI :+1: !

Will provide a fix for that.
