### ISSUE TITLE
Hono introduction image uses non-embedded, non-standard font

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#887]
I always wondered why the fonts looked a bit weird on the Hono introduction image. It looks like the AI and the SVG image use a font named `Ubuntu`, but doesn't embed the font.

That will work on Ubuntu, but it doesn't work on Fedora, RHEL/CentOS, Windows and MacOS:

RHEL:

![image](https://user-images.githubusercontent.com/202474/48135349-ffd93280-e29c-11e8-9ce8-e264b9e7479e.png)

Windows 10:

![image](https://user-images.githubusercontent.com/202474/48135359-05367d00-e29d-11e8-9f25-9506b5e54379.png)

I think a proper solution would be to either:

* Use one of the standard web fonts: https://www.w3schools.com/cssref/css_websafe_fonts.asp
* Embed the font into the SVG – might be problematic due to licensing issues
* Import the font into the SVG via CSS – might be problematic due to licensing issues or GDPR

**Comment by sophokles73** [comment]
That's really bad :-( FMPOV we should go for a standard font as proposed by option 1.

**Comment by sophokles73** [comment]
@ctron can we close this?

**Comment by ctron** [comment]
Fixed.
