### ISSUE TITLE
Command sender client cannot check for credits before sending

### ISSUE THREAD

**Issue by sysexcontrol** [eclipse/hono#888]
Our command client lacks the possibility to check for available credits before sending a command.

To be more detailed, it seems that only the defined interface lacks it - the underlying implementation offers such a possibility.
Methods for `getting the current credits` and to `set a drain handler` are necessary to offer.

Remark: to rely on the `ttd` event is not sufficient, since the event may be delivered at a point of time when a `flow frame` (that announces new credits) was not received yet - resulting in no credits if a `send` is invoked directly after receiving the `ttd` event.

**Comment by sysexcontrol** [comment]
@sophokles73 @kaniyan : I guess this issue can be closed now, right?

**Comment by kaniyan** [comment]
yes with PR #898. This can be closed.

**Comment by sysexcontrol** [comment]
Fixed by PR #898 .
