### ISSUE TITLE
Add a (simple) MQTT protocol adapter

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#9]
We basically need the same as for HTTP (see #3).

It would be great if we could use Eclipse Paho/Mosquitto for it. But that's not a prerequisite.

**Comment by hriships** [comment]
Can someone give the brief idea. Just to confirm we are expecting **MQTT broker** adapter here right?

**Comment by sophokles73** [comment]
I guess there are several ways this could be implemented.
One option would be to use a dedicated (separate) MQTT broker to which the devices connect. Our protocol adapter would then connect to that broker and to Hono as a client and translate hence and forth between MQTT and AMQP 1.0.
The other option would be to implement/embed MQTT in the protocol adapter itself, e.g. using something like Moquette and let the devices connect to the adapter directly.

**Comment by hriships** [comment]
Alright, thanks.
First option looks easy as compare to second one to begin with.

**Comment by sophokles73** [comment]
However, it also introduced another component (that needs to be managed) to the overall picture, i.e. the MQTT broker which will also most likely need to be scaled out etc.
So, at first sight it might look tempting to simply rely on that but in practice it might actually be easier to start with option 2 and then evolve ...
May I ask what your interest in this is? Would you like to start some work on this issue? We could certainly use some help :-)

**Comment by hriships** [comment]
ohh mistaken I wrote first option, actually I meant to say second one 👍
Coming to interest nothing specific as of now, certainly I have keen interest in doing some contribution in IoT/cloud.
Sure would like get some help to begin with.

**Comment by kartben** [comment]
I think Option 1 is also a bit tricky when it comes to e.g retained messages (what happens when the protocol adapter has to reconnect to the front-end broker, and therefore receives the retained messages all over again?), or ensuring QoS > 0 is handled properly (it would be confusing for a publisher receiving an ACK from the front-end broker to realize that in the end the message didn't make it to the "actual" backend because the protocol adapter had hiccups).

**Comment by sophokles73** [comment]
@kartben, all valid points. However, I think a first goal would be to get at least basic support for QoS 0 Telemetry upload (that's what we have implemented in Hono so far). Maybe we do not even need to support all of the MQTT feature set in conjunction with Hono ...

@hriships implementing Telemetry upload support based on Moquette would actually be a great starting point IMHO :-)

**Comment by ppatierno** [comment]
My idea is to add main MQTT features (like will, retain and session) at AMQP protocol level. It means that even AMQP protocol (so no MQTT) could provide a feature like "will" that is something that the spec doesn't provide. 
It means that my idea of MQTT protocol adapter isn't necessarily based on an MQTT broker.
I developed an MQTT server that now it's part of the official Vert.x stack : https://github.com/vert-x3/vertx-mqtt-server

It's not an MQTT broker but is a server able to handle MQTT connections with clients. It means that the high level application which uses the server (in the Vert.x style) has some events for being notified (i.e. a CONNECT comes in, a SUBSCRIBE comes in, ...) and some method callable to the MQTT endpoint for replying to the client (i.e. sending a CONNACK, a SUBACK, ...). In the middle, the application can put its own logic that in our case could be use an AMQP client for communicating with Hono (i.e. event on PUBLISH from the MQTT server, means AMQP client sends message to telemetry API in Hono, then if needed sends PUBACK to the MQTT endpoint).

In order to add MQTT features on AMQP, other services could be necessary (for will, retain and so on) : all of them define an abstraction layer (and an API) on how they could be implemented (using a real MQTT broker, an AMQP broker, Kafka, a simple file system, a DB).

**Comment by ppatierno** [comment]
Even if not providing all the MQTT features but just a translation for now, I'd like to start developing this adapter using the MQTT server for that. WDYT ?

**Comment by sophokles73** [comment]
Sounds great, @ppatierno :+1: 

By all means, go ahead :-)

**Comment by danielbohn** [comment]
@ppatierno do you have any idea how to map the MQTT Topics to the AMQP 1.0 semantic which is offered by Hono ? E.g. a client (devie) will send a message on the mqtt Topic:  livingRoom/temperature with payload 22.0

**Comment by ppatierno** [comment]
@danielbohn I thought about what you said at EclipseCon and this is my opinion on that ...

In the Hono ecosystem you have to see MQTT just as another "transport protocol" but you can't change the semantics of the endpoints and API defined by the backed AMQP interface. It means that you aren't free of defining your topics just like "livingRoom/temperature" ... that could work well for a little and customized solution but not for a connectivity layer that should support any kind of IoT semantics and communication.
I mean that Hono API defines telemetry/TENANT_ID for sending data and it's the only topic you can use from an MQTT client perspective, adding the metadata and information inside the payload.

It's the quite realistic this meaning ... it works in the same way for other big companies IoT platforms.

**Comment by danielbohn** [comment]
@ppatierno yes than we have the MQTT connector as just another "transport protocol". We can not provide all the good features of MQTT to our customers. Do we really want this ? From my point of view in Hono we focus currently only on the adress of devices. In MQTT this is simplified the clientId. I think we need a way to descibe the content of a message. From my perspective this is in MQTT the Topic.
I had also a look at one of these big companies for IoT platforms (Iot Hub from Azure). They provide also additional possibilities to set some custom values at the Topic. They called this {property_bag}.

**Comment by ppatierno** [comment]
@danielbohn the Azure IoT Hub doesn't provide the way to have a topic like "livingRoom/temperature". The schema for telemetry is well defined as "devices/{device_id}/messages/events" like our "telemetry/TENANT_ID".
They added the property bag just as a way to carry properties for an AMQP internal mapping into the corresponding AMQP properties. Do we want this ? 

Btw it's different on being free to have any name for the topic that is instead well defined even in the Azure IoT Hub and Hono.

**Comment by dguggemos** [comment]
Regardless of how other IoT platforms do this, why should we not allow custom extensions of the address after the DEVICE_ID level e.g. something like telemetry/{TENANT_ID}/{DEVICE_ID}/livingRoom/temperature? This would allow to further route the message based on the information provided in the address. If this additional information is provided in custom headers or even in payload, one would always have to inspect the headers/payload to further process the message. Simple routing as it is applied by the Dispatch Router isn't possible with his approach.

@ppatierno I don't quite understand your last statement, could you explain a bit more?

**Comment by ppatierno** [comment]
The dispatch router can't route on more generic custom properties. You should have some different component in Hono but with much overhead.

The last statement referring to the fact that the {property_bag} isn't the extension you are talking about (i.e. adding the /livingRoom/temperature at the end of the telemetry endpoint) but just a way to bring properties from MQTT to AMQP internals.

**Comment by danielbohn** [comment]
@ppatierno what do you mean with generic custom properties ?

**Comment by danielbohn** [comment]
@ppatierno what is your opinion or experience with your customers regarding the MQTT protocol ? How they use this protocol ?

**Comment by dguggemos** [comment]
> The dispatch router can't route on more generic custom properties. You should have some different component in Hono but with much overhead.

That's why we should consider to allow a "custom topic" after the {DEVICE_ID}, to leverage Dispatch Router's mechanism.

> just a way to bring properties from MQTT to AMQP internals

Ok, then those properties are attached to each message sent to this address?

**Comment by ppatierno** [comment]
@danielbohn I mean that router can't route messages inspecting an application property inside an AMQP message. I.e. you can set an application properties named "my_prop" with some value. Router can't route message based on "my_prop" value.

@dguggemos yes it seems that their MQTT "adapter" gets the {property_bag} from the topic and put these properties into each message sent to that address.

**Comment by danielbohn** [comment]
@ppatierno ok i also think it is a really bad idea to look into every message. But are there any disadvantages to allow a flow felixble adress schema in AMQP 1.0 after the deviceId what was also ment by @dguggemos . E.g telemetry/{TENANT_ID}/{DEVICE_ID}/livingRoom/temperature ? Can the Qpid Dispatch Router handle this ?

**Comment by ppatierno** [comment]
in AMQP 1.0, the address is just a string and there is no specific semantics for that.

The router routes messages based on the attached address (from source and/or target) and "to" system property inside the message.

I can suggest to open this discussion to broader audience in the hono-dev mailing list where other people from router team can jump in (if interested ;)).

Btw it's not so related on what the router can do ... but if we really want having such address schema using MQTT. Today I see it just as another supported transport protocol on Hono but API defines the address endpoint.

**Comment by sophokles73** [comment]
My understanding is that the dispatch router's routing behavior can be configured by means of *address prefixes* as of today, e.g. you can specify that messages with addresses starting with `telemetry/*` are dispatched to multiple consumers concurrently or to a single consumer only. For that it doesn't matter whether the address contains any more data *after* the `telemetry/${tenant}/${device}` prefix.
We actually already support arbitrary strings as the `${device} part of the address, in particular we support it to contain a full path with slash characters as separators. Hono doesn't care about this, however, and treats the whole string as one.
Regarding the capability to allow for clients of the MQTT adapter to use arbitrary topic names, I agree with @ppatierno that we do not need to support that, at least not in the first step. Maybe we can later add funtionality to the MQTT adapter to *map* such topics to the addresses defined by Hono's APIs. But we should keep in mind that we are not implementing an MQTT broker but instead simply provide support for using MQTT as the transport protocol.

**Comment by danielbohn** [comment]
@sophokles73 thanks for the clarification. Yes i also think we do not need to support this in the first step.

**Comment by ppatierno** [comment]
I haven't tried it yet but I think that if we have something more after the ${device} part, the ResourceIdentifier class could raise following exception : 

IllegalArgumentException("resource must not contain more than 3 segments")

**Comment by sophokles73** [comment]
Then we should change that. But I think that we at least intended `ResourceIdentifier` to support this ...

**Comment by ppatierno** [comment]
@sophokles73 could we add the MQTT adapter with current status as part of the next 0.5-M2 ? WDYT ?

**Comment by sophokles73** [comment]
Sure, but then you need to add a README.md to the adapter module :-)

**Comment by ppatierno** [comment]
Sure ... I'll do that !

**Comment by ppatierno** [comment]
Currently I'm using the MQTT adapter publishing telemetry in the following way : 

topic -> telemetry/TENANT_ID
client_id -> DEVICE_ID

So the DEVICE_ID isn't specified into the topic.
We should support even topic as telemetry/TENANT_ID/DEVICE_ID.
The client_id is specified only in the CONNECT packet while the topic is specified for each PUBLISH message. Fortunately I have the client_id of the MQTT remote client connected so I can check that for every PUBLISH, the client_id matches the DEVICE_ID in the topic.

Is this what we want after the discussion at EclipseCon ?

With current adapter we are authenticating the MQTT adapter not the remote MQTT client.

WDYT ?

**Comment by sophokles73** [comment]
Sounds reasonable to me. The MQTT adapter needs to *translate* (or better: strip down) the topic name into Hono's `telemetry/${tenant}` address pattern and include the device_id (taken from the topic name) in the `device_id` AMQP application property.
The MQTT adapter also MUST check that the client only writes to a topic containing the device_id it has been authenticated as. Hono then only authenticates the MQTT adapter and *trusts* it with having authenticated the client properly.
At least that's my world view. Any other opinions?

**Comment by sophokles73** [comment]
Will now close this issue as we have a first version of the MQTT adapter supporting upload of Telemetry data via MQTT :-)
