### ISSUE TITLE
Add specific value property for find operation in device registration API

### ISSUE THREAD

**Issue by pellmann** [eclipse/hono#90]
In the device registration API to find a device by data, you need to give the key with the property "key" but the value with the property "device_id". To be consistent I suggest to add a new property called "value". So to search for e.g. city=berlin you need to give key=city and value=berlin instead of key=city and device_id=berlin.

**Comment by sophokles73** [comment]
sounds reasonable, would you care to create a PR?

**Comment by sophokles73** [comment]
We came to the conclusion that we probably need to make changes to this as part of introducing a Credentials API anyways. So closing for now.
