### ISSUE TITLE
Close connection if devices/gateways/tenants are disabled/deleted 

### ISSUE THREAD

**Issue by kaniyan** [eclipse/hono#903]
When a device requests connection to the Hono server, credentials are verified and so the device registration and then the connection is established. Assume a device, which is already connected to the Hono server is being deleted from the device registry. This deleted device that remains connected, is still able to perform telemetry, event or command operations until the adapter or the device is restarted/reconnected.  The same situation is applicable when gateways or tenants are disabled. There is also already an issue #293 which talks about actively closing connections when credentials are deleted or changed. 

IMHO I think it is necessary to actively close those connections when devices (gateways/tenants) are no longer registered.

**Comment by sophokles73** [comment]
@kaniyan I think that this has been resolved by performing these checks with every message/subscribe request. Can you verify and comment/close accordingly?

**Comment by kaniyan** [comment]
@sophokles73 Yes we introduced checks with message/subscribe request. This issue also goes one step further, whether to actively close the existing connections or not, once the devices are no longer registered.

**Comment by sophokles73** [comment]
@kaniyan Personally, I do not think that we need to actively close connections to devices that have been disabled. The checks we already have in place are sufficient FMPOV.

@calohmn @ctron @dejanb WDYT?

**Comment by kaniyan** [comment]
@sophokles73 With the current checks and resource limits in place, I wouldn't emphasis any longer on actively closing the connections. IMHO we can close this issue.
