### ISSUE TITLE
Multiple Devices connected to single Tenant

### ISSUE THREAD

**Issue by shailesharya** [eclipse/hono#904]
Hey,
       I have tried to register 2 devices with a single tenant and it worked but when I send a message from the device to the client I'm able to get only messages from one device-id and not from the other device-id.

      so how do I figure it out?
  
      Hope my point is clear here.

**Comment by ctron** [comment]
Hi Shailesh,

maybe you can provide a bit more information. What protocol adapters are you using, how are you consuming data, what response do you get back when you publish your data, is there any errors in the logs.

This will definitely help in understanding your problem.

**Comment by sophokles73** [comment]
closing, no response
