### ISSUE TITLE
Does Eclipse Hono provide LwM2M Client/Server Source Code?

### ISSUE THREAD

**Issue by maul5** [eclipse/hono#92]
Hello, I have question.

Do you happen to know does Eclipse Hono provide(support) LwM2M Client/Server Source Code?

**Comment by sophokles73** [comment]
Hi,
Hono does not itself implement a LWM2M server if this is what you're asking. However, we are planning to add a LWM2M protocol adapter based on the [Eclipse leshan](https://www.eclipse.org/leshan) project which provides an implementation of LWM2M client, server and bootstrap server. Once we have this protocol adapter, it will be possible to e.g. consume notifications sent by managed devices via Hono's telemetry and event APIs.

**Comment by maul5** [comment]
Thanks, Kai Hudalla.

Do you happen to know does the LwM2M Adapter work with LwM2M Server in front of Hono?
Or Can I receive information directly from the LwM2M communication device?

Best Regards,

**Comment by sophokles73** [comment]
To be clear: there currently is no LWM2M protocol adapter. However, we envision it to be built on top of leshan and thus it will serve as a LWM2M server, yes.
Not sure what you mean by *Can Hono receive information directly from the LwM2M communication device* though ...

**Comment by maul5** [comment]
Thanks,

![20170214_110438](https://cloud.githubusercontent.com/assets/7858036/22912217/3c66b980-f2a7-11e6-8374-ace295332c16.jpg)

Case 1) Through the Leshan Server
Case 2) Direct connection Leshan Adapter

Which one do you think is LwM2M adapter archetecher?

**Comment by sophokles73** [comment]
We are currently thinking in the direction of what you pictured in case 2.
However, we are also considering splitting up leshan into two parts:
1. a CoAP protocol adapter to which the devices connect
2. a LWM2M application that would be located *right* of Hono.

But this has not undergone a lot of deeper thinking yet ...

**Comment by maul5** [comment]
Thanks,

![hono_instance](https://cloud.githubusercontent.com/assets/7858036/23069051/4971837a-f569-11e6-8523-d90b810df78e.png)

(In the picture above)
Do you happen to know does the Hono Server include MOM(ActiveMQ)?
Is the server acting as an Message Queue?

Best Regards,

**Comment by sophokles73** [comment]
The original question seems to have been answered and there doesn't seem to be any issues with Hono. I would therefore kindly ask you to move this discussion to the mailing list if further questions arise. Thank you.

**Comment by fayvaz** [comment]
Hello
Is there any update related to lwm2m adapter support on Hono? The second question is that any plan to connect Hawkbit DMF to Hono client. As far as I know, Hawkbit DMF supports AMQP 0-9-1 (RabbitMQ) and this situation is not proper for Hono client which supports AMQP1.0. I wonder if it can be solved via AMQP1.0 plugin on RabbitMQ?thx

**Comment by sophokles73** [comment]
> Is there any update related to lwm2m adapter support on Hono? 

There are no plans for a LWM2M protocol adapter at the moment. We are thinking about adding a CoAP adapter, though.

> The second question is that any plan to connect Hawkbit DMF to Hono client. As far as I know, Hawkbit DMF supports AMQP 0-9-1 (RabbitMQ) and this situation is not proper for Hono client which supports AMQP1.0. I wonder if it can be solved via AMQP1.0 plugin on RabbitMQ?

As this seems to be a question related to hawkbit's future plans, you should ask that question on the hawkbit mailing list/GitHub.

**Comment by RomainPelletant** [comment]
Hi,
Any update about LwM2M adapter five years later?
Still no chance to see it coming into hono?
Thanks in advance

**Comment by sophokles73** [comment]
No, at least not from my side. Just out of curiosity, which features/interfaces of LwM2M are you specifically interested in?

**Comment by RomainPelletant** [comment]
@sophokles73 thanks for your answer.
We are interested in managing MQTT devices for telemetry and LwM2M devices for telemetry/fleet management/keys manager/bootstrap and FOTA.

We took a look at the hono/ leshan papier from Eclipse and saw a solution by using Hono : https://www.eclipse.org/lists/hono-dev/pdfy9O8qnvxIr.pdf
Do you think you shoule consider other solutions/platforms/tools?

**Comment by sophokles73** [comment]
> and LwM2M devices for telemetry/fleet management/keys manager/bootstrap and FOTA.

I had been doing some prototyping with LwM2M support in Hono's CoAP adapter but quickly ran into some conceptual problems regarding Observe relations in the context of FOTA that were not easy to overcome. I therefore did not further pursue the approach.

The given slidedeck had been based on the idea of having a dedicated (single instance) LwM2M adapter which we also did not further evolve as it was unclear as to how to scale it out.

Currently, my best bet would be to run a dedicated leshan server next to Hono and maybe try to use the same database for keeping the device registration data.

**Comment by RomainPelletant** [comment]
@sophokles73 thanks for your advices

**Comment by gozeist** [comment]
Hello, 

To be sure, I have a question. I've read when a device tries to connect to one of Hono’s protocol adapters, the protocol adapter first tries to authenticate the device using information  kept in the Device Registry. In this case, the same process should be applied to use LwM2m devices via coap protocol. On the other hand, we need to set up/develop a separate Leshan server in order to use the LWM2M protocol.  If I don't get it wrong, if we are not going to use a gateway, the devices will communicate with the Leshan server, not directly over Hono.  Is it right?

I know, Eclipse Leshan is a library for implementing applications that use the LWM2M protocol to manage devices. 
So, from the Hono point of view, will Leshan server be like a separate solution application where we can use the common database for register  as a completely standalone application server?

Thanks, best regards,  Tolga

**Comment by sophokles73** [comment]
> To be sure, I have a question. I've read when a device tries to connect to one of Hono’s protocol adapters, the protocol adapter first tries to authenticate the device using information kept in the Device Registry.

Yes, that is the case.

> On the other hand, we need to set up/develop a separate Leshan server in order to use the LWM2M protocol. If I don't get it wrong, if we are not going to use a gateway, the devices will communicate with the Leshan server, not directly over Hono. Is it right?

Yes, the LwM2M devices will connect to your leshan server in this case.

> So, from the Hono point of view, will Leshan server be like a separate solution application where we can use the common database for register as a completely standalone application server?

From Hono's point of view, your leshan server is completely independent from Hono. However, you might still allow your leshan server to retrieve data from the Hono Device Registry. That is just a matter of configuring authorizations. You could then use the stored information to authenticate the devices.

**Comment by gozeist** [comment]
Thanks, Kai Hudalla for your information and recommendation.
Best Regards,
