### ISSUE TITLE
Support limiting the number of simultaneously connected devices

### ISSUE THREAD

**Issue by sysexcontrol** [eclipse/hono#927]
Protocol adapters should support limiting the number of simultaneously connected devices per tenant.
The limit should apply to all devices of the tenant connected to any protocol adapter instance (regardless of transport protocol).
The limit must be configurable per tenant.

**Comment by sophokles73** [comment]
@kaniyan can we close this issue from your point of view?

**Comment by kaniyan** [comment]
@sophokles73 With the last merged PRs, now this feature is available in Hono. Yes, we can close this issue.

**Comment by sophokles73** [comment]
fixed in https://github.com/eclipse/hono/commit/bba1d9d6e9b16b218c2806ac05b000ec5b8b784d
