### ISSUE TITLE
Question: SonarQube for Eclipse Hono

### ISSUE THREAD

**Issue by Alfusainey** [eclipse/hono#940]
I understand that there is already a [SonarQube](https://wiki.eclipse.org/SonarQube) instance available for Eclipse projects and am wondering if there is a reason for not setting it up for Hono?

IMHO, (static analysis) issues reported on the SonarQube dashboard can be another good way for beginners to find their way around the code base :-)

**Comment by sophokles73** [comment]
In general I agree that having something like SonarQube helps with improving code quality. So far, we haven't considered this being an issue for Hono so nobody actually wanted to spend the effort setting it up.

I have not, so far, perceived SonarQube as a tool for helping beginners finding their way around the code base, though. Interesting thought :-)

**Comment by Alfusainey** [comment]
should i close this then or i can leave it open?

**Comment by sophokles73** [comment]
FMPOV you should close this issue.
