### ISSUE TITLE
Headers device-id and tenant-id missing in command response

### ISSUE THREAD

**Issue by dguggemos** [eclipse/hono#958]
When using Hono's command&control together with Ditto, I noticed that the command responses do not contain the `tenant-id` and `device-id` headers, as provided for example in telemetry messages.
This would be very useful information for us, as we would not need to remember which device sent a command and correlate the response using the `correlation-id` (across multiple nodes in the worst case).

**Comment by kaniyan** [comment]
Currently as part of the telemetry and event messages, the application properties contain `device-id` and not `tenant-id`. I think `tenant-id` should also be part of it. Eventually the command responses should also have the both.

**Comment by sophokles73** [comment]
> This would be very useful information for us, as we would not need to remember which device sent a command and correlate the response using the correlation-id (across multiple nodes in the worst case).

Including the device ID in a command response as an application property should be no big deal. Do you also need the message to contain the tenant ID or can you derive the tenant from the *connector* that the command response is received over? I would assume that you do the same for telemetry/events already, don't you?

**Comment by sophokles73** [comment]
@dguggemos any news on this?

**Comment by dguggemos** [comment]
We do not need the `tenant-id` currently, but maybe in the future. As the PR also contains the `tenant-id` for the command responses, I'm completely fine with the changes. 👍
