### ISSUE TITLE
Sending telemetry fails after restarting Dispatch Router

### ISSUE THREAD

**Issue by dguggemos** [eclipse/hono#96]
I'm sending telemetry data via Hono REST Adapter -> Hono -> Dispatch Router -> external application. After the Dispatch Router is restarted messages are dropped:
> 09:53:19.349 [vert.x-eventloop-thread-3] INFO  o.e.h.t.i.ForwardingTelemetryDownstreamAdapter - no downstream sender for link [5c595b4f-31c2-4c4f-a898-54f20b2ca36f] available, discarding message and closing link with client

The receiving application did successfully reconnect to the Dispatch Router as well as the Hono server. But a new sending link is not opened for new telemetry data arriving.

**Comment by sophokles73** [comment]
My understanding of the log entry is that the sender is still able to publish data via the REST adapter and the REST adapter forwards the message to the Hono server's telemetry endpoint. However, then the downstream adapter fails to forward the message to the dispatch router and closes the link with the REST adapter. 
Is that what's happening?

**Comment by dguggemos** [comment]
Yes, the REST Adapter is able to publish its data, but the link is closed immediately. I think the problem is that Hono Server does not try to open a new sender, but says "no downstream sender for link available".

**Comment by sophokles73** [comment]
I have taken a first look. It seems that `ForwardingDownstreamAdapter` doesn't close the corresponding upstream links when it loses its downstream connection. When a new message arrives frmo the upstream link there is no sender available because these are only created when an upstream link is attached ...

**Comment by sophokles73** [comment]
It is as I suspected. The upstream receivers are not closed when the connection to the downstream sender is lost. I will provide a fix during the afternoon...

**Comment by sophokles73** [comment]
fixed on master a77879897802eff7b944add9a223aa902bcb249b
