### ISSUE TITLE
CertificateExpiredException: NotAfter: Wed Dec 12 16:01:54 CET 2018

### ISSUE THREAD

**Issue by jdeantoni** [eclipse/hono#985]
Hi,

I tried to connect the sandbox for a test but ended up with 

`java.security.cert.CertificateExpiredException: NotAfter: Wed Dec 12 16:01:54 CET 2018` 

could you please regenerate the certificate ?

thanks

**Comment by sophokles73** [comment]
Hi,

thanks for reporting. I will also need to update to Hono 0.9-M1 as well. I'll let you know once I am done ...

**Comment by sophokles73** [comment]
@jdeantoni should be fixed, can you verify and close this issue if it works for you?

**Comment by jdeantoni** [comment]
Works for me ! Thanks a lot !
